gip-inclusion/les-emplois

itou/templates/apply/includes/list_card_body.html, itou/www/apply/views/list_views.py
Even those sent by someone else.
=> Display all applications to a job seeker

itou/templates/content/faq.html
Pour une sémantique plus forte du contenu, il me semble que l'usage de ces balises est plus intéressante.
=> Utilise une liste de description

itou/job_applications/models.py, itou/job_applications/tests.py, itou/templates/403.html, itou/templates/apply/submit_step_check_prev_applications.html, itou/templates/home/home.html, itou/www/apply/tests/tests_submit.py, itou/www/apply/urls.py, itou/www/apply/views/submit_views.py
- Limit the possibility of applying to the same SIAE for 24 hours
- If a candidate is applying to an SIAE where he or she has already applied, ask for a confirmation to apply again
Plus, hide login and subscription links if the user is authenticated on HP.
=> Avoid duplicates in job applications

itou/templates/account/account_inactive.html, itou/www/apply/forms.py
- Add a custom template for users who attempt to login while their account is inactive
- Disable the ability to apply for inactive job seekers
=> Disable the ability to apply for inactive job seekers

itou/static/css/itou.css
=> Ajout d'une marge pour les messages flash

itou/approvals/admin.py, itou/approvals/admin_views.py, itou/job_applications/admin.py, itou/prescribers/admin.py, itou/siaes/admin.py, itou/users/admin.py, itou/utils/address/models.py, itou/utils/widgets.py, itou/www/apply/forms.py, itou/www/apply/views/process_views.py, itou/www/apply/views/submit_views.py, itou/www/dashboard/forms.py, itou/www/dashboard/views.py, itou/www/prescribers_views/forms.py, itou/www/prescribers_views/views.py, itou/www/search/forms.py, itou/www/siaes_views/forms.py, itou/www/siaes_views/views.py, itou/www/signup/forms.py
Je propose d'utiliser `gettext_lazy` toujours de façon explicite.
- https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#lazy-translation
- https://stackoverflow.com/questions/4160770/when-should-i-use-ugettext-lazy
=> Use of gettext and gettext_lazy in a coherent way

itou/templates/apply/includes/job_applications_filters.html, itou/www/apply/forms.py, itou/www/apply/tests/tests_list.py
Les SIAE et les prescripteurs peuvent filtrer les candidatures en renseignant le nom d'un candidat.
=> Ajout d'un filtre au tableau de bord des SIAE et des prescripteurs.

itou/templates/signup/select_siae.html
=> Wording (2)

itou/utils/urls.py, requirements/base.txt
Je vous encourage à lire le changelog :
> https://docs.djangoproject.com/en/dev/releases/3.0/
Et ça aussi :
> https://docs.djangoproject.com/en/dev/ref/models/fields/#field-choices-enum-types
=> Upgrade Django 3

itou/prescribers/migrations/0010_auto_20200311_1404.py, itou/prescribers/models.py, itou/templates/stats/stats.html, itou/www/stats/views.py
Il y a pas mal de catégories à zéro mais je les laisse car cela donne aussi une info utile.
[...]
[...]
=> vgrange/stats_v11 (display stats per prescriber organization kind)

.gitignore, itou/static/js/city_autocomplete_field.js, itou/templates/search/includes/siaes_search_form.html
Réduction du délai d'apparition de la sélection et problème de cleanup du champ de recherche﻿
=> Fix autocompletion sur recherche

itou/static/css/itou.css, itou/templates/home/home.html, itou/templates/layout/base.html
- Ajout d'un bouton dans le header,
- Ajout d'un bloc informatif relié à l'actualité,
- Modification des blocs d'inscription.
(le bandeau "BETA" est décalé sur ma capture d'écran mais il apparaît correctement sur le navigateur)
=> Ajout du forum sur la page d'accueil

itou/templates/layout/base.html
Le lien vers le forum devrait être visible également par les utilisateurs connectés.
=> Modification du header

itou/approvals/models.py, itou/approvals/tests.py, itou/eligibility/admin.py, itou/siaes/migrations/0019_auto_20200210_1626.py, itou/siaes/migrations/0020_auto_20200227_1755.py, itou/users/models.py
> https://sentry.data.gouv.fr/itou/itou-prod-5t/issues/1875895/
=> Fix bug PASS IAE sans diagnostic

itou/templates/search/siaes_search_results.html, itou/www/search/views.py
=> Save SQL queries

config/settings/base.py, itou/cities/factories.py, itou/cities/models.py, itou/prescribers/models.py, itou/siaes/factories.py, itou/siaes/models.py, itou/templates/layout/base.html, itou/templates/search/includes/siaes_search_form.html, itou/templates/signup/select_siae.html, itou/templates/stats/stats.html, itou/utils/perms/user.py, itou/www/apply/views/list_views.py, itou/www/apply/views/submit_views.py, itou/www/approvals_views/views.py, itou/www/autocomplete/views.py, itou/www/dashboard/views.py, itou/www/search/forms.py, itou/www/search/views.py, itou/www/siaes_views/forms.py, itou/www/siaes_views/views.py, itou/www/signup/forms.py, itou/www/signup/tests.py, itou/www/stats/tests.py, itou/www/stats/views.py
=> Open the gates

itou/siaes/management/commands/import_deleted_siae.py, itou/www/apply/views/process_views.py, itou/www/siaes_views/forms.py, itou/www/siaes_views/tests.py, itou/www/siaes_views/urls.py, itou/www/siaes_views/views.py, itou/www/signup/forms.py
3 choses :
- Rendre les fiches entreprises publiques
- Nouveau *help text* avec un exemple de descriptif dans le formulaire de modification de fiche entreprise
- Nouveau message d'embauche
=> COVID-19 - "Operation ETTI"

itou/templates/home/home.html
Changements :
- Modification du lien pour télécharger l'attestation de déplacement,
- ajout d'une croix pour fermer le message.
=> Mise à jour du message d'alerte de la page d'accueil.

itou/templates/apply/email/accept_trigger_approval_body.txt, itou/templates/apply/email/accept_trigger_approval_subject.txt, itou/templates/apply/process_accept.html, itou/templates/apply/process_base.html, itou/templates/dashboard/dashboard.html, itou/templates/home/home.html, itou/templates/layout/base.html
- Remplacement du terme "agrément" par "PASS IAE" à certains endroits.
- Modification de certains liens de la page d'accueil.
=> Boost design

itou/templates/dashboard/dashboard.html, itou/templates/prescribers/members.html, itou/templates/siaes/members.html, itou/www/prescribers_views/tests.py, itou/www/prescribers_views/urls.py, itou/www/prescribers_views/views.py, itou/www/siaes_views/tests.py, itou/www/siaes_views/urls.py, itou/www/siaes_views/views.py
> https://trello.com/c/jQIEtXAS
> https://trello.com/c/M9fxKxHp
=> Display a list of members of SIAE/Prescribers

itou/prescribers/admin.py, itou/siaes/admin.py
Fix pour :
- https://sentry.data.gouv.fr/itou/itou-staging/issues/1877180/
- https://sentry.io/organizations/labonnedreamteam/issues/1614751253/
=> Correction d'un bug admin à la création de Siae/PrescriberOrganization

itou/templates/apply/process_eligibility.html, itou/utils/widgets.py, itou/www/apply/forms.py, itou/www/dashboard/forms.py
- Modification de la date jusqu'à laquelle les critères administratifs sont simplifiés,
- Modification de l'affichage par défaut de la date de naissance.
=> Changements de l'interface

docker/dev/postgres/maintenance/backup
=> Make a second dump in a custom-format archive

itou/job_applications/models.py, itou/job_applications/tests.py, itou/templates/apply/email/cancel_body.txt, itou/templates/apply/email/new_for_job_seeker_body.txt, itou/templates/apply/email/new_for_job_seeker_subject.txt, itou/templates/apply/email/new_for_prescriber_body.txt, itou/templates/apply/email/new_for_prescriber_subject.txt, itou/www/apply/views/submit_views.py
Le prescripteur est en copie de l'e-mail envoyé à un employeur lorsqu'il envoie une nouvelle candidature.
=> Nouvelle notification envoyée au prescripteur par e-mail

.gitignore, config/settings/prod.py
La mise à jour de cette branche déclenche un déploiement automatique de l'application de production chez Clever Cloud.
=> Branche master utilisée par Clever

itou/templates/signup/includes/submit_rgpd.html
Ce message apparaît sur la page de création de compte.
=> Ajout d'un message concernant les données personnelles

itou/templates/prescribers/email/organization_with_no_member_email_body.txt, itou/www/signup/forms.py, itou/www/signup/tests.py
Tout est dans le titre
De l'utilisation de blocktrans avec des objets...
=> Données manquantes dans l'email d'inscription pour les orgas sans membres

itou/approvals/export.py, itou/templates/apply/process_details.html, itou/www/apply/views/process_views.py
Ajouts des champs:
* type de structure
* code postal du demandeur d'emploi
dans l'export XLS des PASS IAE
** + Quick fixes feedback**:
* réorganisation des options lors de l'embauche d'un candidat ("Je l'embauche" en première position)
* suppression d'un message inopportun à la fin du process d'embauche sans PASS IAE
=> Ajout de champs dans l'export des PASS IAE + quick fixes

requirements/base.txt
> https://docs.djangoproject.com/en/3.0/releases/3.0.8/
=> Upgrade to Django 3.0.8

itou/invitations/admin.py
Tout est dans le titre ! :sweat_smile:
=> Visualisation des invitations Prescripteurs dans l'admin

requirements/base.txt, requirements/demo.txt, requirements/dev.txt, requirements/prod.txt, requirements/staging.txt
> https://docs.djangoproject.com/en/3.1/releases/3.1/
=> Mise à jour de Django en version 3.1 et des requirements

Makefile, itou/job_applications/admin.py, itou/job_applications/models.py, itou/job_applications/tests.py, itou/utils/urls.py
Grâce à Zohra, je me suis rendu compte qu'il n'y avait pas de moyen simple de retrouver les PASS IAE à délivrer manuellement en attente dans l'admin.
Cette petite modif fait le job !
=> Pouvoir retrouver facilement les PASS IAE à délivrer manuellement en attente dans l'admin

itou/job_applications/tests.py, itou/prescribers/tests.py, itou/siaes/tests.py, itou/templates/account/email/email_confirmation_subject.txt, itou/templates/account/email/password_reset_key_message.txt, itou/templates/apply/email/accept_body.txt, itou/templates/apply/email/accept_trigger_approval_body.txt, itou/templates/apply/email/approval_number_body.txt, itou/templates/apply/email/approval_number_subject.txt, itou/templates/apply/email/cancel_body.txt, itou/templates/apply/email/new_for_job_seeker_body.txt, itou/templates/apply/email/new_for_job_seeker_subject.txt, itou/templates/apply/email/new_for_prescriber_subject.txt, itou/templates/invitations_views/email/invitation_establishment_body.txt, itou/templates/prescribers/email/new_signup_warning_email_to_existing_members_body.txt, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt, itou/templates/prescribers/email/validated_prescriber_organization_email_body.txt, itou/templates/prescribers/email/validated_prescriber_organization_email_subject.txt, itou/templates/siaes/email/new_signup_activation_email_to_official_contact_body.txt, itou/templates/siaes/email/new_signup_activation_email_to_official_contact_subject.txt, itou/templates/siaes/email/new_signup_warning_email_to_existing_members_body.txt, itou/templates/siaes/email/new_signup_warning_email_to_existing_members_subject.txt, itou/www/signup/tests.py
Suite à la revue de Nathalie, les issues 270 à 293 sont fixées.
Les tests unitaires utilisant le contenu des templates modifiés ont aussi été corrigés.
=> MAJ du contenu des emails 

config/settings/base.py, itou/templates/dashboard/dashboard.html, itou/templates/siaes/create_siae.html, itou/www/dashboard/views.py, itou/www/siaes_views/forms.py, itou/www/siaes_views/views.py
Quelques modifications dans le formulaire de création pour aiguiller vers une invitation/rattachement si nécessaire:
- MAJ dashboard
- MAJ formulaire: messages d'erreurs et infos
Voir carte: https://trello.com/c/h8LLz3UD/931-changer-les-textes-du-formulaire-cr%C3%A9er-une-nouvelle-structure
Et détails ici: https://docs.google.com/document/d/1OAbD1-x3Nr9LWNaz49TzRoIOPBBH9L-8V9jecXHOvN8/edit
=> [BOOST] MAJ des messages info/erreur pour le formulaire de création de structures

itou/templates/siaes/create_siae.html
=> [TYPO] Erreur dans le titre du formulaire de création de  SIAE

itou/approvals/management/commands/import_pe_approvals.py, requirements/base.txt
Le fichier Excel qui nous est fourni varie souvent, notamment au niveau des colonnes. Cette PR permet de récupérer les données en se basant sur le nom des colonnes et non sur leur index.
=> Amélioration du script d'import des agréments

itou/approvals/admin.py, itou/approvals/management/commands/import_pe_approvals.py, itou/approvals/models.py
J'en profite au passage pour ajouter la possibilité de voir et de filtrer les dates des imports dans l'admin :
=> Fix pour le bug des dates de naissances dans le futur des agréments PE

itou/templates/search/siaes_search_results.html
Fix une petite typo :
> https://github.com/betagouv/itou/commit/593fc5bf210a2eb78b8a0c9c8521c34675e8a9aa#diff-fcdefb0949dc5cc8617a9e0eed92fc28R176
=> Fix block.super

requirements/base.txt
> https://docs.djangoproject.com/en/dev/releases/3.1.1/
=> Upgrade to Django 3.1.1

config/settings/base.py, envs/secrets.env.template, itou/external_data/apis/pe_connect.py, itou/external_data/signals.py, itou/external_data/tasks.py, itou/external_data/tests.py, itou/utils/emails.py, requirements/base.txt
Asynchrone avec Huey: https://github.com/coleifer/huey
Nécessite une instance Redis pour tourner (`itou-redis` sur CleverCloud)
Au programme:
* intégration de Huey avec Django
* import de données PE async, mais sans `eventloop` ou `thread`
* envoi des mails en async (backend email wrapper)
Le code est documenté.
=> Async avec Huey

config/settings/base.py, itou/utils/emails.py
Quick fix sur les headers de `EmailMessage`. A investiguer
=> Fixed (tmp) headers issue

itou/templates/dashboard/dashboard.html
=> Do not display the grace period alert to everybody

itou/static/css/itou.css, itou/templates/layout/base.html
=> Nouvelle proposition de footer

itou/www/stats/views.py
=> Stats publiques

itou/job_applications/models.py, itou/templates/apply/process_accept.html, itou/www/apply/forms.py
=> L'employeur ne sait pas qu'une embauche dans le passé est impossible

itou/siaes/admin.py
Cette PR règle un bug lors de la persistance d'une nouvelle SIAE via l'admin.
=> [FIX] Création d'une SIAE via l'admin

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/_import_siae/vue_af.py, itou/siaes/management/commands/_import_siae/vue_structure.py, itou/siaes/management/commands/import_siae.py
Import ASP et amélioration du script import_siae.py
Un import ASP est censé être fait chaque début de semaine, mais exceptionnellement on traite ici trois semaines d'un coup vu que le dernier date du 12 octobre.
Amélioration du script import_siae.py pour gérer plusieurs nouveaux problèmes de données.
Pas de revue attendue.
---
Liens intéressant :
- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- https://gist.github.com/mikepea/863f63d6e37281e329f8
=> Import ASP et amélioration du script import_siae.py

itou/siaes/models.py
Ajout de documentation pour clarifier le modèle SiaeConvention.
Parce que la complexité derrière ce modèle est importante et a donné lieu à pas mal d'échanges dev sur https://github.com/betagouv/itou/issues/466
=> Ajout de documentation pour clarifier le modèle SiaeConvention

requirements/base.txt
Mise à jour vers Django 3.1.4
> https://docs.djangoproject.com/en/3.1/releases/3.1.4/
=> Mise à jour vers Django 3.1.4

CHANGELOG.md
=> Changelog 9

requirements/base.txt
Mise à jour vers Django 3.1.5
> https://docs.djangoproject.com/en/3.1/releases/3.1.5/
=> Mise à jour vers Django 3.1.5

itou/approvals/models.py, itou/templates/apply/process_base.html, itou/templates/approvals/includes/status.html, itou/templates/approvals/suspend.html, itou/templates/approvals/suspension_delete.html, itou/templates/approvals/suspension_update.html, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py
Nouvelle interface permettant de supprimer une suspension.
Une suspension peut avoir été créée par erreur.
=> Ajout de la possibilité de supprimer une suspension

itou/templates/apply/includes/job_applications_filters.html
=> MEP Boost Design

itou/approvals/models.py, itou/asp/models.py, itou/asp/tests.py, itou/job_applications/models.py, itou/prescribers/migrations/0020_auto_20200924_1420.py, itou/prescribers/migrations/0024_auto_20201116_1621.py, itou/siaes/admin.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/_import_siae/vue_af.py, itou/siaes/migrations/0034_auto_20200914_1702.py, itou/siaes/migrations/0035_auto_20200924_1420.py, itou/siaes/migrations/0036_auto_20201006_1755.py, itou/siaes/migrations/0037_auto_20201009_1619.py, itou/siaes/migrations/0040_remove_siaefinancialannex_convention_number.py, itou/siaes/models.py, itou/users/migrations/0012_user_is_reporting.py, itou/utils/emails.py, itou/utils/perms/middleware.py, itou/www/dashboard/forms.py, itou/www/siaes_views/views.py, itou/www/signup/forms.py, itou/www/signup/urls.py, requirements/dev.txt
Mise à jour de certaines dépendances de dev.
Le problème initial concerne le _shell_ Django et `ipython` dont les versions récentes ne fonctionnent pas avec les versions récentes de `jedi` :
> https://github.com/ipython/ipython/issues/12740
Du coup on pin explicitement `jedi==0.17.2` en attendant un fix.
J'en ai profité pour mettre à jour quelques autres dépendances de dev car il faut le faire de temps en temps.
Le fichier principal à review est `requirements/dev.txt`.
Le reste des modifs est simplement le résultat d'un _run_ de la dernière version de black qui a quelques nouvelles règles que je laisse par défaut.
=> Mise à jour de certaines dépendances de dev

CHANGELOG.md
=> [build] 11

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py
Améliorations mineures des scripts d'import GEIQ/SIAE/EA.
A l'occasion d'un nouvel import GEIQ et des imports SIAE/EA hebdos habituels.
Pas besoin imho.
=> Améliorations mineures des scripts d'import GEIQ/SIAE/EA

itou/approvals/admin.py, itou/approvals/export.py, itou/approvals/management/commands/export_approvals.py
- Ajout d'un onglet dans l'export Excel des PASS IAE
- Essais d'amélioration des performances de l'export via l'interface d'admin
- Demande métier (ajout des suspensions)
- Essayer de débloquer l'export via l'interface d'admin (lent et potentiellement menant à une erreur 502)
- Utilisation de `FileResponse` pour le type de réponse plutôt que le type par défaut
=> Export au format Excel des PASS IAE - the revenge 

CHANGELOG.md
Résumé des modifications apportées au projet pour le **build 12** (sprint du 01/02/2021 au 12/02/2021)
=> [build 12] Changelog

CHANGELOG.md
Résumé de notre boulot lors de ce dernier sprint ! 👏 👏 👏
=> Journal du sprint 13

itou/templates/apply/list_for_siae.html, itou/templates/apply/process_base.html
Pour réactiver le téléchargement de PDF
=> Suppression des commentaires dans les tags URL

itou/templates/apply/process_accept.html, itou/templates/apply/submit_step_job_seeker_check_info.html, itou/www/apply/views/process_views.py
Mise en avant du contrat de professionnalisation.
Demande de la DGEFP.
- ajout d'un message informatif dans la modale d'obtention d'un PASS IAE précisant qu'on pourra demander de l'aide a posteriori
- ajout d'un lien vers le site de Pôle emploi sur la page permettant d'obtenir de l'aide
---
Au passage, rétablissement de l'affichage des erreurs d'un formulaire.
=> Mise en avant du contrat de professionnalisation

.github/workflows/ci.yml, Makefile, config/settings/base.py, docker/dev/django/Dockerfile, requirements/base.txt, requirements/demo.txt, requirements/dev.txt, requirements/prod.txt, requirements/staging.txt
Mise à jour de Python en version 3.9.
Parce qu'on le vaut bien.
=> Mise à jour de Python en version 3.9

itou/templates/layout/base.html
Cette PR/issue ajoute la mention "Accessibilité : non conforme" à votre footer.
La mention "Accessibilité : non conforme" est obligatoire pour les sites du service public et réellement utile pour les personnes en situation de handicap.
En tant que site faisant partie du service public, nous avons un certain nombre d'obligation. 
L'une d'elle est la [**transparence du niveau d'accessibilité de votre site**](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#mention-obligatoire-sur-la-page-daccueil). 
Pour cela, il faut afficher le niveau de conformité dans le footer :
Tant que le niveau de conformité est inconnu, il est considéré comme **non conforme**.
Après avoir effectué un audit, on peut afficher : 
- Accessibilité : non conforme : score inférieur à 50 %.
- …
=> Mentionne le niveau d'accessibilité dans le footer

CHANGELOG.md
Le journal des modifications n°15 en bon français.
=> Changelog 15

itou/www/apply/views/process_views.py
Affichage d'un message d'erreur à l'utilisateur plutôt qu'une erreur 500 en cas de `InvalidTransitionError`.
Pour être aimable avec les utilisateurs et calmer Sentry sur les transitions en erreur :
> https://sentry.io/organizations/itou/issues/?project=5671910&query=is%3Aunresolved+InvalidTransitionError
Quelques double `save()` retirés au passage.
=> Gestion aimable pour l'utilisateur des `InvalidTransitionError`

itou/approvals/export.py
https://bugs.python.org/issue31803
=> Fix use of deprecated time.clock()

itou/approvals/export.py
https://bugs.python.org/issue31803
=> Fix use of deprecated time.clock() (bis)

itou/metabase/management/commands/_database_sqlalchemy.py, itou/metabase/management/commands/_job_descriptions.py, itou/metabase/management/commands/_missions_ai_ehpad.py, itou/metabase/management/commands/populate_metabase.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/siaes/management/commands/_import_siae/utils.py
Améliorations diverses des scripts metabase.
Tickets :
https://trello.com/c/gJj14OsV/1624-r%C3%A9duire-lindisponibilit%C3%A9-pendant-une-mise-%C3%A0-jour-fluxiae-metabase
https://trello.com/c/IgLb09zI/1625-c2-injecter-les-28-r%C3%A9f%C3%A9rentiels-fluxiae-dans-metabase => 🙏  svp reviewez aussi la PR du repo privée https://github.com/betagouv/itou-private/pull/27
https://trello.com/c/DZiS4nEY/1574-c2-op%C3%A9-ai-ehpad-affiner-les-codes-%C3%A0-identifier-dans-le-champ-description
https://trello.com/c/7ollbhM9/1582-c2-op%C3%A9-ai-ehpad-ajouter-le-code-aiph-dans-le-champ-description
https://trello.com/c/l1RuzZFS/1629-ajouter-la-colonne-nombre-de-candidature-par-fiche-de-poste-dans-la-table-fiches-de-poste
A la demande de Pierre, Soumia et Zohra.
Je conseille de la faire commit par commit.
🙏 …
=> Améliorations diverses des scripts metabase

requirements/base.txt
https://www.djangoproject.com/weblog/2021/apr/06/security-releases/
Je ne suis pas sûr que cette faille pose un problème pour nous mais dans le doute...
=> Upgrade to Django v3.1.8

CHANGELOG.md
Tout beau, tout frais, ~tout bogué~ c'est le nouveau build !
Vos contributions sont bien présentes et bien décrites, c'est à vous de me le dire...
=> [build] 16

CHANGELOG.md
Le titre et la description sont en français et au format texte.
- etc.
---
Liens intéressant :
- https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/
- …
=> Mise à jour changelog itération 17

.editorconfig
Ajout d’un [`.editorconfig`](https://editorconfig.org/) au projet. Ca permet, si vous utililisez [un éditeur compatible](https://editorconfig.org/#pre-installed) ou un plugin (vim, sublime text…), d’avoir le bon format pour les tabulations, les commentaires… et plus généralement pour des trucs pas traités par le linter.
Ça ne s’intègre pas comme linter, mais lors du développement. Lorsqu’on modifie un fichier concerné, l’éditeur va mettre à jour le fichier pour coller à ce style.
C’est complémentaire d’un linter, cela traite tous les fichiers, pas que les .py.
Pour éviter d’en discuter ;)
Le cas est arrivé dans une PR ou j’ai oublié un retour à la ligne à la fin du fichier.
Je n’ai traité que les formats principaux du projet, ce qui me parait suffisant dans un premier temps.
```bash
$ …
```
=> Ajout d’un fichier .editorconfig

config/settings/dev.py.template
- Éviter la validation du mot de passe en DEV
- Logger les requêtes SQL dans la console en  DEV
=> Mise à jour du template des settings de DEV

itou/job_applications/models.py, itou/templates/home/home.html, itou/templates/layout/base.html, itou/templates/releases/list.html, itou/www/apply/forms.py, itou/www/apply/tests/tests_process.py
- Les liens "Besoin d'aide" de la page d'accueil pointent désormais vers le portail assistance
- On borne la date de fin d'embauche à la durée maximum d'un PASS IAE ou le temps restant d'un PASS IAE déjà existant
- Nouveau texte sur la HP à la demande du MDI
=> Boost design 2

itou/approvals/admin_forms.py, itou/templates/approvals/includes/status.html
We speek English in code, isn't it?
Some developers are obstinate.
=> Pardon my French

requirements/base.txt
Mise à jour vers Django 3.2.3
> https://docs.djangoproject.com/en/3.2/releases/3.2.3/
=> Mise à jour vers Django 3.2.3

requirements/demo.txt, requirements/prod.txt, requirements/staging.txt
Mise à jour 1.1.0 du SDK Sentry.
=> Mise à jour 1.1.0 du SDK Sentry

CHANGELOG.md
Le journal des modifications numéro 19.
Parce que c'est comme ça.
En écrivant un mot derrière l'autre.
Ce sprint va durer 4 semaines, mais je le rédige au fur et à mesure.
=> Journal des modifications 19

config/settings/prod.py
Élément nécessaire pour éviter les 400 ;)
=> added forum.inclusion.beta.gouv.fr to ALLOWED_HOSTS

envs/README.md
Ajoute un fichier `README.md` qui documentare le chargement automatique des variables d'environnement lors de l'activation du virtualenv.
Pour faciliter la vie des devs.
En utilisant un crochet d'activation virtualenv.
=> Note pour charger automatiquement les variables d'environnement avec virtualenv

CHANGELOG.md
Comme son nom l'indique.
Pour communiquer au monde notre génie.
En listant point par point nos avancées.
=> Journal des changements version 20

itou/siaes/management/commands/_import_siae/convention.py
Désactivation finale des 2.5% des conventions (100 sur 4000) qui n'ont toujours pas d'AF 2021 à ce jour.
En deux parties :
- https://github.com/betagouv/itou/pull/726 pour la désactivation en question
- https://github.com/betagouv/itou-private/pull/57 pour la documentation
Par définition une siae est conventionnée si et seulement sa convention a au moins une AF valide à ce jour.
Le 1er janvier 2021 on s'est rendu qu'on compte que 0% (!) des siaes avaient une AF 2021, du coup en théorie on aurait du déconventionner 100% des siaes. Bien sûr on a mis en place une exception pour donner le bénéfice du doute à toutes les conventions en supposant que leur AF 2021 finirait par arriver, même très en retard.
Le ratio est progressivement monté de 0% en janvier à 98% aujourd'hui. Il est temps de …
=> Désactivation des conventions sans AF 2021 [sera MEP le 28 juin]

itou/siaes/management/commands/_import_siae/convention.py
Respect des réactivations de convention par le support pendant 90 jours au lieu d'une semaine.
Parfois les données ASP sont en retard et affirment qu'une structure n'est pas conventionnée. La structure contacte le support, fournit les preuves de son conventionnemenent, et le support réactive manuellement la convention correspondante.
Avant cette PR : la convention était désactivée au prochain import SIAE (donc une semaine plus tard environ) si les nouvelles données ASP considéraient toujours la structure comme non conventionnée.
Après cette PR : la réactivation manuelle du support reste en place 90 jours. Au dela, le prochain import SIAE reprend la main.
Du support (Sarah et Pierre M).
=> Respect des réactivations de convention par le support pendant 90 jours au lieu d'une semaine

clevercloud/sync_employee_records.sh
Pas de revue nécessaire.
Probablement ma plus courte PR :)
=> Dumbfix of shebang

requirements/demo.txt, requirements/prod.txt, requirements/staging.txt
MAJ de sentry SDK de la version 1.1.0 vers 1.3.0
=> MAJ sentry SDK

CHANGELOG.md
=> Changelog #22

requirements/base.txt, requirements/demo.txt, requirements/deploy.txt, requirements/dev.txt, requirements/prod.txt, requirements/staging.txt
Utilisation de versions plus récentes de l'ensemble de nos dépendances.
Il reste quelques versions qui nécessitent une review plus détaillée de l'impact concernant Bootstrap/UI.
Pour bénéficier des correctifs des applications tierces.
En modifiant les numéros de version dans les fichiers requirements.
Factorisation des fichiers de déploiement.
En lisant les changelogs des différentes dépendances, je n'ai pas vu de nouveautés qui nécessitaient de modifier notre code.
=> Mise à jour des dépendances

itou/metabase/management/commands/_database_sqlalchemy.py, itou/metabase/management/commands/_dataframes.py, itou/metabase/management/commands/_job_applications.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/import_geiq.py, itou/siaes/management/commands/import_siae.py, requirements/base.txt
Au menu :
- Amélioration du script le plus lourd (fluxIAE) qui fera maintenant 5 tentatives à chaque table, comme ça on devrait mieux gérer les déconnexions aléatoires par le serveur.
- Prévention des injections SQL.
- Upgrade de dépendances (sqlalchemy, xlrd)
- Et quelques broutilles
Parce que Supportix ça se respecte !
=> Améliorations variées des scripts Supportix

CHANGELOG.md
On a bien bossé ! Autant le montrer !
La communication, c'est aussi pour les devs.
En listant point par point nos tickets.
=> Journal des modifications 24

itou/www/apply/views/process_views.py
Simplification du message d'information qui apparaît lors de l'acceptation d'une candidature.
Avant : 
Après :
=> Correction d'un message informatif

itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
Mise à jour du script pour rajouter l'opération AI,ETTI restauration
Une opération restauration a commencé le 01/07/2021
=> Opération restauration

.github/pull_request_template.md
Simplification du template des PR.
Pour s'épargner des manipulations qu'on est obligés de faire systématiquement à la main à chaque fois et qui n'apportent plus de valeur à cet endroit.
=> Simplification du template des PR

.pre-commit-config.yaml
Ajout de Flake8 dans le script et mise à jour des versions.
Afin de rester cohérent avec le Makefile.
=> Mise à jour du script « pre-commit »

CHANGELOG.md
Relecture et ajouts "à vot'bon cœur !"
Validation et merge vendredi soir
=> Journal des modifications / release 26

.github/workflows/review-app-creation.yml, config/settings/prod.py, config/settings/review_apps.py, envs/secrets.env.template, requirements/deploy.txt
Ajout du module de mesure de performance d'Elastic
Pour suivre les performances de l'application
En activant l'application 'elastic-apm' et le middleware pour activer les traces
=> Mesure de performance avec Elastic

CHANGELOG.md
Résumé des changements du sprint 27
Parce qu'on a bien bossé !
=> Journal du sprint 27

itou/metabase/management/commands/sql/002_missions_ai_ehpad.sql
Mise à jour du script permettant de mettre à jour le tableau de bord AI-ETTI opérations en remplaçant les colonnes 'ITOU%' par des colonnes équivalentes des tables flux IAE
Eviter d'utiliser des sources de données différentes (données de la plateforme + données de l'asp)  pour alimenter un même tableau de bord
=> Mise à jour du script AI-ETTI opérations

itou/employee_record/models.py, itou/employee_record/serializers.py
FIX 2: 
- type orienteur again : quelque chose de pourri sur ce truc
Traitement des retours d'intégration ASP / cas limites ou nouveau
Vite
- plusieurs PR du style à prévoir aujourd'hui
- la plupart du temps sans revue (mais les tests sont toujours ok !)
=> FIX intégration fiches salarié 2

itou/metabase/management/commands/populate_metabase_itou.py
Résolution d'une 500 dans le cron Metabase quotidien.
Avec nos données qui grandissent, un gros queryset a fini par provoquer une `psycopg2.errors.DiskFull`.
En paginant le queryset en question.
Le fait qu'une grosse lecture PG sans écriture puisse causer une erreur `DiskFull` m'a beaucoup surpris. J'ai cru à tort au début que l'erreur se produisait dans le PG Metabase où on écrit les nouvelles tables, avant de me rendre compte de mon erreur. L'erreur est bien dans le PG local et causée par une lecture sans écriture.
=> Résolution d'une 500 dans le cron Metabase quotidien

CHANGELOG.md
=> Journal des modifications 28

config/settings/base.py
Clarification de doc pour paramètres d’API
la différence recette/prod ne saute pas au visage actuellement
=> Clarification de la documentation des paramètres d’API PE

CHANGELOG.md
Ajout des évolutions du sprint 30 au [journal des modifications](https://github.com/betagouv/itou/blob/c60f947395fa872fc141bd9c2862e35bab84b29c/CHANGELOG.md).
Pour maintenir un historique des évolutions de l'application.
Parcours des `Pull request` mergé sur master depuis le début du sprint.
Utilisation des filtres Github en utilisant la requête suivante : 
[`is:pr  merged:>2021-10-25 `](https://github.com/betagouv/itou/pulls?q=is%3Apr++merged%3A%3E2021-10-25+)
=> Ajout des évolutions du sprint 30 au journal des modifications

requirements/base.txt
[Mise à jour vers Django 3.2.9](https://docs.djangoproject.com/en/3.2/releases/3.2.9/).
=> Mise à jour vers Django 3.2.9

CHANGELOG.md
Des ajouts, des modifications et une suppression.
Communiquer au monde — que dis-je, à l'univers ! — les changements apportés au projet.
Mise à jour du Journal.
=> Journal des modifications n° 31

config/settings/base.py, itou/templates/home/home.html, itou/templates/layout/_header.html, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt
Mises à jour diverses de l'interface.
Des liens sont cassés.
Mise à jour des textes par le métier. :raised_hands:
=> Modification des liens vers la Communauté

itou/users/management/commands/import_ai_employees.py
L'ASP nous a fourni un fichier avec les dates de contrat, des données sur les candidats ainsi que les entreprises concernées. Ce script trouve, ou crée le cas échéant, des utilisateurs, des PASS IAE et des candidatures.
Les AI ont désormais besoin d'un PASS IAE pour recruter. Nous devons intégrer dans notre base les employés actuels et leur délivrer un PASS IAE. 
Ajout d'une _management command_ qui parcourt un fichier, le traite et fournit en retour un CSV à envoyer à l'ASP.
Nous pourrions mettre à jour le NIR des candidats trouvés mais il faudrait s'assurer que les informations personnelles concordent. Nous le ferons probablement dans une autre PR.
=> Reprise de stock des AI

itou/users/management/commands/import_ai_employees.py
Le script génère des IntegrityErrors.
=> Correction d'un bug à la délivrance des PASS IAE pour les AI

itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_prolongation.py
Le motif de prolongation d'un PASS IAE "contexte sanitaire" ne doit plus être affiché à partir du 1er décembre 2021. 
Conformément à la loi n°2020-734 du 17 juin 2020
Suppression du motif dans le formulaire de prolongation. Il est conservé en base de données pour garder l'historique.
Attention : la PR ne doit pas être passée en production avec le 1er décembre.
=> Le motif de prolongation "Contexte sanitaire" doit disparaitre le 1er décembre 2021

CHANGELOG.md
Lien direct vers l'aperçu : https://github.com/betagouv/itou/blob/vgrange/changelog/CHANGELOG.md
=> Journal du sprint 32

requirements/deploy.txt
Mise à jour d'Elastic APM
Issue :
https://github.com/elastic/apm-agent-python/issues/1422
Mise à jour du paquet Python
=> Mise à jour d'Elastic APM suite à des erreurs avec httpx

itou/templates/apply/submit_step_check_job_seeker_nir.html
Message d'information pour éviter des effets de bord
Pour éviter que des candidatures soient annulées.
=> Ajout d'un message d'information pour les AI

itou/metabase/management/commands/sql/010_sorties.sql
Création d'une table pour suivre les catégories de sortie(sortie positive, sortie durable...)
Les DDETS souhaitent suivre les sorties pour chaque structure/conventionnement
=> Suivi des sorties

config/settings/base.py, config/settings/test.py, itou/api/siae_api/tests.py, itou/approvals/tests.py, itou/employee_record/tests.py, itou/utils/tests.py, itou/www/apply/tests/tests_submit.py, requirements/base.txt, requirements/deploy.txt, requirements/dev.txt
Mise à jour vers Django 4.0.
> https://docs.djangoproject.com/en/4.0/releases/4.0/
> https://docs.djangoproject.com/en/4.0/howto/upgrade-version/
Actions effectuées :
- Suppression de `pytz` car `zoneinfo` le remplace (c.f. _changelog_)
- Mise à jour de **toutes** les dépendances du projet
- Mise à jour de Django vers la version 4.0
- Correction des `DeprecationWarning` affichés par `python -Wa manage.py test`
- Correction des tests unitaires relatifs à `SessionMiddleware` (suite à [cette modification](https://github.com/django/django/pull/11828))
=> Mise à jour vers Django 4.0

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/signup/job_seeker_nir.html
Correction du lien "Le numéro de sécurité sociale".
Ajout d'un attribut HTML `title` au passage.
L'ancien n'était pas le bon.
=> Correction du lien "Le numéro de sécurité sociale"

itou/users/management/commands/import_ai_employees.py, itou/users/tests/test_management_commands.py
Le script cassait si une ValidationError était levée. Je propose de continuer la boucle et de logger ces erreurs pour les déboguer ultérieurement.
=> Import AI : continuer la boucle malgré les erreurs

itou/templates/dashboard/dashboard.html
Limitation du message d'information au AI
Le message apparaît pour tout le monde.
Renommage de la variable.
=> Limitation du message d'information

itou/metabase/management/commands/sql/012_annexes_financieres.sql
Suivre les conventionnements des structures pour l'année n en se basant sur les annexes financières de l'année n-1
Construire un tableau de bord pour suivre à chaque début d'année les conventionnements des structures
=> Suivi des annexes financières 

CHANGELOG.md
Lien direct vers l'aperçu : https://github.com/betagouv/itou/blob/vgrange/changelog/CHANGELOG.md
=> Journal du sprint 33

itou/metabase/management/commands/sql/012_annexes_financieres.sql
Correction du nom de la table à partir de laquelle il faut récupérer les annexes financières 
Cohérence des nouvelles données AF 2022
=> MAJ du suivi des annexes financières 2022

itou/metabase/management/commands/sql/007_suivi_consommation_etp.sql
Améliorations apportées au script qui alimente le tableau de bord metabase sur le suivi de la consommation des ETP
=> MAJ du suivi de la consommation des ETP

itou/metabase/management/commands/sql/008_saisies_mensuelles.sql
Une table agrégée et sécurisée avec un certain nombre de données retravaillées qui proviennent des saisies mensuelles des structures dans l'extranet asp
- Gagner en réactivité face au demandes ponctuelles de chiffrages
- Gagner en temps de traitement au niveau des TDB et ne plus faire de jointure dans Metabase
=> Table agrégée des saisies mensuelles des structures dans l'asp

CHANGELOG.md
Rédaction du changelong du sprint 34
=> Changelog sprint 34

Makefile, README.md, scripts/deploy_prod.sh
Première PR pour tenter d'améliorer une ou deux petites choses que j'ai vues de ci, de là.
- Pour être un peu plus précis dans le texte du README (et à jour)
- Pour éviter tout merge non désiré lors des déploiements en prod (bien que peu probable sauf si certain.es bossent sur master)
- Amélioration légère du Makefile (ne pas générer de PNG, plus de lisibilité)
Trop petit pour vraiment être décrit ici.
=> Petites améliorations de doc, script, makefile

CHANGELOG.md
=> Modification du changelog - release 35

itou/metabase/management/commands/sql/012_annexes_financieres.sql
MAJ du script des annexes financières 
Limiter le nombre de lignes retournés : une ligne par  structure avec annexe financière 2022 valide
=> Suvi des annexes financières 2022

config/settings/base.py, config/settings/demo.py, config/settings/prod.py, config/settings/review_apps.py, config/settings/staging.py
Mise à jour de l'adresse Email de Contact
L'adresse email `assistance@inclusion.beta.gouv.fr` est remplacée par `assistance@inclusion.beta.gouv.fr`
Mise à jour de la valeur dans `base.py` et dans `prod.py`
=> [URGENT] Mise à jour `ITOU_EMAIL_CONTACT` contact@ > assistance@

itou/metabase/management/commands/sql/014_nombre_etp_conventionnes.sql
Suivre le nombre d'ETP conventionnés par département/région
Dresser un comparatif entre département et région de France
=> Carte de France avec le nombre d'etp conventionnés en IAE

CHANGELOG.md
Mise à jour du changelog - sprint 36
=> Modification du changelog - release 36

CHANGELOG.md
C’est un peu galère quand il y a beaucoup de PRs, donc pour les prochains, à défaut de mieux je conseille d’utiliser [github CLI](https://github.com/cli/cli):
```
gh pr list --search="sort:updated-desc is:closed" --limit 50
```
Ensuite:
- jouer sur le paramètre limit pour retrouver le changelog précédent
- virer les PRs closes mais pas mergées
- il faut encore mettre les PR dans les bonnes catégories et retravailler un peu les titres
=> Changelog #37

itou/siaes/management/commands/move_siae_data.py
Migration des données d'une SIAE à une autre. Cas de la migration 'toutes données'
exemple : `django-admin move_siae_data --from 9789 --to 10574 --dry-run`
Le modèle de données contient une contrainte d'unicité sur les fiches de poste (Job Description) : 
- Il ne peut y avoir qu'une seule fiche de poste pour une SIAE et une Appellation.
- Une fiche de poste peut exister avec la même Appellations dans les 2 SIAE.
Lors de la migration "toutes données" : 
- les fiches de poste sont détachées de la SIAE d'origine (from_siae) pour être rattachées à la SIAE de destination (to_siae)
- le lien entre les candidatures (Job Application) et les fiches de poste restent inchangé
- les candidatures sont rattachées à la SIAE de destination
Les fiches de postes qui ne respectent pas la règle d'unicité ne …
=> Migration de toutes les données d'une SIAE - gestion des candidatures liées à des fiches de poste en doublon

itou/job_applications/models.py
Évite de faire des appels à l’API pole emploi lorsqu'une info clé, l’identifiant chiffré fourni par PE, est manquant
Envoyer des identifiants chiffrés vides fait planter l’API PE.
Meilleure gestion des erreurs. L’erreur de déchiffrement de l’api de mise à jour est remplacée par la cause racine, les candidats non trouvés
=> Correction de l’erreur de déchiffrement lors des appels à l’API PE

itou/templates/apply/includes/job_applications_filters.html, itou/templates/layout/content_small.html, itou/templates/search/includes/siaes_search_filters.html, itou/templates/siaes/card.html, itou/templates/siaes/edit_siae_preview.html, itou/templates/siaes/includes/_configure_jobs_list.html, itou/templates/siaes/includes/_list_siae_jobs.html
Corrections de quelques erreurs de formatage ou de structure du dom
Pour finaliser les corrections sur les 10 pages de l'audit d'accessibilité
En passant les pages dans le validateur w3c et en fixant les errors
=> Corrections de quelques erreurs de formatage ou de structure du dom

requirements/base.txt, scripts/imports-asp.sh
- Mise à jour de Django
- Redirection de la sortie des scripts d'imports ASP
- Pour être toujours à la pointe ! et en sécurité 😎
- Avoir un historique des exécutions
- Mise à jour de la dépendance Django
- Écriture de la sortie dans le bucket partagé
=> Boostdev du sprint 38

itou/job_applications/tests.py, itou/templates/apply/email/new_for_siae_body.txt, itou/templates/dashboard/dashboard.html, itou/templates/dashboard/edit_user_notifications.html, itou/templates/layout/_nav_btn_items.html, itou/www/dashboard/tests.py, itou/www/dashboard/urls.py, itou/www/dashboard/views.py, itou/www/employee_record_views/urls.py, itou/www/employee_record_views/views.py
- Modifier l'affichage de la mention "préférences"
- Afficher le nb de fiches salarié à traiter sur la dashboard
Détaillé dans les tickets afférents.
Avec du wording et des balises HTML :)
=> Boostdev sprint 38 [preferences, pylint,  nb FS a traiter]

itou/siaes/admin.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/import_siae.py, scripts/create-fast-machine.sh
Améliorations mineures de l'import des SIAE.
Voir le détail commit par commit.
A l'occasion de mon passage sur l'import ASP de ce sprint 28 - semaine 10.
=> Améliorations mineures de l'import des SIAE.

itou/templates/layout/_footer.html, itou/templates/static/accessibility.html
Correction des erreurs a11y sur les formulaires.
Mise a jour de la page d'accessibilité et du % de conformité (74% 🥳)
Pour mettre en conformité le site avec les règles d'accessibilité et respecter les recommandations de l'audit.
=> Correction des erreurs a11y sur les formulaires

itou/www/dashboard/tests.py, itou/www/dashboard/views.py
Corriger le dysfonctionnement remonté par Eric.
J'etais persuadé qu'il fallait remonter le lombre d'erreurs toutes SIAEs confondues.
En fait il ne faut pas.
En corrigeant.
=> dashboard: Fix the displayed number of FS in error

CHANGELOG.md
Liste des changements effectués durant le sprint 38.
=> Changelog #38

itou/metabase/management/commands/sql/015_taux_transformation_prescripteurs.sql
Table qui alimente le tableau de bord taux de transformation des prescripteurs habilités
Amélioration des filtres
=> Taux de transformation des prescripteurs habilités

CHANGELOG.md
Pas de description particulière.
=> Ajout du changelog pour le sprint 39

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests.py, itou/job_applications/admin.py, itou/siaes/admin.py, itou/siaes/management/commands/move_siae_data.py, itou/siaes/models.py, itou/siaes/tests/tests_models.py, itou/templates/siaes/includes/_list_siae_actives_jobs.html, itou/templates/signup/siae_select.html
Ensemble de tickets boost.
Chaque commit est assez différent mais remplit un objectif précis, cf la liste de commits.
Pour tout le monde <3
Cf les commits, ça dépend !
Il y a une recette jetable.
=> BOOST Sprint 39

itou/metabase/management/commands/sql/008_saisies_mensuelles_iae.sql
Ajout de la variable de la variable RQTH (Reconnaissance de la qualité de travailleur handicapé)
Ajouter le filtre RQTH dans le tableau de bord statistiques des employeurs
=> Saisies mensuelles  dans l'asp

itou/static/css/itou.css, itou/templates/siaes/includes/_list_siae_actives_jobs.html, itou/templates/siaes/includes/_list_siae_jobs.html
Correction de l'affichage de l'icône de réduction.
L'icône a disparu après des corrections sur la structure HTML pour l'accessibilité.
L'affichage de l'icône est géré en ciblant la balise `span` de classe `h5`.
=> Restauration de l'icône du curseur de réduction

itou/metabase/management/commands/sql/008_saisies_mensuelles_iae.sql
Recoder des modalités du filtre QPV
Correction des valeurs prises par le filtre QPV
=> Correction des valeurs du filtre QPV

itou/siaes/management/commands/import_siae.py, itou/siaes/tests/tests_import_siae_command.py
Une amélioration d performances.
`Method check_whether_signup_is_possible_for_all_siaes took 476.42 seconds to complete`
Avec un ou deux prefetch related bien sentis, l'inversion d'une condition, un filtre efficace.
On passe de 6 à une seule requête.
En prod:
`Method check_whether_signup_is_possible_for_all_siaes took 0.01 seconds to complete`
:ok_hand:
=> import_siae: Améliorer la performance d'une vérification un peu lente

itou/siaes/tests/tests_import_siae_command.py
=> import_siae_command: Fix a flaky test on CI

CHANGELOG.md
Changelog.
On fait ça a chaque sprint.
En mettant ce qui a changé.
=> Edit changelog for sprint 40

CHANGELOG.md
Comme tous les fin de sprint pour le C1.
En reprenant les titres des PR fusionnées :)
=> Changelog: release 41

itou/api/employee_record_api/tests.py, itou/api/employee_record_api/viewsets.py
Ajout de 2 champs de recherche portant sur la date de création de la fiche salarié.
Demande utilisateur.
Ajout des champs paramètres de requêtes (chainables) : 
- `created` : liste à une date donnée,
- `since` : liste depuis une date donnée.
Plus : 
- documentation API
- tests
=> Ajout de champs de recherche pour l'API fiches salarié

itou/templates/dashboard/dashboard.html
Message d'information sur la mise en place de l'assistance technique par téléphone pour les prescripteurs et les candidats
Pour informer les prescripteurs et les candidats du lancement de l'assistance technique par téléphone. 
Ajout d'une bannière sur le tableau de bord des prescripteurs et des candidats
=> Message d'information sur la mise en place de l'assistance technique par téléphone

itou/templates/apply/process_eligibility.html
- Correction de la mise en forme d'une alert dans le "process eligibility"
Pour répondre a cette demande de fix
- https://www.notion.so/C1-Alert-large-9ab6de77f5ed46c8858c6f5370b71243
Voir Avant/Apres dans les cartes Notion
=> Correction front de l'alerte process eligibility

itou/static/css/itou.css, itou/templates/account/login_generic.html, itou/templates/account/login_job_seeker.html, itou/templates/apply/submit_base_two_columns.html, itou/templates/layout/content_two_columns.html, itou/templates/signup/job_seeker_nir.html, itou/templates/signup/job_seeker_signup.html, itou/templates/signup/job_seeker_situation.html
- Correction de la mise en forme du layout "content_two_columns.html" et ajustement des templates l'utilisant
Pour répondre a cette demande de fix
- https://www.notion.so/Corriger-le-layout-de-certaines-pages-de-connexion-cr-ation-de-compte-b04f2e0a7fcf4c99bb3ce7fedbf89a45
Voir Avant/Apres dans la carte Notion
=> Quelques ajustements frontend

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/_import_siae/vue_structure.py, itou/siaes/management/commands/import_siae.py
Hotfix de edge cases dans l'import SIAE.
Edge cases pénibles avec le tout dernier fichier.
Je merge sans review pour avancer vite sur ce hotfix, mais une revue a posteriori est la bienvenue.
=> Hotfix import_siae

itou/approvals/models.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Faire en sorte que les demandes de PASS IAE échouent moins en erreur 500 pour nos utilisateurs, en leur affichant une erreur plus compréhensible.
Il semblerait que certains utilisateurs soient parfois créés en doublon, par exemple:
- utilisateur "Lison" avec `pole_emploi_id=foobar` pour lequel on a créé un PASS IAE.
- utilisateur "Lisa"  avec le même `pole_emploi_id=foobar`,  pour lequel on va à nouveau tenter la création d'un PASS IAE. Erreur 500. Pas forcément avec le meme prescipteur ni la meme SIAE, d'aileurs.
Les raisons d'existence de ces utilisateurs en "double" sont probablement justifiées: oubli de mot de passe, typo, ...
Toujours est-il que la recherche d'agrément PE va retrouver un agrément concernant le même NIR ou Pole Emploi ID; ce dernier ayant déjà fait l'objet d'une …
=> Eviter un crash lorsqu'un PASS IAE existe déjà pour le meme NIR ou ID Pole Emploi

itou/templates/layout/_header.html, itou/templates/layout/_nav_btn_items.html
Affichage du nom de la structure dans l'entête.
Pour améliorer la visibilité de la structure et éviter les erreurs de validation de candidatures sur la mauvaise structure. 
Affiche du nom de la structure directement dans le bouton.
=> Améliorer la visibilité de la structure dans l'entête

itou/static/css/itou.css, itou/templates/welcoming_tour/job_seeker.html, itou/templates/welcoming_tour/prescriber.html, itou/templates/welcoming_tour/siae_staff.html
Correction du comportement responsif des welcoming_tour.
En passant, correction de quelques erreurs d'accessibilité et quelques petits ajustements ux.
Pour répondre a ce ticket 
https://www.notion.so/Corriger-les-welcome-tour-sur-la-version-mobile-67cbb0b24d414f7fb6d1ea1453fc050e
=> Correction du comportement responsif des welcoming_tour

itou/api/employee_record_api/viewsets.py
Optimisation SQL pour l'API fiches salarié.
Performances à la ramasse sur l'accès aux listes de fiches salarié.
En analysant la requête SQL, on s'aperçoit qu'une sous-requête imbriquée faisait exploser l'explain plan.
Plutôt qu'une sous requête, une liste fixe d'IDs de SIAEs pré-calculée renvoie le tout dans le domaine du raisonnable.
Voir le diff pour les détails, mais convertir le `QuerySet` ramenant les SIAEs de l'utilisateur en une liste d'IDs fait le job.
A noter que cette partie fera peut-être l'objet d'une modification. 
Je ne retrouve pas la demande métier / utilisateur originelle pour permettre de lister les fiches salariés de TOUTES les SIAEs dont l’utilisateur est admin.
Il faudrait plutôt créer un utilisateur dédié API pour chaque SIAE, avec des droits admin.
Pas de revue …
=> HOTFIX : optimisation de la requête SQL de récupération de liste pour l'API fiche salarié 

itou/metabase/management/commands/sql/017_fiches_deposte_en_tension_recrutement.sql
Parmi les fiches de poste en difficulté de recrutement calculer nombre de fiches de poste n'ayant jamais reçu de candidatures 
Besoin remonté lors du groupe de travail PE
=> Nombre de fiches de poste n'ayant jamais reçu de candidatures 

clevercloud/cron.json
Réparation du fichier de CRON clever.
Parce que c'est dimanche, que j'ai pris la confiance et que je suis allé trop vite pour pousser cet modif en PROD.
Syntaxe correcte du fichier de CRON
=> HOTFIX: fix fichier CRON file

itou/metabase/management/commands/sql/019_candidatures_echelle_locale
Ajout d'informations afin d'avoir des filtres à l'échelle locale
Jointure entre la table candidatures + structures + sa zones infra départementales
=> Table contenant infos sur epci et bassin d'emplois

CHANGELOG.md, itou/siaes/management/commands/_import_siae/vue_af.py, itou/templates/apply/process_cancel.html, itou/templates/approvals/printable_approval.html, itou/templates/employee_record/includes/list_item.html, itou/templates/siaes/includes/_siae_info.html, itou/templates/siaes/job_description_card.html, itou/templates/signup/siae_select.html, itou/www/apply/tests/tests_process.py, itou/www/approvals_views/tests/test_display.py, itou/www/employee_record_views/tests/test_list.py, itou/www/signup/tests/test_siae.py, requirements/base.txt, scripts/imports-asp.sh
De multiples boost, mais aussi (surtout ?) une amélioration pour le script d'import des fichiers ASP.
> Se donner du mal pour les petites choses, c'est parvenir aux grandes, avec le temps.
Soit les commits sont simple, soit c'est (normalement) mentionné dans le commit.
=> [Supportix] Sprint 43

itou/metabase/management/commands/sql/020_delai_1ere_candidature_embauche.sql
Calculer le délai entre la première candidature et la première embauche pour les candidats orientés par PE
Besoin remonté lors du groupe de travail PE
=> Délai entre première candidature et la première embauche 

itou/templates/dashboard/dashboard.html
cf titre
demande métier
mise à jour du template
=> Supprimer le message d’info sur les régul AI qui est affiché dans leur tableau de bord

itou/metabase/management/commands/sql/024_taux_refus_siae.sql
Suivi du taux de refus par type de structure
Identifier le type de structure avec des taux de refus élevé
=> Taux de refus par SIAE

itou/templates/apply/process_accept.html, itou/www/apply/forms.py, itou/www/apply/tests/tests_process.py
Ajout d'une modale de confirmation contenant le carte de la structure lors de l’embauche.
L’employeur ne sait pas dans quel tableau de bord il se trouve et il s’aperçoit de son erreur une fois la fiche salarié transmise dans l’ASP (mauvaise mesure ou Siret)
=> En tant qu’employeur je veux valider l’embauche d’un candidat dans le tableau de bord de la bonne structure

CHANGELOG.md
Mise à jour du changelog pour le sprint 44
Pour traçabilité
Mise à jour du changelog
=> [Supportix] sprint 44

itou/metabase/management/commands/sql/017_fiches_deposte_en_tension_recrutement.sql
Inclure dans les stats les fiches de poste n'ayant jamais reçu de candidatures
Actions spécifiques de la part du métier pour les fiches de poste n'ayant jamais reçu de candidature
=> MAJ des fiches de poste en difficulté de recrutement

CHANGELOG.md
Résumé des changements apportés durant le sprint.
Pour communiquer sur le travail accompli 💪 !
Un changelog texte !
=> [supportix] Changelog sprint 45

itou/static/css/itou.css
Ajuster la taille la "banner" BETA.
https://www.notion.so/1f630a1c1ea54ecdbfd037ca07a7f146?v=6119c6aa4385475a8fbdf8d7f220f19e&p=a52dca8c36c14fd5bc0d2e36d84581ce
Parcque c'était moche
🧙
=> Ajuster la taille la "banner" BETA

itou/users/adapter.py
=> users: Fix logout for anonymous users

CHANGELOG.md
Résumé des changements apportés durant le sprint.
Pour communiquer sur le travail accompli muscle !
Un changelog texte !
=> [supportix] Changelog sprint 46

itou/templates/admin/approvals/manually_refuse_approval.html, requirements/base.txt, requirements/deploy.txt, requirements/dev.txt
Modifications des fichiers `requirements`.
Rester à jour sur les versions de librairies.
`pip freeze` + `pip-review`
- `paramiko` est explicitement fixé en version `2.8.1` pour compatibilité avec les échanges SSH avec les serveurs SFTP de l'ASP.
- `django-allauth` en version > `0.47.0` casse le SSO
**Ne pas mettre à jour !**
=> Mise à jour des fichiers requirements 

CHANGELOG.md
Ajout au journal de bord des avancées de ces quinze derniers jours.
Nous avons bossé, montrons-le !
Quelques lignes en plus.
=> Journal des changements 47

itou/metabase/management/commands/_organizations.py, itou/metabase/management/commands/_utils.py, itou/metabase/management/commands/populate_metabase_itou.py
Correction de la colonne `organisations.total_candidatures` et autres colonnes similaires.
Cette colonne incluait à tort certaines candidatures qui sont normalement exclues dans le reste des données Metabase (notamment les candidatures de structures inactives).
En rajoutant les bons filtres, ce qui a occassionné pas mal de refactoring pour rester DNRY.
=> Correction de la colonne `organisations.total_candidatures` et autres colonnes similaires.

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/templates/siae_evaluations/includes/siae_infos.html, itou/templates/siae_evaluations/siae_upload_doc.html, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/views.py
Cf chaque commit.
Changements remontés par les utilisateurs.
Cf chaque commit.
1. Version que je n'aime pas trop
2. Version implémentée
1. Déjà présente sur les fiches SIAE
2. Ajoutée sur la page de candidature
=> Controle a posteriori : Correction de bugs remontés par les DDETS et SIAE

CHANGELOG.md
C'est l'usage.
En regardant commit par commit.
=> CHANGELOG Sprint 48

itou/metabase/management/commands/sql/017_fiches_deposte_en_tension_recrutement.sql
Correction du script pour obtenir le bon nombre de fiches de poste
=> Correction : obtention du bon nombre de fdp

itou/metabase/management/commands/sql/019_candidatures_echelle_locale.sql
Ajout de colonnes indiquant l'appartenance (ou non) des structures à différents réseaux
=> Ajout réseaux structures

itou/metabase/management/commands/sql/015_taux_transformation_prescripteurs.sql
addition of a column id_org_prescripteur
=> 015_Metabase : add column id organization

itou/employee_record/tests/tests_notifications.py
=> Nettoyage de code

itou/metabase/management/commands/sql/019_candidatures_echelle_locale.sql
Modification du script de création de la table candidatures_echelle_locale pour ajout du dept de l'organisme prescripteur.
Calculs agrégés par département sur metabase.
Join sur table organisation avec l'id pour récupération du département.
=> candidatures echelle locale : ajout dept prescripteur

itou/metabase/management/commands/sql/020_delai_1ere_candidature_embauche.sql
ajout d'une colonne département prescripteur
=> delai cddr : ajout departement prescripteur

itou/metabase/management/commands/sql/016_candidatures_recues_par_fiche_de_poste.sql
Ajout de la colonne département prescripteur
=> cddr_par_fdp : ajout département presc

itou/metabase/management/commands/sql/015_taux_transformation_prescripteurs.sql
Ajout d'une colonne contenant le département du prescripteur
=> Taux transfo prescp : ajout departement presc

itou/users/management/commands/extract_c2_users.py
Abandon de 2 des 4 extracts C2.
Sur demande de Annie.
=> Abandon de 2 des 4 extracts C2

README.md
Ajoute des recettes pour mettre à jour les dépendances Python et enlever les bases de données existantes dans l’environnement Docker.
Facilite l’exécution de tâches communes.
=> Ajoute des recettes Docker dans le README

itou/metabase/management/commands/sql/019_candidatures_echelle_locale.sql
Modification de la colonne dept_org : ajout du nom du département
=> Candidatures : modif dept_org

CHANGELOG.md
changelog 49 (en cours, sera gelé lundi matin)
Best Practice, dude
Relire le titre des PR du sprint, les traduire en français quand necessaire et possible, les ajouter dans le changelog. Period.
=> CHANGELOG 49

CHANGELOG.md
=> Changelog 49

itou/metabase/management/commands/_approvals.py, itou/metabase/management/commands/_insee_codes.py, itou/metabase/management/commands/_job_applications.py, itou/metabase/management/commands/_job_descriptions.py, itou/metabase/management/commands/_job_seekers.py, itou/metabase/management/commands/_organizations.py, itou/metabase/management/commands/_rome_codes.py, itou/metabase/management/commands/_siaes.py, itou/metabase/management/commands/_utils.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/metabase/tests/_utils.py, itou/metabase/tests/test_job_applications.py
Utilisation d'une classe pour les tables Metabase.
Ce changement fait suite à une suggestion de @vperron sur https://github.com/betagouv/itou/pull/1436 et fait finalement l'objet d'une PR séparée car le diff est considérable.
=> Utilisation d'une classe pour les tables Metabase

.github/workflows/ci.yml, .vscode/extensions.json, .vscode/settings.json, itou/employee_record/mocks/asp_test_siaes.py, itou/employee_record/mocks/test_serializers.py
A relire commit par commit, ils sont a priori _self-explanatory_.
Pour résoudre de petits problèmes rencontrés de temps à autre:
- pollution des apps par des scripts obsolètes ou créés une seule fois mais que l'on maintient malgré tout
- erreurs de build parfois sur la CI
- clarification de code
- paramètres VSCode perfectibles
Cf. chaque commit.
=> Petites améliorations techniques 

itou/metabase/management/commands/sql/016_candidatures_recues_par_fiche_de_poste.sql
Ajout de la colonne injection pour obtenir des données homogènes entre les TBs
=> Candidatures par fdp : ajout colonne injection AI

itou/www/apply/tests/tests_submit.py, itou/www/dashboard/tests.py
=> Fix broken tests on master

itou/api/employee_record_api/tests/tests.py, itou/siae_evaluations/tests/tests_models.py, itou/siaes/tests/tests_models.py
EvaluationCampaignMiscMethodsTest.test_select_min_max_job_applications
65s -> 1s
DummyEmployeeRecordAPITest.test_happy_path:
21s -> 1.8s
SiaeJobDescriptionQuerySetTest.test_with_annotation_is_popular
15s -> 1.6s
- etc.
=> Sauvons les pingouins (accélération d'un test)

itou/utils/tests.py
=> Fix import

itou/openid_connect/france_connect/tests.py, itou/utils/tests.py
respx.mock wasn't doing anything since we dont use httpx in the logout view
- etc.
=> Correction d'un test de France Connect

itou/siae_evaluations/admin.py, itou/siaes/admin.py
Simplify jumping to the definition.
=> Rename siae admin classes to XXXAdmin

itou/siaes/tests/tests_import_siae_command.py
Instead updating each generated membership twice, simply generate them
in the expected state.
Also seems to fix the intermittent failures of
test_check_signup_possible_for_a_siae_with_members_but_no_auth_email_case_two
=> Simplify test_check_signup_possible_for_a_siae_*

Makefile, config/settings/base.py, config/settings/dev.py
Le dossier `config` contient aussi du code, il semble donc normal de faire passer les outils dessus.
=> [Tech] Qualité : Ajout du dossier `config` à la liste

.github/workflows/review-app-creation.yml
Allow uploading documents for the evaluation campaigns.
=> Use the cellar (S3) bucket c1-review-apps-bucket in review apps

config/settings/base.py, itou/siaes/enums.py, itou/siaes/tests/tests_models.py
=> Utiliser le siret plutot que la PK des Siae pour choisir les contrats convergence

.github/workflows/review-app-removal.yml, scripts/create-fast-machine.sh
Cela ne fonctionne pas actuellement.
=> Review Apps & Scripts: Retrait des dernières mentions inutiles d'organisation

Makefile, config/settings/base.py, itou/approvals/tests/test_management_commands.py, itou/employee_record/constants.py, itou/www/apply/tests/tests_submit.py, pytest.ini
Tout est dans le titre.
Oui, je sais, les deux commits ne sont pas vraiment super liés, mais j'en ai eu assez de certains warnings en lançant mes tests.
=> Correction du mode de lancement par défaut de pytest & quelques warnings

CHANGELOG.md
Journal des modifications - Sprint 50
Comme à chaque fin de sprint
Rien de plus, à part l'ajout des numéros de PR et une classification
=> Journal des modifications #50

Makefile
We need to check html formating in quality.
- etc.
=> Makefile: Improve quality target

itou/templates/inclusion_connect/includes/description.html
=> inclusion_connect: Fix alt

itou/templates/dashboard/dashboard.html
djlint does not like `<span>...</span>` followed by some text.
=> templates: Fix dashboard indentation

CHANGELOG.md
Journal des changements du sprint 51, du 10-10-2022 au 23-10-2002.
=> CHANGELOG : Sprint 51

itou/approvals/factories.py, itou/eligibility/factories.py, itou/invitations/factories.py, itou/job_applications/factories.py, itou/siaes/factories.py
Utilise factory.LazyFunction pour les dates dans les tests
Évite de fixer les dates au moment de l’import de la factory.
=> Utilise factory.LazyFunction pour les dates dans les tests

.github/workflows/ci.yml, .github/workflows/review-app-creation.yml, requirements/base.in, requirements/base.txt, requirements/dev.txt, scripts/create-fast-machine.sh
Utilisation de la version la plus récente de uWSGI
https://github.com/unbit/uwsgi/issues/2398 est maintenant résolue.
=> Utilisation de la version la plus récente de uWSGI

itou/metabase/management/commands/sql/019_candidatures_echelle_locale.sql
Ajout de la région du prescripteur à la demande du C2.
=> cddr locale : ajout de la région du prescripteur

itou/metabase/management/commands/populate_metabase_fluxiae.py
I sense the power of the spaghetti in there...
=> populate_metabase_fluxiae: Ajout d'un FIXME à propos d'un redesign à venir.

itou/templates/layout/content_small.html, itou/templates/siaes/card.html, itou/templates/siaes/includes/_list_siae_jobs.html, itou/templates/siaes/includes/_siae_info.html
Correction de l'ui des card siae.
Pour répondre à cette demande https://www.notion.so/Am-liorations-front-de-la-fiche-structure-aa941ad2a8024885995082c194c3425f et pour coller au nouveau design de ce type de boite en `.c-box`
=> Correction de l'ui des card siae

itou/employee_record/models.py, itou/employee_record/tests/tests_models.py
Suite à des tests avec le groupe Actual avec leurs problèmes de transfert, il s'avère que le SIRET d'un clone de fiche salarié ne renvoie pas une valeur actualisée. 
Les données de la convention n'étaient pas rechargée avec la copie, et le numéro de SIRET n'était pas correctement affecté.
Lors d'un clonage de fiche salarié ;
- chargement et vérification de la convention
- affectation du SIRET à la signature 
- vérification de l'état modifié : les fiches désactivées peuvent être clonées
=> FIX: le clonage d'une fiche salarié envoie le bon numéro de SIRET

config/settings/dev.py, itou/templates/includes/pagination.html, itou/templates/layout/breadcrumbs_from_dashboard.html, itou/templates/siaes/includes/_siae_info.html, itou/templates/siaes/job_description_card.html
Correction de l'ui des card job_description.
En passant, petit fix sur une erreur de DOM dans le breadcrumb et ajout d'un ALLOWED_HOSTS dans le dev.py (apparemment nécessaire dans mon installation locale sous docker)
Pour répondre a cette demande https://www.notion.so/Fiche-de-poste-C1-658699a57e5848caa1f2f75a5ac1f02a
Avant
Apres
=> Correction de l'ui des card job_description

itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/create_job_seeker_for_sender/step_base.html, itou/templates/apply/submit/create_job_seeker_for_sender/step_end.html, itou/templates/layout/base.html, itou/www/apply/views/submit_views.py
Déposer une candidature - Modifier la largeur du container
=> [Supportix] Déposer une candidature - Modifier la largeur du container

itou/conftest.py, itou/siaes/factories.py, itou/siaes/models.py, itou/templates/layout/_header.html, itou/templates/search/includes/siaes_search_filters.html, itou/templates/search/siaes_search_results.html, itou/templates/siaes/includes/_card_jobdescription.html, itou/templates/siaes/includes/_card_siae.html, itou/templates/siaes/includes/_list_siae_actives_jobs.html, itou/templates/siaes/includes/_list_siae_actives_jobs_row.html, itou/templates/siaes/job_description_card.html, itou/www/search/tests.py, itou/www/search/urls.py, itou/www/search/views.py, itou/www/signup/tests/test_siae.py, itou/www/testing.py
Permettre l'affichage des fiches de poste.
Besoin très pressant du métier :) Beaucoup d'impacts.
En ajoutant un tab.
Aux relecteurs : j'ai fait exprès de bien découper les commits de manière progressive pour vous faciliter la lecture, j'espère que ça ira !
=> Affichage des fiches de poste

itou/allauth_adapters/peamu/tests.py, itou/allauth_adapters/peamu/views.py, itou/siae_evaluations/migrations/0010_finalize_evaluation_campaign_2021.py, itou/siae_evaluations/models.py, itou/users/adapter.py, itou/www/siae_evaluations_views/views.py
Correction de l’accès à `has_completed_welcoming_tour` sur les anonymes
- https://sentry.io/organizations/itou/issues/3705359057/
=> Correction de l’accès à `has_completed_welcoming_tour` sur les anonymes

itou/metabase/management/commands/_utils.py, itou/utils/swear_words.py
Utilisation de functools.cache au lieu de lru_cache
=> Utilisation de functools.cache au lieu de lru_cache

itou/approvals/enums.py, itou/approvals/models.py, itou/approvals/tests/tests.py, itou/job_applications/csv_export.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/static/js/approvals_filters.js, itou/static/js/job_applications_filters.js, itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/list_for_siae.html, itou/templates/apply/process_base.html, itou/templates/approvals/detail.html, itou/templates/approvals/includes/approvals_filters/status.html, itou/templates/approvals/includes/approvals_filters/users.html, itou/templates/approvals/includes/job_applications.html, itou/templates/approvals/includes/list_card.html, itou/templates/approvals/list.html, itou/templates/dashboard/dashboard.html, itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_results.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/tests/test_list.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py, itou/www/dashboard/tests.py, itou/www/dashboard/views.py
Ajout d'une section Salariés au tableau de bord des SIAEs
Déplacement de la gestion des PASS IAE dans cette section
Fournir un accès aux salariés d’une structure pour faciliter la recherche d’un salarié lorsqu’un employeur doit le trouver pour faire une action le concernant
- Découpage dashboard (bloc “Mes salariés”)
- Une vue synthétique qui me permet de voir uniquement les salariés embauchés au sein de ma structure (1 ligne par salarié)
- Filtrer / Rechercher (statut du PASS, nom du candidat)
- Une vue détaillée ‘Profil salarié” : 
- Gérer la modification de la date de début du contrat de travail (dans le futur) = à travers la liste des candidatures
- Gérer le PASS IAE (annulation, suspension, prolongation)
- modification de la vue “candidature “ :
- retrait du PASS IAE
- ajout d’un …
=> Accès "Mes Salariés"

itou/templates/apply/process_accept.html
=> [Supportix] Amélioration UX dans le parcours d’embauche (wording)

config/settings/base.py, itou/templates/api/index.html, itou/utils/settings_context_processors.py
=> [Supportix] Ajout de l'API candidats à la liste des nouveautés de la doc de l'API

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Affichage de l’erreur NIR dupliqué
Au lieu d’une belle 500.
- https://sentry.io/organizations/itou/issues/3491663989/
=> Affichage de l’erreur NIR dupliqué

itou/templates/dashboard/dashboard.html, itou/templates/dashboard/includes/admin_card.html, itou/templates/dashboard/includes/job_seeker_approval_card.html, itou/templates/dashboard/includes/job_seeker_job_applications_card.html, itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/labor_inspector_organization_card.html, itou/templates/dashboard/includes/prescriber_job_applications_card.html, itou/templates/dashboard/includes/prescriber_organisation_card.html, itou/templates/dashboard/includes/siae_card.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html, itou/templates/dashboard/includes/siae_job_applications_card.html, itou/templates/dashboard/includes/stats.html
Découpage du template du dashboard en petits templates
rend plus lisible la page le fichier html du dashboard.
=> Découpage du template du dashboard en petits templates

itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/prescriber_organisation_card.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html, itou/templates/siaes/includes/_card_jobdescription.html, itou/www/dashboard/tests.py
Mises à jours de couleurs des badges "Nouveau"
Mises à jours de couleurs de badges
=> [Supportix] Mises à jours de couleurs de badges

itou/approvals/management/commands/export_pe_api_rejections.py, itou/approvals/tests/test_management_commands.py
Histoire de le faire ressembler à celui de fusion des doublons d'utilisateurs.
=> Amélioration du script d'export des rejet de l'API PE

itou/www/search/tests.py, itou/www/search/views.py
De petits bugs ont été constatés. Test flaky ou pas assez précis, code un peu plus élégant et qui prépare la suite, mais surtout un bug sur les filtres actuellement en production.
Corriger un certain nombre de mini problèmes avant de passer une nouvelle feature.
Cf les commits bien séparés.
=> Correctifs pour les fiches de poste

clevercloud/pre_build.sh, clevercloud/pre_run.sh
It is available on the Python images.
=> clevercloud: Ne plus télécharger sops.

.github/workflows/antivirus-scan.yml, config/settings/base.py, itou/antivirus/admin.py, itou/antivirus/apps.py, itou/antivirus/management/commands/scan_s3_files.py, itou/antivirus/migrations/0001_initial.py, itou/antivirus/models.py, scripts/antivirus-daily.sh, scripts/antivirus-monthly.sh
Mise en place de la solution ClamAV pour scanner les fichiers déposés sur le stockage S3 comme les CVs ou les justificatifs du contrôle a posteriori.
Pour éviter qu'un utilisateur dépose intentionnellement ou non, un fichier infecté sur notre plateforme.
=> Mise en place d'un antivirus pour les fichiers déposés sur le stockage S3

requirements/dev.in, requirements/dev.txt
jedi & xlwt qui sont malgré tout tirés par d'autres dépendances :-/
Car on ne les utilise pas directement.
=> requirements: nettoyage des dépendances de dev

itou/users/admin_forms.py, itou/users/tests/test_admin_views.py
Problème depuis 4ea618dd5bd7b8e60523e056068ee3758d29e57b
https://sentry.io/organizations/itou/issues/3060572437/
=> Autorise la modification d’utilisateurs SSO sans champ email

itou/www/search/tests.py
Suite à une mise en prod malencontreuse.
=> search.tests: Correction d'un test 

requirements/base.in
Suppression de la plupart des contraintes de version.
On garde une contrainte au niveau mineur pour les dépendances liées à `pandas` car il y a a priori peu de tests.
`django-bootstrap4` étant lié à la version de la lib bootstrap, cela nécessitera sûrement des vérifications manuelles
`elastic-apm` devrait bientôt nous quitter
Afin de rester à jour.
`dependabot` devrait faire des PRs régulièrement pour tenter des mises à jour.
=> requirements: suppression de la plupart des contraintes

itou/templates/siaes/job_description_list.html
Retrait d’un élément non utilisé de la configuration des postes
Jamais utilisé.
=> Retrait d’un élément invisible de la configuration des postes

itou/templates/siae_evaluations/email/to_siae_notify_before_adversarial_stage_body.txt
Ajoute une formule de politesse au mail de notification avant la phase contradictoire
=> Ajoute une formule de politesse au mail de notification avant la phase contradictoire

itou/approvals/tests/tests.py, itou/eligibility/tests.py, itou/employee_record/tests/tests_models.py, itou/job_applications/factories.py, itou/job_applications/tests/test_eligibility.py, itou/job_applications/tests/tests.py, itou/job_applications/tests/tests_transfer.py, itou/siae_evaluations/factories.py, itou/siae_evaluations/tests/tests_models.py, itou/users/tests/test_management_commands.py, itou/utils/tests.py, itou/www/apply/tests/test_edit.py, itou/www/apply/tests/tests_list.py, itou/www/apply/tests/tests_process.py, itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/tests/test_pe_approval.py, itou/www/approvals_views/tests/test_prolongation.py, itou/www/approvals_views/tests/test_suspend.py, itou/www/dashboard/tests.py, itou/www/eligibility_views/tests.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py
On souhaite s'assurer que le PASS IAE reste visible
=> Ajout de tests sur la page de détail des candidures pour les prescripteurs

itou/asp/models.py, itou/asp/tests/tests_communes.py
=> asp: Fix other Commune uses regarding manually created objects

itou/metabase/management/commands/sql/026_suivi_etp_realises_v2.sql
Création d'une nouvelle table afin de calculer les ETPs réalisés et les proposer aux DDETS, DREETS, SIAE et à la DGEFP
Cela nous permettra de créer un tableau de bord permettant le suivi des ETPs réalisés
=> etp réalisés v2

itou/templates/apply/includes/eligibility_diagnosis.html, itou/templates/apply/includes/job_application_sender_info.html, itou/templates/apply/includes/list_card_body.html, itou/templates/apply/includes/list_card_header.html, itou/templates/apply/includes/transfer_job_application.html, itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/includes/status.html, itou/templates/approvals/suspend.html, itou/templates/approvals/suspension_delete.html, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/list.html, itou/templates/includes/members.html, itou/templates/layout/_nav_btn_items.html, itou/templates/search/prescribers_search_results.html, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html, itou/templates/siae_evaluations/includes/siae_infos.html, itou/templates/siaes/show_financial_annexes.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
=> Utilisation des badges arrondis partout sur le site

itou/static/css/itou.css, itou/templates/apply/includes/job_applications_filters/criteria.html, itou/www/apply/forms.py
Remplacement du widget utilisé pour filtrer par critère d'éligibilité.
Il est plus facile de sélectionner les critères par mot-clé dans une liste qu'avec des cases à cocher.
=> Liste de candidatures : modification du filtre par critères d'éligibilité

.github/pull_request_template.md
La section Autre n’est pas utilisée. Les sections Quoi, Pourquoi et Comment se recoupent fréquemment, laissons les devs organiser la présentation à leur guise.
=> Mise à jour du gabarit pour les pull requests

itou/metabase/management/commands/sql/028_suivi_consommation_etp_V2.sql
Création d'un indicateur de suivi des etps pour les DDETS/DREETS/SIAE
=> Suivi de la consommation des ETPs

requirements/base.in
Moins de redirection, plus de clarté.
=> Correction de l’URL du projet Redis-py

config/settings/base.py
Il y a beaucoup de rapport CSP liées à hotjar depuis le déploiement
=> Autoriser hotjar au niveau du CSP

config/settings/base.py
Voir les commits pour le détail
=> CSP: plus de corrections

config/settings/base.py
=> CSP: Encore des améliorations

config/settings/base.py
=> CSP: Ajout du NONCE dans la règle script-scr-elem

itou/antivirus/management/commands/scan_s3_files.py
=> Petits correctifs pour l’antivirus

itou/siae_evaluations/admin.py, itou/siae_evaluations/tests/test_admin.py
Le fichier zip ne donne pas un bon aperçu de l’état de la campagne, car les données sont réparties dans plusieurs fichiers. Finalement, un seul CSV est plus pratique.
=> Exporter les SIAE des campagnes d’évaluation en CSV

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Dernière utilisation dans 608fd6b056aeeecfcf87b9b74cec1631d6ae9715
=> www.apply: remove unused function

config/settings/base.py
=> CSP: Allow connection to hotjar websockets

itou/antivirus/management/commands/scan_s3_files.py
Sera utile pour identifier si la taille des lots ou la fréquence des analyses doit être augmentée.
=> Ajoute un log à l’analyse antivirus

docker/dev/postgres/maintenance/restore
Utiliser plus de threads avec `pg_restore --jobs`
=> Accélerer le chargement de dumps

clevercloud/cron.json, config/settings/base.py, itou/analytics/admin.py, itou/analytics/apps.py, itou/analytics/employee_record.py, itou/analytics/factories.py, itou/analytics/management/commands/collect_analytics_data.py, itou/analytics/migrations/0001_initial.py, itou/analytics/models.py, itou/analytics/tests/test_collect_analytics_data_management_command.py, itou/analytics/tests/test_employee_record.py, itou/employee_record/factories.py, requirements/dev.in, requirements/dev.txt
Création de l'app `analytics et premier jet avec l'ajout de métriques pour les fiches salariés
Commencer à poser les fondations de ce qui doit nous servir à faciliter les mesures qui nous semblent pertinentes.
La premier cas sera sur les fiches salariés, dans l'objectif de mesurer les impacts ainsi que piloter les changements ou améliorations liés à celles-ci.
Création d'une app ainsi que d'une tâche cron journalière.
Pour le moment le code est purement procédurale et avec aucune "magie" (décorateur, métaclasses, etc), cela engendre un peu de _boilerplate_ (code et/ou tests) mais l'app étant encore à son balbutiement ça me semble le mieux, le temps de voir comment tout cela évolue bien évidemment :grin:.
Pour un peu les mêmes raisons, mais aussi pour ouvrir la PR le plus tôt, le code est …
=> App `analytics` et premières métriques des fiches salariés

itou/metabase/tables/siaes.py
We did absolutely fuck up the get_parent_siae, sorry :'(((
=> metabase.siaes: Corriger une erreur grave dans `get_parent_siae`

itou/metabase/management/commands/populate_metabase_emplois.py
Le décompte de membres est incorrect.
Il faut que l'on se dote vite de tests intégraux sur cette partie.
=> metabase.siaes: Fix incorrect members count

itou/metabase/management/commands/populate_metabase_emplois.py
Metabase: Fix suite à un merge conflict
=> Metabase: Fix suite à un merge conflict

itou/metabase/management/commands/populate_metabase_emplois.py
=> Correction de l'import metabase journalier

itou/www/search/tests.py, itou/www/search/views.py
=> www.search: fix N+1 issue when listing jobs of the found SIAEs

itou/metabase/management/commands/populate_metabase_emplois.py, requirements/base.in, requirements/base.txt
Faire en sorte que populate_metabase_emplois rééssaie 3 fois (avec une petite attente) avant de jeter l'éponge.
=> metabase_emplois: Implémenter des retry

itou/www/invitations_views/tests/test_new_user.py, itou/www/invitations_views/views.py
https://sentry.io/organizations/itou/issues/3851693266/
=> Fix unvalidated lookup in invitations_views:new_user

requirements/base.txt, requirements/dev.txt
Cela supprime des RemovedInDjango50Warning
=> Bump django-anymail 9.0

.github/workflows/review-app-creation.yml, itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py
Afficher dans sentry les informations permettant d'identifier l'utilisateur pour le retrouver
=> Amélioration (encore) des erreurs Inclusion Connect

itou/metabase/db.py, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/job_seekers.py, itou/metabase/utils.py
20 à 30% plus rapide en local, à voir le gain en prod
=> Metabase : Améliorer les performances de l'export des candidats

itou/geo/admin.py
Filtrer les éléments ZRR par statut (38k+)
=> Ajout d'un filtre par status pour les ZRR

config/settings/base.py
voir les erreurs suivantes :
https://sentry.io/organizations/itou/issues/3865240345/?project=6164438&query=logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
https://sentry.io/organizations/itou/issues/3795985723/?project=6164438&query=logger%3Acsp+is%3Aunresolved&referrer=issue-stream&statsPeriod=14d
=> CSP: Ajout de frame-src

itou/metabase/sql/030_taux_penetration_tb_prives.sql
Annie souhaite calculer le taux de pénétration de nos tableaux de bord (Visiteurs uniques des TBs privés/Utilisateurs potentiels).
Création d'une table contenant ces deux informations.
=> Taux de pénetration : lien visiteurs uniques et utilisateurs

itou/openid_connect/inclusion_connect/views.py
Améliorer l'expérience utilisateur et réduire le nombre d'erreurs sentry
- Dans le cas où le logout ne fonctionne pas, quand même rediriger l'utilisateur.
https://sentry.io/organizations/itou/issues/3855984779/?project=6164438&query=is%3Aunresolved&referrer=issue-stream
Est-ce utile se logger l'erreur malgré tout ?
=> Inclusion Connect: Corrections d'erreurs sentry

config/settings/base.py
https://www.notion.so/Audit-de-s-cu-mettre-en-place-une-politique-CSP-c379068b4d0f4198906f8c8198924bd4
En réponse à l'audit de sécurité
On force CSP sur tous les environnements,
On n'envoie les rapports que pour les reviews apps pour limiter la facture sentry et le temps d'analyse des innombrables scripts d'extensions...
=> Activation des Content Security Policy

itou/siaes/management/commands/sync_pec_offers.py
Cf le commentaire dans le message de commit pour plus de compréhension.
[L'erreur Sentry ](https://sentry.io/organizations/itou/issues/3870979527/activity/?alert_rule_id=10485625&alert_timestamp=1673546725138&alert_type=email&environment=production&project=6247245&referrer=alert_email).
On a une erreur dans Sentry que j'ai peut-être mal comprise et que j'essaie de réparer, sans pouvoir vraiment reproduire. En prod, les runs suivants du cron ont fonctionné sans problème.
Cela dit, cette modification améliore les choses de toutes manières à mon avis.
Maintenant je suis preneur d'avis:
- le faire ou pas ?
- le tester ou pas: ça me semble overkill pour le cas d'usage.
=> sync_pec_offers: Verrouiller les lignes synchronisées et ajouter une transaction

itou/www/dashboard/forms.py, itou/www/dashboard/views.py
Afin de ne pas supprimer des champs dans l'`__init__` ce qui n'est pas super propre et posait des soucis pour ma PR sur les NIRs.
=> Création d'un formulaire dédié à l'édition des candidats

clevercloud/crons/populate_metabase_matomo.sh, itou/metabase/management/commands/populate_metabase_matomo.py
=> Matomo : améliorations de stabilisation

itou/metabase/dataframes.py, itou/metabase/db.py
Utiliser  create_table et rename_table_atomically partout.
=> Metabase: petit refactor des fonctions utilitaires

itou/metabase/sql/015_taux_transformation_prescripteurs.sql
Suite à MEP de https://github.com/betagouv/itou/pull/1978
Cf fil ([lien](https://itou-inclusion.slack.com/archives/C03ES35UL30/p1674135689746579))
@YannickPassa Pourras-tu reviewer a posteriori stp 🙏 . Là je MEP sans t'attendre, j'ai besoin de débloquer la prod.
cc @laurinehu
=> [Metabase] Hotfix mineur d'une requête SQL

itou/siae_evaluations/emails.py, itou/users/management/commands/deduplicate_job_seekers.py
Centraliser la logique, aussi plus clair.
=> Utilisation de get_absolute_url() au lieu de construction manuelle

itou/cities/tests.py
Non utile, certainement pas une approche recommendable.
=> Retrait de l’utilitaire to_dict

itou/templates/account/login_generic.html
Suite à la modification du nom de domaine associé au partage public de pages du Notion ITOU
=> Mise à jour du lien notion "en savoir plus" pour Inclusion Connect

itou/templates/inclusion_connect/includes/button.html
Le domaine public de Notion a changé.
=> [IC] Fix lien Notion

itou/www/autocomplete/tests.py, itou/www/autocomplete/views.py
https://www.notion.so/plateforme-inclusion/Am-liorer-la-recherche-de-communes-ASP-18be9bbf90d14c45a1913ed8b98efb90
Le problème nous a été remonté par un utilisateur
Je reprends la même logique que la PR de @vperron : https://github.com/betagouv/itou/pull/2051
=> Amélioration de l'autocompletion pour les Communes

itou/conftest.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/approvals.py
=> Metabase: corriger la lecture du champ "origin" sur les approvals

clevercloud/cron.json, clevercloud/crons/populate_metabase_fluxiae.sh, itou/approvals/models.py, itou/approvals/tests/tests.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/scripts/sql/cta_export.sql, itou/templates/employee_record/includes/list_item.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, itou/www/employee_record_views/tests/test_list.py
**Cartes Notion : **
https://www.notion.so/plateforme-inclusion/1-2-Suspension-36-mois-Modifier-la-dur-e-max-de-suspension-d-un-PASS-IAE-boost-895a122365f045c0af9e9252343811c6
https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-je-veux-comprendre-pourquoi-je-dois-mettre-jour-certaines-fiches-salari-alors-q-73b073cfad444415ab4b72d0cae4f10e
- Les BOOST haute priorité de ce sprint.
- J'ajoute l'import du script d'export CTA qui sera mieux maintenu s'il est ici [PR soeur là.](https://github.com/betagouv/itou-private/pull/177)
=> Boost S05 2023

itou/metabase/sql/028_suivi_consommation_etp_V2.sql, itou/metabase/sql/029_suivi_consommation_mensuelle_etp_V2.sql
Ajout de certaines colonnes nécessaires à la création d'indicateurs
=> [Metabase] Ajout de colonnes pour le calcul des ETPs

itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/evaluated_job_applications.py, itou/metabase/tables/evaluated_siaes.py, itou/metabase/tables/utils.py
**Fil : https://itou-inclusion.slack.com/archives/CT7986ULC/p1675706646711829 **
A la demande de Laurine pour lui permettre de faire davantage de jointures pertinentes.
=> [Metabase] Ajout de deux colonnes aux tables CAP

itou/templates/eligibility/includes/form.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py, itou/www/eligibility_views/forms.py
**Carte Notion : ** https://www.notion.so/Am-lioration-du-texte-li-la-conservation-des-justifs-administratifs-boost-877add4c6939411abfd5dc558c1778db
Alléger la page, le bouton suffit.
=> Amélioration du texte lié à la conservation des justifs administratifs

itou/approvals/models.py, itou/asp/models.py, itou/common_apps/organizations/models.py, itou/eligibility/models/common.py, itou/eligibility/models/iae.py, itou/employee_record/models.py, itou/external_data/models.py, itou/institutions/models.py, itou/invitations/models.py, itou/job_applications/models.py, itou/jobs/models.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/siaes/models.py
=> Suppression de managers & utilisation de as_manager()

itou/cities/sample-cities.csv, itou/www/autocomplete/tests.py, itou/www/autocomplete/views.py
The alphabetical order was actually not properly done.
=> autocomplete: Fix issue in looking for cities

itou/www/autocomplete/tests.py, itou/www/autocomplete/views.py
On a des remontées d’utilisateurs qui n'arrivent pas à trouver certaines communes.
=> Utilisation de la nouvelle autocompletion sur les Communes ASP

itou/www/siae_evaluations_views/views.py
=> Correction de l'affichage de la fin de campagne lorsqu'il n'y a pas de sanctions

itou/templates/apply/includes/job_application_answers.html, itou/templates/apply/includes/job_application_info.html, itou/templates/apply/includes/job_applications_export_button.html, itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/apply/process_accept.html, itou/templates/apply/process_postpone.html, itou/templates/layout/_header.html, itou/templates/layout/_nav_btn_items.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/A11Y-Gestion-de-candidatures-Autoaudit-4b2f0925eb0144478c63cdb024daa4e7
Amélioration de l'accessibilité du parcours "Gestion des candidatures"
En corrigeant les erreurs liées aux points
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9.1
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9.4 
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.9
- et les erreurs remontées par l'extension d'accessibilité pour navigateur axe
=> Corrections liées à l'autoaudit d'accessibilité lot#01

CHANGELOG.md
=> changelog: sprint 56

itou/templates/employee_record/list.html
Broken with 82acecefa716caf28d8c740b8705281a69274723.
=> Fix itou/templates/employee_record/list.html lint sur master

itou/metabase/sql/026_suivi_etp_realises_v2.sql
Correction de l'inversion ETPs annuels/mensuels
=> [Metabase] Correction inversion etp annuels/mensuels

itou/siae_evaluations/models.py
La méthode `review()` est protégée par `can_review`, qui vérifie que la `EvaluatedSiae` est dans un état attendu.
Aussi, la sécurité qui `raise` une `TypeError` en cas d’état inattendu ne pouvait pas fonctionner, car elle était protégée par le garde.
=> Retrait d’un mauvais garde de EvaluatedSiae.review()

itou/templates/stats/stats.html, itou/templates/stats/stats_test1.html, itou/templates/stats/stats_test2.html, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py
**Fil slack : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1676909525575239**
Deux nouvelles vues vont permettre de tester si le souci vient du script `iframeResizer`.
=> [Stats] Ajout de vues temporaires pour tester un souci technique du popup Tally qui ne se produit qu'en production

itou/templates/stats/stats_test1.html, itou/templates/stats/stats_test2.html, itou/www/stats/views.py
**Fil : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1676909525575239**
Pas de revue, de toute façon je vais 🔪 toutes les views de test une fois ce souci résolu.
=> [Stats] Continuation des tests autour d'un souci technique du popup Tally qui ne se produit qu'en production

itou/metabase/sql/019_candidatures_echelle_locale.sql
**Carte Notion : ** : https://www.notion.so/plateforme-inclusion/Ajouter-et-envoyer-la-BDD-R-seaux-de-Cocagne-5f387e8488ad4b238d20e41b94ebb4a5?pvs=4
Ajout du nouveau réseau Cocagne pour permettre de générer l'export du réseau
=> Metabase : ajout du réseau Cocagne dans candidatures_echelle_locale

itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/evaluated_job_applications.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/includes/list_item.html, itou/templates/siae_evaluations/institution_evaluated_job_application.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/templates/siae_evaluations/siae_upload_doc.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Simplication-du-code-de-calcul-des-tats-du-controle-a-posteriori-45a39a6f990b4cf68159aa49c34fbf55
Essayer de simplifier
=> Controle a posteriori: réusinage des states

itou/templates/dashboard/dashboard.html
Correctif pour envoyer l'événement.
=> [Matomo] Activer l'envoi d'un événement en ajoutant la classe adéquate 

.github/workflows/review-app-creation.yml
=> Utiliser la même version python de prod dans les review-apps

itou/common_apps/organizations/admin.py, itou/institutions/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Emp-cher-qu-une-structure-organisation-institution-partenaire-se-retrouve-sans-administrateur-1db9cc735ad8451981efe76d30657f73?pvs=4
Tenter de limiter le nombre de structure sans administrateur
=> admin: ajout d'un avertissement dans l'admin quand le dernier administrateur est retiré

itou/templates/layout/_nav_btn_items.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Fix-Header-Dropdown-66b6618306534d169112a1d4193593ee?pvs=4
Pour respecter l'intégration des Dropdown du thème et rendre les états :active et  :focus plus lisible
Avant
Apres
=> Correction de l'UI du menu dropdown du header

itou/templates/apply/list_for_siae.html
As expected after 2 weeks.
**Carte Notion : prévu dans la carte initiale**
Cela fait deux semaines.
=> apply/list: Retirer le formulaire Tally

itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/import_geiq.py
Pour pouvoir importer le fichier envoyé par la FFGEIQ.
=> Correction de la management command `import_geiq`

clevercloud/cron.json, clevercloud/crons/populate_metabase_emplois.sh, clevercloud/crons/test-errexit.sh, itou/analytics/admin.py, itou/users/management/commands/sync_group_and_perms.py, itou/users/tests/test_management_commands.py
=> analytics: Donner accès à la table de visite des dashboards aux admin

itou/templates/account/activate_inclusion_connect_account.html, itou/utils/tests.py, itou/utils/urls.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/login/tests.py, itou/www/login/views.py
https://www.notion.so/plateforme-inclusion/BUG-en-lien-avec-inclusion-connect-les-invitations-dans-une-autre-orga-ne-fonctionnent-plus-f80a49b85e8244c1b633a2b30b90b751?pvs=4
BUG en lien avec inclusion connect les invitations dans une autre orga ne fonctionnent plus
=> fix: ajout du next_url pour la redirection Inclusion Connect

itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
Correction d'une erreur dans la conversion des str en int. Je ne prenais que les deux caractères du str avant...
=> [Metabase] Correction d'une erreur dans la conversion des str en int

itou/metabase/management/test_populate_metabase_matomo.py
=> test_populate_matomo: Accélération des tests

Makefile, clevercloud/archive_employee_records.sh, clevercloud/crons/populate_metabase_emplois.sh, clevercloud/crons/populate_metabase_matomo.sh, clevercloud/download_employee_records.sh, clevercloud/pre_build.sh, clevercloud/pre_run.sh, clevercloud/review-app-after-success.sh, clevercloud/run_management_command.sh, clevercloud/upload_employee_records.sh, docker/dev/postgres/maintenance/_sourced/constants.sh, docker/dev/postgres/maintenance/_sourced/messages.sh, requirements/dev.in, requirements/dev.txt, scripts/create-fast-machine.sh, scripts/deploy_prod.sh, scripts/import-latest-db-backup.sh, scripts/imports-asp.sh, scripts/upload_itou_theme.sh
_tl;dr:_ J'ai mis le doigt où fallait pas et un peu trop d’enthousiasme matinal :sweat_smile:.
Problème lié à l'archivage des FS
=> Je déplace le code actuel dans sa propre _management command_
=> Je vois shellcheck qui râle car le script shell lançant la _management command_ ne fait que `cd "$APP_HOME"`
=> L'erreur est dans quasiment tout nos fichiers
=> Je commence à corriger mais shellcheck râle pour d'autre chose dans les autres fichiers
=> Je suis une feignasse donc je cherche si ça peux pas corriger tout seul, no-mé-ho!
=> C'est possible !
=> FIN
=> Qualité : Ajout de l'outil `shellcheck`

itou/users/admin.py
Corriger le lien vers les SIAE et ajouter les candidatures envoyées pour les prescripteurs et employeurs
=> Améliorer l'admin des utilisateurs

itou/approvals/tests/tests.py
Suite à une mauvaise compréhension de l'UI de github, j'ai mergé mes PR sans passer par la merge queue (en voulant passer outre un test flaky que je vais essayer de corriger juste après).
=> Correction d'un test

itou/metabase/sql/031_suivi_auto_prescription.sql, itou/metabase/sql/033_siae_pratiquant_autoprescription.sql
Retrait des structures inactives pour être raccord avec les chiffres de Laurine
=> [Metabase] : Auto prescription -> retrait des structures inactives

itou/templates/siaes/card.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Arrondis-page-fiche-structure-d5ed1d1f49494dd197f97034b08f7bad?pvs=4
Parcque c'est plus mignon
=> Petite amélioration UI de la fiche SIAE

itou/approvals/admin_forms.py, itou/approvals/tests/tests.py
Voir l'erreur https://itou.sentry.io/issues/4032868339/?project=6164438&referrer=slack
=> Correction de l'admin des PASS IAE lors d'une tentative d'ajout avec un numéro commençant par 99999

itou/siaes/factories.py
De temps en temps, le code postal n'est pas d'un département valide
=> Correction de la génération du code postal de SIaeFactory

itou/templates/apply/includes/buttons/accept.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Avec un test cette fois-ci :sweat_smile:
=> Simplification de show_geiq_eligibility_modal V2

itou/metabase/tables/utils.py, itou/users/migrations/0004_fill_user_last_checked_at.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py, itou/www/search/tests.py
Soucis identifiés via pylint/unnecessary-comprehension
=> Simplification de code

itou/metabase/sql/033_siae_pratiquant_autoprescription.sql
Ajout de la région et du département des structures dans le tableau de bord 267 - Auto prescription
Cela permettra d'avoir une vision du nombre de SIAE par territoire
=> [Metabase] Ajout de la région et du département des structures

itou/metabase/sql/019_candidatures_echelle_locale.sql
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/DIHAL-TB-V1-prise-en-compte-des-retours-d497f14fd575430fa4e97e11f8f87324?pvs=4
ajout d'une filtre par siret sur le TB DIHAL
=> Metabase : ajout du siret de l'organisation sur la table 019 + corrections sqlfluff

itou/templates/dashboard/dashboard.html, itou/www/dashboard/tests.py
https://www.notion.so/plateforme-inclusion/Ajouter-une-phrase-qui-annonce-le-passage-100-inclusion-connect-dans-le-bandeau-d-info-inclusion--5a4e2b46db8246df8608037bf63d40da?pvs=4
https://www.notion.so/plateforme-inclusion/3566874a30f44c44859a3c8ba9cef8d8?v=407946978aa3485c8353a502ff9397ea&p=006411cdfdc14a388bfa8db27dd15ace&pm=c
Prévenir les utilisateurs du changement
=> Prévenir de la connexion forcée avec Inclusion Connect

itou/invitations/models.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/invitations_views/views.py
Pensez à mettre le label "no-changelog" si nécessaire.
=> Simplification des invitations

itou/templates/apply/list_of_available_exports.html, itou/www/apply/tests/tests_list.py
**Carte Notion: ** https://www.notion.so/plateforme-inclusion/Amelioration-UI-liste-export-des-candidatures-497192aa45a64a28b7de12657a975ddc?pvs=4
Respect du thème et harmonisation des tables
Avant
Apres
=> Amélioration UI de la liste des exports de candidatures

itou/siaes/management/commands/move_siae_data.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Support-C1-Move-SIAE-data-complet-Mode-1-f074c95cac0a4d1281a944f3100ab875**
Parfois, l’utilisateur du script ne souhaite pas écraser les données cible (`to`) avec les données d’origine (`from`). Au lieu de systématiquement écraser les données, formalisons ce besoin avec un argument.
=> Ajout de --preserve-to-siae-data à move_siae_data

itou/eligibility/data/administrative_criteria_geiq.json, itou/www/geiq_eligibility_views/forms.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Postuler-en-GEIQ-modifier-le-texte-du-crit-re-Jeune-de-moins-de-26-ans-sans-qualification-e1a3cf726dff4ae4b88786dc1afbb653**
=> Mise à jour du texte d’éligibilité GEIQ

itou/templates/apply/includes/rdv_insertion_promo_card.html
**Carte Notion : https://www.notion.so/plateforme-inclusion/Modifier-le-lien-de-la-promo-de-RDV-insertion-boost-279e6b3ed72c4b94b56ac0a11f9cd0ab**
=> Replace RDV-I link with typeform

itou/templates/apply/includes/_submit_title.html, itou/templates/apply/includes/geiq/geiq_administrative_criteria_form.html, itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/resume.html, itou/templates/apply/submit_base.html, itou/templates/apply/submit_base_two_columns.html, itou/templates/dashboard/includes/siae_job_applications_card.html, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py, itou/www/dashboard/tests.py
https://www.notion.so/plateforme-inclusion/1-3-Pack-postuler-en-Geiq-En-tant-qu-employeur-je-r-alise-une-auto-prescription-96bded172c0649f1b421d09370cfa599?pvs=4
https://www.notion.so/plateforme-inclusion/3-3-Pack-postuler-en-Geiq-En-tant-que-postulant-en-GEIQ-je-renseigne-le-message-de-candidature-2d7ef157cfb94926a7adfd67dd9fab82?pvs=4
Suite au nouvel arrêté relatif aux critères d’éligibilité à l’aide à l’accompagnement GEIQ et à la demande de la FFGEIQ qui souhaite adapter le parcours de candidature aux besoins des GEIQ.
Reprise de la même logique que pour l'IAE, avec simplification vu que les cas PASS IAE n'existent pas,
=> GEIQ : Ouverture du parcours d'auto-prescription et messages contextuels

itou/templates/apply/email/cancel_body.txt, itou/templates/apply/email/new_for_job_seeker_body.txt, itou/templates/apply/email/new_for_prescriber_body.txt, itou/templates/apply/email/new_for_siae_body.txt, itou/templates/apply/includes/job_application_info.html, itou/templates/apply/includes/list_card_body.html, itou/templates/apply/submit/application/jobs.html
=> Retire les (s) de Métier(s) recherché(s)

itou/openid_connect/inclusion_connect/views.py
L'access token est masqué dans sentry donc ce code ne sert à rien.
=> Nettoyage de code inutile pour Inclusion Connect

itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html
Cf https://getbootstrap.com/docs/4.6/components/collapse/#example
=> Utilisation de data-target au lieu de href pour controler le toggle

itou/templates/apply/submit/create_or_update_job_seeker/step_1.html, itou/templates/siae_evaluations/evaluated_siae_sanction.html, itou/templates/stats/stats_pilotage.html, itou/www/siae_evaluations_views/tests/test_views.py
Encore des petites corrections d'HTML.
=> Nettoyage d'HTML

itou/templates/employee_record/disable.html, itou/templates/employee_record/reactivate.html, itou/templates/stats/stats.html, itou/templates/stats/stats_pilotage.html
Pour que le validateur soit heureux (et que nos pages s'affichent bien comme on le souhaite).
=> Nouvelles corrections HTML

itou/static/js/approvals_filters.js, itou/static/js/job_aside_collapse_filters.js, itou/templates/apply/includes/eligibility_diagnosis.html, itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/approvals/detail.html, itou/templates/approvals/includes/approvals_filters/status.html, itou/templates/approvals/includes/approvals_filters/users.html, itou/templates/approvals/includes/card.html, itou/templates/approvals/includes/job_applications.html, itou/templates/approvals/includes/job_description_list.html, itou/templates/approvals/includes/list_card.html, itou/templates/approvals/list.html, itou/templates/approvals/printable_approval.html, itou/templates/approvals/suspend.html, itou/templates/employee_record/list.html, itou/templates/layout/base_printable.html, itou/www/apply/tests/__snapshots__/tests_list.ambr, itou/www/approvals_views/tests/test_list.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/A11Y-Gestion-du-PASS-IAE-Autoaudit-5c3dcc6e39d94bfb90e1386c163dba5b?pvs=4
Amélioration de l'accessibilité du parcours "Gestion dus PASS IAE" et en passant, amélioration et harmonisation de l'ui
En corrigeant les erreurs liées aux points :
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#6.1
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#8.2
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#8.9
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.1
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.5
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.6
- …
=> Corrections liées à l'autoaudit d'accessibilité lot#02

itou/templates/apply/includes/known_criteria.html, itou/templates/siaes/edit_job_description.html, itou/templates/siaes/edit_job_description_details.html, itou/templates/siaes/edit_job_description_preview.html, itou/templates/siaes/edit_siae_preview.html, itou/templates/siaes/includes/_job_description_details.html, itou/templates/siaes/job_description_card.html, itou/www/siaes_views/forms.py
=> Correction HTML

itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/www/apply/tests/tests_list.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Empty-state-du-r-sultat-de-recherche-Candidature-employeurAction-af2f1367e35a49428baeac31fe30f052?pvs=4
Amélioration UI et UX
=> Amélioration UI/UX pour aucun résultat de recherche "Candidature"

itou/static/js/formset_add_remove_row.js, itou/templates/includes/members.html, itou/templates/invitations_views/create.html, itou/www/signup/forms.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Refonte-page-inviter-un-collaborateur-dde527070c7c44a6bdd2a8bd36154287?pvs=4
Amélioration de l'UI du formulaire d'invitation de collaborateurs.
Améloration de l'UX/UI de la liste des actions dans le tableau de liste des collaborateurs 
Avant
Apres
---
Avant
Apres
=> Amélioration UX/UI page inviter un collaborateur

itou/templates/approvals/includes/status.html, itou/templates/signup/includes/peamu_button.html
Parce que du HTML bien formaté, c'est mieux.
=> Les corrections HTML du jour

itou/templates/apply/list_for_job_seeker.html, itou/templates/dashboard/includes/job_seeker_job_applications_card.html, itou/templates/layout/_header.html
=> Mise à jour wording des boutons de recherche

itou/templates/dashboard/dashboard.html
Meilleure organization de l’espace.
=> Grouper les badges prescripteurs sur le tableau de bord

itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/eligibility.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/application/resume.html, itou/templates/apply/submit/create_or_update_job_seeker/step_1.html, itou/templates/apply/submit/create_or_update_job_seeker/step_2.html, itou/templates/apply/submit/create_or_update_job_seeker/step_3.html, itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, itou/templates/apply/submit_step_check_prev_applications.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/apply/submit_step_job_seeker_check_info.html, itou/templates/apply/submit_step_pending_authorization.html, itou/templates/siaes/job_description_card.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/A11Y-D-p-t-d-une-candidature-Autoaudit-fa3cdf9181ca4926b56f0fb95ce76a42?pvs=4
Amélioration de l'accessibilité du parcours "Dépot de candidature"
Corrections des erreurs liées aux points :
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#6.1
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#8.2
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#8.9
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9.1
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.5
- https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.6
=> Corrections liées à l'autoaudit d'accessibilité lot#03

itou/templates/dashboard/dashboard.html, itou/templates/dashboard/edit_user_email.html, itou/templates/dashboard/includes/job_seeker_job_applications_card.html, itou/templates/dashboard/includes/prescriber_job_applications_card.html, itou/templates/dashboard/includes/prescriber_organisation_card.html, itou/templates/dashboard/includes/stats.html, itou/templates/home/home.html, itou/templates/siaes/card.html, itou/templates/siaes/includes/_card_siae.html, itou/www/dashboard/forms.py, itou/www/home/tests.py
Diverses améliorations réalisées lors de la journée tech avec les UX.
=> Boost UI/UX

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/www/apply/views/submit_views.py
Pour simplifier et faire comme dans les autres vues/templates.
=> Petits nettoyages sur le parcours de candidatures

itou/templates/approvals/detail.html
[Carte Notion](https://www.notion.so/plateforme-inclusion/6d2f772966114bc98fefc6ef17df79c0?v=99352c5142224ce8995dcc6ea3a78337&p=b068ef7f5a3449268014fd3d60198a36&pm=c)
[Proposition d'amélioration d'Antoine P.](https://itou-inclusion.slack.com/archives/CQ6C3LSAH/p1682512559169699?thread_ts=1682511260.150009&cid=CQ6C3LSAH)
=> Carte du PASS IAE : ajout d'icônes

itou/metabase/db.py
**Fil slack : https://itou-inclusion.slack.com/archives/C050D9JNJ9Z/p1683887044392079?thread_ts=1683837006.366749&cid=C050D9JNJ9Z**
Le précédent fix https://github.com/betagouv/itou/pull/2508 n'a pas suffit, on s'est repris l'erreur cette nuit.
On supprime en cascade les vues staging obsolètes vu que de toute façon elles pointent toutes vers une donnée obsolète.
Aucun indicateur Metabase ne sera cassé car ils pointent tous vers des tables `marts` et non des vues `staging`.
=> Pilotage : Airflow : suppression des vues obsolètes à chaque mise à jour de données

itou/www/apply/tests/tests_submit.py, itou/www/apply/urls.py, itou/www/apply/views/submit_views.py
nettoyage & suite de #2459 & 40d017b8e952dc301
=> Candidature: suppression des anciens chemins sans PK de candidat & de récupération de la PK dans la session

itou/www/apply/forms.py, itou/www/apply/tests/tests_forms.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=8d3218d540304fc49adf170dbf71c119&pm=c
Demande FFGEIQ / DGEFP (c’est temporaire en 2024 on limitera à un mois)
=> BOOST: les GEIQ peuvent embaucher rétroactivement

itou/employee_record/admin.py, itou/employee_record/tests/test_sanitize_employee_records.py, itou/templates/employee_record/disable.html, itou/templates/employee_record/includes/create_step_1.html, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/reactivate.html, itou/templates/employee_record/summary.html, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/views.py
1. Texte pouvant porter à confusion, on essaye autre chose :)
2. Moins de _warning_ lors du lancement des tests
3. Simplification et correction d'un lien "Retour" au passage
=> Fiches salarié : Quelques corrections en mode BOOST

itou/www/signup/tests/test_siae.py, itou/www/signup/urls.py, itou/www/signup/views.py
Addresses an old todo. It’s been 184 days, more than the planned 7 days.
=> Remove fallback code from SiaeBaseView

itou/templates/approvals/detail.html, itou/users/models.py, itou/utils/perms/middleware.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/views.py
Partiellement lié à https://www.notion.so/plateforme-inclusion/Associer-les-diagnostic-aux-PASS-IAE-116db83de976432e93b94474631c7401
=> Nettoyage de vieux fixmes

itou/allauth_adapters/peamu/client.py, itou/analytics/tests/test_collect_analytics_data_management_command.py, itou/approvals/migrations/0005_fill_approvals_eligibility_diagnoses.py, itou/approvals/tests/test_management_commands.py, itou/common_apps/organizations/views.py, itou/employee_record/constants.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/scripts/management/commands/import_pe_approvals.py, itou/scripts/management/commands/merge_pe_approvals.py, itou/siae_evaluations/tests/tests_models.py, itou/siaes/factories.py, itou/siaes/management/commands/move_siae_data.py, itou/siaes/tests/test_management_commands.py, itou/users/tests/test_management_commands.py, itou/utils/storage/s3.py, itou/utils/sync.py, itou/utils/test.py, itou/utils/tests.py, itou/www/apply/forms.py, itou/www/apply/tests/tests_submit.py, itou/www/employee_record_views/views.py, itou/www/siaes_views/views.py
Trop facile de se rater quand on déplace du code
=> Remplacement de la majorité de l'interpolation en %-style par des f-string ou `.format()`

itou/www/signup/views.py
The org.add_member() should also be protected against database errors.
Hotfix.
https://itou.sentry.io/issues/4230654009/?project=6164438&query=is%3Aunresolved&referrer=issue-stream&stream_index=23
=> prescriber_join_org: Elargir le bloc atomic()

itou/templates/apply/list_for_job_seeker.html, itou/templates/approvals/includes/job_description_list.html, itou/templates/dashboard/includes/dora_card.html, itou/templates/dashboard/includes/job_seeker_job_applications_card.html, itou/templates/dashboard/includes/siae_card.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/templates/dashboard/includes/siae_job_applications_card.html, itou/templates/dashboard/includes/stats.html, itou/templates/search/siaes_search_results.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Harmonisation-des-icones-783d16e56ad744d3adb57c5ca7018beb?pvs=4
Harmonisation de certaines icones du dashboard
=> Harmonisation des icones

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html, itou/www/dashboard/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Contr-le-a-posteriori-m-j-du-Tableau-de-bord-SIAE-77ed7912c46a45a19b852ed979a339c3
=> Control a posteriori: adaptation du tableau de bord des SIAEs

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py
Sentry : https://itou.sentry.io/issues/4239256440/?project=6164438&referrer=assigned_activity-email
=> Limiter inclusion connect aux prescripteurs et employeurs 

itou/templates/siae_evaluations/includes/siae_infos.html
Le contrôle est déjà assez compliqué :sweat_smile:
=> Contrôle a posteriori: simplification d'un template

CHANGELOG.md
=> Changelog :  sprint 64

itou/metabase/tables/evaluated_siaes.py, itou/siae_evaluations/enums.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/includes/siae_infos.html, itou/templates/siae_evaluations/institution_evaluated_siae_list.html, itou/www/siae_evaluations_views/tests/__snapshots__/tests_institutions_views.ambr
Continuer de simplifier le code.
=> Contrôle a posteriori: suppression de l'état NOTIFICATION_PENDING

itou/templates/approvals/detail.html, itou/www/approvals_views/tests/__snapshots__/test_detail.ambr, itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/views.py
**[Carte Notion](https://www.notion.so/plateforme-inclusion/En-tant-qu-employeur-je-souhaite-pouvoir-cl-turer-un-PASS-IAE-apr-s-12-mois-cons-cutifs-de-suspensio-64412311adee49e79fb39da453e88c90)**
Cf le ticket.
On ajoute un bouton sur la page Détail d'un PASS.
=> En tant qu’employeur je souhaite pouvoir clôturer un PASS IAE après 12 mois consécutifs de suspension

CHANGELOG.md
Pour dire tout ce qu'on a fait !
=> Changelog: sprint 65

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Depuis la page Message & CV, pour avoir un chemin linéaire.
Le comportement actuel fonctionne car `not self.siae.is_subject_to_eligibility_rules` est vrai pour les GEIQ et l'utilisateur est donc redirigé vers l'étape  `Métiers recherchés` mais il dans le cas d'un prescripteur habilité cela le fait donc revenir 2 étapes en arrière au lieu d'une seule.
=> Parcours de candidature: permettre le retour sur la vue d'Eligibilité GEIQ

itou/www/dashboard/tests.py, itou/www/dashboard/views.py
- https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=6da2c1120be34a5890cd53599240b3b4&pm=c
- https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=03285b099322414c8efea24cc2834ecf&pm=c
Ajout d'un message d'information invitant les prescripteurs sans organisation à se rattacher une organisation de prescripteur existante (si nécessaire).
Ce message est différent pour certains employés de Pôle emploi enregistrés comme orienteurs sur la plateforme.
=> BOOST: Ajout d'un message invitant les orienteurs à rejoindre une organisation (si pertinent)

itou/users/admin.py, itou/users/tests/test_admin.py
=> profils demandeur d'emploi : Rendre visible la certification Pole Emploi

itou/templates/dashboard/includes/stats.html
- Suspension temporaire de certaines stats : https://www.notion.so/plateforme-inclusion/Rendre-invisible-les-liens-Voir-les-donn-es-IAE-de-mon-d-partement-dans-le-c1-76069d1903bb4e9d82c82851ff2ac2f8
- Harmonisation des icones des liens stats : https://itou-inclusion.slack.com/archives/C04SAGUGJFJ/p1686029575148079
=> Boost stats

Makefile, itou/utils/management/commands/loaddata_bulk.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Un-r-gime-pour-les-fixtures-3aec2252c5c9405abe9e009211756b59**
Les performances, détails dans le message de commit.
=> Créer une commande de gestion pour charger les données en masse

Makefile, itou/siae_evaluations/fixtures.py
L’exécution locale affiche:
```
Traceback (most recent call last):
File "/home/freitafr/dev/itou2/itou/siae_evaluations/fixtures.py", line 21, in <module>
django.setup()
File "/home/freitafr/dev/itou2/.venv/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/freitafr/dev/itou2/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
self._setup(name)
File "/home/freitafr/dev/itou2/.venv/lib/python3.11/site-packages/django/conf/__init__.py", line 72, in _setup
raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable …
```
=> Ajouter DJANGO_SETTINGS_MODULE et définir PYTHONPATH aux siae_evaluations.fixtures

itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/views.py
**[Carte Notion](https://www.notion.so/plateforme-inclusion/En-tant-qu-employeur-je-souhaite-pouvoir-cl-turer-un-PASS-IAE-apr-s-12-mois-cons-cutifs-de-suspensio-64412311adee49e79fb39da453e88c90)**
Ceci est un petit correctif lié à l'interprétation du ticket ci-dessus.
Il semblerait que ce soit passé au travers des tests et de la recette, mais pour etre honnête je n'étais pas totalement certain d'avoir entièrement compris tous les cas applicables du ticket.
Il se trouve que le support Itou permet de préciser, donc on corrige.
En n'affichant pas le bouton pour le cas remonté par le support.
=> PASS IAE : Modifier légèrement la règle de gestion de l'affichage du bouton de suppression

CHANGELOG.md
is:pr is:merged merged:>2023-06-19 -label:no-changelog -label:dependencies
=> CHANGELOG Sprint 66

itou/templates/approvals/includes/status.html, itou/templates/employee_record/list.html, itou/templates/siae_evaluations/email/to_siae_sanctioned_subject.txt, itou/templates/siae_evaluations/evaluated_siae_sanction.html, itou/templates/siaes/card.html, itou/templates/siaes/includes/_job_description_details.html, itou/templates/siaes/includes/_list_siae_actives_jobs.html, itou/templates/siaes/job_description_card.html, tests/www/siae_evaluations_views/test_views.py, tests/www/siaes_views/test_views.py
=> Utilisation de `pluralizefr` partout

itou/approvals/models.py, itou/templates/approvals/detail.html, itou/www/approvals_views/views.py, tests/www/approvals_views/test_detail.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=a6c18d44aef94b25af9ab88f9d0047b7&pm=c
Besoin métier
=> BOOST : toutes les SIAE peuvent effectuer une prolongation (si la candidature est disponible dans leur tableau de bord)

itou/approvals/models.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Afficher-l-ligibilit-IAE-sur-la-liste-des-candidatures-2ae374e0d88d444d867fb1a05061463d**
Évite de scanner 450K lignes pour une condition qui ne peut pas arriver.
=> Retrait d’une condition impossible de PoleEmploiApproval.find_for

tests/approvals/tests.py
=> Correction de ApprovalModelTest.test_remainder

itou/approvals/enums.py, itou/approvals/models.py, itou/employee_record/models.py, itou/prescribers/management/commands/merge_organizations.py, itou/templates/approvals/declare_prolongation.html, itou/templates/utils/toasts.html, itou/utils/context_processors.py, itou/utils/templatetags/theme_inclusion.py, itou/www/approvals_views/forms.py, tests/approvals/tests.py, tests/www/approvals_views/test_prolongation.py
Vu pendant #2727, je les sort pour simplifier la relecture.
=> Corrections mineures, diverses et variés

itou/approvals/models.py
=> Retire une vieille logique de CommonApprovalMixin.is_valid()

itou/job_applications/admin.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Corrections-et-investigation-des-probl-mes-de-performance-li-s-aux-candidatures-425b910a002240c995254f883f7254d2**
C’était bien trop lent.
=> Amélioration des performances de l’admin candidatures

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/commands/populate_metabase_matomo.py
Bon, voilà quoi...
Bonne remarque de Romain.
In da commit.
=> metabase crons: Ajout de moniteurs sentry

tests/www/search/tests.py
=> Correction d’assertions dans test_pec_display

tests/www/approvals_views/test_detail.py
=> Mettre à jour les requêtes de TestApprovalDetailView.test_approval_status_includes

CHANGELOG.md
=> CHANGELOG: sprint 67

config/settings/base.py
Retour des zolies cartes dans l'admin
=> admin: fix CSP for OpenStreetMap

clevercloud/cron.json
=> cron: Garder les lignes dans leur ordre d'exécution

itou/settings_viewer/templates/settings/list.html, itou/templates/admin/base_site.html, itou/templates/admin/prescribers/change_form.html, itou/templates/apply/process_accept.html, itou/templates/apply/submit/create_or_update_job_seeker/step_base.html, itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/printable_approval.html, itou/templates/dashboard/api_token.html, itou/templates/employee_record/list.html, itou/templates/invitations_views/create.html, itou/templates/invitations_views/includes/pending_invitations.html, itou/templates/layout/base.html, itou/templates/layout/base_printable.html, itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_results.html, itou/templates/siaes/job_description_card.html, itou/templates/siaes/job_description_list.html, itou/templates/stats/stats.html, itou/templates/stats/stats_pilotage.html, itou/templates/utils/widgets/csp_proof_openlayers-osm.html, pyproject.toml, tests/utils/__snapshots__/tests.ambr
=> Use djlint to format CSS and JS

itou/approvals/models.py, tests/approvals/tests.py
:facepalm: 
Les demandes déjà acceptées seront corrigées manuellement.
=> Correctement lié la prolongation à sa demande lors de sa création

itou/approvals/admin.py, itou/approvals/models.py
Suite à des besoins rencontrés lors de l'utilisation de l'admin afin de suivre le bon fonctionnement sur la PROD.
=> Prolongations - Admin : Autres améliorations rapides suite à la MEP

clevercloud/cron.json, itou/approvals/management/commands/prolongation_requests_chores.py, itou/approvals/migrations/0013_prolongationrequest_reminder_sent_at.py, itou/approvals/models.py, itou/approvals/notifications.py, itou/templates/approvals/email/prolongation_request/created_reminder_body.txt, itou/templates/approvals/email/prolongation_request/created_reminder_subject.txt, itou/utils/emails.py, tests/approvals/__snapshots__/test_notifications.ambr, tests/approvals/__snapshots__/test_prolongation_requests.ambr, tests/approvals/test_notifications.py, tests/approvals/test_prolongation_requests.py
- https://www.notion.so/plateforme-inclusion/Accepter-par-d-faut-les-demandes-de-prolongation-sans-r-ponse-depuis-de-30-jours-ab86f6c9a8854a59977d7e9db3cf27b8?pvs=4
- https://www.notion.so/plateforme-inclusion/Email-de-relance-J-7-tous-les-membres-d-une-organisation-si-une-demande-de-prolongation-n-a-pas-c8b8de8c5b5c4e268336dbae62ad1871?pvs=4
Dépend de #2727, tout les commits ne sont donc pas à relire ;).
Ne pas laisser des demandes de prolongation sans réponse.
=> PASS IAE - Demandes de prolongation : Taches récurrentes

itou/job_applications/admin.py
À pousser plus loin. Je ne faisais que passer.
=> BOOST : modification (en passant) de quelques descriptions dans l'admin des candidatures

clevercloud/crons/populate_metabase_emplois.sh, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/prolongation_requests.py, itou/metabase/tables/prolongations.py, itou/metabase/tables/utils.py, tests/approvals/factories.py, tests/metabase/management/test_populate_metabase_emplois.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-er-un-tableau-de-bord-de-pilotage-des-demandes-de-prolongations-4327e4e093ba45db91bb0b1df6c13ee9**
Suite à la refonte du système des prolongations du C1.
=> Metabase : Injections des prolongations et de leurs demandes

itou/templates/dashboard/includes/siae_card.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Homog-n-iser-les-tags-25ff799c5ac244238e9716964c5bd7cb
Parce que c'est demandé gentiment
=> Fix ux/ui badge "action requise"

CHANGELOG.md
=> CHANGELOG: sprint 68

tests/eligibility/test_iae.py
=> Découper EligibilityDiagnosisManagerTest

itou/users/models.py
=> Nettoyage: suppression d'un appel de fonction inutile

itou/www/apply/views/process_views.py, tests/siaes/factories.py, tests/www/apply/__snapshots__/test_process.ambr, tests/www/apply/test_process.py
Correction d'une faille remontée pendant l'audit de sécurité.
=> Correction d'une faille XSS

itou/templates/apply/process_accept.html, itou/templates/apply/process_base.html, itou/templates/apply/process_cancel.html, itou/templates/apply/process_details_prescriber.html, itou/templates/apply/process_details_siae.html, itou/templates/apply/process_eligibility.html, itou/templates/apply/process_postpone.html, itou/templates/apply/process_refuse.html, itou/templates/eligibility/includes/form.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Am-liorer-le-DOM-dans-les-templates-apply-process-32d143724c1c4c99a9e136b01e5c9a5a?pvs=4
Selon les états/etapes de la candidature, un affichage de `<section class="s-section"></section>` vide pouvait etre présent dans le DOM des templates
Changement du mode d'extend de `apply_base.html` via un nouveau block `{% block content_extend %}`
Amélioration de quelques zone de boutons de formulaire en passant
=> Amélioration de l'affichage des templates apply/process_

itou/templates/apply/includes/_submit_title.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_of_available_exports.html, itou/templates/approvals/list.html, itou/templates/approvals/prolongation_requests/list.html, itou/templates/dashboard/includes/job_seeker_job_applications_card.html, itou/templates/dashboard/includes/labor_inspector_organization_card.html, itou/templates/dashboard/includes/prescriber_job_applications_card.html, itou/templates/dashboard/includes/prescriber_organisation_card.html, itou/templates/dashboard/includes/siae_card.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/templates/dashboard/includes/siae_job_applications_card.html, itou/templates/prescribers/edit_organization.html, itou/templates/siaes/show_financial_annexes.html, tests/www/dashboard/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Utiliser-des-verbes-sur-tous-les-liens-du-tableau-de-bord-harmoniser-les-vos-boost-6cef587a82d9448fb95c4e571842f873?pvs=4
Pour homogénéiser
=> Utiliser des verbes dans les liens du tableau de bord

itou/www/apply/views/process_views.py, tests/www/apply/__snapshots__/test_process.ambr, tests/www/apply/test_process.py
Ajout de test et correction dans le cas d'un contrat "Autre"
=> Parcours de candidature: correctif sur le formulaire d'acceptation GEIQ

itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/create_or_update_job_seeker/step_base.html, itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, itou/templates/apply/submit_base.html, itou/templates/apply/submit_base_two_columns.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_check_prev_applications.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/apply/submit_step_job_seeker_check_info.html, itou/templates/apply/submit_step_pending_authorization.html, itou/templates/approvals/includes/card.html
Pour faire suite a cette PR https://github.com/betagouv/itou/pull/2872
Selon les états/etapes de la candidature, un affichage du container `<section class="s-section"></section>` pouvait etre en trop
Changement du mode d'extend de `submit_base.html` via un nouveau block `{% block content_extend %}`
En passant :
- Amélioration de quelques zone de boutons de formulaire 
- Ajout de section de titre oubliées dans des templates avec des `<section class="s-section-twocolumns">`
=> Amélioration de l'affichage des templates apply/submit_

itou/approvals/admin.py, itou/common_apps/organizations/admin.py, itou/eligibility/admin.py, itou/institutions/admin.py, itou/invitations/admin.py, itou/prescribers/admin.py, itou/siae_evaluations/admin.py, itou/siaes/admin.py
TODO + vu au détour des derniers passage dans l'admin :).
=> Admin : Corrections de code diverses et variées

tests/conftest.py
pour de jolis diff dans `assertMessages` & `assertSoupEqual`
=> tests: update register_assert_rewrite

tests/www/apply/test_process.py
=> Ajout d'un test vérifiant la cohérence htmx du formulaire d'acceptation de candidature

itou/approvals/models.py
=> Ajout d’un commentaire à propos d’Approval.suspended_until

itou/www/approvals_views/views.py, tests/www/approvals_views/test_prolongation_requests.py
[LES-EMPLOIS-PROD-XM](https://itou.sentry.io/issues/4387771758/)
=> Demandes de prolongation : Correction d'une N+1

itou/templates/apply/includes/_submit_title.html, itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, tests/www/apply/test_submit.py
https://www.notion.so/plateforme-inclusion/wording-du-titre-des-pages-d-clarer-l-embauche-de-d2d29507a08c45b098d264c0a82e0784?pvs=4
https://www.notion.so/plateforme-inclusion/plusieurs-wording-ccda8665df424d3b839dd3c545a9ba4c?pvs=4
=> Parcours de candidature: wording

itou/templates/eligibility/includes/form.html
https://www.notion.so/plateforme-inclusion/plusieurs-wording-ccda8665df424d3b839dd3c545a9ba4c?pvs=4
=> Validation d'éligibilité: wording

itou/approvals/models.py, itou/scripts/management/commands/deduplicate_asp_approvals.py, itou/siae_evaluations/models.py, itou/siaes/admin.py, itou/www/approvals_views/forms.py, tests/www/apply/test_edit.py, tests/www/apply/test_process.py
=> Utiliser le formatage des f-strings plutôt que `strftime()`

itou/users/models.py, itou/utils/perms/middleware.py
=> Utilisateurs: suppression des propriété "is_siae_staff_with_siae" & "has_pole_emploi_email"

itou/templates/static/legal/privacy.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Mise-jour-politique-de-confidentialit-boost-dec716eeb6fe460fb53547a6211282c1?pvs=4
=> Mise à jour de la politique de confidentialité

itou/utils/apis/metabase.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Publication-de-notre-nouvelle-page-stats-boost-43f845d2fd2e4a85aed4df54e2f3fe24?pvs=4
Voir la page /stats qui affiche le nouveau tableau de bord
=> Publication de notre nouvelle page stats

itou/approvals/models.py, itou/utils/validators.py, itou/www/approvals_views/forms.py, tests/approvals/__snapshots__/test_notifications.ambr, tests/approvals/factories.py, tests/approvals/tests.py, tests/www/approvals_views/__snapshots__/test_prolongation.ambr, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation.py
Erreur de ma part lors du merge originel de #2914  :confounded:.
=> Remerge #2914 : Renouvellement des prolongations par périodes d’un an

tests/api/applicants_api/tests.py
Vérifier qu'une modif ne fait pas exploser le nombre de requêtes (par exemple le déplacement des champs `birth_place` & `birth_country`)
=> Ajout  d'un test comptant les requêtes sur l'applicants_api

itou/www/apply/forms.py, itou/www/approvals_views/forms.py, itou/www/dashboard/forms.py, itou/www/employee_record_views/forms.py, itou/www/prescribers_views/forms.py, itou/www/siaes_views/forms.py
Cohérence, facilité de navigation dans la base de code.
=> Réordonner les déclarations des ModelForm

itou/metabase/dataframes.py, itou/siaes/management/commands/_import_siae/utils.py
Les fichiers de la semaine du 28/08/2023 posent problème : 
- Les archives .gz contenues dans le fichier `fluxIAE_*.zip` ne sont pour la majorité pas des gzip, mais des pkzip (on ne sait pas si c'est définitif ou non, mais autant être compatible avec les 2 formats au cas où cela se reproduise)
- Lors de la conversion en CSV du dataframe, certaines cellules n'étaient pas échappées correctement ce qui faisait planter l'import.
=> Correction import Fluxiae

itou/approvals/models.py, tests/approvals/tests.py
https://github.com/betagouv/itou/pull/2914#discussion_r1301705745
=> Clarifier la signature de Prolongation.has_reached_max_cumulative_duration

itou/employee_record/models.py, tests/api/employee_record_api/tests.py
[LES-EMPLOIS-PROD-108](https://itou.sentry.io/issues/4458217630/)
=> API - FS : Correction d'une N+1

itou/templates/static/legal/privacy.html
https://mattermost.incubateur.net/betagouv/pl/khrupaa9kjftd8m1zep4t5wgza
=> Mettre à jour la politique de confidentialité pour diriger vers CleverCloud

tests/utils/tests.py
Sinon, la ligne n'est pas exécutée.
=> tests: uncomment assertion

itou/templates/layout/_header_nav_primary_items.html, itou/www/dashboard/urls.py, itou/www/dashboard/views.py, tests/www/dashboard/tests.py
Moins de code, moins de problème.
=> Entête: factorisation du HTML

scripts/create-fast-machine.sh
=> fix: ensure local `master_clever` branch is up-to-date before creating a fast-machine

itou/templates/apply/includes/rdv_insertion_promo_card.html, tests/www/apply/__snapshots__/test_list.ambr
=> BOOST: Changement de lien pour "RDV insertion"

itou/www/siaes_views/views.py, tests/www/siaes_views/test_job_description_views.py
Pour corriger les bêtises de #3027
=> [Hotfix] Les candidats ne peuvent plus voir les fiches de poste

itou/api/siae_api/viewsets.py, itou/siaes/models.py, tests/siaes/test_models.py
Il n'était plus utilisé qu'à un seul endroit.
=> Suppression de prefetch_job_description_through

itou/scripts/management/commands/fill_updated_at.py
=> Script préparatoire : Ne plus avoir de champs combinant auto_now=True et null=True

itou/templates/apply/includes/list_card_body_siae.html, tests/www/apply/__snapshots__/test_list.ambr
Joffrey a remarqué mon erreur sur les tailles de badges. Merci Joffrey 👍  
https://www.notion.so/plateforme-inclusion/5-4-Refonte-carte-candidature-employeur-petite-boostinette-14289125206f4aab98b5208787df1fb7?d=726c03583056456c9e38577295514f47
=> Correction de la taille des badges Pass IAE

CHANGELOG.md
Journal des changements - sprint 72
=> CHANGELOG: sprint 72

Makefile, docker/dev/django/Dockerfile, docker/dev/django/entrypoint.sh, docs/Docker.md
=> Simplifier la construction du virtualenv

tests/www/api/tests.py
cf https://github.com/betagouv/itou/pull/3042#discussion_r1336357400 sans aucun test qui plante.
=> tests: ajout d'un test pour la page d'accueil de l'API

itou/www/apply/forms.py, itou/www/apply/views/submit_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Am-liorer-la-compatibilit-de-l-envoi-des-fichiers-c4cfcdb49db64ebca1b80fec141539ba**
Travail préparatoire pour https://github.com/betagouv/itou/pull/3069.
=> Réusinage de SubmitJobApplicationForm

itou/siae_evaluations/migrations/0007_evaluationcampaign_calendar.py, itou/siae_evaluations/models.py
https://itou.sentry.io/issues/4517418543/?project=6164438&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
=> Correction de l'admin d'évaluation des campagnes à postériori

itou/templates/employee_record/includes/employee_record_summary.html, tests/www/employee_record_views/test_summary.py
Petit oubli dans be5b9960a858b9b54fa3e55be1f583895685778c & #2967
=> Correction du lieu de naissance sur le détail d'une fiche salarié

itou/approvals/models.py, itou/www/approvals_views/views.py, tests/approvals/tests.py, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_list.py
https://itou.sentry.io/issues/4468943450/?project=6164438&query=is%3Aunresolved&referrer=issue-stream&stream_index=5
=> Améliorations des performances

itou/templates/approvals/prolongation_requests/list.html, itou/templates/approvals/prolongation_requests/show.html, itou/www/approvals_views/views.py, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/En-tant-que-prescripteur-habilit-qui-visualise-une-demande-de-prolongation-je-vois-le-nom-du-prescr-7a56f8be36ed40b0b01d66f0590eef5a
Voir à qui la demande de prolongation a été adressée
=> approvals: Add prolongation request recipient

itou/api/data_inclusion_api/serializers.py, itou/api/data_inclusion_api/views.py, tests/api/data_inclusion_api/tests.py
https://itou.sentry.io/issues/4514148277/?project=6164438&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
=> Correction d'un 1+N dans l'api des structures

itou/siaes/management/commands/move_siae_data.py, tests/siaes/test_management_commands.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Support-C1-Move-SIAE-data-complet-Mode-1-faire-le-30-09-b6bf213af1c84757b43c8d0977274056?d=d6a283c4a7674e27b3eebb2f8d945daf**
=> Ne pas toucher aux EvaluatedSiae lors d’un move_siae_data

itou/www/approvals_views/views.py, tests/www/approvals_views/test_prolongation_requests.py
Erreur sentry : [LES-EMPLOIS-PROD-12P](https://itou.sentry.io/issues/4510572790/)
=> www - demandes de prolongation : Correction de la redirection pour les utilisateurs non-connecté

config/settings/base.py
Cf. le message de commit pour les explications détaillées.
=> settings : Nettoyer des settings inutilisés

itou/templates/dashboard/includes/prescriber_job_seekers_card.html
voir https://itou-inclusion.slack.com/archives/C03ES35UL30/p1696328527785069?thread_ts=1696326677.985159&cid=C03ES35UL30
=> Suppression d'un badge "nouveau" du dashboard

itou/utils/staticfiles.py
Pas besoin de dire que tout va bien.
=> Fichiers static: réduction de la verbosité du collectstatic

itou/www/prescribers_views/views.py
https://itou.sentry.io/issues/4527623975/?project=6164438&referrer=github-pr-bot
=> Correction d'une typo dans le code

itou/external_data/tasks.py, tests/openid_connect/pe_connect/tests.py
-> https://itou.sentry.io/issues/4388532001/?project=6164438&query=is%3Aunresolved&referrer=issue-stream&stream_index=1
=> Utilisation de huey.contrib.djhuey.on_commit_task() sur les tâche de synchro peamu

tests/www/prescribers_views/test_list.py
Une vue testée c'est moins de bug en production.
Cf #3153
=> tests: ajout des tests pour la vue list_accredited_organizations

itou/templates/apply/includes/buttons/new_diagnosis.html, itou/templates/apply/includes/buttons/refuse.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/BOOST-correction-d-une-faute-de-frappe-sur-la-page-candidature-co-8128d283f0904efc9bea5f1f1852493e?pvs=4
=> Correction d'une coquille

tests/www/approvals_views/test_prolongation.py
=> Nettoyage de www.approval_views.test_prolongation

itou/job_applications/models.py, itou/templates/apply/includes/siae_hiring_actions.html, tests/job_applications/test_transfer.py, tests/www/apply/test_process.py
**Carte Notion : ** https://www.notion.so/061d460f790a4d12b02ffb1f58fa723e?v=e8eb76e87cdd409e924980b2c721d8a2&p=5921cbd6d1b349b9a84d18635d448c0b&pm=s
=> Ajout d'actions pour les nouvelle candidatures

itou/templates/invitations_views/create.html, itou/www/invitations_views/views.py, tests/www/invitations_views/test_prescriber_organization.py, tests/www/invitations_views/test_siae_accept.py, tests/www/invitations_views/test_siae_send.py
C'était une bonne idée de vouloir afficher le nom de la structure.
=> Création d'invitations: correction du sous-titre

docs/coding-style.md
Autant que les règles soient publiques pour tous.
=> Importer et MAJ le style de programmation de itou-private

itou/www/approvals_views/forms.py, tests/www/approvals_views/test_prolongation.py
=> Demande de prolongation : ne pas proposer les organisations a laquelle un prescripteur n'appartient plus

itou/utils/management/commands/loaddata_bulk.py
=> Amélioration de la commande `loaddata_bulk`

itou/siae_evaluations/migrations/0013_remove_evaluatedadministrativecriteria_proof_url.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Am-liorer-la-compatibilit-de-l-envoi-des-fichiers-c4cfcdb49db64ebca1b80fec141539ba**
=> Retirer le champ EvaluatedAdministrativeCriteria.proof_url

itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html, tests/www/siae_evaluations_views/test_siaes_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Mauvais-statut-lorsque-la-SIAE-a-s-lectionn-ses-crit-res-en-phase-contradictoire-6567b6936bdc446cb81734fac24013c9?pvs=4
=> Contrôle a posteriori: amélioration d'un statut en phase 3

itou/templates/employee_record/list.html, itou/www/employee_record_views/views.py
Pour corriger une erreur lors de la migration du nouveau thème
Avant
Apres
=> FIX: employee records badge classmane

config/settings/base.py, config/settings/dev.py, itou/utils/logging.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/test.txt, tests/users/test_management_commands.py
=> Mise en place logs datadog

itou/openid_connect/inclusion_connect/urls.py, itou/openid_connect/inclusion_connect/views.py, tests/openid_connect/inclusion_connect/tests.py
On n'en a plus besoin à présent :champagne:
=> inclusion_connect: Nettoyage de code de migration à Keycloak

.github/ISSUE_TEMPLATE/bug_request.md, .github/ISSUE_TEMPLATE/feature_request.md
Ajout de gabarits pour les issues github
prototyper la gestion des tâches dans un projet github
=> [PROTO] issue templates

itou/templates/siaes/show_financial_annexes.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/ui-ux-Adapter-le-tableau-Annexes-financi-res-8e209b25f856491588d6dcc9143b579a?pvs=4
Respect du thème et harmonisation des tables
Avant
Apres
=> Amélioration UI de la liste des annexes financières

config/urls.py
Laissé temporairement dans #3227
=> siaes->companies: Nettoyage des urls après quelques jours

config/settings/base.py
Le setting est activé en prod depuis 10 mois
=> Utilisation de connections persistantes 

itou/templates/apply/submit/create_or_update_job_seeker/step_1.html
=> JS: Ajout d'un guillemet manquant

itou/templates/apply/includes/accept_section.html, itou/templates/apply/includes/buttons/archive.html, itou/templates/apply/includes/transfer_job_application.html, itou/templates/apply/submit/create_or_update_job_seeker/step_1.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/includes/demo_accounts.html, itou/templates/signup/includes/no_email_link.html, tests/www/apply/test_submit.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/ui-harmonisation-de-positionnement-des-modales-5a00031e8093426ab34c6b915d5e3475?pvs=4
Harmonisation du positionnement par ajout du centrage vertical
Harmonisation de la taille et des couleurs des boutons d'action
=> Harmonisation des modales

.vscode/launch.json
lancer l'app `django` en mode debug dans `vscode`
mise à jour `.vscode/launch.json`
=> (vscode settings): debug django app

itou/users/admin.py, tests/users/test_admin_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/BOOST-Ajouter-une-commande-dans-l-admin-pour-les-changements-de-comptes-6e0c0c076c404cceac8481f8d374c23a?pvs=4
Pour ne pas avoir à passer par un dev
=> Permettre au support de "libérer" une adress e-mail quand un employeur veut devenir prescripteur (ou l'inverse)

.vscode/settings.json
https://github.com/VSCodeVim/Vim/issues/4017#issuecomment-1714557940
Merci à Antoine, mais je pense que c'est aussi bien commité.
=> vscode settings : Add vim compatibility workaround

itou/static/css/itou.css, itou/templates/dashboard/dashboard.html, tests/www/dashboard/__snapshots__/tests.ambr, tests/www/dashboard/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Test-refonte-C1-Cr-ation-d-un-lien-Maze-sur-la-homepage-des-employeurs-336604c0938d4e44a80e0057cc4083eb?d=5276ae5a0f3f456fa93d5c130cd18bec
=> Test refonte C1 - Création d’un lien Maze sur la homepage des employeurs

itou/templates/approvals/list.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, tests/www/approvals_views/test_list.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/URGENT-En-tant-qu-employeur-je-veux-identifier-rapidement-les-PASS-IAE-qui-expirent-bient-t-84c55b692aee4445a33ca6704ec7ecf0?pvs=4
Leur permettre de faire les demandes de prolongations à temps, ou d'accompagner le salarié pour la suite
/!\ ne pas encore relire, les tests ne sont pas encore écrits
=> En tant qu’employeur je veux identifier rapidement les PASS IAE qui expirent bientôt

itou/templates/siaes/edit_job_description_preview.html, itou/templates/siaes/edit_siae_preview.html
Identifier précisement des evènements pour la construction d'objectifs et d'entonnoirs dans matomo
* mise à jour des informations de la fiche  structure
```
class="matomo-event" 
data-matomo-category="employeurs" 
data-matomo-action="submit" 
data-matomo-option="publier-infos-structure"
```
* ajouter une offre de poste
```
class="matomo-event" 
data-matomo-category="employeurs" 
data-matomo-action="submit" 
data-matomo-option="publier-fiche-poste"
```
=> [ENTONNOIR] ajout d'evenements pour configurer les entonnoirs

itou/templates/dashboard/dashboard.html, itou/templates/utils/toasts.html, itou/templates/welcoming_tour/includes/message.html, itou/www/apply/views/common.py, itou/www/apply/views/process_views.py, itou/www/companies_views/views.py, itou/www/employee_record_views/views.py, itou/www/invitations_views/views.py, itou/www/siae_evaluations_views/views.py, tests/www/apply/__snapshots__/test_process.ambr, tests/www/invitations_views/test_siae_send.py, tests/www/welcoming_tour/tests.py
https://www.notion.so/plateforme-inclusion/2-X-Alertes-Changer-certaines-banni-res-infos-alertes-par-des-toasts-08b03248ac7149c7be247c3ecb576db4?pvs=4
⚠️ requiert la #3149 
Trop de bannière annule leur impact pour l’utilisateur. Résultat ils ne lisent plus les messages et ça nuit à l’expérience globale. 
- Transformer certaines bannières qui ont un rôle plutôt de réassurance  en toasts. 
- En profiter pour ajuster certains contenus (wording) 
⏰ messages HTMX dans métiers et recrutements : KO pour le moment
Créer une fiche de poste
Supprimer une fiche de poste
Envoyer des invitations (SIAE)
désactivation fiche salarié
candidature acceptée
candidature transférée
candidature : embauche annulée
bloquer les candidatures
débloquer les candidatures
=> Changer certaines bannières infos/alertes par des toasts

itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
C'est plus simple à relire si on récupère toujours l'info de la même façon.
=> Tableau de bord: harmonisation du template

tests/openid_connect/inclusion_connect/tests.py, tests/openid_connect/pe_connect/tests.py, tests/utils/tests.py, tests/www/apply/test_geiq.py, tests/www/apply/test_submit.py, tests/www/companies_views/test_job_description_views.py, tests/www/companies_views/test_views.py, tests/www/dashboard/tests.py, tests/www/employee_record_views/test_create.py, tests/www/employee_record_views/test_disable.py, tests/www/employee_record_views/test_list.py, tests/www/employee_record_views/test_reactivate.py, tests/www/home/tests.py, tests/www/invitations_views/test_company_accept.py, tests/www/invitations_views/test_prescriber_organization.py, tests/www/prescribers_views/test_members.py, tests/www/search/tests.py, tests/www/siae_evaluations_views/test_siaes_views.py, tests/www/signup/test_prescriber.py, tests/www/signup/test_siae.py, tests/www/welcoming_tour/tests.py
Pour détecter plus de problèmes à peu de frais.
=> Réduction du nombre de tests ne testant pas leurs templates

itou/invitations/models.py, itou/templates/approvals/detail.html, itou/templates/companies/edit_job_description.html, itou/templates/invitations_views/new_ic_user.html, itou/templates/siae_evaluations/siae_select_criteria.html, itou/templates/siae_evaluations/siae_upload_doc.html, itou/www/approvals_views/views.py, itou/www/siae_evaluations_views/views.py, tests/www/approvals_views/test_detail.py, tests/www/companies_views/test_job_description_views.py, tests/www/companies_views/test_views.py, tests/www/dashboard/tests.py, tests/www/invitations_views/test_company_accept.py, tests/www/invitations_views/test_prescriber_organization.py, tests/www/siae_evaluations_views/test_siaes_views.py
Pour l'instant j'ai fait ceux qui me semblaient triviaux à corriger :angel:
=> Plus de nettoyage de ignore_template_errors

itou/analytics/approvals.py, itou/approvals/management/commands/send_approvals_to_pe.py, itou/approvals/models.py, itou/utils/apis/pole_emploi.py, tests/analytics/test_approvals.py, tests/approvals/factories.py, tests/approvals/test_notify_pole_emploi.py
https://www.notion.so/plateforme-inclusion/Notification-PE-des-changements-de-date-des-PASS-IAE-bba5d340115d456291cc97b7987f9d08?pvs=4
Pour que pole emploi dispose des données à jour.
=> Notification des PASS IAE supprimés à pole emploi

CHANGELOG.md
Pour montrer ce qu'on a fait durant ce sprint.
=> CHANGELOG: Sprint 75

itou/templates/static/accessibility.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Landing-du-GIP-R-daction-sch-ma-pluriannuel-d-accessibilit-bonus-c48c04fa863442119fdf63fbe41bc798?pvs=4
Mise à jour du contenu de la déclaration d'accessibilité afin d'ajouter le paragraphe concernant le schéma pluriannuel du GIP
=> Mise a jour du contenu de la déclaration d'accessibilité

itou/templates/static/accessibility.html
Mise a jour des urls de téléchargement de pdf et correction d'un mauvais copier / coller de la phrase d'intro.
=> Correctif du contenu de la déclaration d'accessibilité 

itou/static/css/itou.css, itou/templates/layout/base.html, tests/www/dashboard/__snapshots__/tests.ambr, tests/www/dashboard/tests.py
période de collecte des avis terminées
=> [dashboard] retrait du sondage maze

itou/approvals/management/commands/reset_pe_notification_status_for_date_updates.py
Date à corriger puis script à merger et lancer après le déploiement de https://github.com/gip-inclusion/les-emplois/pull/3383
=> PASS IAE: ajout d'un script pour repasser les PASS modifées en PENDING

itou/users/models.py, tests/users/test_models.py
Elle n'est plus utilisée nulle part.
=> Utilisateurs: suppression de la property inutilisée is_orienter

itou/templates/apply/submit_step_check_job_seeker_nir.html
Vu dans une capture d'écran d'un TZ.
=> Candidature : Correction des attributs Matomo ajoutés dans le `href`

itou/job_applications/admin_forms.py, tests/job_applications/test_admin.py
https://itou.sentry.io/issues/4680217436/
=> admin: mieux gérer les entrées invalides lors de la création de candidature

itou/templates/dashboard/edit_user_info.html
Pour que ce soit plus joli :art:
=> dashboard: adaptation du HTML du formulaire d'édition de profil

itou/templates/dashboard/includes/prescriber_job_seekers_card.html, itou/templates/dashboard/includes/prescriber_organisation_card.html, itou/www/dashboard/views.py
Pour (je l'espère) la rendre un peu plus lisible et bien séparer les différents cas en fonction du type d'utilisateur car je compte bientôt rajouter un `elif request.user.is_job_seeker:`...
=> Réusinage de la vue du tableau de bord

itou/utils/staticfiles.py
Mise à jour du thème vers la v1.1.4
Corrections pour le `.btn-partner`
=> Maj du theme itou vers la v1.1.4

tests/conftest.py
=> tests: correction de l'incompatibilité entre pytest-django & pytest-randomly

itou/job_applications/models.py, itou/www/apply/forms.py, itou/www/apply/views/list_views.py, tests/job_applications/tests.py, tests/www/apply/test_list.py
Pour faciliter l'ajout d'annotations conditionnelles aux filtres ce qui sera utile pour le correctif du filtre "Éligibilité validée"
=> Liste de candidatures: réusinage du formulaire des filtres / Comptabilité entre PASS IAE Actif & Suspendu

itou/approvals/admin.py, itou/approvals/admin_views.py, itou/templates/admin/approvals/change_list_with_stats.html, itou/templates/admin/approvals/send_approvals_to_pe_stats.html, tests/approvals/test_admin.py
Pour avoir rapidement un résumé de la situation.
=> approvals: ajout dans l'admin d'une page de stats concernant la synchronisation des PASS IAE avec PE

itou/templates/apply/includes/job_applications_filters/criteria.html, itou/templates/apply/includes/job_applications_filters/dates.html, itou/templates/apply/includes/job_applications_filters/departments.html, itou/templates/apply/includes/job_applications_filters/eligibility_validated.html, itou/templates/apply/includes/job_applications_filters/job_seekers.html, itou/templates/apply/includes/job_applications_filters/pass.html, itou/templates/apply/includes/job_applications_filters/selected_jobs.html, itou/templates/apply/includes/job_applications_filters/sender.html, itou/templates/apply/includes/job_applications_filters/to_companies.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/www/apply/forms.py, tests/www/apply/__snapshots__/test_list.ambr, tests/www/apply/test_list.py
=> [GEN-7780] Supprimer le filtre statut du PASS IAE dans la page de liste des candidatures pour les employeurs HORS IAE

.env.template, Makefile, scripts/restore_latest_backup.sh
Suite à la dernière journée dev.
=> [GEN-7755] Ajout d'une commande pour récupérer la dernière sauvegarde de Scaleway

itou/eligibility/models/geiq.py, itou/eligibility/models/iae.py, itou/job_applications/models.py, itou/www/apply/forms.py, itou/www/apply/views/process_views.py, tests/www/apply/test_list.py
C'est plus pratique qu'il fonctionne.
=> [GEN-3536] Correction du filtre "Éligibilité à valider"

itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/list.html, itou/templates/employee_record/summary.html, tests/www/employee_record_views/__snapshots__/test_list.ambr, tests/www/employee_record_views/test_summary.py
Quelques corrections et améliorations au passage, et ajout de plus d'informations technique en vue du changement de la clause d'unicité.
=> Fiches salariés :  Améliorations et corrections UI/UX pour la page de listing et de détails

tests/job_applications/factories.py, tests/users/factories.py, tests/www/employee_record_views/test_create.py
Réduire le nombre de factories.
=> tests: fusion de JobSeekerWithAddressFactory & JobSeekerWithMockedAddressFactory

itou/templates/apply/email/diagoriente_job_seeker_invite_body.txt, itou/templates/apply/email/diagoriente_prescriber_invite_body.txt, itou/templates/apply/submit/application/resume.html, itou/templates/dashboard/includes/diagoriente_card.html, itou/templates/dashboard/includes/job_seeker_job_applications_card.html, tests/www/apply/test_process.py, tests/www/apply/test_submit.py, tests/www/dashboard/tests.py
=> Changement de l'URL pour Diagoriente [GEN-7831]

itou/templates/companies/includes/_card_jobdescription.html, itou/templates/companies/includes/_card_siae.html
=> [Boost] Correction des 2 types de badges [GEN-7822]

.vscode/settings.json
=> Mise à jour des settings `vscode` avec le passage à la version `1.85.1`

itou/templates/account/includes/login_form.html, itou/www/login/forms.py
=> [GEN-7877] Suppression du lien en double "Mot de passe oublié ?"

itou/templates/apply/includes/job_applications_filters/departments.html, itou/templates/apply/includes/job_applications_filters/selected_jobs.html, itou/www/apply/forms.py, tests/www/apply/__snapshots__/test_list.ambr
Pour que ce soit un peu plus compact.
=> [GEN-7556] Modification du widget des départements et fiches de poste dans la recherche de candidatures

itou/users/admin.py, tests/users/test_admin_views.py
https://itou.sentry.io/issues/4843254110/
=> admin: amélioration des performances sur la page de l'utilisateur

itou/templates/layout/_header.html, itou/utils/staticfiles.py
Carte Notion : https://www.notion.so/plateforme-inclusion/A11Y-Am-liorer-le-disclosure-du-menu-burger-83d44660792446d19a33acf98f2cc505?pvs=4
Mise à jour du thème vers la v1.1.7
Mise à jour du bouton burger pour corriger un défaut d'accessibilité
=> Maj du theme itou vers la v1.1.7 et de l'a11y du bouton burger

itou/templates/apply/includes/eligibility_diagnosis.html, itou/templates/apply/includes/geiq/geiq_diagnosis_details.html, itou/templates/apply/includes/job_application_answers.html, itou/templates/apply/includes/job_application_diagoriente_invite.html, itou/templates/apply/includes/job_application_info.html, itou/templates/apply/includes/job_application_sender_info.html, itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/includes/out_of_band_changes_on_job_application_state_update_siae.html, itou/templates/apply/includes/siae_hiring_details.html, itou/templates/apply/includes/transition_logs.html, itou/templates/apply/process_base.html, itou/templates/apply/process_details.html, itou/templates/apply/process_details_company.html, itou/templates/approvals/detail.html, itou/templates/approvals/includes/status.html, itou/templates/companies/includes/_list_siae_actives_jobs_row.html, itou/templates/companies/includes/_siae_jobdescription.html, itou/utils/templatetags/job_applications.py, tests/utils/__snapshots__/tests.ambr, tests/www/apply/__snapshots__/test_list.ambr, tests/www/apply/test_edit.py, tests/www/apply/test_process.py, tests/www/approvals_views/__snapshots__/test_includes.ambr, tests/www/companies_views/__snapshots__/test_views.ambr, tests/www/dashboard/__snapshots__/tests.ambr
**Carte Notion :** https://www.notion.so/plateforme-inclusion/2-3-page-candidature-Am-liorer-la-hi-rarchisation-des-donn-es-dans-la-page-de-d-tail-de-candidatur-9d17131d0d4641f291528720d1f9e867
Clarifier les écrans de détail des candidatures 
Amélioration UI des templates
Avant
Apres
=> Améliorer la hiérarchisation des données dans la page de détail de candidature

itou/job_applications/admin.py, itou/job_applications/admin_forms.py, itou/job_applications/migrations/0001_initial.py, itou/job_applications/models.py
Car ce n'est pas forcément clair en l'état.
=> [GEN-7531] Amélioration de la disposition des champs concernant l'origine d'une candidature

tests/users/factories.py
=> Correction de JobSeekerProfileFactory

itou/static/css/itou.css, itou/templates/search/includes/prescribers_search_form.html, itou/templates/search/includes/siaes_search_form.html, itou/utils/staticfiles.py, itou/www/autocomplete/views.py, itou/www/search/forms.py, tests/www/autocomplete/tests.py, tests/www/search/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/C1-Suppression-de-jQuery-UI-680d46411c3f4972ad1c113765924453?pvs=4
Pour avoir un endroit de moins où l'on utilise jQuery-UI
=> Rechercher un emploi/des prescripteurs: utilisation de select2 pour l'auto-complétion

itou/templates/apply/includes/siae_card.html, itou/templates/apply/process_details.html, itou/templates/apply/submit/application/base.html, itou/templates/apply/submit_base_two_columns.html, itou/templates/approvals/prolongation_requests/show.html, itou/templates/companies/edit_siae.html, itou/templates/companies/edit_siae_preview.html, itou/templates/companies/includes/_siae_details.html, itou/templates/companies/includes/_siae_info.html, itou/templates/companies/job_description_card.html
**Carte Notion: ** https://www.notion.so/plateforme-inclusion/Refonte-UX-UI-Box-structure-2cea300c343e496bbb60313480cdc4b3?pvs=4
Amélioration de l'affichage des infos de structure
Mise en place de la `.c-box--structure`
https://zeroheight.com/85c89893b/p/96e94f-box/b/995f63/t/413122
=> Refonte UX/UI - Modification de la box des infos structure 

CHANGELOG.md
Pour savoir rapidement ce qui a été modifié pendant le sprint.
=> Changelog Sprint 79

itou/templates/search/includes/siaes_search_filters.html, itou/www/search/forms.py, itou/www/search/views.py, tests/www/search/tests.py
Pour trouver une entreprise plus rapidement.
=> [GEN-7849] Ajout du filtre nom à la recherche d'entreprise

itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, tests/www/approvals_views/test_list.py
Parce que le message d'erreur affiché actuellement n'a pas lieu d'être.
=> [GEN-7993] Liste des PASS IAE: correction du filtre "Fin du parcours en IAE" en combinaison avec la pagination

tests/www/employee_record_views/__snapshots__/test_add.ambr, tests/www/employee_record_views/test_add.py
https://github.com/gip-inclusion/les-emplois/actions/runs/7781914332/job/21217283785
=> Modification d'un test instable

itou/approvals/enums.py, itou/approvals/migrations/0016_prolongationrequestdenyinformation.py, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Car sinon les utilisateurs ont tendance à choisir un autre motif, ne correspondant pas à ce motif.
:warning: En attente du merge de https://github.com/gip-inclusion/pilotage-airflow/pull/245
=> [GEN-7930] Ajouter un nouveau motif de refus de prolongation (motif pas adapté)

itou/static/css/itou.css, itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html, itou/templates/search/includes/generic_search_home.html, itou/templates/search/includes/prescribers_search_form.html, itou/templates/search/includes/siaes_search_form.html, itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_results.html, itou/utils/staticfiles.py, itou/www/search/forms.py
Modification de la barre de recherche principale. 
Sur le Home et sur les pages de resultat de recherche
Avant
Apres
=> Mise a jour de l'UI de la recherche principale

itou/templates/layout/base.html, tests/utils/__snapshots__/tests.ambr
As Xavier pointed out, it should be loaded after the `trackPageView`.
=> layout/base : Use matomoMore to track visible content

tests/api/applicants_api/tests.py
Merged before the update for
https://github.com/gip-inclusion/les-emplois/pull/3616/files#r1482776191
was pushed.
=> Ajout d’un commentaire dans ApplicantsAPITest.test_rate_limiting

tests/users/test_management_commands.py
Cette branche de code n'est actuellement pas testée (et j'avais donc oublié une modif à faire pour le déplacement du champs nir).
=> tests: ajout d'un test pour le cas difficile de la commande deduplicate_job_seekers

CHANGELOG.md
Pour voir rapidement ce qu'on a fait.
=> changelog: sprint 80

itou/www/apply/views/process_views.py, tests/www/apply/test_process.py
Soulager cette pauvre base de données.
=> Moins de requêtes SQL pour details_for_company

itou/www/dashboard/urls.py, itou/www/dashboard/views.py, tests/www/dashboard/tests.py
Faire moins de requête en DB (et supprimer du code obsolète)
=> Modifier mon profile: nettoyage, réduction des requêtes & ajout de tests

itou/www/apply/views/process_views.py, tests/www/apply/test_process.py
Trop de requêtes font pleurer la base de données.
=> Moins de requêtes pour details_for_jobseeker
