gip-inclusion/les-emplois

itou/templates/approvals/suspend.html, itou/www/approvals_views/forms.py
Now all the "Siae accessible reasons" for a suspension are within the list of reasons allowing an unsuspend, so we can remove some complicated logic.
Also, keep loading the datepicker now.
=> Suspension des PASS IAE: simplification du gabarit

.pre-commit-config.yaml
Utiliser les linters du venv pour [pre-commit](https://pre-commit.com/)
Éviter les incohérences entre la version déclarée dans la configuration
de pre-commit et celle déclarée dans requirements/dev.txt.
Ce changement s’attend à ce que les linters soient présents dans le
`PATH`.
---
Une PR ultérieure pourrait harmoniser la construction du venv localement
(e.g. make + [pip-tools](https://pypi.org/project/pip-tools/)) pour
figer (et idéalement `hash`er) les requirements et améliorer la
“reproducibilité” des vens entre les machines de dev (et la prod 🎉), et
utiliser les linters situé à un endroit conventionnel (e.g. `.venv`)
pour éviter de dépendre du `PATH`.
=> Utiliser les linters du venv pour pre-commit

itou/templates/siae_evaluations/institution_evaluated_siae_list.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
There must be an evaluated SIAE, otherwise get_list_or_404 would return
a 404 response.
Take that opportunity to simplify the context: pass in the campaign.
=> Remove dead code from institution_evaluated_siae_list

itou/employee_record/tests/tests_models.py, itou/users/models.py
Correction rapide suite a erreur 500 possible sur la geoloc
Le modele JobSeekerProfile jette directement des erreurs de geoloc en cas de non résolution de la commune
On transforme les erreurs de géoloc de `users.JobSeekerProfile` en `ValidationError` qui sont correctement gérées coté interface.
- Pas de revue : hotfix. 
- Les autres erreurs de geoloc seront gérées par : https://github.com/betagouv/itou/pull/1611
=> HOTFIX: rattrapage de toutes les erreurs de geoloc du modèle User

Makefile
Utilise requirements/dev.in pour MacOS
L’application est déployée uniquement sous Linux. MacOS n’est actuellement pas compatible avec la version pinnée, avec contrôle d’intégrité des dépendances. Pour MacOS et les plateformes non supportées, une spécification moins précise des dépendances est utilisée.
=> Utilise requirements/dev.in pour MacOS

README.md
Retrait des instructions concernant “DJANGO_SECRET_KEY” du README
Ces instructions ne sont plus utiles, une bonne valeur par défaut a été choisie dans bd61a67522aa80870b1b0631fa1434b74c623576.
=> Retrait des instructions concernant “DJANGO_SECRET_KEY” du README

itou/asp/factories.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/tests/tests_management_commands.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/siaes/factories.py, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/list.html, itou/www/employee_record_views/views.py
Transmettre les notifications d’actualisation de date de PASS IAE lorsqu’on prolonge ou suspend un PASS IAE qui n’est pas concerné par les fiches salariés (import agrément via module PE ou PASS IAE obtenu avant le 27/09/2021)
Actuellement lorsqu’un utilisateur prolonge ou suspend un PASS IAE qui n’a pas généré de fiche salarié , les nouvelles dates du PASS IAE ne sont jamais transmises dans l’ASP.
1. Ajout de ces cas à la liste des "nouvelle" FS avec une UI spécifique afin de permettre leur création, le parcours de création reste inchangé.
2. Ajout d'une règle générique au moment de l'ingestion du fichier de retour de l'ASP :
_Lors du premier envois de la FS, si l'ASP nous dit que c'est un doublon 3436 et que nous avons une suspension ou prolongation alors on demande l'envois d'une …
=> Transmission de la date de fin pour les PASS IAE sans fiches salariés

itou/static/js/split_nir.js, itou/templates/apply/submit_step_job_seeker.html
Bien que cela n'a pas d'impact techniquement c'est, à juste titre, déroutant.
Remplacement du filtre django `format_nir` par l'utilisation du JS déjà existant dans `split_nir.js`.
=> Correction du formatage du NIR lors du dépôt de candidature

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
Supprime les `cached_property` de quelques méthodes du contrôle a posteriori
`can_review` et `should_select_criteria` utilisent `state`, qui est une `cached_property`. Ces deux méthodes ne sont pas “chères” et ne méritent pas un cache.
=> Supprime les `cached_property` de quelques méthodes du contrôle a posteriori

itou/templates/siae_evaluations/includes/criterion_validation.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
Autorise la modification des justificatifs pendant la revue de la phase contradictoire
Auparavant, durant la phase contradictoire, cliquer sur le bouton Accepter ou Refuser sur la page de revue des justificatifs pour une candidature enregistrait immédiatement le résultat, sans laisser la possibilité à l’utilisateur de Modifier le justificatif.
Maintenant, tant que la revue n’est pas validée par la DDETS, l’utilisateur peut changer la pièce justificative.
=> Autorise la modification des justificatifs pendant la revue de la phase contradictoire

itou/siae_evaluations/constants.py, itou/siae_evaluations/models.py, itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/institution_evaluated_job_application.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/templates/siae_evaluations/siae_job_applications_list.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
Mode lecture seule pour les campagnes de contrôle a posteriori terminées
Les campagnes de contrôle a posteriori terminées étaient masquées dans l’interface. Les utilisateurs y accédant par les URLs recevaient une erreur 404. L’objectif est de montrer les résultats de la campagne. Ultérieurement, la notification de sanction sera ajoutée à la liste des résultats.
=> Mode lecture seule pour les campagnes de contrôle a posteriori terminées

config/settings/base.py
Utilisation du moteur d'e-mail Anymail, synchrone, en recette jetable et en fast machine car on n'a pas besoin de plus. Je lance le débat !
Les recettes jetables nous permettent de tester que les fonctionnalités fonctionnent comme en prod. Pour cela, l'environnement doit s'en rapprocher le plus possible fonctionnellement parlant. Concrètement, si je dois tester un nouveau contenu d'e-mail, je veux pouvoir le faire.
Concernant les fast machines, c'est plus discutable. Je m'attends à ce que les scripts envoient effectivement des e-mails car l'environnement est presque celui de la prod.
=> Envoi des e-mails en synchrone en recette jetable et en fast machine

itou/openid_connect/france_connect/tests.py, itou/openid_connect/france_connect/views.py, itou/openid_connect/models.py, itou/www/approvals_views/tests/test_pe_approval.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/login/tests.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/tests/test_siae.py
Meilleur prise en charge du cas où un utilisateur a 2 comptes, un django, un France connect, et change son email sur france connect en utilisant celui du compte django.
On lui affiche un bandeau d'erreur lui disant de se rapprocher du support.
- etc.
=> Erreur propre en cas de changement d'email sur France Connect + conflit sur les emplois

itou/templates/dashboard/dashboard.html
Ajustement du bandeau Dora dans le dashboard
Le bandeau Dora et le bandeau Nouveau statistiques et pilotage" prennent beaucoup de hauteur et repoussent trop loin la ligne de flottaison comme décrit sur cette carte https://www.notion.so/R-duire-la-taille-du-bandeau-Dora-b6f0218cf71e43839cfd4aed37bb4e24
En jouant sur l'espacement entre les bandeaux, en changeant le format du bandeau "Nouveau statistiques et pilotage", en le passant dans la zone des alertes conditionnelles et en le rendant refermable
=> Ajustement du bandeau Dora dans le dashboard

itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html
Le `{{ filters_form.media.js }}` ne servait en fait pas que pour le date picker :)
Avec le bug  : 
Une fois corrigé (aka comme avant la regression):
=> templates: Fix regression on Select2MultipleWidget

Makefile, README.md, docker/dev/postgres/maintenance/backup, docker/dev/postgres/maintenance/backups, docker/dev/postgres/maintenance/clean, docker/dev/postgres/maintenance/restore, scripts/import-latest-db-backup.sh
Utilisation de [la « nouvelle » version de Docker compose](https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command) au lieu de l'ancien projet qui est déprécié.
Pragmatiquement, pour faire marcher mon environnement local qui ne contient plus docker-compose.
=> Renommer docker-compose en docker compose

itou/external_data/admin.py
Retirer une page de l'admin qui ne fonctionne pas (trop de FK à charger dans un champ du formulaire d'édition).
Comme elle ne marche pas depuis un moment, personne ne l'utilise, ni n'en voit l'usage. Autant la supprimer.
La page ne charge pas (chargement trop long)
=> Suppression de JobSeekerExternalDataAdmin

itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/samples_selection.html
Mise à jour du tableau de bord “Sélectionner l’échantillon”
Remplace le titre par le nom de la campagne, pour mieux distinguer des campagnes récemment terminées.
=> Mise à jour du tableau de bord “Sélectionner l’échantillon”

Makefile
Autorise populate_db à charger plusieurs bases de données
Le nom "itou" était forcé, mais le développeurs peuvent vouloir charger plusieurs bases de données en même temps.
=> Autorise populate_db à charger plusieurs bases de données

itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/www/apply/forms.py
Remplacement d'une boucle de sous-requêtes par des clauses `WHERE`.
Dans mes tests on passe de ~8s à moins de 200ms.
Ralentissement notable et généralisé du site.
Cette page à d'autre problème de performance qui couvent mais je n'ai pas trouvé de moyen simple de les corriger :
1. Le `.prefect_related()` de `.with_list_related_data()` récupère pour toutes les candidatures (ie: 3k+) et pas juste celles filtrées (ie: 500+)
https://github.com/betagouv/itou/blob/80e56f1f9d71a84cf4feb5bf101ba5c63f19bc72/itou/www/apply/views/list_views.py#L115-L117
2. `.with_has_suspended_approval()` fait aussi une boucle de sous-requête mais il y a moins d'objet donc ça devrait tenir pour le moment
https://github.com/betagouv/itou/blob/80e56f1f9d71a84cf4feb5bf101ba5c63f19bc72/itou/job_applications/models.py#L154 …
=> Amélioration des performances pour le filtre "PASS IAE actif" pour le listing des candidatures

itou/users/models.py
Affichage des noms et prénoms des utilisateurs dans l'admin (au lieu de juste l'email).
le nom et le prénom du candidat n’est pas visible sur la page du PASS dans l’admin
Attention : cela impacte TOUTES les pages de l'admin.
- etc.
=> Amélioration de l'affichage des utilisateurs sur la page d'admin des pass IAE

Makefile
Lancer pip-sync seulement sous Linux
pip-sync vérifie que seuls les dépendances listées dans un requirements.txt sont installées. Sur les plateformes utilisant le requirements.in comme `REQUIREMENTS_FILE`, le résultat de pip-sync est la désinstallation de nombreuses dépendances.
Refs 7f9f4a86251bc67b2c1eec0bf339d39fb9ac43ac,
https://github.com/betagouv/itou/pull/1571#pullrequestreview-1140870562
=> Lancer pip-sync seulement sous Linux

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py
Réparation de l’envoi d’email pour les campagnes de contrôle a posteriori
La représentation textuelle de l’objet utilisateur peut contenir des caractères sortant de l’ASCII, ce qui n’est pas valide pour une adresse email. Selon les heuristiques des bibliothèques, l’email pouvait être accepté ou non. Autant se conformer au reste du système et utiliser le champ `email`.
=> Réparation de l’envoi d’email pour les campagnes de contrôle a posteriori

itou/siae_evaluations/enums.py
Inclut les AI dans la campagne de contrôle a posteriori 2022
Règlementaire.
=> Inclut les AI dans la campagne de contrôle a posteriori

itou/job_applications/enums.py, itou/job_applications/migrations/0044_alter_jobapplication_refusal_reason.py
Ajout de la raison de refus “candidature en doublon”
C’est une raison fréquemment citée par les employeurs, qui cochaient “autre” jusqu’à maintenant.
=> Ajout de la raison de refus “candidature en doublon”

requirements/dev.txt
6c41b355a33119f0c193e08b8c49aafab0914ac1 n’a mis à jour que la version de base.txt (la plus importante), autant utiliser la même version de Django dans les environnements de développement.
=> Mise à jour de la version Django dans requirements/dev.txt

itou/static/js/siae_evaluations_sample_selection.js, itou/templates/siae_evaluations/samples_selection.html, itou/www/siae_evaluations_views/forms.py
Utilisation de Bootstrap pour afficher/masquer la sélection du ratio de contrôle a posteriori
Améliore l’accessibilité du code, permet d’avoir les transitions et de faciliter la maintenance en retirant un peu de de code JavaScript.
[Screencast from 10-24-2022 11:47:43 AM.webm](https://user-images.githubusercontent.com/2758243/197500069-0b8e2c90-27b5-44d6-b497-41aebb02c976.webm)
=> Utilisation de Bootstrap pour afficher/masquer la sélection du ratio de contrôle a posteriori

itou/siae_evaluations/admin.py, itou/siae_evaluations/enums.py, itou/siae_evaluations/factories.py, itou/siae_evaluations/migrations/0011_evaluatedsiae_notification.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/email/to_siae_sanctioned_body.txt, itou/templates/siae_evaluations/email/to_siae_sanctioned_subject.txt, itou/templates/siae_evaluations/evaluated_siae_sanction.html, itou/templates/siae_evaluations/includes/siae_infos.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/templates/siae_evaluations/institution_evaluated_siae_list.html, itou/templates/siae_evaluations/institution_evaluated_siae_notify.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/siae_evaluations_views/forms.py, itou/www/siae_evaluations_views/tests/test_views.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/urls.py, itou/www/siae_evaluations_views/views.py
Implémente le processus des sanction des campagnes de contrôle a posteriori
Après un résultat négatif d’évaluation, la DDETS applique des sanctions à la SIAE contrevenante. Les sanctions sont annoncées par une notification. Dans la liste des SIAE contrôlées, le système affiche maintenant “Notification à faire” là où “Résultat négatif” était affiché.
Lorsque l’utilisateur de la DDETS clique sur le bouton notifier, il est dirigé vers une page pour renseigner la raison principale du refus et les détails de la sanctions. Une fois la sanction enregistrée, un email est envoyé aux membres de la SIAE contrôlé pour annoncer la disponibilité des résultats sur leur tableau de bord.
Les membres de la SIAE peuvent alors se connecter et voir le résultat de la sanction.
=> Sanction des campagnes de contrôle a posteriori

itou/templates/dashboard/dashboard.html
Supprimer le bandeau pilotage actuellement visible dans le tableau de bord
- etc.
=> Supprimer le bandeau pilotage actuellement visible dans le tableau de bord

itou/templates/dashboard/dashboard.html
Fix intitulé du lien de sélection d’échantillon contrôle a posteriori
Mauvais rebase depuis 1f72729d69f4e3574b572fd605c5d7eefe4ec990, où le nouveau lien a été déplacé dans le `{% if prescriber %}`, où il ne pouvait jamais apparaître (un prescripteur n’est jamais une DDETS).
=> Fix intitulé du lien de sélection d’échantillon contrôle a posteriori

itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py
There must have been as mishap in a rebase somewhere, this is not supposed to happen :/
En attendant, cette commande crashe.
=> import_ea_eatt: Restaurer l'import timeit

itou/api/applicants_api/perms.py, itou/api/applicants_api/serializers.py, itou/api/applicants_api/tests.py, itou/api/applicants_api/views.py, itou/api/urls.py
Une API mise à disposition pour que les structures puissent récupérer la liste de leur candidats.
Demande métier et utilisateur.
- L'API ne demande pas de paramètre particulier,
- il est nécessaire d'utiliser les identifiants d'un compte administrateur de la structure pour pouvoir l'utiliser (via un token)
- endpoint : `/api/v1/candidats`
- redoc
- interface de test
=> API candidats

itou/metabase/management/commands/_approvals.py, itou/metabase/management/commands/_job_applications.py, itou/metabase/management/commands/_job_seekers.py, itou/metabase/management/commands/_utils.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/metabase/management/commands/sql/019_candidatures_echelle_locale.sql, itou/metabase/tests/test_approvals.py, itou/metabase/tests/test_job_applications.py
- Le champ `candidatures.nom_conseiller_pe` est renommé en `candidatures.nom_conseiller` et est maintenant aussi rempli pour les conseillers SPIP.
- Ajout du champ manquant `pass_agréments.id_candidat_anonymisé`.
- Utilisation de la méthode `hash_content` partout pour harmoniser.
- Ajout du champ `candidats.hash_nir` pour suivre quels candidats ont un NIR ou non, et plus tard croiser avec d'autres sources obfusquées de la même manière. Malheureusement non testé car sur la table problématique `job_seekers`.
Pour faire avancer le C2.
=> Boost pour le C2

itou/templates/apply/process_eligibility.html
Retirer le bandeau alerte dans l’écran de validation de l’éligibilité IAE par un employeur 
Ce n'est plus d'actualité 
Avant :
=> Boost - Retirer le bandeau alerte dans l’écran de validation de l’éligibilité IAE par un employeur 

itou/metabase/management/commands/sql/017_fiches_deposte_en_tension_recrutement.sql
Correction sur l'ajout des régions des structures. 
Sur la version précédente la région était prise à partir de la table candidatures plutôt que la table structure -> Générait des cellules vides.
=> fdp en tension : correction sur ajout régions

itou/approvals/management/commands/check_approvals_date.py
Les dates de début et/ou de fin d’un PASS IAE (`Approval()`) ne sont pas cohérentes avec celles de l’agrément Pôle Emploi (`PoleEmploiApproval()`) ayant le même numéro.
Le mode `--fix` ne corrige que les `Approval()` dont la date qui pose problème est également trouvée dans un `OriginalPoleEmploiApproval()` car dans ce cas précis on est certain de pouvoir corriger sans craindre d'écraser de la donnée modifiée suite à un `Suspension()`, un `Prolongation()` ou une intervention manuelle par exemple.
Quelques statistiques :
```shell
$ grep --count --extended-regexp "Approval [[:digit:]]+ " output.log
1834  # PASS IAE avec au moins 1 erreur
$ grep --count "End before the PoleEmploiApproval" output.log 
775  # PASS IAE dont la date de fin est antérieur à la date de fin de l'agrément
$ grep …
```
=> Ajout d'un script pour vérifier (et corriger) les dates des PASS IAE importés depuis un agrément PE

itou/approvals/admin.py, itou/utils/apis/api_entreprise.py, itou/utils/tests.py
1. La `KeyError` était levée quand un membre du groupe `itou-support-externe` voulais afficher un PASS IAE depuis l'admin.
2. Ajout d'un message plus métier pour les erreurs 403 de l'API Sirene.
=> [Supportix] Correction de deux erreurs sentry

itou/job_applications/models.py, itou/siae_evaluations/management/commands/patch_siae_emails.py, itou/siae_evaluations/models.py, itou/siaes/management/commands/import_siae.py, itou/utils/emails.py, itou/www/siae_evaluations_views/views.py
Ajout d’un utilitaire pour envoyer des emails
Centralise le motif souvent répété `mail.get_connection().send_messages([])`, avec l’utilisation d’un *context manager* pour une gestion plus claire de la connection.
=> Ajout d’un utilitaire pour envoyer des emails

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_siae_forced_to_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_forced_to_adversarial_stage_subject.txt
Envoi de notifications lors du passage forcé en phase contradictoire
6 semaines après le début d’une campagne de contrôle a posteriori, les SIAE n’ayant pas transmis leurs justificatifs passent en phase contradictoire. Ce changement permet de les informer par email.
=> Envoi de notifications lors du passage forcé en phase contradictoire

itou/templates/apply/list_of_available_exports.html, itou/templates/dashboard/dashboard.html
Changer de version d'icone de téléchargment de remix icon
Pour harmoniser avec le thème et répondre à cette demande UX
https://www.notion.so/Modifier-l-icon-download-2d03a2efc1164ee59f4191c4109badd6 
En remplacant la classe `ri-download-2-line` par `ri-download-line`
=> Remplacer l'icone de téléchargement

itou/employee_record/factories.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py
On ne propose plus de FS d'actualisation si une FS existe déjà pour cette SIAE et ce PASS IAE, l'existante fait foi.
Correction suite à f540bbe87.
=> Correction des doublons pour les fiches salariés d'actualisation

itou/approvals/admin.py
Génère une `TypeError: BaseModelAdmin.has_add_permission() takes 2 positional arguments but 3 were given`.
Commit responsable : 05d9167a8 :confounded:.
=> [FIX] Corrige une erreur dans la page d'admin pour les utilisateurs avec des droits limités

itou/asp/management/commands/check_asp_ref.py, itou/employee_record/admin.py, itou/employee_record/models.py, itou/employee_record/tests/tests_management_commands.py, itou/employee_record/tests/tests_models.py, itou/templates/employee_record/includes/list_item.html
1. Suppression du bouton "Voir le detail de la fiche salarié" quand la FS est dans l'état "Désactivée"
3. Ajout d'une action dans l'admin pour simplifier l'envois de "Notification de changement de la fiche salarié".
4. On stocke le JSON reçu et pas la représentation JSON du JSON pour l'archive ASP.
Pas de migration de données vu qu'on supprime l'archive au bout d'un moment et que l'information est tout de même présente même l'affichage est moche.
5. Ajout de la commande `check_asp_ref` pour faire la diff entre le contenu de la BDD et les fichiers de fixture.
Remonté par une erreur sentry, au final il n'y avais qu'une (1) commune qui posant problème.
=> [Supportix] Corrections et améliorations pour les fiches salariés

itou/metabase/management/commands/_approvals.py, itou/metabase/tests/test_approvals.py
Hotfix d'une erreur sur les Agréments PE.
Ma PR récente https://github.com/betagouv/itou/pull/1660 a malheureusement cassé le script quotidien d'injection des données C1 dans le C2 (aussi connu sous le nom de "populate_metabase_itou"). Mea culpa, je ne l'ai pas assez testée manuellement (j'ai zappé un dry run) et bien que j'ai écris des tests ils ne couvraient pas ce cas, ce qui est corrigé avec le test ajouté par cette PR.
=> [Metabase] Hotfix d'une erreur sur les Agréments PE

itou/templates/approvals/printable_approval.html, itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py
Effet de bord du chantier espace salarié : on utilise l'id du pass IAE au lieu d'une candidature, hors on peut avoir de multiples candidatures acceptées pour un même utilisateur et une même SIAE
=> Correction de l'affichage du PASS IAE

itou/siaes/models.py, itou/siaes/tests/tests_models.py
Il faut absolument (ce qui n'etait pas fait) que l'on vérifie aussi l'état actif de la SIAE sous-jacente, sinon cela n'a pas vraiment de sens.
Actuellement notre recherche d'emplois par fiche de poste affiche des offres actives qui sont liées à des SIAE inactives donc non listées.
=> SiaeJobDescription: correction de la méthode active()

config/settings/base.py
Privilégier `os.getenv()` à son équivalent `os.environ.get()` 
C'est la même chose (cf https://github.com/python/cpython/blob/v3.10.8/Lib/os.py#L772-L776), c'est plus court et surtout ça permet en cherchant `os.getenv` d'avoir toutes les variables d'environnement utilisables.
=> Utilisation d'os.getenv

requirements/deploy.in
Suppression du fichier https://github.com/betagouv/itou/blob/master/requirements/deploy.in
Il n'est plus utilisé depuis e597d88bb9305beefc25125ff9e39623269ef891
=> Suppression du fichier inutilisé deploy.in

requirements/dev.in, requirements/dev.txt
On base maintenant les dépendances de dev sur les versions utilisées en production.
Actuellement les deux résolutions (base.in -> base.txt et dev.in -> dev.txt) sont complètement indépendantes et avec un peu de malchance peuvent donc sélectionner des versions différentes pour des dépendances.
En dev, on veut toujours avoir les mêmes dépendances qu'en production, d'où le fait de se baser sur le fichier contenant toutes les dépendances de prod pinnées.
Cf aussi cf https://github.com/jazzband/pip-tools#workflow-for-layered-requirements
=> requirements: use the same pinned packages of base in dev

.github/workflows/ci.yml
Mise à jour de la v3 à la v4
On a des warnings de déprécation avec  la v3:
```
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
=> github: mise à jour de la version setup-python

itou/approvals/models.py, itou/approvals/tests/tests.py, itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/tests/test_prolongation.py
En tant qu’employeur qui cherche a déclarer un CDI inclusion, je ne peux pas demander la prolongation du PASS IAE 12 mois après la date de début du PASS IAE, je dois attendre 3 mois avant l’expiration du PASS IAE pour le faire, c’est assez complexe
Diminuer la friction utilisateurs dans l’enregistremnt du CDI inclusion pour des SIAE qui rencontrent déjà bcp de difficultés la dessus
Modifier le blocage actuel de 3 mois avant date de fin du PASS IAE à 12 mois après la date de début du PASS IAE pour permettre la déclaration d’une prolongation
=> Modification des règles de prolongation

.github/workflows/ci.yml, docker-compose.yml
Désactive certains mécanismes de postgresql assurant la durabilité des données.
Pour des tests un peu plus rapides:
- chez moi, ce n'est pas incroyable mais c'est toujours cela de pris: je passe de 43 sec en moyenne à 40 sec
- sur Github, vu la variabilité d'un build à l'autre, c'est assez dur à mesurer mais devrait grapiller quelques secondes également
(cf https://www.postgresql.org/docs/current/non-durability.html pour les sécurités désactivées).
=> postgres: moins de durabilité et plus de vitesse

itou/external_data/apis/pe_connect.py, itou/external_data/tests.py, itou/utils/slack.py, requirements/dev.in, requirements/dev.txt
`httpx` est majoritairement utilisé mais quelques utilisations de `requests` persistent.
:warning: Concernant les utilisations dans `itou/allauth_adapters/peamu`, la migration est plus compliqué car `django-allauth` (et son `OAuth2TestsMixin`) utilisent (et mockent) `requests`: cette PR ne s'occupe pas de cette partie.
Cela permet d'uniformiser notre code et de supprimer la dépendance `requests_mock` en faveur de `respx`.
=> requirements: migration de requests à httpx

.github/dependabot.yml, requirements/base.in
Active le bot `dependabot` pour avoir des PRs de mise à jour des dépendances automatiquement.
Pour [automatiser la gestion des dépendances](https://www.notion.so/Automatisation-de-la-gestion-des-versions-de-d-pendances-1ad38c9b15c247c9a01e8f2095346f71)
J'ai commencé à relâcher certains pins dans `base.in` afin que`dependabot` puisse trouver des choses à mettre à jour (en plus des dépendances de dev).
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file pour la doc
=> github: try enabling dependabot

itou/templates/approvals/declare_prolongation.html
Remplace les transitions jQuery UI par jQuery
Objectif : retirer jQuery UI à terme. Il ne reste “plus” que les autocomplete qui nécessitent jQuery UI.
[Screencast from 2022-11-09 15-19-56.webm](https://user-images.githubusercontent.com/2758243/200873069-05321b54-939a-474a-9529-f3a3a68e2202.webm)
=> Remplace les transitions jQuery UI par jQuery

itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/views.py
Si on ne trouve pas de candidature, on doit lever une 404 "proprement"
Lien sentry : https://sentry.io/organizations/itou/issues/3749177330/?project=6164438&query=is%3Aunresolved&referrer=issue-stream
=> Corriger une erreur sentry quand un utilisateur essaye d'afficher un PASS IAE

clevercloud/http.json, config/urls.py
Les pages 403 et 500 n’étaient jamais utilisées.
La page 404 n’est pas claire. D’après https://www.clever-cloud.com/doc/deploy/application/python/python_apps/, qui documente le format de `http.json` :
> error_pages: configure custom files for error pages
La directive "/404" n’est pas un fichier. Je m’attendais à ce que CleverCloud utilise la directive NGINX `error_page`, qui cause :
> an internal redirect to the specified uri with the client request
method changed to “GET”.
Mes tests sur la /review app/ révèlent un comportement différent, où la 404 de Django est affiché, y compris pour les URL commençant par /static/notfound. Au final, les fichiers statiques ne sont pas chargés directement par le client, mais par le navigateur à la lecture du fichier HTML (ce sont les fichiers JavaScript, …
=> Retrait des URLs de page d’erreur

itou/users/admin.py
Permettre de changer le username d'un nouvel utilisateur
Le support doit parfois créer des comptes candidats à la main dans l'admin
=> Permettre de changer le username d'un nouvel utilisateur

.github/workflows/antivirus-scan.yml
Récupération de l’historique git complet pour les analyses antivirus
L’action GitHub échoue avec :
> Failed to push your source code because your repository is shallow and
therefore cannot be pushed to the Clever Cloud remote.
=> Récupération de l’historique git complet pour les analyses antivirus

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/urls.py, itou/openid_connect/inclusion_connect/views.py
Dans le cas ou un utilisateur ne peut pas confirmer son email pour inclusion Connect (il ne reçoit pas l’email) il est complique de lui éviter de recommencer à 0 le processus de création de compte une fois qu’on valide l’email manuellement dans l’admin de Keycloak.
Simplifier la vie au support pour leur éviter de gérer le canal (prescripteur ou employeur, invité ou non, etc) dans la reponse à envoyer après avoir valider l'email dans l'admin d'Inclusion Connect
Ajouter une vue qui reprend les informations présentent dans la session.
=> Permettre à un utilisateur de reprendre sa création de compte via Inclusion Connect

itou/templates/search/includes/siaes_search_filters.html, itou/templates/search/siaes_search_results.html, itou/www/search/forms.py, itou/www/search/tests.py, itou/www/search/views.py
- Optimiser une requête qui sinon peut se révéler assez douloureuse
- Ajouter un filtrage des offres et structures par types de postes proposés
Demandes et attentes du métier, tout simplement.
=> Recherche de postes : Filtre des offres par type de contrat

itou/job_applications/models.py, itou/job_applications/tests/tests.py
Une candidature crée au statut acceptée est pour l'instant toujours listée en premier quand on cherche à connaître la dernière embauche d'un candidat, ce qui pose problème pour permettre la suspension de son pass.
On se base sur les transitions des candidatures, qui n'existent pas quand elles sont créées directement au statut acceptée. 
Ajout d'un cas pour les candidature sans transition.
=> Correction de la détection du dernier employeur

clevercloud/cron.json, clevercloud/evaluation_campaign_notifications.sh, itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/migrations/0012_evaluatedsiae_reminder_sent_at.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/test_management_commands.py, itou/templates/siae_evaluations/email/to_siae_notify_before_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_notify_before_adversarial_stage_subject.txt
Rappel aux SIAE n’ayant pas soumis de pièces justificatives à J+30
Inciter les SIAE à transmettre leurs pièces justificatives pendant la phase amiable du contrôle a posteriori.
=> Rappel aux SIAE n’ayant pas soumis de pièces justificatives à J+30

itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/employee_record/tests/tests_management_commands.py
La connexion SFTP n'est utile que pour `--upload` et `--download` pas pour `--preflight` ou `--archive`, sauf que actuellement `--archive` échoue si l'ouverture de la connexion SFTP échoue.
=> Commande `transfer_employee_records` : On n'ouvre plus de connexion SFTP en mode `--archive`

itou/approvals/models.py, itou/approvals/tests/tests.py
Gestion d’un pass sans candidatures acceptées dans l’admin
Lorsqu’un pass existe pour un candidat qui n’a pas de candidature acceptée, l’admin affichait une 500 lors de l’ajout manuel d’une suspension. La logique de `Suspension.clean()` gère déjà le cas où la prochaine date de disponibilité n’est pas définie, autorisons ce cas.
- https://sentry.io/organizations/itou/issues/2993609554/
=> Gestion d’un pass sans candidatures acceptées dans l’admin

itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_siae_refused_no_proofs_body.txt, itou/templates/siae_evaluations/email/to_siae_refused_no_proofs_subject.txt
Notification des SIAE qui n’ont pas envoyé de documents pour le contrôle a posteriori
Une SIAE sera probablement sanctionnée si elle n’explique pas à sa DDETS pourquoi elle n’a pas fourni de justificatifs pour ses auto-prescriptions.
=> Notification des SIAE qui n’ont pas envoyé de documents pour le contrôle a posteriori

itou/approvals/factories.py, itou/approvals/models.py, itou/employee_record/tests/tests_management_commands.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py
Le filtre de date n'est plus sur `Approval` mais sur `Suspension` et `Prolongation`.
J'en profite pour corriger un warning `DateTimeField ... received a naive datetime`.
Car j'ai compris de travers la carte action :/, et que je ne me suis pas dis que ce que je faisais était un peu idiot ^^.
=> Fiches salariés d'actualisation : Implémenter correctement ce qui était voulu

itou/metabase/management/commands/sql/024_tx_refus_siae.sql
ajout d'une echelle plus locale a la table tx refus siae
permettre de filtrer par epci/bassin d'emploi sur le TB 116
=> ajout echelle plus locale au tx refus siae

itou/utils/perms/context_processors.py, itou/utils/tests.py
Cf le titre.
Cela permettra de suivre sur chaque page quelle organisation / institution / siae consulte quoi.
Complément aux variables matomo déjà en place.
=> Ajout des SIAE, Organisations prescriptrices & institutions dans le suivi Matomo

itou/approvals/models.py, itou/approvals/tests/tests.py, itou/templates/approvals/includes/status.html, itou/www/dashboard/tests.py
Donner plus de visibilité sur la durée d’un PASS IAE car les suspensions modifient la date de fin et un employeur peut penser à tort qu’un PASS IAE est valide pour une longue durée.
La date de fin du PASS IAE est amenée à évoluer (surtout avec les suspensions on peut avoir une date de fin repoussé de 12 mois et dès lors qu’une embauche est déclarée la date de fin est modifiée et les utilisateurs ne comprennent pas forcément
Indiquer le reliquat de jours restants et préciser que la date de fin du PASS est prévisionnelle  
- etc.
=> Affichage du reliquat d'un PASS IAE

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
Clarifier le début de la phase contradictoire dans un mail
Ne pas re-calculer le temps pour être sûr d’utiliser la date à laquelle les évaluations ont été demandées.
=> Clarifier le début de la phase contradictoire dans un mail

itou/siae_evaluations/factories.py, itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/test_management_commands.py, itou/templates/siae_evaluations/email/to_siae_notify_before_campaign_close_body.txt, itou/templates/siae_evaluations/email/to_siae_notify_before_campaign_close_subject.txt
Notifier les SIAE sans justificatifs vers la fin de la phase contradictoire
30 jours après le début de la phase contradictoire, envoie un email aux SIAE qui n’ont pas transmis (ou retransmis après une revue négative) de justificatifs.
=> Notifier les SIAE sans justificatifs vers la fin de la phase contradictoire

itou/templates/apply/process_base.html
Afficher le statut du PASS pour les prescripteurs qui n'ont pas accès à l'espace salarié
=> Correction de l'affichage des PASS IAE pour les prescripteurs

itou/asp/admin.py, itou/asp/models.py, itou/asp/tests/tests_communes.py
Vu le mécanique du formulaire de selection de commune de naissance des fiches ASP, on ne peut pas ajouter des Commune pour séparer plusieurs villes avec le même code INSEE.
On va donc ignorer les objects ajoutés à la main lors de l'appel à `by_insee_code_and_period()`
=> Correction de Commune by_insee_code_and_period

config/settings/_sentry.py, config/settings/base.py
L'intégration redis rajoutera des infos sur nos erreurs.
L'intégration httpx et la possibilité de configurer le traces_sample_rate permettra d'utiliser le module performance de sentry (sachant qu'on a 100k transactions gratuites par mois), cela permettra peut-être de nous donner des infos sur la performance de l'application.
=> sentry: ajout des intégrations Redis & HTTPX + possibilité d'activer le suivi de performance

itou/metabase/management/commands/_job_seekers.py, itou/metabase/management/commands/_utils.py, itou/metabase/tests/test_utils.py
Ajout du champ `candidats.adresse_en_qpv`.
Pour profiter de la nouvelle app django `geo` récemment introduite qui permet de vérifier si n'importe quelle adresse donnée est ou non en QPV. On l'applique sur l'adresse du candidat si présente.
- Testé OK en dry run local.
- Pas de test car sur la table `_job_seekers` problématique.
=> [Metabase] Ajout du champ `candidats.adresse_en_qpv`

config/settings/base.py, itou/settings_viewer/admin.py, itou/settings_viewer/apps.py, itou/settings_viewer/models.py, itou/settings_viewer/templates/settings/list.html, itou/settings_viewer/tests.py, itou/settings_viewer/views.py
Ajoute la possibilité pour les superuser de voir les settings (non-sensibles) dans l'admin
Pour faciliter le debug 
Ajout d'un modèle fictif avec son admin surchargé.
=> settings: allow to view settings in admin for superuser

config/settings/base.py, config/settings/dev.py, requirements/base.in, requirements/base.txt, requirements/dev.txt
Sentry offre la même fonctionnalité, mais plus pratique a utiliser. L’APM n’est pas très utilisé de toute façon.
Le client APM a déjà noyé Sentry sous les erreurs, cassant notre surveillance applicative et demandant du temps et de l’argent pour résoudre le problème.
=> Retire l’APM

clevercloud/cron.json
We don't want it to run on sunday, but after the beginning of the next week to not lose 6 days waiting for an analysis.
Also, start it a little later in the night to not be surprised by matomo latencies or daylight saving time.
=> matomo-metabase: Lancer le cron plus tard dans la semaine

itou/static/css/itou.css, itou/templates/layout/_header.html
Ajoute une marge au défilement vers un endroit de la page
Autrement, la nav bar cache l’élément pointé.
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top
=> Ajoute une marge au défilement vers un endroit de la page

itou/metabase/management/commands/sql/027_suivi_etp_conventionnes_v2.sql
Création d'une nouvelle table afin de calculer les ETPs conventionnés et les proposer aux DDETS, DREETS, SIAE et à la DGEFP
Cela nous permettra de créer un tableau de bord permettant le suivi des ETPs conventionnés
=> etp conventionnés v2

itou/common_apps/organizations/models.py
Elle prend plusieurs secondes pour récupérer une personne ([voir lien sentry](https://sentry.io/organizations/itou/performance/les-emplois-prod:13fe28555ff34107b1bbe4e05e31ae24/?project=6164438&query=transaction.duration%3A%3C15m+http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=7d&transaction=%2Fsiae%2Fcolleagues&unselectedSeries=p100%28%29)).
Suppression de la Subquery en utilisant plutôt la relation direct
=> Améliorations des performances de la requête de récupération des membres d'une organisation

itou/templates/siaes/edit_job_description_details.html
Retire job_autocomplete.js de la page edit_job_description_details
Le script n’est pas utilisé sur la page.
=> Retire job_autocomplete.js de la page edit_job_description_details

itou/job_applications/models.py, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/list.html
Remplacement de la date arbitraire _2022-01-01_ par `EMPLOYEE_RECORD_FEATURE_AVAILABILITY_DATE` (_2021-09-27_)
Changement de wording et d'UI (`danger` -> `warning`) pour les messages liés aux FS d'actualisation.
Avant :
Après :
Cette date avait été choisie car on ne voulais pas faire remonter les anciennes candidatures comme FS actualisation, surtout qu'il était plus que probable que celle-ci est déjà été traitées par le support.
Mais un ticket support pourrais être facilement résolu en reculant cette date à début décembre, donc autant utiliser la même date que celle de disponibilité des fiches salariés.
Au pire des cas on va demander aux SIAE de recréer des FS alors que l'info est déjà présente coté ASP, mais vu que la majorité de nos problèmes récents sont liés à des problèmes de …
=> Utiliser la même date pour les sous-fonctions de `eligible_as_employee_record()`

itou/templates/employee_record/list.html, itou/www/employee_record_views/enums.py, itou/www/employee_record_views/forms.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/views.py
Ajout d'un dropdown pour choisir entre le tri par date de début de contrat (valeur par défaut) et le tri par nom
[Ticket notion](https://www.notion.so/1-2-Simplifier-la-recherche-des-fiches-salari-En-tant-que-SIAE-je-veux-trier-les-fiches-salari-ede1158ea9434e9b9af7c822665d9fb3)
Pour faciliter la recherche d'un salarié
=> Ajoute la possibilité de trier les fiches salariés

itou/api/data_inclusion_api/serializers.py, itou/api/data_inclusion_api/tests.py
* (ajout des nouveaux champs du schéma: horaires_ouverture, accessibilite, labels_nationaux, labels_autres, thematiques. Non renseignés car à priori données non présentes)
* suppression des sirets matchant le pattern `999\d\d$` de l'api (tambouille interne des emplois, légalement pas top d'exposer ces sirets)
* remplacement du champ `structure_parente` (une ref à l'identifiant d'une autre siae) par le champ `antenne` (un flag)
* pour les siaes ayant la source `USER_CREATED` et un siret avec le pattern `999\d\d$`, on récupére quand c'est possible le siret d'une siae qui a le même asp_id et on les flags systématiquement comme antenne
* pour les siaes ayant la source `USER_CREATED` mais un vrai siret, on garde ce siret
* pour les siaes ayant des sirets dupliqués, quelque soit la source, on …
=> data.inclusion: amélioration de la gestion des antennes

itou/jobs/models.py, itou/templates/search/includes/siaes_search_filters.html, itou/templates/search/siaes_search_results.html, itou/www/search/forms.py, itou/www/search/tests.py, itou/www/search/views.py
Ce changement permet une amélioration de la frobulation.
En effet nos désactuateurs ont souffert d'une perte fibulaire de 300 thétas, ce qui est énorme.
A l'aide de tests rigoureux, corriger la trajectoire tentaculatoire du `DeadBeefService`.
Refonte totale des racamiers dans l'application.
Lire le détail des commits pour plus d'explications.
=> Améliorer la fréquence de frobulation des désactuateurs

itou/siae_evaluations/admin.py
Demande de Zohra, pour faciliter le suivi des campagnes de contrôle a posteriori.
=> Affiche EvaluatedSiae.state dans la liste des champs de l’admin

itou/www/search/tests.py
The test is written in such  a way that eventually, we might have two times the same appellation, thus same job name twice, and the test for its absence thus fails.
=> www.search: Correction d'un test flaky

config/settings/base.py
Actuellement lorsque notre connection à postgresql saute nos workers uwsgi se retrouvent bloqués à essayer de se connecter, jusqu'à ce que le harakiri uwsgi intervienne (60 sec). Pendant ce temps, plus aucun worker uwsgi n'est dispo et le site ne répond donc plus.
Mettre le connect_timeout à 5 seconds devrait limiter ce blocage :crossed_fingers:
=> settings: ajout d'un connect_timeout pour PostgreSQL

.github/workflows/ci.yml
Réduire la file d'attente des Github Actions
=> github actions: annulation du run de la CI lorsqu'un nouveau commit est poussé sur une PR

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_institution_selected_siae_body.txt, itou/templates/siae_evaluations/email/to_siae_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_notify_before_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_refused_body.txt, itou/templates/siae_evaluations/email/to_siae_selected_body.txt, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
**Notion : https://www.notion.so/BUG-Contr-le-a-posteriori-Un-mail-de-r-sultat-n-gatif-a-t-transmis-une-SIAE-alors-que-son-r-su-b2a0f543f3f94651ae109d12ff638dd8**
Des emails indiquant une sortie de phase contradictoire négative ont été envoyés à des SIAE, qui voyaient bien leur résultat de contrôle positif dans l’interface. Évidemment, c’est perturbant.
Recalcule l’état après la mise à jour de `review()`, avant d’envoyer l’email.
L’email `to_siae_refused` était envoyé pour signifier le début de la phase contradictoire. Le `to_siae_adversarial_phase` était envoyé à la fin de la phase contradictoire. Les deux ont été inversés pour :
1. Une première revue négative (qui démarre la phase contradictoire) envoie le message “vous entrez en phase contradictoire” (`to_siae_adversarial_stage`)
2. …
=> Recalcul de l’état d’une EvaluatedSiae avant notification de revue

config/settings/base.py
En son absence, on devrait regarder le contenu de script-src, mais ça ne fonctionne pas pour certains utilisateurs.
=> CSP: Ajout de script-src-elem

itou/metabase/management/commands/sql/026_suivi_etp_realises_v2.sql, itou/metabase/management/commands/sql/027_suivi_etp_conventionnes_v2.sql
Ajout de l'id de l'annexe financiere car les mesures DC et MP du même type de structure peuvent avoir le même numéro d'annexe financière et de convention. L'id de l'af, lui, est unique -> Nouvelle référence
=> ajout des id af pour la prise en compte mesures MP

itou/siae_evaluations/admin.py, itou/siae_evaluations/tests/test_admin.py
**Carte Notion : https://www.notion.so/Extraction-des-SIAE-avec-l-tat-de-leur-contr-le-et-leur-d-partement-75a89f459b0f4577a82ce53bcf1217bf**
- Suivi de la campagne de contrôle afin d’anticiper les problèmes liés aux retardataires
- Fournir un état des lieux à la DGEFP
- Liste de toutes les SIAE avec l’état de leur contrôle (pour la campagne 2 de 2022)
- SIRET SIAE
- Type de SIAE
- Nom SIAE
- Département de la SIAE
- Email de l’administrateur de la SIAE
- Numéro de téléphone de la SIAE (si renseigné)
- Etat du Contrôle
Les fichiers générés sont groupés dans un fichier zip pour la commodité d’utilisation.
L’export de toute la base prend quelques secondes. Dans l’idéal, les exports de données seraient générés de manière asynchrone, pour éviter les longues requêtes web.
=> Export des SIAE des campagnes de contrôle a posteriori depuis l’admin

itou/api/siae_api/tests.py, itou/api/siae_api/viewsets.py, itou/siaes/models.py
La requête prend plus de 450ms au lieu de ~50 sans les innombrables mini requêtes
https://sentry.io/organizations/itou/performance/les-emplois-prod:ea4f95dcbba74f8ea42db112427d1ca7/?project=6164438&query=transaction.duration%3A%3C15m+http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=24h&transaction=%2Fapi%2Fv1%2Fsiaes%2F&unselectedSeries=p100%28%29
=> Correction d'un 1+N dans l'api des SIAEs

clevercloud/cron.json, config/settings/base.py, itou/antivirus/admin.py, itou/antivirus/management/commands/scan_s3_files.py, itou/antivirus/migrations/0002_scan_delete_filescanreport.py, itou/antivirus/models.py, itou/files/admin.py, itou/files/apps.py, itou/files/management/commands/sync_s3_files.py, itou/files/migrations/0001_initial.py, itou/files/models.py, itou/utils/storage/s3.py
Ventiller les tâches d’analyse antivirus
Le scan quotidien de l’antivirus dure environ 17 minutes. Si un déploiement a lieu durant le scan, il est interrompu (`SIGTERM`) et les fichiers ne sont pas scannés. Le scan complet de la base de production prendra probablement plusieurs jours, et il est inconcevable qu’il n’y ait pas de déploiement sur cette période. C’est pourquoi il faut implémenter un mécanisme pour suivre la progression de l’analyse et la reprendre.
Les fichiers sur S3 sont synchronisés fréquemment avec la base de données par la commande de gestion `sync_s3_files`.
Régulièrement, la commande de gestion `scan_s3_files` lit la table des fichiers pour identifier lesquels analyser, prend 200 fichiers, les analyse et enregistre les résultats. La taille des lots a été réduite et la …
=> Ventiller les tâches d’analyse antivirus

config/settings/base.py
The c1-worker machine deployment has been failing since at least
December 9th, always on a time out attempting to connect to the
database.
Give the machine more time to establish the connection.
=> Bump database connect timeout to 15 seconds

itou/static/js/formset_add_remove_row.js, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/approvals/declare_prolongation.html, itou/templates/invitations_views/create.html, itou/templates/layout/base.html, itou/templates/signup/job_seeker_nir.html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type
> The HTML specification urges authors to omit the attribute rather than
provide a redundant MIME type.
=> Retire type="text/javascript" des tags <script>

config/settings/base.py
This reverts commit 3d503a04e1b39557ec86f1612bab57ecd0b4cfa3.
Does not help, the issue seems to lie on Clever deployment side. The
`c1-worker` machine can access the database in a few ms using the
POSTGRESQL_ADDON_DIRECT_URI.
=> Revert "Bump database connect timeout to 15 seconds"

itou/files/management/commands/sync_s3_files.py
This reverts commit 76e767bbef6e11decb8a541e021f11d702b639f3.
La table est remplie.
=> Revert "Inject fake scan data to spread the antivirus load"

config/settings/base.py, config/settings/dev.py, itou/conftest.py, itou/utils/tasks.py
**Carte Notion : https://www.notion.so/Tester-l-envoi-d-e-mail-530ca30075de462481a6baed89a3f2b0**
Utiliser le même moteur d’envoi d’email en production et en test, pour des tests plus réalistes.
Amélioration des performances en diminuant le nombre de connexions.
Petites améliorations de la documentation.
=> Amélioration de l’envoi d’email et de sa testabilité

itou/siaes/factories.py
L’utilisation de valeurs prédéterminées évite les conflits. Les tests échouent de temps à autre car deux annexes financières ont le même numéro.
Exemple récent : https://github.com/betagouv/itou/actions/runs/3686688408/jobs/6239263783
=> Éviter les conflits de SiaeFinancialAnnexFactory

itou/antivirus/management/commands/scan_s3_files.py
`relativedelta` utilise le pluriel pour les durées. Le singulier permet de fixer la valeur. Donc `relativedelta(month=1)` signifie le mois de Janvier.
=> Corrige la requête de dernier scan antivirus

itou/siaes/factories.py, itou/www/search/views.py
Éviter les descriptions de métier sans rapport avec le code ROME dans les tests.
Réduit la variabilité entre les lancements de tests. De nombreux tests font des `assertContains()` et `assertNotContains`, mais certaines appellation générées par Faker sont inclues dans une autre, générant de nombreux faux positifs.
Ce changement a révélé un `select_related` manquant dans la recherche de SIAEs.
=> Utilisation de l’appellation dans SiaeJobDescriptionFactory

itou/siae_evaluations/admin.py, itou/siae_evaluations/tests/test_admin.py
**Notion : https://www.notion.so/Am-lioration-du-CSV-de-suivi-des-campagnes-avec-l-ajout-d-une-colonne-relative-la-PHASE-29851bf907f54a6296de208bf7956fa3**
Deux SIAE peuvent être à l’état `SUBMITTED`, alors que l’une est en phase amiable et l’autre en phase contradictoire. Cette nouvelle colonne aide à distinguer les deux.
=> Ajout de la phase dans l’export des SIAE

itou/metabase/sql/024_tx_refus_siae.sql
- Résolution de l'erreur `psycopg2.errors.AmbiguousColumn: column reference "code_commune" is ambiguous` introduite par l'introduction récente de la nouvelle colonne `structures.code_commune`. Erreur quasi impossible à anticiper étant donné que nous n'avons plus de dry run et que nous ne testons pas encore les requêtes SQL de fin de MAJ. Néanmoins ce genre d'erreur est rarissime en pratique, je ne me souviens pas avoir jamais rencontré ce scénario.
=> Metabase : Résolution de bug mineur

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/siaes.py, itou/metabase/tables/utils.py
Tentative d'amélioration de la situation.
Initialement:
```
timeit: method=handle completed in seconds=153.54
```
Nous pensons que trop d'objets liés sont retournés via les très nombreux prefetch; essayer de descendre ce nombre via des annotations.
```
pm populate_metabase_emplois --mode=siaes
timeit: method=handle completed in seconds=51.27
9911195 function calls (9827528 primitive calls) in 52.888 seconds                              
Ordered by: cumulative time                                                                           
ncalls  tottime  percall  cumtime  percall filename:lineno(function)                                                                                                                                            
1    0.000    0.000   52.960   52.960 …
```
=> Metabase : optimiser la requete SIAEs

.gitignore, config/settings/base.py, itou/utils/new_dns/middleware.py, itou/utils/new_dns/tests.py
**Carte Notion : ** https://www.notion.so/mort-staging-d48ccb48d7fe49ec85d17c3ee66dba92
Plus personne ne l’utilise !
Cela fait un environnement de plus à maintenir et les données, rarement à jour, nous causent régulièrement des soucis.
=> À mort staging !

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/job_applications.py, itou/metabase/tables/job_seekers.py, itou/metabase/tables/organizations.py, itou/metabase/tables/selected_jobs.py
Améliorations sur un peu tous les exports.
Les benchmarks sont réalisé en local donc ne représentent pas exactement les gains que l'on aura en prod.
J'ai permis de spécifier une taille de batch différente pour tous les exports, et j'ai amélioré certaines requêtes / calculs
- `job_seekers` ~2.5x plus rapide (sur 1h en prod ?)
- `job_applications` 3x plus rapide (de 36 à 12 minutes juste en augmentant la taille des batchs)
- `selected_jobs` de 1h à 2 minutes
Les autres c'est du niveau de quelques minutes gagnées max (sur des exports de quelques minutes)
=> Metabase autre amélioration de performances

clevercloud/crons/populate_metabase_emplois.sh
Avoir l'output des MAJ Metabase dans un bucket était bien pratique mais a été perdu quand on est passé sur notre worker. Cette PR rétablit cette pratique.
- Premier essai avec une `function` bash jolie mais s'obstine à ne pas fonctionner et ce silencieusement ¯\_(ツ)_/¯. Voir le premier commit reverté. Je squasherais au merge (TODO).
- Second essai plus simple avec `()` testé OK sur le worker.
=> Metabase: Envoyer l'output des crons vers le bucket

itou/prescribers/models.py, itou/users/models.py, itou/users/tests/test_models.py, itou/www/stats/views.py
**Carte Notion : [lien](https://www.notion.so/Accorder-la-DG-PE-une-vision-nationale-sur-leur-tableaux-de-bord-priv-s-c16cac799d614549871c73d2e7fb3e77)**
Mise au point d'un accès stats pour la DGPE (Direction Générale Pôle emploi) pour pouvoir consulter les stats PE de toute la France.
Jusqu'ici les stats PE n'étaient visibles soit que pour un département (agence classique) soit pour une région (DRPE).
Testé OK en local dev.
=> Mise au point d'un accès stats pour la DGPE (Direction Générale Pôle emploi)

itou/users/tests/test_models.py
`test_merge_approvals_timeline_case1` échoue dès à présent, `test_merge_approvals_timeline_case2` l'aurais rejoint d'ici quelques mois.
=> :snowman_with_snow: Correction de 2 tests avec des dates absolues

itou/job_applications/admin.py
La page est assez lente, et souvent utilisée par le support. En enlevant le gadget hiérarchie de date (on peut trier par date de création, et avec la pagination, il est facile de naviguer), les requêtes coûteuses pour le consituer sont évitées. Les gains sont très visibles sur les filtres.
Rechercher un email : 1300 ms → 400 ms
Filtrer par délivrance manuelle : 2000 ms → 300 ms
Les autres filtres montrent environ une amélioration 2x.
=> Accélération de la page admin candidature

itou/static/js/duet_date_picker_widget.js, itou/static/js/htmx_handlers.js, itou/templates/apply/process_accept.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
**Carte Notion : https://www.notion.so/6d2f772966114bc98fefc6ef17df79c0?v=99352c5142224ce8995dcc6ea3a78337&p=13de885a0a174400b746d9c05339ab7f&pm=c**
Actuellement, la modale de confirmation s'affiche alors qu'elle ne devrait pas. En effet, les formulaires contiennent des erreurs mais ils sont couverts par la modale.
L'affichage de la modale est décidé également côté serveur.
Plusieurs PR suivront :
- utilisation d'un seul ID de modale partout (discuté avec Victor)
- amélioration de HtmxTestClient pour pouvoir l'utiliser dans la même session qu'un TestClient (discuté avec Romain) et remplacement des tests Unittest par Pytest.
=> Acceptation d'une candidature : affichage de la modale de confirmation si les formulaires sont valides

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/siaes.py, itou/metabase/tables/utils.py
On espère un gain de performance certain en prod.
Actuellement 1500 secondes, on espère passer sous la minute. A vérifier et compter dans les logs ensuite (retour sur la PR)
=> metabase.organizations/siaes: Cesser d'annoter les membres

itou/templates/employee_record/includes/list_item.html
**Carte Notion : ** https://www.notion.so/Correction-affichage-du-badge-Int-gr-e-ASP-le-sur-la-liste-des-salari-s-506a580290834eef95b05b22540ec2ef
C'est plus joli.
Avant:
Après:
=> Fiches salariées: amélioration de l'affichage des badges

itou/job_applications/factories.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py
La version actuelle de `.with_accepted_at()` tombais dans son deuxième `When` et utilisais donc `created_at`, sauf que si une SIAE avait embauchée la personne avant la création des candidatures du stock AI alors elle n'était pas considéré comme le dernier employeur donc impossible pour elle de prolonger ou suspendre alors qu'elle est effectivement le dernier employeur.
Ce cas est probablement minime mais la correction n'était pas énorme non plus, autant la faire et ne plus risquer de tomber dessus, surtout qu'il est plus logique d'utiliser `hiring_start_at` que `created_at` (qui à une valeur fixe) pour ces candidatures.
Idéalement je pense qu'il aurais fallu en profiter pour convertir `is_from_ai_stock` d'une propriété à un champs physique (avec peut-être un nom plus générique pour le …
=> Gestion de la date d'acception (`accepted_at`) des candidatures du stock AI

itou/siaes/tests/tests_import_siae_command.py
Réparer la suite de tests.
Les données de l’ASP utilisées pour les tests sont valides pour 2022 seulement. Les données pour 2023 ne seront pas disponibles avant plusieurs mois. Pour éviter d’avoir ce problème tous les ans, fixons la date à 2022 pour ces tests.
=> Correction de tests dépendant de la date

itou/approvals/admin.py, itou/users/models.py
Copier-coller un texte entouré de parenthèses demande de bien viser.
L’email serait plus facile à copier s’il était séparé par un tiret.
Aussi, le SIRET d’une SIAE pourrait être sélectionné par un double clic
s’il n’avait pas d’espaces, et s’il n’était pas entouré de parenthèses.
=> Changement de représentation pour la qualité de vie du support

itou/approvals/admin.py
=> Simplifier l’affichage du SIRET d’une SIAE dans l’admin

itou/templates/apply/process_accept.html, itou/www/apply/urls.py, itou/www/apply/views/process_views.py
**Carte Notion : ** https://www.notion.so/1-3-Renseigner-le-NIR-apr-s-l-inscription-du-candidat-En-tant-qu-employeur-j-aimerais-renseigner-l-297c09b3b5844a05b6909a39499016ca
La suppression de la bannière fait partie du ticket Notion de gestion du NIR (cf Figma)
Au passage en regardant d'où venait le champ `approval_not_needed` conditionnant l'affichage de la bannière je suis tombé sur la vue obsolète `accept_without_approval`.
Avant
Après
=> Suppression d'une bannière et d'une vue inutile

itou/templates/siaes/includes/_siae_jobdescription.html
=> Masquer le badge de type de contrat si le champ n’est pas rempli

.github/dependabot.yml
On a plus de 45 dépendances (en comptant celle de dev) qui ne sont pas à jour.
La limite par défaut est de 5 PRs par semaine ce qui laisse peu d'espoir d'avoir un jour une stack totalement à jour.
=> dependabot: augementation de la limite de PR

itou/www/apply/views/submit_views.py
La suppression du `SessionNamespace` ne fait que modifier la session, et la modification n’est enregistrée que si la vue se termine bien. Autrement, Django ne modifie pas la session et les données sont préservées.
=> Retrait du commentaire non clair “Point of no return“

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
**Carte Notion : https://www.notion.so/Contr-le-posteriori-Limiter-la-selections-des-SIAE-aux-pass-99999XXXXXXXX-d06aad2f980b41b8aae2d4273e4455c9**
La plupart des tests n’auraient pas remarqué les erreurs, car la candidature n’était pas éligible.
Utiliser une candidature éligible et vérifier que chaque changement la disqualifie.
=> Exclure les agréments PE des évaluations a posteriori

clevercloud/cron.json
By experience, midnight seems to be a bad choice and Matromo tends stop answering. I don't have the details of what's happening but it's very possible that maintenance or consolidation operations happen around that time.
I tried very successfully the same operation in the middle of the night, so this mitigation seems to be a simple way to be more successful.
=> matomo: Modifier l'heure de synchronisation

itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/resume.html, itou/www/apply/tests/tests_submit.py
**Carte Notion : https://www.notion.so/1-2-Parcours-d-p-t-de-candidature-hors-auto-prescription-Remplacer-le-dernier-bouton-Suivant-du--722480e4dee34e319800815667454429 et https://www.notion.so/2-2-Parcours-d-p-t-de-candidature-en-auto-prescription-Remplacer-le-dernier-bouton-Suivant-du-pa-49c7afb1b73e425483f63bc53acda448**
Etre plus clair pour nos utilisateurs.
=> submit_views.resume: Améliorer le texte du bouton du dépôt de candidature

itou/institutions/enums.py, itou/institutions/migrations/0001_initial.py, itou/templates/dashboard/includes/stats.html, itou/users/models.py, itou/utils/apis/metabase.py, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/views.py
**Carte Notion : https://www.notion.so/TB-DIHAL-d-ployer-le-TB-81ff15c839a141ef9cf4b30243c2454f**
Il s'agit dune demande de la DIHAL.
Comme le reste. La gestion des permissions d'accès aux Stats me semble chargée, mais je ne vois pas de moyen simple, rapide et explicite de faire mieux, il y a pour l'instant un peu trop d'exceptions partout. Ce n'est pas très joli mais à part ça on n'a pas beaucoup de problèmes qui en découlent.
Deux choses cependant:
- il y a zéro tests sur les accès, il faudrait essayer d'en ajouter (comme ici) à chaque modification.
- a minima les `can_view_stats` sur User et l'injection de chaque droit dans le contexte devrait être plus "automatique": un systeme par tags (`custom_permissions = [("read", "stats", {"cd89", "cd56", "dgefp"}), ...]`) permettrait cela mais …
=> stats: Ajout d'un tableau de bord DIHAL

clevercloud/crons/populate_metabase_emplois.sh, itou/metabase/conftest.py, itou/metabase/db.py, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_matomo.py, itou/metabase/tables/analytics.py, itou/users/management/commands/sync_group_and_perms.py, itou/users/tests/test_management_commands.py
**Carte Notion :  https://www.notion.so/C1-kpi-16-Taux-de-transmissions-des-fiches-salari-s-r-ussies-au-premier-envoi-statut-int-gr-e-2a532dc2089b42e2bdfced8f66ab3827**
Les derniers développements de Romain concernant l'app Analytics permettent d'extraire des données historisées, en particulier sur l'évolution des fiches de poste.
Extraire ces données vers Metabase permettra de les exploiter.
Ajouter cet export à la liste des données exportées par le cron.
On en profite pour introduire un premier test _end to end_ du cron !
=> Synchronisation des analytics C1 avec Metabase

itou/job_applications/models.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/views.py
Problème de performance sur cette page : 
https://sentry.io/organizations/itou/performance/les-emplois-prod:278ac935105b4c5ba33ba5e955b518a6/?project=6164438&query=transaction.duration%3A%3C15m+http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=7d&transaction=%2Femployee_record%2Flist&unselectedSeries=p100%28%29
- Correction d'une requête en 1+N 
- Suppression du doublon de requêtes pour compter les JobApplications
=> Amélioration des performances de la liste des nouvelles fiches salariés

itou/templates/apply/includes/job_seeker_info.html, itou/www/apply/tests/tests_process.py
**Carte Notion : https://www.notion.so/En-tant-qu-employeur-ou-prescripteur-je-veux-voir-que-le-CV-ou-le-num-ro-de-t-l-phone-du-candidat-n--884eae0e15b94a6db0163221bd127403**
Actuellement si les infos sont absentes la ligne entière disparaît. Il est plus explicite d'afficher le label, puis l'info "Non rensigné".
=> boost: Afficher "non renseigné" en cas de non-présence d'une information de candidature

itou/antivirus/admin.py, itou/antivirus/management/commands/scan_s3_files.py, itou/antivirus/migrations/0002_scan_delete_filescanreport.py, itou/antivirus/migrations/0003_rename_clamav_infected_scan_infected.py, itou/antivirus/models.py
Le champ stocke l’information de si le fichier est vraiment infecté selon un humain. Lorsque ClamAV détecte une signature de virus, elle est stockée dans le champ `clamav_signature`.
=> Renommer Scan.clamav_infected → infected

itou/templates/account/email/unknown_account_message.txt, itou/templates/account/email/unknown_account_subject.txt
Modification du gabarit par défaut pour l'e-mail envoyé lors d'une demande de réinitialisation de mot de passe lorsque le compte est inconnu.
Le message envoyé était celui par défaut, en anglais, avec quelques petits bout de "french in the text".
Surcharge du gabarit `allauth` par défaut.
=> BOOST : Modification de l'e-mail envoyé pour un compte inconnu demandant un reset de mot de passe

itou/www/signup/tests/test_job_seeker.py, requirements/base.in, requirements/base.txt, requirements/dev.txt
Revert du commit 6227d0b6299bd2a562d19d6aad42d4dd7f9119fd.
https://sentry.io/organizations/itou/issues/3858480806/
Devrait être corrigé avec https://github.com/pennersr/django-allauth/pull/3230
=> Revert "requirement: bump django-allauth from 0.51.0 to 0.52.0"

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
https://sentry.io/organizations/itou/issues/3865301686/?project=6164438
On ne devrait pas pouvoir arriver sur cette vue sans session mais comme les sessions expirent mais pas les onglets, tout est possible.
=> Parcours de vérification des informations candidat: correction d'un bug sur la session de candidature

config/settings/base.py, itou/status/management/commands/run_status_probes.py
**Carte Notion : https://www.notion.so/Surveiller-les-crons-avec-UptimeRobot-58916e8ebc6b46e0aac17f146c4de22a**
La machine exécutant les tâches planifiées était en panne durant plusieurs jours, et l’équipe de dev a mis longtemps à le remarquer.
Avec Sentry.
Cette première étape vérifie qu’au moins une tâche planifiée est exécutée. Il n’y a pas d’API Sentry pour enregistrer les crons, ce qui décourage la surveillance toutes les tâches.
Actuellement, lorsque les tâches ne tournent pas, le système continue de rendre service aux utilisateurs, simplement les synchronisations avec les autres services ne fonctionne pas, et les données affichées sont moins récentes. Revenir à l’état normal demande simplement de relancer les tâches. Ce n’est pas la peine de surveiller chaque tâche pour le moment.
=> Implementation d’une surveillance des tâches planifiées

itou/www/apply/tests/tests_process.py
Ça prend de la place sur la console (et accessoirement ça ne marchera plus en Django 5)
=> test: suppression d'un message de dépréciation

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
Éviter de tomber dans un cas non prévu de manière silencieuse.
=> Ajout d’un garde à EvaluatedJobApplication.state

itou/metabase/management/commands/populate_metabase_matomo.py, itou/metabase/management/test_populate_metabase_matomo.py
Sentry nous indique deux soucis:
- [ici](https://sentry.io/organizations/itou/issues/3838668440/?project=6247245&query=is%3Aunresolved&referrer=issue-stream)  un crash car on essaie d'écrire une table alors qu'aucune donnée n'a été récupérée
- [ici](https://sentry.io/organizations/itou/issues/3862664998/?project=6247245&query=is%3Aunresolved&referrer=issue-stream) et [là](https://sentry.io/organizations/itou/issues/3848282584/?project=6247245&query=is%3Aunresolved&referrer=issue-stream) parce que il n'a pas réussi à contacter correctement Matomo, faisant crasher l'intégralité du script.
On ajoute un retry d'un coté, on corrige le mini bug de l'autre, on teste les deux cas.
=> Matomo : ajout d'un retry et correction d'un crash si valeurs absentes

itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/analytics.py
**Carte Notion : https://www.notion.so/Ajout-d-une-colonne-Type-detailled-sur-la-table-C1-Analytics-V0-5d7257aed90e42c08db617b1ab943bfe**
Evite un AR dans le code aux data analysts pour savoir à quoi correspond un code de donnée.
=> populate_metabase_emplois: Ajout du label à l'export des analytics

itou/static/js/city_autocomplete_field.js, itou/static/js/commune_autocomplete_field.js, itou/static/js/job_autocomplete.js, itou/static/js/matomo.js, itou/static/js/prevent_multiple_submit.js, itou/static/js/split_nir.js, itou/static/js/utils.js
Pour gérer le cas de nouveaux éléments DOM créé par htmx (un form swappé par exemple) afin que les champs continuent d'avoir le comportement souhaité.
On souhaite utiliser le target pour s'assurer qu'on ne rajoute des callbacks que sur les nouveaux éléments dans le cas où htmx ne recharge qu'une partie de la page.
=> static: remplacement de $(document).ready par htmx.onLoad

itou/job_applications/admin.py
Les données ne sont pas utilisées et ralentissent les requêtes.
=> Retrait de list_select_related dans JobApplicationAdmin

itou/status/management/commands/run_status_probes.py
**Carte Notion : https://www.notion.so/Surveiller-les-crons-avec-Sentry-58916e8ebc6b46e0aac17f146c4de22a**
Le _cron monitor_ précédent a été supprimé, car `run_status_probes` s’exécutait dans l’environnement FAST-MACHINE et non production. Finalement, `run_status_probes` va bien s’exécuter en production, le _cron monitor_ a été recréé, mais a changé d’ID.
=> Mise à jour de l’ID du _cron monitor_ Sentry

itou/templates/layout/_footer.html, itou/templates/layout/_nav_preheader_items.html
**Carte Notion:** https://www.notion.so/Rediriger-tous-les-sites-de-la-PDI-vers-la-nouvelle-interface-C3-f1ccd9f264814ff7bfc029af3aaa7192
Mise à jour des liens communauté 
De communaute.inclusion.beta.gouv.fr vers communaute-experimentation.inclusion.beta.gouv.fr
Préparation de la redirection/fermeture du site WP
=> Mise à jour de l'url communauté

itou/templates/employee_record/includes/list_item.html, itou/www/employee_record_views/tests/test_list.py
**Carte Notion :** Ticket support
Le gabarit `list_item.html` n'a pas été ajusté suite à 0635f3e31.
Actuellement :
Attendu :
=> Correction pour le message d'information des fiches salariés d'actualisation

itou/templates/dashboard/dashboard.html, itou/templates/dashboard/includes/dora_card.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py
**Cartes Notion :**
- https://www.notion.so/1-2-Promouvoir-DORA-Bandeau-d-information-en-haut-du-tableau-de-bord-Limit-aux-territoires-d-XP-73603d4018894239b47370dcef091ee2
- https://www.notion.so/2-2-Promouvoir-DORA-Nouveau-bloc-Services-pour-Dora-f66a731a66864b9ab34783b2ec417a3a
Augmenter l’acquisition de nouveaux utilisateurs pour DORA
Employeur :
Prescripteur :
=> Promouvoir DORA : bandeau et bloc dans le tableau de bord

itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/includes/list_card_header.html, itou/templates/apply/process_base.html, itou/www/apply/tests/tests_list.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/list_views.py, itou/www/apply/views/process_views.py, itou/www/approvals_views/views.py
Actuellement un orienteur peut créer une candidature pour n'importe quel NIR et accéder ensuite à ses informations personnelles.
=> Cacher les informations personnelles aux orienteurs

itou/siaes/apps.py, itou/siaes/migrations/0001_initial.py
Le `TransactionTestCase` utilise `TRUNCATE` sur les tables, et ne réinstalle
pas l’objet spécial POLE EMPLOI SIAE.
=> Installer l’objet POLE EMPLOI SIAE avec post_migrate

itou/templates/dashboard/dashboard.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py
L'absence d'annexe financière est "normale" en début d'année. L'ajout de ce bandeau devrait servir à éviter quelques tickets au support.
=> Tableau de bord: ajout d'un bandeau pour les SIAE avec une convention active mais sans annexe financière

itou/templates/employee_record/list.html, itou/users/admin.py, itou/users/management/commands/fill_user_asp_uid.py, itou/users/migrations/0006_user_asp_uid.py, itou/users/models.py, itou/users/tests/test_models.py
**Carte Notion :** https://www.notion.so/Comment-g-rer-le-doublon-ASP-quand-on-a-plus-le-doublon-chez-nous-95592f7f625142b98fa4a2264a8195e6
La propriété `jobseeker_hash_id` n'est actuellement utilisé que dans nos échanges avec l'ASP et en particulier dans les fiches salariés en tant que `IdItou`.
Deux problématiques on été identifiées : 
1. Lors d'échange avec l'ASP nous souhaitons pouvoir rechercher un utilisateur par cet ID, qui est le seul identifiant technique commun, ce qui est impossible avec une propriété.
2. Dans le cas d'un doublon utilisateurs :
a. Si l'utilisateur a déjà été envoyé vers l'ASP mais que l'on a supprimé celui-ci chez nous alors il est plus simple de juste changer cette valeur dans l'utilisateur existant.
b. Si nous avons encore les deux utilisateurs mais que celui …
=> Modèle `Users` : Ajout du champs `asp_uid` afin de remplacer la propriété `jobseeker_hash_id`

config/settings/base.py
Utilisation de l’intergiciel officiel.
`CSP_REPORT_PERCENTAGE` n’est pas utilisé lorsque `CSP_REPORT_URI` n’est pas défini.
https://github.com/mozilla/django-csp/blob/e209183b0956bfe2cef562bece18a6a526479c80/docs/reports.rst#throttling-the-number-of-reports
Inutile depuis f78c015eea060d773fd69245509b7c4879c4df89.
=> Nettoyage après l’activation de la CSP

itou/metabase/tables/job_seekers.py
La MAJ Metabase quotidienne casse sur une nouvelle erreur. Cf fil ([lien](https://itou-inclusion.slack.com/archives/CT7986ULC/p1674160204873409))
Bien résumé par la description du commit :
Pour info @tonial et @vperron 
Je merge sans revue car je suis off ce vendredi après-midi et je tiens à débloquer la MAJ pour ce weekend.
=> [Metabase] Fix technique sur le user kind.

itou/metabase/tables/job_seekers.py
Certains utilisateurs is_staff ne sont pas superusers
=> [Metabase] Fix technique sur le user kind (correction de #2013)

itou/metabase/sql/015_taux_transformation_prescripteurs.sql, itou/metabase/sql/016_candidatures_recues_par_fiche_de_poste.sql, itou/metabase/sql/019_candidatures_echelle_locale.sql, itou/metabase/sql/020_delai_1ere_candidature_embauche.sql
Les colonnes "ID anonymisé" (qui ont vocation à être bientôt supprimées) ont l'ID en clair ce qui casse certaines jointures.
Cf https://itou-inclusion.slack.com/archives/CT7986ULC/p1674123224547489
J'ai testé les 4 requêtes SQL manuellement en local, elles semblent ok.
Pour mémoire : lié à ce commit ([lien](https://github.com/betagouv/itou/pull/1978/commits/fd8cf584427c1afe4091b654ff122164a35a8c43)) de cette PR ([lien](https://github.com/betagouv/itou/pull/1978))
=> [Metabase] Fix technique des colonnes "ID anonymisé"

itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/tests/test_management_commands.py
Aujourd’hui, 255 administrateurs de SIAE qui avaient terminé leur campagne de contrôle a posteriori avec un résultat positif, ont reçu un rappel d’envoyer leurs documents justificatifs avant la fin de la campagne, sans quoi ils seraient sanctionnés. 😵
=> Exclure les SIAE dont le contrôle est terminé du rappel en phase contradictoire

config/settings/base.py
**Carte Notion : ** https://www.notion.so/BUG-la-page-documentation-API-ne-fonctionne-plus-depuis-google-chrome-c2c80e0a86754df9aad1e8518eaef2b5
On a une erreur CSP:
`Failed to construct 'Worker': Access to the script at 'blob:https://emplois.inclusion.beta.gouv.fr/3e5d929e-9e5b-4c36-b483-ee07254ec18e' is denied by the document's Content Security Policy.`
sur la page https://emplois.inclusion.beta.gouv.fr/api/v1/redoc/
=> CSP: add object-src directive

itou/siae_evaluations/emails.py, itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/test_emails.py, itou/siae_evaluations/tests/tests_models.py, itou/www/siae_evaluations_views/views.py
Éviter des centaines de lignes de codes pas très intéressantes ni très liées au modèle.
=> Déplacer les emails du contrôle a posteriori dans un module

itou/templates/search/includes/siaes_search_filters.html, itou/templates/search/siaes_search_results.html, itou/templates/siaes/includes/_card_siae.html
**Carte Notion:** https://www.notion.so/Am-lioration-de-l-int-gration-de-la-section-des-onglets-dans-les-r-sultats-de-recherche-c4087c0c8aca4ea7b8c5147d12c2a13d
Amélioration de l'ui des onglets avec résultats des recherches en respectant la mise en forme du thème et pour faire fonctionner le masquage des onglets trop longs en mobile. Au passage, amélioration de l'accessibilité
Modification du DOM et classes css dans les templates
=> feat: update ui for siae results tabs

itou/approvals/admin.py, itou/approvals/tests/tests.py, itou/employee_record/admin.py
**Carte Notion :** https://www.notion.so/ADMIN-Page-PASS-IAE-L-information-sur-le-statut-de-la-fiche-salari-n-est-pas-toujours-fiable-59cf47653dd641ba834ef79c0e7e13c1 + remontée du support
Commit 1 : Ne pas créer de confusion parce qu'on affiche une phrase qui est là uniquement car c'est un cas par défaut.
Commit 2 : Remettre l'information "FS en attente de création" directement dans l'admin (plutôt que de devoir regarder sur le tableau de bord de l'employeur), enlevé par 592e23f63 car on ne disais pas la vérité dans les cas problématiques.
=> [Admin] Plus de granularité pour le message d'un champ des PASS IAE et des Fiches Salariés

itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/status/management/commands/run_status_probes.py, itou/utils/sentry.py
Il arrive régulièrement (~1 fois par trimestre) qu'une fiche salarié "se coince" et bloque les échanges, n'ayant pas d'alerte nous nous en rendons compte soit par hasard soit parce que les utilisateurs font un ticket au support qui nous pousse à le découvrir.
Utilisation de [Cron Monitoring](https://docs.sentry.io/product/crons/) et des [Alertes](https://docs.sentry.io/product/alerts/) proposées par Sentry
=> Ajout de la supervision pour les tâches d'envois et de récupération des fiches salariés

itou/siae_evaluations/emails.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/test_emails.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_institution_campaign_close_body.txt, itou/templates/siae_evaluations/email/to_institution_campaign_close_subject.txt
**Carte Notion : https://www.notion.so/1-4-Pack-sanctions-En-tant-que-DDETS-je-prends-connaissance-de-l-ouverture-de-la-phase-des-sanctio-2e9646d5e4be4c04bebedbba90f70497**
Prévenir les DDETS qu’elles doivent enregistrer la ou les sanctions prévues à l’encontre des SIAE qui ont obtenu un résultat négatif.
=> Notifier les DDETS quand les SIAE attendent les sanctions

itou/users/migrations/0001_initial.py, itou/users/models.py, itou/www/apply/tests/tests_submit.py
On passe de:
Un objet Utilisateur avec ce champ NIR existe déjà.
à
Ce numéro de sécurité sociale est déjà associé à un autre utilisateur.
plus clair.
=> Amélioration du message d'erreur pour l'unicité du numéro de sécurité sociale

itou/templates/siaes/includes/_job_description_details.html, itou/www/siaes_views/tests/tests_views.py
**Carte Notion : ** https://www.notion.so/BUG-Le-badge-X-postes-ouverts-au-recrutement-s-affiche-m-me-si-le-recrutement-est-ferm-b9cf85af217b4f5682bc61a1ff83de91
Si le recrutement est fermé, il n'y a pas de poste ouvert.
=> Suppression du badge du nombre de postes ouverts si le recrutement est fermé

itou/metabase/sql/031_suivi_auto_prescription.sql
L'auto prescription est définie par un diagnostic effectué par un employeur X suivie d'une embauche faite par ce même employeur. Il est impossible d'avoir ces deux info via metabase, la création d'une table était donc nécessaire.
=> Creation d'une table du suivi de l'auto prescription 

itou/metabase/sql/015_taux_transformation_prescripteurs.sql, itou/metabase/sql/018_nombre_candidatures_par_structure.sql, itou/metabase/sql/021_tx_candidats_acceptes_par_prescripteurs.sql, itou/metabase/sql/022_delai_recrutement.sql
**Carte Notion : ** [ici](https://www.notion.so/Reprise-de-stock-AI-V-rifier-les-scripts-sql-pour-int-grer-les-reprises-de-stock-5c89efd36077487a9b05e8ff6b9e03e4)
Dans le cadre de la fiabilisation des données nous avons décidé d'ajouter la reprise de stock AI dans nos tableaux de bord. Il a donc fallu reprendre les scripts sql ou cette dernière était manquante
+ modifications dans l'indentation des scripts
=> Ajout de la reprise de stock AI quand nécessaire

itou/templates/siaes/card.html
Regression introduite avec 30331edeed8d6aa1b0e1b7363bc274c2d5ad24e9.
https://itou-inclusion.slack.com/archives/C01181Y04LT/p1674569058030759
=> Corrige l’ancrage des métiers sur la page de description des SIAE

itou/cities/factories.py, itou/common_apps/address/tests/tests.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/signup/tests/test_job_seeker.py
Évite une requête SQL, façonner les outils à notre usage.
=> Retourner la liste de villes crées avec create_test_cities

itou/users/models.py, itou/users/tests/test_models.py
La clause d'unicité du champs était déclenchée car le formulaire de l'admin enregistrais `""` pour ce champ.
=> Forcer le champ `asp_uid` à `None` si ce n'est compte n'est pas un compte candidat

itou/templates/employee_record/summary.html, itou/utils/templatetags/format_filters.py, itou/www/employee_record_views/tests/test_summary.py
**Carte Notion : ** https://www.notion.so/En-tant-que-SIAE-je-veux-voir-l-horodatage-de-la-fiche-salari-BOOST-dcac301134084b83b18ed54912a747a0
Lorsqu’il y a des anomalies d’intégration des fiches salarié, l’ASP demande aux SIAE de fournir l’horodatage
=> Ajout des infos d'horodatage ASP sur les fiches salariés

itou/utils/test.py, requirements/dev.in, requirements/dev.txt
Utile pour capturer une partie d’un document HTML, notamment pour inclure du _markup_ dans un format compact et facile à lire dans l’attendu d’un test.
=> Ajout d’outils pour formatter le HTML dans les tests

itou/metabase/tables/job_applications.py
Pour débloquer une étude urgente pour le Ministère du Travail. Cf fil ([lien](https://itou-inclusion.slack.com/archives/CT7986ULC/p1673550096493869)).
Pas de revue car trivial *et* urgent.
=> [Metabase] Ajout du champ `candidatures.date_début_contrat`

itou/siae_evaluations/tests/test_management_commands.py
`evaluated_job_app_accepted` devrait avoir le statut `ACCEPTED`.
=> Correction d’une typo dans itou/siae_evaluations/tests/test_management_commands.py

itou/prescribers/tests.py, itou/templates/admin/prescribers/change_form.html
**Carte Notion : ** https://www.notion.so/C1-Probl-me-r-soudre-le-CRI-a-acc-s-la-commande-valider-ou-refuser-une-habilitation-a19e6b85cded499aa1d5130e7f27b8a8
Ils ne sont pas censés effectuer cette action (et n'ont pas les droits pour).
=> admin: cacher les boutons valider ou refuser une habilitation au CRI

itou/metabase/db.py, itou/metabase/tables/selected_jobs.py
En local dev en partant d'une db vierge, même après avoir fait les trois populates (emplois/fluxiae/matomo), le `build_final_tables` casse sur un tas de tables manquantes. Cela empêche de tester l'ensemble des requêtes SQL en local après un changement.
Ces tables manquantes sont des tables "non versionnées" (c.a.d. dont la création n'est codée nulle part dans le présent repo) qui ont été créées manuellement (dette technique).
Fil complet ([lien](https://itou-inclusion.slack.com/archives/CT7986ULC/p1673626720113039))
- En crééant toutes ces tables avec la bonne structure mais aucune donnée. Au moins cela débloque l'ensemble des requêtes SQL et on la visibilité de l'ensemble de ces tables qu'on peut maintenant discuter au cas par cas. C'est un premier pas.
- En passant j'ai levé un loup sur …
=> [Metabase] Recensement et création à vide de toutes les tables non versionnées

itou/metabase/management/commands/populate_metabase_matomo.py, itou/metabase/management/test_populate_metabase_matomo.py, itou/static/vendor/tarteaucitron/tarteaucitron.js, itou/static/vendor/tarteaucitron/tarteaucitron.services.js, itou/templates/layout/base.html, itou/utils/settings_context_processors.py
**Carte Notion : https://www.notion.so/C1-Gestion-du-d-p-t-des-cookies-d8f6e882c9be47fb8e03c68115822f6d**
Actuellement les emplois ignore complètement le choix des préférences de cookies de l'utilisateur.
De plus il tracke l'intégralité des visites via Matomo, refus de tracking ou non.
Note: il faudra modifier la valeur de la variable MATOMO_BASE_URL dans les secrets pour ne plus inclure `index.php`.
=> RGPD : Ne pas stocker de cookies si ils sont refusés

itou/utils/widgets.py
La branche `if value` est inutile. `NoneType` et la chaîne vide `""` ne sont pas des instances de `datetime.date`.
Le block protégé par `isinstance(value, str)` essaye de reconnaître une date dans la chaîne de caractères, et renvoie la chaîne de caractères. Que se passe-t-il si aucune chaîne n’est reconnue ? On ignore l’erreur et continue. Rien de sert de valider si on ignore l’erreur correspondante.
=> Simplifier DuetDatePickerWidget

itou/metabase/sql/032_metier_candidatures.sql
Carte Notion : https://www.notion.so/plateforme-inclusion/Fiabilisation-donn-es-candidature-vs-donn-es-fiche-de-poste-bbb5709d60de499ea06b7f8372a15995
Pour ajouter l'analyse des métiers associés aux candidatures.
Ajout d'une table qui associe les fiches de postes et métiers associés aux candidatures.
=> metabase: add new table with jobs associated to job_applications

itou/users/models.py, itou/www/apply/tests/tests_list.py
Pour toujours plus de vitesse (et surtout moins de requêtes SQL).
=> users: prevent useless SQL query in is_handled_by_proxy

itou/www/apply/forms.py, itou/www/apply/tests/tests_list.py
Pas besoin de récupérer 2 fois les demandeurs d'emploi.
Pour toujours plus de vitesse (et surtout moins de requêtes SQL).
=> www.apply: une requête SQL en moins

config/settings/base.py
**Carte Notion:** https://www.notion.so/plateforme-inclusion/Publier-le-TB218-sur-la-page-TB-publics-et-ajout-embed-enqu-te-85b64fad3921489cb47aea06d083dccb
Ajout d'un ID de dashboard metabase à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
=> Ajout d'un ID de dashboard metabase

itou/users/admin.py, itou/users/migrations/0009_alter_user_kind.py, itou/users/models.py
C'est une information plus complète que "is_staff" qui correspond au type administrateur
=> Ajout du type d'utilisateur dans l'admin

itou/templates/utils/widgets/duet_date_picker_widget.html, itou/utils/widgets.py, pyproject.toml
- Afficher tous les attributs du widget (ex `aria-label`)
- Cohérence avec les widgets de Django
- Forcer l’utilisation de `identifier` et non `id` pour le widget
=> Amélioration du rendu de DuetDatePickerWidget

itou/users/adapter.py, itou/users/models.py, itou/users/tests/test_models.py, itou/utils/perms/context_processors.py, itou/www/apply/tests/tests_list.py, itou/www/employee_record_views/tests/test_list.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siaes_views/tests/tests_job_description_views.py
On privilégie le champ `identity_provider` pour identifier les utilisateurs de PE Connect.
=> users: drop is_peamu property

itou/www/autocomplete/tests.py, itou/www/autocomplete/views.py
Carte Notion : https://www.notion.so/plateforme-inclusion/Am-liorer-la-recherche-de-communes-ASP-18be9bbf90d14c45a1913ed8b98efb90
Prise en compte des retours sur la recette de https://github.com/betagouv/itou/pull/2051
Le problème de code postal n'est en revanche pas présent sur ce formulaire.
=> Amélioration de l'autocompletion des commues pour les fichies salariées (bis)

itou/approvals/management/commands/export_pe_api_rejections.py, itou/approvals/tests/test_management_commands.py, itou/job_applications/export.py, itou/job_applications/tests/tests.py, itou/prescribers/management/commands/update_refused_prescriber_organizations_kind.py, itou/scripts/management/commands/export_approvals.py, itou/scripts/management/commands/export_auto_prescriptions.py, itou/scripts/management/commands/update_nir_from_pass.py, itou/siae_evaluations/admin.py, itou/siae_evaluations/tests/test_admin.py, itou/templates/apply/list_of_available_exports.html, itou/users/management/commands/deduplicate_job_seekers.py, itou/users/tests/test_management_commands.py, itou/utils/export.py, itou/utils/management_commands.py, itou/utils/testing.py, itou/www/apply/tests/tests_list.py, itou/www/apply/urls.py, itou/www/apply/views/list_views.py, requirements/base.in, requirements/base.txt, requirements/dev.txt
https://www.notion.so/Export-XLSX-au-lieu-de-CSV-ac904d6d521b4076b9b3c5ee8b874ca9
On est en ~2022~2023 et on ne veut pas traiter des problèmes d’import de fichier au support
Liste des exports :
- :heavy_check_mark:  Candidatures
- :heavy_check_mark:  Siae_evalusation (admin)
Pour les exports des management commands, je ne sais pas si c'est très utile de le faire....
Est-ce que ce sont est exports qui servent à donner à des utilisateurs après ou juste pour des besoins de dev / interne?
- :heavy_check_mark: export_pe_api_rejections
- :x: update_nir_from_pe_data (logs)
- :heavy_check_mark:  update_refused_prescriber_organizations_kind
- :heavy_check_mark:  export_auto_prescriptions
- :x: geolocate_jobseeker_addresses (usage interne)
- :x: update_nir_from_pass (logs)
- :x: …
=> Exporter en XSLX au lieu de CSV

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/job_seekers.py
Le queryset appelé est tellement large que la commande ne termine jamais.
Corriger en s'appuyant sur les travaux d'antoine pour en faire un fix immédiat, et le tester.
Au passage ne pas faire de retry sur ce check, ça n'a pas de sens.
=> metabase: Correction du freeze de la commande check_inconsistencies

itou/templates/siae_evaluations/institution_evaluated_siae_notify.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/2-4-Pack-Sanctions-En-tant-que-DDETS-je-peux-consulter-le-d-tail-du-r-sultat-n-gatif-de-la-SIAE-et-431c34731f224be48e5d637e447661f5**
Aide à la décision pour les DDETS.
=> Contrôle a posteriori : Afficher des statistiques sur la page de sanction

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
Le nombre d’éléments n’est pas gardé en mémoire sur le `QuerySet` quand la méthode `.count()` est utilisée.
=> Retrait d’une requête en double dans EvaluationCampaign.populate

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
Ajouté dans 419ab0bce36042d0a065b09c1e54a68a3836c347 pour contourner un problème lors de la création des premières campagnes, inutilisé depuis.
=> Retrait de l’argument upperbound de EvaluationCampaign.populate

itou/api/employee_record_api/tests/tests.py, itou/conftest.py, itou/employee_record/factories.py, itou/employee_record/tests/tests_models.py, itou/utils/faker_providers.py, itou/www/employee_record_views/tests/test_disable.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/tests/test_reactivate.py, itou/www/employee_record_views/tests/test_summary.py
Mais aussi l'occasion d'ajouter un nouvel outil à notre ceinture afin d'avoir des tests toujours-plus-mieux©®.
La fixture pytest `itou_faker_provider` s'occupe d'ajouter le nouveau provider aux instances unique de `Faker` :
- La fixture pytest de _Faker_, j'utilise `_session_faker` car la `faker` utilise un scope `function` contrairement à ce que la documentation indique.
- La déclaration `Faker()` de _factory_boy_ pour l'utiliser dans les factory.
C'est la raison qui fait que j'injecte la fixture pytest dans les `TestCase`, afin de ne pas avoir à répéter l'ajout du provider à chaque instanciation de `Faker()`.
A noter l'utilisation de [`.unique`](https://faker.readthedocs.io/en/master/index.html#unique-values) dans `test_reactivate()` qui est assez pratique je trouve :).
=> Création du `ItouProvider` pour Faker afin de remplacer les `RIAE_FS_...` par des `.asp_batch_filename()`

itou/metabase/sql/026_suivi_etp_realises_v2.sql, itou/metabase/sql/027_suivi_etp_conventionnes_v2.sql, itou/metabase/sql/028_suivi_consommation_etp_V2.sql, itou/metabase/sql/029_suivi_consommation_mensuelle_etp_V2.sql
**Carte Notion : **  [Suivi opérationnel des effectifs mensuels exprimés en ETP](https://www.notion.so/plateforme-inclusion/Cr-er-un-tableau-de-bord-du-suivi-op-rationnel-des-effectifs-mensuels-exprim-s-en-ETPs-a2cd262583194ed9b6c3734d9c7a937c)
Changement de titres de colonnes pour coller aux définitions établies par Aurélie + ajout du calcul des ETPs conventionnés mensuels
=> ETPs : changements de nomenclatures et ajouts de colonnes

itou/metabase/management/test_populate_metabase_emplois.py, itou/static/vendor/tarteaucitron/tarteaucitron.js, itou/static/vendor/tarteaucitron/tarteaucitron.services.js
- François m'a fait part d'un test flaky: je le corrige ici de manière certes brouillon mais directe (pas de monkeypatch complexe etc)
- David m'a fait remarquer que le souci avec tarteaucitron est que le thème itou ne supporte pas la dernière version et qu'il se chargera de l'intégraiton plus tard, je downgrade donc ce qui devrait retirer la bannière bizarre. Cette approche est plus sage que celle que j'avais proposée initialement qui consiste à forcer le CSS de manière extérieure avec des `!important`.
=> Petits correctifs : test flaky, bannière tarteaucitron

itou/approvals/tests/tests.py, itou/templates/approvals/email/new_prolongation_for_prescriber_body.txt, itou/www/apply/forms.py
**Cartes Notion : **
- https://www.notion.so/plateforme-inclusion/Zammad-prolongation-Afficher-n-PASS-sans-espace-ae08f1a64ec3463a90052812231dfa80
- https://www.notion.so/plateforme-inclusion/Modifier-un-message-d-alerte-confus-ad2f65a1487b459e9201fc75aee94387
- E-mail de confirmation de candidature envoyé au prescripteur : affichage du numéro de PASS IAE sans espace.
- Modification d'un message d'alerte.
=> Boost février

itou/static/js/city_autocomplete_field.js, itou/www/autocomplete/tests.py, itou/www/autocomplete/views.py
The search suffered from many issues.
It could return entries that had nothing to see with the query. The order was seemingly random. The number of results was frustrating when looking for a city that exists in many different departments.
Also there were issues related to the case and accent matching.
We could not lookup by post code either.
Address all of that.
**Carte Notion : https://www.notion.so/Am-liorer-la-recherche-de-communes-cf94f8db05c34730aa9ec71e0baa692c**
CF le ticket, la recherche est hasardeuse au mieux.
Cesser d'utiliser des trigrammes, avoir un tri plus malin.
=> Améliorer l'ordre, la précision et la qualité des résultats de recherche de villes par autocomplétion

clevercloud/crons/populate_metabase_emplois.sh, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/evaluated_job_applications.py, itou/metabase/tables/evaluated_siaes.py, itou/metabase/tables/evaluation_campaigns.py, itou/metabase/tables/institutions.py, itou/metabase/tables/utils.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Import-des-tables-contr-le-du-contr-le-posteriori-23f28d51d1684fa1ba389eb7d8d399dc**
(CAP = Contrôle a posteriori)
- institutions
- cap_campagnes
- cap_structures
- cap_candidatures
Pour permettre l'élaboration de KPI et TB pour le C1.
=> [Metabase] Ajout des tables du CAP

itou/metabase/sql/029_suivi_consommation_mensuelle_etp_V2.sql
Changement de nom d'une colonne pour que le script tourne
=> [Metabase] ETP conventionnés : correction d'un oubli de changement de nom

itou/approvals/test_notify_pole_emploi.py, itou/employee_record/factories.py, itou/employee_record/management/commands/clone_orphan_employee_records.py, itou/employee_record/models.py, itou/employee_record/tests/test_clone_orphan_employee_records.py, itou/siaes/factories.py
L'`asp_id` n'est pas unique par `SiaeConvention()` ce qui peux donc générer ce genre d'erreur :
```
itou.siaes.models.SiaeConvention.MultipleObjectsReturned: get() returned more than one SiaeConvention -- it returned 2!
```
Normalement tout est expliqué dans le commit.
=> Permettre à `clone_orphan_employee_records.py` de fonctionner pour les SIAE ayant plusieurs mesures

itou/metabase/sql/028_suivi_consommation_etp_V2.sql
Right join au lieu d'un left joint -> On zappait des infos c'est donc corrigé
=> [Metabase] : Correction d'une jointure

itou/templates/siae_evaluations/institution_evaluated_siae_notify.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/il-manque-les-deux-s-parateurs-horizontaux-213286b81c904d41aa772de537d102d9**
=> Ajout de <hr> à l’encart données des sanctions contrôle a posteriori

itou/templates/siae_evaluations/institution_evaluated_siae_notify.html
**Carte Notion : https://www.notion.so/plateforme-inclusion/le-bloc-devrait-s-arr-ter-avant-en-fonction-du-contenu-c6b112f119a2481fb3e12be661299d77**
Réduit la hauteur du bloc « données ».
Aligner horizontalement les titres des cartes.
=> Ajuster les placements encart données sur la page sanction

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Publier-le-TB-Femmes-dans-l-IAE-3cfa59734b9548a6938b0155b9abeb1e
Ajout d'un ID de dashboard metabase à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
=> Ajout de l'ID 216 de dashboard metabase

itou/templates/apply/submit/create_or_update_job_seeker/step_1.html, itou/utils/emails.py, itou/utils/tests.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
**Carte Notion : ** https://www.notion.so/En-tant-que-professionnel-qui-postule-pour-un-candidat-je-ne-veux-pas-faire-d-erreur-lorsque-je-rens-fdcd4ff16a6745cb9328e72f5657a732
Pour limiter les comptes dupliqués de candidats.
=> Détection de candidat existant lors de la création d'un nouveau candidat

itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/En-tant-que-DDETS-je-souhaite-pouvoir-visualiser-tout-moment-les-justificatifs-et-commentaires-p-eb852e0e303e43d3b16cc34be7f6ed49
Actuellement, en phase contradictoire, la DDETS n'a plus accès aux justificatifs.
=> Controle a posteriori: toujours afficher le lien vers les justificatifs

itou/utils/export.py
Cette fonction sera retirée dans la prochaine version.
Refs https://github.com/betagouv/itou/pull/2096
=> Remplace la fonction dépréciée openpyxl.writer.save_virtual_workbook

itou/metabase/management/commands/populate_metabase_matomo.py, itou/metabase/management/test_populate_metabase_matomo.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-le-tracking-du-TB-suivi-pass-iae-dans-le-suivi-des-visiteurs-18536f30490a4d2ea7d7a69872675960**
Demande pour le C2.
=> metabase-matomo: Ajout de la synchronisation pour le TB public "suivi pass IAE"

itou/employee_record/admin.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/employee_record/tests/tests_update_management_command.py
Erreur sur la production : `Can't perform update: notification=<EmployeeRecordUpdateNotification pk=...>, ex=TypeError('the JSON object must be str, bytes or bytearray, not dict')` suite à #2042.
Un test existe mais celui ne couvrais pas ce chemin de code car aucun fichier n'étais trouvé donc pas d'enregistrement de notification.
J'en profite aussi pour corriger quelque truc au niveau de l'admin, notamment les `readonly_fields` pour éviter des erreurs bêtes.
=> [Hotfix] Correction de l'enregistrement des notification de changement de la fiche salarié

itou/templates/includes/test_accounts.html
Agrandir la zone clickable pour utiliser un compte.
Les outils peuvent facilement être un poil plus pratiques et jolis.
=> Petites améliorations à l’écran de comptes de test

itou/templates/layout/base.html
Forgotten chars were responsible for the failing init of tarteaucitron.
Stupid error, but difficult to cover with a test.
En attendant, pas de données envoyées vers Matomo.
=> layout/base: Fix tarteaucitron (urgent !)

itou/scripts/management/commands/update_suspensions_end_at.py, itou/scripts/tests.py
**Carte Notion : ** (à créer)
[Carte Notion du script précédent.](https://www.notion.so/plateforme-inclusion/2-2-Suspension-36-mois-R-gularisation-sur-le-stock-des-PASS-IAE-suspendus-pour-12-mois-BOOST-18795bec5259430382701d67a3a879e0)
(à rédiger)
- Enregistrement des bonnes dates des suspensions en erreur.
- Gestion des exceptions: 1 PASS ayant été supprimé et 10 suspensions ayant été modifiée par un utilisateur.
=> Correction de 1790 suspensions qui finissent dans trop longtemps

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
Éviter des erreurs en cas d’accès anonyme. Voir le commit pour les détails.
=> Vérifier qu’un utilisateur est authentifié avant get_current_XXX_or_404

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
- Sortir la condition qui rend le contrôle positif lorsque la SIAE est la dernière à avoir soumis un document avant la clôture de la campagne. Cela permet factoriser des traitements répandus dans différentes branches de code.
- Le code explosera si `reviewed_at` n’est pas défini à la clôture de la campagne. Ce champ est défini lors du passage en phase contradictoire, ce qui arrive forcément suivant le planning de la DGEFP.
- Certains tests créaient une situation invalide, où une campagne terminée n’avait `reviewed_at=None`.
- `test_review` ne vérifiait pas un scénario réaliste (faire des revues sur une campagne terminée). Il a été supprimé.
=> Simplification du calcul d’état des évaluations de SIAE

itou/templates/siae_evaluations/includes/evaluation_data.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Sanctions-Affichage-des-sanctions-des-campagnes-pr-c-dentes-dans-l-encart-de-donn-es-d-aide-la-d--9ac0d922f0f040e89e90ac4dabbe8173
Pour aider la prise de décision
=> Controle a posteriori: affichage de l'historique des sanctions dans les données d’aide à la décision

config/settings/_sentry.py
Tout chaud de la version [1.15 ](https://github.com/getsentry/sentry-python/releases/tag/1.15.0)
=> settings: ajout de l'intégraton sentry HueyIntegration

itou/metabase/sql/034_candidats_auto_prescription.sql
Correction d'un petit problème d'id qui se superposent, non visible quand le script est lancé en très local chez les data analyst avec des common table expressions
pour le reste des explications cf cette PR : https://github.com/betagouv/itou/pull/2106
=> metabase : fixing a duplicated id problem

clevercloud/crons/populate_metabase_emplois.sh, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/criteria.py, itou/metabase/tables/evaluated_criteria.py
**Carte Notion : https://www.notion.so/Import-des-tables-contr-le-du-contr-le-posteriori-tape-1-DONE-tape-2-WIP-23f28d51d1684fa1ba389eb7d8d399dc**
Pour permettre à Laurine de produire des TB et KPI du CAP pour le C1.
Ajout de deux nouvelles tables :
- `cap_critères_iae`
- `critères_iae`
Objectif MEP d'ici mardi pour le retour de Laurine.
=> [Metabase] [CAP] Ajout des tables des critères administratifs

itou/approvals/admin.py, itou/approvals/tests/tests.py, itou/employee_record/models.py, itou/employee_record/tests/tests_models.py
**Carte Notion :** Remontée support
Si la SIAE change de SIRET ou de convention alors les FS déjà créées restent sur les anciennes données, ces données étant périmées l'ASP les refusent et la FS n'est pas intégrée.
Je fait également `approval_number` pour gérer le cas (plus rare) où l'on crée un nouveau PASS IAE pour une personne suite à une erreur lors de l'embauche, l'idée étant de dire "Désactive/Réactive, si ça ne marche pas il y a quelque chose à corriger" plutôt que d'avoir des cas particuliers.
Le faire pour `asp_id` est normalement inutile car la FS est orpheline et donc plus affichée à la SIAE, mais au moins c'est exhaustif et si il y a un trou quelque part ça permet de rester dans la logique "Désactive/Réactive".
Le reste des infos est dans le commit.
=> Mettre à jour les champs dénormalisés sur les transitions `NEW` et `READY` plutôt que `SENT`

itou/siae_evaluations/migrations/0003_reset_evaluated_siae_notified_at.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Reprise-de-stock-des-SIAE-pour-lesquelles-la-DDETS-a-utilis-la-V1-du-module-des-sanctions-f171c4dba82d4e19b17741156408eb33**
Certaines DDETS n’ont pas suivi le nouveau processus de sanctions (car il n’était pas disponible avant le 13 février).
Liste des SIAE mises à jour :
| EvaluatedSiae id | SIAE id |
|------------------|---------|
| 810              | 5217    |
| 889              | 7586    |
| 892              | 6339    |
| 893              | 6355    |
| 918              | 7584    |
| 1019             | 5109    |
| 1020             | 5119    |
| 1025             | 9848    |
| 1026             | 3896    |
| 1027             | 5133    |
| 1049             | 4740    |
| 1051             | 2725    |
| 1052             | 10251   | …
=> RàZ le champ notified_at pour les sanctions SIAE incomplètes

itou/templates/stats/stats.html
Avant ce fix, le popup était infermable.
Voir fil slack https://itou-inclusion.slack.com/archives/CT7986ULC/p1676455510844709
Je n'ai pas eu le temps de tester en local dev, mais il n'y a rien à perdre vu l'état actuel et l'urgence.
=> [Stats] Fix du popup Tally

itou/www/autocomplete/views.py
Il y a (à date) 11 villes s'appelant Saint-Paul en France: une n'était donc pas trouvable.
=> Autocomplétion : augmentation du nombre de résultats pour les communes de 10 à 50

itou/templates/employee_record/list.html
Certains employeurs (groupe Actual) remontent le fait qu'une FS complétée ne s'envoit pas comme un bug. Ils ne comprennent pas qu'il suffit d'attendre quelques heures pour un envoi automatique. Ils pensent qu'ils ont encore une action à faire, ce qui n'est pas le cas.
Cf fil ([lien](https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1673021278502709))
=> [FS] Amélioration du message confusant à propos des FS complétées en attente d'envoi

itou/templates/account/activate_inclusion_connect_account.html, itou/www/login/tests.py, itou/www/login/views.py
Carte Notion : https://www.notion.so/plateforme-inclusion/Bugfix-Activation-compte-Inclusion-Connect-0d0825c2103b4216a5bdfacde1e976fd
Faire gagner du temps à l’utilisateur.
=> Pré-remplir l'email sur inclusion connect pour un utilisateur voulant activer un compte qui l'est déjà

itou/templates/stats/stats.html
**Fil slack : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1676909525575239**
En chargeant le js tally dans le bon ordre en le déplacant dans le `{% block script %}`.
=> [Stats] Tentative de résolution d'un souci technique avec le popup Tally sur les vues stats

itou/users/migrations/0013_user_has_kind.py, itou/users/models.py, itou/users/tests/test_models.py
L’exception doit être `raise` pour être utile, la construire seulement ne nous sert pas.
Aussi, le champ est validé par une `CheckContraint`.
=> Retrait d’un garde invalide dans User.save()

itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
Assurer que le message s’affiche une seule fois, après chaque revue.
Au lieu de tenter de deviner quand afficher le message (`show_notified`), utilisation de `django.contrib.messages` pour n’afficher le message qu’une seule fois, lors de la revue.
=> Utilisation de messages.success à la notification de revue DDETS

clevercloud/crons/populate_metabase_emplois.sh, clevercloud/crons/populate_metabase_matomo.sh
set -o errexit ignores anything that happens in a subshell.
En attendant, les crashes de ces scripts sont silencieux.
=> populate_metabase, populate_emplois: actually crash if errors

itou/users/admin.py, itou/users/admin_forms.py, itou/users/tests/test_admin_views.py
Le type d’utilisateur est central a itou et doit être spécifié. Une `CheckConstraint` a été ajoutée avec 58c68c9899f358c9de8163a3362d1ae4c24735da pour vérifier ce point. La création d’utilisateurs via l’admin Django ne respectait pas cette contrainte.
=> Spécifier le type d’utilisateur à la création dans l’admin

itou/metabase/sql/035_suivi_cap.sql, itou/metabase/sql/037_suivi_cap.sql
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Cr-er-les-indicateurs-contr-le-du-contr-le-posteriori-e7b99880b3b649cd9bf7d2542f5b26ef?pvs=4
Pour suivre les structures controlées par département et par campagne.
=> Metabase : Création de la table pour le suivi du contrôle à posteriori

itou/templates/siae_evaluations/evaluated_siae_sanction.html, itou/www/siae_evaluations_views/tests/test_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Changer-le-bouton-Revenir-au-tableau-de-bord-par-un-lien-retour-qui-redirige-vers-la-liste-des-SIA-69243c83fc3c4ad5a15a15cc8091dd69?d=ba29e517a30742a2b88685b41298b08d**
On s'est planté en appliquant les recommandations (pas forcément claires) de la carte. Les UX m'ont répondu post-merge de la PR de boost.
=> siae_evaluations: Corriger le wording d'un bouton sur la page des sanctions d'une SIAE

itou/templates/apply/includes/job_seeker_info.html
Simplifier le code et ne pas répéter plusieurs fois le même lien, texte, etc
On garde la typo modfifier-les-informations-personnelles pour ne pas fausser les stats matomo
=> Candidature: réusinage lien avec matomo-event

itou/employee_record/management/commands/clone_orphan_employee_records.py, itou/employee_record/models.py, itou/employee_record/tests/test_clone_orphan_employee_records.py, itou/employee_record/tests/tests_models.py
Quand les antennes deviennent connus de l'ASP et ne sont pas rattaché à la même convention qu'auparavant  (`asp_id` différent)  alors leur fiches salariés deviennent "orphelines" et disparaissent de l'interface employeur, en attendant la mise en place de l'interface dédiés à la récupération de ces FS il faut pouvoir redonner accès à ces FS aux employeurs.
1. Modification de `clone_orphan(self, asp_id)` en `clone(self)` car il n'y a pas vraiment de raison de vouloir avoir un `asp_id` différent de celui de la convention, cela créerais une FS orpheline...
2. Gestion du changement de l'`asp_id` et du `siret` pour les antennes en ne demandant plus `--old-asp-id`/`--new-asp-id` mais `--for-siae`, ce qui permet au script de traité le cas:  _N antennes (1 SIAE, 1 Convention) => N SIAE, N …
=> Gestion des antennes pour `clone_orphans_employee_records`

itou/siae_evaluations/tests/tests_models.py, itou/siaes/models.py, itou/static/css/itou.css, itou/templates/apply/includes/buttons/new_diagnosis.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/utils/models.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/process_views.py, itou/www/apply/views/submit_views.py, itou/www/dashboard/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/4-4-Pack-Sanctions-En-tant-que-SIAE-sanctionn-e-je-ne-peux-plus-r-aliser-d-auto-prescription-penda-52b7f76129b84abdaffd3c593751ffcd
Pour que les sanctions soient appliquées.
=> Controle a posteriori: application des suspensions d'auto-prescription

itou/templates/apply/includes/job_seeker_info.html, itou/www/approvals_views/tests/test_detail.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/En-tant-que-professionnel-je-veux-comprendre-que-je-n-ai-pas-la-possibilit-de-modifier-les-informat-24359ec8005b47a29bb4c5e503c0bddb?pvs=4
Pour que l'utilisateur comprenne mieux qu'il ne peut pas modifier les informations personnelles.
=> Candidature: bouton désactivé & tooltip pour expliquer qu'on ne peut pas modifier les informations personnelles

.github/pull_request_template.md
Pour ne pas se faire taper sur les doigts par supportix
=> Mise à jour du template de PR pour penser à ajouter le label no-changelog

itou/templates/dashboard/includes/stats.html, itou/templates/siae_evaluations/samples_selection.html, itou/templates/stats/stats.html, itou/templates/stats/stats_test1.html, itou/templates/stats/stats_test2.html, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-er-le-TB-Focus-Autoprescription-et-contr-le-a-posteriori-dans-le-TB-priv-DDETS-DREETS-et-DGEFP-1770e22dc62b4d50946b26443c53780c**
On veut créer plus de valeur pour les DDETS, DREETS et DGEFP.
- Ca commence à faire beaucoup de vues stats DDETS, DREETS et DGEFP au total donc j'ai factorisé un max de code dans les vues, dans de nouvelles méthodes `render_stats_ddets/dreets/dgefp`. Le refacto est dans un commit séparé.
- Pas de test supplémentaire, j'avoue que comme `user.can_view_stats_ddets/dreets/dgefp` est déjà testé je vais pas plus loin avec ces nouveaux TB.
Ce que voit une DDETS.
Une DREETS.
Et la DGEFP.
=> Metabase : Ajout de deux nouveaux TB (Auto-prescription et Suivi CAP) aux DDETS / DREETS / DGEFP => MEP en cachant les TB car pas encore prêts

itou/metabase/sql/033_siae_pratiquant_autoprescription.sql
A la demande de la DGEFP, ajout de l'année pour le suivi du nombre de structures pratiquant l'autoprescritopn
=> metabase : ajout de l'année dans l'auto prescription & SIAE

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
Lié à https://www.notion.so/En-tant-que-SIAE-qui-a-soumis-ses-justificatifs-en-phase-2-mais-qui-n-ont-pas-t-contr-l-s-temps--a0c3feddc60046aeb1807fe8a3fff1d5?d=744125640d614733b763ef4159de741f
Auparavant, le système ignorait les SIAE qui avaient envoyés des documents lors du passage en phase contradictoire, ce qui pénalisait les SIAE ayant envoyé leurs justificatifs sans qu’ils ne soient revus par la DDETS.
Maintenant, en l’absence de réponse de la DDETS, les SIAE ayant soumis leurs documents avant la fin de la phase amiable obtiennent un contrôle positif lors du passage en phase contradictoire. Le principe général de l’administration s’applique : l’absence de réponse dans les délais impartis implique consentement.
Pour clarifier ce nouveau comportement du système, un message explique …
=> Transitionne toutes SIAE en phase contradictoire

itou/siae_evaluations/emails.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_siae_force_accepted_body.txt, itou/templates/siae_evaluations/email/to_siae_force_accepted_subject.txt
**Carte Notion : https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-qui-a-soumis-ses-justificatifs-en-phase-2-mais-qui-n-ont-pas-t-contr-l-s-temps--a0c3feddc60046aeb1807fe8a3fff1d5**
Les informer.
=> Notifier les SIAE dont le contrôle vient d’être forcé positif

itou/siae_evaluations/emails.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_institution_siaes_forced_to_adversarial_stage_subject.txt, itou/templates/siae_evaluations/email/to_institution_siaes_transition_to_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_institution_siaes_transition_to_adversarial_stage_subject.txt
**Carte Notion : https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-qui-a-soumis-ses-justificatifs-en-phase-2-mais-qui-n-ont-pas-t-contr-l-s-temps--a0c3feddc60046aeb1807fe8a3fff1d5**
Informer les DDETS de ce comportement du système, et leur donner plus de détail sur le passage en phase contradictoire.
=> Envoyer un rapport des EvaluatedSiae acceptées par défaut aux DDETS

itou/templates/siaes/includes/_card_siae.html
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=77ca3159cc404d9d97afcd10fe7efdf4&pm=c
Haromniser l'UI sur la carte des SIAE en enlevant le gras dans l'adresse.
=> fix: suppression du gras sur l'adresse d'une SIAE

itou/common_apps/organizations/models.py, itou/job_applications/models.py
Cela complexifie le code qui doit alors gérer différents types d'utilisateur.
Si un super-utilisateur veut avoir accès il peut soit rajouter un des comptes de support (assistanceemployeur@inclusion.beta.gouv.fr, etc) à l'organisation, soit utiliser la fonctionnalité de hijack.
=> Ne plus considérer les super-utilisateurs comme des membres des organisations

itou/templates/siaes/create_siae.html, itou/users/models.py, itou/users/tests/test_models.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/R-activer-l-option-Cr-er-Rejoindre-une-structure-pour-les-GEIQ-0f189147861045ff817717783256ad65
Demande de la FFGEIQ (acceptée par la DGEFP)
=> Autoriser la création d'antenne pour les GEIQ

clevercloud/cron.json
Avant :
```sql
SELECT count("session_key") AS total_session, count("session_key") FILTER ( WHERE expire_date < NOW() ) AS expired_session FROM django_session;
total_session | expired_session 
---------------+-----------------
3471368 |         3383043
SELECT pg_size_pretty(pg_total_relation_size('django_session')) AS django_session_size, pg_size_pretty(pg_database_size('itou')) AS database_size;
django_session_size | database_size 
---------------------+---------------
1925 MB             | 6938 MB
```
Après un `VACUUM FULL django_session;` :
```sql
SELECT count("session_key") AS total_session, count("session_key") FILTER ( WHERE expire_date < NOW() ) AS expired_session FROM django_session;
total_session | expired_session 
---------------+-----------------
86869 |             131
SELECT …
```
=> Nettoyage journalier des sessions expirées

itou/approvals/admin_forms.py, itou/approvals/tests/tests.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Si un candidat a déjà un diasgnostic d'éligibilité, pas besoin de demander à créer un diagnostic pour accepter la candidature
=> Correction de l'embauche pour les candidats avec un diagnostic déjà existant non relié à la candidature

itou/templates/stats/stats.html
**Carte Notion : https://www.notion.so/plateforme-inclusion/Param-trer-les-enqu-tes-en-ligne-sur-le-NPS-dc8e6085d64a4b92bbb4a6437c1c3b15**
Jusqu'ici le popup s'ouvrait à nouveau à chaque fois que la personne revenait sur la page stats. La seule alternative native côté Tally est de ne plus jamais afficher le popup une fois qu'il est rempli. On veut vraiment un juste milieu entre ces deux extrêmes.
Le comportement au final sera : le popup cesse de s'afficher pendant 14 jours à partir du moment où soit 1) l'utilisateur ferme manuellement le popup en cliquant sur la croix en haut à droite, soit 2) l'utilisateur soumet le formulaire. Tant que l'utilisateur n'a fait aucune de ces deux actions on continue d'afficher le popup.
On fait ici un code Javascript dédié qui affiche le popup à nouveau …
=> Stats : Montrer le popup Tally maximum une fois toutes les deux semaines

.github/workflows/ci.yml
to avoid the merge queue getting its build cancelled by the push event (since they have the same pull request but not the same branch)
=> github: add ref_name to concurrency group

itou/employee_record/exceptions.py, itou/employee_record/management/commands/clone_orphan_employee_records.py, itou/employee_record/models.py, itou/employee_record/tests/tests_models.py, itou/siaes/management/commands/move_siae_data.py
**Notion :** https://www.notion.so/plateforme-inclusion/Support-C1-Move-SIAE-data-partiel-Mode-2-b429a83ada564a03bd768d8c328301c7
Pour diverse raisons (plus ou moins légitimes) un salarié de la structure _source_ peux déjà exister dans la structure _destinataire_, on peux donc l'ignorer.
=> `move_siae_data` : Gestion du cas où le salarié à déjà été rembauché

itou/metabase/sql/038_suivi_cap_criteres.sql
**Carte Notion : ** : https://www.notion.so/plateforme-inclusion/Suivi-du-contr-le-posteriori-Prise-en-compte-de-retours-362f52edf1d5453f9540f54753248397?pvs=4
Permettre d'afficher les statistiques détaillées des critères d'éligibilité dans le cadre du suivi du contrôle a posteriori.
=> metabase : CAP : creation d'une table avec le détail des critères d'eligibilité par campagne

itou/templates/account/activate_inclusion_connect_account.html, itou/templates/account/login_generic.html, itou/templates/dashboard/dashboard.html, itou/utils/perms/context_processors.py, itou/utils/tests.py, itou/www/login/views.py
** Carte notion : **  En créer une ? ou rattacher à la carte précédente ?
TODO:
Sinon, le tracking est incomplet
Commentaire du commit (en anglais) : We could rely on UserKind labels, using user.get_kind_display() when available, but tht means :
- changing "employeur" to "employeur solidaire" in SIAE_STAFF label
- any change in labels would change data in matomo (which does not seems a good idea)
Je serai d'avis de ne pas utiliser le label de UserKind pour éviter des erreurs bêtes dans le futur.
=> Correction de balises matomo dans le parcours d'activation de compte Inclusion Connect

itou/openid_connect/inclusion_connect/views.py, itou/www/invitations_views/tests/tests_siae_accept.py
https://www.notion.so/plateforme-inclusion/BUG-une-diff-rence-de-casse-au-niveau-de-l-e-mail-impacte-les-invitations-2d2ed331e8b04529a738a7ba40f47797?pvs=4
Une différence de casse au niveau de l’e-mail impacte les invitations
=> fix: comparaison des emails inclusion connect en casse insensible

clevercloud/cron.json, config/settings/base.py, itou/users/management/commands/shorten_active_sessions.py, itou/users/tests/test_management_commands.py
https://www.notion.so/plateforme-inclusion/V-rifier-s-il-existe-une-d-connexion-automatique-des-utilisateurs-8c402b9de67d426ab639287ad68f6b98?pvs=4
On veut forcer les utilisateurs à se re-connecter régulièrement (notamment pour encourager la migration à Inclusion Connect des employeurs / prescripteurs)
On a le setting `SESSION_EXPIRE_AT_BROWSER_CLOSE = True` qui devrait forcer le navigateur à supprimer le cookie de session à la fermeture.
Cependant certains navigateurs restaurent les sessions (https://developer.mozilla.org/fr/docs/Web/HTTP/Cookies#d%C3%A9finir_la_dur%C3%A9e_de_vie_dun_cookie) donc la session ne se termine jamais.
Comme à chaque changement de SIAE/organisation, ou à chaque parcours de candidature réalisé par un prescripteur ou un employeur on va modifier la session, cela …
=> Déconnecter automatiquement les utilisateurs le lundi matin très très tôt

itou/templates/apply/process_refuse.html, itou/utils/enums_context_processors.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=e45fd06a4cb9432295c2199510c2e8e8&pm=c
Expliquer le motif  de refus “ L’embauche empêche la réalisation des objectifs du dialogue de gestion”
=> feat: ajout d'un tooltip d'explication pour le refus `prevent_objectives`

itou/templates/signup/job_seeker_signup.html, itou/www/signup/forms.py, itou/www/signup/tests/test_job_seeker.py, itou/www/welcoming_tour/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Rendre-obligatoire-la-civilit-du-candidat-En-tant-que-candidat-je-renseigne-ma-civilit-lorsque-j-7cc3fd16482d47c3ad9e8e01d9c18b78?pvs=4
Actuellement il manque la civilité du candidat lors de l'inscription en autonomie
=> Rendre obligatoire la civilité du candidat lors de la création

scripts/deploy_prod.sh
A priori rajouté à l'origine pour faciliter les rollbacks (cf https://github.com/betagouv/itou/pull/747#discussion_r657897032 )
Mais à ma connaissance il y a très peu de rollback.
Je trouve que ce commit de merge n'aide pas pour identifier ce qui tourne en production: avec du fast-forward, on verrait directement sur Clever le dernier commit de master qui tourne en production alors que là il faut regarder les parents du commit de merge.
Et si malgré tout, on souhaite faire un rollback, l'historique des déploiements avec leur commit se trouve sur le canal "tech-notifications-c1".
=> deploy_prod: suppression de l'option --no-ff

itou/templates/dashboard/includes/stats.html
**Carte Notion : https://www.notion.so/plateforme-inclusion/Mettre-disposition-le-guide-d-analyse-PE-sur-leur-espace-priv-3c43be960c064e5a989f2cfa3c66da8b**
Pour que les divers acteurs PE puissent tirer davantage de valeur de leurs stats.
=> Stats : Ajout d'un lien vers le guide d’analyse PE dans l'espace privé PE

scripts/deploy_prod.sh
Suite à c75e20ed8646c21e942b2b08009ffa4f708a8d53, `origin/master_clever` a subi un push force pour se réaligner sur `origin/master`. La plupart des devs ont donc un `master_clever` qui ne pourra pas se rebase sur `origin/master_clever`.
=> deploy_prod: resynchronisation de la branche master_clever

itou/metabase/management/commands/populate_metabase_matomo.py, itou/metabase/management/test_populate_metabase_matomo.py, itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql, itou/metabase/sql/030_taux_penetration_tb_prives.sql
Sometimes the order of execution makes it possible that we don't write any of the results to metabase.
Explanation: we run 20 dashboard fetches in parallel.
Let's imagine that the 19 first to return get us valid values, but unfortunately the 20th and latest is empty.
We would not detect correctly its emptiness and would make `columns` be [], which would in turn make the subsequent check before updating Metabase fail.
Not only because of this but because the Matomo table structure did change, we need to re-run this from the beginning of 2022.
This is tricky to test though cause the order of the ThreadPoolExecutor is by nature non deterministic so it is difficult to design mocks so that the first URLs are filled and "the last one consulted" is empty.
=> matomo: Correction d'un bug qui annule certaines écritures + autres correctifs

itou/approvals/admin_forms.py, itou/approvals/factories.py, itou/approvals/tests/tests.py, itou/eligibility/tests/tests_iae.py, itou/job_applications/factories.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/users/tests/test_models.py, itou/www/apply/tests/tests_submit.py, itou/www/approvals_views/tests/test_display.py
https://www.notion.so/plateforme-inclusion/Associer-les-diagnostiques-aux-PASS-IAE-116db83de976432e93b94474631c7401?pvs=4
Il restait un trou dans la raquette.
=> Correction du formulaire de délivrance manuelle de PASS IAE

itou/metabase/sql/034_candidats_auto_prescription.sql
Retrait de certaines lignes filtrant l'autoprescription directement sur le script sql, alors que cela peut se faire sur metabase (déjà corrigé de ce côté là).
=> [Metabase] : retrait d'une condition inutile

itou/metabase/sql/038_suivi_cap_criteres.sql, itou/metabase/sql/039_suivi_cap_structures.sql
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Suivi-du-contr-le-posteriori-Prise-en-compte-de-retours-362f52edf1d5453f9540f54753248397?pvs=4
Intégrer un filtre par type de structure pour le suivi du CAP
=> Metabase : correctifs pour intégrer un filtre par type de structure sur le tb suivi CAP

itou/metabase/sql/025_suivi_visiteurs_tous_tb.sql
Prise en compte de la table `_v1` pour le suivi des visiteurs des TBs publics et non `_v0`
=> Metabase : prise en compte de la table V1 pour les visiteurs publics

itou/users/admin.py, itou/www/dashboard/forms.py
Vu qu'on ne compte pas conserver PEAMU sur le long terme, et que modifier la connexion pour mettre à jour ces informations est complexe, autant juste donner la main au support et à l'utilisateur pour modifier les nom/prénom/email
=> Permettre de changer les informations personnelles d'utilisateurs sous PE Connect

itou/metabase/sql/038_suivi_cap_criteres.sql
Les critères à l'état pending peuvent en réalité être de deux types différent : 
- Non transmis : si pas de date de transmission et état pending
- Non contrôlés : si une date de transmission mais toujours état pending 
On souhaite pouvoir distinguer les deux cas sur le suivi des critères.
=> Metabase : suivi contrôle a posteriori -> distinguer les criteres non transmis de ceux non controlés

itou/prescribers/enums.py, itou/prescribers/models.py, itou/templates/dashboard/includes/stats.html, itou/users/models.py, itou/users/tests/test_models.py, itou/www/stats/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Identifier-les-DTPE-dans-C1-pour-un-acc-s-aux-donn-es-des-d-partements-rattach-s-cfb152057ab146a8a0e847ab8d446118**
Jusqu'ici les DTPE étaient indistinguables des agences PE classiques, et donc n'avaient accès qu'aux stats de leur département.
Or certaines DTPE sont techniquement multi-départements, on doit donc les recenser pour leur donner accès à leurs différents départements automatiquement.
Similairement à la méthode qu'on utilisait déjà pour les DRPE et la DGPE.
=> Stats : Identification des DTPE (organisations PE qui chapeautent un département voire parfois plusieurs départements)

itou/templates/apply/process_cancel.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
https://www.notion.so/plateforme-inclusion/Adapter-le-texte-de-confirmation-d-annulation-d-embauche-pour-les-structures-GEIQ-EA-et-OPCS-boost-e5176bea4d1345c783a188e32c7ea661?pvs=4
Certaines structures ne sont pas concernées par les PASS IAE, il ne faut pas leur en parler.
=> BOOST: Amélioration de l'alerte d'annulation de candidature

itou/templates/dashboard/includes/dora_card.html, itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/prescriber_organisation_card.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py
https://www.notion.so/plateforme-inclusion/Retirer-le-tag-nouveau-du-bloc-dora-et-bloc-salari-s-54378a3e41e5493da882b11f64ded725?pvs=4
Les blocs espace salarié, dora et contrôle à posteriori ne sont plus vraiment nouveaux
=> Retirer le tag "nouveau" de certains fonctionnalités

config/settings/base.py
**Fil slack : https://itou-inclusion.slack.com/archives/CT7986ULC/p1678980016000689**
On a une erreur `Refused to display 'https://emplois.inclusion.beta.gouv.fr/' in a frame because it set 'X-Frame-Options' to 'deny'.` dans certaines situations, par exemple depuis https://pilotage.inclusion.beta.gouv.fr/tableaux-de-bord/cartographies-iae/
L'erreur n'est pas complètement comprise, notamment elle disparait mystérieusement en mode incognito (sans cookie). Mais cela n'a aucun sens, une erreur CSP devrait être systématique.
En permettant le bon `frame-ancestor`.
Liens utiles :
- https://django-csp.readthedocs.io/en/latest/configuration.html?highlight=frame%20ancestor
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
=> Stats : Tentative de résolution d'une erreur CSP sur l'iframe utilisée par le site Pilotage

Makefile, pytest.ini, requirements/dev.in, requirements/dev.txt
Afin de détecter automatiquement les tests qui prendraient trop de temps, par défaut nos tests ne devraient pas prendre plus que quelques secondes donc autant avoir un outils qui le fait pour nous :).
Typiquement, les 15 secondes sont là car il faut un certain temps en `--create-db`, je suppose qu'en simplifier le setup de la DB on devrais pouvoir réduire ce temps, même si ça devrais surement être au plugin de ne pas compter ça dedans :shrug:.
J'ai également ajouté la règle `upgrade-deps` dans le Makefile et enlever le `--upgrade` de `compile-deps` car ça me courrais sur le haricot de modifier les fichiers à la mains lors de l'ajout d'une nouvelles dépendance.
Y a encore des trucs pas clair avec les `--allow-unsafe` et `--generate-hashes` car `pip-compile` veux ajouter ça en fin de …
=> tests: Ajout de `pytest-timeout`

itou/approvals/admin.py, itou/approvals/tests/tests.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/BUG-impossible-de-modifier-une-date-de-d-but-de-PASS-m-me-si-la-fiche-salari-est-archiv-e-ou-d-sact-daa36165790e48edb905d2c6f7e2fc12
Suite de 0e55b95de
=> Admin PASS IAE : Ré-autoriser la modification quand la FS existe pour certain statuts

itou/templates/apply/includes/buttons/accept.html, itou/templates/apply/includes/geiq/check_geiq_eligibility_form.html, itou/templates/apply/includes/geiq/continue_without_geiq_diagnosis_form.html, itou/templates/apply/includes/geiq/geiq_diagnosis_details.html, itou/templates/apply/includes/geiq/no_allowance_modal.html, itou/templates/apply/process_accept.html, itou/templates/apply/process_details_prescriber.html, itou/templates/apply/process_details_siae.html, itou/utils/enums_context_processors.py, itou/www/apply/views/process_views.py
A relire commit par commit
Faciliter la réutilisation des includes sans devoir passer trop de variables
=> Simplification / Suppression de variables à passer aux templates

itou/templates/apply/includes/buttons/accept.html, itou/www/apply/views/process_views.py
This reverts commit 72e13ddf4d6b4c9d840ac4c68ef4900a4ebd475f.
Sinon la modale apparait pour chaque acceptation hors GEIQ (car ces SIAE n'ont - assez logiquement - pas de diagnostique GEIQ).
=> Revert "www.apply: remove show_geiq_eligibility_modal variable"

itou/users/admin.py
Il est globalement redondant d'afficher les candidatures envoyées pour un candidat ou les candidatures des employeurs et prescripteurs.
Avec cette implémentation il est possible que de la donnée soit masquée si une candidature est envoyée pour un utilisateur qui n'est pas candidat, le bloc `JobApplicationInline()` n'étant pas affiché, et que cette candidature n'a pas été envoyée par l'utilisateur visualisé, puisque non récupérée par `SentJobApplicationInline()`.
=> Admin - Utilisateur : Forcer l'affichage de certaines informations liées que si le type correspond

itou/templates/static/legal/privacy.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/cgu-Mettre-jour-adresse-mail-5a214598ddb34ba8bd530e25ff9ee431?pvs=4
L'email a changé.
=> Mise à jour de l'adresse email de contact dans les mentions légales

requirements/base.txt, requirements/dev.txt
Eviter le `DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13`
=> requirements: upgrade boto3 & botocore

itou/metabase/sql/032_metier_candidatures.sql
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Ajouter-dans-TB-genre-la-sectorisation-17df3cf3af5f44a4b8a318d93b03a210?pvs=4
Créer des indicateur sur la répartition des candidatures h/f en fonction du secteur d activité
nécessaire de passer par cette table car une candidature peut être associée à plusieurs fiches de poste
=> Metabase : ajout du genre sur la table candidatures par secteur

itou/approvals/models.py, itou/approvals/test_notify_pole_emploi.py, itou/prescribers/enums.py, itou/prescribers/tests.py, itou/utils/apis/pole_emploi.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Envoyer-le-type-de-prescripteur-P-le-emploi-007047d944224dab95a004a48ddd8cab
Enrichir les infos transmises dans les dossiers PE
Attention, comme indiqué dans le ticket et le PPT joint, certains types de prescripteurs sont "sensibles" et on préfère donc envoyer la catégorie "Autre".
=> Envoyer le type de prescripteur à Pôle emploi

itou/static/css/itou.css, itou/templates/employee_record/list.html, itou/www/employee_record_views/forms.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/tests/test_reactivate.py, itou/www/employee_record_views/views.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/2-2-Simplifier-la-recherche-des-fiches-salari-En-tant-que-SIAE-je-veux-filtrer-les-fiches-salari-2d839498402946ac805d3d3f9ec26263
Faciliter la recherche d’une fiche salarié.
A noter que les badges (à droite des statuts) ne sont pas impactés par le filtre, l'idée est que l'on indique toujours le nombre total.
=> Simplifier la recherche des fiches salarié : Ajout du filtre par nom du candidat

itou/metabase/sql/037_suivi_cap.sql
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Suivi-du-contr-le-posteriori-derniers-retours-avant-d-ploiement-854a9d94fd62412d90d7377b2b840baa?pvs=4
Correction d'incohérences liées aux structures inactives mais contrôlées.
=> Metabase : CAP : ne prendre en compte que les structures actives 

itou/templates/apply/submit/application/base.html, itou/users/models.py, itou/users/tests/test_models.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Correction de deux anomalies repérées en production :
- affichage du badge d'éligibilité GEIQ incorrect pour les diagnostics valides mais sans montant d'allocation
- les orienteurs pouvaient avoir accès à la saisie de critères GEIQ
=> Corrections : badge d'éligibilité GEIQ et redirection des orienteurs

itou/api/applicants_api/views.py, itou/api/employee_record_api/viewsets.py, itou/api/token_auth/tests.py, itou/api/token_auth/views.py, itou/api/urls.py, itou/templates/dashboard/api_token.html, itou/templates/layout/_nav_btn_items.html, itou/www/dashboard/tests.py, itou/www/dashboard/urls.py, itou/www/dashboard/views.py
Carte Notion : https://www.notion.so/plateforme-inclusion/Acc-s-l-API-avec-un-compte-Inclusion-Connect-7f56844b0f624e06b746fa4030f3937c
Une fois passé à inclusion connect, il est impossible d'agir sur son mot de passe pour le changer et donc accéder à l'api de génération de token
=> Ajout d'une page pour créer / accéder à son token d'API

itou/templates/employee_record/list.html, itou/www/employee_record_views/tests/test_list.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=79adca370b9c41f5ba8ea58062d05549&pm=c
Le total du nombre de fiches salarié est aussi affiché au dessus de la liste de résultats (pas seulement dans les badges).
=> Affichage du nombre de résultats dans la liste des fiches salarié 

itou/templates/account/login_generic.html, itou/templates/inclusion_connect/includes/description.html
**Discussion :** https://itou-inclusion.slack.com/archives/C0403V04UAD/p1680096958849269
Sur les vieux firefox, le support de <picture> et <source> ne semble pas pris en compte et l'image dans picture est déformée. 
Hack trouvé, forcer la prise en compte de la taille de l'image.
Le mode "mobile" sur 2 lignes ne fonctionne pas, mais l'image ne déborde plus.
Avant
Apres
=> Correction du bouton inclusion connect pour les vieux firefox

itou/templates/employee_record/list.html, itou/www/employee_record_views/tests/test_list.py
Ajouté, sans test :confounded:, dans 24a1b936b (#2146), mais ensuite supprimé dans ce4335f76 (#2274).
=> Fiches salariés : Correction de la disparition du champ de recherche par candidat

itou/job_applications/models.py, itou/www/apply/tests/tests_list.py
Lenteur importante de la base de données de prod, suite à l’ajout d’une requête de type 1+N pour les villes.
https://itou.sentry.io/issues/4060571138/?project=6164438&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&referrer=issue-stream&sort=inbox&stream_index=1
=> Correction de 1+N pour la ville du poste dans la liste des candidatures

Makefile, requirements/dev-mac.txt
**Fil slack : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1671534012842349**
Je (dejafait) suis le seul dev C1 sous Mac et depuis quelques mois je me débrouillais avec un souci avec le package `appnope` qui est seulement présent sur Mac. Mais aujourd'hui à mon retour de deux semaines AFK, pas moyen de ressuciter mon local dev... du coup j'ai retenté toutes les solutions dans le fil slack plus haut, et au final voici la PR pour pérenniser la seule qui fonctionne.
Ajout d'un `dev-mac.txt` qui permet d'ajouter les packages spécifiques au Mac et stabiliser le build du local dev.
=> Pip :  Résolution d'un souci uniquement présent sous Mac

itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-er-le-TB-Focus-Autoprescription-et-contr-le-a-posteriori-dans-le-TB-priv-DDETS-DREETS-et-DGEFP-1770e22dc62b4d50946b26443c53780c**
Ces nouveaux tableaux de bord était prêts depuis https://github.com/betagouv/itou/pull/2141 mais cachés.
Le grand jour d'ouvrir leur accès est venu !
Voir les screenshots sur https://github.com/betagouv/itou/pull/2141
On ajoute aussi les formulaires Tally correspondants.
Pas de revue car trivial.
=> Stats : Activation de deux nouveaux TB (Auto-prescription et Suivi CAP) pour les DDETS / DREETS / DGEFP

itou/invitations/tests.py
Il n'y avait pas de tests qui couvrait ce cas (vérifier avec un coverage).
Par contre, le code semble bien marcher, ce qui n'explique pas les soucis en prod...
=> itou.invitations: add test for the inactive member case

itou/templates/apply/includes/list_card_body_siae.html, itou/www/apply/tests/tests_list.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Correction-des-requ-tes-1-N-qui-ralentissent-la-prod-f809446c5f87406dab3fc6b11d0bbfa0**
La DB est très chargée suite à ces commits. Retirons les, le temps d’investiguer une façon d’alléger les calculs.
Revert des commits a0164e4caccd959924d7b7808f6890f29ee394fe et
97d9e7b0f9187a61837e90a9d19f855e9918ca90.
=> Cache l’égibilité IAE de la liste des candidatures

itou/templates/siaes/job_description_list.html, itou/www/siaes_views/tests/tests_job_description_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Afficher-le-nombre-de-r-sultats-sur-la-liste-des-metiers-et-recrutements-036885d8b7254386a5a625b23dc52d6f**
- `assert response.status == 200` est déjà effectué par `assertContains()`
- Le niveau de titre a été ajusté pour correspondre aux autres titres du document
=> Afficher le nombre de métiers dans SIAE job_description_list

itou/employee_record/management/commands/clone_orphan_employee_records.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py
`--wet-run` écrit les données dans la base (ou appelle les API). La documentation était incorrecte. Comme la plupart des commandes n’ont pas de `help_text` pour cette option, les `help_text` incorrects ont été retirés.
=> Retrait du help_text pour wet_run des commandes de gestion

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/openid_connect/models.py
https://www.notion.so/plateforme-inclusion/Ne-pas-bloquer-un-utilisateur-d-Inclusion-Connect-qui-a-voulu-changer-son-email-avec-un-email-exista-54aa136eb3ce4addb23452f32597b0d7?pvs=4
Actuellement on les empêche de se connecter une fois déconnecté (par exemple les dimanches) mais ça n'a aucune valeur ajoutée.
Cela n'aura aucun impact sur les demandes au support en revanche.
=> Ne pas bloquer un utilisateur d’Inclusion Connect qui a voulu changer son email avec un email existant déjà pour un autre compte.

itou/www/apply/tests/tests_list.py, itou/www/apply/views/list_views.py
https://www.notion.so/plateforme-inclusion/Export-des-candidatures-impossible-pour-un-orienteur-sans-organisation-36b52f80750f4981b5d0d6a0f57b9731?pvs=4
Il fallait une organisation pour accéder à ce lien avant.
=> Correction de l'export des candidature pour les orienteurs sans organisation

itou/metabase/management/commands/populate_metabase_matomo.py, itou/metabase/management/test_populate_metabase_matomo.py, itou/templates/dashboard/includes/stats.html, itou/www/dashboard/tests.py, itou/www/stats/views.py
- bien penser à faire un `update suivi_visiteurs_tb_prives_v1 set "Tableau de bord"='TB DGEFP IAE' where "Tableau de bord"='TB DGEFP'` juste après la MEP pour rendre le changement de nom de TB dans Matomo rétroactif. @vperron 
- penser à prévenir Y&L du changement en question
Avant (le bug était seulement côté DGEFP)
Après
Avant
Après
=> Stats : Boost Dev C2

itou/prescribers/models.py, itou/users/models.py, itou/users/tests/test_models.py
Les commentaires sur le modèle des prescripteurs laissaient un doute sur la définition métier d'un orienteur.
Pour rappel, un "orienteur solo" est un prescripteur (de type `User` et `kind=="prescriber"`) sans rattachement à une organisation (`PrescriberOrganization`).
L'habilitation étant rattachée à l'organisation, un "orienteur solo" ne peut être habilité.
D'une manière plus générale, les orienteurs sont des prescripteurs sans habilitation, qu'ils aient une organisation ou pas.
=> Modification de commentaires concernant les prescripteurs

.github/pull_request_template.md
- Le commentaire évite d’avoir à retirer le texte à propos de `no-changelog`.
- Le retrait de *(optionnel)* évite d’avoir à modifier le titre de la section lorsqu’elle est remplie.
- Le texte explicatif de captures d’écran me semblait superflu.
=> Simplification du gabarit de pull request

itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/tests/test_sanitize_employee_records.py
Il est possible que certain PASS IAE soient prolongés ou suspendus après qu'une FS ai été `ARCHIVED` mais avant que le PASS IAE soit inutilisable (voir #2297.)
Le nombre de FS archivées alors que le PASS est toujours utilisable étant de 70K+ il n'était pas vraiment concevable de juste changer le statut à `PROCESSED` (ou `NEW`) de celles-ci car cela aurais voulu dire les réafficher aux employeurs alors que la majorité est surement inutile, ce qui aurais surement engendré plus de support que de traiter les cas en erreur au fil de l'eau sachant que le premier lancement va en corriger 100+.
Ajout d'un nouveau check à `sanitize_employee_records` qui vérifiera donc avant chaque envois que les données envoyés vers l'ASP via les FS soient postérieurs aux dernières modifications d'un PASS IAE [1].
=> Fiches salariés : Récupération des notifications manquées

itou/templates/prescribers/edit_organization.html, itou/utils/enums_context_processors.py, itou/utils/htmx/test.py, itou/utils/htmx/tests.py, itou/utils/test.py, itou/www/apply/tests/tests_process.py, itou/www/prescribers_views/forms.py, itou/www/prescribers_views/tests/__snapshots__/test_edit.ambr, itou/www/prescribers_views/tests/test_edit.py, requirements/dev.in, requirements/dev.txt
**Carte Notion : https://www.notion.so/plateforme-inclusion/Emp-cher-les-utilisateurs-de-modifier-les-infos-d-organisation-P-le-emploi-BOOST-4cc28457394a4403adeb30125c648477**
Les utilisateurs PE modifient régulièrement la description de leur organisation par erreur.
Utilisation de [syrupy](https://tophat.github.io/syrupy/) pour les tests, afin de faciliter la comparaison (et la maintenance) de fragments HTML.
=> Lecture seule pour l’organisation de PE

itou/templates/apply/includes/list_card_body.html
**Carte Notion : https://www.notion.so/plateforme-inclusion/Probl-me-d-Affichage-des-badges-sur-les-cartes-candidatures-boost-d07cc0d793b84d4293e803888c1b5506**
=> Ajuster la taille de la colonne badge dans la liste des candidatures

itou/static/js/siae_evaluations_sample_selection.js, itou/templates/siae_evaluations/samples_selection.html, itou/www/siae_evaluations_views/forms.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Retirer-la-case-cocher-qui-permet-une-DDETS-de-ne-pas-r-aliser-la-campagne-de-contr-le-e8bc69f63c5644da86f58cce7a9418bb**
=> CAP: Retrait de l’option pour ne pas participer

itou/templates/apply/includes/list_card_body.html, itou/templates/apply/includes/out_of_band_changes_on_job_application_state_update_siae.html, itou/templates/apply/includes/state_badge.html, itou/templates/apply/process_base.html, itou/templates/approvals/includes/job_description_list.html, itou/utils/__snapshots__/tests.ambr, itou/utils/templatetags/job_applications.py, itou/utils/tests.py, itou/www/apply/tests/tests_templates.py
Pour faciliter la relecture et la résolution de conflit git.
En bonus: si un nouvel état est ajouté, un joli `KeyError` fera penser à définir la couleur souhaitée
=> Etat des candidatures: calcul de la couleur du badge en python

itou/www/apply/forms.py
Dans les graphes tels que https://itou.sentry.io/performance/les-emplois-prod:75da9b3960494cc782fb10beda5a1576/?project=6164438&query=http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=14d&transaction=%2Fapply%2Fprescriber%2Flist&unselectedSeries=p100%28%29
on verra plus simplement où se situent les opérations lentes.
=> Add sentry trace on slow form to ease performance improvements

itou/templates/utils/widgets/duet_date_picker_widget.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
Ce n'est pas un élément "vide"/void et peut donc pas être auto-fermant.
=> widget: correction de l'HTML du widget duet-date-picker

itou/templates/dashboard/api_token.html
Suppression d'un `</div>` sauvage.
Pour avoir un joli document HTML.
=> Création d'un token d'API: correction du HTML

itou/templates/apply/includes/list_card_body_siae.html, itou/www/apply/tests/tests_list.py, itou/www/apply/views/list_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/2-4-Refonte-carte-candidature-employeur-En-tant-que-SIAE-je-veux-visualiser-les-crit-res-d-ligi-2fad987c88574e848aec0d44a4ef7d28?pvs=4
Faciliter les gestions et améliorer le délai de traitement des candidatures
=> Affichage des critères administratifs sur la carte candidature 

itou/conftest.py, itou/www/search/tests.py, itou/www/search/views.py
Cela permet de détecter dès les tests qu'une vue devrait surcharger le contexte `matomo_custom_url`.
Ca fonctionne mais ça fait peut-être beaucoup de magie noire non documentée et lente pour une petite chose.
```
FAILED itou/www/search/tests.py::SearchSiaeTest::test_distance - AssertionError: template=search/siaes_search_results.html uses a variable title; please provide a `matomo_custom_title` in the context !
FAILED itou/www/search/tests.py::SearchSiaeTest::test_district - AssertionError: template=search/siaes_search_results.html uses a variable title; please provide a `matomo_custom_title` in the context !
FAILED itou/www/search/tests.py::JobDescriptionSearchViewTest::test_district - AssertionError: template=search/siaes_search_results.html uses a variable title; please provide a …
```
=> Détecter automatiquement les blocs "title" variables (+ correction)

itou/templates/approvals/list.html, itou/templates/approvals/printable_approval.html
Les éléments button n'ont pas de raison d'avoir des href.
Pour le toggle: cf https://getbootstrap.com/docs/4.6/components/collapse/#example
=> Suppression des href sur les boutons HTML

itou/templates/apply/includes/job_application_sender_info.html, itou/templates/apply/includes/job_seeker_info.html, itou/templates/prescribers/card.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/templates/siaes/includes/_siae_details.html, itou/www/apply/tests/tests_process.py
Les attributs href ne sont pas censés contenir d'espace.
On le fait déjà ici: https://github.com/betagouv/itou/blob/master/itou/templates/siaes/edit_siae_preview.html#L79
=> HTML:  Correction des href de téléphone

pytest.ini
```
.venv/lib/python3.11/site-packages/django/test/utils.py:398
/home/runner/work/itou/itou/.venv/lib/python3.11/site-packages/django/test/utils.py:398: PytestCollectionWarning: cannot collect test class 'TestContextDecorator' because it has a __init__ constructor (from: itou/utils/test.py)
class TestContextDecorator:
```
=> Ignorer les utilitaires de test avec pytest

itou/conftest.py, itou/utils/test.py, itou/www/apply/tests/__snapshots__/tests_list.ambr, itou/www/apply/tests/tests_list.py
Les snapshots (syrupy) permettent de capture plus facilement la représentation HTML des éléments, et de façon plus exacte. Ils sont également plus faciles à mettre à jour.
=> Retrait de l’auxiliaire `format_html`

itou/allauth_adapters/peamu/tests.py, itou/openid_connect/inclusion_connect/tests.py, itou/settings_viewer/tests.py, itou/www/apply/tests/test_edit.py, itou/www/apply/tests/tests_geiq.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/tests/test_prolongation.py, itou/www/dashboard/tests.py, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/tests/test_list.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/login/tests.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siaes_views/tests/tests_views.py, itou/www/signup/tests/test_job_seeker.py, itou/www/signup/tests/test_siae.py
`assertContains` et `assertNotContains` vérifient le code de retour de la réponse.
=> Retrait des assertions dupliquées response.status_code == 200

itou/templates/inclusion_connect/includes/description.html
Car l'HTML valide, c'est mieux.
=> Correction d'une typo dans un tag <img>

pyproject.toml, requirements/dev.in, requirements/dev.txt
On ne gère plus de fichiers SQL.
Cela fait moins de dépendances et de règles à maintenir.
=> Retirer sqlfluff du projet

config/settings/base.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-ation-des-premi-res-listes-de-diffusion-Mailjet-aliment-es-automatiquement-avec-les-nouveaux-util-63bdf909270b480a9ab9b17db2c4dfca?d=82e355c6c3d941668379d0801ed0b2a3**
Avec un changement prochain, le compte principal de MailJet sera disponible pour l’application. Les secrets existants ont été renommés avec le suffixe `_APP` pour bien distinguer quel compte est utilisé.
=> Utilisation de API_MAILJET_{KEY,SECRET}_APP

.github/dependabot.yml
Le projet a environ 160 dépendances. À raison de 10 par semaines, il faut environ 4 mois pour faire le tour. En 4 mois, de nombreux changements peuvent arriver sur un projet. Essayons d’être plus assidus dans les mises à jour.
=> Augmenter le nombre de dépendances mises à jour chaque semaine

clevercloud/cron.json, scripts/expire-elastic-indices
**Carte Notion : https://www.notion.so/plateforme-inclusion/Retirer-les-logs-de-plus-de-12-mois-de-c1-elk-acc5250b39124afa88a3539f97b3615b**
Ils contiennent des données personnelles, et ont peu de chances d’être consultés au delà d’une année.
=> Expiration des indexs ElasticSearch après un an

itou/templates/layout/base.html, itou/utils/__snapshots__/tests.ambr, itou/utils/context_processors.py, itou/utils/test.py, itou/utils/tests.py
Pas de carte Notion, toujorus dans le cadre de l'amélioration de Matomo.
Matomo propose une fonctionnalité de "Site Search" qui permet de tracer les utilisations des recherches intra-site.
Nous en avons une évidente avec notre recherche par villes. Cela permettra de débloquer d'autres analyses intéressantes.
On autorise un nouveau query param dans le context processor de Matomo.
=> Permettre le Site Search de Matomo par les villes

itou/templates/stats/stats.html, itou/utils/apis/metabase.py, itou/www/stats/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Mettre-embed-KPI-Utilisation-bas-de-page-des-Tb-priv-s-e911710c612c4ce9ac8ac8bed15666f2**
Cet encart ("embed") est affiché en permanence et s'ajoute au popup Tally déjà existant.
Pour rester iso avec le site statique Pilotage qui le fait déjà pour les TB publics, par exemple https://pilotage.inclusion.beta.gouv.fr/tableaux-de-bord/auto-prescription/
=> Stats : Ajout d'encarts Tally pour alimenter les KPI en bas des pages

itou/templates/siaes/card.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Fiche-structure-modifier-le-badge-de-type-de-structure-et-le-placer-sous-le-H1-53d3e0af66bc48eab72d7015009731fe?pvs=4
Modifications à faire en vue de j’ajout futur de l’info PHC et Convergence
=> Modification UI/UX de la zone titre de la fiche de structure

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Empêcher les utilisateurs de faire des choses qu'ils ne sont pas censés pouvoir faire
=> Candidature: empêcher les orienteurs de mettre à jour les données du candidat

clevercloud/cron.json, config/settings/base.py, config/settings/dev.py, itou/users/factories.py, itou/users/management/commands/new_users_to_mailjet.py, itou/users/tests/test_management_commands.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-ation-des-premi-res-listes-de-diffusion-Mailjet-aliment-es-automatiquement-avec-les-nouveaux-util-63bdf909270b480a9ab9b17db2c4dfca**
Ces listes seront utilisées à des fins de formation des nouveaux utilisateurs.
MailJet enregistre les désinscriptions. Renvoyer un utilisateur désinscrit ne mets pas à jour ses préférences concernant la réception des courriels de la campagne (`addnoforce` est utilisé pour cette raison).
Au lieu d’essayer de s’inscrire dans chaque parcours utilisateurs (comme le demande le ticket), itou identifie tous les utilisateurs qui devraient recevoir les communications et les envoie à MailJet. MailJet s’occupe de la déduplication et du suivi du consentement.
=> Alimenter les listes de diffusion avec les nouveaux utilisateurs

config/settings/base.py
Without the principal, the app token is used.
=> Fix typo in API_MAILJET_{KEY,SECRET}_PRINCIPAL

itou/templates/account/activate_inclusion_connect_account.html, itou/templates/account/login_generic.html, itou/templates/account/login_job_seeker.html, itou/templates/search/includes/prescribers_search_filters.html
=> Retirer form_group_class="form-group" des bootstrap_field

itou/prescribers/management/commands/merge_organizations.py, itou/prescribers/tests.py
Suivre le comportement des autres commandes.
=> Utilisation de --wet-run pour merge_organizations

itou/prescribers/management/commands/merge_organizations.py, itou/prescribers/tests.py
Pour éviter des suppressions de diagnostics non-souhaités
Et je rajoute un check pour limiter les chances qu'on oublie à nouveau.
=> Ajout des diagnostics GEIQ dans le script merge_organizations

itou/www/apply/forms.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/En-tant-que-prescripteur-je-veux-tre-clairement-inform-de-qui-re-oit-mon-message-afin-de-ne-pas-g--da123f410c2b45ffa95132e28148e4ef?pvs=4
Pour éviter les "frictions"
=> Clarification des destinataires du message rédigé par un prescripteur

itou/metabase/tables/organizations.py
**Fil slack : https://itou-inclusion.slack.com/archives/C04SAGUGJFJ/p1682669892156689**
Historiquement on applique 5 exceptions dans le nommage de `organisations.type`. Ces exceptions ne sont pas appliquées partout du coup causent des céphalées inutiles à Laurine.
On vire ces exceptions.
Non car trivial. J'attends juste que les tests passent.
=> Metabase : Simplification de la colonne organisations.type

itou/job_applications/tests/tests.py, itou/templates/approvals/email/deliver_body.txt, itou/templates/approvals/includes/status.html, itou/templates/approvals/printable_approval.html, itou/www/approvals_views/tests/test_display.py
[Carte Notion](https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-je-suis-inform-e-du-nombre-de-jours-restants-sur-le-PASS-IAE-depuis-l-attestation-e-376b318fd063427da458524743052c01)
La date de fin étant fluctuante, il vaut mieux envoyer le nombre de jours restant dans la version imprimable et dans l'e-mail envoyé à l'acceptation d'une candidature.
Mise à jour de l'e-mail et de l'attestation.
=> En tant que SIAE je suis informée du nombre de jours restants sur le PASS IAE depuis l’attestation en ligne et via la notification email

itou/employee_record/common_management.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/employee_record/models.py, itou/employee_record/tests/__snapshots__/tests_management_commands.ambr, itou/employee_record/tests/__snapshots__/tests_update_management_command.ambr, itou/employee_record/tests/common.py, itou/employee_record/tests/tests_management_commands.py, itou/employee_record/tests/tests_notifications.py, itou/employee_record/tests/tests_serializers.py, itou/employee_record/tests/tests_update_management_command.py
Le but premier était de ne plus générer d'erreur dans sentry lors de l'utilisation de `--preflight`, et ça a dérapé :grin:.
=> Fiches salariés : Plus d'erreur lors d'un `--preflight`, un peu de nettoyage, et tests plus complets

itou/utils/perms/middleware.py, itou/utils/perms/tests.py
Depuis que la fonctionnalité qui force inclusion connect est passée, il est impossible de libérer un compte non migré (le post vers hijack:release est redirigé vers la page d'activation)
=> Permettre de libérer des détournement d'identité de compte non migrés à Inclusion Connect

scripts/expire-elastic-indices
Autrement, les secrets `ELASTICSEARCH_*` ne sont pas disponibles.
=> Charger les secrets depuis expire-elastic-indices

itou/templates/search/siaes_search_results.html, itou/www/search/tests.py
Voir tout de suite lorsqu'il y a 0 résultat et simplifier.
Avant:
Après:
=> Mise à jour des labels des onglets dans les résultats de recherche

config/sentry.py, config/settings/base.py, scripts/expire-elastic-indices
Envoyer les évènements du script à Sentry.
=> Initialiser le SDK Sentry pour expire-elastic-indices

itou/static/js/utils.js, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/create_or_update_job_seeker/step_base.html
La fonctionnalité n’apporte pas un vrai gain UX, les attributs `required` permettent au navigateur d’empêcher l’envoi.
Correction d’un bug UX lors de la sélection de la ville dans l’auto-complete. La sélection d’une valeur dans le champ ville ne débloque pas le bouton, il faut également déclencher l’évènement `blur` ou un autre changement.
=> Retrait de JS pour désactiver les boutons de formulaires

scripts/imports-asp.sh
Petit oubli dans 6f610d0699cdaf4f2cfb15f18
=> scripts: lancement d'import_ea_eatt par le script imports-asp

itou/siaes/management/commands/_import_siae/convention.py
**Fil slack : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1683554701418109**
L'import plante sur une nouvelle erreur (qui vient d'un oubli dans le code de ma PR 2445 du 24 avril, mea culpa) avec les données de cette semaine du 8 mai, et en fait cette erreur s'était aussi produite la semaine dernière le 4 mai mais n'avait pas été remontée par Supportix (ou alors j'ai loupé, pas taper). Le 25 avril l'erreur ne s'est pas produite.
Récapitulatif des évènements :
1) Le 24 avril on a brutalement repris le déconventionnement des SIAE mis en pause depuis le début d'année car on est enfin passé en dessous du seuil de 200 déconventionnements. On a donc déconventionné ce jour là 199 SIAE.
2) Le 25 avril retour en arrière sur ordre express de l'ASP, on doit étendre l'immunité à fin mai …
=> Import SIAE : Résolution d'un souci technique mineur

itou/siaes/management/commands/_import_siae/utils.py
**Carte Notion : ** https://www.notion.so/BUG-disparition-d-antennes-eb1a9edb0f584862a30f8a1b746bcd58
Ce n'est pas pratique pour les utilisateurs
=> import_geiq/ea_eatt: empêcher la suppression de SIAE créées par des utilisateurs

itou/templates/apply/submit/application/eligibility.html, itou/templates/apply/submit_base_two_columns.html, itou/templates/signup/siae_select.html, itou/www/apply/views/submit_views.py, itou/www/signup/tests/test_siae.py, itou/www/signup/views.py
1. [En tant que prescripteur habilité, je veux accéder au diagnostic socio-pro de référence depuis la page dédiée à la situation administrative du candidat](https://www.notion.so/plateforme-inclusion/En-tant-que-prescripteur-habilit-je-veux-acc-der-au-diagnostic-socio-pro-de-r-f-rence-depuis-la-pa-d0722f1eaf3c40c1b87398fc1f44afb3)
2. [Bug d'affichage lorsque je cherche a postuler pour un candidat qui est reconnu dans le système](https://www.notion.so/plateforme-inclusion/BUG-D-AFFICHAGE-Bug-lorsque-je-cherche-a-postuler-pour-un-candidat-qui-est-reconnu-dans-le-syst-me-61e34a334f464688a3b3b90eabb057b1?pvs=4)
3. [Ajouter “Extranet EA 2” dans une bannière d’info présente lors de l’inscription](https://www.notion.so/plateforme-inclusion/Ajouter-Extranet-EA-2-dans-une-banni-r …
=> Améliorations UI/UX et correction de bogue

itou/approvals/factories.py, itou/approvals/models.py, itou/approvals/tests/tests.py, itou/templates/apply/includes/eligibility_diagnosis.html, itou/templates/approvals/detail.html, itou/templates/approvals/includes/prolongations_list.html, itou/templates/approvals/includes/status.html, itou/www/apply/tests/tests_process.py, itou/www/approvals_views/tests/__snapshots__/test_detail.ambr, itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/views.py, itou/www/dashboard/tests.py
[Carte Notion](https://www.notion.so/plateforme-inclusion/Rendre-l-affichage-des-infos-du-PASS-en-cours-claires-avant-que-l-employeur-valide-l-embauche-50d114b4a4a2450f8d431d9c518996e4)
Il est difficile de comprendre qu'un PASS IAE peut finir à une autre date que la date de fin.
Mise à jour de l'affichage de la date de fin prévisionnelle des PASS IAE.
```
from datetime import date
from dateutil.relativedelta import relativedelta
from itou.siaes.models import Siae 
from itou.approvals.models import Suspension, Prolongation, Approval
approval = Approval.objects.get(pk=1)
siae = Siae.objects.get(pk=3850)
Suspension.objects.create(start_at=date(2022,12,3), end_at=date(2022,12,31), siae=None, approval=approval)
Suspension.objects.create(start_at=date(2023,1,3), end_at=date(2023,1,10), …
```
=> Rendre l’affichage des infos du PASS en cours plus clair avant que l’employeur valide l’embauche

itou/metabase/db.py
Some airflow views (e.g. stg_structures) are built directly on top of C1 tables built by populate_metabase_emplois.py (e.g. structures). When the C1 table is being rebuilt (e.g. structures) the old version (e.g. z_old_structures) cannot and should not be deleted because a view (e.g. stg_structures) still depends on it. It will be deleted the next run, no biggie.
**Fil slack : https://itou-inclusion.slack.com/archives/C050D9JNJ9Z/p1683837006366749**
La MAJ C1 quotidienne casse actuellement quand elle reconstruit la table `structures` :
```
psycopg2.errors.DependentObjectsStillExist: cannot drop table z_old_structures because other objects depend on it
DETAIL:  view stg_structures depends on table z_old_structures
```
C'est nouveau parce qu'une PR récente a introduit pour la première fois …
=> Airflow : Résolution d'un souci technique avec les vues

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py
Pour la future campagne, les DDETS auront des périodes différentes en fonction de leur participation à la dernière campagne de janvier à septembre.
=> Contrôle a posteriori: possibilité de créer des campagnes pour certaines DDETS uniquement

itou/templates/approvals/includes/status.html, itou/www/approvals_views/tests/test_detail.py
[Carte Notion](https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-je-veux-voir-la-date-de-fin-pr-visionnelle-du-PASS-5a09e199a1004123892f570696fe08da)
Les employeurs se plaignent de la disparition de cette information.
=> Affichage de la date de fin estimée du PASS IAE aux prescripteurs et employeurs

itou/common_apps/nir/forms.py, itou/templates/apply/submit/create_or_update_job_seeker/step_1.html, itou/templates/apply/submit/create_or_update_job_seeker/step_base.html, itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, itou/www/apply/forms.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
**Carte Notion : ** En préambule du pack "Déclaration d'embauche" (cf maquettes de https://www.notion.so/plateforme-inclusion/1-8-D-claration-d-embauche-rapide-Transformer-le-parcours-actuel-D-clarer-une-embauche-par-En-65bddac801ed4e2ca502eb981113ef72 et suivantes)
Pour pouvoir utiliser l'écran final comme récapitulatif des informations du candidat.
=> Candidature: ajout des informations de NIR dans les parcours de création/mise à jour des profils de demandeur d'emploi

clevercloud/crons/populate_metabase_emplois.sh, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/test_populate_metabase_emplois.py, itou/metabase/tables/users.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-une-table-utilisateurs-avec-les-emails-pro-b0e49c5bd5544087a7e92300b8aa4840**
Pour aider les bizdev C2 à identifer l'email des utilisateurs pros (employeur, prescripteur, institution) à l'aide de leur ID C1 déjà disponibles à plusieurs endroits notamment dans le tracking Matomo (quel utilisateur a consulté quel TB) afin de faire des contacts et/ou des mailings ciblés.
- attention on met seulement les utilisateurs pros, pas les candidats
- car on part toujours du principe que Metabase peut être hacké et qu'il ne faut pas fuiter des données sensibles
- on ne met que les utilisateurs actifs
En l'absence de Victor, c'est pour Supportix (donc Céline pour cette fois).
=> Metabase : ajout d'une table utilisateurs avec *uniquement* les utilisateurs pros et leur email, pas les candidats

itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html
L'icone `ri-line-chart-line` est déjà utilisée pour les tableaux de bord
=> Controle a posteriori: mise à jour des icones sur le tableau de bord

itou/employee_record/admin.py, itou/employee_record/tests/test_admin.py, itou/users/admin.py
[Carte Notion](https://www.notion.so/plateforme-inclusion/6d2f772966114bc98fefc6ef17df79c0?v=99352c5142224ce8995dcc6ea3a78337&p=1130a80b9d7b4846853a31350e32570e&pm=c)
Le support est bloqué car il a besoin de créer des profils candidat sans pouvoir le faire.
=> Django admin : permettre d'ajouter un profil candidat

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/openid_connect/models.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Faciliter-la-connexion-des-employeurs-prescripteurs-qui-se-trompent-de-formulaire-de-connexion-8b513092ee6a4709be1835e62dbdc64a
Pour limiter le grand nombre de remontées au support d'utilisateurs qui vont au mauvais endroit
=> inclusion_connect: Autoriser les prescripteurs de se connecter depuis la page des employeurs (et reciproquement)

itou/prescribers/management/commands/merge_organizations.py
Le script est cassé à cause d'un paramètre qui est considéré comme `positional` alors que c'est un `keyword only`.
=> Correction du script merge-organizations

itou/employee_record/management/commands/archive_employee_records.py, itou/employee_record/models.py, itou/employee_record/tests/__snapshots__/test_archive_employee_records.ambr, itou/employee_record/tests/test_archive_employee_records.py
Pour ne pas bloquer l'archivage de toutes les FS si 1 seule échoue, et vu que le nombre de FS à archiver n'est pas énorme (74 en attente entre le 05/05 et le 10/05 donc ~15 par jour) la suppression du `bulk_update()` ne devrais pas être trop visible au niveau des performances.
Le cas rencontré est un PASS IAE avec 2 candidatures et 2 FS (1 `Intégrée` et 1 `Désactivée`), les 2 FS sont donc archivable mais la contrainte `unique_asp_id_approval_number` nous bloque car on se retrouve avec 2 FS ayant le même couple `asp_id`/`approval_number` et dont le statut n'est pas `Désactivée`.
Le changement ne corrige pas ce problème (devrais arriver dans un second temps) mais permet déjà de ne plus tout bloquer.
=> Fiches salariés : Ne plus bloquer l'archivage quand seulement une échoue

itou/templates/signup/facilitator_search.html
[Carte Notion](https://www.notion.so/plateforme-inclusion/061d460f790a4d12b02ffb1f58fa723e?v=5bba2284c4ef442f98d35080ff535d6c&p=c36251e581a74c2683181105d33749b8&pm=c)
Les employeurs se trompent en se créant un compte facilitateur à tort.
=> Ajout d'un texte explicatif avant le formulaire d'inscription des facilitateurs

itou/scripts/sql/cta_export.sql
[Carte Notion](https://www.notion.so/plateforme-inclusion/061d460f790a4d12b02ffb1f58fa723e?v=5bba2284c4ef442f98d35080ff535d6c&p=68039c449cc54f0997ec049a0f76e9a9&pm=c)
Les membres inactifs (c'est-à-dire les membres dont la `membership` est inactive) figuraient dans l'export.
=> Exclusion des membres inactifs des exports CTA

itou/templates/django/forms/widgets/password.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Personnalisation-de-certains-bootstrap_field-17bf22aeb6ab4d90893c1a8da5e07f3f?pvs=4
Amélioration de l’ui et de l'inclusion automatique de l'input type="password"
En surchargant le templates dans le widgets du formulaire
Par contre, c'est un échec. Mis à part le password, je n'ai pas réussi à surcharger les autres inputs.
Explication >
Après quelques recherches et tests avec Romain. On peut conclure que certaines modifications pourront être faites directement avec de la surcharge de template dans les widgets. D'autres nécessiteraient de surcharger les renderer.py des django form et/ou de bootstrap form. Ces modifications impliquent une certaine charge de travail. Nous préférons donc attendre le passage à Bootstrap form 5 pour …
=> Personnalisation de widgets de form field

itou/www/signup/tests/test_siae.py
CI en échec car il y a parfois 6 "EI", je suspecte que l'on retrouve parfois cette suite dans un nom de structure. Vu qu'on se fiche de vérifier précisément le type autant utilisé ce qu'on sais être unique et fixe.
=> Tentative de correction d'un test échouant aléatoirement

itou/templates/bootstrap4/messages.html, itou/templates/layout/base.html, itou/templates/utils/toasts.html, itou/utils/templatetags/theme_inclusion.py
Afin de pouvoir afficher un toast après une action serveur, demandé dans un ticket par les UX pour remplacer une page de résumé en fin de parcours.
Cas d'utilisation : #2528
=> Utilisation des `messages` de Django afin d'afficher des toasts Bootstrap

itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/tests/test_sanitize_employee_records.py
En regardant le code je me suis rendu compte qu'on pourrais tout simplement supprimer la désactivation pour les `NEW` et `REJECTED` car ces statut vont faire passer l'utilisateur dans le tunnel de création et donc un `JobSeekerProfile()` sera créé au passage.
https://github.com/betagouv/itou/blob/50f1a0322f0de11187692dc167448ab7985226f7/itou/www/employee_record_views/views.py#L207
Cas pratique : Une SIAE change de SIRET, elle doit renvoyer une FS pour tout les salariés encore présent dans la structure, certain peuvent avoir été embauché avant l'interopérabilité, on doit donc créer une FS manuellement, ce salarié n'ayant jamais eu de FS auparavant il n'a pas de `JobSeekerProfile()`, la FS se retrouve `DISABLED` au prochain passage de `sanitize_employee_records`, l'employeur ne comprend pas …
=> Fiches salarié : Suppression de la désactivation automatique des fiches avec un `JobSeekerProfile()` incorrect

itou/templates/employee_record/includes/create_step_5.html, itou/utils/perms/employee_record.py, itou/utils/perms/tests.py, itou/www/employee_record_views/tests/__snapshots__/test_create.ambr, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Am-liorer-l-UI-de-l-tape-de-confirmation-de-cr-ation-de-la-fiche-salari-0766ffb579c649a69b81619274e1dad6**
- Trop de texte présent sur la page
- On ne voit pas facilement où est le lien de retour 
- le récap des infos du profil salarié ne sont plus nécessaires une fois la fiche envoyée
Voir #2529 pour la mécanique des toasts
Commits : 
1. On ne gère plus le réaffichage de la FS en dernière étape
2. On n'autorise plus les FS prête à être envoyées d'être éditées dans le tunnel
=> Améliorer l’UI de l’étape de confirmation de création de la fiche salarié

itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/views.py
Éviter qu'un utilisateur puisse forger des requêtes pour contourner les vérifications des templates.
=> Controle a posteriori: vérification des conditions dans les vues en plus des templates

itou/employee_record/admin.py, itou/employee_record/enums.py, itou/employee_record/factories.py, itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/migrations/0005_stop_using_notification_type_field.py, itou/employee_record/models.py, itou/employee_record/tests/test_admin.py, itou/employee_record/tests/tests_management_commands.py
Ce champs est globalement inutile donc autant s'en débarrasser.
Dans cette première PR on ne référence ni n'utilise plus le champ, il sera supprimer définitivement dans un second temps.
=> Fiches Salarié : Suppression du champs `notification_type` 1/2

clevercloud/archive_employee_records.sh, clevercloud/crons/populate_metabase_emplois.sh, clevercloud/crons/populate_metabase_matomo.sh, clevercloud/download_employee_records.sh, clevercloud/expire-elastic-indices.sh, clevercloud/run_management_command.sh, clevercloud/send_approvals_to_pe.sh, clevercloud/status-probes.sh, clevercloud/upload_employee_records.sh
`expire-elastic-indices` est lancé 2 fois, sur `c1-prod` et `c1-worker` a priori.
=> crons : Uniformisation des wrappers shell afin qu'ils ne puissent pas être lancé plusieurs fois en parallèle

itou/www/approvals_views/views.py
Suite de https://github.com/betagouv/itou/pull/2535 qui a causé https://itou.sentry.io/issues/4207043425/?project=6164438
La vue `edit_job_seeker_info` a pour le moment besoin d'une candidature pour fonctionner donc on vérifie son existence avant d'y donner accès.
En cible bientôt, `edit_job_seeker_info` utiliser la pk du job seeker ce qui résoudra ce soucis.
=> Gestion des salariés et PASS IAE: vérifier la présence d'une candidature pour éditer les infos personnelles d'un candidat

itou/siae_evaluations/tests/tests_models.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
Documents refused after the reviewed_at (second phase) have their
criteria state at `REFUSED_2`, not `REFUSED`.
=> Increase realisms of some evaluation campaign tests

itou/templates/apply/includes/job_seeker_info.html, itou/templates/dashboard/edit_job_seeker_info.html, itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/views.py, itou/www/dashboard/tests.py, itou/www/dashboard/urls.py, itou/www/dashboard/views.py
Cela facilitera la réutilisation du template `apply/includes/job_seeker_info.html` pour le parcours de "Déclaration d'embauche" où l'on ne dispose pas de candidature (créée uniquement à la fin du parcours)
=> Modifier les informations personnelles: utilisation de la clef primaire du candidat au lieu de celle de la candidature

itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/views.py
Suite de https://github.com/betagouv/itou/pull/2560
Quand il n'y a pas de candidature liée, il ne faut pas essayer d'autoriser l'édition.
Cf https://itou.sentry.io/issues/4207043425/activity/?project=6164438
=> Gestion des salariés et PASS IAE: correction d'un crash pour les Pass sans candidature

itou/www/signup/tests/test_prescriber.py, itou/www/signup/tests/test_siae.py, itou/www/signup/views.py
Trou depuis qu'on permet aux prescripteurs de se connecter avec Inclusion Connect depuis la page des employeurs et inversement
=> N'autoriser que des prescripteurs à rejoindre des organisations

config/settings/base.py, itou/prescribers/tests.py, itou/status/probes.py, itou/utils/apis/api_entreprise.py, itou/utils/apis/test_entreprise_api.py, itou/utils/mocks/pole_emploi.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/tests/test_siae.py
Pour ne pas laisser croire qu'on utilise une autre API que celle de l'INSEE pour la recherche par SIRET.
=> Suppression des mentions de l'API Entreprise de `api.gouv.fr`

itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/process_details_prescriber.html, itou/templates/apply/process_details_siae.html, itou/templates/approvals/detail.html, itou/www/approvals_views/tests/test_detail.py, itou/www/approvals_views/views.py
Pour faciliter son utilisation dans le nouveau parcours de "Déclaration d'embauche".
En bonus, on aura maintenant plus d'informations affichées dans la page de détail des Pass sans candidature.
=> templates: rendre job_seeker_info.html utilisable sans candidature

itou/templates/approvals/includes/status.html, itou/www/dashboard/tests.py
https://www.notion.so/plateforme-inclusion/BUG-La-date-de-fin-pr-visionnelle-du-PASS-IAE-n-est-pas-visible-dans-l-encart-du-PASS-cot-CANDIDA-e651b24e73004b73b897e7f4a9d67568
Le template d'affichage (en mode card) du PASS IAE n'affiche pas la date de fin prévisionnelle du contrat pour les candidats
=> boost: La date de fin prévisionnelle du PASS IAE n’est pas visible pour le CANDIDAT

itou/employee_record/tests/test_admin.py, itou/employee_record/tests/test_sanitize_employee_records.py, itou/employee_record/tests/tests_models.py, itou/job_applications/factories.py, itou/job_applications/tests/tests.py, itou/users/factories.py, itou/users/models.py, itou/users/tests/test_models.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py, itou/www/employee_record_views/tests/test_create.py, itou/www/signup/tests/test_job_seeker.py
Afin d'éviter de devoir vérifier si le profil existe partout, on souhaite généraliser son existence et cela commence par systématiquement en créer un.
Plutôt que d'aller le créer partout où on crée des `User` avec un `UserKind.JOB_SEEKER` (`CreateJobSeekerStepEndForSenderView`, 
`JobSeekerSignupForm`, `france_connect_callback`, l'admin et peut-être d'autres), il a semblé plus simple de systématiquement faire le `create` dans le  `User.save()`.
Cela a engendré quelques complications au niveau des factories (avec la `JobSeekerProfileFactory` qui crée un `User` comme dépendance, créant au passage un `JobSeekerProfile`, que la `JobSeekerProfileFactory` ne pourra plus créer mais qu'elle doit mettre à jour).
Comme un certain nombre de nos tests nécessitaient l'absence de `JobSeekerProfile`, je …
=> Création automatique d'un profil de demandeur d'emploi à la création d'un demandeur d'emploi

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Publication-TB-300-suivi-du-contr-le-a-posteriori-166d4e02b9ed454e9ff4a84125b32d3c?pvs=4
Ajout d'un ID de dashboard metabase à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
=> Ajout de l'ID 300 de dashboard metabase

itou/templates/siae_evaluations/siae_job_applications_list.html, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/views.py
Moins de requête, plus simple.
=> Controle a posteriori: simplification de code

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
=> Candidature: nettoyage du NIR en session

itou/job_applications/models.py, itou/job_applications/tests/tests.py
https://www.notion.so/plateforme-inclusion/Correction-du-type-d-employeur-dans-les-auto-prescriptions-boost-8c74736161a4417abd4bde54af91b9d6
N'afficher que la SIAE est ... une SIAE que lorsque c'est le cas dans le détail de la candidature
(les GEIQ, EA, EATT et OPCS ne sont pas des SIAE)
=> BOOST: ne pas afficher les GEIQ, EA, EATT, OPCS comme étant des SIAE

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/__snapshots__/tests_models.ambr, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_siae_adversarial_stage_body.txt
Si la DDETS a effectué toutes les revues mais a oublié de soumettre le résultat, la validation de leur contrôle est automatique à la fin de la phase 2 bis. Cela permet de s'assurer que toutes les SIAEs passent en phase contradictoire et qu'aucune ne reste en phase amiable.
=> Controle a posteriori: validation automatique des revues complètes de la DDETS lors du passage en phase contradictoire

itou/templates/siaes/includes/_job_description_details.html, itou/www/siaes_views/tests/tests_job_description_views.py
https://www.notion.so/plateforme-inclusion/Fiche-de-poste-r-gles-d-affichage-lorsque-la-description-ou-certains-champs-sont-vides-boost-fc4c7bd2f7d647d995c415baa3719bd6
Si aucune description n'est saisie dans la fiche de poste, seul les titres de paragraphes sont affichés (moche).
=> BOOST : ajout de champ par défaut pour l'affichage si les descriptions de la fiche de poste sont absentes

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py
=> Inclusion connect: Retrait d’une instruction return inutilisée

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/signup/tests/test_prescriber.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Inclusion-Connect-probl-me-avec-la-d-connexion-sur-la-refonte-Django-b6f9d0b71e1e4901aa840a4935c6ecbf?pvs=4
Keycloak autorise un post sur l'URL de logout depuis le backend, ce qui n'est pas autorisé par les specs OIDC.
En prévision du déploiement de Inclusion Connect en django, cette PR rend le code compatible avec les specs OIDC.
=> Modification de la déconnexion sur Inclusion Connect

itou/openid_connect/inclusion_connect/views.py
=> Inclusion connect: Retrait d’un assignement inutile

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/__snapshots__/test_emails.ambr, itou/siae_evaluations/tests/__snapshots__/tests_models.ambr, itou/siae_evaluations/tests/test_emails.py, itou/siae_evaluations/tests/tests_models.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
https://www.notion.so/plateforme-inclusion/1-2-Diff-rer-la-transmission-du-r-sultat-aux-SIAE-Stopper-la-transmission-du-r-sultat-du-contr-le--3d0ba94efb98496b8259c42414205062
https://www.notion.so/plateforme-inclusion/2-2-Diff-rer-la-transmission-du-r-sultat-aux-SIAE-Transmettre-les-r-sultats-apr-s-les-phases-bis-c00d6a8239064548a529b1cd73df4328
Maintenant qu'il y a des phases "strictes", on ne veut pas envoyer un mail à une SIAE et lui dire d'aller faire des modifs qu'elle ne pourra pas faire.
=> Contrôle a posteriori: différer la transmission du résultat par mail

itou/siae_evaluations/emails.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/__snapshots__/tests_models.ambr, itou/siae_evaluations/tests/test_emails.py, itou/siae_evaluations/tests/test_management_commands.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/email/to_institution_ratio_to_select_body.txt, itou/templates/siae_evaluations/email/to_institution_ratio_to_select_subject.txt, itou/templates/siae_evaluations/email/to_institution_selected_siae_body.txt, itou/templates/siae_evaluations/email/to_siae_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_forced_to_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_notify_before_adversarial_stage_body.txt, itou/templates/siae_evaluations/email/to_siae_notify_before_campaign_close_body.txt, itou/templates/siae_evaluations/email/to_siae_selected_body.txt, itou/utils/constants.py
**[Carte Notion](https://www.notion.so/plateforme-inclusion/URGENT-Retirer-les-dates-indiqu-es-dans-les-emails-du-contr-le-a-posteriori-02876e096ba04800becf08812634ff56?d=2ad2b4b8065d42fa9900690dca62290c)**
On a besoin d'éviter de faire apparaître en toutes lettres les dates finales de certaines échéances et laisser l'utilisateur calculer lui-même.
De plus d'autres wordings sont retirés ou modifiés, et on corrige une erreur concernant la documentation qui est mal redirigée pour les DDETS.
On introduit la notion de ITOU_DOCS_URL mais on ne la corrige pas partout; ce sera l'objet d'une autre PR.
=> [BOOST] Controle à posteriori: modifier le wording sur certains mails

itou/openid_connect/constants.py, itou/openid_connect/france_connect/tests.py, itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/tests/test_siae.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/BUG-Certains-de-nos-utilisateurs-ne-parviennent-pas-rejoindre-leur-organisation-lorsqu-ils-cr-ent-3bf1d9d4fa424087bd739c2638504403
Gros irritant pour le support et les utilisateurs.
En attente du déploiement d'Inclusion Connect en Django 
=> Autoriser les utilisateurs Inclusion Connect à valider leur email sur un autre navigateur

itou/www/signup/tests/test_siae.py, itou/www/signup/views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/BUG-lors-de-l-inscription-nous-n-affichons-plus-toutes-les-entreprises-disponibles-en-base-4c1ddfd6f5f24f6e97f434cb19f29e0b?pvs=4
Dans le cas où l'on a plusieurs SIAEs avec le même siret, on n'affichait qu'une seule (choisie aléatoirement par PSQL)
=> Correction du choix de SIAEs à l'inscription

itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html, itou/www/siae_evaluations_views/tests/tests_siaes_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/ECRAN-SIAE-Changer-le-statut-trait-par-justificatifs-t-l-vers-s-451d213377ec4a57ba2e01d74e5ecbbe?pvs=4
"traité" est très vague
=> Contrôle a posteriori: écran SIAE - renommage du statut "traité" en "justificatifs téléversés"

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/__snapshots__/tests_models.ambr, itou/siae_evaluations/tests/tests_models.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
Pour rester cohérent avec la phase 2
Et en bonus, cela permet de simplifier le code de calcul du `state` :tada:
=> Contrôle a posteriori: validation automatique des revues complètes de la DDETS lors de la clôture de la campagne

itou/employee_record/admin.py, itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/models.py, itou/employee_record/tests/test_admin.py, itou/employee_record/tests/test_sanitize_employee_records.py, itou/employee_record/tests/tests_models.py, itou/job_applications/factories.py, itou/users/factories.py, itou/users/tests/test_models.py, itou/www/apply/tests/tests_submit.py, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/views.py
Suite de la discussion entamée sur #tech-c1 .
Nous optons pour l'approche la plus simple pour l'instant.
=> Supprimer la possibilité d'un jobseeker_profile vide, même dans les tests.

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/www/apply/views/submit_views.py
Dans les deux cas, cela correspond à l'URL de la page visitée le rendant inutile (et complexifiant le code inutilement, surtout lorsque l'on souhaite réutiliser ce même template dans une autre URL - :wave: Déclaration d'embauche)
=> Parcours de candidature: suppression de l'action du formulaire

itou/approvals/admin_forms.py, itou/approvals/tests/__snapshots__/test_admin.ambr, itou/approvals/tests/test_admin.py
**[Carte Notion](https://www.notion.so/plateforme-inclusion/Prise-en-compte-et-mise-jour-des-objets-suspensions-et-prolongation-si-on-modifie-les-dates-du-PAS-ffce5eb31eef41918620190ae442d7a4?pvs=4)**
Pour rapidement aider le support.
Avec une petite modification de l'admin form.
=> PASS IAE : Mentionner dans l'admin de faire attention aux dates de Prolongation/Suspension

README.md, config/settings/dev.py, itou/api/README-FS-SSII.md, itou/openid_connect/france_connect/tests.py, itou/siae_evaluations/tests/__snapshots__/test_emails.ambr, itou/siae_evaluations/tests/__snapshots__/tests_models.ambr, itou/siae_evaluations/tests/test_management_commands.py, itou/utils/urls.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
`127.0.0.1` est tellement IPv4…
Une isntance locale d’inclusion connect requiert une liste de validation pour le schéma et les hôtes vers lesquels IC peut rediriger. Pour harmoniser, utilisons le nom le plus moderne pour la machine locale.
=> Préférer localhost au lieu de 127.0.0.1

itou/approvals/admin_forms.py
Quand la CRI sauve un formulaire, sachant que kleurs droits sont limités ils peuvent voir un crash.
En faisant pareil qu'ailleurs: on vérifie si le champ est présent.
=> approvals.admin_forms: Corriger une exception dueà certains droits manquants

itou/templates/dashboard/includes/stats.html, itou/users/models.py, itou/users/tests/test_models.py, itou/utils/apis/metabase.py, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Mettre-dispo-TB-Dihal-pour-les-DREET-DDETS-Logement-insertion-avec-une-vue-r-gionale-60760d61b8ef4614bb50c62bbb782769**
Pour que les DDETS LOG, et non plus seulement les DDETS IAE, aient accès à des stats pertinentes.
- Cablage d'un nouveau TB 310 pour que chaque DDETS LOG puisse voir les données de toute sa région et filtrer par département, et non pas juste consulter les données de seulement son département comme on aurait pu s'y attendre.
- Recablage du TB DIHAL vers le nouveau TB 310 pour rester bien DNRY et pouvoir jeter l'ancien TB 235 obsolète.
Vue d'une DDETS LOG :
Vue de la DIHAL :
=> DDETS Logement Insertion : Ajout de leurs premières stats

itou/metabase/tables/evaluated_siaes.py
Ajouté dans b9026508a599a7925c pour que le changement soit transparent pour le pilotage.
Mais en fait, ils ont de leur coté un code qui transforme l'état `NOTIFICATION_PENDING` dans l'état `REFUSED`...
Donc, on peut dropper cette rétro-compatibilité et une fois ce changement en prod et l'export metabase effectué, @laurinehu pourra supprimer leur code d'équivalence `NOTIFICATION_PENDING` :arrow_right:  `REFUSED`
=> Contrôle a posteriori: suppression d'une rétro-compatiblité inutile dans l'export metabase

itou/eligibility/admin.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=22538e95ff154ef0b4e8cfdb6b0e1c2e&pm=c
Les critères administratifs (GEIQ et IAE) sont fixés par décret, dans leur texte et attributs. 
Ils ne sont pas modifiables.
Les critères administratifs sont ajoutés / modifiés par fixtures à chaque décret.
=> BOOST : Les critères adminitratifs ne peuvent pas être modifiés dans l'admin

itou/approvals/management/commands/export_pe_api_rejections.py, itou/approvals/tests/test_management_commands.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=253a71ea895340f8b811794567b0831b&pm=c
Demande Pôle emploi
Ajout de la raison sociale et du type de SIAE dans le fichier de rejet PE
=> BOOST : modification du fichier des rejets, ajout de la raison sociale et du type de SIAE

itou/templates/apply/includes/job_application_prior_action.html
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=46402d04ea0043cb946f5e4117f939c3&pm=c
- mauvais alignement du texte
- suppression de l’icône
=> BOOST: format de la widget de suppression d'une action préalable

itou/templates/siaes/card.html, itou/templates/siaes/includes/_card_siae.html, itou/templates/siaes/job_description_card.html, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Plus aucune vue de `submit_views.py` (qui sont les vues utilisant/exigeant l'`apply_session`) n'utilise le `back_url` présent en session (depuis #2656, où `ApplicationJobsView` a arrêté de l'utiliser avec 271acef8ec9bb ).
Voici les URL de retour des différentes vues:
- start: pas de back_url (renvoit 403, 404 ou 302)
- pending_authorization_for_sender => "Revenir à la recherche" / `home:hp`
- check_nir_for_sender => "Retour" / `dashboard:index`
- search_by_email_for_sender => "Retour" / `apply:check_nir_for_sender`
- create_job_seeker_step_1_for_sender => "Retour" ou "Modifier l'email du candidat" / `apply:search_by_email_for_sender`
- create_job_seeker_step_2_for_sender => "Retour" / `apply:create_job_seeker_step_1_for_sender`
- create_job_seeker_step_2_for_sender => "Retour" / …
=> Parcours de candidature: suppression de la clef back_url de l'apply_session

itou/templates/search/siaes_search_results.html
https://www.notion.so/plateforme-inclusion/virer-le-tag-nouveau-du-filtre-PEC-boost-ccbb59a5ccc8486eb4eb180ce2c21c5d?pvs=4
C'est violet.
=> BOOST : retrait du badge "Nouveau" pour les contrats PEC dans le filtre de recherche

itou/templates/dashboard/dashboard.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=ffcd93fbd0914b5e884c69459902222e&pm=c
Plus nécessaire
=> BOOST : retrait d'un message du tableau de bord concernant les fiches salarié

itou/templates/apply/includes/geiq/continue_without_geiq_diagnosis_form.html, itou/templates/apply/process_geiq_eligibility.html, itou/www/apply/forms.py, itou/www/apply/urls.py, itou/www/apply/views/process_views.py
Je vais avoir besoin de réutiliser l'équivalent des vues `eligibility` et `geiq_eligibility` pour le parcours de déclaration d'embauche alors j'essaie de simplifier au maximum.
=> Parcours de candidature GEIQ: simplification/suppression de la vue remove continue_without_geiq_diagnosis

itou/users/factories.py, itou/users/models.py, itou/users/tests/test_models.py, pytest.ini
La façon dont la logique de `User.has_data_changed()` était implémentée pouvait retourner `True` alors que en pratique aucun champ n'a changé ou  même n'existe encore en mémoire ou en base de données.
Changer cela pour que cela corresponde plus à notre intuition et corrige du même coup la `JobSeekerProfileFactory`.
=> User.has_data_changed() : être plus clair sur les cas positifs

Makefile
Can directly list files with a glob, the order of expanded pathnames is
guaranteed by bash.
=> Remove useless ls -d | xargs from populate_db

itou/siae_evaluations/fixtures.py
L’utilisateur a changé pendant le développement, mais le commentaire n’a pas été mis à jour.
=> Correction d’un commentaire dans siae_evaluations.fixtures

itou/templates/layout/base.html
tarteaucitron charge piwik.js depuis MATOMO_BASE_URL. En développement, il déclenche des requêtes :
GET /dashboard/Nonepiwik.js
Évidemment, le résultat est une 404.
=> Ne pas initialiser Matomo pour tarteaucitron en dev

pytest.ini
The timeout is good to detect frozen tests.
But it was set to 15 seconds, which too often on my machine is too slow to run the migrations locally and all the tests fail.
So I usually edit locally to be able to run my tests, until of course with my last PR the change made it to master.
So there is my proposal to make it a bit longer so that people like me stop editing it; a longer timeout does not harm by the way, as the only thing we want is to protect us from infinite loops, which do not happen that often. It will not make the tests any longer usually.
Cf. ci-dessus. A force de l'éditer manuellement puis de finir par me planter (malgré relecture) il serait pas mal de juste l'augmenter, je pense. Sans impact particulier.
=> pytest: Monter le timeout à 30 secondes

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests/test_admin.py, itou/approvals/tests/tests.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/__snapshots__/test_prolongation.ambr, itou/www/approvals_views/tests/test_prolongation.py
Pas de carte notion
- suite à discussion concernant le suivi des bilans dans l'admin (n'ayant pas donné lieu à la création d'une carte)
- amélioration continue
- ajout de tests sur la partie saisie du prescripteur dans la partie bilan de prolongation
- ajout d'un filtre dans l'admin
- correction de : https://itou.sentry.io/share/issue/764b73a484f14b969636eef5fffd2b25/
=> BOOST : améliorations diverses concernant le bilan de prolongation

itou/siaes/admin.py
Évite les erreurs du support, qui casse l’import ASP.
=> Mettre SIAE.kind en lecture seule pour les changements

itou/templates/admin/users/change_form.html, itou/users/admin.py, itou/users/tests/test_admin_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/ADMIN-DJANGO-avoir-le-bouton-D-tourner-dans-la-page-de-d-tail-de-l-utilisateur-60de1ebec2de4cbf92814f2e73957c74?pvs=4
Pour éviter de devoir revenir sur la vue liste en filtrant sur son utilisateur pour pouvoir le détourner.
=> admin: ajout du bouton détourner sur la vue de détails d'un utilisateur

itou/static/js/admin.js, itou/templates/admin/base_site.html
Les SIRET, NIR et numéro de PASS IAE ont une signification particulière, et les espaces séparateurs devraient être ignorés. Le support passe pas mal de temps à les gérer manuellement.
=> Gérer les identifiants dans la recherche admin et les pages de changement

CHANGELOG.md, itou/api/applicants_api/views.py, itou/api/data_inclusion_api/views.py, itou/api/employee_record_api/viewsets.py, itou/api/siae_api/viewsets.py, itou/api/urls.py, itou/approvals/admin.py, itou/approvals/tests/tests.py, itou/templates/employee_record/list.html, itou/www/employee_record_views/tests/test_list.py
1. Uniformisation du nommage "fiches salarié"
2. Corrections de typo pour les pages API qui vont bientôt être utilisé pour les GEIQ
=> Correction de quelques typo

itou/www/approvals_views/tests/test_pe_approval.py
Avec beaucoup de malchance, on pouvait avoir `self.pe_approval.id` égal à `123` et obtenir une 200.
Le plus simple est donc de ne pas créer d'objet dans ce test.
=> Correction d'un test instable

itou/www/approvals_views/views.py, tests/www/approvals_views/test_list.py
https://itou.sentry.io/issues/4293217915/?project=6164438
J'ai laissé le N+1 sur les suspensions car il demanderait plus de modifications
=> Liste des Pass: amélioration de performances

itou/approvals/admin.py, itou/employee_record/management/commands/uniquify_employee_records.py, itou/employee_record/models.py, itou/job_applications/models.py, itou/utils/perms/employee_record.py, itou/www/employee_record_views/views.py, tests/approvals/__snapshots__/tests.ambr, tests/approvals/tests.py, tests/employee_record/test_models.py
Avoir de multiple FS avec le même couple `asp_id`/`approval_number` bloque leurs archivages car la contrainte d'unicité `unique_asp_id_approval_number` désigne seulement `DISABLED` comme exclusion.
Ajouter `ARCHIVED` comme statut exclus à la contrainte aurais été une alternative mais cela me semble plus pérenne d’arrêter de considérer `DISABLED` comme un statut à part, cela permet également d'aligner un peu plus la représentation de nos FS avec celle de l'ASP (ils n'ont pas d'état et seule 1 peux exister à tout moment), mais aussi de couper court à la technique de déclarer de nouvelle embauche (donc des `JobApplication`) afin de renvoyer de la donnée vers l'ASP.
Sachant que :
- Depuis quelque mois on ne propose pas la FS dans "Nouvelle" si une équivalente (même `asp_id`, …
=> Fiches Salarié : Dédoublonnage des `Status.DISABLED` 1/2

itou/www/dashboard/views.py, tests/www/dashboard/tests.py
Empêcher des utilisateurs d'écrire des choses fausses en session (au cas où on ne referait pas les vérifications dans une autre vue)
=> Vérification des permissions avant d'autoriser le changement de structure

itou/www/apply/views/process_views.py, tests/www/apply/test_geiq.py, tests/www/apply/test_process.py
Avec des requêtes manuelles un candidat pouvait se créer un diagnostic GEIQ
=> Parcours de candidature: vérification des permissions des utilisateurs

itou/job_applications/admin.py
Le compte engendre une requête SQL en doublon :
`SELECT COUNT(*) AS "__count" FROM "job_applications_jobapplication"`
Avec 1.5M d’entrée dans la table, éviter cette requête dupliqué a un impact sur les performances.
- avant ce commit, 3 requêtes, 300 ms
- après ce commit, 2 requêtes, 160 ms
=> Ne pas recompter les candidatures dans l’admin

itou/users/models.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Django-4-2-d30d5bfb62b24ca495c0d87ac19669f3**
Au lieu de définir un mot de passe pour un utilisateur qui ne sait même pas qu’il dispose d’un compte sur la plateforme, on peut l’empêcher de se connecter.
=> Définir un mot de passe inutilisable pour les utilisateurs créés par des tiers

itou/www/apply/views/submit_views.py, tests/www/apply/test_submit.py
La seule utilisation de la session est pour `selected_jobs`, afin d'avoir un poste présélectionné pour la candidature.
En cas de session manquante, l'utilisateur peut tout à fait recocher la case et cela permet d'éviter les erreurs de session manquante aux utilisateurs.
=> Parcours de candidature: la session est maintenant optionelle

itou/www/apply/forms.py, itou/www/apply/views/process_views.py
Pour le parcours de déclaration d'embauche, on souhaite réutiliser au maximum les vues existantes, mais sans candidature.
=> Parcours de candidature: faciliter la réutilisation d'un formulaire sans candidature

clevercloud/crons/populate_metabase_matomo.sh
Cela fait planter la commande.
En le corrigeant tout bêtement.
=> populate_metabase_matomo: Retirer un argument inutilisé

itou/approvals/migrations/0008_poleemploiapproval_nir_idx.py, itou/approvals/models.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Afficher-l-ligibilit-IAE-sur-la-liste-des-candidatures-2ae374e0d88d444d867fb1a05061463d**
Approximativement une accélération de 25x de `PoleEmploiApprovalQuerySet.find_for()`.
=> Indexer PoleEmploiApproval.nir

tests/approvals/tests.py
Une suspension ne peut pas être saisie pour une date future.
=> Retrait d’un cas impossible de ApprovalModelTest.test_remainder

itou/siaes/models.py, itou/templates/approvals/email/new_prolongation_for_prescriber_body.txt, itou/templates/approvals/includes/declaration_upload_panel.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, tests/www/approvals_views/test_prolongation.py
https://www.notion.so/plateforme-inclusion/Limiter-l-affichage-du-bilan-Excel-prolongation-uniquement-aux-AI-c7c73577a3ae4a83bf470fc2131e63a3
Changement d'avis coté DGEFP, à priori temporaire
Le téléversement du fichier bilan et sa mention dans l'e-mail récapitulatif sont désormais réservés aux AI pour les bonnes raisons de prolongation.
=> Les bilans de prolongation ne sont disponibles que pour les AI

itou/approvals/models.py, itou/job_applications/models.py, tests/approvals/tests.py
Moins de requêtes, moins de mémoire utilisée, plus de clarté.
=> Réécrire Approval.can_be_deleted

itou/approvals/migrations/0009_suspension_cannot_start_in_the_future.py, itou/approvals/models.py
Vérifier et documenter cette contrainte.
=> CheckConstraint que les Suspensions ne démarrent pas dans le futur

itou/www/apply/forms.py, itou/www/apply/views/process_views.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=690529239c8b463bbb57d34ce1ecd83c&pm=c
Ce champ dynamique était revalidé systématiquement lors d'un rechargement HTMX , déclenché par une modification du champ "Type de qualification".
Une erreur de validation était affiché en dehors de la validation principale du formulaire.
Suppression des erreurs de validation pour ce champ dans un contexte de rechargement HTMX.
=> BOOST : GEIQ - correction de la validation du niveau de qualification

tests/approvals/factories.py, tests/approvals/tests.py, tests/job_applications/factories.py, tests/users/factories.py, tests/www/approvals_views/test_detail.py
Utiliser les fonctionnalités natives de _factory_boy_ et essayer de coller au maximum à sa philosophie pour éviter des déconvenues.
=> Améliorations et corrections pour certaines `approvals.factories`

itou/approvals/admin.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, tests/www/approvals_views/__snapshots__/test_prolongation.ambr, tests/www/approvals_views/test_prolongation.py
- Utiliser au maximum ce que Django nous propose (`required`, `initial`, `errors_messages`, _widgets_, etc) et ainsi réduire le code _custom_.
- N'avoir au maximum que 2 endroits (classe et `__init__`) qui modifie le comportement du champs au lieu de 3 (classe, `__init__` et `Meta`).
- Ne garder que ce qui est dynamique dans les méthodes, le reste est mis dans la classe.
- Faciliter le découpage en 2 formulaires pour #2727.
=> Quelques corrections et un réusinage pour le formulaire de prolongation des PASS IAE

itou/metabase/utils.py
Préferer `itou.utils.iterator.chunks`.
=> Retrait de itou.metabase.utils.chunks

itou/approvals/models.py, tests/approvals/tests.py
Inutile depuis 57403698c6e27a219711f5f16a02e4df324f19e2.
=> Retrait de Suspension.start_in_future

itou/templates/layout/_footer.html
Nous avons remplacé UptimeRobot par Updown mais nous avons oublié de le répercuter dans le site.
=> Remplacement du lien de disponibilité (désormais Updown)

itou/siae_evaluations/emails.py, itou/templates/siae_evaluations/email/to_institution_selected_siae_body.txt, itou/utils/constants.py, tests/siae_evaluations/__snapshots__/test_models.ambr
Le nom de domaine est différent de celui utilisé pour les emplois (`aide.emplois`).
ATTENTION : ce centre d'aide n'a pas encore été publié, c'est pourquoi nous avons décidé avec Sarah de supprimer le seul lien public en attendant.
=> [Zendesk] Ajout d'une constante pour référencer la plateforme d'aide aux DDETS et suppression d'un lien

itou/approvals/notifications.py, itou/templates/approvals/email/new_prolongation_for_prescriber_body.txt, itou/utils/emails.py, itou/utils/settings_context_processors.py, tests/approvals/tests.py
[Carte Notion](https://www.notion.so/plateforme-inclusion/Envoi-des-e-mails-de-prolongation-avec-l-adresse-ad-quate-dfd061ab4abc44b5afd9f5e06f0b9548?pvs=4)
Zendesk considère les e-mails transférés comme étant du SPAM. De plus, il est plus confortable pour l'utilisateur de répondre à un courriel que de le transférer.
=> Envoi des e-mails de prolongation avec l'adresse adéquate

itou/siae_evaluations/emails.py, itou/siae_evaluations/fixtures.py, itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/migrations/0009_calendar_adversarial_stage_start.py, itou/siae_evaluations/models.py, tests/siae_evaluations/factories.py, tests/siae_evaluations/test_management_commands.py, tests/siae_evaluations/test_models.py, tests/www/siae_evaluations_views/test_institutions_views.py
**Doit être en prod avant le 24 juillet 2023**
Le calendrier type de la DGEFP n’est pas respecté pour cette campagne. Il stipule que la phase contradictoire commence 6 semaines après le début de la phase amiable.
Pour cette campagne de contrôles qui a débuté le 12 juin, ça tombe le 24 juillet. À cause de la période juillet-août, il a été décidé de reprendre le contrôle a posteriori au 1er septembre 2023, mais le code n’a pas été modifié.
En l’état, la phase contradictoire démarrerait donc le 24 juillet 2023 et non le 1er septembre.
=> Permettre la configuration du début de la phase contradictoire

itou/siae_evaluations/emails.py, itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/migrations/0010_evaluationcampaign_submission_freeze_notified_at.py, itou/siae_evaluations/models.py, itou/templates/siae_evaluations/email/to_institution_siaes_submission_frozen_body.txt, itou/templates/siae_evaluations/email/to_institution_siaes_submission_frozen_reminder_body.txt, itou/templates/siae_evaluations/email/to_institution_siaes_submission_frozen_reminder_subject.txt, itou/templates/siae_evaluations/email/to_institution_siaes_submission_frozen_subject.txt, tests/siae_evaluations/__snapshots__/test_management_commands.ambr, tests/siae_evaluations/factories.py, tests/siae_evaluations/test_management_commands.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Notification-e-mail-pour-annoncer-l-Ouverture-de-la-phase-2-bis-et-3-bis-uniquement-pour-les-ddet-e5fb9c1a204d4d67bd582b16834955b6**
**Carte Notion : https://www.notion.so/plateforme-inclusion/Notification-e-mail-Rappel-8-jours-apr-s-le-lancement-d-une-phase-bis-2-ou-3-uniquement-pour-les-a821c688aff24140a2ff484ef188f5bf**
Informer les DDETS que leur contrôle est attendu par les SIAE.
=> Ajout d’une notification lors du passage en phase 2 & 3 bis

itou/siaes/management/commands/import_ea_eatt.py
XLS import file for EA / EATT can contain fields with a new value that must be ignored : _"Entreprise Adaptée en Etablissement Pénitentiaire"_
=> ASP imports: fix EA/EATT XLS import

itou/templates/account/login_generic.html
[Carte Notion](https://www.notion.so/plateforme-inclusion/Affichage-d-un-formulaire-de-secours-quand-Inclusion-Connect-est-indisponible-47796de784f642cebf4e97c4027957a5?pvs=4)
Suite ~~à la matinée~~ aux quelques minutes d'exercice « Inclusion Connect brûle », mise en place d'un formulaire de secours accessible par les prescripteurs et les employeurs. Il est actuellement désactivé mais il suffira de le réactiver dans Tally.
=> Affichage d'un formulaire d'urgence en cas de panne d'Inclusion Connect

itou/utils/apis/metabase.py, itou/www/stats/views.py
**Fil slack : https://itou-inclusion.slack.com/archives/C04SAGUGJFJ/p1689686808968639?thread_ts=1688553709.006999&cid=C04SAGUGJFJ**
Pour dépanner Yannick et lui éviter un long recablage. C'est plus simple si directement au niveau C1 on verrouille ce filtre en amont. C'est pas idéal mais la vie est faite de compromis.
=> Stats : Ajout d'un filtre technique verrouillé sur 5 des 7 TB PE

itou/users/models.py, tests/conftest.py
Ne pas gérer de cas impossible dans le code de production.
=> Rendre la fixture admin_client plus réaliste

itou/static/js/admin.js
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=1fd7b3e4df2a46898bd1cdaf8a6f647c&pm=c
Tout est dans le titre : c'est pas beau.
Le fichier template du widget par défaut des champs de mots de passe a été modifié pour le site principal avec un ajout de bouton (pour cacher ou montrer le mot de passe).
Ce n'est pas utile (ni fonctionnel) sur l'admin, puisque pas de bootstrap disponible.
=> BOOST: enlever les boutons disgracieux sur les champs de mot passe dans l'admin

itou/static/js/admin.js
**Carte Notion : https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=1fd7b3e4df2a46898bd1cdaf8a6f647c&pm=c**
https://github.com/betagouv/itou/pull/2790#discussion_r1272191364
=> Préciser le JS qui cache le champchamp password de l’admin

itou/openid_connect/france_connect/models.py, itou/openid_connect/inclusion_connect/models.py, itou/openid_connect/models.py, itou/users/models.py, tests/openid_connect/france_connect/tests.py, tests/openid_connect/inclusion_connect/tests.py, tests/users/test_admin_views.py, tests/users/test_models.py, tests/www/login/tests.py
**Carte Notion : **  https://www.notion.so/plateforme-inclusion/Emp-cher-les-candidats-d-utiliser-Inclusion-Connect-84a3ac9e883a42118c3e2535dd8b97e9?pvs=4
Pour éviter des cas de candidats migrant à inclusion connect parce que le prescripteur leur a donné leur email.
=> Améliorer la cohérence SSO / User.kind

itou/approvals/admin.py
- Ajout du champ et filtre pour `ProlongationRequest.status`.
- `is_in_progress` n'est utile que pour `Prolongation()`.
- J'enlève le filtre `HasReportFile` de `ProlongationRequest()` car pas d'historique pour ce modèle.
- Pas de `date_hierarchy` pour `ProlongationRequest()`, on verra si le besoin arrive.
=> Prolongations - Admin : Améliorations rapides suite à la MEP

itou/www/approvals_views/forms.py, tests/www/approvals_views/test_prolongation.py
=> DeclareProlongationForm: vérifier le paramètre “reason”

itou/employee_record/management/commands/employee_records_status.py
Nous avons de plus en plus de demandes au support a propos de nombreuses fiches salariés n’apparaissent pas.
Dans la quasi-totalité des cas c'est suite à un changement de SIRET, l'ASP ne gérant pas cette opération de leur coté ils obligent les employeurs à renvoyer une fiche salarié pour tout leurs salariés...
Création d'un script à utiliser par un tech afin d'extraire le statut de fiche salarié (semblable à ce qui est affiché dans l'admin des candidatures) pour une liste de PASS IAE et un/des SIRET.
Pour le moment pas de test associés car ça été fait (un peu) dans la précipitation, ça ne fait que lire la donnée et que c'est lancé manuellement par un tech.
=> FS : Ajout de `employee_records_status` pour extraire le statut de fiche salarié en masse

itou/prescribers/apps.py, itou/users/apps.py
But not all of them!
Do not change all models / app : some users are heavily relying on the current display order (by force of habit or convenience). 
Display order can be changed with a custom ordering field in the app (should the need arise).
=> admin: change display name of some apps

clevercloud/download_employee_records.sh
Changement de la logique de `--dry-run` à `--wet-run` dans 91ad4396ec07390d7cf83e332c62f74f3354948a qui n'a pas été répercuté dans le script shell utilisé sur la PROD...
=> [Fix] Cron - transfer_employee_records : Utiliser `--wet-run` pour la PROD

itou/templates/siae_evaluations/institution_evaluated_siae_notify_step2.html
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=b325b680bd5d48dcb49a8f0848110199&pm=c
La partie "Données" doit être positionnée à droite de l'écran 
Dans le bon `div`.
=> BOOST: CAP - décalage de la partie "données" dans la notification de sanction

itou/approvals/models.py, itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/models.py, tests/approvals/tests.py, tests/employee_record/test_models.py
https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-je-veux-pouvoir-prolonger-un-PASS-IAE-7-mois-avant-la-fin-210-jours-de-reliquat-re-a6684dd5dfc34e1dbfd80f87b5b3802a
Changement demandé par la DGEFP
- une prolongation est possible 7 mois avant la fin du PASS IAE (210 jours de reliquat)
- un seul commit : retour en arrière facilité (demande métier)
=> PASS IAE : modification de la période ou les prolongations sont possibles

requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/test.txt
Clever fournit uWSGI, nous n’avons pas besoin de l’installer.
=> Retirer uWSGI des requirements Python

itou/www/approvals_views/forms.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=05244c8409ad4769aa788e3b45ab34cc&pm=c
Cette mention fait référence aux motifs de suspension de la circulaire DGEFP de 2006 et n’est désormais plus en vigueur.
=> BOOST : retrait d'une mention obsolète sur le formulaire de suspension

itou/templates/apply/process_geiq_eligibility.html, itou/www/apply/views/process_views.py
Évite l'utilisation de la session (qui peut être perturbant avec plusieurs onglets) et cela facilitera la réutilisation de ces vues pour le parcours de déclaration d'embauche (sans objet candidature disponible).
=> Éligibilité GEIQ: utilisation des paramètres d'URL plutôt que la session

itou/templates/signup/job_seeker_situation.html
(https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=73b2807b839d4d4aae362d48144cc9d7&pm=c)
Plus nécessaire (point UI)
=> BOOST - Retirer le texte qui parle d’IAE dans l’écran d’inscription des candidats

itou/www/approvals_views/forms.py
https://www.notion.so/plateforme-inclusion/Mot-anglais-qui-s-est-gliss-dans-le-formulaire-de-prolongation-fe4ad23e9e594a829c790b5b37b2f234
On est contre les anglicismes
=> BOOST : le label du champ "reason" apparait en anglais dans le formulaire 

tests/www/dashboard/tests.py
La `factory` pouvait choisir "Bob" comme prénom.
=> Test: correction d'un test instable

itou/templates/apply/submit_base_two_columns.html
Cela facilitera la mise en place du bandeau d'information prévu dans le parcours de Déclaration d'embauche.
Avant:
Après:
=> Parcours de candidature: utilisation du bloc content_title

itou/eligibility/models/iae.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Afficher-l-ligibilit-IAE-sur-la-liste-des-candidatures-2ae374e0d88d444d867fb1a05061463d**
=> Retirer du code non testé de EligibilityDiagnosis

itou/templates/dashboard/includes/siae_employees_card.html, itou/www/dashboard/views.py
Dans le cadre du parcours de déclaration d'embauche, on aura bientôt 2 liens ("Enregistrer une candidature" & "Déclarer une embauche"), qui seront tous les deux désactivés en cas de sanction.
Il faudra soit une `cached_property` soit une variable dans le contexte, je pars sur la seconde option.
=> Tableau de bord: vérification des sanctions au niveau de la vue

itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, tests/www/apply/test_submit.py
Pour bien indiquer qu'on modifie un candidat et non qu'on en crée un.
=> Parcours de vérification de profil : correction du titre sur la dernière étape

itou/templates/approvals/declare_prolongation.html
Le template `approvals/declare_prolongation.html` contenant le bloc `htmx` n'est utilisé que par la vue `itou.www.approvals_views.views:declare_prolongation` qui n'est jamais appelé par htmx.
1er commit de #2856 qui devrait être moins sujet à discussion.
=> Suppression d'un bloc htmx inutile

itou/siaes/admin.py, itou/templates/apply/includes/job_application_sender_info.html, itou/templates/apply/includes/job_seeker_info.html, itou/templates/invitations_views/create.html, itou/templates/invitations_views/email/accepted_notif_establishment_sender_body.txt, itou/templates/prescribers/card.html, itou/templates/static/accessibility.html, itou/www/apply/forms.py, itou/www/approvals_views/forms.py, itou/www/signup/forms.py
https://www.notion.so/plateforme-inclusion/Harmoniser-le-wording-e-mail-Adresse-e-mail-partout-dans-l-interface-boost-effc21ea11464650beef2138fb8664c8
Faire le distingo entre l'objet e-mail et l'adresse e-mail
`ripgrep` mais pas tout le temps
=> BOOST: remplacer "e-mail" par "adresse e-mail" où nécessaire

itou/metabase/tables/approvals.py, tests/metabase/management/test_populate_metabase_emplois.py
**Carte Notion : https://www.notion.so/Ajouter-la-colonne-ID-pass-agr-ment-sur-la-table-pass-agr-ments-puis-ajouter-une-colonne-injection_-47b196f5d93644c08dd6ebc4f75d8a77**
Pour permettre à nos analystes de croiser la table des demandes de prolongation avec celle des PASS IAE.
C'est essentiellement un oubli de ma part.
=> Metabase : Ajout de l'ID de PASS IAE

Makefile, itou/siaes/management/commands/move_siae_data.py, scripts/import-latest-db-backup.sh
Les commandes `make django_admin` cassent toutes chez moi sur `django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`.
Si le problème est juste chez moi, ignorer cette PR (je pars en congés et revient le 7 août de toute façon donc pas d'urgence).
Si le problème est chez plus de monde, le fix de cette PR est un début qui a fonctionné au moins pour moi, après quelques autres essais.
=> Makefile : Réparation des commandes `make django_admin`

tests/openid_connect/inclusion_connect/tests.py
Le nouvel IC ne transmets plus un jwt en tant qu'access token, on ne le décode done plus.
=> Nettoyage de code de test inutile

config/urls.py, itou/utils/hijack/urls.py, itou/utils/hijack/views.py, tests/utils/perms/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Revenir-sur-l-admin-lorsqu-on-rel-che-un-utilisateur-d60f2474dd354a81ac258fce4a2b4f63?pvs=4
Pour simplifier la vie du support.
=> Retourner sur l'admin quand on relâche un utilisateur détourné.

itou/templates/layout/_footer.html, itou/templates/layout/_header_nav_primary_items.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/C1-Dropdown-besoin-d-aide-74e9f80717ec4e2686c50a3a26c6bf46?pvs=4
Transformation du bouton "besoin d’aide ?" du header menu en dropdown
Harmonisation du menu footer au passage
=> Update menu "besoin d'aide"

docker-compose.yml
**Fil slack : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1691682102369149**
Le debugging interactif (`import ipdb; ipdb.set_trace()`) ne fonctionne plus avec Docker depuis... un certain temps.
=> Ressucitation du debugging interactif en local dev dans le cas de Docker

config/settings/base.py, itou/templates/dashboard/includes/stats.html, itou/users/models.py, itou/utils/apis/metabase.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/views.py, tests/www/dashboard/tests.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Outil-ACI-Cr-er-une-liste-blanche-pour-mettre-disposition-ce-TB-priv-certaines-SIAE-a0e8210f55e84b72852ff5583be4d0a8**
Ces nouvelles stats sont prêtes à être mises à disposition de quelques ACI dans leur espace privé de telle manière qu’elles ne voient que les données qui les concernent. 
- Nouvelle vue stats dédiée
- Nouvelle liste blanche par structure, similaire à la liste blanche déjà existante par utilisateur
- PR d'un nouveau secret https://github.com/betagouv/itou-secrets/pull/42 (👁️👁️👁️)
=> Stats : Ajout de nouvelles stats "Suivi du cofinancement de mon ACI" ouvertes à une liste blanche d'employeurs

itou/www/apply/forms.py, tests/www/apply/test_forms.py
(https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=39dd6f8b478f44bfad2aa9ea41d0fdfa&pm=c)
Mentions non applicables aux structures ne faisant pas partie de l'IAE (EA, EATT, OPCS, GEIQ).
=> BOOST - retirer des mentions spécifique à l'IAE dans le formulaire d'embauche

itou/eligibility/models/iae.py, itou/templates/apply/includes/list_card_body_siae.html, tests/www/apply/__snapshots__/test_list.ambr, tests/www/apply/test_list.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Afficher-l-ligibilit-IAE-sur-la-liste-des-candidatures-2ae374e0d88d444d867fb1a05061463d**
Faciliter la vie des SIAE.
Le badge avait été retiré pour des raisons de performances. Depuis la recherche d’agréments Pôle emploi a été accélérée (bc31fd390bc0830893aead76e664593640fea372 et 8b154ca66d2acffbc418e5b0b0ed7399878a9cf7).
Avec le second commit, la recherche du dernier diagnostic valide a également été accélérée.
La vue passe plus de temps à construire les filtres (2s sur les 3 nécessaires au rendu pour une SIAE avec beaucoup de candidatures). Les requêtes SQL prennent au total 200ms en local, ce qui reste raisonnable.
Il reste un 1+N pour chercher le dernier diagnostic d’éligibilité. Comme ce n’est pas une mince affaire, ce sera …
=> Afficher l’éligibilité IAE dans la liste des candidatures SIAE

itou/siae_evaluations/fixtures.py
La plupart des SIAE sont de type ACI, qui doivent sélectionner trois critères.
=> CAP: Améliorer les fixtures

itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, tests/siae_evaluations/test_management_commands.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Rappel-envoy-lorsque-la-DDETS-n-a-rien-faire-4469424ada6f44f69efcea17d5d09872**
=> CAP: Retrait du rappel lorsque les SIAE restantes n’ont pas soumis de docs

itou/approvals/notifications.py, tests/approvals/test_notifications.py
Mailjet limite à 50 destinataires, certaine agence PE ont plus de 50 agents inscrits donc l'envoi de l'email de rappel échouais.
Vu qu'il n'est pas vraiment nécessaire d'envoyer le rappel à autant de personne on limite désormais au 10 utilisateurs qui se sont connecté le plus récemment, cela devrais cibler les personnes qui sont dédiés à l'IAE mais aussi ceux qui interviennent ponctuellement dessus.
=> Limiter le nombre de destinataire pour l'email de relance pour la demande de prolongation

itou/approvals/notifications.py, itou/templates/approvals/email/prolongation_request/created_reminder_body.txt, tests/approvals/__snapshots__/test_notifications.ambr
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Retirer-la-mention-qui-fait-r-f-rence-l-acceptation-automatique-dans-l-email-de-notif-des-prolonga-3616e4ea7c0a4544b2d893427d013e38
=> Retirer la mention qui fait référence à l’acceptation automatique dans l’email de notif des prolongations

config/settings/base.py, itou/templates/dashboard/includes/stats.html, itou/users/models.py, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py, tests/users/test_models.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Cr-er-liste-blanche-et-publier-les-TB345-et-TB330-sur-c1-pour-les-CD-phase-de-test-aupr-s-d-un-gro-0ecae07747d8434bae347e620c96acfc**
Cela fait un moment que les CD n'ont plus aucune stats spécifiques à eux (le TB 118 était désactivé). Ici on teste deux nouveaux TB à leur destination.
L'intégration est testée OK depuis mon local dev, mais il reste un souci côté Metabase à résoudre par les analistos avant MEP, les filtres du 330 n'ont pas l'effet filtrant attendu. Cf https://itou-inclusion.slack.com/archives/C04SAGUGJFJ/p1692107278924309?thread_ts=1691560994.578509&cid=C04SAGUGJFJ
=> Stats : Ajout de deux nouveaux TB pour les CD sur liste blanche de quelques départements

itou/www/approvals_views/forms.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Prolongations-en-tant-qu-employeur-je-veux-comprendre-que-ma-prolongation-doit-se-faire-par-p-riod-1bfa9cc189414bccaec62abb49e62751**
=> Retrait d’un garde inutile de CreateProlongationForm

itou/templates/siaes/card.html, itou/templates/siaes/includes/_card_siae.html, itou/www/apply/views/submit_views.py, itou/www/siaes_views/views.py, tests/siaes/factories.py, tests/www/apply/test_submit.py, tests/www/search/tests.py, tests/www/siaes_views/__snapshots__/test_views.ambr, tests/www/siaes_views/test_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Bloquer-la-possibilit-de-postuler-sur-les-structures-qui-n-ont-pas-de-membres-539eddfa645c4b25bd592633436288c2?pvs=4
Des candidats postulent à des postes dans des entreprise n’ayant pas de membre et ces candidatures restent lettre morte si aucun employeur ne s’inscrit sur la structure
=> Bloquer les candidatures dans des SIAEs sans membre actif

itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/includes/prolongation_declaration_form.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py, tests/www/approvals_views/test_prolongation.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Prolongations-en-tant-qu-employeur-je-veux-comprendre-que-ma-prolongation-doit-se-faire-par-p-riod-1bfa9cc189414bccaec62abb49e62751**
Le `help_text` est calculé dynamiquement, mais n’est pas montré tant que le formulaire n’est pas rechargé. Voir le commit.
=> Recharger CreateProlongationForm.reason.help_text lors d’un changement

itou/approvals/models.py, itou/www/approvals_views/forms.py, tests/approvals/tests.py, tests/www/approvals_views/__snapshots__/test_prolongation.ambr, tests/www/approvals_views/test_prolongation.py
`prolongation.end_at` n’est pas _nullable_.
=> Suppression d’une vérification doublon sur Prolongation.end_at

itou/www/apply/forms.py, tests/www/apply/test_forms.py
Petit oubli dans le `Meta` du form.
=> Parcours de candidature GEIQ: sauvegarde du niveau de qualification

tests/www/approvals_views/test_prolongation.py
Il manque le freeze de la date, master est donc rouge.
=> test_prolongation: Geler la date pour les tests et snapshots

itou/siaes/models.py, itou/static/js/utils.js, itou/templates/approvals/prolongation_requests/show.html, itou/templates/dashboard/api_token.html, itou/templates/includes/copy_to_clipboard.html, itou/templates/invitations_views/includes/pending_invitations.html, itou/templates/siaes/job_description_card.html, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/siaes_views/test_views.py
Simplifier la réutilisation et la maintenance.
Uniformiser le comportement, code et UI ([fil slack UX](https://itou-inclusion.slack.com/archives/CQ6C3LSAH/p1692622507238619)).
Le thème contient aussi un moyen de copier dans le presse-papier mais ce n'est actuellement pas utilisé et demande un balisage particulier donc à voir ce qu'on veux en faire.
1. Lien fiche métier (Avant/Après)
2. Invitation (Avant/Après)
3. Token API (pas de changement UI)
4. Demande de prolongation (pas de changement UI)
5. Tooltip
=> Mise en commun du code JS et HTML pour la copie presse-papier

itou/siaes/admin.py, itou/www/siaes_views/views.py, tests/www/siaes_views/test_job_description_views.py
A été cassée car un test manquait.
=> Correction de la fonctionnalité d'historisation des fiches de poste

itou/approvals/models.py, itou/utils/validators.py, itou/www/approvals_views/forms.py, itou/www/siae_evaluations_views/forms.py, tests/approvals/__snapshots__/test_notifications.ambr, tests/approvals/factories.py, tests/approvals/tests.py, tests/www/approvals_views/__snapshots__/test_prolongation.ambr, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation.py, tests/www/siae_evaluations_views/test_institutions_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Prolongations-en-tant-qu-employeur-je-veux-comprendre-que-ma-prolongation-doit-se-faire-par-p-riod-1bfa9cc189414bccaec62abb49e62751**
Beaucoup de demandes de prolongation (pour motifs RQTH ou + de 50 ans + AI/ACI difficultés particulières) sont déposées pour 2, 3, 4 voire 5 ans d’un coup alors que le réglementaire indique “par prolongations successives de 12 mois”
Le support doit reprendre toutes ces demandes à la main pour aller modifier la demande de prolongation = perte de temps.
=> Renouvellement des prolongations par périodes d’un an

itou/utils/validators.py, itou/www/siae_evaluations_views/forms.py, tests/www/siae_evaluations_views/test_institutions_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/format-date-en-anglais-dans-le-texte-d-erreur-dsl-pas-vu-au-1er-tour-c5e085ab35db4314882c31b475099ff1**
Clarté pour les utilisateurs.
=> Utiliser le format français pour les dates dans les messages d’erreur

itou/www/apply/forms.py, tests/www/apply/test_submit.py
It could be part of the URL, thus be exploited.
**[Carte Notion ](https://www.notion.so/plateforme-inclusion/S-curit-am-liorer-le-filtre-d-URLs-concernant-les-fichiers-envoy-s-sur-le-S3-5e948ac77d574b249d647455a0f828ee?pvs=4)**
Fait partie des problèmes remontés durant l'audit.
=> Sécurité : améliorer la détection du domaine S3

itou/templates/stats/stats.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/ic-ne-mal-plac-058cc2a65ac641cfa5a1d5eba4b971c0?pvs=4
Elle est mal placé
=> Correction de l'icone de lien de la page de Stats

itou/job_applications/export.py, tests/job_applications/tests.py
**[Carte Notion](https://www.notion.so/plateforme-inclusion/Ajouter-la-civilit-du-candidat-dans-le-fichier-des-exports-de-candidatures-bf07f5590fda4b6b913e0b8c08579ecf)**
Permettre de partager cette info en particulier à RDVI qui en a besoin et les traite manuellement pour l'instant.
Sans promesse que la donnée soit dispo, mais on donne ce qu'on a : titre déclaré et si dispo, info depuis le NIR (dans cet ordre).
- 781 480 candidats
- 322 048 (41%) ont ET un titre, et un NIR renseigné (obligatoire depuis un certain temps)
- 221 089 ont un NIR mais pas de civilité
-  54 952 ont une civilité mais pas de NIR
- 183 391 (23%) n'ont ni NIR, ni civilité 
Dans 76% des cas nous aurons donc une civilité à proposer.
En outre, le titre déclaré et celui proposé par le NIR est différent dans 1705 cas …
=> job_applications: Add the job seeker title in exports

itou/utils/perms/context_processors.py, itou/utils/perms/middleware.py, itou/utils/perms/prescriber.py, tests/utils/test.py, tests/utils/tests.py, tests/www/apply/test_list.py, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_list.py, tests/www/approvals_views/test_prolongation_requests.py, tests/www/dashboard/tests.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py, tests/www/siaes_views/test_job_description_views.py
Le middleware et le context processor regardent à peu près les mêmes infos: autant stocker les infos sur la requête et éviter de les récupérer deux fois.
Globalement on passe pour les vues avec rendu de template:
- pour les SIAE: de 2 à 4 requêtes à toujours 2 requêtes
- pour les prescripteurs: de 2 à 4 requêtes à toujours 1 requête
- pour les inspecteurs: de 1 à 3 requêtes à toujours 1 requête
Et pour les vues sans rendu de template:
- pour les SIAE: de 1 à 3 requêtes à toujours 2 requêtes
- pour les prescripteurs: de 1 à 3 requêtes à toujours 1 requête
- pour les inspecteurs: de 0 à 2 requêtes à toujours 1 requête
=> Optimisation de requêtes entre le middleware & le context processor

itou/job_applications/migrations/0011_added_geiq_qualification_and_training_fields.py, itou/job_applications/models.py, tests/www/apply/__snapshots__/test_process.ambr
https://www.notion.so/plateforme-inclusion/Modifier-wording-dans-les-champs-du-formulaire-d-embauche-des-GEIQ-pour-pr-ciser-qu-il-s-agit-de-la-246fa053deda4f62a07d26260b849d81?pvs=4
Risque possible de confusion sur les libellés
Modification directe du modèle et de la migration pour en éviter une nouvelle.
=> BOOST - Modification des labels des champs concernant la qualification pour les GEIQ

itou/templates/approvals/prolongation_requests/list.html, itou/templates/dashboard/includes/prescriber_job_seekers_card.html, itou/templates/includes/pagination.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation_requests.py, tests/www/dashboard/tests.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/URGENT-En-tant-que-prescripteur-habilit-je-peux-filtrer-les-demandes-de-prolongation-par-statut-V-00b248a4f40f4d23a9751cd555a8706b?pvs=4
- Demandes nombreuses classées de la plus récente à la plus ancienne, certains ne traitent pas forcément par ordre d’arrivée, on doit éviter que des demandes soient mises de coté car non visibles 
- Permettre aux utilisateurs qui pilotent l’activité de leur organisation d’identifier rapidement les demandes en attente
- Mettre en place un filtre les demandes à traiter (pour la V1 on se contente juste d’une case à cocher)
=> Demandes de prolongation : Filtre "À traiter" et navigation

itou/templates/layout/_header_nav_primary_items.html
yanapa
Voir captures 
Avant : 
Après :
=> BOOST : le contenu du menu de sélection de structure peut être trop long

itou/siae_evaluations/admin.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/ADMIN-ajouter-le-champ-commentaire-dans-la-page-d-une-campagne-de-contr-le-a-posteriori-boost-a29b590a72fa4d679f2c2364fe8e0622?pvs=4
Pour tracer les éventuelles actions réalisées par l’équipe
=> Ajouter le champ commentaire dans la page d’une campagne de contrôle a posteriori

itou/prescribers/enums.py, itou/prescribers/migrations/0001_initial.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Donner-plus-de-pr-cisions-sur-le-type-Organisation-d-l-gataire-d-un-CD-boost-a51e9163dcc84b3ebf83dae93be83e09?pvs=4
De nombreuses organisations concernées ne le sélectionnent pas au moment de l’inscription
=> Donner plus de précisions sur le type Organisation délégataire d'un CD

itou/fixtures/django/05_test_users.json
Sinon, on ne peut pas le détourner dans les review apps pour accéder aux vues du controle à posteriori des SIAEs
=> Corriger le SSO d'un employeur des fixtures

itou/templates/dashboard/dashboard.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/En-tant-qu-utilisateur-des-emplois-je-veux-tre-inform-des-v-nements-boost-e7e6431b08c8410e93a93fe4f360970a?pvs=4
Actuellement l’intégration livestorm n’est visible que sur le moteur de recherche mais certains utilisateurs comme les employeurs n’utilisent pas le moteur de recherche
=> Ajout de la bannière livestorm au tableau de bord des prescripteurs et employeurs

itou/templates/dashboard/includes/labor_inspector_evaluation_campains_card.html, itou/templates/dashboard/includes/siae_evaluation_campains_card.html, itou/www/dashboard/views.py, itou/www/siae_evaluations_views/views.py, tests/www/siae_evaluations_views/test_siaes_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Mettre-dispo-le-lien-du-calendrier-de-la-campagne-de-contr-le-c-t-SIAE-d8a0ee41329d4c12826a4011dcc443b7?pvs=4
Rendre le calendrier de la campagne en cours accessible également pour les SIAE
=> Mettre à dispo le lien du calendrier de la campagne de contrôle côté SIAE

docker-compose.yml, docker/dev/django/Dockerfile, docker/dev/postgres/Dockerfile
Debian buster ne sera bientôt plus du tout maintenu : https://www.debian.org/releases/buster/.
Je n'ai pas eu de problème particulier de mon coté mais a tester pour ceux qui utilisent MacOS ;).
=> Docker : MAJ de Debian et quelques améliorations au passage

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Mise-en-production-du-tableau-de-bord-Suivi-des-demandes-de-prolongation-ebd620b3c59f40449d12eff435e96dd2?pvs=4
Ajout d'un ID de dashboard metabase à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
=> Ajout de l'ID 336 de dashboard metabase

clevercloud/crons/populate_metabase_emplois.sh, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/job_applications.py, tests/metabase/management/test_populate_metabase_emplois.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-une-colonne-candidatures-parcours_de_cr-ation-reprise-de-stock-AI-7726c410cb52499c88d4a5b2742be9f1**
Suite aux améliorations réalisées par Antoine on peut désormais savoir quel parcours de création à suivi une candidature (Normale, reprise de stock AI, import agrément PE, action support).
Il faut désormais créer une colonne `candidatures.parcours_de_création` afin que les merveilleux data analyst du C2 puissent l’exploiter, en particulier en ce qui concerne la fiabilisation des reprises de stock AI.
=> Metabase : Ajouter une colonne candidatures.parcours_de_création (reprise de stock AI)

itou/templates/dashboard/dashboard.html, itou/utils/perms/context_processors.py, tests/utils/tests.py
`Par ailleurs, a noter que le matomo_context est a priori non utilisé de nos jours car nous n'avons plus de "custom variables" (deprecated coté Matomo, et jamais utilisé par nos analystes au final) donc si il pose des batons dans les roues, on peut le retirer.`
(de https://github.com/betagouv/itou/pull/2937#pullrequestreview-1600649841)
Cf https://github.com/betagouv/itou/commit/16ef33e807a35586da3466cf766a53f2c724dc52
Une fois ce nettoyage effectué, on pourra également totalement supprimer le context processor `get_current_organization_and_perms`  qui ne fait que reprendre des infos présentes sur l'objet `request` (objet déjà présent dans le `context` via `django.template.context_processors.request`).
=> Suppression de matomo_custom_variables du contexte

tests/metabase/conftest.py
The `db` module was patched, which was fine as long as it was imported first. Now with the new `enums` test, the `dataframes` module is in some cases imported first, which makes it not ptched correctly for the tests.
=> tests.metabase: Corriger le test "enums" qui casse master

itou/templates/approvals/email/prolongation_request/created_body.txt, tests/approvals/__snapshots__/test_notifications.ambr
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/En-tant-que-prescripteur-sollicit-pour-une-demande-de-prolongation-je-comprends-que-la-demande-doit-cb363e2ffb8b4860ad7f03314b667e2b?pvs=4
Alerte du support, certains prescripteurs habilités continuent de transférer l’email au support alors que cela n’est plus nécessaire
=> Améliorer le contenu de l'email de demande de prolongation de pass

README.md
Spécifique à Docker, probablement jamais utilisée.
=> Supprimer la doc pour créer un superutilisateur du README

itou/templates/apply/submit_base.html, tests/www/apply/test_submit.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Anomalie-dans-le-parcours-d-enregistrement-d-une-candidature-GEIQ-BOOST-17207fe470074112954d7fe1f921f4c5?pvs=4
Les geiq ne sont pas concernés par les PASS IAE donc on ne doit pas afficher cet encart lorsqu’on oriente en GEIQ
=> Ne plus afficher le PASS IAE dans le parcours d'embauche GEIQ

itou/metabase/tables/organizations.py
https://www.notion.so/plateforme-inclusion/REX-Utilisateur-Ajouter-un-niveau-de-filtre-suppl-mentaire-par-type-de-prescripteur-8261c1c366514b9cb736323883e894e2?pvs=4
Pour l'ajout de filtres sur les indicateurs construits sur la table `organisations`, nous avons besoin d'ajouter des données. Cette table c1 est donc renommée en `organisations_v0` et la table enrichie par le c2 est renommée `organisations`.
=> Modification du nom de la table organisations

README.md
=> Retirer la section données de test du README

itou/eligibility/admin.py, itou/templates/admin/users/change_user_form.html, itou/templates/admin/users/transfer_user.html, itou/users/admin.py, itou/users/admin_forms.py, tests/users/test_admin.py, tests/users/test_admin_views.py
https://www.notion.so/plateforme-inclusion/Admin-Permettre-aux-membres-du-support-de-pouvoir-transf-rer-tous-les-objets-d-une-fiche-utilisate-24aea387d0b04c3aa546bc4fda0201da?pvs=4
Faire gagner du temps au support
=> Admin : Permettre aux membres du support de pouvoir transférer tous les objets d’une fiche utilisateur (candidat) vers une autre, en une seule fois

itou/jobs/models.py
Plus propre.
Avant:
```
In [2]: str(models.Appellation.objects.autocomplete("toto,titi,tutu").query)
Out[2]: 'SELECT "jobs_appellation"."updated_at", "jobs_appellation"."code", "jobs_appellation"."name", "jobs_appellation"."rome_id", "jobs_appellation"."full_text", "jobs_rome"."updated_at", "jobs_rome"."code", "jobs_rome"."name" FROM "jobs_appellation" LEFT OUTER JOIN "jobs_rome" ON ("jobs_appellation"."rome_id" = "jobs_rome"."code") WHERE (full_text @@ to_tsquery(\'french_unaccent\', toto:* & titi:* & tutu:*)) ORDER BY "jobs_appellation"."name" ASC LIMIT 10'
```
Après:
```
In [2]: str(models.Appellation.objects.autocomplete("toto,titi,tutu").query)
Out[2]: 'SELECT "jobs_appellation"."updated_at", "jobs_appellation"."code", "jobs_appellation"."name", "jobs_appellation"."rome_id", …
```
=> jobs: utilisation du SearchQuery de Django plutôt qu'un extra

itou/metabase/dataframes.py, itou/metabase/db.py, itou/metabase/tables/insee_codes.py, itou/metabase/tables/job_applications.py, itou/metabase/tables/siaes.py, itou/metabase/tables/utils.py, itou/metabase/utils.py, tests/metabase/conftest.py, tests/metabase/management/test_populate_metabase_emplois.py
Le type "float" n'existe pas en postgresql.
De même, les type sdéclarés en majuscules ne passent plus à la déclaration stricte avec COPY FORMAT BINARY.
Par contre cela permet de déclarer des colonnes de type UUID natif et de les valider.
=> metabase: Correction d'un nouveau crash qui était jusque là non testé

itou/templates/employee_record/includes/list_item.html, tests/www/employee_record_views/test_list.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/fiches-salari-mettre-jour-En-tant-qu-employeur-je-veux-voir-les-dates-du-PASS-et-non-celles-e8686d21bf3b4338a32c9d1848d0ce1d?pvs=4
Éviter que les employeurs sollicitent le support pour comprendre
=> Amélioration de la page "fiches salarié à mettre à jour"

itou/metabase/tables/selected_jobs.py, tests/metabase/conftest.py, tests/metabase/management/test_populate_metabase_emplois.py
Encore une table qui casse et qui n'était pas testée.
C'est un peu pénible à vérifier car il faut des données récentes (plusieurs GB à télécharger)
Lancer l'export complet (une à deux heures sur ma machine)
Lancer DBT run complet (une bonne quarantaine de minutes sur ma machine)
Et même là on peut encore avoir des fois quelque chose qui "tombe en marche" si les casts sont heureux, et pas plus tard.
=> Corriger une colonne UUID (& integer) dans Metabase

itou/www/dashboard/forms.py, tests/www/dashboard/tests.py
Les utilisateurs préfèrent les messages d'erreur clairs aux 500.
Cf https://itou.sentry.io/issues/4400697798/?project=6164438
=> www.dashboard: avoid crash on missing address line

Makefile, README.md
S’assurer que le venv est à jour au lancement du serveur de développement.
=> Ajouter une règle runserver au Makefile

itou/job_applications/models.py
FIXME qui traîne depuis un certain temps :).
Pas la peine de faire de _multiples_ requêtes SQL si l'on n'est pas sensé avoir de résultats.
=> Candidatures - Éligibilité aux fiches salariés : Sortir plus rapidement et simplement si la SIAE n'utilise pas les FS

config/settings/base.py, itou/approvals/migrations/0001_initial.py, itou/approvals/migrations/0014_migrate_triggers.py, itou/approvals/models.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/migrations/0002_add_notification_update_trigger.py, itou/employee_record/migrations/0005_stop_using_notification_type_field.py, itou/jobs/migrations/0002_create_full_text_trigger.py, itou/jobs/migrations/0003_migrate_trigger.py, itou/jobs/models.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/test.txt, tests/approvals/tests.py
Meilleure traçabilité des modifications et des utilisations.
Permet aussi de se faire la main avant la [mise en place de la table d'audit](https://www.notion.so/plateforme-inclusion/Am-lioration-ADMIN-En-tant-que-membre-ITOU-je-ne-veux-plus-qu-un-PASS-IAE-soit-totalement-supprim--5d303e5a620944909ffde8ff00fd7a01?pvs=4).
=> Utilisation de `django-pgtrigger` pour gérer nos triggers PostgreSQL

itou/templates/includes/pagination.html, itou/templates/siaes/job_description_list.html, itou/www/siaes_views/views.py, tests/www/siaes_views/test_job_description_views.py
https://www.notion.so/plateforme-inclusion/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=bf72d6e5c9eb4999823cca204a7f4fbf&pm=c
Potentiel problème pour les SIAE qui ont plusieurs fiches de postes pour un même code ROME.
Surtout après https://github.com/betagouv/itou/pull/2935 qui permettra l'association et la création de fiche à une candidature.
**Mais** ... le problème tel qu'exprimé dans la carte ne semble pas se poser. Il n'y a pas actuellement de limitation / unicité sur le code ROME des fiches de poste à la création.
J'ai peut-être loupé un truc : à confirmer avec le métier.
Du temps, j'ai ajouté un petit revamping `hx-boost` sur les formulaire de la liste des fiches de postes.
=> Lever la contrainte d’unicité sur la création des fiches de poste

itou/utils/perms/middleware.py
Cela permettra d'utiliser `request.current_organization` et les autres attributs dans toutes les vues sans avoir à se demander si on est dans une des vues matchant `skip_middleware_conditions`.
Au passage, je corrige:
- le logout pour les utilisateurs SIAE/prescripteur n'ayant pas activer IC.
- la libération d'un utilisateur SIAE/institution n'ayant pas d'organisation active
=> Intergiciel ItouCurrentOrganizationMiddleware: on enrichit maintenant toujours l'objet request

docker-compose.yml
A priori, seuls les processus de nos machines ont besoin de communiquer avec...
=> docker-compose: limiter la visibilité de postgres

itou/www/siaes_views/views.py, tests/www/siaes_views/test_job_description_views.py
Le nom de la session était en dure et depuis 4c2cd64f21cd306c1d1cd4775e9081db60ef0289 on n'y met plus rien, les tests étaient aussi trop large car le `"Modifier"` est aussi dans le header (_Modifier mon profil_).
=> Correction : Les SIAE ne peuvent plus modifier leur fiches de poste

itou/eligibility/models/iae.py, itou/utils/perms/user.py, itou/www/apply/views/common.py, itou/www/apply/views/submit_views.py, tests/eligibility/test_iae.py, tests/siae_evaluations/test_models.py, tests/utils/tests.py, tests/www/eligibility_views/tests.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py
- Simplification
- Évite de refaire une nouvelle fois les requêtes vérifiant l'organisation active de l'utilisateur en réutilisant les attributs de l'objet `request`
=> Suppression de la fonction `get_user_info`

itou/utils/perms/institution.py, itou/utils/perms/prescriber.py, itou/utils/perms/siae.py, itou/www/siaes_views/views.py, tests/www/apply/test_list.py, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_list.py, tests/www/approvals_views/test_prolongation_requests.py, tests/www/dashboard/tests.py, tests/www/employee_record_views/test_list.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py, tests/www/siaes_views/test_job_description_views.py
Trop de requêtes, cela fatigue un peu Postgresql et beaucoup les devs qui écrivent des `assertNumQueries`.
Relecture commit par commit encouragée.
=> Réduction du nombre de requêtes SQL sur de nombreuses vues

Makefile
=> Retirer la règle graph_models_itou

itou/templates/invitations_views/includes/pending_invitations.html
**Fil slack : https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1694511293405909**
Essentiellement pour corriger un oubli de ma part dans cette PR précédente : https://github.com/betagouv/itou/pull/2788
Modifications de l'interface :
- Retrait de la mention de la durée de 15 jours
- Ajout de la colonne "Valable jusqu'à" qui permet d'un coup d'oeil de savoir quand l'invitation expire, peu importe qu'elle dure 15 ou 90 jours.
Avant :
Après :
=> Invitations : Correction mineure de l'interface sur le fait que la durée des invitations n'est pas toujours de 15 jours

itou/templates/institutions/members.html, itou/templates/invitations_views/includes/pending_invitations.html, itou/templates/prescribers/members.html, itou/templates/siaes/members.html, itou/templates/siaes/show_financial_annexes.html, itou/templates/signup/includes/authorization_proof.html, itou/templates/signup/includes/submit_rgpd.html, itou/templates/signup/job_seeker_signup.html, itou/templates/signup/prescriber_choose_kind.html, itou/templates/signup/prescriber_confirm_authorization.html, itou/templates/signup/prescriber_user.html, itou/templates/signup/siae_select.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/3-X-Alertes-Changer-certaines-alertes-en-du-texte-simple-pas-boost-bdadbb5222fb49299fe490db16eb6ae7?pvs=4
Améliorer la lisibilité des messages.
=> Changer certaines alertes en du texte simple.

itou/approvals/migrations/0015_alter_suspension_updated_at.py, itou/approvals/models.py, itou/job_applications/migrations/0015_alter_jobapplication_updated_at.py, itou/job_applications/models.py
Car c'est contradictoire :).
Suite et fin de 925118bf829bc5c5914fa6b1c096858df625f818.
Déploiement en 2 étapes :
1. Script `fill_update_at` pour remplir les valeurs manquantes (140k+ `Suspension`, 0 `JobApplication` :thinking:) : ~2 min (sans `time.sleep`) en local
2. Migration du DDL avec voiture balais : ~10s en local
=> Ne plus avoir de champs combinant `auto_now=True` et `null=True`

itou/templates/apply/includes/list_card_body_siae.html, itou/templates/approvals/includes/list_card.html, itou/templates/layout/_header_nav_primary_items.html, tests/www/apply/__snapshots__/test_list.ambr, tests/www/approvals_views/test_list.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/5-4-Refonte-carte-candidature-employeur-petite-boostinette-14289125206f4aab98b5208787df1fb7?pvs=4
Pour respecter l'UX définies dans l'UI Kit et ZeroHeight et pour utiliser les icones `ri-pass-*`
Au passage, correction d'une petite erreur de DOM dans le menu du header
=> Harmonisation des badges Pass IAE

itou/analytics/admin.py, itou/antivirus/admin.py, itou/api/admin.py, itou/approvals/admin.py, itou/asp/admin.py, itou/cities/admin.py, itou/common_apps/organizations/admin.py, itou/eligibility/admin.py, itou/employee_record/admin.py, itou/external_data/admin.py, itou/files/admin.py, itou/geo/admin.py, itou/invitations/admin.py, itou/job_applications/admin.py, itou/jobs/admin.py, itou/settings_viewer/admin.py, itou/siae_evaluations/admin.py, itou/siaes/admin.py, itou/users/admin.py, itou/utils/admin.py
Réduire et stabiliser le nombre de requête SQL dans l'admin.
Ajout de classes d'admin de base pour propager le comportement partout
Pour `ItouModelAdmin` le gain est moindre qu'attendu (entre 0 et 5 requêtes suivant les cas) car `ForeignKeyRawIdWidget` (les champs listés dans `raw_id_fields`) n'utilise pas l'objet préchargé, chaque widget fait sa propre requête : https://github.com/django/django/blob/613b7ba212d773e8b8a4ecb8236ef575c153a9a6/django/contrib/admin/widgets.py#L195.
J'ai essayé de jouer avec les fonctions de surcharge de admin et les formfield mais je n'ai pas trouvé le moyen d'avoir l'objet édité :'(.
`ItouStackedInline` et `ItouTabularInline` sont plus situationnelles mais permettent de gagner beaucoup sur les pages les plus lourdes.
Bonus : Quelques `list_select_related` …
=> Admin : Préchargement des objets liés lors de l'édition d'un objet et pour les _Inline_

config/settings/base.py, itou/utils/apis/metabase.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-le-93-dans-la-liste-blanche-des-CD-c15824cc3e224bfe9dcddf1ad505a3f1**
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-le-NPS-et-Utilisation-indicateur-aux-TB310-et-TB235-77d91cd68ada4495ad6a7e9bbbd86c6c**
Pour élargir un peu le beta testing des stats CD et pour mener des enquêtes auprès des DDETS LOG.
Avant MEP bien vérifier la réponse d'Annie sur l'ID de TB incorrect pour les formulaires Tally.
=> Stats : Boost

config/settings/base.py, itou/api/redoc_views.py, itou/api/urls.py
Pour encore un peu limiter les possibilités.
=> CSP: ajout de base-uri et suppression de redoc

config/settings/base.py, itou/approvals/admin.py, itou/approvals/enums.py, itou/approvals/migrations/0016_prolongationrequestdenyinformation.py, itou/approvals/models.py, itou/templates/approvals/email/prolongation_request/denied/employer_body.txt, itou/templates/approvals/email/prolongation_request/denied/jobseeker_body.txt, itou/templates/approvals/prolongation_requests/_deny_information_card.html, itou/templates/approvals/prolongation_requests/_status_card.html, itou/templates/approvals/prolongation_requests/deny.html, itou/templates/approvals/prolongation_requests/show.html, itou/utils/templatetags/theme_inclusion.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py, pytest.ini, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/test.txt, tests/approvals/__snapshots__/test_notifications.ambr, tests/approvals/factories.py, tests/approvals/test_notifications.py, tests/approvals/test_prolongation_requests.py, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation_requests.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/En-tant-que-prescripteur-habilit-qui-refuse-une-prolongation-je-justifie-par-crit-les-raisons-de-m-3e3740aa214d42b4936bde7aa39546bf?pvs=4
Obligation réglementaire d’avoir une notification écrite adressée à la SIAE et au bénéficiaire.
- Ajout d'un parcours pour motiver le refus.
- Transmettre cette informations par email à la SIAE et au bénéficiaire
Utilisation de `django-formtools` afin de gérer facilement le découpage et l'embranchement demandé, les tests pourraient être moins verbeux mais ça me semblait prématurée de faire de l'outillage pour 1 cas d'utilisation.
Pas forcément convaincu du fait d'avoir mis les 4 nouveaux champs dans leur propre model, le but était d'éviter d'avoir un préfix `deny_` devant chaque champs et de …
=> Demandes de prolongation : Procédure de refus (motifs et actions proposées)

itou/metabase/tables/job_applications.py, tests/metabase/management/test_populate_metabase_emplois.py
.label makes it crash.
We want the base value, not the french translation anyway. Let the analysts do their translation in a dashboard.
=> metabase.job_applications: Fix contract_type

.github/SECURITY.md, config/urls.py, itou/templates/static/security/security.txt, itou/www/security/urls.py, itou/www/security/views.py, tests/www/security.py
Faciliter la remontée de faille de sécurité en suivant la RFC 9116 [1].
[1] https://www.rfc-editor.org/rfc/rfc9116
=> Ajouter un security.txt

clevercloud/cron.json, itou/approvals/management/commands/prolongation_requests_chores.py, tests/approvals/test_prolongation_requests.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Retrait-de-l-acceptation-automatique-J-30-modif-des-relances-email-046c5b63c30c4a6f9cafdcb285e6ea82?pvs=4
Demandes du groupe projet PASS AI (DGEFP, PE, Réseaux AI) :
- Retirer l’acceptation automatique à J+30
- Reprendre le mail de rappel initialement utilisé à J+7 pour le mettre à J+10 J+20 J+30
La suppression du code de l'auto-acceptation est dans un commit séparé pour facilité le _revert_ si besoin.
=> Retrait de l’acceptation automatique à J+30 + modif des relances email 
