gip-inclusion/les-emplois

config/settings/base.py
Les polices Google ne sont actuellement pas chargées (problème avec la CSP), et seront auto-hébergées avec la prochaine version du thème.
https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1695300407115159?thread_ts=1695292442.473209&cid=CQ6D0QPPZ
=> Retirer fonts.googleapis.com de CSP_STYLE_SRC

Makefile
Cible `run` retirée dans 94db4cbac973724ceb1807bc6ab8a7a665a705d6.
=> Retrait de la cible PHONY run au profit de runserver

Makefile
Plus utile depuis `dev-mac.txt` (3ff5f6182f4f9b55b2061b5d006680809d5fbbfa).
Si `make venv` s’exécute bien (dans `itou_django` et sur votre machine hôte (= Mac)), tout va bien. :)
=> Retirer une condition de la règle venv du Makefile

itou/job_applications/models.py, itou/www/apply/views/submit_views.py, tests/job_applications/test_transfer.py, tests/job_applications/tests.py
Occurs when refusing a job application when 'sender' field is None. Nearly 2k job applications have no sender, mostly with a `prescriber` sender kind This fix is *temporary*, while investigating the real source of the 'leak'. It will/may be removed if we can find a proper way for processing / exterminating 'null' senders.
=> fix: workaround for email sending crash

itou/siae_evaluations/migrations/0001_initial.py, itou/siae_evaluations/models.py
Éviter la confusion avec `Siae.verbose_name`.
=> Définir EvaluatedSiae.verbose_name comme “entreprise contrôlée”

itou/www/dashboard/urls.py, itou/www/dashboard/views.py, tests/www/dashboard/tests.py
Suite de #3010
Cela fait maintenant ~ 2 semaines que la PR a été mergée, il y a peu de chance qu'un utilisateur ait encore une page chargée pointant vers une de ces anciennes URLs.
=> Suppression des vues dépréciées de changement d'organisation

itou/api/applicants_api/serializers.py, tests/api/applicants_api/tests.py
=> fix: first and last name were inverted in applicants API

itou/metabase/tables/job_seekers.py, tests/metabase/management/test_populate_metabase_emplois.py
Tout comme pour la table organisations, candidats devient candidats_v0, ce qui nous permet d'enrichir la table candidat au besoin côté c2 sans avoir à refaire de nombreux indicateurs.
Accompagne cette PR : https://github.com/gip-inclusion/pilotage-airflow/pull/138
=> Renommer la table candidats en candidats_v0 

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/prolongation_requests.py, itou/metabase/tables/prolongations.py, itou/metabase/tables/utils.py, tests/metabase/management/test_populate_metabase_emplois.py
A la demande du métier, ajout de la colonne motif_de_refus sur la tble demandes_de_prolongation
=> Ajout d'une colonne : motif_de_refus sur la table demandes_de_prolongation

.github/workflows/git.yml
Èviter de merger une PR en oubliant de squasher les fixups.
=> github: add check to detect fixup commits

.github/workflows/git.yml
Pour pouvoir mettre ce check comme bloquant l'intégration dans master sans bloquer la merge queue
=> Run git fixup check in merge queue only

.github/workflows/git.yml
Reverts betagouv/itou#3108
Le check ne fonctionne que sur les pull requests et non les merge queues...
Cf https://github.com/betagouv/itou/actions/runs/6377687401/job/17306810374
=> Revert "Run git fixup check in merge queue only"

itou/employee_record/admin.py
Besoin identifié suite au TZ 2982 
L'annexe financière est enregistrée sur la FS mais elle n'est pas utilisée dans les échanges avec l'ASP mais uniquement par les logiciels de gestion utilisant l'API FS.
Il arrive fréquemment d'avoir quelque ticket car l'employeur c'est trompé d'AF ou ne l'a pas remplis, le seul moyen pour modifier une FS est de repasser par le tunnel de création des FS ce qui est plus que problématique, par exemple si la FS a été intégrée elle sera donc renvoyée et reviendra "En Erreur"...
On peux donc se permettre l'édition de ce champs dans l'admin car il n'est que pour nous, donc même si une erreur était faite cela ne changerais rien pour les échanges avec l'ASP et nous serions en mesure de la corriger sans problème.
=> Admin - FS : Autoriser la modification de l'annexe financière

itou/employee_record/models.py, tests/employee_record/factories.py, tests/employee_record/test_archive_employee_records.py, tests/employee_record/test_models.py
On peux se retrouver dans le cas où un employeur nous demande à renvoyer une FS pour un PASS IAE déjà expiré, dans cette situation la FS aura été passée en `ARCHIVED` et ne sera donc plus utilisable, modifier le statut peux suffire mais demande de se coordonner avec l'employeur pour qu'il la complète avant que le cron d'archivage ne repasse, ce n'est pas le plus pratique :).
Ajout d'une nouvelle clause dans `EmployeeRecordQuerySet().archivable()`
=> Fiches salarié : Ne pas archiver celles modifiés récemment

itou/siae_evaluations/emails.py, itou/templates/siae_evaluations/email/to_institution_siaes_submission_frozen_reminder_body.txt, tests/siae_evaluations/__snapshots__/test_management_commands.ambr
On avait apparemment prévu de mettre le nom de l'organisation, alors on met le nom de l'organisation.
=> Contrôle a posteriori: correction du mail de rappel des institutions

tests/siae_evaluations/factories.py
S'il y a un contrôle a posteriori, c'est a priori qu'il existe un Pass.
(et au passage, cela évite un certain nombre d'erreur avec l'option `--fail-on-template-vars` qui se prend les pieds dans https://github.com/betagouv/itou/blob/cab247064fd6e5156c247efb8a8dc592555b2832/itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html#L9)
=> tests: amélioration de la cohérence de EvaluatedJobApplicationFactory

Makefile
L’action GitHub casse de temps à autre.
=> populate_db: Charger les fixtures petit à petit

itou/employee_record/admin.py
Voir #3090 et 83ae104d7
Les utilisateurs de `itou-support-externe` n'ont pas de droits d'édition donc il n'y a pas de champs dans le formulaire.
=> Admin - FS : Correction suite à #3090

itou/users/admin.py, itou/users/admin_forms.py, itou/users/migrations/0001_initial.py, itou/users/models.py, tests/users/test_admin_views.py
Besoin identifié en journée support.
=> Ne pas définir de mot de passe pour les utilisateurs créés via l’admin

itou/metabase/tables/prolongation_requests.py, tests/metabase/management/test_populate_metabase_emplois.py
We should be able to send both denied and approved and pending prolongations.
=> metabase : Corriger les exports de demande de prolongation

itou/templates/dashboard/includes/prescriber_job_seekers_card.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Modifier-la-couleur-de-la-pastille-des-demandes-de-prolongation-traiter-26bb1b3e2d954f5cbe2d24e4ff419d0a
Pole emploi remonte que les conseillers ne voient pas les demandes en attente avec cette couleur
=> Modifier la couleur du badge de nombre de demande de prolongations à traiter

itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py, tests/www/stats/test_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Prio-1-Vermeer-Mettre-en-production-un-tableau-de-bord-priv-Suivi-des-prolongations-pour-les-DDE-a13e85bde14c434e9a2534ae42b8d418**
Les DDETS et DREETS sont demandeuses de telles stats de suivi des prolongations.
=> Stats : Ajout de stats sur les demandes de prolongations pour les DDETS IAE et DREETS IAE

.github/workflows/ci.yml, .github/workflows/review-app-creation.yml, docker-compose.yml
**Carte Notion : https://www.notion.so/plateforme-inclusion/Mettre-jour-Postgres-sur-la-derni-re-version-15-boost-ed9c92020475411f939bae5d6a3e04b6**
Pour info, Clever met à jour la DB de prod demain à 17h.
Mise à jour de performance et de sécurité.
On met à jour  la base de données de dev, on lance les tests, on vérifie en recette. On ne peut pas faire grand-chose de plus.
=> Passage à PostgreSQL 15

itou/templates/dashboard/dashboard.html
C'est plus pratique d'afficher son nom.
=> Tableau de bord: correction du nom de l'admin à contacter

itou/templates/signup/siae_select.html
https://www.notion.so/plateforme-inclusion/Ecran-d-inscription-Modifier-un-message-qui-n-est-pas-adapt-au-cas-des-GEIQ-boost-2069f423014a45ea98316f6f5b1a5128?pvs=4
Le texte parle des correspondants ASP les geiq n’utilisent pas l’ASP
modification du texte pour qu’il colle aux différentes situations
=> Inscription : adapter le message aux GEIQ

itou/users/admin.py
=> Admin: ajout des infos du profil de demandeur d'emploi dans l'admin utilisateur

itou/utils/perms/middleware.py
Pour éviter que des tests échouent de temps en temps, ou que les utilisateurs aient des comportements légèrement différents.
On utilise la date de création comme pour les organisations de prescripteurs.
=> Intergiciel: limitation du hasard

itou/siae_evaluations/admin.py, itou/users/management/commands/sync_group_and_perms.py, itou/utils/perms/middleware.py, tests/conftest.py, tests/siae_evaluations/test_emails.py, tests/siaes/test_import_siae_command.py, tests/status/tests.py, tests/users/test_admin.py, tests/users/test_management_commands.py
- Casser plus vite, qu'une fois de temps en temps, lorsque un de nos test s'attend à un ordre précis et que celui-ci n'est pas spécifié dans le code
- Permet de simuler le cas où l'ordre des lignes physique n'est pas l'ordre des lignes logique.
Ajout d'une _fixture_ `autouse=True` pour patcher la ligne qui va bien dans le code de Django pour que l'ordre par défaut soit `"?"`.
Pour les relecteurs : Je vous ajoute car vous êtes les derniers à être passé sur les bouts de code que je modifie dans `itou` donc vous être normalement bien placés pour voir si un meilleur ordre (ou pas) est possible.
=> tests: Ordre aléatoire pour les requêtes qui n'en spécifie pas

itou/asp/models.py, itou/employee_record/migrations/0010_add_asp_measure_to_unique_constraint.py, itou/employee_record/models.py, tests/employee_record/factories.py
Pour ne plus les confondre avec `siaes.enums.SiaeKind()`
=> Renommage de `asp.models.SiaeKind()` en `asp.models.SiaeMeasure()`

itou/templates/prescribers/card.html
Parce que.
cf https://github.com/betagouv/itou/blob/60dbd7ce4210992f2a6a80198f470090da53f38d/itou/www/prescribers_views/views.py#L18-L26
=> Détail d'une organisation de prescripteur: correction du titre

itou/templates/layout/base.html, itou/utils/staticfiles.py
Les règles CSP empechent l'execution de `htmx`
PR préparant la #3146 
🎃 mise à jour des lib js
🎃 modification de l'import dans `base.html`
🎃 ajout de la règle `"allowScriptTags":false` dans la balise méta `htmx-config` pour limiter l'execution de scripts js non-désirés mais déclenchés par `hx-boost`
🎃 remplacer le `document.ready` par `htmx.onLoad` pour capturer les messages toastés servis via htmx, et le déplacer après le chargement de htmx
=> Mise à jour Htmx de 1.8.2 à 1.9.6, adaptation gabarit de base

itou/approvals/enums.py, itou/approvals/migrations/0016_prolongationrequestdenyinformation.py, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
**Carte Notion :** https://www.notion.so/plateforme-inclusion/URGENT-En-tant-que-prescripteur-habilit-je-peux-refuser-une-prolongation-si-la-dur-e-demand-e-n-e-c6a24797cc994c848b4be1894bf809a4
Actuellement le prescripteur qui n’est pas d’accord avec la durée demandée n’a pas la possibilité de l’indiquer il ne peut que refuser avec un motif qui ne correspond pas à la réalité.
=> Demandes de prolongation : Ajout du motif de refus "La durée de prolongation demandée n’est pas adaptée à la situation du candidat"

itou/templates/layout/breadcrumbs_from_dashboard.html, itou/templates/siaes/edit_siae_breadcrumb.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/breadcrumb-cass-en-tant-que-prescripteur-habilit-je-consulte-un-poste-ouvert-au-recrutement-f65434804be64d1aa3384837825abe91?pvs=4
Parce qu'il est cassé
=> Correction du breadcrumb pour le tableau de bord

itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py, tests/www/stats/test_views.py
**Carte Notion : https://www.notion.so/Ouvrir-le-TB310-aux-DREETS-IAE-50176fe8dc2148b5b06a783a342e0da4**
Parce que !!!
A la mano comme d'habitude pour que il soit dispo rapidement.
Ce système de permissions + injection de tableaux de bord commence à me gêner un tantinet.
J'ai envie de mettre en place un système revisité de permissions, avec des modèles correspondant aux tableaux de bord managés. 
Chaque tableau de bord pourrait être ouvert à des publics de typologies différentes, directement dans l'admin, et désactivé si besoin, tout en suivant les métadonnées et options (Tally, etc) correctement dans ces modèles.
Cela permettrait d'avoir une seule moulinette d'affichage et de ne plus avoir de temps de dev pour ajouter/supprimer ces tableaux.
=> stats : Ajout du dashboard 310 pour les DREETS IAE

itou/approvals/admin.py, itou/users/management/commands/sync_group_and_perms.py, tests/users/test_management_commands.py
Un oubli. C'est quand meme plus sympa d'avoir l'admin disponible.
=> approvals : Add minimalistic admin for CancelledApprovals

itou/static/js/job_autocomplete.js
`autocomplete-source-url` contient déjà le paramètre siae_id
cf
https://github.com/betagouv/itou/blob/c89b352d88ff5cb8652f81243e7572298baa8438/itou/www/siaes_views/forms.py#L302
=> static: simplification JS

itou/templates/apply/email/cancel_body.txt, tests/job_applications/tests.py
Éviter d'envoyer des éléments de liste vides dans l'email.
=> Candidature annulée: amélioration de l'email envoyée

.env.template
🎯 ajouter les variables d'environment minimum pour faire fonctionner `itou` en local :
* `PGHOST`, `PGUSER`, `PGPASSWORD` pour accéder à la ligne de commande `psql` si `postgres` est hébergé dans un contener `docker`
* `S3_STORAGE_BUCKET_NAME` pour ne pas faire planter `itou` (`s3_upload` not defined) sur les formulaires de téléversement.
* mise à jour de `env.template`
=> Fichier de variables d'environnement minimaliste

itou/static/css/itou.css, itou/static/js/utils.js, itou/templates/apply/submit/application/eligibility.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/application/geiq_eligibility.html
Le support des fonctionnalités du site sans JavaScript demande beaucoup d’efforts de développement et n’est pas dans les objectifs de l’équipe. De nombreuses fonctionnalités du site nécessitent JavaScript et n’ont pas de mode dégradé. Arrêtons de prétendre que le site pourrait fonctionner sans JavaScript, et simplifions le code.
=> Retirer js-display-if-javascript-enabled

config/settings/base.py, itou/approvals/admin.py, itou/approvals/notifications.py, itou/files/models.py, itou/templates/approvals/email/prolongation_request/created_body.txt, itou/templates/approvals/prolongation_requests/show.html, itou/utils/storage/s3.py, itou/www/apply/views/submit_views.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py, tests/approvals/__snapshots__/test_notifications.ambr, tests/conftest.py, tests/files/tests.py, tests/www/apply/test_submit.py, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation.py, tests/www/approvals_views/test_prolongation_requests.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Am-liorer-la-compatibilit-de-l-envoi-des-fichiers-c4cfcdb49db64ebca1b80fec141539ba**
Sécurité.
=> Valider les accès aux bilans des demandes de prolongation

itou/siae_evaluations/admin.py, itou/siae_evaluations/migrations/0012_evaluatedadministrativecriteria_proof_url_to_proof.py, itou/siae_evaluations/models.py, itou/templates/siae_evaluations/includes/criterion_validation.html, itou/templates/siae_evaluations/includes/list_item.html, itou/templates/siae_evaluations/institution_evaluated_job_application.html, itou/templates/siae_evaluations/siae_upload_doc.html, itou/www/siae_evaluations_views/urls.py, itou/www/siae_evaluations_views/views.py, tests/siae_evaluations/factories.py, tests/siae_evaluations/test_models.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py, tests/www/siae_evaluations_views/test_views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Am-liorer-la-compatibilit-de-l-envoi-des-fichiers-c4cfcdb49db64ebca1b80fec141539ba**
`TestProlongationReportFileView` https://github.com/betagouv/itou/pull/3193)
=> Migrer EvaluatedAdministrativeCriteria.proof_url vers proof

itou/www/siae_evaluations_views/views.py, tests/www/siae_evaluations_views/test_views.py
https://itou.sentry.io/issues/4553165118/
Et ça n'est pas très cher. Si cela se complique, on pourra toujours décider de renvoyer une 404.
=> Contrôle a posteriori: autoriser les admins à vérifier la vue du calendrier de la campagne

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Modifier-le-lien-du-TB-Public-stats-des-emplois-b960f82bc7cf43f4a56a89d4121a9bab?pvs=4
Ajout de l'ID de dashboard metabase 236 à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
Suppression de l'ancien ID 63
=> Ajout de l'ID 236 de dashboard metabase

config/settings/base.py
Il logge toutes les exceptions via un logger.exception qui envoie trop de choses à Sentry.
Autant laisser Sentry gérer les exceptions non-gérées.
=> settings: suppression de l'intergiciel ErrorLoggingMiddleware

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Modifier-le-TB-vers-lequel-renvoie-le-lien-stat-de-la-page-d-accueil-Pilotage-2a44f7a77de14228911e3bb43904f04a?pvs=4
Ajout de l'ID de dashboard metabase 63 à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
Tri de la liste au passage
=> Ajout de l'ID 63 de dashboard metabase et tri de la liste

tests/conftest.py, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_display.py, tests/www/invitations_views/test_prescriber_organization.py, tests/www/invitations_views/test_siae_accept.py
Cf https://github.com/pytest-dev/pytest-django/pull/1076
=> Correctif de la fixture `_template_string_if_invalid_marker`

itou/metabase/tables/siaes.py, tests/metabase/management/test_populate_metabase_emplois.py, tests/metabase/test_siaes.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Ajouter-une-colonne-d-partement_c1-la-table-structures-b7c78894ae4b4aa8bdf5aef5c31f2c2b
Actuellement la table `structures` récupère uniquement le département/région de la structure mère. De ce fait, si une antenne est localisée dans le 28 alors que la structure mère se trouve dans le 27 : c’est le 27 qui sera dans la table au lieu du 28.
=> metabase - Structures : Ajout des champs adresses renseignées par l'utilisateur

itou/templates/approvals/printable_approval.html, itou/templates/layout/base_printable.html, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_display.py
Car personne ne semble vouloir les corriger.
Lancer `pytest -v tests/www/approvals_views/test_detail.py` résulte en erreur car des variables ne sont pas définies, je ne sais pas pourquoi elle ne sont pas sur la CI mais c'est peut-être dû au fait que ça soit des `TestCase` :shrug:.
=> Templates : Correction de variables manquantes

itou/jobs/models.py, itou/www/autocomplete/views.py, itou/www/companies_views/forms.py
- La logique d'exclusion posait soucis dans le cas de l'édition où on ne pouvait plus retrouver le poste existant vu qu'il existait en base pour la SIAE
- Mais comme la contrainte n'existe plus depuis #1888 et qu'on souhaite en fait autoriser la création de plusieurs fiches de poste pour le même code ROME (typiquement pour utiliser des offres situées à différents endroits), c'est plus simple de supprimer complètement cette logique et simplifier le code.
=> Création/modification des fiches de postes: possibilité de choisir un poste (code ROME) déjà existant

itou/approvals/admin.py, itou/job_applications/models.py, tests/job_applications/tests.py
Le drapeau `create_employee_record` est levé pour toute les candidatures créées lors de la reprise de stock des AI, mais si une prolongation/suspension est faite alors ce drapeau ne devrait plus être pris en compte car la nouvelle date de fin du PASS IAE **doit** être envoyé à l'ASP sinon les employeurs se retrouve bloqué au moment de la déclaration d'heure.
Pour le moment je limite aux prolongations car ce sont les plus problématiques mais aussi les moins nombreuses, j'espère ne pas avoir à gérer les suspensions (ainsi que d'autre problème de ce type) avec #3218 .
Nombre de nouveaux résultats retournés par la fonction `eligible_as_employee_record` et qui :
- Prolongation uniquement : 6042 pour 430 SIAE impactées
- Prolongation et Suspension : 41535 pour 625 SIAE impactées
=> Fiches salarié : Outrepasser `create_employee_record` si une prolongation existe

itou/metabase/tables/siaes.py, tests/metabase/management/test_populate_metabase_emplois.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-dans-la-table-structure-c2-les-mails-d-authentifications-code-NAF-des-SIAE-dans-c2-53e3df5ade37425bae73edc60868d85f**
Pour que nos Bizdev aient une source supplémentaire d'emails pros pertinents pour mieux cibler les responsables de chaque SIAE. Avant cette PR ils pouvaient uniquement cibler les membres admin d'une SIAE donnée, qui en pratique ne correspondent pas vraiment aux responsables de la SIAE. L'email d'authentification fourni par l'ASP devrait permettre un meilleur ciblage.
=> Metabase : Ajout de trois nouveaux champs (code NAF, email public et email d'authentication) à la table `structures`

itou/employee_record/serializers.py, tests/employee_record/__snapshots__/test_transfer_employee_records.ambr, tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr, tests/employee_record/test_serializers.py, tests/employee_record/test_transfer_employee_records.py, tests/employee_record/test_transfer_employee_records_updates.py
[LES-EMPLOIS-PROD-109](https://itou.sentry.io/issues/4458291355/)
[LES-EMPLOIS-PROD-17N](https://itou.sentry.io/issues/4573311262/)
=> Fiches Salarié : Ne plus casser au moment de la sérialisation pour le pays de naissance et la commune

itou/job_applications/models.py, tests/job_applications/test_eligibility.py
Cas vu au support, suite à un doublon de PASS IAE celui enregistré sur la FS et celui du candidat ne sont plus les mêmes.
=> Fiches salarié : Permettre de les renvoyer quand le PASS IAE ne correspond plus

itou/templates/approvals/includes/list_card.html, tests/www/approvals_views/test_list.py
https://www.notion.so/plateforme-inclusion/En-tant-que-SIAE-je-visualise-les-dates-du-PASS-IAE-sur-les-cartes-profil-salari-s-8a6d3df8d9e84397a89508dea03d5678
Nous souhaitons afficher les dates du PASS IAE sur les cartes “profil salarié”
=> Ajout des dates du PASS IAE sur les cartes « profil salariés »

itou/templates/apply/includes/list_card_body_siae.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/approvals/includes/job_description_list.html, itou/www/apply/views/list_views.py, tests/www/apply/__snapshots__/test_list.ambr, tests/www/apply/test_list.py
[](https://www.notion.so/plateforme-inclusion/Refonte-carte-candidature-prescripteur-En-tant-que-prescripteur-je-veux-visualiser-les-infos-cl-s-0935119b28b04121a626476ff0e46a91?pvs=4)
améliorer la lisibilité des informations
* duplication des templates de `apply.views.list_views.list_for_siae`
* enrichissement du template `approvals/includes/job_description_list.html`
* enrichissement de la vue `apply.views.list_views.list_for_prescriber`, ajout des critères administratifs
vue prescripteur habilité
vue orienteur
=> Refonte carte candidature vue prescripteur

config/urls.py, itou/utils/redirect_legacy_views.py, tests/utils/test_redirect_legacy_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Renommer-le-mod-le-Siae-b2eae354455a43a9bdef969c4ffa0d73?pvs=4
Éviter que des urls soient cassés sur les sites des SIAEs
=> Mise en place d'une redirection permanente pour les urls commançant pas SIAE

itou/approvals/admin.py, itou/approvals/models.py, itou/companies/admin.py, itou/utils/admin.py, tests/approvals/test_admin.py
demande support : https://itou-inclusion.slack.com/archives/C01181Y04LT/p1698703924145149
J'aimerais bien ajouter le champ en question aussi sur le PASS, mais je n'arrive pas à réutiliser l'annotation `with_assigned_company()` à cause de la surcharge de `get_objet()` mise en place dans `ItouModelAdmin`.
Une idée ?
=> Lister les PASS IAE d'une SIAE sur la page d'admin

itou/www/companies_views/views.py, tests/www/siaes_views/test_job_description_views.py
Sinon la suppression de la localisation dans le formulaire n'est pas prise en compte.
=> Edition de fiche de poste: permettre la suppression de la localisation (pour réutiliser celle du siège, par défaut)

tests/conftest.py
https://github.com/pytest-dev/pytest-django/pull/1076 a été mergée et déployée dans pytest-django 4.6.0 mergée dans #3302
=> conftest: suppression de la solution de contournement

itou/templates/apply/process_accept.html, itou/templates/apply/submit/hire_confirmation.html
Le CSS est déjà géré par le thème.
Et idéalement le CSS devrait de toutes façons être rajoutés dans le `block` "extra_head"
=> form media: ne pas réinclure de CSS pour les champs Select2 des formulaires

itou/asp/models.py, itou/templates/employee_record/includes/create_step_2.html, itou/www/autocomplete/views.py, itou/www/employee_record_views/forms.py, tests/www/autocomplete/tests.py, tests/www/employee_record_views/test_create.py
Pour pouvoir supprimer jQuery UI.
https://www.notion.so/plateforme-inclusion/C1-Suppression-de-jQuery-UI-680d46411c3f4972ad1c113765924453?pvs=4
=> Saisie adresse fiche salarié: utilisation du widget Select2 pour la commune

itou/metabase/tables/siaes.py, itou/metabase/tables/utils.py, tests/metabase/management/test_populate_metabase_emplois.py
Afin de simplifier la vie des data analystos et éviter de casser plusieurs indicateurs metabase on créé une table structures_v0 côté emplois pour créer une table structures sur dbt. 
[PR côté C2](https://github.com/gip-inclusion/pilotage-airflow/pull/189)
=> Création d'une table structures_v0

config/settings/base.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Ajouter-CD-18-la-liste-blanche-des-conseils-d-partementaux-pour-acc-der-aux-TB330-et-TB346-24510c2b7c234efe97610e61f7b26e6f**
Parce que les stats développées pour les CD commencent à avoir du succès.
=> Stats : Ajout du département 18 à la liste blanche des CD (Conseils Départementaux)

itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py, tests/www/stats/test_views.py
**Carte Notion : ** : https://www.notion.so/plateforme-inclusion/Suivi-des-cartes-b3082fffe3f34eaea8fff8ba69338005?p=88acffe3b0b34aa6973686c9f64ac5e2&pm=c
Les DDETS et DREETS avaient accès aux TB privé de suivi de demandes de prolongation mais pas la DGEFP, nous corrigeons ici cet oubli.
[PR DDETS/DREETS](https://github.com/betagouv/itou/pull/3099)
=> Stats : Ajout de stats sur les demandes de prolongations pour la DGEFP

itou/templates/employee_record/list.html, itou/www/employee_record_views/views.py, tests/www/employee_record_views/test_list.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/UX-UI-Harmoniser-les-Aucun-0-r-sultat-a7243f4552664bb586dd72d04ed749a5?pvs=4
Sur la liste des fiches salarié (ASP) quand il n’y a pas de résultats, harmonisation de l'affichage.
Remplacement de "Aucun résultat" par "0 résultat" comme sur les autres listes.
Avant / Apres
=> UX: Harmonisation de l'affichage des 0 résultat sur les fiches salarié (ASP) 

itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/application/resume.html, itou/templates/apply/submit/create_or_update_job_seeker/step_base.html, itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/approvals/pe_approval_search.html, itou/templates/approvals/pe_approval_search_found.html, itou/templates/approvals/pe_approval_search_user.html, itou/templates/invitations_views/create.html, itou/templates/prescribers/edit_organization.html, itou/templates/siaes/create_siae.html, itou/templates/siaes/edit_job_description.html, itou/templates/siaes/edit_job_description_details.html, itou/templates/siaes/edit_job_description_preview.html, itou/templates/siaes/edit_siae.html, itou/templates/siaes/edit_siae_description.html, itou/templates/siaes/edit_siae_preview.html, itou/templates/siaes/includes/_siae_details.html, itou/templates/siaes/job_description_card.html, itou/templates/siaes/select_financial_annex.html, tests/www/prescribers_views/__snapshots__/test_edit.ambr
**Carte Notion :** https://www.notion.so/plateforme-inclusion/ui-harmonisation-de-zone-de-boutons-de-formulaire-80c201142e8b454f975e05855648c858?pvs=4
Pour harmoniser la mise en forme UI/UX des zones de boutons dans les formulaires
Globalement
- respect des dimensions et couleurs
- respect de la mise en forme (surtout pour le bouton "retour")
- respect du positionnement par l'alignement des boutons à droite (sauf pour le bouton "retour")
- respect de la mise en forme responsive (demi-largeur ou full largeur selon les cas)
Exemple de mise en forme recommandée https://betagouv.github.io/itou-theme/layout-itou-form-simple.html
Afin de ne pas faire une trop grosse PR, je referais surement une ou plusieurs PR pour les formulaires restants
En passant, harmonisation de certainn message d'alerte …
=> Harmonisation de la zone de boutons dans les formulaires

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/job_descriptions.py, tests/metabase/management/test_populate_metabase_emplois.py
Fil Slack : https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1694162133414989
Pour permettre d'identifier les fiches de poste CVG et PHC dans le cadre des travaux avec convergence.
=> Ajout de la colonne type de contrat à la table fiches de poste

itou/utils/staticfiles.py
Suite au changement d'adresse de repository du thème
=> Mise a jour de l'url statique de l'import du thème itou

itou/templates/apply/includes/siae_hiring_actions.html, tests/www/apply/test_process.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/BUG-Disparition-du-bouton-Mettre-en-attente-sur-certaines-candidatures-a12459018b48468487a07214d13ea48a
Pour que le comportement soit plus simple (c'est un cas de figure qui n'a pas besoin de cas particulier)
=> Permettre de mettre en liste d'attente des candidatures à l'étude nécessitant un diagnostic d'éligibilité

itou/templates/layout/_footer.html, itou/templates/layout/_header_nav_primary_items.html, itou/templates/layout/base.html
Des liens d'aide sont présents : dans le header, dans le footer et dans un sticky widget. 
L'objectif est d'analyser leurs utilisation
Ajout d'evenements Matomo 
```
data-matomo-category="help"
data-matomo-action="clic"
```
puis, selon le lien et sa postion : `{position}_{destination}`
où `position` =  `header` ou `footer` ou `sticky`
et `destination` = `documentation` ou `comprendre_lieae`
exemple : `data-matomo-option="header_documentation"`
=> [STATS] analyser l'usage des liens d'aide

itou/static/js/matomo.js, itou/templates/apply/list_of_available_exports.html, itou/templates/apply/submit/application/resume.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/approvals/pe_approval_search_found.html, itou/templates/companies/card.html, itou/templates/companies/edit_siae_preview.html, itou/templates/companies/includes/_card_siae.html, itou/templates/companies/job_description_card.html, itou/templates/dashboard/includes/siae_job_applications_card.html, itou/utils/templatetags/matomo.py, tests/utils/test_templatetags.py, tests/www/companies_views/test_views.py
+ quelques fixes au passage isolés dans leur propres commits
* réduire la longueur de code à ajouter dans les gabarits pour les nouveaux evenements matomo
* enregistrer les evenements liés aux candidatures
🦺 ajout du templateag `matomo-attributes`
🦺 modification de `matomo-js` pour considerer soit les liens contenant la class `matomo-event` (legacy mode), soit l'attribut `data-matomo-event=true`
=> [MATOMO] ajout d'un templatetag et utilisation sur les candidatures

clevercloud/crons/populate_metabase_emplois.sh, clevercloud/crons/populate_metabase_matomo.sh, itou/metabase/db.py, itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/management/commands/populate_metabase_fluxiae.py
Les DAGS du pilotage mettant à jour les tables sont lancés via les emplois. [Dans cette PR](https://github.com/gip-inclusion/pilotage-airflow/pull/198) nous avons divisé en deux dags les mises à jours qui doivent être faites quotidiennement (données issues des emplois) et les maj qui doivent être faites de façon hebdomadaire (flux IAE).
Les modifications de cette PR ont pour but de prendre cela en compte côté C1
=> Modification d'un ancien DAG + nouveau DAG pilotage

.github/pull_request_template.md, CHANGELOG_breaking_changes.md
Pour permettre aux développeurs intervenant occasionnellement sur notre projet de conserver un environnement de travail stable (ou de le réparer plus rapidement).
=> Ajout d'un journal des changements techniques majeurs

itou/templates/companies/includes/_list_siae_actives_jobs_row.html, tests/www/search/tests.py
C'est une information utile (et cela permet de supprimer une `pytest.mark.ignore_template_errors`)
=> Fiche de poste: correction de l'affichage de la ville d'une fiche de poste en l'absence de l'information

itou/approvals/management/commands/send_approvals_to_pe.py, itou/approvals/models.py, tests/approvals/test_notify_pole_emploi.py
On n'utilise jamais le paramètre `at`.
=> Simplification de la fonction notify_pole_emploi

itou/employee_record/management/commands/sanitize_employee_records.py
Pour ne pas gâcher du temps pour rien.
Je ne fait pas un `filter()` avec seulement les états qui font que `can_be_disabled is True` pour éventuellement choper les cas anormaux plus tard en mode "C'est bizarre d'avoir autant de FS toujours orphelines" (#monderéel).
=> Fiches salarié : Amélioration de performance pour le nettoyage des FS orphelines

itou/job_applications/models.py, itou/templates/employee_record/add.html, itou/templates/employee_record/includes/_status.html, itou/templates/employee_record/includes/create_step_1.html, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/list.html, itou/templates/employee_record/summary.html, itou/www/employee_record_views/forms.py, itou/www/employee_record_views/urls.py, itou/www/employee_record_views/views.py, tests/job_applications/tests.py, tests/www/employee_record_views/__snapshots__/test_add.ambr, tests/www/employee_record_views/test_add.py, tests/www/employee_record_views/test_list.py
**Carte notion :** https://www.notion.so/plateforme-inclusion/Fiche-salari-En-tant-qu-employeur-je-peux-cr-er-une-fiche-salari-sans-que-celle-ci-soit-dans-Nou-85e0190b04754325a8e1106e8f6eefad?pvs=4
Permettre la création d’une FS par l’employeur sans quelle soit obligatoirement dans “Nouvelle”
⇒ Philosophie : Les emplois transfert ses données vers l’ASP, ce n’est pas au système mais à l’employeur de choisir ce qu’il veux envoyer vers l’ASP. Les FS sont de la périphérie et pas centrale pour les emplois
⇒ Autonomise l’employeur pour toute les opérations de création de FS : changement de SIRET, embauche avant l'interopérabilité, drapeau "Création de fiche salarié" pour le stock AI, etc
⇒ Moins de logique métier chez nous, ce qui devrais permettre de plus facilement renvoyer la balle vers le …
=> Fiches salarié : Parcours de création autonome

itou/templates/employee_record/list.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/BOOST-Pr-venir-les-SIAE-du-d-lai-d-int-gration-dans-l-Extranet-IAE-de-l-ASP-bb08521f3e9c4bfbaa61546c0ac1499b?pvs=4
Certaines SIAE s’inquiètent de ne pas voir dans l’Extranet IAE 2.0 de l’ASP leurs fiches salariés et/ou les mises à jours de la date de fin
=> Prévenir les SIAE du délai d’intégration dans l’Extranet IAE de l’ASP

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Mettre-en-prod-le-TB287-public-ETP-88404324d3044e918fe12fb30d1a086a?pvs=4
Ajout de l'ID de dashboard metabase 287 à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
=> Ajout de l'ID 287 de dashboard metabase

itou/templates/signup/prescriber_check_already_exists.html, tests/www/signup/test_prescriber.py
Moins de tests avec `ignore_template_error` et un code plus clair.
=> Nettoyage d'une référence inutile à une variable inexistante

itou/metabase/management/commands/populate_metabase_emplois.py, tests/metabase/management/test_populate_metabase_emplois.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Technique-DNRY-Injecter-la-donn-e-type-prescripteur-directement-depuis-le-C1-1cd4e97f65be49c6afa7afd6149d0167 et https://www.notion.so/plateforme-inclusion/Uniformiser-les-labels-prescripteurs-dans-les-TB-efedd3d00a984a1c83c81cb79a6ae01d**
Les analystes ont hardcodé les différents type de prescripteur ici ([lien](https://github.com/gip-inclusion/pilotage-airflow/blob/main/dbt/seeds/prescripteurs_habilites/nom_prescripteur.csv)) et ici ([lien](https://github.com/gip-inclusion/pilotage-airflow/blob/main/dbt/seeds/prescripteurs_habilites/organisations_libelles.csv)). Bref, ce jeu de données initialement du C1 est au final présent en 3 exemplaires au lieu d'un seul o_O.
Il est temps de revenir à un seul exemplaire propre …
=> Metabase : Ajout du référentiel du type prescripteur (`c1_ref_type_prescripteur`)

itou/job_applications/models.py, tests/conftest.py, tests/www/apply/test_submit.py
Le commit d8ef8d0c4 n'était au final pas suffisant, certains tests cassaient quand lancé dans le docker `itou_django`.
J'ai testé de modifier l’expression régulière de `URLValidator` par différente manière mais sans effet.
=> Tests : Faire en sorte qu'ils passent depuis environnement docker

Makefile
Sinon, il faut remarquer que rien d'autres n'a échoué et qu'il n'y a pas le message "No changes detected".
=> Makefile: ajout d'un message pour clarifier l'absence d'une migration

.gitignore
Le téléchargement de la dernière image de la base de prod peut-être stockée dans le répertoire `backups`.
Ignorer ce répertoire 
A discuter en équipe
=> [gitignore] repertoire backups

itou/utils/apis/metabase.py
Suite a des[ modifications côté C2](https://github.com/gip-inclusion/pilotage-airflow/pull/202), Correction de la valeur PE_PRESCRIBER_FILTER_VALUE
=> Correction de la valeur PE_PRESCRIBER_FILTER_VALUE

itou/templates/approvals/declare_prolongation.html, itou/www/approvals_views/views.py, tests/www/approvals_views/test_prolongation.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/R-gul-PASS-AI-Prolonger-de-1-mois-les-PASS-IAE-concern-s-par-une-demande-de-prolongation-tardive--133fbe5d5d1f42caa46542dc4f9beb6a?pvs=4
1. éviter les relances support sur le traitement des renouvellements de PASS AI de fin novembre 
2. éviter la perte des aides aux postes pour les prolongations refusées 
Ajout d'une bannière d'information lors de la prévisualisation de la demande de prolongation
⚠️ ne concerne que les AI 
⚠️ pas de limite de temps, mais potentiellement à démonter fin 2023
=> [PASS IAE AI] message pour les pass arrivant à expiration dans moins de 30 jours

Makefile
cassé dans 2c77b028cf36ec6ad467ad1641b40f8bc90ddd7a
En cas de migration manquante, le `echo` se lance bien mais le script se termine alors sur un exit code 0 et `make quality` passe...
=> Makefile: correction de la vérification des migrations

itou/approvals/admin.py
[**Carte Notion : **](https://www.notion.so/plateforme-inclusion/R-gul-PASS-AI-Prolonger-de-1-mois-les-PASS-IAE-concern-s-par-une-demande-de-prolongation-tardive--6e6696e99bcf45869f6802dcdafc0c50?pvs=4)
rechercher manuellement les demandes de prolongations refusées pour les AI pour ajuster manuellement la durée du PASS. 
suite de #3377 
* ajout de 2 filtres dans l'admin
=> [PASS IAE AI] filtrer les demandes refusées par date pour les AI

itou/templates/approvals/declare_prolongation.html, tests/www/approvals_views/test_prolongation.py
[carte notion](https://www.notion.so/plateforme-inclusion/R-gul-PASS-AI-Prolonger-de-1-mois-les-PASS-IAE-concern-s-par-une-demande-de-prolongation-tardive--36b86457aab94b399b8c5d003d300bf2?pvs=4)
simplification du message pour une meilleure compréhension
=> [PASS IAE AI] CORRECTION MESSAGE pour les pass arrivant à expiration dans moins de 30 jours

itou/templates/approvals/includes/status.html, itou/www/approvals_views/views.py, tests/www/approvals_views/__snapshots__/test_detail.ambr, tests/www/approvals_views/test_detail.py
https://www.notion.so/plateforme-inclusion/Ajout-d-information-dans-le-PASS-IAE-pour-une-Prolongation-en-cours-7a4757d5d430431f931cab25177ea355
Les utilisateurs ont besoin de voir les informations ajoutées pour suivre correctement leur demande de prolongation.
Ajouter des informations dans l’encart du PASS IAE, visible par tous (SIAE, PH, Candidat).
On on profite pour réaligner les textes qui étaient décalés via l'usage de la classe `ps-3`.
=> Ajout d’information dans le PASS IAE pour une Prolongation en cours

itou/analytics/approvals.py, itou/analytics/migrations/0001_initial.py, itou/analytics/models.py, itou/approvals/management/commands/send_approvals_to_pe.py, itou/approvals/migrations/0001_initial.py, itou/approvals/migrations/0017_cancelledapproval.py, itou/utils/apis/enums.py, tests/analytics/test_approvals.py, tests/approvals/test_notify_pole_emploi.py
Pour différencier les PASS prêts à être envoyés des PASS pending par manque d'infos ou car commençant dans le futur.
Plutôt que de rajouter un statut POSTPONED et devoir gérer les transitions de PENDING (état par défaut) à POSTPONED puis de POSTPONED vers PENDING il était plus simple de rajouter un état READY indiquant que toutes les infos sont bien disponibles et que le PASS peut être envoyé.
=> Notification des PASS IAE à pole emploi: ajout du statut READY

itou/approvals/admin.py
suite #3381 
* réagencement des colonnes pour faciliter le traitement par le support
* filtre sur `created_at` au lieu de `processed_at`
=> [PASS IAE AI] filtrer les demandes refusées par date pour les AI (part2)

config/settings/base.py
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Publier-le-TB325-Analyse-autour-des-conventionnements-en-IAE-fc937fa77d2c4249a5356abf70875a72?pvs=4
Ajout de l'ID de dashboard metabase à la constante `PILOTAGE_DASHBOARDS_WHITELIST`
=> Ajout de l'ID 325 de dashboard metabase

itou/approvals/management/commands/send_approvals_to_pe.py, tests/approvals/test_notify_pole_emploi.py
Comme on a 140 000 PASS à renvoyer, cela risque de prendre beaucoup de temps avec des batchs de 10.
=> PASS IAE: augmentation de la taille des batchs des envois à pole emploi

itou/users/management/commands/pe_certify_users.py, tests/users/__snapshots__/test_management_commands.ambr
Pour ne pas avoir de données personnelles dans les logs
=> Certification PE: suppression de données personnelles des logs

itou/templates/includes/members.html, itou/www/companies_views/views.py, itou/www/institutions_views/views.py, itou/www/prescribers_views/views.py, tests/companies/test_models.py, tests/institutions/tests.py, tests/prescribers/tests.py, tests/www/companies_views/test_views.py, tests/www/institutions_views/test_views.py, tests/www/prescribers_views/test_members.py
https://www.notion.so/plateforme-inclusion/En-tant-que-membre-du-tableau-de-bord-de-mon-entreprise-je-souhaite-tre-inform-de-l-utilit-d-avoi-337e6d4b8cee4feca0a25789b37bbf8f?pvs=4
- Beaucoup de sollicitations au support pour nommer un autre admin quand l’unique admin de la structure l’a quittée
- Solution trouvée lors d’un atelier en équipe  https://www.notion.so/plateforme-inclusion/Nouvelle-r-gle-pour-d-signer-les-admin-par-d-faut-755915e399294537b8a4d27988bede45
Informer les utilisateurs par le biais d'un message d'informations présent uniquement s'il y a plusieurs membres actifs mais seulement un administrateur.
- L'implémentation des tests a mis en évidence que la méthode `MembershipQuerySet.active` n'est employée que sur les entreprises. Les membres des prescripteurs et institutions …
=> Message d’information pour inciter les membres d’une organisation à avoir plusieurs administrateurs

itou/utils/apis/pole_emploi.py
Le champ `start_at` est obligatoire.
=> Envoi PASS à pole emploi: simplification

itou/approvals/management/commands/send_approvals_to_pe.py
Beaucoup de PASS à envoyer et aucune raison de vouloir garder des petits batchs (tant que les crons ne se marchent pas dessus).
=> PASS IAE: nouvelle augmentation de la taille des batchs des envois à pole emploi

itou/templates/dashboard/edit_user_email.html, itou/templates/dashboard/edit_user_info.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Reprise-de-stock-civilit-Rendre-obligatoire-la-civilit-du-candidat-afa04f9bd69b4311b6ef786f048947bb?pvs=4
Titre plus cohérent avec l'entrée du menu déroulant "Mon espace" qui utilise "Modifier mon profil".
=> Tableau de bord: modification du titre de la page de modification du profil

itou/utils/staticfiles.py
Mise à jour du thème vers la v1.1.3
Pour ajouter le `.btn-partner` 
https://zeroheight.com/85c89893b/p/207551-buttons/t/95959d
=> Maj du theme itou vers la v1.1.3

CHANGELOG.md
changelog sprint 76 - 20.11-2023 / 03.12.2023
=> changelog sprint 76

itou/www/apply/views/submit_views.py, tests/www/apply/test_submit.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/D-claration-d-embauche-rapide-pour-un-demandeur-d-emploi-ayant-eu-un-PASS-il-y-a-moins-de-2-ans-1e1521f59e894b5fa5ffdea6da310b60?pvs=4
Dans ce cas seul un prescripteur habilité peut recréer un PASS et un employeur ne pourra pas aller au bout du parcours:
il faut donc lui mettre un message clair plutôt que la dernière étape ne plante.
=> Déclaration d'embauche: gestion des demandeurs d'emploi ayant eu un PASS dans les 2 dernières années

itou/templates/dashboard/edit_user_info.html, itou/templates/dashboard/includes/edit_job_seeker_info_form.html, itou/www/dashboard/forms.py, itou/www/dashboard/views.py, tests/openid_connect/france_connect/tests.py, tests/openid_connect/pe_connect/tests.py, tests/www/dashboard/__snapshots__/tests.ambr, tests/www/dashboard/tests.py, tests/www/signup/test_job_seeker.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Reprise-de-stock-civilit-Rendre-obligatoire-la-civilit-du-candidat-afa04f9bd69b4311b6ef786f048947bb?pvs=4
:warning: Seuls les 4 derniers commits sont à relire, les autres faisant parti de la PR #3407
Les nouveaux candidats doivent remplir ce champs à l'inscription mais on a 390k candidats sans civilité.
=> [Reprise de stock civilité] Rendre obligatoire la civilité du candidat

itou/www/companies_views/views.py, tests/www/companies_views/test_job_description_views.py, tests/www/companies_views/test_views.py
Les autres postes [ne s'affichaient pas](https://itou-inclusion.slack.com/archives/C0412CTV63D/p1701786817678629) et on préfère faire peu de requêtes à la DB.
=> Vue "Description du poste": correction de l'affichage des autres postes + réduction requêtes

itou/templates/apply/process_refuse.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/POC-Modifier-le-motif-Pas-de-poste-disponible-a016e0eb1e884e498cd7c051f511901f?pvs=4
Afficher un tooltip sur le refus "pas de recrutement en cours"
Afficher un `alert-info` quand ce motif de refus est sélectionné.
Ajout script.
formulaire au chargement
tooltip au survol
motif selectionné
=> [CANDIDATURE] tooltip sur le motif de refus

itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/check_job_seeker_info_for_hire.html
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/retirer-des-boutons-inutile-qui-risque-de-faire-sortir-l-utilisateur-du-parcours-boost-9c7eaa761fbb46a582d8f76a0029983e?pvs=4
- supprimer les boutons "Revenir à la recherche" lors de l'enregistrement d'une candidature
- supprimer le boutont "Retour au tableau de bord" lors la déclaration d'une embauche
Enregistrer une candidature
Déclarer une embauche
=> Retirer des boutons inutile qui risque de faire sortir l’utilisateur du parcours

itou/templates/approvals/suspension_action_choice.html, tests/www/approvals_views/test_suspend.py
typo in action_name, fix #3327
ajout d'un test sur les action_name  dans le gabarit
=> [FIX #3327] approvals : annuler une suspension

itou/templates/dashboard/includes/stats.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Supprimer-les-tags-nouveaux-de-quelques-tableaux-de-bord-priv-s-sur-c1-10531ae97c6d4e00ae9ddf2780ccdadb
TAG Nouveau qui apparaît sur plusieurs TDB mais qui ne sont plus nouveaux
=> templates.stats: Remove some "Nouveau" badges

tests/employee_record/test_models.py
Test en échec : https://github.com/gip-inclusion/les-emplois/actions/runs/7126695842/job/19405112701?pr=3438
On l'avais déjà vu mais compliqué de reproduire sans le _seed_ de `pytest-randomly` ;).
=> Tests : Correction de la _flakyness_ pour `EmployeeRecordModelTest.test_archivable`

itou/templates/includes/pagination_for_title.html, itou/templates/search/siaes_search_results.html, tests/www/search/tests.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Mettre-en-coh-rence-le-titre-de-la-page-de-r-sultats-du-moteur-de-recherche-avec-le-contenu-recherch-526682b5fa47459b81e5d39ad5962720?pvs=4
Mettre en cohérence le titre de la page de résultats du moteur de recherche avec le contenu recherché
=> Mise à jour des titres de l'écran de recherche des emplois

itou/templates/apply/includes/job_application_prior_action.html, itou/templates/apply/process_details.html, tests/www/apply/test_process.py
[GEIQ : afficher les informations associées a(ux) action(s) préalable(s) à l’embauche dans la page candidature pour les candidats et prescripteurs](https://www.notion.so/plateforme-inclusion/GEIQ-afficher-les-informations-associ-es-a-ux-action-s-pr-alable-s-l-embauche-dans-la-page-ca-1a8aba474fb84deeb1d644c71c52a481?pvs=4)
Savoir qu’une action préalable à l’embauche a été ajoutée par un employeur sur une candidature 
Partage de l’information au prescripteur et candidat sur l’avancée du recrutement et sur les détails relatifs à l’action préalable ajoutée par le recruteur. 
Afficher les actions préalables à l’embauche sur la pages candidature pour eux (comme c’est le cas pour le GEIQ)
vue employeur
vue candidat
=> [CANDIDATURE GEIQ] afficher les actions préalables pour les candidats et les prescripteurs

itou/templates/apply/includes/job_application_prior_action.html, itou/templates/companies/job_description_list.html
**Carte Notion :** https://www.notion.so/plateforme-inclusion/Modale-Supprimer-la-fiche-de-poste-Passer-le-btn-en-danger-icon-6b53adc2ea5142e69aeb221fd4f18868?pvs=4
Parcque les UX y préfèrent
Changements du DOM et des classes css
Avant
Apres
=> Modification UI des boutons "Supprimer" dans les modales

itou/templates/account/account_type_selection.html
Pour corriger une erreur que j'avais faite dans [cette PR](https://github.com/gip-inclusion/les-emplois/pull/3417/files#diff-ee78cb95f43868c0b768f9ead6c6b1104aa02e55dc286a5b9e1dd18c0e29243c)
=> Correction d'une mauvaise utilisation du block content_title_wrapper

itou/www/stats/utils.py, tests/www/stats/test_utils.py
**Fil slack : https://itou-inclusion.slack.com/archives/C04SAGUGJFJ/p1700818972747209**
Pour donner plus de visibilité aux stats publiques de Pilotage à tous les utilisateurs pros du C1, pas juste ceux qui ont accès à des stats privées.
On montre à tous les utilisateurs du C1 sauf les candidats, l'encart simple suivant :
=> Stats : Montrer la section Pilotage à tous les utilisateurs professionnels

itou/templates/apply/submit/application/end.html, tests/www/apply/test_submit.py
[Carte Notion](https://www.notion.so/plateforme-inclusion/En-tant-qu-employeur-je-souhaite-que-les-num-ros-de-t-l-phones-des-candidats-soient-renseign-s-afin--857b793d366f475ab359aa8913aa99bc?pvs=4)
Augmenter la complétude du numéro de téléphone des candidats
=> Candidatures : message en l'absence de telephone renseigné lors de la confirmation [GEN-5256]

itou/templates/apply/list_for_siae.html, itou/www/apply/views/list_views.py, tests/www/apply/test_list.py
Faire varier le message d'absence de résultat de recherche selon que la compagnie a des candidatures nouvelles, à l'étude, en attente, ou non.
AJout d'une variable de contexte pour dénombrer les candidatures dans l'un des états `pending_states` avant application des filtres
Compagnie avec des `pending_states applications`
Compagnie sans `pending_states application`
=> Recherche Candidatures Company : variabilité du message d'absence de résultat [GEN-3296]

itou/users/management/commands/new_users_to_mailjet.py, tests/users/test_management_commands.py
Les utilisateurs IC n'utilisent plus le modèle Email d'allauth et n'ont donc plus d'email vérifié coté Emplois: on considère leur email vérifié coté Inclusion Connect.
=> [GEN-7763] Liste de diffusion Mailjet: considérer les utilisateurs IC comme ayant une adresse email vérifiée

itou/prescribers/models.py, tests/www/prescribers_views/test_list.py
La règle actuelle ne convient pas.
=> [GEN-7294] Modifier la règle d’affichage de la liste des organisations conventionnées pour les admin d’un CD

itou/templates/search/siaes_search_home.html
Ajout d'une bannière temporaire faisant la promotion de l’événement d'inclusion demain.
Demande validée par Eric X Comm
=> Ajout d'une bannière temporaire sur la homepage

config/urls.py, itou/templates/500.html, itou/www/error.py, tests/www/test_error.py
- cela nous permet d'avoir une page d'erreur complète avec:
- des meta remplies
- le JS qui fonctionne (matomo & tarteaucitron)
- le lien "Besoin d'aide" qui fonctionne
- et surtout pour les devs cela permet d'avoir le test qui dit pourquoi il échoue et non plus `Undefined template variable 'ITOU_PROTOCOL' in '.../itou/templates/layout/base.html'`
=> Ajout d'une vue d'erreur personnalisée

.gitignore, CHANGELOG_breaking_changes.md, docker-compose.yml, docker/dev/django/Dockerfile, docker/dev/django/entrypoint.sh
Pour ne plus avoir tout qui explose pour la personne utilisant l'env docker ainsi que le venv en local :).
Activer le venv automatiquement lors du login dans le container.
=> docker : Ne plus utiliser le nom de venv par défaut

.pre-commit-config.yaml, CHANGELOG_breaking_changes.md
Il est lancé dans la CI mais pas en local. C'est dommage car cela permettrait de repérer les erreurs en amont.
=> [GEN-7755] Lancement de ShellCheck dans pre-commit

tests/approvals/tests.py, tests/eligibility/test_iae.py, tests/job_applications/tests.py, tests/metabase/management/test_populate_metabase_emplois.py, tests/users/factories.py, tests/users/test_models.py, tests/www/apply/test_process.py, tests/www/apply/test_submit.py, tests/www/employee_record_views/test_create.py
Plutôt que reposer sur le comportement par défaut de la factory.
Et cela me permettra de faire une transition plus douce (et une PR plus courte) lors de la bascule des champs `pole_emploi_id` / `lack_of_pole_emploi_id_reason`  du modèle `User` au modèle `JobSeekerProfile`.
=> tests: clairement spécifier quand un test nécessite que le demandeur d'emploi ait un identifiant pole emploi

itou/users/admin.py, tests/users/test_admin_views.py
Cela correspond plus à l'utilisation effectuée par le support
=> [GEN-7796] Admin : Fonction “transfert” des objets puis arriver sur la bonne page

itou/job_applications/models.py, itou/templates/apply/includes/job_application_answers.html, itou/templates/approvals/prolongation_requests/show.html, itou/templates/companies/job_description_card.html, itou/templates/dashboard/api_token.html, itou/templates/includes/copy_to_clipboard.html, itou/templates/invitations_views/includes/pending_invitations.html, itou/www/apply/views/process_views.py, tests/job_applications/tests.py, tests/www/apply/test_process.py
https://www.notion.so/plateforme-inclusion/En-tant-que-prescripteur-qui-re-oit-un-refus-pour-motif-autre-je-suis-invit-contacter-l-employeur-81f39548494042538ee5d8d935c8d9ce?pvs=4
Les prescripteurs se plaignent de ne pas être suffisamment informés lorsque l’employeur sélectionne le motif autre 
Lorsqu’un employeur a choisi le motif  de refus “Autre" on affiche au prescripteur les coordonnées de l’employeur et on l’incite à le contacter
=> [GEN-5180] En tant que prescripteur qui reçoit un refus pour motif autre je suis invité à contacter l’employeur si je souhaite en savoir +

tests/metabase/conftest.py
Pouvoir lancer `populate_metabase_emplois` et la suite de tests sans avoir à modifier son `.env` à chaque fois :).
=> tests: Forcer le paramètre de configuration `METABASE_HASH_SALT`

itou/users/models.py, tests/api/test_geiq.py, tests/job_applications/factories.py, tests/users/factories.py, tests/users/test_models.py, tests/www/apply/test_submit.py
Pour se rapprocher au plus du comportement natif de factory-boy et ne plus devoir jongler entre les différentes factories.
=> tests: simplification des JobSeeker/JobSeekerProfileFactory

itou/templates/layout/_header_nav_primary_items.html, tests/www/__snapshots__/test_layout.ambr, tests/www/approvals_views/test_prolongation_requests.py, tests/www/companies_views/test_job_description_views.py, tests/www/test_layout.py
Ce guide existe et est un outil pour les nouveaux PH qu’il faut leur mettre à dispo au bon endroit
=> [Boost] Ajout du guide a la prescription dans la navigation pour les employeurs et les PH [GEN-3635]

itou/templates/approvals/detail.html
=> Anomalie UI : le “i” est décalé quand la suspension du PASS n’est pas possible [GEN-7815]

scripts/create-fast-machine.sh
Toujours mieux de nettoyer après avoir fini :smirk_cat:.
=> scripts : Proposer la suppression du remote git dans `create-fast-machine.sh`

itou/employee_record/management/commands/sanitize_employee_records.py, tests/employee_record/test_sanitize_employee_records.py
Voir commit.
Voir commit.
Pas de script à part pour gérer l'existant, les nombres étant raisonnables tout sera fait au premier passage :
```
In [2]: EmployeeRecord.objects.orphans().exclude(status__in=[Status.ARCHIVED]).count()
Out[2]: 7819
```
En local :
```
$ time ./manage.py sanitize_employee_records
...
real    0m21.106s
user    0m2.909s
sys     0m0.568s
```
=> Fiches Salarié : Archiver plutôt que désactiver les “FS Orphelines” [GEN-7836]

itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/views.py
**Carte Notion : https://www.notion.so/plateforme-inclusion/Publier-le-TB118-aux-CD-2e66a24c98384a0e9ac3696a41d31396**
Proposer des données de références sur le nombre et le parcours des bénéficiaires (entrées / sorties / durée).
=> Stats : Ajout de stats IAE pour les CD (déploiement national)

itou/www/apply/views/submit_views.py
https://itou.sentry.io/issues/4792190341/
=> www.apply: gestion d'une session obsolète empêchant la création d'un candidat

itou/employee_record/management/commands/clean_orphans.py
> [!IMPORTANT]  
> A relire et déployer après #3499 et avant #3500.
En faisant une vérification de dernière minute pour #3500, je me suis rendu compte que la PR allais créer des problèmes sur le long terme, toute les FS orpheline allaient redevenir "visible" là où auparavant on les filtraient, ce qui aurais pour conséquence de ne plus avoir 1 FS active pour 1 candidature.
Supprimer toutes les FS orphelines n'est pas possible car cela allais faire réapparaître de _nombreuses_ demandes de création dans le tableau de bord des employeurs pour des salariés n'étant plus dans la structure.
Je suis donc parti sur la logique que si l'on supprime la notion de FS orpheline alors il faut aussi adapter nos données pour faire comme si cette notion n'avais jamais existé et ne garder qu'une FS …
=> Fiches salarié : Nettoyage des FS orphelines faisant doublon

itou/api/c4_api/serializers.py, itou/api/data_inclusion_api/serializers.py, itou/companies/management/commands/import_siae.py, itou/companies/models.py, itou/employee_record/migrations/0011_clean_orphans_duplicate.py, itou/employee_record/migrations/0012_clean_data_to_change_unique_constraint.py, itou/employee_record/migrations/0013_change_unique_constraint.py, itou/employee_record/models.py, tests/employee_record/__snapshots__/test_transfer_employee_records.ambr, tests/employee_record/test_models.py, tests/job_applications/test_eligibility.py, tests/www/employee_record_views/test_create.py
> [!IMPORTANT]  
> A relire et déployer après #3500 (et donc #3509 ainsi que #3499).
La clause d’unicité utilisée par l’ASP est : Siret + Mesure + PASS IAE
Notre clause d’unicité est : ASP ID + Mesure + PASS IAE
Empêche la création d’une FS pour : 1 ASP ID, plusieurs Siret
Changement de la clause d'unicité.
2 SIAE ont des données non-compatible avec la nouvelle clause :
- J'en ai corrigé 1 à la main car seulement 1 FS et celle-ci étaient `ARCHIVED` car orpheline.
- La seconde est corrigée dans une migration en supprimant les (24) FS en doublons et qui sont associées à une SIAE avec une convention expirées suite à son changement d'ASP ID.
=> Fiches salarié : Utiliser la même clause d’unicité que l’ASP [GEN-7786]

itou/templates/layout/base.html
Le lien est de facto invisible depuis 2c59b59eec0fa7ac37f789 et ses redirections automatiques.
Les retours utilisateurs étaient assez difficilement exploitables.
=> [GEN-7876] Suppression du lien voxusagers

tests/utils/test.py, tests/utils/tests.py, tests/www/companies_views/test_views.py, tests/www/employee_record_views/test_list.py
Rendre `parse_response_to_soup` capable de gérer les urls complexes dans les snapshots.
ie : `href="http://localhost:8000/company/job_description/[PK of JobDescription]/card?back_url=/company/[PK of Company]/card"`
Modifier le traitement du paramètre  `replace_objects_pk_in_href` : 
1. Si reçoit une liste de tuple, remplacement du premier membre du tuple par le second
2. Sinon, maintien du fonctionnement existant, remplacement des PK de la liste d'objet de la liste
###
=> Utilitaires de test : gerer le remplacement des urls complexes

itou/employee_record/migrations/0011_clean_orphans_duplicate.py
Elle a déjà été passée en production mais autant avoir des migrations fonctionnelles
=> Correction d'une migration

itou/templates/approvals/includes/status.html, tests/www/approvals_views/__snapshots__/test_includes.ambr, tests/www/approvals_views/test_includes.py
Ne pas afficher l'alerte sur le Pass expiré si le candidat a un diagnostique d'éligibilité valide et fait par un prescripteur, lors de la déclaration d'embauche
Mise à jour du gabarit `approvals/includes/status.html`
`check-infos`
`check-previous-application`
`confirm`
> [!NOTE]
> le cas des diagnostiques réalisés par un employeur est déjà géré par ailleurs. Contrôle inutile dans l'include
>  ![image](https://github.com/gip-inclusion/les-emplois/assets/11419273/a517c3e6-b80c-44c0-a76a-406b8547dacd)
=> Embauche : masquer l'alerte sur le Pass expiré lors du dépot de candidature [GEN-7451]

itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, tests/www/siae_evaluations_views/test_institutions_views.py
Pour qu'il soit plus clair que l'info est manquante.
=> [GEN-7860] Contrôle a posteriori: ajout de la mention “Non renseigné” lorsque le téléphone de la SIAE n’est pas connu

.envrc, .gitignore
Avant 4e24681ba6ea6e7f1f4b0bdd76b81f5b52236283, les développeurs pouvaient configurer leur environnement en entrant dans le répertoire du projet avec direnv. En particulier, activer leur environnement virtuel pour Python.
Après ce commit, les développeurs doivent soit charger l’environnement manuellement, soit modifier leur `$PATH` dans leur `.env` à partir de ce que fait `.venv/bin/activate`.
Avec ce changement, les développeurs peuvent à nouveau personnaliser leur environnement via `.envrc.local`.
=> Permettre aux développeurs de gérer un .envrc local

itou/approvals/admin.py, itou/approvals/models.py, itou/job_applications/admin.py, itou/job_applications/models.py, itou/users/admin.py, itou/utils/admin.py, tests/approvals/test_admin.py, tests/job_applications/test_admin.py, tests/users/test_admin_views.py
**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Admin-Transfert-des-donn-es-candidats-Ajouter-texte-pour-l-agent-support-vigilance-de-la-coh-re-f27d4c6d4e9a4b748d8b219d858fd30b?pvs=4
Lors de modification pour gérer les doublons d'utilisateur, il peut arriver de créer des incohérences entre les candidatures/PASS & diag.
=> admin: ajout d'une action pour détecter des incohérences sur les données

itou/users/admin_forms.py, itou/users/models.py, itou/www/signup/forms.py, tests/users/test_admin_forms.py, tests/users/test_models.py
Moins de code -> moins de problème
=> Vérification d'unicité du NIR: simplification

itou/siae_evaluations/models.py, itou/www/dashboard/views.py, itou/www/siae_evaluations_views/views.py
Elles ne sont pas censées compter.
=> [GEN-2736] Retirer le lien vers les campagnes expérimentales de l’historique du contrôle a posteriori

itou/templates/apply/includes/accept_section.html, itou/templates/apply/includes/job_application_accept_form.html, itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/list_for_siae.html, itou/templates/apply/process_refuse.html, itou/templates/dashboard/includes/edit_job_seeker_info_form.html, tests/www/apply/__snapshots__/test_list.ambr
Matomo ne prend que soit le nom, soit la catégorie, soit l'action d'un évènement pour parémetrer un objectif, sans combinaison possible. Le nom des évènements doit alors être unique :
- `accept_application` / `accept_application_submit` / `accept_application_modal_confirmation` 
- `refuse_application` ∕ `refuse_application_submit`
- `edit_jobseeker_infos` / `edit_jobseeker_infos_submit`
- utiliser `-` et à place de `_` dans les tags FR : `voir-candidature-employeur`
=> [STATS] amélioration de tags

config/settings/dev.py
Permettre l'utilisation de DB (ou autres) différentes entre `gip-inclusion/les-emplois` et `gip-inclusion/pilotage-airflow`.
@dejafait @YannickPassa Je vous met en relecteurs car _normalement_ vous êtes les seuls à avoir éventuellement besoin de ça, ça devrait rien casser sauf si vous avez définis une variable `METABASE_` mais pas trop de raison _a priori_.
=> settings.dev: Allow customizing Metabase configuration variables

itou/templates/dashboard/dashboard.html, itou/templates/dashboard/includes/prescriber_job_applications_card.html, itou/templates/dashboard/includes/siae_card.html, itou/templates/dashboard/includes/siae_employees_card.html, itou/templates/dashboard/includes/siae_job_applications_card.html, itou/templates/layout/_header_nav_primary_items.html, itou/utils/staticfiles.py, tests/www/__snapshots__/test_layout.ambr
**Carte Notion: ** https://www.notion.so/plateforme-inclusion/Refonte-UX-UI-Carte-dashboard-33e1363a586d453ba1b7c36706ad17a1?pvs=4
Modification de l'ordre et ajout d'un bouton d'action principale sur les cartes du dashboard
Avant
Apres
=> Refonte UX/UI - Cartes dashboard

itou/employee_record/management/commands/unarchive_employee_records.py
Besoin ponctuel (mais toujours en masse, 30+ par structure, avec parfois plusieurs structure) pour l'ensemblier EUREKA suite à des changements de Siret consécutifs.
Création d'un petit script plutôt que de faire la commande dans mon coin.
Depuis #3500 et #3467, un changement de Siret n'invalide plus la FS donc les (possibles) demandes devraient disparaître d'ici 3-6 mois, on pourra alors supprimer ce script, d'où l'absence de tests :see_no_evil:.
=> Fiches salarié : Ajout d'un script pour sortir en masse des FS pour une SIAE

itou/common_apps/organizations/models.py, tests/approvals/__snapshots__/test_notifications.ambr
Actuellement, on affiche le nome en le "capitalizant": on met tout en minuscule sauf la première lettre qui est en majuscule.
Cela marche parfois mais cela fait souvent des choses plutôt moche du genre:
- "France Travail - Quelque Part sur Oise" devient "France travail - quelque part sur oise"
- "APAJH" devient "Apajh"
Comme les administrateurs ont la main pour modifier le nom de leur structure (et qu'il n'y a pas d'import automatique écrasant leurs modifs) autant les laisser décider de leur nom.
=> [GEN-7981] Arrêter de modifier le nom d'affichage des organisation prescriptrices et des institutions

itou/files/forms.py, itou/static/js/matomo.js, itou/templates/account/activate_inclusion_connect_account.html, itou/templates/account/login_generic.html, itou/templates/apply/includes/buttons/archive.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/apply/process_details_company.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/approvals/detail.html, itou/templates/approvals/includes/job_applications.html, itou/templates/approvals/includes/list_card.html, itou/templates/companies/includes/_card_jobdescription.html, itou/templates/companies/includes/_card_siae.html, itou/templates/companies/includes/_list_siae_actives_jobs_row.html, itou/templates/dashboard/dashboard.html, itou/templates/employee_record/includes/create_step_5.html, itou/templates/inclusion_connect/includes/description.html, itou/templates/layout/_footer.html, itou/templates/layout/_header_nav_primary_items.html, itou/templates/search/siaes_search_results.html, itou/templates/signup/includes/france_connect_button.html, itou/templates/signup/includes/no_email_link.html, itou/templates/signup/includes/peamu_button.html, itou/templates/signup/job_seeker_nir.html, tests/www/__snapshots__/test_layout.ambr, tests/www/apply/__snapshots__/test_list.ambr
En préparation de la revue des évènements matomo diffusés par le site, cette PR harmanise l'implémentation de ces évènements.
La nouvelle implémentation bénéfiice du `simple_tag` `matomo_event`
```
class="matomo-event" 
data-matomo-category="category_name"
data-matomo-action="action_name"
data-matomo-option="option_name"
```
En début de gabarit : `{% load matomo %}`
Dans le corps gabarit :
* `{% matomo_event "category_name" "action_name" "option_name" %}`
* `{% matomo_event "category_name"|add:var-to-be-concactenated "action_name" "option_name" %}` en cas d'aggrégation de vars
Simplification du script `matomo.js` : suppression de l'interpretation de `class=matomo-event`
=> [STATS] harmonisation de l'appel aux évènements matomo

itou/employee_record/management/commands/transfer_employee_records.py, tests/employee_record/test_transfer_employee_records.py
C'est mieux quand ça fonctionne comment c'est supposé fonctionner ;), et ça devrait réduire _un peu_ le nombre de ticket support inutile.
=> Fiches salarié : Correction de la création automatique d'une notification en cas de doublon PASS IAE/SIRET (3436)

itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/models.py, tests/employee_record/test_models.py, tests/employee_record/test_sanitize_employee_records.py
Le trigger PG ne crée une notification que si la FS est `NEW` mais auparavant nous archivions les FS 13 mois après leur création, un certain nombre de FS ont donc été archivées mais sont ensuite prolongées ou suspendues après ces 13 mois, la nouvelle date de fin ne sera donc pas transmise à l'ASP.
La commande `sanitize_employee_record` essaie de détecter ces cas (uniquement pour les prolongations) pour créer la notification manquée, il semble donc de bon aloi d'également sortir la FS du statut `ARCHIVED`.
=> Fiches salarié : Sortir d'archive automatiquement les FS dont on a raté la notification

itou/users/models.py, tests/www/dashboard/tests.py
Éviter facilement des erreurs 500.
cf https://itou.sentry.io/issues/4934484020/
=> Modifier mon profil en tant que candidat: meilleure gestion d'un identifiant France Travail/pôle emploi invalide

clevercloud/crons/populate_metabase_emplois.sh, itou/utils/apis/metabase.py
Les enums peuvent changer n'importe quand, les mettre à jour qu'une fois par mois n'est donc pas suffisant.
=> C2 : Mettre à jour les tables de références d'énumérations tout les jours au lieu de tout les mois

itou/templates/dashboard/dashboard.html
Pour avoir davantage d’idée pour les emplois premium.
=> [GEN-7933] Afficher le lien d’une enquête tally pour les employeurs

.github/pull_request_template.md
With the `GEN-*` linking, there’s no need for systematic hyperlinks.
=> Retirer “Carte Notion” de pull_request_template

itou/www/apply/views/process_views.py, tests/www/apply/test_process.py
Le seul moyen d'accéder à la vue "apply:eligibility" c'est de cliquer sur le bouton "Accepter cette candidature":
il est donc assez logique de toujours rediriger vers la vue d'acceptation une fois le diagnostic validé.
=> [GEN-7265] Suppression d'une étape dans le parcours d'acceptation d'une candidature IAE

scripts/restore_latest_backup.sh
=> `restore_latest_backup.sh` : Utilisation de `RCLONE_CONFIG` au lieu de `PATH_TO_RCLONE_CONF`

.env.template, CHANGELOG_breaking_changes.md, scripts/create-fast-machine.sh
- Moins d'étape pour avoir le script fonctionnel
- Plus besoin de faire : œuf -> poule -> œuf -> poule
- Pas de duplication de configuration entre le `.env` et le fichier lu nativement par `clever`, ça éviteras des surprises (2 fois, 2 personnes différentes)
=> configuration : Suppression de `CLEVER_TOKEN` et `CLEVER_SECRET`

tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation_requests.py
PR d'origine : #3018 
C'est quand même mieux quand le contenu des _snapshots_ est le bon...
=> Correction d'un test d'une ancienne PR (#3018)

itou/companies/management/commands/move_company_data.py, itou/utils/faker_providers.py, tests/companies/factories.py, tests/companies/test_management_commands.py
Le script fait l'inverse de ce à quoi on s'attend en passant l'option `--preserve-to-company-data`.
1. Ajout d'un nouveau _formater_ Faker : `geopoint`
2. Nouveau traits pour `CompanyFactory`
3. Correction avec son test
=> Correction de l'option `--preserve-to-company-data` pour `move_company_data`

itou/static/js/matomo.js
Toutes les pages ont l’erreur JS suivante :
```javascript
Uncaught Error: Syntax error, unrecognized expression: data-matomo-event="true"
at I.error (jquery.min.2c872dbe60f4.js:2:11769)
at Y (jquery.min.2c872dbe60f4.js:2:17234)
at re (jquery.min.2c872dbe60f4.js:2:20008)
at Function.I [as find] (jquery.min.2c872dbe60f4.js:2:7520)
at ce.fn.init.find (jquery.min.2c872dbe60f4.js:2:21991)
at new ce.fn.init (jquery.min.2c872dbe60f4.js:2:22511)
at ce (jquery.min.2c872dbe60f4.js:2:1077)
at matomo.691dc1384641.js:12:5
at HTMLBodyElement.<anonymous> (htmx.min.f78c4167bb3a.js:1:5211)
at fe (htmx.min.f78c4167bb3a.js:1:25722)
```
=> Corriger le sélecteur data-matomo-event dans matomo.js

itou/api/token_auth/views.py
Pour pouvoir aider les utilisateurs n'arrivant pas à se connecter à notre API.
À noter que tous nos tokens sont générés automatiquement et ont actuellement la même taille: cette donnée ne dévoile donc rien mais permettrait de détecter des soucis de paramétrage coté utilisateur (si on reçoit des tokens qui ne font pas 40 caractères).
=> API: ajout d'un log en cas de token invalide

itou/companies/management/commands/_import_siae/utils.py
Un commentaire laissait penser à tort que l'import EA supprimait parfois des antennes, ce qui n'est jamais le cas.
Discussion initiale : https://itou-inclusion.slack.com/archives/C01181Y04LT/p1707232064037189?thread_ts=1706024473.600199&cid=C01181Y04LT
=> Import EA : Correction d'une erreur mineure dans un commentaire

itou/api/token_auth/views.py, tests/api/token_auth/tests.py
Sinon, ça `TypeError: object of type 'NoneType' has no len()`
=> API: correction du log en cas de mot de passe manquant

config/settings/base.py, itou/templates/layout/base.html
Avoir connaissance des problèmes dans les scripts fournis par les emplois.
=> Surveiller les erreurs JS avec Sentry

itou/templates/apply/includes/list_card_header.html, itou/templates/companies/includes/_card_jobdescription.html, itou/templates/companies/includes/_card_siae.html, itou/templates/dashboard/includes/siae_card.html, itou/www/companies_views/views.py
Cette vue n'en fait rien et les liens seront un peu plus léger/lisible/joli.
=> Suppression du paramètre d'URL back_url des liens vers les fiches entreprises

itou/users/admin.py
Quand on cherche une candidature pouvant correspondre à un évènement cela permet de voir rapidement si cette candidature est pertinente.
=> Admin: ajout de la date de création de la candidature dans le listing de la vue Utilisateur

itou/static/js/utils.js, itou/templates/includes/copy_to_clipboard.html, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Moins de JS, moins de problème (et moins d'erreur Sentry :see_no_evil: )
@hellodeloo Je n'arrive pas à trouver la doc, j'ai juste trouvé pour les input-group: https://zeroheight.com/85c89893b/p/90ca0a-input-group/b/995f63/t/1486d8
=> Utilisation de la fonctionnalité "Copier dans le presse-papier" du thème

tests/approvals/test_admin.py, tests/settings_viewer/tests.py, tests/www/apply/test_forms.py, tests/www/companies_views/test_job_description_views.py, tests/www/employee_record_views/test_create.py, tests/www/login/tests.py
Pour s'assurer que nos `assertNotContains` continue de vérifier l'absence de valeur pertinentes.
J'en ai corrigé quelques uns mais il en reste encore pas mal.
=> tests: amélioration de nos tests techniques

itou/templates/dashboard/dashboard.html, itou/templates/dashboard/includes/dora_card.html, itou/utils/settings_context_processors.py
L'URL "officielle" de Dora n'est plus celle de la fabrique.
Par ailleurs ils transitionnent de Plausible à Matomo, d'où la nécessité de corriger le tracker.
Simplement.
=> Tableau de bord : correction des URLs et trackers Dora

itou/templates/layout/base.html, itou/utils/apis/data_inclusion.py, itou/www/companies_views/views.py, tests/utils/__snapshots__/tests.ambr, tests/utils/apis/test_data_inclusion_api.py, tests/www/companies_views/test_views.py
- Nous ne désirons que des services en présentiel (en particulier, retirer les Emplois)
- Certains services, venant de Dora, ont une URL plus "précise" que la canonique data.inclusion.
- Si data.inclusion ne répond pas, il est intéressant de ne pas stocker cette "erreur" en cache pendant 24h.
- Le tracking de contenu Matomo sémantique ne peut pas fonctionner si on ne l'active pas globalement.
Cf. les commits.
=> Bannière Dora : correctifs demandés par le métier + la technique

itou/templates/companies/hx_dora_services.html, tests/www/companies_views/__snapshots__/test_views.ambr, tests/www/companies_views/test_views.py
Dans le jargon DI, il est plus précis de donner l'adresse du service que celle de la structure, la recherche étant faite sur le service "présentiel" on a bien plus de chances d'avoir une adresse correcte ainsi.
Par ailleurs avec cette modification nous testons que si l'adresse est non présente pour le service (a priori pas possible) alors nous n'affichons pas un affreux "None None".
Ce qu'on essaie de corriger:
=> Services Dora : correction du cas où l'adresse structure est manquante

itou/api/__init__.py, itou/api/applicants_api/views.py, itou/api/employee_record_api/viewsets.py, itou/api/token_auth/views.py
Clarifier comment les utilisateurs de l’API peuvent se connecter, l’ancienne documentation étant obsolète depuis la migration à Inclusion Connect.
[GEN-5116]
=> MàJ de la doc d’API pour générer un jeton

itou/www/apply/views/submit_views.py, tests/www/apply/test_submit.py
Pour soulager Postgresql et que les pages s'affichent quelques millisecondes plus vite :dash:
=> Confirmation d'embauche: réduction du nombre de requêtes

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/approvals/printable_approval.html, itou/templates/signup/job_seeker_nir.html
https://itou.sentry.io/issues/4953055957/ est en train de dévorer notre quota d’erreurs.
=> Charger les <script>s des gabarits parents

itou/templates/approvals/pe_approval_search_user.html
=> Retirer une surcharge de bloc script inutilisée

itou/openid_connect/pe_connect/views.py
Pôle emploi Connect a été cassé ce matin. Une fois le fix déployé (https://github.com/gip-inclusion/itou-secrets/pull/69), la connexion candidat avec mon compte francetravail.fr affichait une erreur 500. Il a fallu plusieurs minutes (stressantes) pour que l’erreur remonte dans Sentry et que je réalise que la connexion était bien réparée, sauf pour moi.
=> [GEN-8064] Gérer les membres ITOU se connectant avec FT connect

itou/users/admin.py, tests/users/test_admin_views.py
De plus en plus de champs sont sur le profil, avoir la même logique de recherche facilitera la transition.
=> admin: même fonctionnement de recherche entre Utilisateur & Profil de candidat

itou/api/geiq/serializers.py, tests/api/__snapshots__/test_geiq.ambr
=> [GEN-8058] Retirer le NIR de l’API GEIQ

itou/www/stats/views.py, tests/www/stats/test_views.py
[LES-EMPLOIS-PROD-1DT](https://itou.sentry.io/issues/4706530465/)
Les tests sont _fortement_ dupliqués, mais c'est à l’instar du code j'ai envie de dire ;).
C'est clairement factorisable mais il faudrait le faire en même temps que le code associé afin d'éviter d'avoir des tests ultra-génériques alors que le code ne l'est pas et se retrouver avec des exceptions à gérer.
=> Stats : Correction d'une erreur pour les `DDETS LOG`

itou/utils/apis/geocoding.py, tests/companies/test_management_commands.py
Actuellement si `API_BAN_BASE_URL` n'est pas remplis alors on a ce message d'erreur :
> Error while requesting \`None/search/?q=...&limit=1&postcode=...`: Request URL is missing an 'http://' or 'https://' protocol.
Le test est sans rapport, mais celui-ci ayant échoué sur la CI autant s'en occuper tout de suite ;).
=> API BAN : Ne pas faire de requête et logué si `API_BAN_BASE_URL` est vide

itou/templates/layout/base.html
The rules to decide whether a script ought to be part of the
`{% block script%}` or not are unclear. Since we consider all scripts
mandatory, do not give the impression that they can be overridden.
=> Grouper les scripts dans le template de base

itou/users/admin.py, tests/users/test_admin_views.py
Pour facilement trouver les incohérences.
=> Profil candidat: ajout d'un check de cohérence dans l'admin

itou/approvals/admin.py, itou/companies/models.py, tests/approvals/tests.py, tests/www/employee_record_views/test_list.py
[LES-EMPLOIS-PROD-1GH](https://itou.sentry.io/issues/4949320866/) et voir le commit :).
=> Correction d'une erreur quand une SIAE sans convention voulais accéder aux interfaces des fiches salarié

itou/companies/management/commands/_import_siae/utils.py
1 semaine c'est un peu court, l'import SIAE est sur 3 mois alors utilisons la même valeur partout.
Nous avons d'ailleurs récemment eu le cas ou une EA créée par le support c'est retrouvé supprimée avant d'être recrée, ce qui n'est pas ouf-ouf.
=> Augmenter le délai avant la suppression automatique d’une entreprise (EA / GEIQ) non référencée [GEN-8073]

itou/users/forms.py, itou/www/invitations_views/forms.py, itou/www/signup/forms.py, tests/www/invitations_views/test_prescriber_organization.py, tests/www/signup/test_prescriber.py
`pole-emploi.fr` → `francetravail.fr`
=> [GEN-7871] Autoriser les @francetravail.fr à créer un compte PE

itou/utils/staticfiles.py
Parcqu'avec les noms court, le dropdown n'est pas assez large
Maj du thème, corrigé dans le css
Avant
Apres
=> Largueur minimum du dropdown-structure

scripts/imports-asp.sh
Dans les 2 derniers mois et pour des cas d'usage différents j'ai eu besoin d'avoir plus que le dernier flux IAE, dans ce même intervalle de temps le flux IAE à eu des problèmes au même moment ce qui m'a obligé d'attendre des semaines supplémentaires, le fichier n'étant pas super gros autant augmenter la rétention pour les cas futur.
=> Scripts : Augmentation du temps de rétention du flux IAE

itou/templates/search/includes/siaes_search_filters.html
Besoin de trop scroller pour accéder aux filtres qui ne concernent pas la localisation
Avant
Apres
=> Ajout de collapse sur les filtres departments et districts 

config/settings/base.py, itou/companies/management/commands/_import_siae/convention.py, itou/companies/management/commands/_import_siae/financial_annex.py, itou/companies/management/commands/_import_siae/siae.py, itou/companies/management/commands/_import_siae/utils.py, itou/companies/management/commands/_import_siae/vue_af.py, itou/companies/management/commands/_import_siae/vue_structure.py, itou/companies/management/commands/import_ea_eatt.py, itou/companies/management/commands/import_geiq.py, itou/companies/management/commands/import_siae.py, scripts/imports-asp.sh, tests/companies/test_import_siae_command.py, tests/conftest.py
Il est possible de recevoir des nouvelles AF alors que la date de fin d’effet est dépassée, hors celles-ci sont actuellement ignorées par le script `import_siae`.
- Multiple réusinages du script d'import des SIAE, il est possible que certain commit ne soit pas tout à fait iso-fonctionnel mais la globalité oui.
- Ne plus se limiter à la conversion des structures ayant une AF valide au moment de l'import.
- Nous continuons d'ignorer les nouvelles structures non-valide car cela en aurais recréé tout un tas dont on se fiche car n'existant plus physiquement.
=> Import SIAE : Importer les structures avec une convention validée rétroactivement [GEN-8055]

scripts/imports-asp.sh
Sinon ça marche pô :grinning: : [LES-EMPLOIS-PROD-1PR](https://itou.sentry.io/issues/5001787469/)
=> scripts.imports-asp: Use the correct environment variable name

Makefile
Ça compte la flemme ? :grin: 
Au dessus de 27 commits GH n'affiche rien mais on a rarement des MEP avec autant de commits :see_no_evil:.
=> Makefile: Afficher la liste des PR déployées pour `deploy_prod`

itou/approvals/models.py, tests/approvals/tests.py
Test flaky révélant un problème potentiel https://itou-inclusion.slack.com/archives/C0412CTV63D/p1708356006800829
=> Utiliser un tri déterministe pour PoleEmploiApproval.find_for()

itou/templates/apply/process_details.html, itou/templates/apply/process_details_company.html, tests/www/apply/test_process.py
=> Masquer “Actions préalables à l’embauche” lorsqu’elles sont vides [GEN-7973]

itou/companies/management/commands/_import_siae/utils.py, itou/metabase/management/commands/populate_metabase_fluxiae.py
Nos analystes ont besoin des données de financement afin de calculer correctement le nombre de bRSA cible.
Attention certaines données bancaires sensibles sont soigneusement filtrées.
Testé OK en local avec le dernier flux.
Environ 800k lignes et 40 colonnes quand même.
=> Metabase : Injection de la vue "Financement" du Flux IAE

itou/templates/apply/includes/profile_infos.html
- Afficher un numéro de téléphone non renseigné, au lieu de ne pas l’afficher.
- Ajouter le label à l’adresse
- Unifier le markup pour “Non renseigné” entre le NIR et le numéro de téléphone
=> Petites màj UI des infos de profil à la fin de la candidature [GEN-8028]

itou/employee_record/migrations/0010_add_asp_measure_to_unique_constraint.py, itou/employee_record/migrations/0014_alter_employeerecord_job_application.py, itou/employee_record/models.py, tests/employee_record/factories.py
Un objet `EmployeeRecord` ne peux pas fonctionner sans `JobApplication` donc autant que le schéma en DB soit cohérent avec la réalité.
```
SELECT COUNT(*) FROM employee_record_employeerecord WHERE job_application_id IS NULL;
count 
-------
0
(1 row)
```
=> Fiches salarié : La clé étrangère vers la candidature est obligatoire

itou/openid_connect/inclusion_connect/enums.py, itou/openid_connect/inclusion_connect/models.py, itou/openid_connect/inclusion_connect/views.py, itou/utils/urls.py, itou/www/login/views.py, tests/openid_connect/inclusion_connect/tests.py, tests/utils/tests.py
En tant que prescripteur, je pourrai voir la liste des candidatures d'un candidat que j'accompagne drectement sur MAP Conseiller. En cliquant sur le lien, je peux voir le détail de la candidature sans avoir à saisir mes identifiants (MAP ou les emplois).
La suite du parcours est [dans cette PR](https://github.com/gip-inclusion/inclusion-connect/pull/426).
Redirection vers Inclusion Connect si « channel=`map_conseiller` » est présent dans l'URL.
:warning: Une seconde PR suivra, sur Inclusion Connect, pour effectuer une redirection vers PEAM-A lorsque ce même paramètre est détecté dans l'URL. Selon PE, le conseiller n'aura pas besoin de saisir de nouveau ses identifiants car c'est géré « automagiquement ».
J'ai utilisé le paramètre « channel » qui avait l'avantage de déjà exister mais je …
=> [GEN-7888] Map conseiller

itou/utils/urls.py
Problème créé avec 27df9567ab89ccdda5da6aea22cf15258ac1b712.
=> Correctif pour l’environnement de dév

tests/approvals/tests.py, tests/www/approvals_views/test_list.py
Réparer la branche master pour le 29 février.
=> Préferer des timedelta aux relativedelta dans les tests de PASS

itou/templates/dashboard/dashboard.html
Les changements d'interface peuvent dérouter les utilisateurs.
=> Ajout d'un message pour prévenir les utilisateurs des changements d'interface

scripts/imports-asp.sh
Sinon `populate_metabase_fluxiae` et `import_ea_eatt` ne fonctionnent plus :
[LES-EMPLOIS-FAST-MACHINES-5Y](https://itou.sentry.io/issues/5016558892/)
[LES-EMPLOIS-FAST-MACHINES-5Z](https://itou.sentry.io/issues/5016562116/)
=> scripts: Correction pour `imports-asp.sh` suite à d1ce32902 et f7b6f4400

itou/fixtures/django/13_company_memberships.json, itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
Afin d'anticiper la synchronisation des candidats avec l'ASP pour les EITI.
=> Affichage d'un message de promotion temporaire sur le tableau de bord des EITI

itou/fixtures/django/05_test_users.json, itou/users/adapter.py
Conserver la même règle qu'en production.
=> Suppression du parcours de bienvenue systématique dans la démo et les recettes jetables

itou/templates/companies/includes/_card_jobdescription.html, itou/templates/search/prescribers_search_results.html, tests/www/search/tests.py
Évolutions UI
Dans la liste des résultats de recherche, onglet “Postes ouverts au recrutement” 
Avant
Apres
=> Refonte UX/UI: Maj UI des cartes de postes ouverts au recrutement

itou/companies/models.py, itou/templates/approvals/includes/job_description_list.html, tests/www/apply/__snapshots__/test_list.ambr
Un balise html mal écrite et des pluriels qui trainent (1 postes recherchés)
=> Fix candidature card job list

itou/templates/dashboard/includes/stats.html, tests/www/dashboard/tests.py
Intitulé qui prête à confusion
=> Pilotage : Modifier un intitulé de TB privé des SIAE [GEN-8137]

itou/companies/management/commands/import_geiq.py
1. Ne plus avoir ce genre d'erreur : [LES-EMPLOIS-FAST-MACHINES-61](https://itou.sentry.io/issues/5038703707/)
2. Simplifier le lancement de la commande :
```
cd ~/app_*
time django-admin import_geiq --verbosity=2 --wet-run shared_bucket/Liste_Geiq_* |& tee -a "shared_bucket/imports-geiq/output_$(date '+%Y-%m-%d_%H-%M-%S').log"
```
plutôt que 
```
cd ~/app_*
mkdir -p itou/companies/management/commands/data
cp -rfv shared_bucket/Liste_Geiq_* itou/companies/management/commands/data/
time django-admin import_geiq --verbosity=2 --wet-run |& tee -a "shared_bucket/imports-geiq/output_$(date '+%Y-%m-%d_%H-%M-%S').log"
```
4. _Quick fix_ au fait d'avoir a spécifier `ASP_FLUX_IAE_DIR` alors que ce n'est pas lié :sweat_smile:  : [LES-EMPLOIS-FAST-MACHINES-60](https://itou.sentry.io/issues/5038695789 …
=> Import GEIQ : Utiliser un argument plutôt qu'un chemin obligatoire

itou/job_applications/export.py, tests/job_applications/tests.py
Besoin remonté par les utilisateurs
Enrichir le tableau excel des candidatures avec la donnée du statut du PASS
=> Ajout du statut du PASS IAE dans l'export des candidatures (employeurs et prescripteurs)

itou/static/css/itou.css, itou/templates/search/includes/prescribers_search_form.html, itou/templates/search/includes/siaes_search_form.html, itou/www/search/forms.py, tests/www/dashboard/__snapshots__/tests.ambr
Améliorer le comportement responsif du placeholder sur le `.input-group-search`
Et aussi modifier le texte des placeholder https://www.notion.so/plateforme-inclusion/Remplacer-le-placeholder-du-champs-de-recherche-d-emploi-8afcfe39718a4155b8f7d50fe2dd3db7?pvs=4
Avant
Apres
=> Améliorer le comportement responsif du placeholder select2 sur la recherche

config/settings/base.py, itou/api/siae_api/viewsets.py, tests/api/applicants_api/tests.py, tests/api/siae_api/tests.py
https://plateforme-inclusion.zendesk.com/agent/tickets/11434
Depuis 9a6c142ccb6834fad7ef7f70d5e5e8246d31f7c4, la limite est descendue d’environ 120/minute à 12/minute.
La nouvelle limite pose problème pour GTA, et probablement d’autres clients. Soyons plus permissifs pour garder le fonctionnement des clients intact, mais protégeons nous contre les usages malveillants des données identifiés.
=> Augmenter la fréquence d’accès aux APIs

itou/approvals/admin.py, itou/employee_record/admin.py, itou/employee_record/management/commands/employee_records_status.py, tests/approvals/tests.py
Le 6 mars nous avons commencé l'écriture d'un logigramme afin d'aider à la résolution des cas habituels ou simple pour les fiches salarié, lors de cette journée nous avons eu l'occasion de clarifier des incompréhensions et modifications rapides afin d'améliorer le nommage ou la lisibilité pour éviter des erreurs.
=> Admin - Fiches salarié : Améliorations rapide suite à la journée d'atelier

itou/approvals/models.py, tests/approvals/tests.py, tests/www/approvals_views/__snapshots__/test_includes.ambr, tests/www/approvals_views/test_list.py, tests/www/dashboard/tests.py
Afficher 730 jours de validité pour les nouveaux pass.
=> Calculer la durée d’un PASS avec end_at inclusif [GEN-8200]

itou/templates/dashboard/dashboard.html
- Mettre un lien vers le replay au lieu de l’inscription.
- Déplacer la bannière fiches salarié EITI au dessus des autres
=> MàJ bannière fiches salarié EITI [GEN-8236]

itou/metabase/tables/job_seekers.py, tests/metabase/management/test_populate_metabase_emplois.py
Fil slack ([ici](https://itou-inclusion.slack.com/archives/C050D9JNJ9Z/p1710497031134269?thread_ts=1710448205.410239&cid=C050D9JNJ9Z)).
La mise à jour quotidienne Metabase casse depuis quelques jours, sur un nouveau cas tordu (coordonnées GPS présentes mais score de géocoding absent).
A la TDD. En rajoutant un test qui reproduit le souci puis en corrigeant le code.
Preuve (avant rebase) que c'est rouge puis vert :
=> Pilotage : Résolution d'un cas tordu dans les données candidat qui casse la mise à jour quotidienne

itou/users/admin.py, tests/users/test_admin_views.py
Améliorer la vie du support en enlevant deux champs qui prennent beaucoup de place horizontale avec des infos qui ne nous intéressent pas.
=> Amélioration page admin des utilisateurs

itou/templates/common/emails/add_admin_email_body.txt, itou/templates/common/emails/remove_admin_email_body.txt, tests/common_apps/organizations/tests.py, tests/www/companies_views/test_views.py, tests/www/institutions_views/test_views.py, tests/www/prescribers_views/test_admins.py
En préparation de la suite. Antoine prend le relais.
Au passage, correction d'une variable manquante : affichage de « e-mail de contact : {{ email }} » uniquement si la structure en a bien un.
=> Envoi d'un courriel à l'ajout d'un administrateur : réusinage des tests

itou/users/admin.py
=> Admin utilisateur: correction du bug du champ "Date de dernière vérification" dupliqué

config/settings/base.py
On ne veut JAMAIS `DEBUG=True` en prod.
=> Forcer DEBUG=False dans settings.base

itou/templates/apply/submit/eligibility_for_hire.html
`content_extend` est là pour cela.
Et la première section était de toutes façons vide.
Avant:
Après:
=> Parcours d'embauche: suppression d'une section dans la vue d'éligibilité

itou/templates/stats/stats.html
Réalisation d’une enquête auprès des utilisateurs entre le 19 mars et le 2 avril : j’ai besoin de communiquer le plus largement possible sur cette enquête pour avoir le maximum de réponses.
=> Pilotage : Ajouter un encart “enquête” au dessus des tableaux de bord privés [GEN-8251]

README.md, pytest.ini, requirements/base.txt, requirements/dev.txt, requirements/test.in, requirements/test.txt
Xavier vient de perdre au moins une journée à cause de `pytest-timeout` qui crashait les workers sur GitHub actions sans information par rapport à un setup trop long.
Nous avons déjà augmenté plusieurs fois les timeouts pour essayer de les faire marcher sur les Macs, finalement c’est à chacun de définir sa limite en fonction de sa machine.
D’autres ont rencontré le problème :
- https://github.com/pytest-dev/pytest-timeout/issues/87
- https://github.com/pytest-dev/pytest-timeout/issues/137
L’investissement dev ne vaut la (faible) sécurité ajoutée.
=> Retirer pytest-timeout

itou/static/css/itou.css
Inutilisé depuis 75e01b341f2b8bfbaea26ad9c783aa8c34ee324a.
=> Retirer du CSS inutilisé pour htmx-indicator

itou/templates/layout/_header_nav_primary_items.html, tests/www/__snapshots__/test_layout.ambr
cf https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-type
=> templates: suppression du type="button" d'une balise <a>

itou/templates/search/siaes_search_results.html, itou/utils/staticfiles.py
Évolutions UI
Maj du DOM et de la version du thème pour prendre en compte l'affichage de l'onglet actif en dessous des onglets
**Avant**
**Apres**
=> Refonte UX/UI: Update UI des section d'onglets des resultats de recherche

tests/utils/test.py, tests/utils/tests.py
Voir le test pour le cas rencontré.
=> `parse_response_to_soup()` : Remplacer également les attributs du nœud parent

itou/users/admin.py, itou/users/models.py, tests/users/test_admin_views.py
Pour facilement identifier les asp_uid modifié manuellement (peut-être d'ailleurs qu'on pourrait se passer de la valeur dans le cas où la valeur par défaut est la bonne).
Cf https://github.com/gip-inclusion/les-emplois/pull/3663#discussion_r1489714429
=> Admin des profils: ajout de la valeur par défaut dans l'help_text

.github/workflows/review-app-creation.yml, .github/workflows/review-app-removal.yml
J'ai changé le nom de l'étiquette pour le faire remonter dans la liste mais cela a cassé le système de recette jetable. Cette PR corrige le problème.
=> Mise à jour du nom des recettes jetables

README.md
Les newbie django comme moi peuvent se retrouver confrontés à un problème bloquant lors du lancement de la commande `make populate_db` s'ils n'ont pas créé les tables avant. Je propose d'ajouter cette petite ligne pour éviter ce problème (et faire ma fièrement première PR sur les emplois sans risquer de tout casser ahah).
=> Proposition d'ajout au readme

itou/asp/fixtures/test_asp_INSEE_communes_factory.json, itou/utils/mocks/address_format.py, itou/www/employee_record_views/views.py, tests/api/__snapshots__/test_geiq.ambr, tests/asp/__snapshots__/test_sync_communes.ambr, tests/asp/factories.py, tests/asp/test_communes.py, tests/users/factories.py, tests/www/employee_record_views/__snapshots__/test_create.ambr, tests/www/employee_record_views/test_create.py
C'est le comportement attendu :), et les utilisateurs vont être content de ne plus avoir à le faire à la main pour les adresses reconnues.
J'ai séparé le test de la correction pour avoir une diff propre du _snapshot_.
J'aurais aimé ne pas avoir à passer `BAN_GEOCODING_API_RESULTS_FOR_SNAPSHOT_MOCK` via `with_mocked_address` et l'utiliser automatiquement en fonction de `for_snapshot` mais je pense que ça va demander de bouger des trucs à plein d'endroits donc on verra plus tard :).
=> Fiche Salarié : Correction du préremplissage de l'adresse depuis les informations candidats

itou/utils/apis/geocoding.py, itou/utils/mocks/geocoding.py, tests/common_apps/address/tests.py, tests/utils/apis/__snapshots__/test_geocoding_api.ambr, tests/utils/apis/test_geocoding_api.py, tests/www/companies_views/test_views.py, tests/www/prescribers_views/test_edit.py
Adresse d'une SIAE impossible a géocoder avec le filtre `postcode` :
- https://api-adresse.data.gouv.fr/search/?q=HOWELL+CENTER&limit=1&postcode=97150
- https://api-adresse.data.gouv.fr/search/?q=HOWELL+CENTER&limit=1
=> Géocodage : Essayer sans le code postal pour les DROM-COM si la BAN ne retourne aucun résultat

itou/api/employee_record_api/viewsets.py, tests/api/employee_record_api/test_throttling.py
=> Augmenter la limite d’appels sur l’API employee_records

itou/approvals/admin_forms.py, itou/approvals/admin_views.py, tests/approvals/tests.py
Pour que ces champs soient toujours remplis et puissent à terme être rendus obligatoires.
=> Délivrer un PASS IAE dans l'admin: remplissage automatique des champs concernant l'origine de la candidature

itou/static/js/sliding_tabs.js, itou/templates/companies/card.html, itou/templates/companies/job_description_card.html, itou/templates/companies/job_description_list.html, itou/templates/companies/members.html, itou/templates/companies/show_financial_annexes.html, itou/templates/layout/base.html, itou/utils/staticfiles.py, tests/www/companies_views/__snapshots__/test_views.ambr
Améliorer le fonctionnement responsif (dropdown avec les items masqués dedans) par un “slider d’onglets”, swipable en mobile
- Maj du thème
- Maj du DOM
- Ajout de js
Avant
Apres
=> Refonte UX/UI: Maj du fonctionnement responsif des onglets

itou/utils/staticfiles.py
Problème de refermerture "automatique".
https://www.notion.so/plateforme-inclusion/1f630a1c1ea54ecdbfd037ca07a7f146?v=6119c6aa4385475a8fbdf8d7f220f19e&p=0218310b60424a7e99110d6e241b8db8&pm=c
Mise a jour du js dans le thème et suppression de l'appel de [la function onResize](https://github.com/gip-inclusion/itou-theme/blob/main/src/javascripts/app.js#L35)
Apparemment, à l'ouverture du collapse un élément interne s'affiche et pousse le contenu, donc "resize" le viewport et relance a nouveau la function.
Supprimer l'appel de la function au resize
Solution imparfaite, mais temporaire, car les sidebars de filtres disparaitront avec la refonte UI
=> Filtre candidatures sur Mobile

Makefile
Souvent, on n'a pas touché aux templates Django et appeler djlint n'est pas nécessaire: autant gagner 10 secondes.
```
❯ time make fix
black config itou tests
All done! ✨ 🍰 ✨
938 files left unchanged.
ruff check --fix config itou tests
find * -type f -name '*.sh' -exec shellcheck --external-sources --format=diff {} + | git apply || true
error: No valid patches in input (allow with "--allow-empty")
djlint --reformat itou
Reformatting 322/322 files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 00:09    
0 files were updated.                                                                                                  
real    0m10,112s
user    1m33,567s
sys     0m1,980s
```
vs
```
❯ time make fast_fix 
black config itou tests
All done! ✨ 🍰 ✨
938 files left unchanged.
ruff …
```
=> Makefile: ajout d'une cible fast_fix

config/settings/base.py, itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/utils.py, itou/www/stats/views.py, tests/www/stats/test_utils.py, tests/www/stats/test_views.py
Expérimentation avec la région.
=> Pilotage : Publier le TB394 "Déclaration d’embauche" pour les SIAE sur la région d’Occitanie [GEN-8121]

itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
Il était prévu que cela se termine aujourd'hui.
=> [GEN-8219] Retirer la bannière promo Mobil Emploi

itou/users/admin.py, tests/users/test_admin_views.py
"Valeur par défaut" n'était pas assez clair.
=> Admin: amélioration du texte d'explication du champs "ID unique envoyé à l'ASP"

Makefile
C'est plus propre et ça évite de polluer la sortie avec le commentaire et un message d'erreur.
=> Makefile: Suppression d'une verrue pour le lancement de `shellcheck`

itou/api/employee_record_api/serializers.py, itou/api/employee_record_api/viewsets.py, itou/employee_record/models.py, itou/employee_record/serializers.py, itou/employee_record/typing.py, itou/templates/employee_record/disable.html, itou/templates/employee_record/includes/employee_record_summary.html, itou/templates/employee_record/reactivate.html, itou/templates/employee_record/summary.html, itou/utils/serializers.py, tests/api/employee_record_api/test_serializers.py, tests/employee_record/__snapshots__/test_serializers.ambr, tests/employee_record/test_notifications.py, tests/employee_record/test_serializers.py, tests/job_applications/factories.py, tests/users/factories.py
La reprise de stock des EITI fait que nous n'avons pas un certain nombre d'informations (pays+commune de naissance et/ou l'adresse postal au format hexa), l'idée originel était qu'il de les faire remplir puis renvoyer par les employeurs mais au vu du nombre (2829+) nous avons décider de réduire la charge pour les employeurs.
Et plutôt que de remplir les `JobSeekerProfile()` pour ces entreprises je me suis dit que c'était mieux de ne pas modifier la données et donc de gérer ça lors de l'envoi.
La quasi totalité des données envoyées dans les notifications n'est pas utilisés du coté de l'ASP mais elles sont tout de même validés donc elles doivent être correcte et cohérentes, je modifie donc les _serializers_ afin de passer sur des données statiques si les champs associés sont manquant. …
=> Fiches salarié : Utiliser des données statiques dans les envois de notification pour éviter des erreurs

itou/templates/apply/includes/job_applications_export_button.html, itou/templates/apply/includes/list_job_applications.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/www/apply/views/list_views.py, tests/www/apply/__snapshots__/test_list.ambr, tests/www/apply/test_list.py
Limiter les rechargements de la page, pour une meilleure expérience utilisateur.
La construction des filtres étant assez coûteuse, on devrait aussi constater
une légère amélioration de performance.
1. Se connecter en tant que prescripteur habilité
1. Aller à la liste des candidatures
1. Filtrer, naviguer entre les pages
=> Filtrer les candidatures des prescripteurs avec HTMX

itou/static/js/job_applications_filters.js
Retiré avec 7fb0f6b0e2b542b7ea50a567d16dea9c2327ea9d.
=> Retirer du code non utilisé pour js-job-applications-filters-button

.vscode/settings.json, itou/api/applicants_api/perms.py, itou/api/applicants_api/serializers.py, itou/api/applicants_api/views.py, itou/templates/dashboard/api_token.html, itou/www/dashboard/views.py, requirements/dev.txt, requirements/test.in, requirements/test.txt, tests/api/applicants_api/tests.py
Des consommateurs de notre API se plaignent de ne pas pouvoir récupérer les candidatures de toutes les structures auxquelles ils appartiennent.
Ajout de deux paramètres optionnels :
- mode_multi_structures
- uid_structures
Ajout de l'identifiant unique des structures dans la page d'information à l'utilisateur (voir capture d'écran ci-dessous).
Mise à jour de la documentation (api/v1/redoc/#tag/candidats/operation/candidats_list).
Technique : utilisation de la bibliothèque [`unittest-parametrize`](https://github.com/adamchainz/unittest-parametrize) pour utiliser la syntaxe de Pytest avec Unittest sans avoir à transformer toutes les classes de test en fonctions. En tous cas pas maintenant. Oui, la flemme, ça compte.
=> API candidats : ajout des paramètres `mode_multi_structures` et `uid_structures`

itou/common_apps/address/forms.py, itou/static/js/address_autocomplete_fields.js, itou/templates/apply/includes/job_application_accept_form.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/create_or_update_job_seeker/step_2.html, itou/templates/apply/submit/hire_confirmation.html, itou/templates/dashboard/includes/edit_job_seeker_info_form.html, itou/utils/mocks/address_format.py, itou/utils/widgets.py, itou/www/apply/forms.py, itou/www/apply/views/submit_views.py, itou/www/dashboard/forms.py, tests/users/factories.py, tests/www/apply/test_process.py, tests/www/apply/test_submit.py, tests/www/dashboard/__snapshots__/tests.ambr, tests/www/dashboard/tests.py
Maintenant que l'autocomplétion des adresses est possible sur la modification du profil d'un candidat (cf https://github.com/gip-inclusion/les-emplois/pull/3046 ), il est temps de la généraliser à tous les formulaires d'adresse.
Dans cette PR, l'autocomplétion de l'adresse est proposée à la création du candidat.
https://www.notion.so/plateforme-inclusion/Autocomplete-des-adresses-Ajouter-l-autocomplete-dans-le-formulaire-de-cr-ation-du-candidat-9f5f67d17713481bb34767fe0a49dd34?pvs=4
On utilise le même formulaire utilisé pour la modification du candidat.
Du code a été refactoré dans le widget en lui-même pour le rendre réutilisable. Il peut être bon de tester que le fonctionnement attendu lors de la modification de l'adresse du candidat …
=> [GEN-8082] Autocomplétion de l'adresse pour la création d'un candidat

itou/employee_record/management/commands/sanitize_employee_records.py, tests/employee_record/test_sanitize_employee_records.py
Depuis #3850 ce nettoyage n'est plus nécessaire et est même à éviter afin de ne pas faire passer des FS "Intégrée" en "Désactivée", ce qui empêcherais l'envoi de notification alors que c'est justement ce qu'on cherche à "corriger".
=> Fiches salarié : Ne plus les désactiver quand `hexa_commune` est manquant

itou/templates/employee_record/includes/list_item.html, itou/utils/templatetags/job_seekers.py, tests/utils/tests.py, tests/www/employee_record_views/test_list.py
=> Liste fiches salariés: correction de l'affichage de la ville du candidat [GEN-277]

itou/employee_record/management/commands/resend_employee_records.py
Lorsque le Siret d'une SIAE change dans l'Extranet IAE elle doit renvoyer **toutes** ses fiches salariés, les ETTI (et les EITI, mais aussi les grosses structures) en ont souvent des centaines ce qui n'est pas vraiment gérable à faire manuellement.
Les SIAE font donc régulièrement des tickets au support nous demandant si nous pouvons les renvoyer, jusqu'à présent nous refusions à cause des règles de validation de l'ASP et que le nombre n'était pas forcément si énorme (quelques dizaines), en plus que toutes n'avaient pas à être renvoyées non plus.
Suite à un TZ (`#11831`) une ETTI se retrouve à devoir renvoyer ~1500 FS, donc testons la procédure de tout renvoyer et qu'elle fasse le tri a posteriori. Cela devrais aussi éviter des demandes "Je ne trouve pas cet employé" car oublié lors de la …
=> Fiches Salarié : Ajout d'une commande afin de renvoyer les fiches salariés pour une SIAE

itou/employee_record/common_management.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/utils/iterators.py, tests/employee_record/__snapshots__/test_transfer_employee_records.ambr, tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr, tests/employee_record/test_transfer_employee_records.py, tests/employee_record/test_transfer_employee_records_updates.py, tests/utils/test_iterators.py
C'est quelque chose qui traîne depuis longtemps (février 2022 de mémoire) et ça permet de faire ceinture-bretelles pour #3872
=> Fiches salarié : Limiter à 1 fichier par envoi

itou/employee_record/serializers.py, tests/employee_record/__snapshots__/test_serializers.ambr, tests/employee_record/test_serializers.py
Oubli de `NullIfEmpty*Field()` pour des champs obligatoire dans #3850, ce qui a révélé d'autres champs problématiques :crying_cat_face:.
=> Fiches salarié : Correction d'oublis pour les données statiques des notifications

itou/templates/dashboard/api_token.html
Pour avertir les utilisateurs de l’option multi-structure est disponible
En attente de https://github.com/gip-inclusion/les-emplois/pull/3527
=> [API CANDIDATS] Message générique sur la page api 

tests/utils/test_cache.py
Avec Docker sous macOS ce n'est pas la même erreur qui est remontée.
Vu avec François : l'essentiel est de matcher l'erreur de connexion.
=> Amélioration du test du cache Redis avec Docker sous macOS

Makefile, config/settings/test.py, tests/openid_connect/inclusion_connect/tests.py, tests/utils/test.py, tests/www/approvals_views/test_includes.py, tests/www/invitations_views/test_company_accept.py, tests/www/invitations_views/test_prescriber_organization.py, tests/www/search/tests.py, tests/www/signup/test_prescriber.py, tests/www/signup/test_siae.py
Pour que ça casse sur la CI plutôt que lors du déploiement en prod ;).
Je suis moyennement convaincu par les `re.sub()` sauvage dans `tests/www/approvals_views/test_includes.py`, j'avais l'idée de réutiliser ce qui est fait dans `parse_response_to_soup()` mais je sais pas si ça vaut le coup :thinking:.
=> CI : Utiliser le même chemin de code que la production

itou/templates/search/siaes_search_results.html
ID retiré dans 9ab58d00895aca7aea48835f1e2e31e95afb5891.
=> Retirer du JS inutilisé pour #siae-number-results

itou/www/apply/views/common.py
Sécurité. https://github.com/gip-inclusion/les-emplois/security/code-scanning/24
=> Supprimer une redirection ouverte des vues d’éligibilité GEIQ

itou/static/js/job_applications_filters.js, itou/templates/apply/includes/list_job_applications.html, itou/templates/apply/list_for_job_seeker.html, itou/www/apply/views/list_views.py, tests/www/apply/__snapshots__/test_list.ambr, tests/www/apply/test_list.py
Limiter les rechargements de la page, pour une meilleure expérience utilisateur.
La construction des filtres étant assez coûteuse, on devrait aussi constater
une légère amélioration de performance.
Comment tester ?
1. Se connecter en tant que candidat (test+de@inclusion.beta.gouv.fr)
2. Aller à la liste des candidatures
3. Filtrer, naviguer entre les pages
=> Filtrer les candidatures des candidats avec HTMX

itou/files/management/commands/configure_bucket.py, tests/files/tests.py
L’accès direct à ces fichiers est interdit depuis mi-octobre 2023. Après environ 6 mois d’attente pour éviter que les liens des emails ne cassent, rendons les réellement privés.
=> Empêcher l’accès anonyme en lecture aux préfixes autres que resume/

.github/pull_request_template.md
Suite à un test sur en précédente PR il a été décider de s'inspirer du [template Carnet de Bord](https://github.com/gip-inclusion/carnet-de-bord/blob/main/.github/pull_request_template.md). L'ajout principal est celui de la partie _Comment tester_.
Inspiration
On met à jour le template de PR en rajoutant de superbes émojis et une nouvelle section « Comment tester ».
=> Amélioration du template de PR Github

itou/templates/static/accessibility.html
Pourquoi ?
Adresse utilisé identique à celle du GIP
---
Remplace https://github.com/gip-inclusion/les-emplois/pull/3874
=> Mise à jour de l'adresse du GIP sur la page accessibilité 

Makefile, requirements/dev-mac.txt
De ce que je comprend de https://github.com/minrk/appnope, il faut importer `appnope` sauf qu'on l'utilise nul part et les utilisateurs de MacOS on _régulièrement_ des problèmes liés à la MAJ de leur venv car seul le fichier `requirements/dev.txt` est modifié donc le timestamp de `requirements/dev-mac.txt` est toujours plus vieux que la dossier du venv.
```
~/betagouv/itou|master> rg appnope
requirements/dev-mac.txt
2:appnope==0.1.3 \
~/betagouv/itou|master>
```
=> Dépendances : Suppression de `appnope` (et du fichier spécifique Mac) car non-utilisé dans le projet

CHANGELOG_breaking_changes.md, Makefile
CleverCloud suit désormais la branche `master` directement.
=> Retirer make deploy_prod

.github/workflows/ci.yml, scripts/create-fast-machine.sh
`master_clever` n’existe plus depuis 4068a0c9d820d58b8f972a2003bb4cd4aa066a91.
=> Retirer des références restantes à master_clever

itou/templates/prescribers/email/must_validate_prescriber_organization_email_body.txt, tests/www/signup/test_prescriber.py
Faciliter la vie du support
1. Démarrer un serveur de dev inclusion-connect
2. Appliquer le patch suivant :
```diff
diff --git a/itou/utils/apis/api_entreprise.py b/itou/utils/apis/api_entreprise.py
index 30b2ed7a4..24c54893a 100644
--- a/itou/utils/apis/api_entreprise.py
+++ b/itou/utils/apis/api_entreprise.py
@@ -45,6 +45,17 @@ def etablissement_get_or_error(siret):
Return a tuple (etablissement, error) where error is None on success.
https://www.sirene.fr/static-resources/htm/siret_unitaire_variables_reponse.html
"""
+    etablissement = Etablissement(
+        name="Cap emploi",
+        address_line_1="12 rue chez moi",
+        address_line_2="",
+        post_code="68000",
+        city="Colmar",
+        department="68",
+        is_closed=False,
+        is_head_office=True,
+ …
```
=> E-mails : Indiquer le type d’organisation prescriptrice dans les demandes d’habilitation [GEN-279]

itou/users/migrations/0003_remove_jobseekerprofile_previous_employer_kind_from_db.py
=> Retirer JobSeekerProfile.previous_employer_kind de la base de données

itou/job_applications/enums.py, itou/job_applications/migrations/0001_initial.py, itou/templates/apply/includes/buttons/refuse.html, itou/templates/apply/process_refuse.html, itou/templates/apply/refusal_messages/did_not_come.txt, itou/templates/apply/refusal_messages/did_not_come_to_interview.txt, itou/templates/apply/refusal_messages/duplicate.txt, itou/templates/apply/refusal_messages/hired_elsewhere.txt, itou/templates/apply/refusal_messages/incompatible.txt, itou/templates/apply/refusal_messages/lacking_skills.txt, itou/templates/apply/refusal_messages/no_position.txt, itou/templates/apply/refusal_messages/non_eligible.txt, itou/templates/apply/refusal_messages/not_interested.txt, itou/templates/apply/refusal_messages/not_mobile.txt, itou/templates/apply/refusal_messages/prevent_objectives.txt, itou/templates/apply/refusal_messages/training.txt, itou/www/apply/forms.py, itou/www/apply/urls.py, itou/www/apply/views/process_views.py, tests/www/apply/test_forms.py, tests/www/apply/test_process.py
- Les employeurs ne personnalisent pas assez le message de refus
- Les employeurs ne distinguent pas assez le message destiné au prescripteur du message destiné au candidat
- Découper le parcours de refus de candidature : précédemment formulaire unique, à présent formulaire en trois parties.
- Une suggestion de message destiné au candidat personnalisée pour chaque motif de refus
- Les logos info qui affichent les tooltips sont maximisés avec la classe `ri-xl` qui cause une différence de taille avec les lignes des motifs de refus qui n'ont pas de tooltips. Je ne suis pas parvenu à fixer le problème autrement qu'à utiliser une grid css (partiellement supportée par bootstrap5 et qui requiert du style inline). Je vous laisse regarder si vous avez une meilleure solution.
- [Réflexions sur la …
=> [GEN-251] Pack de motifs de refus

itou/templates/companies/includes/_card_siae.html, itou/templates/search/siaes_search_results.html
Faciliter la candidature.
Vérification de la pertinence de l’expérimentation via une campagne A/B testing Matomo.
https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=117&period=day&date=yesterday#?period=day&date=yesterday&category=AbTesting_Experiments&subcategory=AbTesting_ManageExperiments&idExperiment=6
1. Rechercher un employeur
2. Si matomo est configuré, une fois sur deux le bouton sera visible. Autrement, retirer la classe `d-none` de l’élément dans le template.
=> Recherche employeur : Afficher le bouton “Postuler” sur la carte entreprise [GEN-238]

tests/employee_record/factories.py, tests/utils/factory_boy.py
Afin de pouvoir utiliser une valeur précise pour un champ `updated_at` dans les tests.
=> Factories : Mixin pour permettre la surcharge des champs `auto_now=True`

requirements/dev.txt
Suite au merge de https://github.com/gip-inclusion/les-emplois/pull/3861, les utilisateurs mac n'ont plus `appnope` installé et cela ne marche que pour `ipython>= 8.18` (cf https://github.com/ipython/ipython/commit/7c18abd9aa05bf0635cf124cd7b4ba867187114d)
Via un `PIP_COMPILE_OPTIONS='-P ipython' make compile-deps`
=> requirements: mise à jour d'ipython

itou/job_applications/enums.py, itou/job_applications/migrations/0001_initial.py, itou/job_applications/models.py, itou/templates/apply/includes/buttons/refuse.html, itou/templates/apply/process_refuse.html, itou/templates/apply/refusal_messages/did_not_come.txt, itou/templates/apply/refusal_messages/did_not_come_to_interview.txt, itou/templates/apply/refusal_messages/duplicate.txt, itou/templates/apply/refusal_messages/hired_elsewhere.txt, itou/templates/apply/refusal_messages/incompatible.txt, itou/templates/apply/refusal_messages/lacking_skills.txt, itou/templates/apply/refusal_messages/no_position.txt, itou/templates/apply/refusal_messages/non_eligible.txt, itou/templates/apply/refusal_messages/not_interested.txt, itou/templates/apply/refusal_messages/not_mobile.txt, itou/templates/apply/refusal_messages/prevent_objectives.txt, itou/templates/apply/refusal_messages/training.txt, itou/www/apply/forms.py, itou/www/apply/urls.py, itou/www/apply/views/process_views.py, tests/www/apply/test_forms.py, tests/www/apply/test_process.py
Meilleure gestion du wizard dans les cas d'usage suivants :
- Ouverture de plusieurs formulaires de refus en simultané sur une même session
- Accès à un step avancé directement par l'URL sans avoir les données précédentes en session
- Ajout de la méthode `get_prefix` pour namespace le storage à une candidature spécifique
- Ajout de vérifications au get/post du wizard pour s'assurer que l'état est conforme par rapport au step courant (commit à part, à squash)
=> Pack de motifs de refus

itou/templates/dashboard/edit_user_info.html, itou/www/dashboard/forms.py, tests/www/dashboard/tests.py
Car on ne les utilise pas.
Assez peu de comptes l'ont d'ailleurs remplis.
On supprime les champs du formulaire et une migration permettra de vider les champs dans un second temps.
Se connecter avec un utilisateur non-candidat et aller sur "Modifier mon profil".
=> Arrêter de stocker les adresses des utilisateurs non-candidats [GEN-1553]

itou/templates/apply/process_accept.html
Le formulaire d'acceptation de candidature utilise également l’autocomplétion d'adresse mais le JS n'y est pas dispo.
Cf https://github.com/gip-inclusion/les-emplois/blob/e722101eb602690f5b4df32a8d906e5b2055311f/itou/templates/apply/submit/hire_confirmation.html#L50-L53
En rajoutant le JS manquant.
Accepter une candidature et voir l'autocomplétion fonctionner.
=> Acceptation de candidature: ajout de JS manquant pour l'autocomplétion d'adresse

itou/static/js/siae_evaluations_sample_selection.js
https://github.com/gip-inclusion/les-emplois/security/code-scanning/19
https://github.com/gip-inclusion/les-emplois/security/code-scanning/20
Il n’y a pas de faille à proprement parler, car l’utilisateur peut bien injecter ce qu’il veut dans le DOM. En revanche, il existe une API plus sûre pour changer le contenu textuel d’un élément, autant l’utiliser. C’est également plus performant.
https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
Jouer le script suivant :
```python
>>> from itou.siae_evaluations.models import EvaluationCampaign, create_campaigns_and_calendar
>>> import datetime
>>> EvaluationCampaign.objects.all().delete()
>>> create_campaigns_and_calendar(datetime.date(2023,1,1), datetime.date(2023,12,31), datetime.date(2024,9,1))
```
1. Se connecter en tant que …
=> Utiliser textContent plutôt que innerHTML

itou/www/apply/views/submit_views.py
Ces clefs ne peuvent plus exister en session depuis un bon moment.
`city_slug` est enlevé au passage car elle ne peut plus exister non plus depuis 810ce0f869132
Vérifier que les parcours de création/mise à jour de candidats fonctionnent correctement.
=> Parcours de candidature: suppression de la rétrocompatibilité avec les anciennes sessions

.github/workflows/review-app-creation.yml
Personne ne remplissait les étapes dans le message de la recette et maintenant on a la section ":desert_island: Comment tester" pour le faire.
Rajouter le tag (ce que je vais faire) et regarder le message posté automatiquement.
=> Github actions: simplification du message de la recette jetable

itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, tests/www/apply/__snapshots__/test_list.ambr
Il ne s’affichait plus, à cause d’un bug.
- Accéder à la liste des candidatures pour un candidat, un employeur et un prescripteur. Tous doivent afficher qui à fait la candidature (par XXX).
=> Carte candidature : Afficher à nouveau le nom de l’émetteur [GEN-1565]

itou/communications/apps.py
Pour faciliter le développement, une synchro automatique des notifications était mise en place au `ready()` lorsque `settings.DEBUG is True`.
Depuis Django 5, le warning suivant est affiché au démarrage :
> RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
Décision prise de retirer la synchro automatique. Il faudra faire un migrate pour synchroniser les notifications.
=> Suppression de la synchro automatique des notifications

itou/templates/dashboard/dashboard.html
Plus personne ne peut la voir depuis 6dd1d32e6eeb3db et la suppression de la variable `ic_activate_url`.
Chercher la variable dans le code et ne pas la trouver :grin: .
=> Tableau de bord: suppression de la bannière Inclusion Connect de mai 2023

itou/templates/apply/process_refuse.html, itou/www/apply/forms.py, itou/www/apply/views/process_views.py, tests/www/apply/test_process.py
Un seul wording "prescripteur" précédemment.
Cf https://itou-inclusion.slack.com/archives/CU8ATF54L/p1713346938777999?thread_ts=1713268571.388719&cid=CU8ATF54L
En fonction du prescripteur on mentionne tantôt "prescripteur" (si habilité), tantôt "orienteur" (non habilité, solo)
- Se connecter en tant que GEIC
- Parcourir [les candidatures](https://c1-review-leo-job-application-refusal-orienteurs-fix.cleverapps.io/apply/siae/list?states=new&states=processing&states=prior_to_hire), s'assurer que dans le parcours de refus (3 étapes) :
- Les mentions "prescripteur" ne concernent que les prescripteur habilités
- Les mentions "orienteur" sont bien présentes pour les orienteurs et orienteurs solo
=> Wording: gestion des orienteurs dans le wizard de refus de candidature

itou/templates/companies/includes/_list_siae_actives_jobs_row.html, itou/templates/companies/includes/_siae_jobdescription.html, itou/templates/employee_record/includes/create_step_5.html
Moins de code, moins de problème.
Vérifier où ces templates sont utilisés et où les variables sont définies.
=> Template: suppression de parties inutilisées

tests/www/approvals_views/__snapshots__/test_includes.ambr, tests/www/approvals_views/test_includes.py
`JobApplicationOrigin` est normalement fourni par le _context processor_ `itou.utils.context_processors.expose_enums`.
=> tests: correction de tests pour mieux correspondre à leur utilisation réelle

itou/templates/apply/process_postpone.html, itou/templates/apply/process_refuse.html, itou/templates/apply/submit/application/resume.html, itou/templates/companies/edit_job_description.html, itou/templates/companies/edit_job_description_details.html, itou/templates/companies/edit_job_description_preview.html, itou/templates/companies/edit_siae.html, itou/templates/companies/edit_siae_description.html, itou/templates/companies/edit_siae_preview.html, itou/templates/dashboard/includes/edit_job_seeker_info_form.html, itou/templates/employee_record/add.html, itou/templates/employee_record/includes/create_step_2.html, itou/templates/utils/templatetags/buttons_form.html, itou/utils/templatetags/buttons_form.py, tests/utils/__snapshots__/test_templatetags.ambr, tests/www/approvals_views/__snapshots__/test_suspend.ambr, tests/www/employee_record_views/__snapshots__/test_add.ambr, tests/www/employee_record_views/__snapshots__/test_create.ambr, tests/www/signup/__snapshots__/test_job_seeker.ambr
Le templatetag acceptait sans broncher la clef `matomo_event` au lieu de celle attendue `matomo_name`
En nommant explicitement toutes les clefs attendues/supportées.
Au passage, la `primary_disabled` était également utilisée à la place de `primary_deactivated` qui était attendue, j'ai tout aligné sur la première.
Aller sur les différents templates pour vérifier l'affichage des boutons avec les bons attributs matomo.
=> Matomo: correctifs de `buttons_form`

itou/templates/invitations_views/create.html
Ajouté en juin 2020 (32a038923d47a4eb2): on voyait alors la liste des invitations en attente sur l'écran de création d'une invitation.
Mais dès juillet 2020 (4862b8136b29afef4) ce n'est plus le cas et la liste des invitations en attente a été ajouté à l'écran de la liste des membres.
`itou/templates/invitations_views/create.html` n'est utilisé que dans 3 vues et aucune ne rajoute la clef `pending_invitations` dans son contexte.
=> Template: suppression de code inaccessible

.github/workflows/notify-slack.yml
=> Notifier #mep-c1 lors d’une mise en prod [GEN-1528]

.github/pull_request_template.md, .github/workflows/mkchangelog.yml, .github/workflows/require-labels.yml, scripts/mkchangelog
Moins de travail manuel.
Utilisation de l’outil en ligne de commande `gh`, qui est disponible par défaut sur les machines des GitHub actions.
<s>Petite tristesse lorsque je me suis aperçu que l’API pull requests ne permet pas de filtrer par date, le script doit donc itérer sur toutes les pull requests. 😢
https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests--parameters</s>
Merci Léo, qui m’a montré l’API `gh search` :)
Ajout d’une action pour vérifier la cohérence des labels des pull requests.
=> Générer le changelog automatiquement depuis GitHub [GEN-1526]

itou/static/js/approvals_filters.js, itou/static/js/job_applications_filters.js, itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/approvals/list.html, tests/www/apply/__snapshots__/test_list.ambr
Ces boutons sont présents dans l’espoir que les utilisateurs sans JS puissent utiliser le site.
Le JavaScript est nécessaire pour que le site fonctionne. Autant le reconnaître et l’assumer. Autrement, on pourrait croire que les utilisateurs sans JS peuvent utiliser le site, alors qu’ils n’ont pas accès au menu déroulant d’authentification, ou au module de recherche d’emploi.
=> Retirer les boutons appliquer dans les filtres

config/settings/base.py
Pour avoir le code HTTP dans les logs.
Le setting `DJANGO_DATADOG_LOGGER_EXTRA_INCLUDE` permet d'inclure les `extra` fourni au logger dans le log JSON.
Dans notre cas, la clef `http.status_code`.
Lancer en dev, enlever le code supprimant le formatter JSON dans config/settings/dev.py et tester une requête.
=> settings: add http.status_code key to request logs

itou/utils/admin.py
Le formulaire d'édition peut être très long en admin et la plupart des actions se font en partie haute.
Évite de scroll tout en bas du form.
https://www.notion.so/plateforme-inclusion/Ajout-d-un-bouton-enregistrer-dans-l-admin-1385ab2419b0439c92ef1d42cc7a1fe3?pvs=4
Django prévoit le coup avec [ModelAdmin.save_on_top](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_on_top) mais ne fournit pas de settings pour le configurer par défaut.
→ ~Monkey patch de ModelAdmin au démarrage de l'app (la surchage du template [ne s'y prête pas bien](https://github.com/django/django/blob/53719d6b5b745dd99b1ab9315afb242f706ebbf1/django/contrib/admin/templates/admin/change_form.html#L40)).~
→ Ajout de l'option à `ItouModelAdmin`
=> [GEN-191] Affichage des boutons enregistrer en haut des formulaires d'admin

.github/workflows/mkchangelog.yml, scripts/mkchangelog
Accidentellement retiré de https://github.com/gip-inclusion/les-emplois/pull/3952. Rajouté sous forme d’une option, pour faciliter le test de la commande en local.
=> Ajouter une option pour générer la pull request avec mkchangelog

itou/templates/apply/includes/job_application_sender_info.html, tests/www/apply/test_process.py
Depuis la dernière mise à jour l’adresse email du prescripteur est visible dans le détail de candidatures coté candidat
Lorsque l'utilisateur connecté est un candidat, on cache dorénavant l'adresse e-mail de l'émetteur si ce dernier n'est pas de type candidat.
=> [GEN-233] Masquage de l’adresse email du prescripteur ou de l'employeur dans la page candidature pour le candidat

scripts/mkchangelog
Autrement, `--publish` demande un argument.
=> Correction de la commande mkchangelog --publish

itou/utils/logging.py
Empêcher de prendre le contrôle d’un compte utilisateur à partir des logs ingérés.
=> Retirer session_key des logs Datadog

itou/www/signup/forms.py
C’est le comportement par défaut.
- Vérifier les champs prénom et nom dans le parcours d’inscription à la plateforme.
=> Retirer les arguments par défaut de FullNameFormMixin

itou/templates/signup/job_seeker_signup.html, tests/www/signup/__snapshots__/test_job_seeker.ambr
Éviter les erreurs de saisie, et être cohérent avec le reste du site.
- Se connecter en tant que candidat
- Depuis le tableau de bord, accéder au profil du candidat
- Vérifier que le prénom est bien demandé avant le nom
=> Profil utilisateur : Demander le prénom avant le nom, pour être cohérent avec le parcours d’inscription

itou/templates/layout/base.html, itou/utils/staticfiles.py
Indiquer aux utilisateurs comment activer JavaScript, afin qu’ils puissent utiliser toutes les fonctionnalités du site (dont des fonctionnalités essentielles, comme la recherche d’employeur).
Désactiver JavaScript, le bandeau doit apparaître en haut des pages, comme sur la capture d’écran ci-dessus.
=> UX/UI : Ajouter une balise `<noscript>` sur le site

itou/approvals/notifications.py, tests/approvals/test_notifications.py
https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1713261492340899
https://www.notion.so/plateforme-inclusion/Notifications-de-relance-des-demandes-de-Prolongation-Privil-gier-les-administrateurs-de-l-organis-c6caa619c19448409a065ef57a116cf2?pvs=4
Priorisation des administrateurs
=> [GEN-1567] Privilégier les administrateurs de l’organisation lors des notifications de relance des demandes de Prolongation

itou/scripts/sql/cta_export.sql
Un export CTA mensuel existe qui est déversé dans Bitwarden. Il faut ajouter le SIRET des structures prescripteurs et employeurs.
https://www.notion.so/plateforme-inclusion/Ajouter-une-colonne-l-extraction-CTA-et-envoyer-le-fichier-chaque-mois-FT-0f7a9457f91d4dd2afb47737cfce3841?pvs=4
=> [GEN-1586] Ajout d'une colonne SIRET à l’extraction CTA 

itou/templates/prescribers/members.html
https://www.notion.so/plateforme-inclusion/C1-Test-r-attribution-des-candidatures-6d9b2be7e1424127afd9270f5ab6c1c3
=> [GEN-1625] Ajout d'un message d'alerte pour inviter à remplir en enquête sur la réattribution des candidatures d’un collaborateur

docker-compose.yml
Pour ne plus avoir des containers qui se relancerais alors que stoppé manuellement.
Changement de l'option `restart` : https://docs.docker.com/compose/compose-file/05-services/#restart
```console
$ docker compose --profile django up
$ docker stop itou_django
$ systemctl restart docker.service
$ docker ps  # Le container itou_django n'est pas présent
```
=> docker: Utiliser `unless-stopped` plutôt que `always`

itou/www/companies_views/views.py
En local, j'ai eu une TypeError car la variable d'environnement n'était pas définie.
Je propose de récupérer les services DI uniquement quand la variable est définie.
Ajout d'une condition
=> [DataInclusion] Ne pas appeler l'API quand l'URL n'est pas définie

tests/www/apply/test_process.py
Certains (longs) tests sont permutés un certain nombre de fois depuis #3914, ce qui engendre un ralentissement.
Randomiser la seconde boucle pour ne conserver qu'une seule raison différente.
=> Réduction de nombre de permutations des subtest apply

tests/approvals/tests.py, tests/conftest.py, tests/openid_connect/inclusion_connect/tests.py, tests/users/test_admin_views.py, tests/utils/test_redirect_legacy_views.py, tests/utils/tests.py, tests/www/apply/test_process.py, tests/www/apply/test_submit.py, tests/www/apply/test_templates.py, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_list.py, tests/www/approvals_views/test_prolongation.py, tests/www/approvals_views/test_prolongation_requests.py, tests/www/approvals_views/test_suspend.py, tests/www/companies_views/test_job_description_views.py, tests/www/companies_views/test_views.py, tests/www/dashboard/tests.py, tests/www/invitations_views/test_company_send.py, tests/www/search/tests.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py, tests/www/signup/test_job_seeker.py, tests/www/test_error.py
Cela permet d'être moins permissif (seules ces erreurs sont tolérées) et également de facilement retrouver tous les tests corrigés lorsqu'on modifie la disponibilité d'une variable.
Et si j'ai le courage de sortir ça dans une lib ou d'intégrer cela à pytest-django, cela sera plus propre.
=> Amélioration du marker `ignore_unknown_variable_template_error` pour autoriser une liste de noms spécifiques

itou/approvals/management/commands/export_pe_api_rejections.py, tests/approvals/test_management_commands.py
Le siret et le type de l'entreprise à l'origine du pass sont stockés sur le modèle depuis quelques mois, autant les réutiliser !
On attend le GO d'eric pour merger
=> Ajout du siret à l'export des rejet d'api PE [GEN-1585]

itou/www/search/views.py, tests/www/search/tests.py
Plusieurs petits problèmes d’affichage, dont les compteurs qui n’étaient pas initialisés (badges vides sur les onglets), bouton retour manquant.
Les problèmes ont été révélés en enlevant le marqueur `ignore_template_errors`.
Afin de mutualiser la construction du contexte entre `form_valid()` et `form_invalid()`, définition d’un `get_context_data()`.
1. Visiter la page `/search/employers/results?city=foo-44`
=> Recherche employeur : amélioration de l’affichage lorsque le formulaire de recherche est invalide

itou/www/apply/views/submit_views.py, itou/www/geiq_eligibility_views/forms.py, tests/www/apply/test_submit.py, tests/www/geiq_eligibility_views/test_forms.py
Le formulaire vérifiait ses arguments, mais deux des trois cas vérifiés étaient impossibles.
Pour le dernier, la vérification a été déplacée dans la vue, pour un peu mieux indiquer le problème (qui ne devrait jamais se produire) aux utilisateurs.
=> Simplifier les vérifications de application_geiq_eligibility

itou/static/js/approvals_filters.js, itou/templates/approvals/includes/list_results.html, itou/templates/approvals/list.html, itou/www/approvals_views/views.py, tests/www/approvals_views/test_list.py
Faciliter la transition vers la nouvelle interface.
```python
from tests.employee_record.factories import EmployeeRecordFactory
EmployeeRecordFactory.create_batch(100, job_application__to_company_id=3850)
```
1. Se connecter en tant que l’EI Garage Martinet
1. Depuis le tableau de bord, suivre le lien “Gérer les salariés et PASS IAE”
1. Vérifier le fonctionnement des filtres
1. Vérifier le fonctionnement de la pagination
=> UX/UI : Filtrer les salariés et PASS IAE de manière plus dynamique 

itou/templates/layout/base.html, itou/utils/context_processors.py, itou/www/error.py, tests/approvals/tests.py, tests/users/test_admin_views.py, tests/utils/__snapshots__/tests.ambr, tests/utils/tests.py, tests/www/test_error.py
```
Failed: Undefined template variable 'matomo_custom_title' in 'itou/templates/layout/base.html'
```
et ses suites.
=> Gérer les variables matomo manquantes dans les tests

itou/templates/search/prescribers_search_results.html, itou/www/search/views.py, tests/www/search/tests.py
Enlever des accès à des variables non définies dans le contexte, s’assurer que la page s’affiche comme prévu.
=> Recherche prescripteur : amélioration de la page lorsque le formulaire est invalide

.github/workflows/require-labels.yml
Pour que l'action `require-labels` se relance lors d'un changement de label, par exemple si on reprend une veille PR et qu'on a déjà _push_ ;).
Sans label : https://github.com/gip-inclusion/les-emplois/actions/runs/8921667281/job/24502236608?pr=4018
Ajout de "no-changelog" : https://github.com/gip-inclusion/les-emplois/actions/runs/8921674884/job/24502262012?pr=4018
Ajouter et enlever les labels sur cette PR.
=> github: Also (re)run `require-labels` on labels changes

itou/templates/search/includes/siaes_search_top.html
Besoin retenu lors d’un atelier métier : ajouter un texte (ou un lien vers la doc) qui explique l’ordre d’affichage des résultats de recherche.
Ajout de 2 modales.
Non affiché si pas de résultats.
Privilégié des `<ol>` dans la modale, également titre et bouton principal moins grands que sur le design mais cohérents avec le reste des modales → À vérifier avec le métier.
---
---
---
---
- https://c1-review-leo-popup-info-sorting.cleverapps.io/search/employers/results?city=tarascon-13
- https://c1-review-leo-popup-info-sorting.cleverapps.io/search/job-descriptions/results?city=tarascon-13&city_name=Tarascon+%2813%29&distance=25
- https://c1-review-leo-popup-info-sorting.cleverapps.io/search/employers/results?city=mars-42&city_name=Mars+%2842%29&distance=5
- …
=> [GEN-274] Ajout d’une explication de l’algorithme de tri dans la liste des entreprises et postes recherchés

itou/employee_record/management/commands/sanitize_employee_records.py, tests/approvals/factories.py, tests/employee_record/__snapshots__/test_sanitize_employee_records.ambr, tests/employee_record/test_sanitize_employee_records.py
Simplification et amélioration suite à #3821.
J'ai ajouté la limite car il y a _un peu_ de backlog :
```
* Checking missing employee records notifications:
- found 16376 missing notification(s)
- done!
```
=> Fiches salarié : Prendre en compte les suspensions dans la détection des notifications ratées

itou/asp/fixtures/test_asp_INSEE_communes_factory.json, itou/common_apps/address/format.py, tests/asp/__snapshots__/test_sync_communes.ambr, tests/asp/test_communes.py, tests/users/test_models.py, tests/www/autocomplete/tests.py
La BAN ne semble pas connaître le code postal de Saint-Martin ce qui crée une erreur lors de la géolocalisation de l'adresse dans les fiches salariés : [LES-EMPLOIS-PROD-1R0](https://itou.sentry.io/issues/5102024422/)
Si la BAN ne nous retourne pas de code postal alors nous allons chercher celui présent dans le référentiel INSEE (`cities.City`).
- Avoir activer la BAN en local
- Embaucher un candidat domicilié à Saint-Martin dans une SIAE
- Créer (sans erreur) la fiche salarié pour ce nouveau salarié
=> Formatage d'adresse : Gérer le cas où la BAN ne connais pas le code postal de la commune (ie. Saint-Martin)

config/settings/base.py
En attendant que l'outil devienne public, ne l'affichons pas en démo.
=> Désactiver GPS en démo

itou/users/admin.py
La méthode `address_in_qpv` ne teste pas la présence de `geocoding_score` avant de le comparer au seuil d'imprécision.
https://itou.sentry.io/issues/5282930811/?project=6164438
Si `geocoding_score` est `None` ou `0`, on considère que l'adresse est non-géolocalisée.
=> Résolution d'un problème entraînant une erreur 500 en admin

itou/templates/search/includes/prescribers_search_results.html, itou/templates/search/includes/prescribers_search_summary.html, itou/templates/search/includes/prescribers_search_title.html, itou/templates/search/prescribers_search_results.html, itou/www/search/views.py, tests/www/search/tests.py
Faciliter la transition vers la nouvelle interface.
1. `/search/prescribers/results?city=rennes-35`
=> UX/UI : Filtrer les prescripteurs habilités de manière plus dynamique

itou/prescribers/enums.py
Actuellement seul le 05 (département renseigné sur l'organisation) est accessible à cette DT.
- Avoir configuré les variables `METABASE_SITE_URL` et `METABASE_SECRET_KEY`.
- Se connecter avec un compte rattaché à une organisation prescriptrice `France Travail` ayant le code SAFIR `04016`.
- Accéder au tableau de bord metabase via l'onglet "Statistique".
=> Statistiques : La Direction Territoriale Alpes de Haute Provence et Hautes Alpes supervise 2 départements (04, 05)

scripts/mkchangelog
Faciliter la mise en cohérence des PRs avec le changelog
=> Mettre à jour le changelog lorsque l’action est lancée à nouveau

itou/common_apps/address/format.py, itou/users/models.py, tests/asp/test_models.py, tests/users/test_models.py
La fonction ne fait pas _juste_ du formatage, elle appelle l'API de la BAN pour faire le gros du travail.
=> App `address` : Renommer `format_address()`

scripts/imports-asp.sh
Éviter de créer de la confusion entre ce qui vient de la DGEFP et ce qui vient de l'ASP, sachant que nous allons avoir 2 sources (car 2 équipes) pour ce même partenaire.
J'ai mis à jour  `c1-imports-config ` pour avoir les deux en même temps le temps de la transition.
- Se connecter sur `c1-worker`
- Vérifier la présence du point de montage `dgefp_shared_bucket`
=> Import ASP : Nom plus explicite pour le point de montage contenant les fichiers de la DGEFP

.pre-commit-config.yaml
Lorsque `pre-commit` se lance à chaque commit, s'il y a une erreur dans un fichier python `ruff` la signale mais ne la corrige pas même s'il peut.
On modifie la configuration `pre-commit` pour laisser `ruff` corriger automatiquement s'il peut.
Lancer `pre-commit install`, rajouter par exemples des lignes vides à la suite des imports d'un fichier et essayer de créer un commit avec ces modifications. `ruff` devrait automatiquement enlever les lignes inutiles.
=> Configurer `ruff` pour qu'il corrige les erreurs automatiquement

itou/siae_evaluations/admin.py
Impossible de charger les pages de l'admin  sans cela : https://emplois.inclusion.beta.gouv.fr/admin/siae_evaluations/evaluatedadministrativecriteria/
=> Contrôle a posteriori : Modification du champ preuve dans l'admin en RO

itou/templates/layout/base.html, tests/utils/__snapshots__/tests.ambr
Segmenter les utilisateurs par type dans Matomo.
Utilisation de custom dimensions.
https://matomo.inclusion.beta.gouv.fr/index.php?module=CustomDimensions&action=manage&idSite=117&period=day&date=yesterday#/list
https://matomo.org/guide/reporting-tools/custom-dimensions/
https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=220&period=day&date=yesterday#?idSite=220&period=day&date=yesterday&segment=dimension1%3D%3Demployer;dimension3%3D%3DEI&category=General_Actions&subcategory=Events_Events
1. Naviguer sur la review app ou sur la PR, en s’assurant que les Matomo est bien configuré
2. S’assurer de déclencher des évènements (par exemple, démarrer une candidature)
3. Sur Matomo, [créer un segment](https://matomo.org/guide/reporting-tools/segmentation/) pour …
=> Analytics: Ajouter le type d’utilisateur et le type d’organisation à Matomo [GEN-249]

itou/templates/dashboard/api_token.html
Éviter les confusions.
1. Se connecter en tant que l’EI
2. Depuis le dropdown du « Mon espace », aller sur « Accès aux API »
3. Voir le message d’avertissement à destination des utilisateurs de l’API `employee-records`
=> API : Indiquer de filtrer par SIRET sur l’API `employee-records` et non `candidats_list`

itou/job_applications/migrations/0003_workaround_clever_dangerous_domain_ms.py
Edge affiche une alerte de sécurité lorsque l’utilisateur est redirigé vers https://cellar-c2.services.clever-cloud.com, qui rend l’accès aux CVs difficile.
Clever a activé un contournement temporaire via un domaine alternatif : par.cellar.clever-cloud.com.
=> Candidatures : Utiliser un autre domaine pour le lien vers le CV [GEN-1628]

itou/approvals/models.py, tests/approvals/test_admin.py
Si un candidat avait émit plusieurs candidatures vers une entreprise, son PASS était listé une fois par candidature.
`Exists`
Comparer `/admin/approvals/approval/?assigned_company=11919&o=2.-6` entre la prod et cette branche.
=> Admin : Éviter les doublons lorsqu’on liste les PASS IAE d’une entreprise

itou/www/autocomplete/views.py
Actuellement l'autocomplete GPS des utilisateurs pour ajouter un bénéficiaire est accessible à tout le monde qui connaît l'URL.
On le restreint au feature flag `GPS_ENABLED` et on requiert que cela soit un professionnel qui est connecté.
Accéder à l'url `/autocomplete/gps_users?term=a` lorsque l'on est candidat ne devrait rien retourner.
=> [GPS] L'autocomplete des utilisateurs ne devrait pas être accessible à tout le monde

.github/pull_request_template.md
Améliorer la cohérence du journal des modifications.
=> Ajouter les catégories fréquentes au gabarit de PR

itou/eligibility/models/geiq.py, itou/eligibility/models/iae.py, itou/www/apply/views/process_views.py, tests/www/apply/test_submit.py
Le seul endroit où `for_job_seeker` est utilisé peut être simplifié en utilisant directement `for_job_seeker_and_siae` avec `siae=None`.
Comme `for_job_seeker` n’est plus utilisé en dehors des tests, la méthode a été supprimée.
=> Remplacer EligibilityDiagnosis.for_job_seeker{,_for_siae}

tests/www/apply/test_process.py
```
__________ ProcessViewsTest.test_details_for_unauthorized_prescriber ___________
[gw0] linux -- Python 3.11.9 /home/runner/work/les-emplois/les-emplois/.venv/bin/python3.11
self = <tests.www.apply.test_process.ProcessViewsTest testMethod=test_details_for_unauthorized_prescriber>
args = (), kwargs = {}
prescriber = <User: Helen GRIFFIN — email1226@domain.com>
job_application = <JobApplication: b74a28c7-c4af-41d7-92a1-ff911dfae110>
url = '/apply/b74a28c7-c4af-41d7-92a1-ff911dfae110/prescriber/details'
response = <HttpResponse status_code=200, "text/html; charset=utf-8">
def test_details_for_unauthorized_prescriber(self, *args, **kwargs):
"""As an unauthorized prescriber I cannot access personnal information of arbitrary job seekers"""
prescriber = PrescriberFactory()
job_application = …
```
=> Correction d’un échec de test_details_for_unauthorized_prescriber

itou/templates/siae_evaluations/evaluated_job_application.html, itou/templates/siae_evaluations/evaluated_siae_detail.html, itou/templates/siae_evaluations/evaluated_siae_sanction.html, itou/templates/siae_evaluations/includes/evaluation_data.html, itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html, itou/templates/siae_evaluations/includes/list_item.html, itou/templates/siae_evaluations/institution_evaluated_siae_list.html, itou/templates/siae_evaluations/siae_select_criteria.html, itou/templates/siae_evaluations/siae_upload_doc.html, itou/www/siae_evaluations_views/urls.py, itou/www/siae_evaluations_views/views.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py, tests/www/siae_evaluations_views/test_views.py
Certaines pages n'étaient accessibles que pour les institutions mais le lien était présent dans la page des employeur
et le commentaire des la DDETS manquait
Détourner http://127.0.0.1:8000/admin/users/user/511
- Contrôle à posteriori
- Historique
- Campagne de contrôle a posteriori du 01/01/2022 au 31/12/2022 
- Revoir les 2 auto-prescriptions
- -> Plus de 404 :+1: 
- Revoir ses justificatifs 
- -> Présence du commentaire de la DDETS
=> Contrôle a posteriori : donner l'accès aux pièces justificatives des contrôles précédents aux employeurs

itou/approvals/models.py
Afin de pouvoir retrouver le PASS lié à des suspensions/prolongations supprimés dans l'admin (car les logs de l'admin Django contienne le champ `object_repr`)
Supprimer une prolongation dans l'admin et aller regarder dans la table des logs.
=> Ajout du numéro de PASS dans les représentations techniques des Supension & Prolongation

tests/www/companies_views/test_views.py
C'est a priori ce qui était souhaité même si en l’état du code, l'ancienne forme fonctionne également car on fait `rome_code not in rome_codes` et  `"N1101" not in "N1101"` ou `"N1101" not in ("N1101",)` retournent la même chose
=> tests: correction d'un appel à create_test_romes_and_appellations call

itou/www/error.py, tests/www/test_error.py
Des échecs de test plus clairs.
=> Ajouter des context processors à www/error.py

itou/templates/companies/includes/_card_siae.html, itou/templates/search/siaes_search_results.html
Éviter de devoir consulter les métiers de l’entreprise pour envoyer une candidature à une entreprise.
1. Faire une recherche d’employeur depuis la page d’accueil
2. Constater la présence du bouton postuler sur chaque entreprise dans les résultats
=> UX/UI : Postuler pour une entreprise directement depuis les résultats de recherche employeur [GEN-1645]

itou/api/applicants_api/views.py
Pour que les utilisateurs puissent copier/coller des requêtes qui fonctionnent.
=> API : Correction d’une typo dans les URLs d’exemple de l’API candidats

itou/www/dashboard/views.py, tests/gps/tests.py, tests/www/dashboard/tests.py, tests/www/signup/test_password.py
Compléter les données, faciliter les échanges avec les autres plateformes étatiques.
1. Saisir une civilité pour Jacques Henry via l’admin http://localhost:8000/admin/users/user/2/change/
2. Se connecter en tant que Jacques Henry (compte candidat de la démo)
3. Vérifier que le candidat est redirigé vers la page de profil, où l’adresse, le prénom et le nom sont requis.
=> Demandeur d’emploi : les champs prénom, nom et adresse sont requis [GEN-1620]

tests/www/apply/test_geiq.py, tests/www/approvals_views/test_pe_approval.py
Pour que les `assertNotContains` restent pertinents.
=> tests: association de quelques `assertNotContains` de plus à leur `assertContains`

itou/approvals/admin.py, itou/users/admin.py
Faciliter l’identification des doublons pour le support, et la recherche dans l’admin en général.
En ignorant les accents dans les prénoms et noms.
Débrouillez-vous, c’est l’admin django 🙊.
=> Admin : Ignorer les accents lors de la recherche par prénom ou nom [GEN-1627]

itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/stats/utils.py, itou/www/stats/views.py
Les stats ETP employeur (TB 128) étaient désactivées depuis un moment. Cette PR introduit enfin une nouvelle version (TB 440) prête à être testée par une liste blanche d'employeurs (Groupe SOS, 60 SIAE environ).
- Voir et valider aussi https://github.com/gip-inclusion/itou-secrets/pull/77 qui accompagne cette PR.
=> Pilotage : Ouverture d'une nouvelle version des stats ETP employeur à une liste blanche (Groupe SOS)

itou/api/geiq/serializers.py, itou/asp/management/commands/sync_communes.py, itou/users/models.py, itou/utils/staticfiles.py, itou/utils/widgets.py, itou/www/invitations_views/views.py, pyproject.toml, tests/approvals/test_notify_pole_emploi.py, tests/conftest.py, tests/job_applications/factories.py, tests/users/test_models.py, tests/utils/test_templatetags.py, tests/www/apply/test_process.py, tests/www/dashboard/tests.py, tests/www/stats/test_views.py, tests/www/test_security.py
Pour utiliser du python moderne souvent plus concis (sachant que beaucoup des règles sont gérées par le `--fix`)
Plus de conf dans `pyproject.toml`.
Écrire l'ancienne version et lancer `ruff check`/`ruff check --fix`.
=> ruff: activation des règles de pyupgrade

itou/utils/logging.py, tests/utils/tests.py
Afin de faciliter le debug, ou pour sortir des stats d'utilisation de fonctionnalité par structure.
Assez facilement avec la méthode `json_record`.
Malheureusement la partie test a été plus laborieuse car `caplog` ne peut pas être utilisé (l'enrichissement du log se passe dans le formatter) et `capfd`/`capsys` n'ont pas voulues fonctionner: https://github.com/pytest-dev/pytest/issues/5997
Commenter cette ligne:
https://github.com/gip-inclusion/les-emplois/blob/9e446412ed76ecd31342da3d6e4e3f427adb0ead/config/settings/dev.py#L73
et faire des requêtes avec un utilisateur ayant une organisation active.
=> logging: ajout de l'organisation courante de l'utilisateur dans les logs JSON

itou/utils/tasks.py, tests/utils/test_emails.py, tests/utils/tests.py
Lorsque l’envoi d’un email parmi la liste des emails à envoyer échoue, tous les emails sont renvoyés. On ne voudrait réessayer que l’email qui n’a pas pu être envoyé.
En gérant chaque envoi indépendamment, pour que la tâche qui soit réessayée ne gère qu’un seul email.
Changement de signature de la fonction `_async_send_messages` en `_async_send_message`, pour indiquer qu’un seul message est attendu.
L’ancienne tâche est préservée pour quelque temps, pour que les tâches en attente puissent être exécutées.
=> Générer une tâche d’envoi d’email par email

.github/pull_request_template.md, itou/templates/static/legal/privacy.html
Ne pas laisser croire aux utilisateurs que le service tire des revenus de la publicité.
=> Vie privée : retrait de la mention des publicités Google, qui n’ont jamais été servies par le site

itou/files/management/commands/configure_bucket.py
https://github.com/gip-inclusion/les-emplois/pull/4089
=> Correction de l’URL MinIO dans `configure_bucket`

itou/templates/account/login_job_seeker.html
Voir https://www.notion.so/plateforme-inclusion/BOOST-France-Travail-Changer-le-logo-Pole-emploi-connect-a3bd75cbcc2348eb9d406b5ee55b872e?pvs=4
Je ne lie pas la PR parce que la grande partie du ticket n'est pas encore faisable (changer le logo PE connect)
Cliquer sur "Se connecter" -> "Candidat"
=> UX/UI: Améliorer le titre de section de connexion avec France Travail

itou/utils/tasks.py, requirements/dev.txt, requirements/test.in, requirements/test.txt, tests/utils/test_emails.py
Éviter de perdre des emails, ce qui peut-être très gênant pour les utilisateurs.
https://anymail.dev/en/stable/sending/django_email/#refused-recipients
https://anymail.dev/en/stable/sending/anymail_additions/#anymail.message.AnymailStatus
=> Notifications : Réessayer d’envoyer les emails lorsque Mailjet indique un problème

itou/www/invitations_views/views.py, tests/www/invitations_views/test_company_accept.py, tests/www/invitations_views/test_new_user.py
On n'a plus d'invitation valide crée avant cette date.
remplacer  `employer` par `siae_staff` dans le lien d'invitation
=> Inscription: Nettoyage d'un code de rétro-compatibiité

itou/openid_connect/pe_connect/views.py
Améliorer une erreur snetry 
https://itou.sentry.io/issues/4537508816/?project=6164438&query=is%3Aunresolved+level%3Aerror&referrer=issue-stream&statsPeriod=14d&stream_index=11
On verra dans un second temps si on la conserve et on échange avec PR, ou si on vire le logger
=> Connexion: Améliorer un logger d'erreur avec France Travail Connect

Makefile
Définir l’environnement via les settings Django au lieu de se baser sur les variables `PG*`.
Refs https://github.com/gip-inclusion/les-emplois/pull/4093
Utilisation de l’outil `dbshell` de Django.
Désactiver les variables `PG*` de son environnement (cas d’un dev arrivant sur le projet).
=> Utiliser dbshell pour charger les fixtures SQL

itou/approvals/admin.py
Simplifier la vie du support en n'ayant moins besoin de faire des calculs de dates à la main.
Champs supplémentaires dans le `ModelAdmin` et les `Inlines`.
- Se connecter sur l'admin
- Regarder un ou plusieurs PASS IAE ayant des suspensions/prolongations
=> Admin : Ajout du reliquat pour les PASS IAE et de la durée pour les suspensions et prolongations

itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
Ticket nochon : https://www.notion.so/gip-inclusion/Mettre-un-encart-pour-promouvoir-webinaire-sur-les-emplois-dans-la-page-stats-du-pilotage-pour-les-M-107032dff4664c298fdbc25cf40d1f16?pvs=4
Encart supprimé dans ~2 semaines.
=> Pilotage : Encart de promotion du webinaire pour les ML / Cap emploi & les acteurs AHI pour 3 régions spécifiques

itou/templates/approvals/prolongation_requests/list.html, itou/templates/approvals/prolongation_requests/show.html, tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr, tests/www/approvals_views/test_prolongation_requests.py
Ce cas de figure peut arriver lorsque le script import siae fait du zèle.
#3150 devrait permettre d'éviter que de nouveaux cas apparaissent.
https://itou.sentry.io/issues/5414626200/?project=6164438&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=3
Voir https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1716818805256809
=> Demandes de prolongation: Gérer le cas où l'entreprise déclarante n'existe plus

itou/users/apps.py
Pour corriger le test flaky dans la CI et probablement un trou dans la raquette en prod.
=> Statistiques: Correction d'un code de dénormalisation

itou/companies/management/commands/_import_siae/utils.py, tests/companies/test_import_siae_command.py
L’antenne crée pour une utilisatrice a été supprimée deux fois par l’import EA. Avant la seconde suppression, la structure avait reçu des candidatures, et l’utilisatrice avait reçu des emails de notification, mais la commande a supprimé à la fois la structure et les candidatures associées.
https://plateforme-inclusion.zendesk.com/agent/tickets/14669
Pour éviter que le problème ne se produise :
- empêchons la suppression s’il y a des candidatures.
- étendons la période d’inactivité à 1 an au lieu de 3 mois
=> Limiter la suppression des SIAE inactives dans l’import ASP

itou/users/forms.py, tests/www/dashboard/tests.py
Pour éviter la saisie d'identifiant invalide, pouvant notamment bloquer l'envoi des fiches salarié à l'ASP.
Depuis https://github.com/gip-inclusion/les-emplois/pull/3485 et le déplacement des champs du modèle `User` au modèle `JobSeekerProfile`, les validateurs du champs `pole_emploi_id` n'étaient plus appelés à la validation du formulaire.
La modification du mixin `JobSeekerProfileFieldsMixin` corrige cela.
Se connecter en tant que candidat et ne pas réussir à saisir un identifiant invalide (contrairement à ce qu'il se passe sur la démo).
=> Demandeur d’emploi: empêcher la saisie d'un identifiant France Travail invalide

itou/approvals/models.py, itou/approvals/utils.py, itou/templates/approvals/detail.html, itou/users/models.py, itou/www/approvals_views/views.py, tests/approvals/tests.py, tests/users/test_models.py, tests/www/approvals_views/test_detail.py, tests/www/approvals_views/test_pe_approval.py, tests/www/approvals_views/test_suspend.py
Pour éviter de consommer pour rien un PASS et de solliciter le support
=> PASS IAE: Permettre de suspendre un PASS quand le candidat a été embauché dans une structure hors IAE (GEIQ par exemple) [GEN-1665]

itou/templates/companies/includes/_card_jobdescription.html, itou/templates/companies/includes/_list_siae_actives_jobs_row.html, itou/utils/staticfiles.py
Mauvais rendu en mobile des cartes de résultats “cartes postes ouverts au recrutement"
Mise a jour du theme et du DOM
**Avant**
**Apres**
=> UX/UI : Correction des cartes postes ouverts au recrutement sur mobile

tests/utils/test_emails.py
Faciliter la maintenance des tests, en utilisant une fausse réponse consolidée.
=> tests: Définir des fixtures pour les réponses Mailjet

config/settings/test.py
Parce qu’autrement, le lien vers le Redis ne se fait pas, les tests et certaines fonctionnalités sont indisponibles.
1. `docker-compose --profile django up`
2. `make shell_on_django_container`
3. `make test`
La commande doit s’exécuter avec succès.
=> Corriger le REDIS_URL dans l’environnement docker

docker-compose.yml
> Compose prefers the most recent schema when it's implemented.
https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete
=> Corriger l’avertissement de docker-compose sur la version

itou/companies/admin.py
On pourrait croire que cette dépendance n’est pas utilisée.
https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1715000077912989
=> Admin : Commenter l’utilisation de import_export pour les entreprises

itou/utils/context_processors.py, tests/utils/__snapshots__/tests.ambr, tests/utils/tests.py
Suivi utilisateur plus exploitable, voir le message de commit pour les détails.
=> Retirer le paramètre city de Matomo

itou/www/approvals_views/forms.py
=> UI : Correction du texte du placeholder de recherche salarié dans la liste des salariés

itou/templates/dashboard/dashboard.html
Éviter d'afficher une section vide :
Se connecter en tant qu'institution partenaire
=> Tableau de bord: Retrait d'un section vide pour les institutions [GEN-1714]

itou/metabase/tables/users.py, itou/metabase/tables/utils.py, tests/metabase/management/test_populate_metabase_emplois.py
Pour pouvoir ajouter des informations à la table `utilisateurs` utilisée par le pilotage
Pour permettre les actions de mailing personnalisés avec le nom et prénom
On renomme la source en `utilisateurs_v0` et on garde le nom `utilisateurs` pour la table enrichie côté pilotage
On ajoute les champs nom et prénom
=> Modification du nom de la table utilisateurs et ajout des champs nom et prénom

itou/www/apply/forms.py, itou/www/dashboard/forms.py
Éviter la création de comptes candidats avec l'adresse e-mail de prescripteurs ou employeurs. 
Modifier le label du champ “Adresse e-mail du candidat*” par “E-mail personnel du candidat*”
=> Demandeur d’emploi : Mise à jour du label adresse e-mail candidat pour préciser qu’elle doit être personnelle

.gitignore, CHANGELOG_breaking_changes.md, docs/developing.md, docs/environment.md
Faciliter la mise en place de l’environnement de dev.
=> Recommander d’utiliser direnv pour le dev local

itou/templates/companies/hx_dora_services.html, itou/utils/apis/data_inclusion.py, itou/www/companies_views/urls.py, itou/www/companies_views/views.py, tests/utils/apis/test_data_inclusion_api.py, tests/www/companies_views/__snapshots__/test_views.ambr, tests/www/companies_views/test_views.py
Data.Inclusion change ses métriques et son mode de consommation des APIs.
Les endpoints de recherche et d eliste sont soit dépréciés, soit ils vont significativement réduire les champs disponibles.
Les appels à l'endpoint de détail d'un service sont qualifiants et sont la méthode préconisée à tous nos clients (dont Les Emplois) pour appeler data⋅inclusion.
Par simplicité nous préférons éviter de recourir à un proxy; la logique étant que de toutes manières, un client devra faire un appel pour récupérer des champs étendus (contact info, etc)
Ceci permet de comptabiliser les appels réellement qualifiants.
Le champ `lien_source`  en particulier va disparaître; nous allons donc devoir modifier la proposition initiale de Valentin pour effectuer un appel RETRIEVE avant de renvoyer vers ce …
=> Fiche entreprise / Fiche de poste : appel GET à data.inclusion au clic d'un lien

.gitignore
cf https://github.com/gip-inclusion/les-emplois/commit/57a0776b236021ee8d28daeb65234684e6db37ef
=> Local: ignorer temporairement le .envrc.local pour éviter les erreurs d'inattention

README.md
Faciliter l’installation du projet.
=> Ajout de GDAL dans le README

itou/templates/dashboard/includes/gps_card.html, itou/templates/gps/my_groups.html, tests/gps/__snapshots__/tests.ambr, tests/gps/tests.py, tests/users/factories.py
Mise en place d'un challenge pendant l'Open Lab de jeudi ! Les utilisateurs de GPS (des professionnels uniquement pour le moment) sont incités à inviter un maximum de partenaire jusqu'au prochain Open Lab.
Ajout d'un bouton dirigeant vers un formulaire Tally.
Se connecter en tant que prescripteur. Aller tout en bas du tableau de bord et dans la page listant les bénéficiaires.
=> GPS : ajout d'un lien vers Tally pour inviter des partenaires

itou/gps/models.py, itou/static/js/gps.js, itou/templates/apply/includes/_submit_title.html, itou/templates/apply/submit/create_or_update_job_seeker/step_1.html, itou/templates/apply/submit/create_or_update_job_seeker/step_2.html, itou/templates/apply/submit/create_or_update_job_seeker/step_3.html, itou/templates/apply/submit/create_or_update_job_seeker/step_base.html, itou/templates/apply/submit/create_or_update_job_seeker/step_end.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/dashboard/includes/gps_card.html, itou/templates/gps/includes/confirm_modal.html, itou/templates/gps/join_group.html, itou/templates/gps/my_groups.html, itou/www/apply/forms.py, itou/www/apply/views/submit_views.py, itou/www/gps/forms.py, itou/www/gps/views.py, tests/gps/__snapshots__/tests.ambr, tests/gps/test_create_beneficiary.py, tests/gps/tests.py
Nous souhaitons pouvoir ajouter des bénéficiaires dans GPS qui ne sont pas déjà dans les emplois.
Nous réutilisons le parcours d'enregistrement d'une candidature classique pour créer le `job_seeker` et le `job_seeker_profile` nécessaires à GPS. Puisque nous n'avons pas besoin de créer de candidature pour GPS, nous bifurquons de nouveau vers GPS avant la fin du parcours d'enregistrement et de la création de candidature, une fois le groupe de suivi créé ou complété.
Pour ce faire on rajoute un query parameter `is_gps` dans les url concernées.
- Se connecter avec l'EI et se rendre sur la page d'ajout d'un bénéficiaire https://c1-review-celinems-gps-create-beneficiary.cleverapps.io/gps/groups/join?back_url=/dashboard/
- Rentrer le nom d'un bénéficiaire inconnu (aaaaaaaaaaaaaaaa par exemple) …
=> GPS : création d'un bénéficiaire

config/settings/base.py, config/settings/test.py
Pour réparer l’environnement de test sans `.envrc`.
=> Définir la valeur par défaut de REDIS_URL dans base.py

config/settings/base.py, itou/templates/dashboard/dashboard.html, itou/utils/settings_context_processors.py, itou/www/autocomplete/views.py, itou/www/gps/views.py, tests/gps/tests.py
L'expérimentation GPS est lancée sur la France entière demain ! :tada:  
En supprimant la variable GPS_ENABLED.
=> Lancement de GPS !

itou/templates/apply/submit_step_check_job_seeker_nir.html
=> Ajouter un espace entre deux mots dans l'encart info bleu du NIR [GEN-1750]

itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
Après 3 mois et une campagne de communication, les EITI sont informées.
=> UX/UI : Retirer le bandeau d’information pour le passage aux fiches salarié des EITI

itou/templates/apply/submit_step_check_job_seeker_nir.html
La nouveauté aura bientôt un an, elle n’a plus besoin d’être mise en valeur.
Attirer l’attention sur les vraies alertes.
=> UX/UI : Remplacer l’alerte nouveauté du parcours déclarer une embauche/candidature par un texte explicatif

itou/templates/signup/prescriber_request_invitation.html
Ce texte d’information n’a pas besoin d’une mise en valeur particulière. Avoir moins d’alertes permet de renforcer les alertes restantes.
=> UX/UI : Transformer l’alerte d’information à la demande d’invitation prescripteur en du texte simple

itou/templates/signup/prescriber_check_already_exists.html
Définir toutes les alertes dans le bloc messages.
=> UX/UI : Déplacer l’alerte de prescriber_check_already_exists dans le bloc messages

itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
https://www.notion.so/gip-inclusion/Mettre-un-encart-pour-promouvoir-webinaire-sur-les-emplois-dans-la-page-stats-du-pilotage-pour-les-S-800a904071904de1bd68711b312b320e?pvs=4
Léger réusinage au passage afin de gérer les dates d'affichage sans avoir besoin de :calendar: et de :brain: les jours J.
Je nettoyais les deux (bientôt) expirés la semaine prochaine ;).
=> Pilotage : Mettre un encart pour promouvoir un webinaire pour les SIAE

itou/emails/admin.py
0 correspond à une erreur, 1 correspond à un réussite. Je vois déjà Xavier rire suite à https://github.com/gip-inclusion/les-emplois/pull/4180#discussion_r1633214062
=> Admin : Échanger les labels pour le filtre “Envoyé au fournisseur d’e-mail”

config/settings/base.py
https://www.notion.so/gip-inclusion/Donner-acc-s-au-CD-31-de-la-Haute-Garonne-l-acc-s-2-TB-priv-s-2c720d311b7a4e25aac38f9b1afd17ea?pvs=4
=> Pilotage: Donner accès au CD-31 de la Haute-Garonne l’accès à 2 TB privés

itou/templates/dashboard/dashboard.html, itou/templates/layout/base.html
Les messages d’alertes sont plutôt liés au contenu d’une page. Pour les messages globaux, un nouveau composant permet de les afficher en bannière et de les retirer du contenu de la page.
Voir le composant dans le thème : https://zeroheight.com/85c89893b/p/0775de-alerts/t/23587a
=> UX/UI : Utiliser un bandeau d’alerte globale pour la refonte

itou/templates/prescribers/list_accredited_organizations.html
Diminuer le nombre d’alertes sur le site, pour attirer l’attention lorsqu’il y a une alerte.
=> UX/UI : Remplacer l’alerte de la liste des organisations accréditées par le conseil départemental par un bloc d’information

itou/templates/apply/list_of_available_exports.html, tests/www/apply/__snapshots__/test_list_for_prescriber.ambr, tests/www/apply/__snapshots__/test_list_for_siae.ambr
Diminuer le nombre d’alertes sur le site, pour attirer l’attention lorsqu’il y a une alerte.
=> UX/UI : Remplacer le bandeau promotionnel « Besoin d’un chiffre » par un bloc d’information

itou/www/dashboard/views.py, tests/www/dashboard/tests.py
On a régulièrement des membres de l"équipe qui se retrouvent dessus par erreur (sans doute suite à un détournement + libération de l'utilisateur + retour arrière dans le navigateur).
cf https://itou.sentry.io/issues/4703990078/events/88b25d3585bb4907b66eb4b9f926deed/activity/?notification_uuid=bc1343fd-ad48-4912-bd4a-3422fcbaf67f&project=6164438&referrer=previous-event
=> Correction d'une 500 sur la page de migration IC

itou/templates/siae_evaluations/evaluated_job_application.html
Pour simplifier le support j'imagine :)
=> Contrôle a posteriori: Ajout d'un lien contacter le support si un prescripteur souhaite retirer des justificatifs attendus lors du contrôle [GEN-8]

itou/emails/tasks.py
Retirer un effet de bord à l’import du module de tâche.
Centraliser la configuration de `logging`.
```diff
diff --git a/tests/emails/test_tasks.py b/tests/emails/test_tasks.py
index 8158a9644..f2120c6f7 100644
--- a/tests/emails/test_tasks.py
+++ b/tests/emails/test_tasks.py
@@ -58,6 +58,8 @@ class TestAsyncSendMessage:
requests_mock.post(f"{anymail_mailjet_settings.ANYMAIL['MAILJET_API_URL']}send", json=success_response)
_async_send_message(email.pk)
assert self.EXC_TEXT not in caplog.text
+        # Huey INFO level is very verbose, make sure it doesn’t log.
+        assert caplog.text == ""
fresh_email = Email.objects.get(pk=email.pk)
self.assert_fields_unchanged(email, fresh_email)
assert fresh_email.esp_response == success_response
```
Jouer avec la variable d’environnement …
=> Retirer un doublon de logging.setLevel dans emails.tasks

.envrc
Aurait du être retiré avec 57a0776b236021ee8d28daeb65234684e6db37ef.
=> Retirer le fichier .envrc

config/settings/dev.py
1. Vérifier que vous n’exportez pas `API_BAN_BASE_URL` dans votre environnement.
2. Démarrer un serveur local
3. Créer un compte candidat
4. Remplir l’adresse du compte créer, l’autocomplétion de la BAN devrait fonctionner.
=> Ajouter API_BAN_BASE_URL au CONNECT_SRC de la CSP dans les settings de dev

tests/institutions/tests.py, tests/utils/tests.py, tests/www/siae_evaluations_views/test_institutions_views.py
Avec `--randomly-seed=824007989` ou `--randomly-seed=1838683268` la contrainte `unique_ddets_per_department` 💥
=> tests: correction d'un test instable 

itou/templates/dashboard/dashboard.html
Tracker le nombre de clic sur chaque onglet indépendamment 
Ajout du tags Matomo sur les onglets du "Tabelau de bord"
=> Employeur: Ajout de marqueurs Matomo sur certains onglets

tests/siae_evaluations/test_models.py
Parce que c'est pénible.
`FAILED tests/siae_evaluations/test_models.py::EvaluationCampaignManagerTest::test_create_campaigns_and_calendar - django.db.utils.IntegrityError: duplicate key value violates unique constraint "unique_ddets_per_department"`
Cf https://github.com/gip-inclusion/les-emplois/actions/runs/9566541131/job/26372076377
=> tests: correction d'un autre test instable

itou/communications/__init__.py, itou/geiq/notifications.py, itou/templates/geiq/email/to_institution_assessment_submitted_body.txt, itou/templates/geiq/email/to_institution_assessment_submitted_subject.txt, itou/www/geiq_views/views.py, tests/www/geiq_views/tests.py
Pour que les membres des DDETS/DREETS soient au courant.
=> GEIQ: ajout d'une notification aux DDETS/DREETS lors de la transmission d'un bilan d'exécution [GEN-1739]

itou/www/approvals_views/views.py, tests/www/approvals_views/test_prolongation_requests.py
https://itou.sentry.io/issues/4496383184/events/1b7ec012828045fea86fac383d8520b3/?project=6164438&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=previous-event&statsPeriod=14d&stream_index=14
L'idée de la PR est d'éviter une erreur 500 en attendant qu'on refonde un peu plus les demandes de prolongation
A faire : ajouter les tests quand validé par le métier
=> Demandes de prolongation: Gestion des chevauchements de date

itou/www/apply/views/submit_views.py, itou/www/gps/forms.py, itou/www/gps/views.py, tests/gps/test_create_beneficiary.py, tests/gps/tests.py
Nous avons utilisé le parcours de candidature pour la création de bénéficiaires dans GPS. L'objectif était d'aller plus vite en réutilisant l'existant.
Le parcours de candidature a besoin (assez logiquement) d'une `Company.pk`. Celle qui était passée était la `request.current_organization` mais cela a posé deux soucis :
- dans [`ApplyBaseView`](https://github.com/gip-inclusion/les-emplois/blob/master/itou/www/apply/views/submit_views.py#L78),  la Company cherchée l'était parfois avec la PK d'une PrescriberOrganization,
- les prescripteurs sans organisation ont eu des 500.
[Après en avoir discuté en équipe](https://itou-inclusion.slack.com/archives/C0412CTV63D/p1718807642049759), nous proposons d'utiliser le Singleton Pôle emploi uniquement dans ce cas là et en attendant que GPS devienne …
=> GPS : correctif pour les prescripteurs sans organisation

tests/users/test_models.py
Can reproduce with `--randomly-seed=3901977061`.
```
E           django.db.utils.IntegrityError: duplicate key value violates unique constraint "unique_ddets_per_department"
E           DETAIL:  Key (kind, department)=(DDETS IAE, 972) already exists.
```
=> Fix test_employer_organizations flakiness

config/settings/base.py
https://www.notion.so/gip-inclusion/Liste-blanche-CD-Donner-acc-s-plusieurs-CD-l-acc-s-2-TB-priv-s-ff2e91592d334639b21e5ffcde8b49cd?pvs=23
On arrête pas le progrès... des stats CD !
Grâce à la liste blanche.
=> Stats : Ouverture des stats CD à 4 nouveaux départements

itou/templates/users/details.html, itou/www/users_views/views.py, tests/gps/__snapshots__/tests.ambr, tests/gps/tests.py, tests/users/factories.py
- Dans la page de détails d'un bénéficiaire, dans le menu déroulant de l'utilisateur connecté, le nom n'était plus celui de l'utilisateur connecté mais celui du bénéficiaire.
- Les membres d'un groupe de suivi voyaient uniquement les initiales du bénéficiaire.
Distinction des variables.
=> GPS: correction de deux erreurs d'affichage (nom du candidat et nom de l'utilisateur connecté)

itou/gps/models.py, itou/templates/users/includes/gps_group.html, itou/users/models.py, itou/www/users_views/views.py, tests/gps/__snapshots__/tests.ambr, tests/gps/tests.py, tests/users/test_models.py
RAF : 
Pour que les utilisateurs distinguent mieux les prescripteurs des employeurs.
Aller dans la liste des membres d'un bénéficiaire suivi.
=> GPS : dans la liste des membres d'un groupe, affichage du type de membre 

itou/job_applications/admin.py, itou/job_applications/admin_forms.py, itou/job_applications/models.py, itou/templates/admin/job_applications/change_form.html, tests/job_applications/__snapshots__/test_admin.ambr, tests/job_applications/test_admin.py
Force le fait de passer par les transitions d'état et l'envoi des emails correspondants.
Impact pour le support :
- les nouvelles candidatures ne peuvent être qu'au statut accepté
- les vérifications de transition sont les mêmes que précédement
=> Admin: Robustifier le changement d'état des candidatures 

itou/static/js/gps.js, itou/templates/gps/join_group.html, itou/templates/gps/my_groups.html
Pour mesurer notre impact.
- page de recherche de bénéficiaire (gps/join_group):
- matomo_category="GPS_formulaire_recherche" matomo_action="clic" matomo_name="ajout_groupe" sur le bouton « Ajouter le bénéficiaire »
- matomo-category="GPS_formulaire_recherche" matomo-action="clic"    matomo-option="creation_beneficiaire" sur le lien « Enregistrer un nouveau bénéficiaire » qui apparaît dans le menu déroulant du champ de recherche lorsqu'aucun résultat n'est trouvé.
- page qui liste les groupes (gps/my_groups) : matomo-category="GPS_liste_groupes" matomo-action="clic" amtomo-name="ajout_groupe"
=> GPS: envoi d'événements à Matomo

tests/institutions/factories.py
Éviter les tests flaky (et le temps nécessaire à leur correction).
Refs b12ea30d6aa091c1d2a44219c79b8d1d49134295, b69f96354751ae70f560606c382b9fc504391571, e20e192b5d20642b89c8761a90d170c02f8f97c0, c39130da689382df4b7a34aaede38728b806b6e9, e04beb373ef71d1478b277e4d062ec261696e553, 83b1b9a52dc44fabf364e2ba8f2778ce4304044f et d’autres à découvrir.
Dernier échec en date :
```
FAILED tests/www/siae_evaluations_views/test_views.py::TestViewProof::test_access_other_institution - django.db.utils.IntegrityError: duplicate key value violates unique constraint "unique_ddets_per_department"
DETAIL:  Key (kind, department)=(DDETS IAE, 14) already exists.
```
=> Utiliser un factory.Iterator() pour les départements des institutions

.github/workflows/ci.yml
Robustesse de la CI, moins d’appels réseau = moins d’erreurs, moins de charges pour les serveurs de fichiers statiques, plus rapide et mieux pour les castors.
=> Mettre en cache les fichiers statiques pour la CI 

config/settings/base.py, config/settings/test.py
Les review apps ont accès à Redis, elles peuvent utiliser la même configuration que la prod et la démo.
Les *fast-machines* sont faites pour lancer des scripts, elles ne démarrent pas le *worker* Huey. Elles doivent rester en mode `immediate`.
Les environnements de test et dev restent en mode immédiat, car l’utilisation de Huey est plus facile dans ce cas.
Ajout de `CC_WORKER_COMMAND=django-admin run_huey` au `c1-deployment-config` des *review apps*. Le `HUEY_QUEUE_NAME` permet d’isoler les queues des différentes *review apps*.
=> Utiliser le mode async de Huey dans la plupart des environnements

itou/api/siae_api/viewsets.py, tests/api/siae_api/tests.py
Certains départements souhaitent pouvoir facilement récupérer la liste des entreprises opérant sur leur territoire.
=> API: ajout des filtres `departement` et `departement_postes` sur la route `/api/v1/siaes/`

config/settings/base.py
`== "FAST-MACHINE"`…
Refs 8186cb2c1380502962f3f28de4f5285555303cf7
=> Correction d’une typo pour l’activation du mode immédiat de Huey

.github/pull_request_template.md
Remonter les catégories de changelog, car elles sont utiles pour remplir le titre.
Descendre les captures d’écran, pour qu’on voit mieux la section « comment tester ».
=> Réordonner pull_request_template.md

itou/utils/emails.py, tests/approvals/__snapshots__/test_notifications.ambr, tests/common_apps/organizations/tests.py, tests/companies/test_import_siae_command.py, tests/job_applications/test_transfer.py, tests/job_applications/tests.py, tests/siae_evaluations/test_emails.py, tests/siae_evaluations/test_management_commands.py, tests/siae_evaluations/test_models.py, tests/www/approvals_views/test_prolongation.py, tests/www/companies_views/test_views.py, tests/www/prescribers_views/test_members.py, tests/www/siae_evaluations_views/test_institutions_views.py, tests/www/siae_evaluations_views/test_siaes_views.py
Éviter de confondre un email envoyé depuis la prod d’un email envoyé depuis un environnement de test.
=> Sécurité : Toujours préfixer le sujet des emails par l’environnement depuis lequel ils sont envoyés

itou/api/migrations/0001_initial.py, itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py, itou/api/models.py
En Python 3.11.9, les tokens ont 32 octets d'entropie par défaut:
https://github.com/python/cpython/blob/v3.11.9/Lib/secrets.py#L32
=> API: utilisation de clefs plus longues pour nos tokens

delete-2023-evaluation-invalid-job-apps, itou/templates/siae_evaluations/email/to_siae_canceled_evaluation_body.txt, itou/templates/siae_evaluations/email/to_siae_canceled_evaluation_subject.txt, itou/templates/siae_evaluations/email/to_siae_removed_auto_prescriptions_body.txt, itou/templates/siae_evaluations/email/to_siae_removed_auto_prescriptions_subject.txt
Suite à une anomalie détectée dans le script de sélection des auto-prescriptions à contrôler, nous avons identifié des auto-prescriptions qui n’auraient pas du être contrôlées. Nous avons donc fait le choix de les supprimer.
Suite à cette suppression :
- les SIAE qui se retrouvent avec une seule auto-prescription passent sous le seuil, requis donc on annule leur contrôle
- les SIAE qui ont encore au moins 2 auto-prescriptions sont toujours dans l’obligation de répondre au contrôle pour cette année
=> Supprimer le contrôle des auto-prescriptions sélectionnées par erreur

itou/api/models.py, itou/utils/logging.py, tests/api/test_geiq.py
Pour pouvoir voir qui utilise nos APIs et voir si les tokens sont toujours utilisés.
Via une nouvelle méthode `datadog_info` sur les objets token pour que le mécanisme soit _opt-in_ et ne pas se retrouver par accident avec des tokens dans nos logs.
=> logs: ajout de l'identifiant du token dans nos logs Datadog

itou/templates/admin/base_site.html
Repérer facilement les onglets de l’admin.
=> Admin : Ajouter une icône à la partie administration du site

.github/workflows/review-app-creation.yml
Essayer de limiter les erreurs au déploiement sur Clever.
=> Empêcher les déploiements concurrent de recettes jetables

itou/templates/dashboard/dashboard.html, itou/templates/gps/my_groups.html, tests/gps/__snapshots__/test_views.ambr, tests/www/dashboard/tests.py
Pour rendre GPS plus visible.
- En supprimant la carte Diagoriente et en déplaçant GPS vers le haut. Diagoriente étant intégré au processus de candidature, il n'est plus nécessaire de continuer de l'afficher sur le tableau de bord.
- Et en ajoutant un encart informatif.
Se connecter en tant que prescripteur ou employeur.
=> Tableau de bord : suppression de Diagoriente, déplacement de GPS et ajout d'un message informatif

itou/templates/apply/includes/job_applications_filters/departments.html, itou/templates/apply/includes/job_applications_filters/selected_jobs.html, itou/templates/apply/includes/job_applications_filters/status.html, itou/templates/includes/btn_dropdown_filter/checkboxes.html
DRY, faciliter le réusinage dans le futur.
=> UX/UI : Partager le template de btn-dropdown-filter pour les checkboxes

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/job_applications.py, tests/metabase/management/test_populate_metabase_emplois.py, tests/metabase/test_job_applications.py
Simplifier l'affichage les labels des motifs de refus sur metabase. 
On réalise une seed côté pilotage pour afficher le nom comme on le souhaite. Donc pour faire ça proprement et ne pas être embêté aux changements de labels côté emplois, on récupère la clé plutôt que la valeur affichée.
=> Modification de la colonne motif_de_refus : recuperer la clé au lieu du label

itou/templates/dashboard/dashboard.html, itou/www/autocomplete/views.py, itou/www/dashboard/views.py, itou/www/gps/views.py, itou/www/users_views/views.py, tests/gps/__snapshots__/test_views.ambr, tests/gps/test_create_beneficiary.py, tests/gps/test_views.py, tests/prescribers/factories.py, tests/www/dashboard/tests.py
Un test échoue.
À vérifier s'il ne faudrait pas ajouter une vérification au niveau des vues aussi : https://github.com/gip-inclusion/les-emplois/blob/fc519717c9035f9e26256c1f272c3d4fd00947b9/itou/www/gps/views.py#L12  
=> Tableau de bord : ne pas afficher GPS aux orienteurs

itou/templates/apply/includes/job_applications_filters/status.html
Corriger une erreur introduite avec 19389b8c8659f9d3e4583bdfa50abcd642d0b19c.
=> UX/UI : Corriger une typo sur le filtre par statut de la liste des candidatures

itou/static/js/utils.js, itou/templates/search/includes/siaes_search_top.html, itou/templates/search/siaes_search_results.html, tests/www/search/tests.py
Seul un résultat est possible lorsqu’on utilise la recherche entreprise. Enlever le reste des filtres afin qu’ils n’interagissent pas avec l’entreprise des résultats:
1. Filtrer par distance 100 kms
2. Sélectionner une entreprise à plus de 5 kms dans le filtre d’entreprise
3. Filtrer sur une de 5 kms
Sur la prod : il n’y a aucun filtre actif dans l’UI, mais aucun résultat. Ceci est dû à la présence de `company=PK` dans l’URL, qui est un choix maintenant invalide. Le select2 ne peut pas être initialisé avec un choix qui n’est pas dans la liste, et n’indique pas d’erreur.
https://c1-review-ff-filter-company.cleverapps.io/
1. Filtrer par distance 100 kms
2. Sélectionner une entreprise à plus de 5 kms dans le filtre d’entreprise
3. Filtrer sur une de 5 kms
=> UX/UI: Correction d’un petit bug sur la recherche employeur

itou/users/admin.py
Autrement, des champs éditables apparaissent lorsqu’on a ajouté un affichage particulier pour le champ (notifications, ID de la structure, etc).
Voir les inline de membership sur la page de détail d’un prescripteur, d’un employeur et membre d’une institution partenaire dans l’admin.
=> Admin : Limiter les champs des `inline` d’appartenance à une entreprise ou organisation aux champs en lecture seule

itou/www/approvals_views/forms.py, tests/www/approvals_views/test_list.py
050d7d2d63b582e4fb445a0a948336ae93a97235
1. Se connecter en tant que l’EI
2. http://localhost:8000/approvals/list
Utiliser le filtre nom salarié.
=> UX/UI : Afficher le nom du candidat en majuscule dans le filtre des PASS IAE et salariés

itou/static/js/gps.js, itou/users/models.py, itou/www/autocomplete/views.py, tests/users/test_models.py
Corrections suite à la campagne de _Bug bounty_.
- Limitation du nom de l'utilisateur à 70 caractères.
- Échappement du nom de l'utilisateur dans les résultats de recherche bénéficiaire.
- Se connecter en tant que candidat et modifier son prénom. Par exemple :
```
<form%20action=#%20style="margin:100px">Login:<input%20name=1><br>Password:<input%20name=2><input%20type=submit%20value="go">
```
- Se connecter en tant qu'employeur et ajouter un bénéficiaire. Vérifier que le nom qui s'affiche n'est pas un formulaire et qu'il est plus court que celui entré précédemment. :sunglasses:
=> Candidats : limitation du nom à 70 caractères et correctif et sécurité

itou/templates/search/siaes_search_results.html
=> Préferer request.path pour la target du form de la recherche SIAE/fiche de poste

itou/templates/approvals/list.html, itou/www/approvals_views/forms.py, tests/www/approvals_views/test_list.py
Le thème casse partiellement le MultipleChoiceField, utilisons plutôt le composant de sélection d’un seul élément.
Dans tous les cas, les utilisateurs utilisent le widget pour accéder rapidement à un candidat, et non pour limiter les éléments présents dans la liste à un ensemble de candidats.
1. Se connecter en tant que l’EI
2. http://localhost:8000/approvals/list
3. Utiliser le filtre de salarié
=> UX/UI : Limiter la sélection rapide à un candidat dans la liste des PASS IAE et salariés [GEN-1687]

itou/templates/employee_record/list.html, itou/www/employee_record_views/forms.py, itou/www/employee_record_views/views.py, tests/www/employee_record_views/test_list.py
Le thème casse partiellement le MultipleChoiceField, utilisons plutôt le composant de sélection d’un seul élément.
Dans tous les cas, les utilisateurs utilisent le widget pour accéder rapidement à un candidat, et non pour limiter les éléments présents dans la liste à un ensemble de candidats.
1. Se connecter en tant qu’employeur EI
2. Dans la liste des fiches salarié, utiliser le champ « Candidat » : http://localhost:8000/employee_record/list?status=SENT
=> UX/UI : Limiter la sélection rapide à un candidat dans la liste des fiches salarié [GEN-1687]

clevercloud/cron.json, clevercloud/crons/populate_c1_analyses.sh, config/settings/base.py, config/settings/dev.py, itou/metabase/dataframes.py, itou/metabase/db.py, itou/metabase/management/commands/metabase_to_csv.py, itou/metabase/management/commands/populate_c1_analyses.py, itou/metabase/management/commands/populate_metabase_matomo.py, itou/metabase/tables/c1_analyses.py, tests/metabase/conftest.py, tests/metabase/management/test_populate_c1_analyses.py
Pour permettre des analyses depuis metabase
Réutilisation de la base de code d'export vers metabase
=> Statistiques: Export de données anonymes pour analyses d'impact

itou/templates/gps/my_groups.html
Les utilisateurs GPS demandent une fonction de recherche / filtrage de la liste des bénficiaires. C'est un certain boulot, donc en attendant, devant nos urgences en déploiement / com, on ajoute un bandeau avec des infos basiques.
Juste un bandeau en plus du bandeau déjà existant (😓).
N/A.
=> UX/UI : bandeau « chercher un bénéficiaire » sur GPS

itou/siae_evaluations/models.py, tests/siae_evaluations/test_models.py
Lors d’une auto-prescription, l’algorithme pouvait sélectionner une embauche postérieure à la date de création du PASS, potentiellement hors de la période contrôlée.
Corrigée cette année avec https://itou-inclusion.slack.com/archives/C01181Y04LT/p1718698175973149.
=> Contrôle a posteriori : Correction de l’algorithme de sélection des auto-prescriptions

tests/www/siae_evaluations_views/test_views.py
```python
_____________________________________________________________________________________ TestViewProof.test_access_other_institution _____________________________________________________________________________________
[gw2] linux -- Python 3.11.9 /home/freitafr/dev/itou3/.venv/bin/python3.11
self = <django.db.backends.utils.CursorWrapper object at 0x673eb347b750>
sql = 'INSERT INTO "institutions_institution" ("address_line_1", "address_line_2", "post_code", "city", "department", "coord...nd") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "institutions_institution"."id"'
params = ('', '', '', '', '14', None, ...)
ignored_wrapper_args = (False, {'connection': <DatabaseWrapper vendor='postgresql' alias='default'>, 'cursor': …
```
=> Flaky TestViewProof.test_access_other_institution

itou/templates/apply/process_base.html, itou/templates/apply/submit_base.html, itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/includes/card.html, itou/templates/approvals/suspend.html, tests/www/apply/test_submit.py
Beaucoup de vues utilisent `approvals/includes/status.html` et le fait d'avoir une indirection avec une faible valeur ajoutée n'aide pas.
=> templates: suppression de l'indirection `approvals/includes/card.html`

itou/templates/apply/submit/create_or_update_job_seeker/step_base.html, itou/templates/dashboard/includes/edit_job_seeker_info_form.html, itou/templates/employee_record/includes/create_step_1.html, itou/templates/signup/job_seeker_signup.html, itou/www/apply/views/submit_views.py, tests/www/signup/__snapshots__/test_job_seeker.ambr
Avoir une mesure d’impact avant la mise en place d’API certifiant l’identité des utilisateurs.
Configuration côté Matomo, bien vérifier le site de recette et la prod.
https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=220&period=day&date=yesterday&showaddsite=false#?idSite=220&period=week&date=2024-07-04&category=FormAnalytics_Forms&subcategory=FormAnalytics_ManageForms
https://matomo.inclusion.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=117&period=day&date=yesterday&showaddsite=false#?idSite=117&period=week&date=2024-07-04&category=FormAnalytics_Forms&subcategory=FormAnalytics_ManageForms
Se mettre dans un navigateur envoyant les analytics (pas de bloqueur), et aller sur un des formulaires concernés. Changer les prénoms et nom d’un …
=> Analytics : Suivi des champs prénom et nom pour les candidats

itou/job_applications/export.py, tests/job_applications/tests.py, tests/www/apply/test_list_for_siae.py
Apparemment le wording actuel pose problème.
=> Employeur: changer la mention “auto-prescription” par “ma structure” dans l'export de candidatures [GEN-1818]

itou/approvals/models.py, itou/templates/approvals/includes/prolongation_declaration_form.html, itou/templates/django_bootstrap5/widgets/radio_select.html, itou/utils/widgets.py, itou/www/approvals_views/forms.py, tests/approvals/tests.py, tests/www/approvals_views/__snapshots__/test_prolongation.ambr, tests/www/approvals_views/test_prolongation.py
Empêcher de saisir certains motifs de prolongations s'il y a déjà un certain nombre de prolongations.
Créer des PASS avec suffisamment de prolongations dans le passé et essayer de les prolonger.
J'essaierai de générer des PASS intéressant demain.
=> PASS IAE: Mise en conformité des règles de  prolongations [GEN-270]

itou/approvals/admin.py
Sinon, on pourrait croire que l'on peut accepter ou refuser la demande dans l'admin alors que cela ne déclenche rien (pas de création de prolongation, etc).
=> Admin: le statut d'une demande de prolongation est maintenant en lecture seule

itou/users/management/commands/send_check_authorized_members_email.py, tests/users/test_management_commands.py
Pour de pas spammer nos utilisateurs (ou bloquer le destinataire côté mailjet)
Subquery dans le prefetch des membres admins des structures qui se charge de filtrer
=> Dédupliquer les notifications créées par send_check_authorized_members_email

itou/templates/approvals/includes/prolongation_declaration_form.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/views.py, tests/www/approvals_views/__snapshots__/test_prolongation.ambr, tests/www/approvals_views/test_prolongation.py
- Bouton "Retour" en doublon du bouton "Annuler"
- et clairement quand on annule la demande on s'attend à revenir sur la page du PASS et non celle du tableau de bord.
=> PASS IAE: suppression du bouton retour et correction de l'URL du bouton annuler dans le formulaire de demande de prolongation [GEN-1633]

itou/job_applications/admin.py, itou/job_applications/admin_forms.py, itou/job_applications/models.py, itou/templates/admin/job_applications/jobapplication_change_form.html, tests/job_applications/__snapshots__/test_admin.ambr, tests/job_applications/test_admin.py, tests/job_applications/tests.py
Suite aux changement de status, voir : https://itou-inclusion.slack.com/archives/C02J7LWNT6Z/p1720176613306289?thread_ts=1718717668.744509&cid=C02J7LWNT6Z
- Le bouton "Annuler" est à présent toujours visible sur une candidature acceptée, mais grisé quand il y a des fiches salariées qui bloquent l'annulation, avec un tooltip. 
- Les fiches salariées d'une candidature sont visible depuis la page de celle-ci pour les retrouver plus rapidement quand elles doivent être supprimées pour régulation.
- On peut accepter depuis l'admin un candidature avec un vieil agrément (on fait confiance au support)
- On vérifie que le diagnostic appartient au candidat
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette …
=> Admin: Amélioration de la page des candidature pour les actions du support

config/settings/base.py, config/settings/test.py, itou/utils/cache.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/test.txt, tests/utils/apis/test_pole_emploi_api.py, tests/utils/test_cache.py
- Pour pouvoir facilement lock les accès au cache dans certains cas de figure (cf. #4356)
- Pour pouvoir facilement surcharger le client Redis sans recourir à un backend dédié
- Pour pouvoir récupérer le client sans passer par des méthodes privées
Utilisation du module [django-redis](https://github.com/jazzband/django-redis/) maintenu par jazzband qui expose davantage de méthodes redis.
=> Changement du backend de cache en faveur de django-redis

itou/templates/gps/includes/memberships_results.html, itou/templates/gps/my_groups.html, itou/www/gps/forms.py, itou/www/gps/views.py, tests/gps/__snapshots__/test_views.ambr, tests/gps/test_views.py
Les utilisateurs peinent à retrouver des bénéficiaires. 
Connectez-vous en tant qu'employeur ou prescripteur habilité puis suivez au moins 11 personnes dans GPS. Vérifiez que la pagination est correcte.
Le filtre par nom devrait vous permettre de retrouver un bénéficiaire.
=> GPS : pagination et filtre par nom de bénéficiaire

itou/www/employee_record_views/views.py, tests/www/employee_record_views/__snapshots__/test_add.ambr, tests/www/employee_record_views/test_add.py
Pour limiter _un tout petit peu_ le conflit de session.
En vrai, vu qu'on stocke également l'entreprise courante en session, ça ne protège que le cas où:
- en tant qu'entreprise A, on commence à ajouter une fiche salarié
- on ouvre un autre onglet
- on bascule en entreprise B
- on commence à ajouter une fiche salarié sur l'entreprise B
- on continue son travail et on rebascule sur l'entreprise A
- on revient sur l'onglet du début et on continue le wizard qui ne plante pas
Cela aurait déjà plus de sens si le wizard d'ajout de fiche salarié mettait l'entreprise dans l'URL plutôt que d'utiliser la `request.current_organization`.
Tout cela pour dire que je suis 0+ pour merger ce fix mais qu'on pourrait aussi passer le ticket Notion en wontfix.
> _Décrivez en quelques mots la solution retenue …
=> Fiche salarié: ajout d'un préfixe à la session d'ajout d'une fiche salarié [GEN-1550]

itou/templates/apply/includes/job_applications_filters/offcanvas.html
Erreur de double fermeture de balise `<form>` sur le htmx des filtres candidats
Chevron en trop visible dans le html sur la page https://demo.emplois.inclusion.beta.gouv.fr/apply/siae/list
=> Candidature: Double fermeture de form sur les filtres candidats

itou/templates/apply/process_base.html, itou/templates/apply/submit_base.html, itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/detail.html, itou/templates/approvals/includes/status.html, itou/templates/approvals/prolongation_requests/show.html, itou/templates/approvals/suspend.html, itou/templates/dashboard/includes/job_seeker_approval_card.html, itou/www/apply/views/submit_views.py, itou/www/approvals_views/views.py, tests/www/approvals_views/__snapshots__/test_includes.ambr, tests/www/approvals_views/test_includes.py, tests/www/approvals_views/test_prolongation.py, tests/www/approvals_views/test_prolongation_requests.py, tests/www/approvals_views/test_suspend.py
Cela semble plus logique (et plus simple).
- On utilise désormais l'origine du PASS et non celle de la candidature pour afficher le texte `Ce PASS IAE a été importé depuis un agrément Pôle emploi.`
- Affichage systématique de la date de fin prévisionnelle, sauf:
* pour le parcours de candidature/d'embauche
* l'acceptation d'une candidature
=> PASS IAE: modification des règles d'affichage de l'encart

itou/users/migrations/0008_fix_user_public_id.py, itou/users/models.py
Accès au Utilisateur par `public_id` plus efficace
=> style(models/User.public_id): add help_text

itou/job_applications/models.py, itou/job_applications/notifications.py, itou/templates/apply/email/postpone_for_job_seeker_body.txt, itou/templates/apply/email/postpone_for_job_seeker_subject.txt, itou/templates/apply/email/postpone_for_proxy_body.txt, itou/templates/apply/email/postpone_for_proxy_subject.txt, tests/www/apply/__snapshots__/test_process.ambr, tests/www/apply/test_process.py
Pour tenter de réduire le nombre de candidature restant bloquée pour cause de candidat injoignable ou ne se présentant pas à l'entretien.
https://c1-review-xfernandez-postponed-notification.cleverapps.io/
Mettre des candidatures en attente et aller voir dans l'admin les mails générés.
=> Candidature: ajout d'une notification au candidat et au prescripteur/orienteur éventuel lors d'une mise en attente [GEN-1759]

itou/templates/includes/copy_to_clipboard.html, itou/templates/users/details.html, itou/templates/users/includes/gps_group.html, itou/www/users_views/views.py, tests/gps/__snapshots__/test_views.ambr, tests/gps/test_views.py
Pour inciter les membres à renseigner le leur. J'en ai profité pour ajouter un bouton pour copier l'e-mail rapidement.
J'ai aussi réorganisé et nettoyé le HTML et les tests.
Consulter la page d'un bénéficiaire dans GPS qui a plusieurs membres.
=> GPS : indiquer que le téléphone du membre n'est pas renseigné ou que la date de naissance du bénéficiaire n'est pas renseignée

itou/www/dashboard/views.py
Ils ont déjà eu un nombre suffisant de réponses.
=> Tableau de bord: suppression de la bannière annonçant une enquête Tally aux employeurs SIAE [GEN-1846]

itou/companies/management/commands/move_company_data.py, tests/companies/test_management_commands.py
Ces deux champs devraient être calculés à partir de l'adresse postale de la structure, or cette adresse n'est pas transférée.
https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1720702597222509?thread_ts=1720701183.511899&cid=C01AQKD7MAN
=> move_company_data: arrêt du transfert des champs `coords` & `geocoding_score`

itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/check_job_seeker_info_for_hire.html, itou/www/apply/urls.py, itou/www/apply/views/common.py, itou/www/apply/views/submit_views.py, itou/www/apply/views/utils.py, itou/www/dashboard/urls.py, itou/www/dashboard/views.py, tests/www/apply/test_geiq.py, tests/www/apply/test_submit.py, tests/www/approvals_views/test_detail.py, tests/www/dashboard/test_edit_job_seeker_info.py
En tant qu’employeur, je ne dois pas récupérer les informations personnelles de tous les candidats des emplois
Remplacer l'utilisation des PKs du base de donnée avec les `public_id`s
=> Vie privée: utilisation du ID public en place de PK dans les URLs

itou/companies/management/commands/move_company_data.py
Depuis e0c0139c83f68ef2c9e7f3b444427fd7523f85ea, une entreprise peut avoir plusieurs fiches de poste avec la même appelation.
On peut donc bouger toutes les fiches de poste si demandé.
=> Support: simplification de move_company_data

config/settings/base.py, itou/companies/admin.py, itou/utils/export.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/test.txt, tests/companies/__snapshots__/test_admin.ambr, tests/companies/test_admin.py, tests/siae_evaluations/test_admin.py, tests/users/factories.py
L'actuel ne marche pas depuis des mises à jour de django-import-export
On remplace la lib externe par un petit morceau de code qui utilise un serializer DRF pour exporter dans un fichier XLSX
=> Admin: Correction de l'export des entreprises [GEN-1861]

itou/companies/admin.py
C'est souvent celles-ci qui nous intéressent.
=> admin: Remonter l’annexe financière valide en haut de liste

config/settings/base.py, itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/utils.py, itou/www/stats/views.py, tests/www/stats/test_views.py
Suite à une demande du pilotage, ajour d'une liste blanche contenant les PK des SIAE + MEP du TB nécessitant cette liste blanche.
=> [Metabase] Whitelist SIAE

itou/job_applications/models.py, itou/www/apply/forms.py, tests/www/apply/test_process.py
Pour éviter une candidature et un PASS commençant en 2502
=> Candidature: Bloquer l'embauche trop loin dans le futur [GEN-1867] 

itou/siae_evaluations/management/commands/evaluation_campaign_notify.py, itou/siae_evaluations/models.py, tests/siae_evaluations/test_admin.py, tests/siae_evaluations/test_management_commands.py, tests/siae_evaluations/test_models.py
Actuellement dès que toutes les SIAES d'un département avaient soumis leur contrôle, la DDETS correspondante recevait la notification (potentiellement donc en avance par rapport au calendrier de la campagne) ce qui les perturbait.
Dorénavant, cette notification est envoyée au moment du blocage des soumissions.
Le rappel quant à lui est envoyé tous les 7 jours tant que la DDETS a des SIAE à contrôler.
https://c1-review-xfernandez-phase-bis-email.cleverapps.io/
Se connecter en tant qu'admin et tenter les différents scénarios.
=> Contrôle a posteriori: envoi de la notification aux DDETS au moment du blocage des soumissions [GEN-1860]

itou/www/companies_views/forms.py, itou/www/employee_record_views/forms.py, itou/www/gps/forms.py, itou/www/search/forms.py, tests/www/dashboard/__snapshots__/test_dashboard.ambr, tests/www/employee_record_views/__snapshots__/test_create.ambr
Suite de #4444.
À merger une fois #4444 en production (pour éviter d'éventuelles erreurs lors du déploiement où le nouveau front appellerait l'ancien back sans `?select2=` et n'obtiendrait pas le bon format).
=> Autocompletion: suppression de code déprécié - partie 2

itou/utils/apis/metabase.py
https://www.notion.so/gip-inclusion/Iframe-Metabase-Augmenter-le-temps-d-affichage-des-donn-es-lors-de-la-consultation-d-un-TB-ef2f3f085c8147259bbb51341f6b4aac?pvs=4
=> Pilotage : Augmenter la durée de vie des tableaux de bord à 1 heure

itou/common_apps/nir/forms.py, tests/www/apply/test_process.py, tests/www/dashboard/test_edit_job_seeker_info.py, tests/www/dashboard/test_edit_user_info.py
Pour que les utilisateurs comprennent que la case peut être cochée
=> Candidature: Faciliter la mise à jour du NIR à l'aide d'un texte d'aide [GEN-265]

itou/static/js/htmx_dropdown_filter.js
La classe `has-selected-item` définit le style en gras, et c’est maintenant dans la version du thème utilisée.
https://github.com/gip-inclusion/itou-theme/commit/778b39e6008478572b8e4ee89266232fd4e7b6e0
=> Retirer le hack pour faire apparaître `.has-selected-item` en gras dans htmx_dropdown_filter

itou/templates/dashboard/dashboard.html, itou/templates/dashboard/includes/stats.html, itou/www/dashboard/views.py
Pour ne plus avoir du vide
J'en profite aussi pour ne pas afficher l'onglet "Statistique" si la personne n'a pas accès à celles-ci (ie, les candidats)
Quand aucun TB privé :
Quand aucun accès aux TB :
=> Pilotage : Ajouter du texte dans la rubrique “Données personnalisées” des utilisateurs qui n’ont pas de TB privé

tests/users/factories.py, tests/www/apply/test_process.py
Le processus d'acceptation de candidature, central et complexe, fait partie des premières fonctionnalités de l'app et cela se reflète dans les tests. Ceux-ci ont évolué de manière tentaculaire. Le fichier de test fait plus de 3000 lignes !
Plus précisément, la processus d'acceptation de candidature intègre 3 formulaires différents. Les tests répétaient les mêmes `post_data` mais avec des variantes, les rendant difficiles à comprendre et à faire évoluer.
L'un de ces formulaires modifie l'adresse du candidat géré par `AddressMixin`. La champ `User.city` est une chaîne de caractères mais `User.insee_city` [a été introduit en septembre 23](https://github.com/gip-inclusion/les-emplois/pull/3043) pour garantir une meilleure cohérence des données. Or cette PK n'était pas utilisée correctement …
=> Processus de candidature : réusinage des tests du processus d'acceptation

config/settings/base.py, itou/rdv_insertion/api.py, itou/utils/mocks/rdv_insertion.py, tests/rdv_insertion/tests.py
Les API RDV-I et RDV-S partagent la même base d'utilisateurs et les mêmes informations d'identification.
Leurs tokens sont émis pour une durée de 24h et chaque renouvellement invalide les tokens antérieurs.
Les informations d'identification sont mises en cache et automatiquement actualisées selon le besoin.
=> Système permettant de renouveler token d’API RDV-S [GEN-1763]

tests/www/apply/__snapshots__/test_list_prescriptions.ambr, tests/www/apply/test_list_prescriptions.py
Éviter de répéter le préfixe, et marquer le groupement.
=> Retirer le préfixe inutile des `test_list_prescriptions`

itou/www/employee_record_views/forms.py
> Clarification du help text (la formulation était négative) 
> Le terme "Pays" du champs Pays de naissance n'avait pas de majuscule.
> RAS
> Ces textes sont visible depuis `inclusion.beta.gouv.fr/employee_record/create`
=> UX/UI - Wording : Clarification du help text + Ajout d'une majuscule à "Pays"

tests/www/apply/__snapshots__/test_process.ambr, tests/www/apply/test_process.py
Exemple d’échec:
```
========================================================================================== FAILURES ===========================================================================================
_______________________________________________________________________________ test_delete_prior_action[True] ________________________________________________________________________________
[gw0] linux -- Python 3.11.9 /home/freitafr/dev/itou3/.venv/bin/python3.11
client = <tests.utils.test.ItouClient object at 0x6f9f78b33ed0>
snapshot = '''
<ul class="list-step" hx-swap-oob="true" id="transition_logs_11111111-1111-1111-1111-111111111111">
...11+00:00">Le 10 décembre 2023 à 11:11</time>
<span>Nouvelle candidature</span>
</li>
</ul>
'''
with_geiq_diagnosis = True …
```
=> Stabiliser test_delete_prior_action

itou/prescribers/admin.py
=> Admin : Permettre l’édition du champ `website` pour les organisations prescriptrices

itou/users/models.py
La recherche de bénéficiaire est une nouvelle entrée dans les vues avec le plus haut _User Misery_ sur Sentry (2ème pire vue du système) avec un P50 à plus de 4 secondes, ce qui affecte la base de données et l’expérience sur le site.
Performances
============
En utilisant le panneau SQL de DjDT, avec la requête :
```bash
curl 'http://127.0.0.1:8000/autocomplete/gps_users?term=dupont&_type=query&q=dupont' 'Cookie: sessionid=SESSIONID'
```
master: 454 ms
commit: 24 ms
cf https://itou-inclusion.slack.com/archives/C067CP07KJR/p1721834260473969
=> GPS : Amélioration des performances de la recherche de bénéficiaires

itou/templates/utils/widgets/file_input.html, tests/www/geiq_views/__snapshots__/tests.ambr
Éviter de perturber les utilisateurs.
=> Clarifier que l’envoi de fichier ne permet d’envoyer qu’un seul fichier [GEN-1889]

tests/conftest.py
Éviter de modifier les settings globaux dans les tests.
=> Utiliser la fixture settings dans les tests au lieu de modifier les settings django

itou/eligibility/admin.py, itou/eligibility/models/geiq.py, itou/templates/apply/includes/eligibility_badge.html, itou/templates/apply/includes/geiq/geiq_diagnosis_details.html, itou/templates/apply/process_details.html, itou/www/apply/views/process_views.py, tests/companies/factories.py, tests/eligibility/factories.py, tests/eligibility/test_geiq.py, tests/job_applications/factories.py, tests/www/apply/test_geiq.py, tests/www/apply/test_submit.py
Pour permettre de conserver l'information même quand le diagnostic n'est plus valide 
employeur et candidat                                     
on prend dans l'ordre de présence
- le diag de la candidature
- le diag le plus récent fait par un prescripteur habilité
- le diag le plus récent fait par l'entreprise destinatrice 
=> tester le cas un diag expiré d'un prescritpeur et un diag valid de la structure
On ne veut pas d'abord le diag valide ?
prescripteur
------------
on prend le diag valide pour ce candidat fait par un presripteur habitilité (s'il existe)
mais on ne prend pas un diag d'un prescripteur habilité expiré ?
sur une candidature acceptée, on n'affiche pas non plus le diag de l'entreprise ?
> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou …
=> GEIQ: Afficher le diagnostic GEIQ d'une candidature acceptée dans le passé [GEN-1701]

tests/www/apply/test_list_prescriptions.py
Consolider les tests avant https://www.notion.so/plateforme-inclusion/Investigation-Cacher-les-diags-SIAE-aux-prescripteurs-lors-des-candidatures-3227290de5b248759a5fe43079868292.
=> Verifier que les prescripteurs habilités voient leurs candidatures comme éligibles à l’IAE

itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/models.py, tests/employee_record/test_models.py, tests/employee_record/test_sanitize_employee_records.py
Ce système avais été mis en place afin de faire ceinture-bretelle pour l'auto-intégration des 3436, mais depuis un certain temps je ne l'ai jamais [1] vu en récupérer qui n'auraient pas déjà été gérées au moment de la réception des fichiers retours.
De plus la fonction n'envoyant pas une notification la date de fin de PASS ne sera pas à jour coté ASP donc création de ticket support au final, alors autant les laisser arriver naturellement et améliorer l'autre bout de code.
=> Fiches salarié : Supprimer la voiture balai pour les erreurs 3436

itou/prescribers/migrations/0004_poleemploi_to_francetravail.py
=> France Travail : Migrer les informations des organisations prescriptrices Pôle emploi vers France Travail

itou/employee_record/models.py, tests/employee_record/__snapshots__/test_transfer_employee_records.ambr, tests/employee_record/test_transfer_employee_records.py
La PK nous permet de retrouver l'utilisateur mais sans dévoiler d'informations personnels, dans les logs par exemple :).
=> Fiches salarié : Afficher la PK plutôt que le `__str__()` du candidat pour le modèle `EmployeeRecord()`

itou/metabase/tables/companies.py, tests/metabase/management/test_populate_metabase_emplois.py
Besoin coté C2 afin de faire un TB pour ces entreprises : https://www.notion.so/gip-inclusion/Convergence-mettre-dispo-au-c2-les-structures-convergence-dans-une-table-9e8918c556c444acbcf4c02ff17eed67?pvs=4
=> Pilotage : Ajout d'un champ pour identifier les entreprises dîtes "Convergence"

itou/metabase/tables/organizations.py, tests/metabase/management/test_populate_metabase_emplois.py
Depuis https://github.com/gip-inclusion/les-emplois/pull/4469/commits/4818e8e31d5c42b06a112306f9e80554cde97a0c la fonction `get_choices()` n'autorise plus les valeurs non connues, mais `NULL` semble pouvoir très bien faire le boulot pour le pilotage donc utilisons cela
PR d'adaptation coté pilotage : https://github.com/gip-inclusion/pilotage-airflow/pull/344
```
$ ./manage.py populate_metabase_emplois --mode organizations
```
=> Pilotage : Utilisation de `None` plutôt qu'une fausse valeur afin de corriger la synchro

itou/templates/gps/includes/memberships_results.html, tests/gps/__snapshots__/test_views.ambr
Suivre le nombre de clic sur le bouton « Consulter la fiche ».
=> GPS : ajout d'un événement Matomo

itou/companies/admin.py, itou/companies/migrations/0001_initial.py, itou/companies/models.py
Demandes support.
Le déplacement de la colonne "Active" est de mon fait, c'est l'information a lire ou qu'on recherche quand on est sur ce bloc donc c'est plus logique de la mettre au début plutôt qu'à la fin, et ça aidera les personnes avec une résolution plus contrainte ;).
=> Admin : Ajout de la date de fin du délai de grâce ainsi que la date de création des AF dans la page des conventions [GEN-1863] [GEN-1864]

config/settings/base.py
https://www.notion.so/gip-inclusion/Liste-blanche-CD-Donner-acc-s-au-CD-de-l-Aisne-et-du-Val-de-Marne-l-acc-s-2-TB-priv-s-ff2e91592d334639b21e5ffcde8b49cd?pvs=4
Donner accès au CD de l’Aisne et du Val de Marne l’accès à 2 TB privés
màj de la liste blanche
=> Stats : Ouverture des stats CD à 2 nouveaux départements

itou/approvals/admin.py, itou/companies/admin.py, itou/employee_record/admin.py, itou/siae_evaluations/admin.py, tests/approvals/tests.py
Car comme d'hab je me suis fait avoir dans #4494 parce que Django ne réécrit pas les `None` dans les `@admin.display()`
Et vu que je me suis demandé si il n'y avais pas une constante pour le `"-"` j'en profite pour changer partout avec la fonction de Django qui va bien :).
=> Admin : Corriger l'affichage de la période de grâce quand c'est vide et utilisation de `.get_empty_value_display()` partout

itou/openid_connect/inclusion_connect/views.py, tests/openid_connect/inclusion_connect/tests.py
On ne souhaite pas le faire qu'à la création de compte, cela permettra de rattraper le stock
=> openid_connect: Add FT users to their new workplace at every connection

itou/templates/apply/submit/application/resume.html
Voir le ticket pour la demande initiale :grin:.
J'en ai profité pour simplifier les blocs conditionnels et mettre en commun pour que ça soit plus _future proof_.
**Candidat - IAE**
**Candidat - GEIQ**
**Candidat - Autres**
**Prescripteur & employeurs - IAE**
**Prescripteur & employeurs - GEIQ**
**Prescripteur & employeurs - Autres**
**Employeurs - Auto-prescription**
=> Candidature : Bon à savoir vide dans le parcours de dépôt de candidature EA [GEN-1873]

itou/employee_record/common_management.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/employee_record/models.py, tests/employee_record/test_models.py
En allant chercher l'archive du flux EA2 j'ai vu que 3 fichiers retours étaient toujours présents :
- `RIAE_FS_20230822125603_FichierRetour.json`
- `RIAE_FS_20230921085512_FichierRetour.json`
- `RIAE_FS_20231205105514_FichierRetour.json`
Les fichiers n'étant pas supprimés si une erreur arrive lors du traitement j'ai commencé à creuser pour trouver ces erreurs.
Le traitement se bloquais dès lors que l'on essayais de changer de statut une FS dont le statut actuel (ie. `DISABLED`, `ARCHIVED`) n'était pas celui attendu (`SENT`).
Au final la nouvelle option est ultra-simple car la logique reste dans le bout de code commun, et avec les améliorations on ne devrais plus trop avoir de fichier qui traînent ou alors avec une grosse erreur mais tout le fichier sera invalidé.
Les fichiers sont dispo …
=> Fiches salarié : Option pour traiter un fichier de retour manuellement et améliorations de leur traitement

itou/metabase/management/commands/populate_metabase_emplois.py
Non connu par Sentry :
Vu qu'il ne nous a pas manqué depuis le temps et que dans les faits c'est suivi via les alertes slacks autant le supprimer.
=> Suppression d'un moniteur de cron non enregistré

itou/www/employee_record_views/forms.py, tests/www/employee_record_views/test_create.py
Suite à la PR  #4420 , le formulaire de création de fiche salarié est cassé.
=> Fiches salarié : correctif sur la commune de naissance

itou/templates/apply/includes/accept_section.html, itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/includes/transfer_job_application.html, itou/templates/apply/process_internal_transfer.html, itou/templates/apply/submit/application/base.html, itou/templates/companies/edit_siae_preview.html, itou/templates/companies/includes/_company_info.html
Éviter que l’utilisateur ne sorte du parcours sur quelques composants clés (attention que j'ai proposé des pages non-définit sur le ticket):
- `job_seeker_info.html` : liens vers son CV sur les pages des applications et approbations
- `process_internal_transfer.html`, `transfer_job_application.html` : "voir la fiche de l'enterprise" sur la confirmation de transfert du candidat
- `accept_section.html` : confirmation de l'acceptation du candidat
- `edit_siae_preview.html` : sous la page "modifier les coordonnées de votre structure"
- `application/base.html` : un lien vers l'information de l'enterprise concernée et inclus sur plusieurs gabarits à la soumission de candidature
=> UX/UI : Privilégier l’ouverture d’onglet [ GEN-1872 ]

docker-compose.yml, docker/dev/django/Dockerfile
`uv` requiert un dossier de cache.
`/home` est own par root donc l'utilisateur courant ne peut écrire dans `/home/.cache`.
- Utilisation d'un volume pour le cache du conteneur django (sous compose)
- Utilisation de `XDG_CACHE_HOME` à la place de `ITOU_CACHE`
- La conf des statics des emplois supporte `XDG_CACHE_HOME`
- `pip` et `uv` supportent `XDG_CACHE_HOME`
Lancer les emplois avec django (`docker compose --profile django up`)
=> docker: add a cache dir writable by docker user

requirements/base.txt, requirements/dev.txt, requirements/test.txt
https://www.djangoproject.com/weblog/2024/aug/06/security-releases/
```
make PIP_COMPILE_OPTIONS='--upgrade-package django' compile-deps
```
=> Mettre à jour vers Django 5.0.8

itou/www/apply/views/common.py, tests/www/apply/test_forms.py, tests/www/apply/test_process.py
`CertifiedCriteriaInfoRequiredForm` utilise un champ `birthdate` qui est anticipé d'être une `date`, mais c'est dans l'utilisation c'est possible que c'est un `str`, qui cause un `ValueError`
* Enforcer que le `birthdate` dans `CertifiedCriteriaInfoRequiredForm` est une date
* Sur [_accept](https://github.com/gip-inclusion/les-emplois/compare/calum/fix-date-format?expand=1#diff-c4816cd2f94ad06618d8ec2ed19b7c4d7109a1fde13565b2f756b73e6c8da948), ratrappe le cas rare où le date est mis à jour en string, et le convertir
* Ajout des tests pour `CertifiedCriteriaInfoRequiredForm`
=> Candidature: correction d'une erreur d'acceptation du siae dans de rares conditions

itou/asp/forms.py, itou/www/apply/forms.py, itou/www/employee_record_views/forms.py
Plus adapté en cas de mise à jour du référentiel ASP.
=> Fiches salarié : Utiliser l’objet Pays au lieu de sa PK

tests/approvals/tests.py, tests/employee_record/test_models.py, tests/gps/test_management_commands.py, tests/job_applications/factories.py, tests/users/test_management_commands.py, tests/www/apply/test_process.py
Car ça semble le plus logique, et que ça m'évite de faire des cabrioles pour corriger certains tests supprimant des informations pour le setup ou en cours de route dans la PR #3150 :grin:.
=> Tests : Ne pas créer de diagnosique d'éligibilité par défaut pour les candidatures réalisées par le candidat

itou/job_applications/models.py, itou/www/apply/views/process_views.py, itou/www/approvals_views/views.py, tests/approvals/tests.py, tests/job_applications/test_transfer.py, tests/job_applications/tests.py
Forcer un appel à `.full_clean()` génère 10 requêtes SQL de vérification (FK + contraintes), ces vérifications sont en générales redondantes car soit le formulaire est déjà passé par là ou on ne modifie qu'un seul champs bien précis, et la DB va aussi bloquer si jamais un trop gros truc devais passer.
L'objet candidature étant central et une transition provoquant un `.save()` il me semble bénéfique de s'éviter ces traitements supplémentaire peu coûteux mais nombreux.
Pour trouver les utilisations dans le code j'ai utilisé : `job(_app(lication)?)?\.save\(`
J'ai également fait une recherche via `jobapplication_set` mais rien de probant.
=> Candidature : Ne plus appeler `.full_clean()` à chaque `.save()`

itou/approvals/models.py
Comme start_at > end_at, il suffit de vérifier que `end_at>=now` pour que le passe soit valide. 
=> PASS IAE: Simplification de la detection de pass valides

itou/eligibility/models/common.py, itou/www/apply/views/common.py, tests/eligibility/test_geiq.py, tests/eligibility/test_iae.py, tests/www/apply/test_process.py, tests/www/apply/test_submit.py
La version précédente était moins restrictive : les diagnostics des prescripteurs aussi étaient pris en compte. Or le métier ne souhaite appeler l'API et certifier les critères uniquement si ceux-ci sont liés à un diagnostic d'origine employeur ou GEIQ.
Créer un diagnostic et une candidature en tant que prescripteur. En tant qu'employeur, l'accepter. Les champs « ville de naissance » et « pays de naissance » ne devraient pas s'afficher.
Créer un diagnostic et une candidature en tant qu'employeur puis l'accepter. Les champs « ville de naissance » et « pays de naissance » devraient s'afficher.
Créer un diagnostic et une candidature en tant que GEIQ puis l'accepter. Les champs « ville de naissance » et « pays de naissance » devraient s'afficher.
=> Candidature : certification des critères sélectionnés pour les diags d'origine employeur ou GEIQ uniquement

itou/www/error.py
Faciliter le debug des tests pour les versions à venir.
Lors d’une erreur dans les vues, Django rend la vue 500 personnalisée par les emplois. Cette vue injectait les `context_processors` configurés dans les settings, mais django [injecte automatiquement](//github.com/django/django/blob/84d1102a8a3bba64bcc1b14a7117c26a83fb7fe5/django/template/context.py) le `context_processor` pour le CSRF. Le menu de la refonte utilise `csrf_token`, et le menu est présent dans la page d’erreur. Sans `csrf_token` dans le contexte au moment du rendu, la véritable erreur de la vue initiale était masquée par l’erreur au rendu de la page d’erreur personnalisée.
Refs #4483
=> tests: Utiliser tous les context_processors de Django dans la 500 personnalisée

itou/templates/includes/copy_to_clipboard.html, tests/gps/__snapshots__/test_views.ambr
Pour que les boutons soient plus accessibles (l’icône étant `aria-hidden=True`)
=> Accessibilité: toujours inclure un texte pour les boutons copier-coller

itou/asp/forms.py, itou/static/js/utils.js, itou/www/apply/forms.py, itou/www/employee_record_views/forms.py, tests/www/apply/test_forms.py
=> Candidature et fiche salarié : activation du champ « Commune de naissance » si le pays de naissance est la France

tests/api/test_geiq.py, tests/employee_record/test_transfer_employee_records.py, tests/job_applications/factories.py, tests/www/apply/test_list.py
Les changements introduits dans 97df9372 ont un effet de bord : on a un certain nombre de factories où l'on passe une PK uuid sous forme littérale, et du coup si effectue une comparaison ensuite (ex: `assert response.context["job_application"] == job_created_by_factory`) Django compare un objet clean hydraté depuis la db (`pk: UUID`) et l’objet créé par la factory (`pk: str`) et échoue
Cf. https://itou-inclusion.slack.com/archives/C0412CTV63D/p1723652479641059
Passer les bons types aux factories
=> Toujours passer le bon type de PK aux factories

itou/scripts/management/commands/add_admin_for_company_group.py
Support pour l'ensemblier ERGOS.
La demande actuelle est pour 95 SIRET / 49 SIREN, mais il y en a souvent d'oublié.
=> Script pour ajouter un utilisateur en tant qu'admin à une liste de SIREN tout en désactivant certaines de ses notifications

itou/metabase/management/commands/populate_metabase_matomo.py, itou/utils/date.py, tests/utils/test_date.py
J'ai aussi besoin de `monday_of_the_week()` dans une autre PR (import EA/EATT) donc autant l'utiliser partout.
En plus ça simplifie le code, la compréhension et rend la commande plus robuste dans le cas où elle ne serais plus lancée le lundi.
=> Pilotage : Simplification de code pour `populate_metabase_matomo`

tests/openid_connect/france_connect/tests.py, tests/openid_connect/pe_connect/tests.py, tests/users/test_management_commands.py, tests/users/test_models.py, tests/www/dashboard/test_edit_user_email.py, tests/www/dashboard/test_edit_user_info.py
Échec de la CI : https://github.com/gip-inclusion/les-emplois/actions/runs/10388984508/job/28765914812
```
pytest -vv tests/www/dashboard/test_edit_user_info.py::EditUserInfoViewTest -k test_edit_as_prescriber --randomly-seed=1992427615
```
=> Tests : `INCLUSION_CONNECT` est le défaut pour `PrescriberFactory()` et correction d'un test bagottant

itou/templates/layout/_header_nav_secondary_items.html
Éviter que les changements de chemin ne cassent la fonctionnalité, mieux tracer la dépendance dans le code.
Aussi, ce mécanisme se multipliant avec la refonte, autant qu’il soit plus solide.
=> Utiliser le nom de la vue au lieu de l’URL pour définir la partie active du header

itou/templates/search/siaes_search_home.html
Parcque c'est [moins bien](https://pagespeed.web.dev/analysis/https-emplois-inclusion-beta-gouv-fr/xlb8bp5vmt?form_factor=mobile) alors que ça devrait [etre mieux](https://pagespeed.web.dev/analysis/https-emplois-inclusion-beta-gouv-fr/fpq2yb69gu?form_factor=mobile)
=> UX/UI : Optimisation des performances étranges sur les images d'illustration de la homepage

docker/dev/django/entrypoint.sh
Préferer `until` à `while !`. C’est plus clair et aligné avec #4523.
=> docker: Changement mineur à l’entrypoint.sh

.github/dependabot.yml
Suite à #4531 :
> The property '#/updates/1/allow' of type object did not match the following type: array
> https://github.com/gip-inclusion/les-emplois/pull/4577/checks?check_run_id=29041932076
=> dependabot : Correction d'une erreur de syntaxe

itou/asp/forms.py, itou/static/js/utils.js, itou/templates/employee_record/create.html
Remonté par le support suite au TZ 18185.
Extraction du code actuellement utilisé dans les vues FS pour être accessible globalement.
- Acceptation d'une candidature (gabarits + htmx)
- Étape 1 du parcours de création d'une fiche salarié
=> Candidature : Correction de l'acception quand la ville de naissance n'est pas référencée pour la date de naissance renseignée

itou/templates/approvals/detail.html, itou/utils/constants.py, itou/utils/immersion_facile.py, itou/www/approvals_views/views.py, tests/utils/test_immersion_facile.py, tests/www/approvals_views/__snapshots__/test_detail.ambr, tests/www/approvals_views/test_detail.py
Permettre les employeurs accèder l'IF depuis la page d'un salarié, pour encourager les recherches à les immersions facilitées
=> [GEN-1835] Profil salarié: Accès à la Immersion Facilitée sur la page de salarié

itou/prescribers/enums.py, itou/prescribers/models.py, itou/templates/apply/list_of_available_exports.html, itou/templates/dashboard/includes/stats.html, itou/utils/apis/metabase.py, itou/www/apply/views/list_views.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/utils.py, itou/www/stats/views.py, tests/www/stats/test_utils.py, tests/www/stats/test_views.py
Je profite de ce mois calme d'août pour dépiler une petite dette technique, il restait des termes PE obsolètes dans le C2.
DTPE devient DTFT, DRPE devient DRFT et DGPE devient DGFT.
`stats_pe` dans le code devient `stats_ft` mais pour ne pas casser les stats Matomo je n'ai pas touché aux routes qui restent en `/pe/*`.
Comme je n'ai changé aucune route, je dirais que cette PR a peu de chance de casser quelque chose côté C2.
Note à moi-même : ca vaudrait peut-être le coup d'enfin casser les routes legacy `/pe/*` (devient `/ft/*`) et `/ddets/*` (devient `/ddets_iae/*`) même si ça perturbe potentiellement notre plomberie Matomo derrière. En parler aux datos à l'occasion.
Romain : si ok pour toi tu peux mepper sans attendre mon retour le 10 septembre, fais comme tu le sens.
=> Dette technique : remplacement de l'obsolète PE par FT dans certains types d'institution et dans le code de certaines stats de Pilotage

itou/www/apply/forms.py
Évite des erreurs utilisateurs.
=> Candidatures : Indiquer la date minimale pour les champs début et fin de contrat

itou/templates/dashboard/dashboard.html
Les employés France Travail n’ont pas la possibilité de changer leur adresse en autonomie.
1. ```sql
UPDATE prescribers_prescriberorganization SET geocoding_score=0.001 WHERE kind='PE' and post_code='13200';
```
2. Se connecter en tant que prescripteur habilité
=> Tableau de bord : Indiquer aux collaborateurs France Travail de contacter le support si l’adresse de leur agence est incorrecte [GEN-1919]

itou/templates/companies/job_description_list.html, itou/templates/companies/members.html, itou/www/companies_views/views.py, tests/www/companies_views/test_job_description_views.py
Éviter une erreur évitable
- Se connecter avec une EA/EATT
- Aller dans une des pages du bloc "Organisation"
=> Tableau de bord - Organisation : N'afficher le sous-menu des annexes financières que si il est utilisable

itou/job_applications/models.py
Mieux suivre l’usage de ces valeurs.
=> Préférer les constantes de JobApplicationWorkflow au lieu de leurs valeurs

itou/templates/users/details.html, itou/www/users_views/views.py, tests/gps/__snapshots__/test_views.ambr, tests/gps/test_views.py
Faire la pub de cet encart à tous les utilisateurs.
=> GPS : Toujours afficher l’encart conseiller emploi France Travail

itou/templates/stats/stats.html, itou/www/stats/views.py
1. https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-webinaire-sur-le-TB149-pour-les-ML-et-Cap-Emploi-ad4009abda4d4c71b3b60c8abf3bfd37
2. https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-webinaire-sur-le-TB-330-et-346-50f2c7764ac849a3bf1c9d19faf48dd9
3. https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-pour-annoncer-un-webinaire-dans-presque-tous-les-TB-priv-s-76b8d2405a4f4d6da2a678c3437927f3
4. https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-sur-le-TB-289-262223184ae946ad9f52836e1cf8bc6e?pvs=4
Réutilisation de ce qui avais été fait dans #4207, sauf que cette fois les bannières sont afficher sur les pages des TB.
=> Pilotage : Ajouter des encarts pour les prochains webinaires

itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_results.html, itou/utils/templatetags/nav.py, tests/www/search/tests.py
La recherche prescripteurs manque aux utilisateurs.
1. Se connecter
2. Vérifier que l’entrée est bien présente dans le menu, et qu’elle s’active lors de la navigation sur ces pages.
=> UX/UI : Rajouter l’entrée « Rechercher » dans le menu en mode connecté

itou/asp/forms.py, itou/www/apply/forms.py, itou/www/apply/views/common.py, itou/www/employee_record_views/forms.py, tests/www/apply/test_forms.py
Suite de #4590 et de https://itou-inclusion.slack.com/archives/C01181Y04LT/p1725009789547099
Pour les GEIQ, le formulaire d'acceptation ne contient pas la date de naissance ce qui causait une erreur JS (`TypeError: birthdatePicker is null`) ici:
https://github.com/gip-inclusion/les-emplois/blob/73fa8368a884f06c71c87ff19d9d68b354d2a49d/itou/static/js/utils.js#L147
rendant le champs inutilisable (et empêchant l'acceptation d'une candidature).
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette jetable, mettre …
=> GEIQ: correctif du champs "Commune de naissance" à l'acceptation d'une candidature

itou/approvals/models.py, itou/communications/cache.py, itou/companies/management/commands/_import_siae/vue_af.py, itou/job_applications/models.py, itou/metabase/tables/job_seekers.py, itou/utils/widgets.py, itou/www/apply/forms.py, itou/www/approvals_views/views.py, tests/approvals/factories.py, tests/approvals/test_notify_pole_emploi.py, tests/approvals/tests.py, tests/communications/factories.py, tests/eligibility/test_iae.py, tests/employee_record/test_models.py, tests/job_applications/tests.py, tests/metabase/management/test_populate_metabase_emplois.py, tests/www/apply/test_edit.py, tests/www/approvals_views/test_detail.py
Pas d’erreur en pratique, parce que django définit la variable d’environnement `TZ` [1] ce qui fait que Python se comporte dans la time zone définit par `settings.TIME_ZONE`. Mais ce mécanisme, assez bien caché et peu clair en intention, tombera en panne si on change la timezone (par exemple au moment du render d’un template).
[1] https://github.com/django/django/blob/cdcd604ef8f650533eff6bd63a517ebb4ffddf96/django/conf/__init__.py#L204
=> Préférer timezone.localdate()

itou/templates/includes/pagination.html, tests/www/approvals_views/test_list.py
Éviter de gérer des variables inconnues lors du rendu du template.
=> tests: Définir la variable boost pour la pagination

tests/gps/test_views.py
LE département est utilisé pour décider d’activer ou non la fonctionnalité.
```diff
FAILED tests/gps/test_views.py::test_beneficiary_details - assert [+ received] == [- snapshot]
'''
...
<div class="c-info c-info--secondary" id="advisor-info-details-collapsable">
-                                             <button aria-controls="collapseAdvisorInfoDetails" aria-expanded="false" class="c-info__summary collapsed" data-bs-target="#collapseAdvisorInfoDetails" data-bs-toggle="collapse" data-matomo-action="clic" data-matomo-category="gps" data-matomo-event="true" data-matomo-option="coordonnees-conseiller-ailleurs">
+                                             <button aria-controls="collapseAdvisorInfoDetails" aria-expanded="false" class="c-info__summary collapsed" …
```
=> Stabiliser tests/gps/test_views.py::test_beneficiary_details

itou/siae_evaluations/admin.py
Le message précédent ne laissait pas entendre que les SIAE dont le contrôle a été refusé en phase amiable passent aussi en phase contradictoire.
https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1725267230368949?thread_ts=1725264005.608879&cid=C01AQKD7MAN
=> Admin : Clarifier le message de confirmation du passage en phase contradictoire du contrôle a posteriori des auto-prescriptions

itou/metabase/management/commands/populate_metabase_emplois.py, itou/metabase/tables/companies.py, itou/metabase/tables/organizations.py, itou/metabase/tables/utils.py, tests/metabase/management/test_populate_metabase_emplois.py
Pour avoir le bon nombre de membres.
Pour les organisations, il est beaucoup trop coûteux de faire une annotation, donc je suis resté sur un calcul python avec un prefretch plus restrictif. (j'ai arrêté après 300 orga exportées sur 8600 en plus d'une minute...)
`populate_companies`
|  | avant | après |  |
| - | ----- | ------ | - |
| 1 | 91.56 s | 48.58 s |  |
| 2 | 111.66 s | 50.99 s |  |
| 3 |80.79 s  | 49.30 s |  |
| moyenne | 94.67 s | 49.62 s | -47% |
`populate_organizations`
|  | avant | après |  |
| - | ----- | ------ | - |
| 1 | 72.67 s | 70.05  s |  |
| 2 | 73.06 s | 71.34  s |  |
| 3 | 79.18 s  | 91.29 s |  |
| moyenne | 74.97 s | 77.56 s | +3% |
Il faut éviter les annotations sur les memberships / members qui sont très coûteuse (aucune idée de pourquoi :shrug:) 
> _Décrivez en …
=> Statistiques: Correction du nombre de members dans les exports

itou/common_apps/address/models.py, itou/prescribers/management/commands/sync_ft_organizations.py, tests/common_apps/address/tests.py
Plusieurs problèmes récent sur les agences FT :
- Codes safir inexistants
- Adresses erronées
Donc ne tergiversons pas et mettons en place une synchro afin d'être proactif plutôt que réactif, surtout que l'édition est bloquée pour les utilisateurs donc cela devrais aussi éviter des tickets à faible valeur au support.
- Configurer les settings pour l'API FT
- Lancer la commande
=> Prescripteur : Synchronisation des informations pour les agences France Travail depuis leur API

itou/emails/migrations/0001_initial.py, itou/emails/models.py
Permettre au support de corriger les typos évidentes.
https://itou.sentry.io/issues/5490570470/
=> Admin : Permettre la modification des champs des e-mails

clevercloud/cron.json
Dès un nouveau candidat s'inscrit sur la plateforme, on veut que son conseiller est mis à jour avec les meilleurs de délais
Avec une tâche cron de chaque 15 minutes, pendant les heures de travail
=> Demandeur d’emploi: Mettre à jour le conseiller FT toutes les 15 minutes

Makefile, tests/conftest.py
Importer depuis l’app django avant qu’elle ne soit prête cause des exceptions.
```shell
$ pytest --help
```
=> Corriger pytest --help

tests/gps/test_views.py
45d28219e6c49df3ac94adb2880517830e7c7089 fixed the beneficiary
department instead of the viewer department.
=> Stabiliser gps test_beneficiaries pour de vrai

itou/templates/includes/pagination.html
=> Utiliser des valeurs par défaut pour boost_{indicator,target} dans la pagination

itou/users/admin.py
Utile au support pour trouver des doublons.
Mais je me demande si pour trouver les candidats ils ne devraient pas prendre l'habitude d'aller chercher dans les profils de demandeur d'emploi ?
=> Admin: retour du champ date de naissance dans la liste des utilisateurs

itou/users/migrations/0012_remove_user_birthdate.py, itou/users/migrations/0013_drop_users_user_birthdate_for_real.py
Suite de #4662 & #4666 .
Maintenant que les migrations sont passées en production, on peut se débarasser du `SeparateDatabaseAndState` et faciliter un futur squash.
=> Tech: simplification des migrations de suppression du champ date de naissance

itou/employee_record/admin.py, itou/geiq/admin.py, itou/utils/admin.py
[LES-EMPLOIS-PROD-1W7](https://itou.sentry.io/issues/5511743562/) et éviter des erreurs humaines.
=> Admin : Lecture seule pour les `EmployeeRecordUpdateNotification()`

itou/templates/apply/process_base.html, itou/templates/approvals/printable_approval.html, itou/templates/layout/_header.html, itou/templates/layout/_header_authenticated.html, itou/templates/layout/_header_print.html, itou/templates/layout/base_printable.html, itou/utils/staticfiles.py
- Maj du thème pour supporter les règles globales d'impression
- Ajout du `header_print`
- Adaptation de la page "attestation imprimable" aux règles globales d'impression 
- Ajout du bouton "Imprimer” sur la page de détail Candidat
=> UX/UI: Ajout du bouton "Imprimer” sur la page de détail Candidat
