gip-inclusion/les-emplois

- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
> Requête en moins pour la mise à jour d'un candidat

- tests/approvals/test_management_commands.py
Pour éviter ce genre d'erreur: https://github.com/gip-inclusion/les-emplois/actions/runs/7883952946/job/21511919525
> tests: correction d'un test

- itou/companies/admin.py
- tests/companies/__snapshots__/test_admin.ambr
- tests/companies/test_admin.py
https://itou-inclusion.slack.com/archives/C01181Y04LT/p1707838145876559
> Améliorer les perfs de admin:companies_company_add

- itou/approvals/admin.py
> admin: correction de la recherche de PASS IAE

- itou/settings_viewer/views.py
- tests/settings_viewer/tests.py
- tests/utils/tests.py
Pour détecter plus facilement des soucis, typiquement: #3653 & #3656
> tests: toutes les vues de liste & recherche dans l'admin

- itou/templates/hijack/notification.html
- itou/templates/layout/base.html
- itou/templates/layout/base_printable.html
- itou/templates/utils/widgets/csp_proof_openlayers-osm.html
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#type
https://github.com/django/django/commit/7c4f3965098baad2396e24501e09237425a7bd6f
> Retirer text/css des link stylesheet et style

- CHANGELOG_breaking_changes.md
- docker-compose.yml
- Fixups to the document on how to setup Redis locally
- Set REDIS_URL for the django docker
> MàJ pour Redis

- itou/templates/apply/includes/transition_logs.html
- itou/www/apply/views/process_views.py
- tests/job_applications/factories.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_process.py
> [GEN-7913] MàJ de l’encart historique de la candidature

- itou/templates/companies/card.html
- itou/templates/companies/edit_siae_preview.html
- itou/templates/companies/includes/_siae_details.html
- itou/templates/includes/email_li.html
- itou/templates/includes/phone_li.html
- itou/templates/includes/website_li.html
- tests/www/companies_views/__snapshots__/test_views.ambr
> [GEN-8052] Afficher les emails très long sans dépasser pour les contacts SIAE

- tests/www/apply/test_geiq.py
> tests: correction d'un test flaky

- tests/www/apply/test_submit.py
> tests: correction de certains appels à assertTemplate(Not)Used

- config/settings/base.py
- config/settings/dev.py
> Retirer le setting SQL_DEBUG

- itou/templates/dashboard/dashboard.html
This reverts commit 2425f0dc7c5d71ab8c9aaa18309098efc71c1525.
The survey is complete.
https://itou-inclusion.slack.com/archives/C0412CTV63D/p1708348638010479
> Retirer l’enquête tally pour les employeurs

- itou/prescribers/admin.py
https://plateforme-inclusion.zendesk.com/agent/tickets/10596/
> Ajouter le champ description à PrescriberOrganizationAdmin

- itou/templates/apply/email/diagoriente_job_seeker_invite_body.txt
- itou/templates/apply/email/diagoriente_prescriber_invite_body.txt
- itou/templates/apply/submit/application/resume.html
- itou/templates/dashboard/dashboard.html
- itou/templates/dashboard/includes/diagoriente_card.html
- itou/templates/dashboard/includes/job_seeker_job_applications_card.html
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/dashboard/tests.py
Refs 3cae6123ba0a9557638462a6555cb5c0d1c065d4
GEN-8004
> [GEN-8004] MàJ les URLs Diagoriente 

- itou/templates/apply/includes/job_application_info.html
- itou/templates/apply/includes/transition_logs.html
- itou/templates/apply/process_details.html
- itou/templates/apply/process_details_company.html
- tests/www/apply/__snapshots__/test_process.ambr
https://www.notion.so/plateforme-inclusion/Modifier-l-ordre-et-affichage-de-historique-des-modifications-et-ajouter-un-tat-boost-d24fc4ec8fe94353adb28f0e9746758b
> [GEN-7913] Amélioration de la page de détail candidature

- config/settings/base.py
- itou/www/middleware.py
- tests/www/test_check_health.py
> Add a check-health endpoint

- tests/api/applicants_api/tests.py
- tests/job_applications/tests.py
- tests/www/approvals_views/test_pe_approval.py
- tests/www/dashboard/tests.py
- tests/www/employee_record_views/test_disable.py
- tests/www/employee_record_views/test_list.py
- tests/www/employee_record_views/test_reactivate.py
- tests/www/search/tests.py
- tests/www/welcoming_tour/tests.py
Éviter d’exécuter du code avant chaque test alors qu’on peut le faire une bonne fois pour toute.
> Correction mineures de setUp dans les tests

- itou/templates/search/prescribers_search_results.html
- itou/utils/staticfiles.py
Evolutions UI
Dans le template de résultat de recherche prescripteurs
Avant
Apres
> Refonte UX/UI: Maj UI des cartes prescripteurs

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
- tests/www/dashboard/__snapshots__/tests.ambr
- tests/www/dashboard/tests.py
> Ajouter la recherche employeur au tableau de bord [GEN-8016]

- itou/templates/apply/includes/job_application_answers.html
- itou/templates/apply/includes/job_application_info.html
- itou/templates/apply/includes/job_application_sender_info.html
- itou/templates/apply/includes/job_seeker_info.html
- itou/templates/apply/includes/siae_hiring_details.html
- itou/templates/approvals/includes/list_card.html
- itou/templates/approvals/list.html
- itou/utils/staticfiles.py
Évolutions UI
Dans la page de gestion des salariés et PASS IAE
Avant
Apres
> Refonte UX/UI: Maj UI des cartes salariés et pass iae

- itou/users/migrations/0043_prevent_pe_connect_duplicates.py
> Empêcher la création de doublons PE Connect

- itou/templates/static/security/security.txt
> security.txt: vérification et mise à jour

- itou/templates/employee_record/includes/list_item.html
- itou/templates/employee_record/list.html
- tests/job_applications/factories.py
- tests/www/employee_record_views/__snapshots__/test_list.ambr
- tests/www/employee_record_views/test_list.py
Évolutions UI
Dans la liste des Fiches salarié ASP
Avant
Apres
> Refonte UX/UI: Maj UI des cartes fiches salariés

- itou/companies/models.py
- tests/www/search/tests.py
The assertNotContains was previously moot.
> Afficher le badge populaire sur les descriptions de postes à partir de 20 candidatures

- itou/templates/approvals/includes/job_description_creation.html
- tests/www/apply/__snapshots__/test_list.ambr
Correction d'une petite classe sur un lien
Avant
Apres
> Fix candidature card job list 

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
> Ajouter une banière Mobil’Emploi prescripteurs [GEN-8211]

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
> Ajouter une banière Mobil’Emploi pour IDF et ARA [GEN-8220]

- tests/www/companies_views/test_views.py
https://github.com/gip-inclusion/les-emplois/pull/3698/files/b21223039828a05031620d7b9bc5ae2785f5a48d#diff-3b4dee06acaad928c18ff2145af4d60a079b01d0a63a4fdd5c44b9f21fa6dba0
> Correction mineure de tests.companies_views

- itou/templates/dashboard/dashboard.html
Voir https://itou-inclusion.slack.com/archives/C0412CTV63D/p1710499382870459
> Ajout d'évènements Matomo aux nouvelles bannières Mobil'Emploi

- itou/templates/apply/includes/accept_section.html
- itou/templates/approvals/declare_prolongation.html
- itou/templates/approvals/pe_approval_search.html
- itou/templates/approvals/suspend.html
- itou/templates/siae_evaluations/institution_evaluated_siae_detail.html
- itou/www/apply/views/common.py
- itou/www/apply/views/edit_views.py
- itou/www/apply/views/process_views.py
- itou/www/approvals_views/views.py
- itou/www/dashboard/views.py
- itou/www/invitations_views/views.py
- tests/www/siae_evaluations_views/test_institutions_views.py
> Changer certaines bannières infos/alertes par des toasts, texte, …  (3/3)

- itou/templates/companies/edit_job_description_preview.html
https://www.notion.so/plateforme-inclusion/Modifier-une-fiche-de-poste-Bouton-Enregistrer-les-modifications-boost-cf34aa1d12564488bafc1e74653159c2?pvs=4
> Modifier le label du bouton pour enregistrer les modifications d'une ficher de poste

- itou/utils/perms/middleware.py
- itou/www/approvals_views/forms.py
> Préparation Django 5 - mark_safe

- itou/fixtures/django/21_approvals.json
Tous les PASS sont créés expirés autrement.
> MàJ des dates de PASS IAE dans les fixtures [GEN-8242]

- config/settings/base.py
- itou/utils/cache.py
- tests/www/companies_views/__snapshots__/test_views.ambr
- tests/www/companies_views/test_views.py
> Fix échecs intermittents DRF rate-limits

- itou/templates/companies/card.html
- itou/templates/companies/job_description_card.html
- itou/templates/includes/copy_to_clipboard.html
- itou/www/companies_views/views.py
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/companies_views/__snapshots__/test_views.ambr
- tests/www/companies_views/test_views.py
Pour répondre a cette demande
https://www.notion.so/plateforme-inclusion/Engagement-S-curit-Signaler-une-fiche-de-poste-boost-245b6d6290fe4944bd3d13975df9aa1a?pvs=4
> Ajout d'actions dans la barre d'action des fiches de poste [GEN-8001]

- itou/templates/companies/job_description_list.html
- itou/templates/companies/members.html
- itou/templates/companies/show_financial_annexes.html
- itou/templates/includes/members.html
- itou/www/companies_views/views.py
- tests/www/companies_views/test_job_description_views.py
Évolutions UI
Maj du DOM et de la version du thème
Avant
Apres
> Refonte UX/UI: Ajouter un menu en onglets sur les pages “structure”

- tests/approvals/test_admin.py
- tests/approvals/tests.py
- tests/employee_record/test_admin.py
- tests/job_applications/test_admin.py
- tests/openid_connect/inclusion_connect/tests.py
- tests/siae_evaluations/test_admin.py
- tests/users/test_admin_views.py
- tests/utils/test.py
- tests/utils/tests.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/approvals_views/test_pe_approval.py
- tests/www/approvals_views/test_prolongation_requests.py
- tests/www/companies_views/test_job_description_views.py
- tests/www/employee_record_views/test_list.py
- tests/www/invitations_views/test_company_accept.py
- tests/www/invitations_views/test_prescriber_organization.py
- tests/www/login/tests.py
- tests/www/siae_evaluations_views/test_institutions_views.py
- tests/www/siae_evaluations_views/test_siaes_views.py
- tests/www/signup/test_prescriber.py
- tests/www/signup/test_siae.py
> Migration à l'assertMessages natif de Django 5

- itou/users/management/commands/pe_certify_users.py
- tests/users/test_management_commands.py
Sinon, après une première erreur on ne réessayait jamais (sauf lors d'une modification de prénom/nom/...).
> Ajout d'un ré-essai régulier d'identification des profils de demandeur d'emploi chez France Travail

- itou/static/js/htmx_compat.js
- itou/static/js/htmx_handlers.js
- itou/static/js/job_applications_filters.js
- itou/templates/apply/includes/list_job_applications.html
- itou/templates/apply/list_for_siae.html
- itou/templates/includes/pagination.html
- itou/templates/layout/base.html
- itou/www/apply/views/list_views.py
- tests/utils/htmx/test.py
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/test_list.py
Limiter les rechargements de la page, pour une meilleure expérience utilisateur.
La construction des filtres étant assez coûteuse, on devrait aussi constater
une légère amélioration de performance.
1. Se connecter en tant que l’EI garage martinet.
2. Aller à la liste des candidatures
3. Filtrer, naviguer entre les pages
Admirez la fluidité :grin:
> Filtrer les candidatures des SIAE avec HTMX

- itou/common_apps/organizations/admin.py
- itou/common_apps/organizations/models.py
- itou/common_apps/organizations/views.py
- itou/templates/common/emails/add_admin_email_body.txt
- itou/templates/common/emails/add_admin_email_subject.txt
- tests/common_apps/organizations/tests.py
- tests/companies/test_admin.py
- tests/institutions/tests.py
- tests/prescribers/tests.py
- tests/www/companies_views/test_views.py
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/test_admins.py
- tests/www/prescribers_views/test_members.py
Donner + d’infos sur le rôle d’administrateur et conseiller d’en nommer plusieurs
> Améliorer le mail d'accueil pour les administrateurs

- itou/templates/layout/_header_nav_primary_items.html
> [GEN-8199] Modification de l'icone de sélection de structure pour les prescripteurs

- itou/static/js/job_applications_filters.js
Sinon les filtres ne marchent pas.
> Liste de candidatures: correctif pour les prescripteurs et candidat

- itou/templates/api/index.html
Améliorer nos APIs en fonction des retours utilisateurs.
> Inviter les développeurs à nous contacter à propos des API

- itou/templates/account/includes/login_form.html
- itou/templates/apply/submit/application/end.html
- itou/utils/staticfiles.py
Pour corriger 2 petits bugs graphiques
- https://www.notion.so/plateforme-inclusion/UI-D-calage-dans-les-boutons-de-formulaires-de9d065691ab4452a291a68b5a6d8e5d?pvs=4
- https://www.notion.so/plateforme-inclusion/Probl-me-doublon-de-texte-dans-une-formulaire-4a24a36136434ff383ffe213134358bc?pvs=4
> Correctif de wording et petit bug ui sur le boutons de formulaires

- itou/templates/companies/job_description_list.html
- itou/utils/staticfiles.py
Pour corriger un problème de conflit de z-index entre .modal et .tab-content
> Mise a jour du theme itou vers la v1.5.1

- itou/job_applications/models.py
Early PR pour les notifications.
Refs https://github.com/gip-inclusion/les-emplois/pull/3652/files#r1551540491
> Ré-ordonnancement des méthodes de JobApplication

- itou/www/signup/views.py
Éviter les 500.
https://itou.sentry.io/issues/5122983068/
> Gérer un email manquant dans ItouResetPasswordView

- CHANGELOG.md
Pour savoir ce qui a changé ces 2 dernières semaines.
> changelog: Sprint 84

- itou/www/apply/views/process_views.py
https://github.com/gip-inclusion/les-emplois/security/code-scanning/58
https://cwe.mitre.org/data/definitions/601.html
> Supprimer une redirection ouverte dans la vue de transfer de candidature

- itou/templates/search/siaes_search_home.html
Suite de https://github.com/gip-inclusion/les-emplois/pull/3806
> Mise à jour du 1er paragraphe de l'accueil

- itou/templates/search/siaes_search_home.html
Suite de https://github.com/gip-inclusion/les-emplois/pull/3828
> Mise à jour du 2e paragraphe de l'accueil

- itou/templates/dashboard/dashboard.html
Demande UX.
:technologist: Captures d’écran
> Prescripteurs : Recherche de volontaires pour construire l’espace « Mes candidats » [GEN-1539]

- itou/static/js/sliding_tabs.js
- itou/templates/apply/submit_step_check_job_seeker_nir.html
- itou/templates/signup/job_seeker_nir.html
- itou/utils/staticfiles.py
C'est pas beau et ça aide pas à la lecture
Au passage maj du thème pour intégrer la prise en charge des boutons de swipe sur les onglets en mobile
> Correction saut de ligne

- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/dashboard/views.py
- itou/www/stats/urls.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_utils.py
> Pilotage : Ouvrir le TB149 "Etat des candidatures orientées" à d’autres prescripteurs habilités sur 3 régions [ITOU-8130]

- Makefile
> Linter les scripts du dossier scripts/

- tests/metabase/management/test_populate_metabase_emplois.py
https://github.com/gip-inclusion/les-emplois/actions/runs/8602168736/job/23571094021
> Stabiliser test_populate_job_seekers

- itou/templates/dashboard/dashboard.html
> Prescripteurs : Fin de la recherche de volontaires pour l’espace « Mes candidats » [GEN-1539]

- itou/templates/account/logout.html
- itou/templates/dashboard/edit_user_info.html
- itou/templates/siae_evaluations/sanctions_helper.html
- itou/templates/signup/choose_user_kind.html
- itou/templates/signup/company_select.html
- itou/templates/signup/prescriber_check_already_exists.html
- itou/templates/signup/prescriber_choose_kind.html
- itou/templates/signup/prescriber_choose_org.html
- itou/templates/signup/prescriber_is_pole_emploi.html
- itou/templates/signup/prescriber_request_invitation.html
- itou/templates/signup/prescriber_user.html
- itou/templates/static/legal/privacy.html
- itou/templates/stats/stats.html
Pour continuer a harmoniser la mise en forme des formulaires
En vérifiant la présence d'un `.c-form` sur toutes les étapes de formulaires de connexion et d’inscription
- sur la page stats, suppression d'une alerte inutile
- sur certaines pages, déplacement de texte de titre dans la zone de titre
> Refonte UX/UI - Formulaires de connexion/inscription dans des .c-form

- itou/companies/management/commands/_import_siae/siae.py
Cas très particulier, voir le message de commit et les commentaires.
> Gestion d’un cas très particulier dans l’import SIAE

- itou/templates/apply/email/refuse_body_for_job_seeker.txt
- itou/templates/approvals/email/prolongation_request/denied/jobseeker_body.txt
> Partenariat : mise à jour du message de l'AFPA dans les messages de candidature

- .github/workflows/notify-slack.yml
Pour éviter des soucis d'échappement (:crossed_fingers: ).
En bidouillant un peu les conditions :see_no_evil: : https://itou-inclusion.slack.com/archives/C03ES35UL30/p1713514821160999
> :wrench: notify_slack: utilisation de la github action Slack pour tenter d'éviter les soucis avec ' ou " :crossed_fingers:

- .github/workflows/notify-slack.yml
Pour avoir de jolies notifications dans Slack, quelque soit le titre de la PR.
Cf https://github.com/slackapi/slack-github-action/issues/202#issuecomment-1769132156
En bidouillant les conditions, une nouvelle fois.
Cf https://itou-inclusion.slack.com/archives/C03ES35UL30/p1713520075945339 pour le résultat.
> :wrench: notify_slack: nouvelle version pour échapper les " (ainsi que les ' qui ne devraient plus poser soucis) :crossed_fingers: 

- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/views.py
Suite à une demande de nos amis de la dgefp, ouverture de tous les TBs DDETS/DREETS au compte dgefp.
> Ouverture des TBs DDETS/DREETS à la DGEFP

- config/settings/base.py
Activation de la fonctionnalité GPS dans tous les environnements sauf en prod.
> GPS : ajout d'un feature flag

- itou/templates/approvals/includes/job_description_creation.html
- itou/templates/employee_record/includes/_status.html
- itou/utils/templatetags/job_applications.py
- tests/utils/__snapshots__/tests.ambr
- tests/www/apply/__snapshots__/test_list.ambr
Problème UI
Mise a jour du css pour les cartes candidatures
Mise a jour du display des .badge dans les cartes
> Correction d'un bug de mise en forme sur les cartes candidatures

- itou/templates/employee_record/list.html
> Retirer les format_filters de employee_record/list.html

- itou/www/apply/urls.py
- itou/www/apply/views/process_views.py
Cela fait 8 mois qu'il ne sert plus.
> Suppression de code inutilisé

- itou/www/apply/views/common.py
- itou/www/apply/views/process_views.py
Les GEIQ ne sont pas des SIAE.
> Renommer des siae en company dans le contexte de GEIQ

- scripts/mkchangelog
Les dates de recherche sont inclusives.
> Éviter les recoupements entre les semaines du journal des modifications

- scripts/create-fast-machine.sh
Changé depuis d2fbdcc2a847a4d8ad9ef289ff1d4fe2c4d2d79b.
> MàJ les instructions pour lancer les imports IAE / EA-EATT

- itou/users/models.py
- tests/users/test_models.py
En espérant que ça n’ait pas eu d’impact.
> Correction d’une typo dans latest_common_approval

- scripts/mkchangelog
> Trier les entrées du changelog en ignorant la casse de caractère

- itou/templates/layout/base.html
> Documenter que matomoMore s’exécute après trackPageView

- config/settings/base.py
Cf https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=Sirene&version=V3.11&provider=insee:
Sirene 4 - décommissionnement de l'Api Sirene 3.09 :
• L'Api Sirene 3.11 devient la version de référence, avec une mise à jour quotidienne et remplace l'Api 3.09.
Aussi à la date du 30 avril au soir, l'Api 3.9 sera décommissionnée et donc inaccessible.
• Le répertoire Sirene en version 4 effectue toujours régulèrement des opérations qualité.
Nous vous invitons à consulter régulièrement « Sirene.fr » pour obtenir le détail des opérations et en suivre l’avancement.
```
>>> settings.API_INSEE_SIRENE_BASE_URL="https://api.insee.fr/entreprises/sirene/V3"
>>> api_entreprise.etablissement_get_or_error("13003013300016")
{"message": "HTTP Request: POST …
```
> Inscription: correction du chemin d'accès à l'API SIRENE de l'INSEE

- itou/templates/layout/base.html
Cf https://github.com/gip-inclusion/les-emplois/pull/4025/files/ab1cb6f3443d6d669fe1847e63ef4e5db3ca0c9b#r1590692850
Se connecter en tant que candidat et modifier son profil.
ou
Se connecter en tant qu'employeur et accepter une candidature.
> Suppression de code dupliqué pour l'affichage des toasts

- itou/templates/dashboard/includes/stats.html
Demande Pilotage.
https://itou-inclusion.slack.com/archives/C0412CTV63D/p1715605889873649?thread_ts=1715100019.478449&cid=C0412CTV63D
> Pilotage : Afficher les stats de la campagne de contrôle a posteriori 2024 pour la DGEFP

- CHANGELOG.md
> Cosmétique sur le changelog

- itou/eligibility/models/iae.py
- itou/job_applications/models.py
> Rendre EligibilityDiagnosis.for_job_seeker_and_siae plus joli

- itou/approvals/management/commands/prolongation_requests_chores.py
https://itou.sentry.io/issues/5388863218/
> Utiliser une transaction pour prolongation_requests_chores

- itou/templates/dashboard/dashboard.html
Aider les structures qui ont plusieurs antennes.
Connectez-vous avec des utilisateurs de différentes organisations (prescripteurs et employeurs)
> Tableau de bord: Afficher le type de structure/organisation dans le tableau de bord [GEN-156]

- itou/common_apps/address/models.py
Parce qu'il existe, et parce que ça me faisait mal au cœur de voir ces boucles inutiles.
> Adresse: utilisation du dictionnaire inversé `DEPARTMENT_TO_REGION` pour trouver la région d'un département

- itou/templates/approvals/suspension_action_choice.html
- itou/templates/approvals/suspension_update.html
Pour améliorer l'ux https://www.notion.so/plateforme-inclusion/Am-liorer-la-navigation-dans-le-parcours-de-modification-d-une-suspension-de-PASS-IAE-7a431b1debec41b893b01fa53fc01d8e?pvs=4
> UX/UI : Améliorer la navigation dans le parcours de modification d’une suspension de PASS IAE

- itou/job_applications/models.py
- itou/users/models.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- tests/users/test_models.py
Clarifier, l’ancien nom étant assez obscur pour moi.
> Renommer approval_{can_be_renewed_by,needs_new_eligibility_diagnosis}

- tests/approvals/factories.py
> Factories: Utiliser le diag d’éligibilité du pass sur la candidature

- itou/openid_connect/models.py
- tests/openid_connect/france_connect/tests.py
- tests/openid_connect/pe_connect/tests.py
Voir https://itou.sentry.io/issues/4985379533/events/8e0459caf3b84ba78f48e47a609c22dd/?project=6164438&query=is%3Aunresolved+level%3Aerror&referrer=previous-event&statsPeriod=14d&stream_index=10
Un candidat se connectant avec FC ou FTC mais dont l'email existe déjà sur un compte prescripteur ou employeur passait entre les mailles du fillet jusqu'à présent, mais cela plantait en essayant de mettre à jour les infos dans job_sekker_profile.
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette jetable, mettre l'URL …
> Connexion: Amélioration des levée d'erreur en se connectant avec France Connect ou France Travail Connect

- itou/utils/apis/geocoding.py
- tests/common_apps/address/tests.py
correction de l'erreur sentry: https://itou.sentry.io/issues/5144204056/?project=6164438&query=is%3Aunresolved+level%3Aerror&referrer=issue-stream&statsPeriod=14d&stream_index=8
> Prescripteur: Correction de la géolocalsation sans adresse

- itou/templates/layout/_header.html
- itou/utils/staticfiles.py
- tests/www/__snapshots__/test_layout.ambr
Mise a jour du theme vers la v1.6.5 et adaptation du DOM du menu #burgerNav pour utiliser le offcanvas natif de bootstrap plutot que le js custom
**Avant**
**Apres**
> UX/UI : Mise a jour du theme et adaptation du DOM du menu #burgerNav

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
https://www.notion.so/plateforme-inclusion/Banni-re-promo-Bimbamjob-mobil-emploi-sur-les-TDB-des-candidats-d-ARA-et-IDF-2e-campagne-7aec035d90294e748e20f101b9c220dd?pvs=4
https://www.notion.so/plateforme-inclusion/Banni-re-promo-Mobil-Emploi-de-bimbam-job-sur-les-tableaux-de-bord-des-prescripteurs-IDF-et-ARA-hor-c65e045fd8ec4675938370cb42d7ee74?pvs=4
> Notifications: Remise en place d'une banière Mobil’Emploi

- itou/utils/tasks.py
Dans l’environnement de développement, les emails ne passent pas par Anymail et n’ont pas l’attribut `anymail_status`, ce qui donne des exceptions dans la console de dev.
Exemple :
```
Unhandled exception in task 8d557b55-0a22-4437-9134-4aa7986a7316.
Traceback (most recent call last):
File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/huey/api.py", line 382, in _execute
task_value = task.execute()
^^^^^^^^^^^^^^
File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/sentry_sdk/utils.py", line 1711, in runner
return sentry_patched_function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/huey.py", line 130, in _sentry_execute
reraise(*exc_info)
File …
```
> Gérer l’attribut manquant `anymail_status` sur les emails envoyés en dev

- CHANGELOG.md
- scripts/mkchangelog
Sinon les sprints se décalent d'un jour toutes les semaines
> Correction de la durée du sprint

- itou/templates/prescribers/members.html
Demande UX : https://itou-inclusion.slack.com/archives/C0412CTV63D/p1717417266160199
> Suppression du message d'alerte pour inviter à remplir en enquête sur la réattribution des candidatures d’un collaborateur

- itou/users/models.py
- tests/users/test_models.py
cc https://itou-inclusion.slack.com/archives/C03ES35UL30/p1717422101245029?thread_ts=1717144213.260569&cid=C03ES35UL30
> Ajout d'un commentaire sur User.first_login

- itou/www/approvals_views/views.py
- tests/www/approvals_views/test_suspend.py
Pour réduire le nombre de requête SQL.
A la base ajoutés pour voir si un cache était vraiment utile mais ça ne fera pas de mal de les avoir.
> Ajout de select_related

- itou/templates/apply/includes/job_applications_export_button.html
- itou/templates/apply/includes/list_job_applications.html
- itou/templates/apply/list_for_prescriber.html
- itou/templates/apply/list_for_siae.html
- itou/templates/apply/list_of_available_exports.html
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/__snapshots__/test_list_for_prescriber.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
Évolutions UX/UI
Maj des templates
**Avant**
**Apres**
> UX/UI : Ajout de cta dans la zone de titre des liste de candidatures

- docs/environment.md
Communiquer avec les collègues et faciliter la prise en main de l’app.
> Documenter les variables d’environnement principales

- itou/siae_evaluations/admin.py
voir https://itou-inclusion.slack.com/archives/C01181Y04LT/p1717504468037729?thread_ts=1717503357.073439&cid=C01181Y04LT
J'ai été payé en chocolat noir en échange
> Admin: Améliorer les filtres de la section contrôle à posteriori

- itou/templates/layout/_header_nav_primary_items.html
- tests/www/__snapshots__/test_layout.ambr
Pour informer les utilisateurs des évolutions du site
Dans le dropdown “Besoin d’aide”, ajouter un lien “Nouveautés” tout en bas
> UX/UI: Ajout du lien "nouveautés" dans le menu du header

- itou/approvals/models.py
- itou/utils/db.py
- itou/www/approvals_views/forms.py
> Ajouter un utilitaire or_queries

- itou/users/apps.py
- itou/users/models.py
Solution plus simple sans nouveau signal ni trigger psql
> Statistiques: Correction d'un code de dénormalisation

- itou/files/forms.py
```
In [1]: from django.utils.html import format_html
In [2]: format_html("%s %s", "toto", "titi")
Out[2]: '%s %s'
In [3]: format_html("{} {}", "toto", "titi")
Out[3]: 'toto titi'
```
> UX/UI: correction du lien d'aide à la conversion d'un pdf sur le widget d'upload de fichier

- itou/templates/hijack/notification.html
Sinon on se prend une 500 et ça ne marche plus.
> django-hijack: correction du CSS

- itou/common_apps/organizations/models.py
- itou/companies/models.py
- itou/institutions/models.py
- itou/invitations/models.py
- itou/openid_connect/inclusion_connect/models.py
- itou/prescribers/models.py
- itou/www/itou_staff_views/export_utils.py
- itou/www/itou_staff_views/views.py
- itou/www/signup/views.py
- tests/companies/test_models.py
- tests/institutions/tests.py
- tests/invitations/tests.py
- tests/prescribers/tests.py
On a des incohérences entre le type d'utilisateur et les memberships.... :roll_eyes: 
> Correction de l'export CTA

- clevercloud/cron.json
- config/settings/base.py
- itou/emails/admin.py
- itou/emails/apps.py
- itou/emails/management/commands/delete_old_emails.py
- itou/emails/migrations/0001_initial.py
- itou/emails/models.py
- itou/emails/tasks.py
- itou/static/css/itou-admin.css
- itou/templates/admin/emails/mailjet_status.html
- itou/users/admin.py
- itou/utils/tasks.py
- tests/conftest.py
- tests/emails/conftest.py
- tests/emails/test_admin.py
- tests/emails/test_commands.py
- tests/emails/test_tasks.py
- tests/utils/test_emails.py
- tests/www/siae_evaluations_views/test_siaes_views.py
Faciliter l’investigation support si une personne ne reçoit pas d’e-mails du système.
En enregistrant les e-mails envoyés par le système dans une table de la base de données.
Enregistrer le détail de l’email à envoyer, et se baser sur l’ID de l’e-mail dans la tâche asynchrone permet de corriger les éléments incorrects avant de réessayer d’envoyer l’email. Il est également possible d’arrêter d’essayer d’envoyer un email en le supprimant de la table.
Pas mal de logs ont été ajouté pour améliorer notre connaissance de l’API Mailjet, étant donné que la documentation contient pas mal de trou sur les réponses en cas d’erreur.
L’index GIN a été testé pour des recherches dans une table avec 3 millions d’entrées factices, les requêtes sont traitées en une centaine de ms.
La table contenant des …
> Admin : Améliorer le suivi des emails envoyés [GEN-1670]

- itou/www/dashboard/views.py
- tests/www/dashboard/tests.py
https://itou.sentry.io/issues/5486138049/?notification_uuid=75bb3c6a-0729-4721-abe9-3d3120bb9882&project=6164438&referrer=assigned_activity-email
> Correction de la page de migration vers IC pour les utilisateurs non connectés

- tests/utils/test.py
Correction des tests flaky.
```sh
pytest --randomly-seed=3684186301 tests/prescribers/tests.py::test_add_admin
```
> Correction de create_fake_postcode

- itou/approvals/admin.py
- itou/users/admin.py
Pour faciliter le travail de l'équipe support 
> Admin: Ajout de la date des candidatures dans certaines pages [GEN-1598]

- tests/siae_evaluations/test_models.py
Cf https://github.com/gip-inclusion/les-emplois/actions/runs/9515754725/job/26230641875
Avec `--randomly-seed=4256415343`, la contrainte `unique_ddets_per_department` :boom: 
> tests: correction d'un test instable

- itou/templates/geiq/assessment_info_for_employer.html
- itou/templates/geiq/assessment_info_for_labor_inspector.html
- tests/www/geiq_views/__snapshots__/tests.ambr
C'est comme cela que le rapport s'appelle dans l'interface Label.
> GEIQ: renommage du rapport d'activité en document de synthèse

- itou/templates/geiq/assessment_info_for_employer.html
> GEIQ: ajout d'un formulaire Tally pour recueillir le retour des employeurs GEIQ [GEN-1757]

- tests/metabase/management/test_populate_metabase_emplois.py
https://github.com/gip-inclusion/les-emplois/actions/runs/9562242773/job/26358210175
> tests: correction d'un autre test instable

- itou/geiq/migrations/0001_initial.py
- itou/geiq/models.py
> GEIQ: renommage du champ "Rapport d'activité" en "Document de synthèse" dans l'admin également

- itou/job_applications/models.py
- itou/www/apply/views/process_views.py
- tests/job_applications/test_transfer.py
- tests/job_applications/tests.py
- tests/www/apply/test_process.py
Reprise du code de transition des candidatures pour préparer #4160 
> Candidature: Amélioration des transitions d'état

- itou/templates/approvals/includes/approvals_filters/expiry.html
- itou/templates/employee_record/includes/employee_record_filters/status.html
- itou/templates/layout/_header_nav_primary_items.html
- tests/www/__snapshots__/test_layout.ambr
> UX/UI : Fusionner les dropdown-item et dropdown-divider avec leur li

- tests/siae_evaluations/test_models.py
Encore et toujours `unique_ddets_per_department` 
> tests: correction d'un test instable (oui, encore)

- tests/www/apply/test_list_for_siae.py
> tests: Ajouter un commentaire à test_list_for_siae_filter_for_different_kind

- tests/www/geiq_views/tests.py
with --randomly-seed=4151567629 unique_ddets_per_department contraint failed
> Test: correction d'un test

- tests/www/search/tests.py
> tests: màj de JobDescriptionSearchViewTest assertNumQueries

- tests/gps/tests.py
La date change tous les jours :)
> Correction d'un test avec snapshot

- itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py
- itou/api/models.py
Ils peuvent être liés à tout type d'entreprise, pas uniquement des SIAE (et actuelllement ce sont uniquement des GEIQ)
> API: changement de nom du modèle CompanyToken

- itou/gps/admin.py
- itou/gps/migrations/0001_initial.py
- itou/gps/models.py
- itou/utils/apis/metabase.py
Pour suivre l'impact.
:warning: J'ai changé la branche de base pour bénéficier des nouvelles fixtures. Seul le dernier commit (le mien) est à prendre en compte.
Se connecter à l'admin et regarder dans GPS > relations si tout convient.
> GPS : visualiser les relations dans l'admin

- itou/www/search/forms.py
- tests/www/search/tests.py
https://itou.sentry.io/issues/5529729309/?alert_rule_id=10681385&alert_type=issue&notification_uuid=78926d62-1cb3-46e2-8442-cedec75c3f08&project=6164438&referrer=slack
> Recherche employeur: Correction d’un bug lors de la recherche de département adjacent

- config/settings/base.py
- config/settings/dev.py
- config/settings/test.py
- itou/files/management/commands/configure_bucket.py
- itou/utils/enums.py
Éviter les typos and lister les environnements disponibles.
> Utiliser une enum.StrEnum pour les ItouEnvironment

- itou/companies/management/commands/_import_siae/convention.py
Le nombre de SIAE à déconventionner est quasiment le même depuis plusieurs semaines/mois, mais cette année nous dépassons encore le seuil enregistré (beaucoup d'antennes requalifié ou de nouvelle structures pour l'intégration de la DNS dans l'Extranet ASP) et gardons donc conventionné des structures qui n'ont plus lieu de l'être.
```
$ SELECT extract('month' from created_at AT time zone 'Europe/Paris'), COUNT(*) FROM companies_siaefinancialannex GROUP BY 1 ORDER BY 1;
extract | count 
---------+-------
1 | 15857
2 |  3823
3 |  4055
4 |  5685
5 |  2525
6 |  3272
7 |  1992
8 |  1015
9 |  1012
10 | 11229
11 |  4443
12 |  1579
$ SELECT extract('month' from end_at AT time zone 'Europe/Paris'), COUNT(*) FROM companies_siaefinancialannex GROUP BY 1 ORDER BY 1;
extract | count 
---------+------- …
```
> Import IAE : Limiter la période de grâce pour le déconventionnement au premier semestre

- .github/workflows/review-app-creation.yml
- .github/workflows/review-app-removal.yml
Afin d'aider à diagnostiquer des déploiements très lent.
> github: ajout de la version de la CLI Clever

- itou/templates/apply/list_prescriptions.html
> Candidature: ajout d'une enquête Tally auprès des prescripteurs habilités sur l'expérience candidat [GEN-1681]

- itou/fixtures/django/28_implementation_assessment_campaigns.json
- itou/fixtures/django/29_implementation_assessment.json
- itou/fixtures/django/dumpdata.sh
Afin de faciliter la recette et faciliter l'accès aux vues du bilan.
> GEIQ: ajout de fixture pour les bilans d'exécution

- config/settings/base.py
- itou/templates/includes/demo_accounts.html
- itou/templates/layout/base.html
- itou/utils/enums.py
Éviter que les hackers n’aillent trifouiller dans la démo (ou la prod).
> Sécurité : Créer un environnement pour le programme de bug bounty

- itou/utils/templatetags/redirection_fields.py
- tests/utils/tests.py
https://yeswehack.com/vulnerability-center/reports/239415
> Sécurité : Empêcher une injection HTML (et éventuellement XSS) sur la page de login

- itou/api/admin.py
- itou/api/migrations/0002_alter_companyapitoken_companies_companytoken.py
- itou/api/models.py
Afficher le champs `key` en lecture seule dans l'admin.
> API: amélioration de l'admin des jetons d'entreprise

- itou/metabase/management/commands/populate_metabase_emplois.py
- tests/metabase/management/test_populate_metabase_emplois.py
Il ne faut pas comptabiliser les comptes inactifs
> Statistiques: Correction de l'export des comptes de collaborateurs

- itou/templates/admin/job_applications/change_form.html
- tests/job_applications/__snapshots__/test_admin.ambr
- tests/job_applications/test_admin.py
> Admin: Correction de permissions

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
> Pilotage : Ajout d’une bannière d’inscription pour tester le nouveau tableau de bord données ETP maille structure [GEN-1834]

- itou/templates/apply/submit_step_pending_authorization.html
- itou/templates/status/index.html
- tests/www/apply/test_submit.py
> UX/UI : remplacer Status par Statut

- itou/templates/dashboard/includes/employer_prescription_card.html
mise en cohérence de l'aspect (placement et couleur du badge "nouveau" dans la carte "Orientation" sur le Tableau de bord des Employeurs) par rapport aux règles du design system
> _Respecter les règles du design system._
> _Le badge "nouveau" passe en violet et à droite._
> _Aller sur le tableau de bord avec le profil d'une structure._
> UX/UI : Mise en cohérence de l'aspect de la carte "Orientation" sur le Tableau de bord des Employeurs

- config/settings/dev.py
> Autoriser Matomo dans l’environnement de dev

- itou/metabase/db.py
Parce que j'ai oublié de tester en dehors des tests et du mock....
> Statistiques: Correction de la connexion à la base de donnée

- itou/geiq/migrations/0001_initial.py
- itou/geiq/models.py
To avoid warning:
geiq.ImplementationAssessment.activity_report_file: (fields.W342)
Setting unique=True on a ForeignKey has the same effect as using a
OneToOneField.
HINT: ForeignKey(unique=True) is usually better served by a
OneToOneField.
> GEIQ: utilisation d'un OneToOneField pour éviter un warning

- itou/common_apps/address/departments.py
> Ajouter les départements 984 et 989 aux TOM

- itou/templates/apply/includes/job_seeker_info.html
- tests/www/apply/test_process.py
> Employeur: toujours afficher le nom de famille du candidat en majuscule [GEN-1786]

- .github/workflows/require-labels.yml
- scripts/mkchangelog
Certains changements techniques méritent d'y apparaître.
> Journal des changements: ajouter une section Tech [GEN-1706]

- tests/job_applications/tests.py
La date change finalement assez souvent.
> tests: correction test instable

- itou/templates/dashboard/includes/job_seeker_approval_card.html
- tests/www/dashboard/test_dashboard.py
Pour y voir un peu plus clair.
> tests: suppression de deux variables inconnues

- itou/templates/gps/my_groups.html
Car l'alerte est bleue
> icon-info
> UX/UI : changer la couleur de l'icone en bleu

- README.md
- docs/developing.md
Pour avoir une guide d'installation avec les étapes exhaustives
> Doc (README): infos sur l'activation de venv

- itou/users/admin.py
- itou/utils/admin.py
Déjà utilisé par le transfert de données d'un candidat à l'autre et bientôt d'une entreprise à l'autre.
> Admin: facilite l'ajout automatique de remarque de support

- itou/gps/management/commands/init_follow_up_groups.py
- itou/gps/management/commands/update_follow_up_groups_member_created_at.py
- tests/gps/test_management_commands.py
Améliorer les données affichées aux utilisateurs de GPS
> GPS: Corriger les dates de création des groupes de suivi créés par script

- itou/templates/dashboard/includes/stats.html
> Changement du titre d'un TB 

- itou/www/apply/views/submit_views.py
> fix(apply/submit_views.py): TypeError on functional views

- itou/templates/dashboard/includes/stats.html
- tests/www/dashboard/test_dashboard.py
Remplace #4362 pour éviter de merger des commits de merge
> Statistiques: Mise à jour des noms sur le tableau de bord

- itou/templates/includes/copy_to_clipboard.html
- tests/utils/test_redirect_legacy_views.py
- tests/utils/tests.py
- tests/www/approvals_views/test_prolongation_requests.py
- tests/www/companies_views/test_card_views.py
- tests/www/companies_views/test_job_description_views.py
- tests/www/dashboard/test_api_token.py
- tests/www/dashboard/test_switch_organization.py
- tests/www/invitations_views/test_company_send.py
Un template de moins qui pose problème :)
> tests: suppression d'une variable inconnue

- itou/templates/apply/list_prescriptions.html
> Avoir des retours sur le future espace Mes candidats
> UX/UI : Ajout d'une alerte Maze

- itou/gps/admin.py
- itou/templates/gps/includes/memberships_results.html
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
Et amélioration de l'admin des groups
> GPS: Affichage de la date des objets créés par script

- itou/utils/apis/metabase.py
Ajout des pop up tally sur les TBs privés du pilotage
> Ajout des pop up tally sur les TBs privés du pilotage

- itou/templates/apply/includes/buttons/archive.html
- itou/templates/apply/process_base.html
- itou/templates/apply/process_details.html
- itou/templates/apply/process_details_company.html
- itou/templates/approvals/includes/status.html
- itou/utils/staticfiles.py
- tests/www/approvals_views/__snapshots__/test_includes.ambr
Rendre plus lisible les [informations de la fiche candidature](https://www.notion.so/plateforme-inclusion/e492120b7a004d2fbbca237999948a3c?v=743c7a3a82a848149d1f7632dcb19575&p=087d18b5490646a48d87170c81b0356d&pm=c)
Ajout d'onglets
Adaptation des largeurs de colonnes
Modification de l'affichage de la box "Etat du Pass IAE"
Mise a jour du thème pour [corriger l'affichage des `<blockquote>`](https://www.notion.so/plateforme-inclusion/Composant-d-aper-u-d-un-message-4d3b8564c50f48688a6a70c12247f590?pvs=4)
**Avant**
**Apres**
> Candidature: ajout d'onglets dans les fiches candidature

- itou/gps/admin.py
> GPS: Ajouter un filtre par département dans l’admin [GEN-1851]

- itou/gps/admin.py
> GPS: Ajouter le département des bénéficiaires dans l’admin [GEN-1850]

- clevercloud/crons/populate_metabase_emplois.sh
- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/metabase/tables/gps.py
- tests/metabase/management/test_populate_metabase_emplois.py
Pour permettre à Louis-Jean de ne pas faire des tonnes de stats à la main depuis l'admin
> Statistiques: Ajout des données des groupes de suivi

- itou/approvals/models.py
- tests/approvals/tests.py
- tests/www/approvals_views/__snapshots__/test_includes.ambr
- tests/www/approvals_views/test_list.py
Autant utiliser la fonction de django qui le fait mieux :)
> PASS IAE: Amélioration de l'affichage de temps restant

- itou/www/autocomplete/views.py
- tests/www/autocomplete/tests.py
Suite de #3542, #3315, #3288 & #3223
> Autocompletion: suppression de code déprécié

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
Les webinaires sont finis donc les bannières ne sont plus affichées.
> Pilotage : Suppression des bannières pour les webinaires du mois de juin

- itou/templates/apply/list_prescriptions.html
Assez de résultats, on peut la retirer
> UX/UI : Retirer l'alerte du test Maze sur la liste des candidatures côté prescripteur

- tests/api/applicants_api/tests.py
- tests/api/data_inclusion_api/tests.py
- tests/api/employee_record_api/test_throttling.py
- tests/api/employee_record_api/tests.py
- tests/api/test_c4_api.py
- tests/approvals/test_notify_pole_emploi.py
- tests/common_apps/address/tests.py
- tests/companies/test_models.py
- tests/conftest.py
- tests/www/institutions_views/test_views.py
- tests/www/invitations_views/test_company_send.py
- tests/www/prescribers_views/test_admins.py
- tests/www/prescribers_views/test_edit.py
- tests/www/prescribers_views/test_members.py
- tests/www/releases/tests.py
- tests/www/search/tests.py
- tests/www/siae_evaluations_views/test_forms.py
- tests/www/siae_evaluations_views/test_institutions_views.py
- tests/www/siae_evaluations_views/test_siaes_views.py
- tests/www/signup/__snapshots__/test_job_seeker.ambr
- tests/www/signup/test_allauth.py
- tests/www/signup/test_job_seeker.py
- tests/www/signup/test_password.py
- tests/www/stats/test_views.py
- tests/www/welcoming_tour/tests.py
> Tests: Migration de certains tests à pytest

- tests/job_applications/tests.py
Le test pose problème pour #4342.
> Améliorer test_auto_prescription_xlsx_export

- .gitignore
- itou/metabase/tables/utils.py
- itou/www/approvals_views/forms.py
- itou/www/companies_views/urls.py
- itou/www/companies_views/views.py
- itou/www/invitations_views/urls.py
- itou/www/search/forms.py
- tests/users/test_models.py
- tests/www/approvals_views/test_display.py
Petite passe de nettoyage sur les FIXMEs et TODOs du projet.
Attention @devc1 : je retire le .envrc.local de .gitignore 
**Pouvez-vous tous confirmer que vous n'avez plus de branche qui traine qui date d'avant le 28 mai ?**
[Ce commit](https://github.com/gip-inclusion/les-emplois/commit/57a0776b236021ee8d28daeb65234684e6db37ef)
> Nettoyages divers

- itou/templates/layout/_footer.html
> UX/UI: Mise a jour des liens nos reseaux sociaux

- itou/templates/apply/process_external_transfer_resume.html
- itou/templates/companies/card.html
- itou/templates/companies/includes/_card_siae.html
- itou/templates/companies/job_description_card.html
> Ajout de tracking matomo pour le tranfert de candidatures

- itou/www/apply/views/process_views.py
> Candidature : ajout d'un select_related à la requête d'acceptation

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
Les commits 26da4533d et 4e2abfb7d ne se revertais pas proprement et vu que j'ai l'impression que les deux sont ensembles à chaque fois j'ai tout groupé :).
> Tableau de bord : Retirer les bannières mobil'emploi [GEN-1789]

- itou/eligibility/admin.py
> Admin: Correction de la page des critères d'éligibilité et des diagnostics suite à l'ajout de la certification

- itou/templates/search/includes/siaes_search_filters_departments.html
Parcque c'était moche
**Avant**
**Apres**
> UX/UI: Correction de l'affichage responsif des filtres départements et arrondissements

- itou/companies/management/commands/move_company_data.py
- tests/companies/test_management_commands.py
Ajouter une vérification automatique à la vérification manuelle effectuée par le support.
> Empêcher de déplacer les données d’entreprise s’il y a un contrôle a posteriori

- itou/www/apply/views/submit_views.py
> Candidature: Ne pas charger le diagnostic dans le contexte s'il n'est pas utilisé 

- itou/openid_connect/inclusion_connect/views.py
- tests/openid_connect/inclusion_connect/tests.py
Pour permettre de se connecter même quand le code safir n'est pas renseigné chez nous.
Si un utilisateur France Travail se connecte et qu'on ne reçoit pas de code safir et qu'il n'est pas rattaché à une organisation, on le déconnecte avec un message d'erreur
Si un utilisateur France Travail se connecte et qu'on reçoit un code safir inconnu de la plateforme :
S'il n'est pas rattaché à une organisation on le déconnecte avec un message d'erreur
S'il appartient déjà à un organisation, on le laisse de connecter avec toutefois un message d'alerte au cas où
> _Les instructions pour reproduire le problème, …
> Connexion: modifier les règles de connexion pour les agents FranceTravail

- itou/utils/apis/pole_emploi.py
- tests/utils/apis/test_pole_emploi_api.py
permet de facilement accéder aux informations d'une agence à partir de son code safir.
> API: Ajout de l'accès à l'api agences de FranceTravail

- itou/templates/apply/includes/job_application_sender_info.html
- itou/templates/apply/includes/job_seeker_info.html
- itou/templates/approvals/includes/list_card.html
- itou/templates/companies/includes/_company_info.html
- itou/templates/employee_record/includes/list_item.html
- itou/templates/includes/email_li.html
- itou/templates/includes/phone_li.html
- tests/www/companies_views/__snapshots__/test_card_views.ambr
- tests/www/geiq_views/__snapshots__/tests.ambr
> templates: utilisation généralisé de l'include copy_to_clipboard.html

- itou/job_applications/admin_forms.py
- itou/templates/apply/includes/job_application_sender_info.html
- tests/job_applications/test_admin.py
- tests/job_applications/tests.py
Parce qu'il s'écrit comme cela.
https://www.notion.so/plateforme-inclusion/Ajouter-un-accent-sur-une-majuscule-3ede3ceccf994bb0905792b803b65920?pvs=4
> Ajout d'un accent au mot Émetteur

- itou/asp/forms.py
- itou/static/js/utils.js
- itou/www/apply/forms.py
- itou/www/employee_record_views/forms.py
- tests/www/apply/test_forms.py
Reverts gip-inclusion/les-emplois#4537
https://itou-inclusion.slack.com/archives/C01181Y04LT/p1723653774979019
> Revert "Candidature et fiche salarié : activation du champ « Commune de naissance » si le pays de naissance est la France"

- scripts/create-fast-machine.sh
Pour être cohérent avec le reste de l'infra, et surtout la PROD.
> Créer les FAST MACHINE avec la bonne version de python

- tests/www/approvals_views/test_detail.py
Mieux correspondre à la réalité.
> tests: MàJ commentaires du assertNumQueries de test_approval_status_includes

- itou/users/models.py
- tests/www/apply/test_process.py
- tests/www/approvals_views/test_detail.py
> Retirer une requête de Approval.latest_approval

- itou/job_applications/utils.py
- itou/templates/layout/base.html
- itou/users/models.py
- tests/utils/__snapshots__/tests.ambr
- tests/utils/tests.py
Permettre au métier de mieux suivre les expérimentations limitées à un territoire.
> Statistiques : Suivi du département de l’utilisateur avec ses actions [GEN-1848]

- itou/templates/apply/includes/list_counter.html
- itou/templates/approvals/includes/list_counter.html
- itou/templates/employee_record/includes/list_counter.html
- itou/templates/search/includes/prescribers_search_summary.html
- itou/templates/search/includes/siaes_search_top.html
- tests/www/apply/test_process_external_transfer.py
Harmonisation de l'interface
Templating
> UX/UI : Harmonisation des “x résultats” au dessus d’une liste de résultats

- itou/templates/dashboard/edit_user_info.html
- tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
Modifier mon profil : 
- Passer le btn “Modifier ces infos” en taille normale 
- Correction du html en passant
> UX/UI: Taille bouton "Modifier ces infos"

- itou/templates/apply/includes/accept_section.html
- itou/templates/apply/includes/job_application_accept_form.html
- itou/www/apply/views/common.py
> Candidature: correction d'affichage dans des cas rares

- itou/users/adapter.py
Plus joli !
1. Se connecter
2. Se déconnecter
> UX/UI : Affichage des messages de succès liés à l’authentification en toast [GEN-1916]

- itou/institutions/enums.py
- itou/institutions/migrations/0007_convergence_institution.py
- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/dashboard/views.py
- itou/www/stats/urls.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
[[Convergence] Permettre les accès aux TBs privés CVG](https://www.notion.so/gip-inclusion/Convergence-Permettre-les-acc-s-aux-TBs-priv-s-CVG-c69faef8a36f45d6ae940a62ce0582be?pvs=4)
Lors de la réflexion initiale on pensais utiliser le type "Autre" mais c'est plus simple d'avoir un type "Convergence" car ça évite d'avoir à mettre en place un _settings_ avec l'ID de l'institution en dur.
1. S'ajouter à l'institution
2. Sélectionner l'institution "Convergence France" dans le menu des structures
---
cc @dejafait
> Pilotage : Création de l'institution "Convergence France" et ouverture des TB446 et TB469 pour celle-ci

- itou/users/models.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
La DB sait très bien faire cela.
> Demandeur d’emploi: tri des agréments en DB

- tests/metabase/management/test_populate_metabase_emplois.py
> tests: Retirer des assertions dupliquées de test_populate_metabase_emplois

- tests/users/factories.py
> tests: correction de JobSeekerFactory

- tests/api/__snapshots__/test_geiq.ambr
- tests/api/test_geiq.py
- tests/asp/test_models.py
- tests/common_apps/address/test_qpv_zrr_fields.py
- tests/employee_record/__snapshots__/test_serializers.ambr
- tests/gps/test_create_beneficiary.py
- tests/gps/test_views.py
- tests/job_applications/factories.py
- tests/scripts/test_users_geolocation.py
- tests/users/factories.py
- tests/users/test_management_commands.py
- tests/users/test_models.py
- tests/utils/test_immersion_facile.py
- tests/utils/tests.py
- tests/www/apply/test_forms.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_templates.py
- tests/www/dashboard/test_dashboard.py
- tests/www/dashboard/test_edit_user_info.py
- tests/www/employee_record_views/test_create.py
- tests/www/signup/test_password.py
> tests: fusion de JobSeekerWithAddressFactory dans JobSeekerFactory

- itou/templates/dashboard/includes/prescriber_job_seekers_card.html
- itou/templates/job_seekers_views/includes/list_counter.html
- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/job_seekers_views/list.html
- itou/utils/templatetags/nav.py
- itou/www/job_seekers_views/forms.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/job_applications/factories.py
- tests/www/dashboard/test_dashboard.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
> Prescripteur: ajout de la liste des candidats [GEN-1806]

- README.md
- docs/developing.md
Accéder à la console d'administration de Django en local, sans avoir à cracker un mot de passe (facilement crackable, certes…)
> Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés. Attirez l'attention sur les décisions d'architecture ou de conception importantes.
> Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette jetable, mettre l'URL pour tester dans cette partie.
> doc: mentionner les identifiants du superutilisateur local

- itou/prescribers/management/commands/sync_ft_organizations.py
Le Siret ne nous sert foncièrement à rien pour les orga PE, je pense que j'avais mis ce filtre sinon ça cassais lors de la diff mais on peux contourner donc faisons ça : 17 nouvelles structures vont être créées, 2 vont avoir leur nom de modifié.
> Prescripteur : Amélioration pour la synchro des organisations FT

- itou/users/admin_forms.py
On est maintenant en Django 5.0 et il n'y a donc plus de `RemovedInDjango50Warning` à éviter :)
> Tech: suppression de code maintenant inutile

- itou/templates/approvals/includes/job_applications.html
Pour éviter de perdre une partie des événements
> Statistiques: Correction d'un nom d'événement Matomo [GEN-1630]

- itou/approvals/models.py
- itou/www/approvals_views/views.py
- tests/www/approvals_views/__snapshots__/test_detail.ambr
Pour que les choses soient plus claires et un poil plus rapides.
> Tech: simplifications & optimisation de la page détail salarié/PASS IAE

- tests/job_applications/tests.py
> Simplifier un parametrize dans tests.job_applications

- itou/templates/dashboard/edit_user_notifications.html
- itou/www/dashboard/views.py
C'est tellement plus sympa quoi.
(+ petite maj UI en passant)
> UX/UI: Toast à la d'Alert lorsque j’enregistre mes préférences de notifications

- itou/employee_record/models.py
> Mettre en CasseDeChameau JobApplication de la ForeignKey du modèle EmployeeRecord

- itou/utils/templatetags/nav.py
- tests/www/test_error.py
La navigation (template tag `nav`) fait partie de tous les gabarits, y compris `500.html`. Lorsqu’une erreur se produit lors du rendu de la `nav`, elle ne devrait pas _bubble up_. Autrement:
1. le gestionnaire de 500 l’attrape
2. commence le rendu du gabarit pour les 500
3. qui appelle nav
4. qui a une erreur
5. `goto 1`
> Capturer les exceptions lors du rendu du template tag nav

- itou/job_applications/models.py
- tests/job_applications/tests.py
https://itou.sentry.io/issues/5836047871/
> Candidatures : Désarchiver lors de l’acceptation

- itou/www/employees_views/views.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/employees_views/test_detail.py
> Profil salarié: affichage du dernier PASS

- Makefile
> Retirer la variable inutilisée VENV_REQUIREMENT du Makefile

- itou/utils/staticfiles.py
Pour corriger le probleme de `position:sticky` sur la `.s-title-02` en mobile
https://itou-inclusion.slack.com/archives/CQ6C3LSAH/p1726514003040989
> UX/UI: mise a jour du theme vers v2.1.9

- itou/www/apply/forms.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_process.py
https://itou.sentry.io/issues/5669190919/?project=6164438
> Performances: réduire le nombre de requête sur le formulaire d'acceptation

- itou/job_applications/migrations/0011_drop_hidden_for_company.py
Uniquement le deuxième commit.
> Supprimer la colonne `JobApplication.hidden_for_company`

- itou/job_applications/admin.py
> admin: ajout du champ "archivé le" dans le détail des candidatures

- itou/prescribers/admin.py
- tests/prescribers/tests.py
https://itou-inclusion.slack.com/archives/C01181Y04LT/p1727080350858439
> Admin: Correction du refus d'habilitations

- itou/templates/dashboard/includes/dashboard_title_content.html
Pour renseigner cette zone de titre pour tous les types d'utilisateurs
Modification des conditions dans le template
⚠️ Les conditions peuvent surement être améliorées. J'ai besoin de vous
> UX/UI: Corriger le titre du dashboard pour les "Candidat" et les "Orienteur seul"

- itou/templates/layout/_header_authenticated.html
- tests/www/__snapshots__/test_layout.ambr
En tablette, présent dans la barre du header et dans le menu offcanvas
> UX/UI: Redondance du menu “mon espace”

- tests/www/approvals_views/test_detail.py
pytest ne les trouvait pas. Maintenant oui, avec un petit correctif pour que le test passe.
> tests: correction de test non lancés

- itou/templates/institutions/members.html
- itou/templates/prescribers/members.html
Parcque les template members des "instititiuons" et des "prescribers" ne sont pas a jour
**Avant**
**Apres**
> UX/UI: Harmoniser l'UI des pages “collaborateurs”

- itou/www/stats/views.py
- tests/www/stats/test_views.py
[LES-EMPLOIS-PROD-1ZN](https://itou.sentry.io/issues/5899622425/)
> Pilotage : Éviter une erreur sentry

- config/settings/base.py
- itou/templates/dashboard/includes/stats.html
- itou/www/dashboard/views.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_views.py
https://www.notion.so/gip-inclusion/Ouvrir-le-TB-440-toutes-les-SIAE-1085f321b6048027ba7efe6cc606aadc?pvs=4
> Pilotage : Ouvrir le TB 440 à toutes les SIAE

- itou/templates/apply/process_postpone.html
Mesurer la mise en attente des candidatures
> Statistiques: Amélioration des mesures de conversion des actions sur les candidatures

- itou/communications/cache.py
- tests/communications/test_cache.py
Sinon, il ne marche pas le dernier jour du mois :) 
> Performances: Correction de la durée de cache des campagnes de nouveautés

- itou/templates/apply/list_for_siae.html
- itou/www/apply/views/list_views.py
- tests/www/apply/test_list_for_siae.py
> Employeur: Les EA, EATT, OCPS ne peuvent pas candidater GEN-2118

- itou/templates/apply/includes/siae_hiring_actions.html
- itou/templates/companies/card.html
- itou/templates/companies/job_description_card.html
- itou/utils/staticfiles.py
- tests/www/companies_views/__snapshots__/test_card_views.ambr
Pour les rendre plus grands sur mobile
**Avant**
**Apres**
> UX/UI: Modifier les positionnement responsifs des boutons de la .c-box--action

- config/settings/base.py
- itou/templates/dashboard/includes/stats.html
- itou/www/dashboard/views.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_views.py
This reverts commit b97cf203bd5cae509ca02257d8127577661a0a08 (#4823).
> Retour arriére : Pilotage : Ouvrir le TB 440 à toutes les SIAE

- itou/utils/admin.py
- tests/job_applications/test_admin.py
Quand on modifie certains objets dans l'admin, il est assez simple d'oublier de modifier les objets liés et ainsi de créer des incohérences.
Je n'ai pas mis de règle bloquante pour autoriser des incohérences temporaires (quand on change le compte candidat d'une candidature puis de son PASS puis de son diag, etc).
> Admin: vérification automatique de certaines règles de cohérence

- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/test_details.py
Pour économiser notre pauvre base de données.
> Performances: réduction du nombre de requête sur la page de détail d'un candidat

- itou/approvals/models.py
- itou/templates/approvals/includes/box.html
- tests/approvals/tests.py
- tests/www/approvals_views/__snapshots__/test_suspend.ambr
Pour prendre soin de notre base de données.
> Performance: réduction du nombre de requête nécessaire pour l'encart PASS IAE en cas de suspension active

- .github/workflows/review-app-creation.yml
Cf https://github.com/gip-inclusion/les-emplois/pull/4836#issuecomment-2382361817
Dans certains cas, les variables d'env `POSTGRESQL_ADDON_DIRECT_HOST/PORT` ne sont pas définies avant que l'application ne démarre ce qui cause logiquement des soucis :boom: 
> Tech: fiabiliser la création de recette jetable

- tests/approvals/factories.py
- tests/metabase/management/test_populate_metabase_emplois.py
Pour facilement avoir des demandes de prolongation cohérentes avec leur prolongation.
> tests: amélioration de `ProlongationFactory`

- itou/templates/account/login_generic.html
Only display it when we use ProConnect
> pro_connect: hide migation banner until the real switch

- itou/templates/dashboard/dashboard.html
> Tableau de bord: Suppression du bandeau GPS GEN-2146

- itou/templates/apply/list_for_siae.html
> Enlever le bandeau “Nouveauté” concernant l’archivage des Candidatures sur la page des candidatures GEN-2153

- itou/templates/employee_record/includes/list_item.html
- tests/www/employee_record_views/__snapshots__/test_list.ambr
> UX/UI: Correction du positionnement du bouton “Régulariser le n° de sécurité sociale”

- itou/utils/staticfiles.py
Un état :hover visible comme sur les autres boutons
**Avant**
**Apres**
> UX/UI: Ajouter un hover au choix de structure

- itou/templates/apply/process_base.html
- itou/templates/apply/process_details.html
- itou/templates/apply/process_details_company.html
- itou/templates/apply/submit/check_job_seeker_info_for_hire.html
- itou/templates/apply/submit/eligibility_for_hire.html
- itou/templates/job_seekers_views/details.html
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
Dans la sidebar des pages detail de candidatures
> UX/UI: N'afficher les infos PASS que dans l'onglet "Informations générales"

- itou/static/js/formset_add_remove_row.js
Ils s’étaient cachés pour 646cb97c31f6fa245cb97d6b3bbe181e8ac39f25.
> UX/UI : Passage de quelques font-weight-* à fw-*

- itou/companies/management/commands/import_ea_eatt.py
- tests/companies/test_import_ea_eatt.py
[LES-EMPLOIS-PROD-20V](https://itou.sentry.io/issues/5990445068/)
> Employeur : Correction de l'import EA/EATT quand d'autres fichiers sont présents

- itou/templates/apply/email/diagoriente_prescriber_invite_body.txt
- itou/templates/apply/includes/job_seeker_info.html
- itou/templates/users/details.html
- tests/gps/__snapshots__/test_views.ambr
> Candidature: normalisation de l'affichage des noms et prénoms

- itou/templates/apply/includes/job_application_prior_action.html
- itou/templates/apply/process_details.html
- itou/templates/apply/process_details_company.html
- itou/www/apply/views/process_views.py
- tests/www/apply/test_process.py
Pour détecter plus d'erreurs et clarifier l'utilisation de nos includes.
> tests: suppression de quelques `ignore_unknown_variable_template_error`

- itou/templates/apply/submit/hire_confirmation.html
- tests/www/apply/__snapshots__/test_submit.ambr
> Candidature: correction de l'affichage du diagnostic dans le parcours d'embauche

- itou/templates/includes/members.html
> UX/UI: Modifier l’icone “sens interdit” dans la liste des collaborateurs

- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/employees_views/views.py
Cf https://github.com/gip-inclusion/les-emplois/actions/runs/11399407439/job/31718136905
On a parfois des:
`FAILED tests/www/apply/test_process.py::test_details_for_prescriber_not_can_have_prior_actions - Failed: Undefined template variable 'expired_eligibility_diagnosis' in '/home/runner/work/les-emplois/les-emplois/itou/templates/apply/includes/eligibility_diagnosis.html'`
> tests: correction de test instable

- itou/templates/apply/list_for_siae.html
> UX/UI: Ajout d'un sondage Maze sur la page des candidatures [GEN-2162]

- itou/templates/stats/stats.html
- itou/www/stats/views.py
:link: https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-pour-annoncer-les-prochains-webinaire-q-r-e3c533e706c04d97a83106c0767d3796?pvs=4
> Pilotage : Ajouter un encart pour annoncer les prochains webinaire Q/R 

- itou/eligibility/models/common.py
- itou/utils/apis/api_particulier.py
- tests/eligibility/test_iae.py
- tests/utils/apis/test_api_particulier.py
- tests/www/apply/test_process.py
- tests/www/apply/test_templates.py
Gestion des resources, moins tabasser l’API particulier.
> API particulier : Améliorer la gestion du client httpx

- itou/www/apply/forms.py
Deux mots collés dans un message d'erreur.
J'ai cherché d'autres coquilles du même style et je n'en ai pas trouvé, donc voilà une toute petite PR !
> Correction d'un message d'erreur

- tests/eligibility/test_iae.py
> tests: découper test_selected_administrative_criteria_certified

- itou/templates/dashboard/edit_user_info.html
- tests/www/dashboard/test_edit_user_info.py
> Amélioration de la page d'édition des informations personelles pour les comptes ProConnectés

- itou/templates/dashboard/edit_user_info.html
> template: Fix typo

- itou/www/login/forms.py
- tests/openid_connect/inclusion_connect/tests.py
- tests/www/login/tests.py
Même si c'est un compte IC, il faut utiliser ProConnect à présent
> Connexion: Correction du message d'erreur pour les comptes Inclusion Connect

- itou/www/companies_views/views.py
- itou/www/prescribers_views/views.py
> UX/UI: Remplacer message de confirmation de maj de la fiche structure par un toast

- itou/templates/apply/list_for_siae.html
> UX/UI : Retrait de la banière d’expérimentation Maze sur la page des candidatures [GEN-2213]

- itou/companies/migrations/0012_fix_ft_company.py
- itou/companies/models.py
https://itou-inclusion.slack.com/archives/C0412CTV63D/p1729779953766069?thread_ts=1729524947.114339&cid=C0412CTV63D
> Employeur : Correction pour l'entreprise utilisée pour les offres PEC

- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
Sinon le déploiement ne se fait pas.
> requirements: add required setuptools

- itou/templates/logout/warning.html
- tests/logout/__snapshots__/tests.ambr
Voir https://itou-inclusion.slack.com/archives/C0803LNV93N/p1731076335000189?thread_ts=1731057024.666129&cid=C0803LNV93N
> UX/UI: Améliorer les messages de déconnexion

- itou/templates/static/legal/privacy.html
Modification de l'adresse mail contact pour demandes RGPD
> Vie privée: modification de l'adresse mail contact pour demandes RGPD

- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- itou/metabase/management/commands/populate_metabase_matomo.py
- itou/status/management/commands/run_status_probes.py
Plus avantageux que d'avoir la configuration uniquement dans l'interface de Sentry.
> sentry : Configuration des moniteurs Cron depuis le code

- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
J'ai lu trop vite la PR #5105 et elle fait du caca... :see_no_evil:
> requirement: Fix bump setuptools from 75.4.0 to 75.5.0

- itou/www/itou_staff_views/merge_utils.py
- tests/www/itou_staff_views/tests.py
> Admin: Corriger le log de fusion de compte dans l'admin 

- itou/eligibility/tasks.py
https://itou.sentry.io/issues/6051443115/?project=6164438
> Envelopper async_certify_criteria dans une transaction

- itou/templates/companies/select_financial_annex.html
- itou/templates/utils/templatetags/buttons_form.html
- itou/www/companies_views/views.py
- tests/utils/__snapshots__/test_templatetags.ambr
- tests/www/approvals_views/__snapshots__/test_suspend.ambr
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_create.ambr
Demande UX.
1. `psql -c "UPDATE companies_company SET source='USER_CREATED';"`
2. Se connecter en tant que l’AI
3. Structure -> Annexes financières
4. Sélectionner une annexe financière
> UX/UI : Amélioration de la navigation pour la gestion des annexes financières [GEN-2191]

- itou/templates/apply/includes/eligibility_badge.html
- itou/templates/apply/includes/list_card_body_company.html
- itou/templates/job_seekers_views/includes/eligibility_diagnosis.html
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_list_for_siae.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
Pour être cohérent avec le thème ? Et surtout pour le sortir de #5089 qui fait déjà pas mal de choses.
> Candidature: correction de la couleur du badge dans le cas de l'Éligibilité IAE à valider

- itou/templates/apply/includes/eligibility_badge.html
- itou/templates/apply/includes/list_card_body_company.html
- itou/templates/apply/includes/out_of_band_changes_on_job_application_state_update_siae.html
- itou/templates/apply/process_accept.html
- itou/templates/apply/process_base.html
- itou/templates/apply/process_eligibility.html
- itou/templates/approvals/includes/box.html
- itou/templates/approvals/includes/job_description_creation.html
- itou/templates/approvals/includes/list_card.html
- itou/templates/job_seekers_views/includes/eligibility_diagnosis.html
- itou/utils/templatetags/badges.py
- tests/utils/__snapshots__/tests.ambr
- tests/utils/tests.py
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/approvals_views/__snapshots__/test_approval_box.ambr
- tests/www/approvals_views/__snapshots__/test_detail.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/approvals_views/test_list.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
Pour essayer de centraliser les règles concernant ces badges.
> Tech: ajout de nouveaux badges et renommage de `job_application_state_badge`

- itou/templates/layout/base.html
Changement de plan de la base de données.
https://itou-inclusion.slack.com/archives/C01AQKD7MAN/p1732719881605269
> Ajout d'une bannière temporaire pour avertir de l'indisponibilité

- itou/templates/layout/base.html
> Retrait de la bannière temporaire

- itou/templates/includes/copy_to_clipboard.html
- tests/gps/__snapshots__/test_views.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/companies_views/__snapshots__/test_card_views.ambr
- tests/www/geiq_views/__snapshots__/tests.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
La dimension de l'icone est trop grande et force l’interlignage
> UX/UI: ajustement de l'UI de copy to clipboard

- tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_list_for_job_seeker.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_prescriptions.py
Cela manquait alors que c'est une vue assez centrale.
> tests: ajout de nouveaux tests de snapshot pour la vue liste des candidatures

- itou/templates/gps/includes/memberships_results.html
- itou/templates/gps/join_group.html
- itou/templates/gps/my_groups.html
- tests/gps/__snapshots__/test_views.ambr
Pour respecter la "charte" des [boxs de résultats](https://zeroheight.com/85c89893b/p/96e94f-box/t/page-96e94f-87697839-995f63-24)
**Avant** 
**Apres**
> UX/UI: Ajustements des templates GPS

- itou/www/api/urls.py
- itou/www/api/views.py
Moins de code, moins de soucis.
> API: simplification de la vue index

- itou/templates/layout/_header_authenticated.html
- tests/www/__snapshots__/test_layout.ambr
> Ajouter un lien vers la politique de confidentialité pour les utilisateurs connectés

- tests/www/search/tests.py
https://github.com/gip-inclusion/les-emplois/actions/runs/12240395537/attempts/1
Reproductible avec `pytest --randomly-seed=1239674710 -v tests/www/search/tests.py::TestSearchCompany::test_is_searchable`
> Tech : Stabilitation du test bagottant `test_is_searchable()`

- itou/www/itou_staff_views/views.py
- itou/www/siae_evaluations_views/views.py
- tests/www/itou_staff_views/__snapshots__/tests.ambr
- tests/www/itou_staff_views/tests.py
- tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
Pour facilement voir qui est censé utilisé telle vue.
> Tech: utilisation du décorateur `check_user`

- itou/templates/dashboard/dashboard.html
Se connecter en tant que prescripteur habilité.
> UX/UI: Demande de retours prescripteurs habilités sur une refonte de leur espace [GEN-2297]

- itou/users/management/commands/new_users_to_brevo.py
- tests/users/test_management_commands.py
On utilise ProConnect à présent.
> Correction de l'envoi à brevo des listes d'utilisateur

- .editorconfig
https://github.com/gip-inclusion/les-emplois/pull/5210/files#r1881657052
> Définir la configuration de l’éditeur pour les JSON

- itou/www/gps/views.py
- tests/gps/test_views.py
https://inclusion.sentry.io/issues/14217816/?project=4508410589020240&query=is%3Aunresolved%20is%3Afor_review%20assigned_or_suggested%3A%5Bme%2C%20my_teams%2C%20none%5D&referrer=issue-stream&sort=inbox&statsPeriod=14d&stream_index=0
> GPS: correction de la page de détail des bénéficiaire pour les orienteurs sans organisation.

- itou/templates/apply/includes/selected_administrative_criteria_display.html
Pour traiter [un retour de Joffrey que j'avais omis](https://www.notion.so/plateforme-inclusion/class-du-badge-121e8fa5c35b80f0b6cbeba6d1d2f7d3?pvs=4).
> [Profil salarié] Diminution de la taille du badge Certifié 

- itou/templates/dashboard/includes/employer_geiq_card.html
- itou/templates/dashboard/includes/labor_inspector_geiq_assessment_card.html
- itou/templates/geiq/assessment_info_for_employer.html
- itou/templates/geiq/assessment_info_for_labor_inspector.html
- itou/templates/geiq/assessment_review.html
- itou/templates/geiq/geiq_list.html
- itou/templates/geiq/includes/labor_inspector_assessment_state_badge.html
- itou/templates/geiq/includes/labor_inspector_assessment_state_badge_for_list.html
- itou/templates/geiq/includes/last_synced_at.html
- itou/templates/geiq/list_base.html
- tests/www/geiq_views/__snapshots__/tests.ambr
- tests/www/geiq_views/tests.py
Corrections de plusieurs bugs d'interfaces et harmonisation avec le thème
https://www.notion.so/plateforme-inclusion/Corrections-UI-interface-GEIQ-157e8fa5c35b80768ec9da3531efd21c?pvs=4
> UX/UI: Corrections interface GEIQ

- tests/www/employee_record_views/test_create.py
Sinon les collègues me parlent avant 9h, et c'est bien trop tôt ! :sleepy: 
J'ai nettoyé un peu mais ce fichier gagnerais à être réécris car on y passe presque 30s et la majorité de ce temps doit être pour de l'initialisation qui ne va pas servir dans tout les cas de test.
> Tests : Correction du bagotement de `TestCreateEmployeeRecordStep4()`

- itou/www/apply/views/edit_views.py
- itou/www/apply/views/process_views.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_detail_rdv_insertion.py
- tests/www/apply/test_edit.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_list_rdv_insertion.py
- tests/www/apply/test_process.py
Pour rapidement voir qui utilise cette vue.
> Tech: ajout de décorateurs `check_user`

- itou/templates/apply/process_refuse.html
- itou/templates/apply/refusal_messages/non_eligible.txt
- itou/www/apply/views/process_views.py
> Tech: faciliter la réutilisation du template `apply/process_refuse.html`

- itou/templates/static/legal/terms.html
Pour appliquer la modification de https://github.com/gip-inclusion/les-emplois/pull/5323 sans attendre qu'on se soit décidé pour https://github.com/gip-inclusion/les-emplois/pull/5324.
> CGU : Changement de l'adresse de contact du DPO

- itou/users/migrations/0018_remove_jobseekerprofile_ata_allocation_since.py
- itou/users/migrations/0019_drop_jobseekerprofile_ata_allocation_since.py
Supprimer la colonne encore présente en BDD : https://github.com/gip-inclusion/les-emplois/pull/5312
> Tech : Suppression de la colonne du champ de l'aide ATA

- itou/templates/dashboard/dashboard.html
This reverts commit 3b8d1ae71d90ab32d1bc5bbd877e09648341a0eb.
> UX/UI: Fin de la demande de retours prescripteurs habilités sur une refonte de leur espace [GEN-2334]

- itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
> UX/UI: Retirer le texte d'aide du filtre archivé des candidatures [GEN-2028]

- itou/openid_connect/pe_connect/views.py
Sinon, ils ne comprennent pas car ils sont redirigés sur la page de connexion sans message
> Connexion; Ajout de plus de contexte d'erreur lors d'échec de connexion via France Travail pour les candidats

- itou/static/css/itou.css
- itou/templates/apply/includes/geiq/legislative_text_link.html
- itou/templates/apply/includes/geiq_eligibility_section.html
- itou/templates/apply/includes/siae_card.html
- itou/templates/apply/process_internal_transfer.html
- itou/templates/apply/submit/application/base.html
- itou/templates/apply/submit/application/end.html
- itou/templates/apply/submit/application/resume.html
- itou/templates/apply/submit/hire_confirmation.html
- itou/templates/apply/submit_base_two_columns.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_base.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
- tests/www/apply/test_submit.py
Les écrans de formulaires ne respectaient pas la "charte" du thème.
- incohérence de la largeur des colonnes entre écrans
- .c-form-conseil plus recommandé
- mauvais positionnement du badge dans la zone de titre
- etc
**Avant**
**Apres**
> UX/UI: corrections UI du parcours de "nouvelle candidature"

- itou/www/signup/forms.py
This reverts commit a3253372f2ea09f568a2f8bee54b018fc2cbf4f8.
> Inscription: Nettoyage suite au déploiement des champs lieu et pays de naissance candidat

- itou/templates/dashboard/dashboard.html
> Prescripteur: Mettre à jour le bandeau d’info des utilisateurs sans organisation [GEN-2366]

- itou/templates/gps/my_groups.html
- itou/www/gps/views.py
- tests/gps/test_views.py
Pour les orienteurs qui n'ont pas accès à la liste des candidats
https://www.notion.so/gip-inclusion/1375f321b604808caaf1f9927f9e4554?v=13c5f321b604802b8046000c4929c2d6&p=14b5f321b60480e29670d47e62d1ba7c&pm=s
> GPS: Ajout d'un bouton pour demander l'ajout d'un bénéficiaire

- itou/templates/users/includes/gps_group.html
- itou/www/gps/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
https://www.notion.so/gip-inclusion/Cr-er-le-flux-Ajouter-un-intervenant-existant-14b5f321b60480ecac08c4198b8ec905?pvs=4
> GPS: Créer le flux “Ajouter un intervenant existant”

- itou/gps/admin.py
https://inclusion.sentry.io/issues/17148832/?project=4508410589020240&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0
Je dois écrire des tests, mais je le ferais calmement plus tard, l'idée est de débloquer @louije rapidement.
> GPS: Corriger et améliorer le formulaire d'admin des participants

- itou/www/apply/views/submit_views.py
Suite à #5389, le code relatif à la création de bénéficiaires dans `apply.views.submit_views` peut être nettoyé.
> apply: nettoyage du code GPS de création de bénéficiaire

- tests/utils/htmx/test.py
- tests/utils/htmx/tests.py
Pour mes cas d'usage dans #5242
> tests: amélioration de l'utilitaire `update_page_with_htmx`

- tests/gps/test_admin.py
> GPS: Ajout de test sur l'admin

- CHANGELOG.md
- itou/approvals/admin_views.py
- tests/approvals/tests.py
> Corrections de "diagnostique" en "diagnostic"

- itou/utils/constants.py
> Retrait de la constante inutilisée ITOU_EMAIL_PROLONGATION

- itou/utils/perms/institution.py
- itou/utils/perms/prescriber.py
Par symétrie avec `get_current_company_or_404`.
> Tech: ajout d'annotations de type sur 2 fonctions

- itou/templates/pro_connect/includes/description.html
- itou/templates/signup/prescriber_user.html
https://www.notion.so/plateforme-inclusion/Corriger-une-phrase-dans-la-page-d-inscription-des-prescripteurs-et-employeurs-ajout-d-un-espace-185e8fa5c35b80c58275c684d8b97082?pvs=4
> Connexion: Petites améliorations de formulation et de mise en page

- itou/templates/gps/user_details.html
- tests/gps/__snapshots__/test_views.ambr
ce n'est pas vraiment utile, et c'est moyen niveau RGPD 
https://www.notion.so/Nettoyage-de-la-zone-informations-de-la-fiche-b-n-ficiaire-1815f321b6048036812ac08a53053614?d=1855f321b60480bab0c6001c067b2ebe&pvs=4#1855f321b604805d9fc0ffc4584bdf8c
> GPS: Ne plus afficher le NIR sur le détail des bénéficiaires

- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
Suite au découpage de la page en 2 sections, la seconde n'était plus dans le snapshot 
> GPS: Correction d'un test

- itou/templates/gps/includes/memberships_results.html
- tests/gps/__snapshots__/test_views.ambr
La notion de “suivi depuis le xxx” porte à confusion (en plus pour les relations créées “à la main”, on ne peut pas mettre une date précise). On préfère la remplacer pour le moment par la plus factuelle “membre du groupe depuis…”.
https://www.notion.so/gip-inclusion/Reformuler-la-formulation-suivi-depuis-1845f321b6048038a196eace92425be2?pvs=4
> GPS: Changement du nom d'une colonne

- itou/www/gps/views.py
- tests/gps/test_views.py
Par ordre de création du FollowUpGroupMembership
https://www.notion.so/gip-inclusion/Classement-des-intervenants-sur-la-fiche-1845f321b6048091a1a4dd499fbd1750?pvs=4
> GPS: Changement de l'ordre d'affichage des membres d'un groupe

- itou/approvals/management/commands/send_approvals_to_pe.py
- itou/utils/apis/pole_emploi.py
- tests/approvals/test_notify_pole_emploi.py
1er commit: faciliter l'accès à la réponse brute de l'API en cas de soucis
2nd commit: avoir de jolis logs (et profiter de #5459)
> PASS IAE: ajout de logs et facilitation du debug

- itou/eligibility/admin.py
- itou/eligibility/admin_form.py
- tests/eligibility/test_admin.py
Permettre de modifier un diagnistic quand l'auteur a quitté la structure/organisation (on veut pouvoir régulariser les vieux diagnostics)
Ne plus mettre à jour la date d'expiration d'un vieux diagnostic
-> correction des données une fois mergé : à partir du dump du 27/01, charger pk/expires_at de tous les diags iae et geiq, et mettre à jour en db si la valeur est différente. 
> Admin: Correction du formulaire des diagnostics d'éligibilité

- itou/status/management/commands/run_status_probes.py
- tests/status/tests.py
Cette commande est principalement lancée par cron et on souhaite donc avoir des jolis logs.
> Tech: utilisation de logs dans la commande `run_status_probes`

- itou/antivirus/management/commands/scan_s3_files.py
- itou/cities/management/commands/resolve_insee_cities.py
- itou/companies/management/commands/update_companies_job_app_score.py
- itou/emails/management/commands/delete_old_emails.py
- itou/users/management/commands/shorten_active_sessions.py
- tests/cities/__snapshots__/tests.ambr
- tests/cities/tests.py
- tests/companies/test_management_commands.py
- tests/emails/test_commands.py
Car elles sont principalement lancées par des crons.
> Tech: utilisation de logs dans plus de commandes

- itou/approvals/management/commands/send_approvals_to_pe.py
- itou/approvals/models.py
- tests/approvals/test_notify_pole_emploi.py
Pour être informé quand il y a des soucis.
> API: ajout de logs sur l'envoi des PASS IAE à France Travail

- itou/fixtures/django/20_eligibility_diagnoses.json
> Technique: Correction des données de fixtures de diagnostics d'éligibilité IAE suite à l'ajout de contrainte en base de donné

- clevercloud/cron.json
- itou/employee_record/management/commands/archive_employee_records.py
- itou/gps/management/commands/import_advisor_information.py
- itou/job_applications/management/commands/archive_job_applications.py
- itou/prescribers/management/commands/update_prescriber_organizations_with_api_entreprise.py
- itou/users/management/commands/send_check_authorized_members_email.py
- tests/employee_record/__snapshots__/test_archive_employee_records.ambr
- tests/employee_record/test_archive_employee_records.py
- tests/job_applications/test_archive_job_applications.py
- tests/users/test_management_commands.py
> Tech: migration d'encore d'autres commandes

- itou/job_applications/models.py
- itou/templates/admin/job_applications/jobapplication_change_form.html
- itou/templates/apply/includes/siae_hiring_actions.html
- itou/templates/apply/process_details_company.html
- tests/job_applications/test_transfer.py
On utilise `xworkflows` donc autant utiliser ses méthodes qui resteront toujours synchro avec le Workflow :)
> Candidature: suppression de méthodes pas ou peu utilisée

- itou/openid_connect/pro_connect/constants.py
Histoire que cette info ne soit pas uniquement présente dans les marque-pages de mon navigateur préféré 
> Technique: Ajout d'un commentaire expliquant l'origine d'un setting

- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Pour ne pas laisser les données personnelles en "accès libre"
> GPS: Ne pas ajouter les orienteurs aux groupes de suivi automatiquement

- itou/common_apps/organizations/views.py
- tests/www/companies_views/test_members_views.py
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/test_members.py
Rassembler les vérifications de permissions pour la clarté et éviter de se répéter.
> Simplifier deactivate_org_membership

- itou/templates/gps/includes/group_members.html
- itou/utils/staticfiles.py
- tests/gps/__snapshots__/test_views.ambr
Bug graphique
-> https://gip-inclusion.slack.com/archives/C067CP07KJR/p1738244049585839
> UX/UI: Fix du bouton avec spinner sur GPS

- itou/www/apply/forms.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_batch_views.py
Tout comme le message de mise en attente lorsqu'on ne met en attente qu'une candidature
> Candidature: le message de mise en attente par lot est maintenant optionnel

- itou/employee_record/common_management.py
- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
- tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr
- tests/employee_record/test_transfer_employee_records.py
- tests/employee_record/test_transfer_employee_records_updates.py
Pour plus facilement retrouver les logs.
> Tech: bascule des commandes de transfert de fiche salarié vers des logs

- itou/common_apps/organizations/views.py
- itou/www/companies_views/views.py
- itou/www/institutions_views/views.py
- itou/www/prescribers_views/views.py
Du code plus simple et plus évolutif.
> Simplification de update_admin_role pour suivre deactivate_membership

- itou/templates/job_seekers_views/job_applications.html
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
> UX.UI: Formulation plus claire pour la liste des candidatures émises par une structure pour le compte d'un candidat [GEN-129]

- clevercloud/cron.json
En attendant que cela soit corrigé coté FT.
> PASS IAE: réduction de la fréquence d'envoi

- itou/www/companies_views/forms.py
- tests/www/companies_views/test_edit_company_views.py
> Employeur: Rendre le numéro de téléphone optionel dans le formulaire de création d'entreprise [GEN-737]

- clevercloud/cron.json
Pour qu'on soit averti en cas d'incohérence.
> Tech: vérification des incohérences entre notre base de données et notre bucket une fois par jour

- itou/templates/apply/list_for_siae.html
La date du séminaire est dépassée
> UX/UI: Supprimer lien vers webinaire dans introjsSwitchView

- itou/templates/companies/edit_siae.html
Améliorations UX de nos formlulaires et aide à la complétion
Il est recommandé de ne mettre d'un champ de saisie par ligne.
> UX/UI: Un seul champ de saisie par ligne

- config/settings/base.py
- itou/allauth_adapters/migrations/0001_initial.py
- itou/templates/account/peamu_no_email.html
- itou/users/migrations/0005_clean_pe_connect_users_from_allauth.py
- tests/users/test_admin.py
Moins de code, moins de problème.
`allauth` rajoute 19 chemins d'URL et la suppression de l'app `socialaccount` qui ne semble pas être utilisée en enlève déjà 4.
Les tests passent mais bon :sweat_smile: 
> Tech: suppression d'une application allauth (a priori) non utilisée

- itou/users/admin.py
- tests/users/test_admin.py
> Admin: permettre de chercher par public_id

- tests/prescribers/tests.py
C'est mieux de ne pas tromper le lecteur peu attentif
> Correction d'un nom de test 

- itou/templates/employee_record/add.html
- tests/www/employee_record_views/__snapshots__/test_add.ambr
Petite faute (ou typo :P), et https://gip-inclusion.slack.com/archives/C03ES35UL30/p1739425925582349
> Fiches Salarié : Correction du phrasé pour la première étape du tunnel de création

- itou/www/job_seekers_views/views.py
- tests/companies/test_admin.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create_or_update.py
Pour enlever encore un `ignore_unknown_variable_template_error`
> Tech: définition systématique d'une variable non définie

- itou/approvals/admin_views.py
- itou/companies/admin.py
- itou/users/admin.py
- tests/approvals/tests.py
- tests/companies/test_admin.py
- tests/users/test_admin_views.py
- tests/www/apply/test_submit.py
> tests: suppression d'autres `ignore_unknown_variable_template_error`

- itou/utils/apis/geiq_label.py
- tests/geiq/test_admin.py
- tests/utils/apis/test_geiq_label.py
Pour être compatible avec les nouvelles méthodes
> GEIQ: mise à niveau du client d'API Label pour gérer les nouvelles commandes

- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/job_seekers_views/list.html
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Car tout a une fin
https://www.notion.so/gip-inclusion/Supprimer-Mini-tuto-de-pr-sentation-de-la-nouvelle-fonctionnalit-postuler-pour-un-candidat-18a5f321b6048187b718d07f82318613?pvs=4
> UX/UI: Suppression de la mise en avant du bouton "Postuler pour ce candidat"

- Makefile
- itou/fixtures/django/dumpdata.sh
Ces données sont maintenant dans des fichiers SQL.
Cette modif aurait du être dans le commit f6959690468bcd3a052fe4d8502ad5cf63f13982.
> fixtures: nettoyage de `dump_data.sh`

- itou/utils/urls.py
- tests/utils/tests.py
Pour éviter des URL contenant des caractères particuliers que les navigateurs interprètent de manière hasardeuse menant à une vulnérabilité de redirection ouverte.
> Sécurité: amélioration de `get_safe_url`

- itou/eligibility/enums.py
- itou/utils/apis/api_particulier.py
- itou/utils/mocks/api_particulier.py
- tests/eligibility/test_geiq.py
- tests/eligibility/test_iae.py
- tests/eligibility/test_tasks.py
- tests/utils/apis/test_api_particulier.py
Utiliser l'API Particulier pour certifier le critère AAH (Allocation Adulte Handicapé).
Ajout du critère AAH à la liste des critères certifiables.
> Certification AAH

- clevercloud/cron.json
Le soucis a été corrigé coté France Travail, on peut recommencer à envoyer des PASS toutes les 5 minutes.
> Tech: rétablissement de la fréquence d'envoi des PASS IAE à France Travail

- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
Pour rendre les choses plus lisibles.
> GPS: refactor des tests

- itou/templates/employee_record/includes/_status.html
> Fiches salarié: correction d'une faute dans le libellé d'un badge

- tests/openid_connect/pro_connect/tests.py
Lisibilité, rapidité des tests.
> Retirer des asserts inutiles dans pro_connect/tests.py

- itou/templates/employee_record/add.html
- itou/templates/employee_record/missing_employee.html
- itou/www/employee_record_views/enums.py
- itou/www/employee_record_views/forms.py
- itou/www/employee_record_views/urls.py
- itou/www/employee_record_views/views.py
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_missing_employee.ambr
- tests/www/employee_record_views/test_missing_employee.py
Pour permettre aux employeurs de mieux comprendre leur situation et éviter des contacts au support
> Fiches salarié: Mise en place d'une page d'aide pour les employeurs [GEN-2218]

- itou/gps/grist.py
Parce que Louis-Jean s'amuse à changer les noms d'onglets sans me dire :D
> GPS: Mise à jour du document Grist

- itou/users/management/commands/new_users_to_brevo.py
- tests/users/test_management_commands.py
L’envoi de données candidats nécessite quelques évolutions de la commande d’envoi.
> Brevo : Préparation à l’envoi de données candidats [GEN-1400]

- itou/utils/apis/metabase.py
Ce n'est pas ou plus les bon, _duh_.
> Pilotage : Mise à jour des formulaire Tally pour les tableaux de bord ETP employeurs

- itou/templates/gps/group_beneficiary.html
- itou/www/gps/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
En reprenant les mêmes règles que pour la page candidat
voir figma : https://www.figma.com/design/qgmw6ZTrDRARTNO5yRF1kW/%F0%9F%A7%AD-B%C3%A9n%C3%A9ficiaires?node-id=260-16490&t=jfMWUKixkQrJBR0T-0
> GPS: Ajout d'un bouton pour modifier le profil candidat

- itou/utils/staticfiles.py
Fix l'etat `disabled` des dakepicker
> UX/UI: mise a jour du theme vers v2.7.3

- itou/templates/gps/group_memberships.html
- tests/gps/__snapshots__/test_views.ambr
> GPS: Petit correctif UI

- itou/www/apply/forms.py
- itou/www/apply/urls.py
- itou/www/apply/views/common.py
- itou/www/apply/views/process_views.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_forms.py
- tests/www/apply/test_process.py
https://github.com/gip-inclusion/les-emplois/pull/5248/files#r1963577826
> Candidature: Paramètrise job_seeker sur AcceptForm

- itou/templates/apply/includes/geiq_eligibility_section.html
- itou/templates/apply/includes/job_application_external_transfer_progress.html
- itou/templates/apply/process_refuse.html
- itou/templates/apply/submit/application/base.html
- itou/templates/approvals/includes/progress_bar.html
- itou/templates/approvals/prolongation_requests/deny.html
- itou/templates/companies/edit_job_description.html
- itou/templates/companies/edit_job_description_details.html
- itou/templates/companies/edit_job_description_preview.html
- itou/templates/companies/edit_siae.html
- itou/templates/companies/edit_siae_description.html
- itou/templates/companies/edit_siae_preview.html
- itou/templates/employee_record/add.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_base.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
- itou/templates/siae_evaluations/institution_evaluated_siae_notify_step1.html
- itou/templates/siae_evaluations/institution_evaluated_siae_notify_step2.html
- itou/templates/siae_evaluations/institution_evaluated_siae_notify_step3.html
- tests/www/apply/__snapshots__/test_process_external_transfer.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/employee_record_views/__snapshots__/test_add.ambr
Mise en cohérence de l'UI et suppression des classes inutiles
> UX/UI: Ajustement UI du stepper et la progress bar

- config/settings/base.py
- itou/templates/apply/includes/buttons/rdv_insertion_promote.html
- itou/templates/apply/includes/list_card_body.html
- itou/templates/apply/includes/siae_hiring_actions.html
- itou/templates/apply/list_for_siae.html
- itou/www/apply/views/list_views.py
- itou/www/apply/views/process_views.py
- tests/companies/factories.py
- tests/prescribers/factories.py
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
Pas assez de retours (le bouton n'est pas présent sur la vue tableau + Auvergne-Rhône-Alpes en congés en ce moment).
Suppression de la restriction départementale.
> Candidature: affichage du bouton de promotion de RDVI à tous les employeurs [GEN-2235]

- itou/www/gps/urls.py
- tests/gps/test_views.py
Ces anciennes urls ont été communiquées par mail à des utilisateurs  
-> https://gip-inclusion.slack.com/archives/C067CP07KJR/p1741260182559899
> GPS: Ajout d'urls de compatibilité

- itou/templates/gps/group_beneficiary.html
- itou/templates/gps/group_details_base.html
- itou/templates/gps/includes/memberships_results.html
- itou/www/gps/forms.py
- itou/www/gps/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
> GPS: Ne pas afficher les informations personnelles aux orienteurs quand le candidat n'a pas repris le contrôle de son compte

- itou/templates/signup/choose_user_kind.html
- itou/templates/signup/company_select.html
- itou/templates/signup/includes/user_kind_radio.html
- itou/templates/signup/job_seeker_criteria.html
- itou/templates/signup/job_seeker_situation.html
- itou/templates/signup/job_seeker_start.html
- itou/templates/signup/prescriber_check_already_exists.html
- itou/templates/signup/prescriber_check_pe_email.html
- itou/templates/signup/prescriber_choose_kind.html
- itou/templates/signup/prescriber_choose_org.html
- itou/templates/signup/prescriber_confirm_authorization.html
- itou/templates/signup/prescriber_pole_emploi_safir_code.html
- itou/templates/signup/prescriber_request_invitation.html
Les liens "Annuler" renvoyaient vers le dashboard
Les boutons "Retour" manquaient sur certaines étapes
Les boutons "Continuer" devaient être renommés en "Suivant"
Et quelques fix UI en passant
> UX/UI: Modifications des urls d'annulation et de retour dans les formulaires d'inscription

- itou/templates/job_seekers_views/list.html
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
Vraisemblablement dû à un copier-coller.
> Correction mineure d'un aria-label

- itou/static/js/formset_add_remove_row.js
- itou/templates/invitations_views/create.html
> UX/UI: Fix invitations placeholder

- itou/approvals/admin_forms.py
La méthode `get_origin` vient d'être supprimée dans cd15a45745eea7aea959ccd6f5142c2a3752e6b2
> admin: correction du formulaire de modification d'un PASS IAE

- tests/approvals/test_admin.py
> Admin: Correction de la page des PASS IAE

- itou/templates/companies/job_description_list.html
Pour parler français
En parlant français
> Fiche de poste: Correction d'une typo dans un template

- itou/templates/dashboard/dashboard.html
- itou/www/dashboard/views.py
- tests/www/dashboard/__snapshots__/test_dashboard.ambr
- tests/www/dashboard/test_dashboard.py
> Admin: Correction du tableau de bord pour les non super utilisteurs

- itou/analytics/admin.py
- itou/approvals/admin.py
- itou/cities/admin.py
- itou/companies/admin.py
- itou/eligibility/admin.py
- itou/emails/admin.py
- itou/gps/admin.py
- itou/job_applications/admin.py
- itou/jobs/admin.py
- itou/otp/admin.py
- itou/siae_evaluations/admin.py
- itou/users/admin.py
- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
Le ReaonlyMixin doit être avant les classes inline.
Dans le doute, je l'ai mis devant partout
> Admin: Corrections diverses pour l'équipe support

- itou/gps/models.py
- itou/templates/gps/join_group_from_name_and_email.html
- itou/www/gps/utils.py
- itou/www/gps/views.py
- tests/gps/test_models.py
- tests/gps/test_views.py
Pour que les liens s'affichent bien dans slack, et que la modal s'affiche tout court
> GPS: Correction de l'ajout de bénéficiare

- itou/prescribers/admin.py
- itou/templates/admin/companies/change_company_form.html
- itou/templates/admin/prescribers/change_form.html
- itou/templates/dashboard/dashboard.html
- itou/users/management/commands/sync_group_and_perms.py
- itou/users/models.py
- itou/www/dashboard/views.py
- itou/www/itou_staff_views/views.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
> Admin: encore une permission manquante

- itou/www/apply/views/process_views.py
- itou/www/gps/views.py
We now use LoginRequiredMiddleware
> Nettoyage des LoginRequiredMixin restants

- config/settings/dev.py
> Désactiver le 2FA par défaut sur l'environnement de développement

- itou/templates/employee_record/add.html
- itou/templates/employee_record/list.html
- itou/www/apply/urls.py
- itou/www/apply/views/batch_views.py
- itou/www/employee_record_views/urls.py
- itou/www/employee_record_views/views.py
- itou/www/utils/wizard.py
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_list.ambr
- tests/www/employee_record_views/test_add.py
Il y a quelques trucs que je changerais bien: 
Le second point est complexe à gérer : Il faut arriver à sortir de `setup()` sans raiser, ne pas planter sur `test_func()` si elle existe, pour arriver à `dispatch()`.
C'est donc lourd à écrire, donc pour l'instant je laisse en l'état et on verra dans un second temps.
> Remplacer formtools.Wizard par notre wizard maison pour la création de fiche salarié

- itou/gps/admin.py
- itou/users/admin.py
- tests/gps/test_admin.py
- tests/users/__snapshots__/test_admin_views.ambr
https://www.notion.so/gip-inclusion/Lien-GPS-dans-l-admin-aller-vers-Relations-et-pas-GDS-1975f321b604805a8b3ec2bca857952a
Pour tester :
Aller sur la page d'un candidat, le lien doit mener vers le détail de son groupe de suivi
Aller sur la page d'un prescripteur ou employeur, le lien doit mener vers la liste des FollowUpGroupMembership dont il est membre
> Admin: changer les liens GPS de la page utilisateur

- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
La permission est vérifiée par la page manually_add_approval
> Admin: Re-permettre aux membre du groupe itou-admin de créer un PASS depuis l'admin

- itou/templates/itou_staff_views/otp_devices.html
- tests/www/itou_staff_views/__snapshots__/tests.ambr
Suite à une remarque de @joffreymougel, car c'est également ce qui est fait pour les critères certifiés
> Admin: Modification de l'icone indiquant l'appareil OTP utilisé

- itou/www/job_seekers_views/views.py
Pour s'assurer que la bonne variable existe
> Correction d'une typo dans JobSeekerBaseView

- itou/users/models.py
> Technique: Utilisation d'un utilisaire pour nettoyer le code 

- config/settings/base.py
> Ajout d'un setting temporaire pour changer le SECRET_KEY de Django

- itou/templates/gps/group_beneficiary.html
- itou/templates/gps/group_contribution.html
- itou/templates/gps/group_edition.html
- itou/templates/gps/group_memberships.html
- tests/gps/__snapshots__/test_views.ambr
> GPS: Mise en conformité de l'UI de la liste des intervenants

- itou/templates/approvals/suspension_delete.html
- itou/templates/approvals/suspension_update.html
- itou/templates/approvals/suspension_update_enddate.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
- tests/www/approvals_views/__snapshots__/test_suspend.ambr
Parcque Joffrey a un œil de lynx
> UX/UI: Correction de wording de boutons de formulaires

- itou/templates/includes/mon_recap_banner.html
Pour suivre l'intérêt des utilisateurs dans le produit (affichages vs clics)
(cf https://gip-inclusion.slack.com/archives/C0412CTV63D/p1742983729325019)
> Ajout d'un tracker sur l'affichage de la bannière Mon Récap

- itou/templates/dashboard/dashboard.html
- itou/templates/dashboard/includes/job_seeker_approval_card.html
- itou/templates/dashboard/includes/job_seeker_job_applications_card.html
Problèmes d'integration UI
**Avant**
**Apres**
> UX/UI: correction UI des "cards" du dashboard candidats

- config/settings/base.py
Plus besoin de cette valeur : toutes les sessions sont supprimée le lundi très tôt
> settings: Remove SECRET_KEY_FALLBACKS

- itou/utils/perms/middleware.py
- tests/companies/__snapshots__/test_admin.ambr
- tests/companies/test_admin.py
- tests/siae_evaluations/test_admin.py
- tests/users/__snapshots__/test_admin_views.ambr
- tests/www/itou_staff_views/__snapshots__/tests.ambr
- tests/www/login/tests.py
C'est plus simple pour l'environnement de dev 
> Dev: ne pas demander l'OTP quand REQUIRE_OTP_FOR_STAFF est désactivé

- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
https://www.notion.so/gip-inclusion/Fusionner-le-TB-traitement-et-r-sultats-des-candidatures-recues-par-ma-ou-mes-structures-et-d-clarat-1b95f321b60480d8a730e4248a0af9f7?pvs=4
> Pilotage : Fusionner le TB traitement et résultats des candidatures recues par ma ou mes structures et déclarations d’embauche (394/185) 

- itou/templates/layout/base.html
Pour prévenir d'une future maintenance
Ajout d'une bannière sur toutes les pages
> Maintenance: Ajout d'une bannière pour informer d'une future maintenance

- itou/templates/layout/base.html
Plus d'actualité
Suppression de la bannière
> Maintenance: retrait d'une bannière informant d'une maintenance

- itou/templates/gps/group_list.html
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
Je cite [[1]](https://www.notion.so/gip-inclusion/Supprimer-Inviter-un-partenaire-1c85f321b60480a18dcffb15422fd847?pvs=4)
> Il est bizarre, cassé, et j’ai la flemme de le réparer.
> GPS: Suppression d'un formulaire tally pour inviter un partenaire

- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
https://www.notion.so/gip-inclusion/Fusionner-le-TB-auto-prescription-et-controle-a-posteriori-295-298-1b95f321b60480a5b67ef5e758b0b036?pvs=4
> Pilotage : Fusionner le TB auto-prescription et controle a posteriori

- itou/gps/management/commands/sync_follow_up_groups_and_members.py
- itou/gps/models.py
- tests/gps/test_management_commands.py
- tests/gps/test_models.py
https://gip-inclusion.slack.com/archives/CRW3TSFRV/p1743688090680429
> GPS: Ne pas créer de relations sur des utilisateurs non prescripteur ou employeur

- itou/templates/dashboard/includes/stats.html
- itou/templates/dashboard/includes/stats_kpi_labor_inspector_iae.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
- tests/www/stats/test_views.py
https://www.notion.so/gip-inclusion/Supprimer-les-tableaux-de-bord-en-ballotage-d-favorable-1c45f321b60480bf8d09d6e2308df14c?pvs=4
> Pilotage : Suppression des tableaux de bord en ballotage défavorable

- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Un prescripteur doit être dans une orga avec au moins 2 membres pour voir l'onglet "Tous les candidats de la structure".
> Candidats : correction d'un test

- itou/templates/403.html
- itou/templates/404.html
- itou/templates/500.html
> UX/UI: déplacement du contenu des pages d'erreur au bon endroit

- .github/workflows/ci.yml
- .github/workflows/review-app-creation.yml
- CHANGELOG_breaking_changes.md
- docker-compose.yml
La prod tourne en PG 17 depuis mercredi
> Migration de la CI & stack local en postgres 17

- itou/templates/includes/demo_accounts.html
- itou/utils/templatetags/demo_accounts.py
Car c'est tout de même pratique ces petits boutons :sweat_smile: 
Mais uniquement en dev pour éviter d'avoir des soucis sur la demo ou les recettes jetables (à discuter ?)
> Tech: ajout d'un bouton de connexion rapide pour l'admin également

- config/settings/base.py
- itou/templates/403.html
- itou/templates/404.html
- itou/templates/500.html
- itou/templates/companies/card.html
- itou/templates/companies/create_siae.html
- itou/templates/companies/job_description_card.html
- itou/templates/companies/job_description_list.html
- itou/templates/companies/members.html
- itou/templates/companies/overview.html
- itou/templates/companies/select_financial_annex.html
- itou/templates/companies/show_financial_annexes.html
- itou/templates/components/c-title.html
- itou/templates/static/accessibility.html
- itou/templates/static/legal/notice.html
- itou/templates/static/legal/privacy.html
- itou/templates/static/legal/terms.html
- itou/utils/templatetags/components.py
- pyproject.toml
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- tests/www/companies_views/__snapshots__/test_card_views.ambr
Pour faciliter l'intégration des composants du thème et éviter les incohérences de UI
Recette jetable > https://c1-review-deloo-add-title-slippers-component.cleverapps.io/search/employers
> Création du composant c-title et mise a jour des templates static et companies

- itou/gps/management/commands/import_advisor_information.py
`argparse.FileType` a un soucis sur la fermeture des fichiers et a été déprécié à cause de ça.
> Correction d'un test erratique

- itou/gps/management/commands/import_advisor_information.py
Suite à un retour de PR https://github.com/gip-inclusion/les-emplois/pull/5914#pullrequestreview-2749903387
> Amélioration du type d'un argument de management command

- itou/utils/apis/data_inclusion.py
- tests/utils/apis/test_data_inclusion_api.py
Pour corriger un problème.
En séparant deux chaînes de caractères.
- x ] Mettre à jour le CHANGELOG_breaking_changes.md ?
> Data inclusion : séparation de deux thématiques

- tests/www/companies_views/test_job_description_views.py
> Déplacer TestEditJobDescriptionView.test_remove_location

- itou/approvals/models.py
- tests/approvals/tests.py
Suite à des commentaires post merge
> Amélioration du code suite à #5937

- itou/users/migrations/0001_initial.py
- itou/users/models.py
- itou/utils/models.py
https://github.com/django/django/pull/16560 est dispo depuis Django 5.0
> utils: suppression de  `UniqueConstraintWithErrorCode`

- tests/www/apply/test_process_external_transfer.py
suite à ce commentaire : https://github.com/gip-inclusion/les-emplois/pull/5931/files/ef5ded14bca113c5c8234aebe6c532ae10bcbf54..3c7f3cae9ebd1ff465534e13bac404aff5950122#r2044747003
> Supression de for_snapshot=True non nécessaires dans des tests

- itou/www/companies_views/views.py
> Utiliser request.current_organization dans companies_views/views.py

- tests/www/companies_views/test_job_description_views.py
Plus simple à lire et maintenir. Retirer des subtests.
> Simplifier les assertions de test_job_description_views

- itou/www/companies_views/views.py
- tests/www/companies_views/test_job_description_views.py
Le formulaire a connaissance de ces champs, et sait les traiter, sans intervention de la vue.
> Simplifier edit_job_description_details

- itou/templates/approvals/includes/box.html
- tests/www/approvals_views/__snapshots__/test_approval_box.ambr
- tests/www/approvals_views/__snapshots__/test_detail.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
Pour permettre aux SIAE de pouvoir prouver la durée d'un PASS expiré (il n'y en a pas par défaut dans les fixtures)
Se connecter en tant que SIAE, et afficher un utilisateur avec un PASS expiré.
Avant : 
Après :
> PASS IAE: Ajouter des informations sur l'affichage d'un PASS IAE expiré [GEN-2392]

- tests/www/apply/test_submit.py
Le test `tests/www/apply/test_submit.py::TestApply::test_start_view_initializes_session` est bagottant.
L'erreur difficilement reproduisible est la suivante :
```
> pytest -vv --randomly-seed=2091349403 tests/www/apply/test_submit.py::TestApply::test_start_view_initializes_session[with_selected_jobs]
...
def test_start_view_initializes_session(self, client, job_description_id, back_url, expected_session):                                                                                                                                    
company = CompanyFactory(with_jobs=True, with_membership=True)                                                                                                                                                                        
if job_description_id: …
```
> Correction d'un test bagottant

- itou/templates/job_seekers_views/details.html
- itou/templates/job_seekers_views/includes/list_results.html
- itou/www/apply/views/submit_views.py
- itou/www/eligibility_views/urls.py
- itou/www/eligibility_views/views.py
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/__snapshots__/test_submit_from_job_seekers_list.ambr
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/eligibility_views/test_views.py
Modifications diverses pour préparer la réutilisation de la page d'éligibilité IAE dans le parcours de candidature
- Ajout de snapshot
- correction d'un test
- saut de l'étape d'eligibilité avant d'y accéder (au lieu d'avoir un dispatch dessus pour ignorer l'étape)
- changements d'un kwargs dans l'url d'eligibilité
> Travail préparatoire pour fusionner les vues d'éligibilité IAE

- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/views.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/search/tests.py
> Nettoyage de code de retrocompatibilité

- itou/templates/django_bootstrap5/form_errors.html
- itou/templates/layout/base.html
- tests/gps/__snapshots__/test_views.ambr
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_prescriptions.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/dashboard/test_edit_user_info.py
- tests/www/employee_record_views/test_create.py
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/siae_evaluations_views/test_institutions_views.py
- tests/www/signup/__snapshots__/test_job_seeker.ambr
- tests/www/signup/test_job_seeker.py
Parcque c'est [une bonne pratique A11Y](https://www.notion.so/gip-inclusion/Formulaires-Am-lioration-A11Y-Messages-d-erreurs-au-rechargement-de-la-page-1ca5f321b604807fb715e4e74cec726d?pvs=4)
**Avant**
**Apres**
> Accessibilité: Amélioration de l'affichage des erreurs de formulaire 

- itou/templates/apply/includes/next_appointment.html
- itou/www/apply/views/list_views.py
- itou/www/apply/views/process_views.py
- tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_detail_rdv_insertion.py
- tests/www/apply/test_list_rdv_insertion.py
Pour que l'ensemble des profils puisse visualiser les rendez-vous à venir.
> Candidature: En tant que prescripteur je vois tous les rendez-vous pris depuis les pages de candidatures [GEN-1913]

- itou/templates/companies/create_siae.html
- itou/templates/companies/edit_siae.html
- itou/templates/companies/edit_siae_description.html
- itou/utils/urls.py
- itou/www/companies_views/forms.py
- tests/utils/tests.py
- Harmonisation du label des Email (e-mail vs Email)
- Correction A11Y de l'affichage des erreurs de formulaire pour correspondre a [cette amélioration](https://github.com/gip-inclusion/les-emplois/pull/5977)
> Interface: Optimisation des formulaires de création et d'édition de structures

- itou/templates/companies/edit_job_description.html
- itou/templates/companies/edit_job_description_details.html
- Quelques corrections UI (remplacement des .alert-info par des c-info)
> Interface: Optimisation des formulaires de création et d'édition de fiches poste

- itou/www/apply/views/submit_views.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/apply/test_submit.py
Suite du travail commencé dans #5931: cette fois-ci on force le passage par StartView
> Candidature: Travail préparatoire en vue de refondre la session 2

- itou/utils/templatetags/nav.py
Il est là depuis assez longtemps
> GPS: Suppression du badge nouveau à côté du menu latéral pour le département du Gard

- itou/www/apply/views/process_views.py
C'est bon, le changement est en place depuis plus d'une semaine.
> Nettoyage de code dans le parcours de transfert de candidature

- itou/companies/management/commands/move_company_data.py
- itou/companies/models.py
Pour mettre ça derrière moi avant de partir en semaine off.
> Typos : Correctif de typos variées dans les commentaires du code

- itou/common_apps/address/forms.py
- itou/common_apps/nir/forms.py
- itou/templates/dashboard/includes/edit_job_seeker_info_form.html
- Remplacement des placeholder par des help_text
> Interface: Optimisation du formulaire de modification de fiche Salarié ASP

- itou/templates/employee_record/add.html
- itou/templates/employee_record/includes/create_step_1.html
- itou/templates/employee_record/includes/create_step_2.html
- itou/templates/employee_record/includes/create_step_3.html
- itou/templates/employee_record/includes/create_step_4.html
- itou/templates/employee_record/includes/create_step_5.html
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_create.ambr
> Interface: Optimisation des formulaires de création et d'édition de Salarié ASP

- itou/templates/apply/includes/eligibility_section.html
- itou/templates/apply/includes/job_application_accept_form.html
- itou/templates/eligibility/includes/form.html
> Interface: Optimisation des formulaires d'éligibilité et d'acceptation

- itou/templates/account/login_job_seeker.html
- itou/templates/apply/includes/job_application_accept_form.html
- itou/templates/approvals/includes/declaration_prescriber_email.html
- itou/templates/dashboard/edit_user_info.html
- itou/templates/dashboard/includes/edit_job_seeker_info_form.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_1.html
- itou/templates/signup/job_seeker_signup.html
- itou/templates/signup/job_seeker_signup_credentials.html
- tests/www/signup/__snapshots__/test_job_seeker.ambr
Si les champs de mêmes types font la même longueur partout, c'est mieux
{% bootstrap_field form.pole_emploi_id %}
{% bootstrap_field form.post_code %}
{% bootstrap_field form.nir %}
{% bootstrap_field form.phone %}
{% bootstrap_field form.email %}
{% bootstrap_field form.title %}
> Interface: Harmonisation des longueurs de champs par type spécifique

- itou/utils/session.py
- tests/utils/tests.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/job_seekers_views/test_list.py
Il n’y a plus d’anciennes sessions.
> Retrait du code de compatibilité sur la vérification des session namespace

- .github/workflows/ci.yml
- .github/workflows/git.yml
- .github/workflows/mkchangelog.yml
- .github/workflows/notify-slack.yml
- .github/workflows/require-labels.yml
- .github/workflows/review-app-creation.yml
- .github/workflows/review-app-removal.yml
https://github.com/gip-inclusion/les-emplois/security/code-scanning
> Github : Définir les permissions pour les jobs

- itou/templates/signup/company_select.html
- itou/templates/signup/includes/prescriber_card.html
- itou/templates/signup/prescriber_request_invitation.html
- itou/users/models.py
- tests/users/test_models.py
- tests/www/signup/test_prescriber.py
- tests/www/signup/test_siae.py
La logique était dispersée dans trois gabarits.
> Interface : gestion du nom tronqué des utilisateurs à partir du modèle

- itou/templates/companies/card.html
- itou/templates/companies/job_description_card.html
- itou/templates/components/c-navinfo.html
- itou/utils/templatetags/components.py
- pyproject.toml
- tests/www/companies_views/__snapshots__/test_card_views.ambr
- tests/www/companies_views/test_card_views.py
Ce composant sera prochainement utile dans d'autres cas
> Réusinage: La carte de job description utilise le nouveau composant c-navinfo

- itou/templates/account/login_job_seeker.html
La phrase est nettement plus correcte ainsi.
> Correction d'une coquille sur la page de connexion candidat

- itou/templates/companies/create_siae.html
- itou/templates/companies/edit_siae.html
- itou/templates/prescribers/edit_organization.html
- tests/www/prescribers_views/__snapshots__/test_edit.ambr
> Interface: Optimisation du formulaire d'édition d'organisation

- itou/www/apply/urls.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/views.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
Encore du travail préparatoire...
Découpage d'un premier bloc de #6039
> Candidature: Travail préparatoire en vue de refondre la session 3a

- itou/www/apply/views/submit_views.py
- tests/job_applications/factories.py
- tests/www/apply/test_submit.py
Seul le "sender" peut accéder à cette page
> Candidature: Vérifier l'identité de l'utilisateur pour accéder à la page de fin de candidature

- itou/templates/eligibility/includes/form.html
- itou/www/apply/urls.py
- itou/www/apply/views/common.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
> Candidature: Travail préparatoire en vue de refondre la session 3b: Refonte des vues l’éligibilité du parcours IAE pour utiliser des CBV

- itou/job_applications/management/commands/fill_resume.py
- tests/job_applications/tests.py
Ajout d'une commande pour remplir le nouveau champ `JobApplication.resume` 
> Candidature: Remplissage des CV des anciennes candidatures [GEN-2443]

- itou/www/apply/views/common.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_views.py
- tests/utils/test.py
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/companies_views/test_job_description_views.py
- tests/www/employee_record_views/test_add.py
- tests/www/job_seekers_views/test_create_or_update.py
Encore du travail préparatoire...
Normalement après ça il ne reste qu'à passer les sessions en uuid :crossed_fingers:  
~~Désolé pour le grand nombre de commits.
Les changements sont normalement les plus petits possibles pour chaque commit.~~
Découpé en 3, les 2 premières parties sont à présent ici : 
https://github.com/gip-inclusion/les-emplois/pull/6083
https://github.com/gip-inclusion/les-emplois/pull/6086
Ici ça reste un peu du mélange :
- j'introduis des méthodes qui permettront de passer les paramètres d'urls (`company_pk` ou `session_uuid`) en fonction de l'url le temps de la bascule (utilisé dans la PR #6065)
Ces méthodes seront supprimées quand on aura fait la bascule.
- je saute l'étape d'eligibilité dans le parcours `for_hire` (comme pour le parcours d'eligibilté dans le …
> Candidature: Travail préparatoire en vue de refondre la session 3c: paramètres d'url et gestion des sessions

- itou/eligibility/enums.py
- itou/eligibility/utils.py
- itou/www/eligibility_views/forms.py
- tests/www/eligibility_views/test_forms.py
Cet attribut est uniquement utilisé dans le cadre de l’IAE.
> Réduire les tests de test_num_level2_admin_criteria

- tests/api/job_applications_api/test_search.py
L'API renvoie les candidatures reçues ces trois derniers mois, or la date était maintenant dépassée.
> [API candidats] Correction d'un test

- itou/templates/gps/join_group_from_name_and_email.html
- tests/gps/__snapshots__/test_views.ambr
Pour que le `aria-labelledby` fonctionne.
> Accessibilité: correction d'un `id` pour correspondre au `aria-labelledby`

- tests/employee_record/factories.py
prerequis #6074 
ajout de la factory en objet
> Vie privée : ajout de EmployeeRecordTransitionLogFactory [GEN-2454]

- itou/users/management/commands/send_users_to_brevo.py
- tests/users/test_management_commands.py
Oubli de aa2d862d669391190625d6398989fe5f910e2ac6.
> Notifications : Utiliser les données Pilotage de l’inclusion pour identifier les candidats autonomes sans solutions 

- itou/www/companies_views/urls.py
- itou/www/companies_views/views.py
- tests/www/companies_views/test_job_description_views.py
La période de rétro-compatibilité est échue.
> Nettoyage des URLs de gestion des fiches de poste

- itou/www/apply/urls.py
- itou/www/apply/views/common.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_process_external_transfer.py
- tests/www/apply/test_submit.py
Toujours pas fini :see_no_evil: 
> Candidature: Travail préparatoire en vue de refondre la session 3d: Refonte de la vue de confirmation d'embauche en CBV 

- CHANGELOG.md
Le journal des changements ne s'est pas créé car la branche existait déjà. :shrug: 
> changelog: From 2025-04-28 to 2025-05-04

- itou/geiq/sync.py
- tests/geiq/test_sync.py
Elle n'est plus utile et ne le saura pas non plus dans la nouvelle version.
> GEIQ: suppression de la fonction `sync_assessments`

- itou/www/apply/urls.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/__snapshots__/test_submit_from_job_seekers_list.ambr
- tests/www/apply/test_geiq.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/job_seekers_views/test_list.py
Necessite de merger #6039
Il restera un peu de travail de nettoyage après une semaine.
> Candidature: Passage a une session UUID

- itou/eligibility/models/iae.py
- tests/eligibility/test_iae.py
Changement de comportement suite à un point avec le métier : https://github.com/gip-inclusion/les-emplois/pull/6090#discussion_r2097376105
> Éligibilité : Créer un nouveau diagnostic plutôt que modifier la date de fin lors de la mise à jour

- itou/approvals/management/commands/bulk_update_from_file.py
- tests/approvals/test_mng_cmd_bulk_update_from_file.py
Une DDETS nous a contacté car une SIAE a reçu un conventionnement un peu en retard. Une centaine de PASS IAE, délivrés automatiquement par la plateforme, n'ont pas pu commencer à la date réelle de l'embauche car la SIAE n'était pas en mesure d'accepter les candidatures sur la plateforme.
Ce script prend en entrée un fichier Excel envoyé par la DDETS et met à jour les objets qui peuvent l'être. Tous les PASS ne pouvant pas être mis à jour, un fichier Excel est généré pour être analysé par le métier.
Ajout d'une commande de gestion temporaire qui sera retirée ensuite. Cela me semblait important qu'elle figure dans l'historique Git et qu'elle soit testée car les cas marginaux sont nombreux.
Je sais que le code pourra être amélioré mais gardons en tête que la commande n'a pas vocation à …
> [PASS IAE] Modification des dates de début de PASS IAE et de candidatures à partir d'un fichier Excel

- clevercloud/cron.json
en attendant de régler l'erreur `Cannot delete some instances of model 'User' because they are referenced through restricted foreign keys: 'JobApplication.sender'`
> Vie privée : suspension de la tâche

- itou/www/stats/views.py
> Pilotage : Nettoyage de code à usage unique

- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
- tests/employee_record/test_transfer_employee_records.py
Car on a eu de la chance jusqu'à maintenant :) : https://github.com/gip-inclusion/les-emplois/actions/runs/15255579582/job/42902275284#step:5:161
> Fiches salarié : Ordre déterministe pour les objets sélectionnés lors du transfert

- clevercloud/cron.json
suspension du traitement d'archivage des utilisateurs
https://inclusion.sentry.io/issues/42878707/?project=4508410589020240&referrer=project-issue-stream
> Reapply "suspend notify_archive_users task"

- itou/www/gps/forms.py
- itou/www/gps/utils.py
- itou/www/gps/views.py
- itou/www/job_seekers_views/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
https://www.notion.so/gip-inclusion/Log-des-v-nements-utilisateur-1ed5f321b60480419f88cb1b453e6ff3?pvs=4
Le but est de centraliser les analyses dans datadog.
> GPS: Ajout de logs plus précis 

- itou/utils/templatetags/nav.py
- tests/www/__snapshots__/test_layout.ambr
> Interface: Intégrer les orientations et candidatures envoyées dans le menu latéral pour les employeurs [GEN-2257]

- itou/templates/layout/base.html
Zendesk n'est plus en maintenance.
> Interface : Suppression de la bannière temporaire pour prévenir que Zendesk était indisponible

- itou/templates/approvals/includes/box.html
- tests/www/dashboard/test_dashboard.py
Cette reformulation est plus claire.
cf. https://www.notion.so/gip-inclusion/suggestion-nouveau-wording-2075f321b60480aea41cc20e085d708a?source=copy_link
> Tableau de bord : reformulation dans l'encart du PASS IAE expiré

- itou/communications/models.py
- itou/templates/layout/_news_modal.html
- itou/utils/context_processors.py
- tests/communications/__snapshots__/test_campaigns.ambr
- tests/communications/test_cache.py
- tests/communications/test_campaigns.py
Pour montrer aux candidats les informations les plus pertinentes.
> Nouveautés: correction de la sélection des évènements mis en avant dans la modale pour les candidats [GEN-2503]

- itou/metabase/tables/job_applications.py
C'est mieux de ne pas avoir de fautes
> Metabase: Correction d'une typo

- itou/users/admin.py
- tests/users/test_admin.py
Automatiser ce que le support fait déjà manuellement.
> Admin : Créer automatiquement les EmailAddress lorsque le support change l’email d’un utilisateur Django 

- itou/templates/companies/job_description_list.html
Pour qu'on puisse améliorer la gestion des métiers et recrutement.
> Employeur: ajout d'un bandeau sur la page “Métier et recrutement” pour le questionnaire Maze  [GEN-2475]

- itou/templates/layout/_header_organization_dropdown_menu.html
L’intention était de faire apparaître ces icônes.
> UX/UI : Ajouter des icônes aux organisations dans le sélecteur de structure

- itou/files/management/commands/purge_files.py
Il y en a 52000 à l'initialisation...
J'ajouterai un logger warning une fois le stock initial géré pour qu'on se rende compte si on ne supprime pas les fichiers assez rapidement.
> Tech; Ajout d'un nombre maximum de fichiers à supprimer à la fois 

- itou/templates/employee_record/add.html
- itou/templates/employee_record/includes/create_step_5.html
- itou/templates/employee_record/includes/employee_record_summary.html
- itou/templates/employee_record/summary.html
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/test_summary.py
Harmoniser la page "Fiche salarié ASP" avec la mise en forme de la page "Salarié et Pass IAE”
Notamment en utilsant les .list-data
> Interface: Actualiser l'affichage des templates Fiche Salarié ASP

- itou/utils/brevo.py
- itou/utils/logging.py
- tests/utils/__snapshots__/test_brevo.ambr
- tests/utils/test_brevo.py
Car les données personnelles n'ont rien à faire dans les logs.
> Tech: suppression d'emails présents dans nos logs

- clevercloud/cron.json
- itou/files/management/commands/sync_s3_files.py
- tests/files/tests.py
https://gip-inclusion.slack.com/archives/C0412CTV63D/p1749963682480569
Tout est rentré dans l'ordre à présent
1ère PR -> #6337  
Corriger `sync_s3_files` pour ne pas dupliquer les fichiers
Ajouter une commande pour supprimer tous les Files orphelins sans se soucier du fichier S3 (`sync_s3_files` recréera les `Files` manquant qui seront supprimés par la suite)
2ème PR -> #6338 
Mettre `File.deleted_at = None` pour tous les fichiers pour ne rien supprimer par erreur en plus
Ajouter une contrainte en db sur keys
Supprimer la commande de nettoyage ajoutée.
**3ème PR**
Remettre en place les crons `find_orphans` `purge_files` et `update_ids` `scan_s3_files`
Modifier `sync_s3_files` pour ne pas ajouter les fichiers avec deleted_at renseigné
> _Décrivez en quelques mots la solution retenue et …
> Tech: Remettre en place les crons gêrant les fichiers

- config/settings/base.py
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
> Tech: mise à jour de `django-csp` avec sa configuration

- config/settings/dev.py
Car je les avais oublié. Suite de #6365
> Tech: mise à jour des settings CSP en dev

- itou/job_applications/admin.py
Pour que le support puisse corriger le poste retenu.
> Admin: ajout de champs manquant pour les candidatures

- itou/templates/geiq_assessments_views/assessment_contracts_details.html
- champs inutile
- label un peu plus clair
- correction du champs "Dont 90 jours dans l'année" (qui affichait en fait "Dont 1 jour dans l'année" :see_no_evil: )
- ajout du montant de l'aide potentielle
> GEIQ: diverses améliorations d'affichage pour le bilan d'exécution

- clevercloud/cron.json
- itou/scripts/management/commands/redact_zendesk_attachments.py
RGPD: On reçoit des pièces jointes sensibles dans nos messages zendesk (CNI, Carte vitale etc) et elles restent stockées alors que la demande a été traitée.
NB: J'ai utilisé les api recommandées par Zendesk, mais la suppression de pièces jointes d'un ticket clos (aka résolu depuis plus de 14 jours) n'est pas possible....
On ne peut donc pas traiter le backlog avec ce script.
NB; j'ai pas mis de tests, je ne sais pas à quel point c'est utile en mockant la class `ZendeskClient`....
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous …
> Zendesk: Suppression des pièces jointes de tickets clos [GEN-235]

- itou/templates/dashboard/edit_user_info.html
> Tableau de bord: correction d'une typo [GEN-2554]

- itou/employee_record/management/commands/employee_record.py
Besoin pour du support afin de renvoyer des FS archivées
> Fiches Salarié : Améliorations pour l'utilitaire `employee_record` [GEN-2487]

- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
> Admin: ajoute l'accès aux données analytiques [GEN-2388]

- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_list_for_siae.py
> Tech: Corrections de typos diverses dans des tests

- itou/templates/apply/process_details.html
- itou/templates/layout/base.html
- tests/conftest.py
- tests/openid_connect/pro_connect/tests.py
- tests/www/apply/test_detail_rdv_insertion.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
Cela fait un moment qu'on utilise plus le mode `strict = False`.
> Tech: simplification de la fixture de détection des erreurs de template

- itou/approvals/management/commands/bulk_update_from_file.py
- itou/archive/management/commands/anonymize_jobseekers.py
- itou/archive/management/commands/anonymize_professionals.py
- itou/archive/management/commands/notify_inactive_jobseekers.py
- itou/cities/management/commands/resolve_insee_cities.py
- itou/companies/management/commands/_import_siae/siae.py
- itou/companies/management/commands/update_companies_coords.py
- itou/scripts/management/commands/geolocate_jobseeker_addresses.py
- itou/status/management/commands/run_status_probes.py
- itou/users/management/commands/pe_certify_users.py
- itou/users/management/commands/send_users_to_brevo.py
- itou/users/management/commands/update_job_seeker_coords.py
> Tech: Nettoyage des logger dans les managments commands

- itou/templates/apply/includes/geiq/geiq_diagnosis_details.html
- itou/templates/apply/includes/invitation_requests.html
- itou/templates/apply/includes/job_application_prior_action.html
- itou/templates/apply/includes/job_applications_filters/offcanvas_footer.html
- itou/templates/apply/includes/job_seeker_info.html
- itou/templates/apply/includes/list_card_body.html
- itou/templates/apply/includes/list_job_applications.html
- itou/templates/apply/list_prescriptions.html
- itou/templates/apply/process_details_company.html
- itou/templates/dashboard/includes/job_seeker_eligibility_card.html
- itou/templates/employee_record/includes/create_step_5.html
- itou/templates/employee_record/list.html
- itou/templates/employee_record/summary.html
- itou/templates/includes/valid_eligibility_diagnosis_and_criteria.html
- itou/templates/job_seekers_views/details.html
- itou/templates/job_seekers_views/includes/job_seekers_filters/offcanvas.html
- itou/templates/job_seekers_views/includes/job_seekers_filters/offcanvas_footer.html
- itou/templates/job_seekers_views/list.html
Les contextes isolés aident à plus facilement identifier où sont utilisées les variables au travers nos labyrinthes d'`include`.
Mais on finit souvent avec une _très_ longue liste de variable à transmettre.
Alors autant détecter les variables inutiles pour alléger certaines listes.
> Tech: utilisation de contexte isolé dans plus d'`include`

- itou/templates/apply/list_for_siae.html
- itou/templates/apply/list_prescriptions.html
> Candidature: déplacement du bandeau invitant à un entretien utilisateur vers l'espace prescripteur [GEN-2579]

- itou/templates/dashboard/includes/stats/employer.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
https://www.notion.so/gip-inclusion/Publier-le-TB-550-aux-SIAE-21b5f321b60480deab10e4d956245248?source=copy_link
> Pilotage : Ouverture du TB "Suivi des bénéficiaires, taux d’encadrement et présence en emploi" aux SIAE

- itou/templates/apply/includes/job_application_accept_form.html
- itou/templates/apply/includes/siae_actions.html
- itou/templates/apply/includes/siae_actions_modals.html
- itou/utils/templatetags/job_application_actions.py
- itou/www/apply/forms.py
- itou/www/apply/urls.py
- itou/www/apply/views/batch_views.py
- itou/www/apply/views/common.py
- itou/www/apply/views/list_views.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_process.py
> Candidatures: Modification du fonctionnement de la barre d’action traitement par lot [GEN-2451]

- itou/templates/siae_evaluations/evaluated_siae_detail.html
- itou/templates/siae_evaluations/includes/criteria_form.html
- itou/templates/siae_evaluations/institution_evaluated_siae_list.html
- itou/templates/siae_evaluations/siae_select_criteria.html
- itou/templates/siae_evaluations/siae_upload_doc.html
Parcque les écrans du “Contrôle a posteriori” méritent quelques corrections et améliorations
**Avant**
👇
**Apres**
👇
> Interface: Corrections des écrans du contrôle a posteriori

- itou/templates/companies/card.html
- itou/templates/companies/edit_siae.html
- itou/templates/companies/edit_siae_base.html
- itou/templates/companies/edit_siae_description.html
- itou/templates/companies/edit_siae_preview.html
- itou/templates/companies/overview.html
- itou/templates/prescribers/edit_organization.html
- tests/www/companies_views/test_edit_company_views.py
- tests/www/companies_views/test_overview.py
- tests/www/prescribers_views/__snapshots__/test_edit.ambr
Pour appliquer la nouvelle UI 
**Avant**
👇
**Apres**
👇
> Interface: Corrections des écrans du parcours de modification d'une fiche structure

- itou/templates/dashboard/dashboard_stats.html
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
https://www.notion.so/gip-inclusion/Ajouter-un-bandeau-sur-l-espace-public-et-priv-2255f321b60480fcbf25ce6c920fc63f?source=copy_link
> Pilotage : Ajouter un encart pour prévenir que nous menons une enquête sur les pratiques des SIAE lorsqu’elles préparent leur DG 

- itou/external_data/migrations/0002_delete_rejectedemaileventdata.py
- itou/external_data/models.py
Nettoyage après https://github.com/gip-inclusion/les-emplois/pull/6500.
> Supprimer la table RejectedEmailEventData

- itou/www/itou_staff_views/merge_utils.py
- tests/www/itou_staff_views/tests.py
https://gip-inclusion.slack.com/archives/C067CP07KJR/p1751615551869469
J'ai simplifié un peu la logique, c'est trop compliqué de regarder le groupe finissant le plus tard.
On garde les informations de fin du groupe de l'utilisateur qui est conservé plutôt que de regarder qui groupe fini le plus tard si les 2 sont finis. 
> Tech: Gérer les groupes GPS dans la fusion de comptes utilisateurs [GEN-2592]

- itou/templates/employee_record/includes/create_step_2.html
- tests/www/employee_record_views/__snapshots__/test_create.ambr
> Texte inutile depuis la suppresion de l'etape "Valider cette adresse"
> Fiches salarié: Suppression d'une recommandation inutile sans la création de fiche salarié ASP

- itou/approvals/management/commands/prolongation_requests_chores.py
- itou/archive/management/commands/anonymize_jobseekers.py
- itou/archive/management/commands/anonymize_professionals.py
- itou/companies/management/commands/move_company_data.py
- itou/emails/management/commands/delete_old_emails.py
- itou/employee_record/management/commands/archive_employee_records.py
- itou/employee_record/management/commands/employee_record.py
- itou/users/management/commands/pe_certify_users.py
- itou/utils/command.py
- itou/utils/logging.py
- tests/approvals/__snapshots__/test_prolongation_requests.ambr
- tests/archive/__snapshots__/tests_management_command.ambr
- tests/archive/tests_management_command.py
- tests/emails/test_commands.py
- tests/employee_record/__snapshots__/test_archive_employee_records.ambr
- tests/employee_record/test_archive_employee_records.py
- tests/users/__snapshots__/test_management_commands.ambr
- tests/users/test_management_commands.py
- tests/utils/test_command.py
- tests/utils/test_logs.py
- tests/utils/tests.py
> There should be one-- and preferably only one --obvious way to do it.
> -- https://peps.python.org/pep-0020/
> Tech : Décorateur `@dry_runnable` générique

- itou/templates/companies/create_siae.html
- itou/templates/dashboard/includes/employer_company_card.html
- itou/templates/layout/_structure_switcher_dropdown_menu.html
- itou/templates/layout/_structure_switcher_nav.html
- itou/templates/layout/_structure_switcher_offcanvas.html
- itou/utils/templatetags/structure_switcher.py
- itou/www/dashboard/views.py
- tests/www/__snapshots__/test_layout.ambr
- tests/www/dashboard/test_dashboard.py
- tests/www/test_layout.py
Pour préparer les futures évolutions du dashboard
**Avant**
**Apres**
> Interface: Déplacer le lien vers la création d'une nouvelle structure dans la liste déroulante des structures du menu principal

- tests/companies/test_import_ea_eatt.py
> Tests : Correction des lundi pour les EA/EATT

- itou/www/approvals_views/views.py
- tests/www/approvals_views/test_suspend.py
Suivre plus facilement les modification des dates de suspension, pour répondre plus efficacement au support.
> PASS IAE : logger la création et modification de suspensions

- itou/templates/apply/list_for_siae.html
- itou/templates/apply/list_prescriptions.html
- itou/templates/approvals/list.html
- itou/templates/includes/mon_recap_banner.html
- itou/templates/job_seekers_views/list.html
- itou/www/apply/views/list_views.py
- itou/www/approvals_views/views.py
- itou/www/job_seekers_views/views.py
Ouvrir à tous les départements et modifier l'URL.
> Mise à jour du bandeau promotionnel de Mon Récap (tous les départements) [GEN-2555]

- tests/www/stats/test_views.py
Pas besoin de parametrize avec une seul valeur possible
> Nettoyage d'un test 

- clevercloud/cron.json
- itou/companies/enums.py
- itou/companies/management/commands/sync_ft_offers.py
- itou/companies/migrations/0003_jobdescription_source_tags.py
- itou/companies/models.py
- itou/templates/companies/includes/_card_jobdescription.html
- itou/utils/apis/pole_emploi.py
- itou/utils/mocks/pole_emploi.py
- itou/www/search/views.py
- tests/companies/test_sync_ft_offers.py
- tests/utils/apis/test_pole_emploi_api.py
- tests/www/search/tests.py
> Recherche fiche de poste: affichage des offres d'entreprise adaptée récupérée via l'API de France Travail [GEN-2377]

- tests/www/apply/test_templates.py
- tests/www/signup/__snapshots__/test_job_seeker.ambr
- tests/www/signup/test_job_seeker.py
> Test: Correction d'un snapshot suite au changement de date ne naissance minimale.

- itou/templates/includes/members_list.html
- tests/www/companies_views/__snapshots__/test_members_views.ambr
- tests/www/prescribers_views/__snapshots__/test_members.ambr
Aller sur la page `Gérer les collaborateurs` en étant connecté avec le compte EI
> Invitations: Ajout de liens vers la documentation sur la page d'invitation de collaborateurs [GEN-2597]

- itou/templates/dashboard/dashboard.html
https://www.notion.so/gip-inclusion/18a5f321b604815dae97d270c3aaec68?v=18a5f321b604811bad80000cf7934cee&p=24e5f321b60480049555c1b349fa2cd5&pm=c
Dans la zone d'alerte
> Prescripteur: Ajout d'un bandeau d’alerte pour une enquête Maze

- clevercloud/cron.json
- config/settings/base.py
- itou/utils/admin.py
- itou/utils/management/commands/check_inconsistencies.py
- tests/utils/test_check_inconsistencies.py
Pour pouvoir être alerté et les corriger le plus tôt possible.
L'idée serait de l'avoir dans un premier temps dans #emplois-tech-notifications et ensuite peut-être un canal dédié.
> Tech: ajout d'une vérification de cohérence quotidienne

- itou/templates/siae_evaluations/includes/criterion_infos.html
- tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
- tests/www/siae_evaluations_views/test_siaes_views.py
Mise en conformité légale :  l’Arrêté du 12/04/22 exige un document papier.
Mise à jour de la mention
> Contrôle a posteriori : Mise à jour d'une mention relative aux justificatifs [GEN-2657]

- itou/openid_connect/france_connect/views.py
- itou/openid_connect/pe_connect/views.py
Pour faciliter le traitement de ces cas peu probables.
> Tech: ajout de message d'erreur dans le parcours de connexion OpenID

- tests/eligibility/factories.py
- tests/openid_connect/france_connect/tests.py
- tests/openid_connect/pe_connect/tests.py
- tests/siae_evaluations/test_models.py
- tests/www/apply/test_process.py
- tests/www/apply/test_templates.py
- tests/www/dashboard/test_edit_job_seeker_info.py
- tests/www/dashboard/test_edit_user_info.py
- tests/www/employee_record_views/test_create.py
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/siae_evaluations_views/test_institutions_views.py
- tests/www/siae_evaluations_views/test_siaes_views.py
> tests: Définir la date de certification quand un critère est certifié

- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
- tests/users/test_sync_group_and_perms.py
> Admin : Permettre aux membres du groupe itou-admin-readonly de télécharger les exports CTA [GEN-2666]

- itou/eligibility/models/common.py
- itou/eligibility/models/geiq.py
- itou/eligibility/models/iae.py
- itou/www/apply/views/common.py
https://github.com/gip-inclusion/les-emplois/pull/6759#discussion_r2307444171
> Renommer EligibilityDiagnosis.certify_criteria en schedule_certification

- tests/archive/tests_management_command.py
> archive: Tester l’anonymisation d’un prescripteur en deux étapes

- itou/templates/companies/select_financial_annex.html
- itou/templates/includes/members_list.html
- tests/www/companies_views/__snapshots__/test_members_views.ambr
- tests/www/prescribers_views/__snapshots__/test_members.ambr
Parcque c'est mieux
- `select_financial_annex.html`amélioration de la UI en déplacant le message dans un composant `c-info`et amélioration de l'a11y avec un texte cliquable et un aria-label plus complet (et complementaire)
- `members_list.html` amélioration de l'a11y avec un texte cliquable et un aria-label plus complet (et complementaire)
**Avant**
**Apres**
> Interface: Amélioration de la UI et de l'A11 de certains liens vers la documentation

- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
> Tech: Mise à jour de Django en 5.2.6

- itou/templates/apply/includes/accept_section.html
On a constaté 2 candidatures à 0,24s d'intervalle en décembre 2024.
https://gip-inclusion.slack.com/archives/C01181Y04LT/p1757001047417419
> Candidature: Empêcher la déclaration d'embauche en double en cas de double-clic 

- itou/utils/templatetags/nav.py
- tests/www/geiq_assessments_views/__snapshots__/test_views_for_geiq.ambr
-  éviter d'envoyer une erreur Sentry pour les _labor inspector_ sans institutions: https://inclusion.sentry.io/issues/51212354/
- éviter de faire une requête qui renvoie maintenant toujours `True`
> Tech: améliorations barre de navigation

- itou/templates/apply/includes/siae_batch_actions.html
- itou/templates/apply/includes/siae_batch_actions_modals.html
- itou/www/apply/views/list_views.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_list_for_siae.py
Il n'y a pas spécialement de raisons de ne pas le mettre là aussi vu l'homogénéisation des deux bandeaux d'actions.
> Candidatures: Permettre le transfert d'une candidature vers une autre structure depuis les actions par lot

- itou/utils/apis/pole_emploi.py
- tests/utils/apis/test_pole_emploi_api.py
Clarifier l’utilisation du client, améliorer ses performances et éviter de perdre de l’information via l’utilisation des exceptions « maison ».
> API Pole Emploi : Simplification

- itou/templates/apply/includes/geiq/check_geiq_eligibility_form.html
- itou/www/apply/views/common.py
- tests/www/apply/test_process.py
Petits correctifs préliminaires à #6732
> quality: corrections mineures

- itou/templates/apply/includes/list_view_switcher.html
- itou/www/apply/views/list_views.py
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_list.py
- tests/www/apply/test_list_for_job_seeker.py
- tests/www/apply/test_list_prescriptions.py
https://www.notion.so/gip-inclusion/Suivi-des-Candidatures-Activer-la-vue-tableau-par-d-faut-pour-tous-les-utilisateurs-25b5f321b60480f8bdb0dc04e2dbe8a3?v=18a5f321b604811bad80000cf7934cee&source=copy_link
> Interface: Activer la vue tableau par défaut pour tous les types d'utilisateurs

- itou/gps/management/commands/import_advisor_information.py
- tests/gps/test_management_commands.py
https://inclusion.sentry.io/issues/64493972/?referrer=github-pr-bot
> GPS: Correction du header du fichier importé 

- itou/files/admin.py
La modification est déjà impossible, la suppression non souhaitable et l'ajout plante.
https://inclusion.sentry.io/issues/64834254/?project=4508410589020240
> Admin: passage de l'admin des fichiers en lecture seule

- itou/utils/apis/pole_emploi.py
- itou/utils/mocks/pole_emploi.py
- tests/utils/apis/test_pole_emploi_api.py
Ajout d’un *mapping* pour les chemins de l’API, pour mieux lier leurs utilisations.
Organisation des réponses par chemin d’API pour les mutualiser et les retrouver.
> apis.pole_emploi: Réusinage et organisation des mocks

- itou/templates/dashboard/includes/stats/dgefp.html
- itou/templates/dashboard/includes/stats/sd_iae.html
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
https://www.notion.so/gip-inclusion/TB-SD-changer-les-titres-et-ordre-des-TB-dans-la-page-statistique-25d5f321b60480f7acf8ca5fedfca321?v=11611994512a48c7a87b7a366129364e&source=copy_link
> Pilotage : Changer les titres et ordre des TB pour les SD

- itou/users/admin.py
https://gip-inclusion.slack.com/archives/C01181Y04LT/p1759411968191659
> Admin: ajout de la date de création des diagnostics dans la vue des candidats

- itou/templates/layout/base.html
- itou/utils/context_processors.py
- tests/utils/__snapshots__/tests.ambr
- tests/utils/tests.py
> Statistiques: Ne plus envoyer à Matomo les urls qui nous sont inconnues

- tests/companies/factories.py
- tests/companies/test_management_commands.py
- tests/companies/test_models.py
- tests/eligibility/test_geiq.py
- tests/utils/tests.py
- tests/www/apply/test_edit.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/companies_views/test_card_views.py
- tests/www/dashboard/test_dashboard.py
- tests/www/dashboard/test_switch_organization.py
- tests/www/employee_record_views/test_create.py
- tests/www/employee_record_views/test_disable.py
- tests/www/employee_record_views/test_list.py
- tests/www/employee_record_views/test_reactivate.py
- tests/www/employee_record_views/test_summary.py
- tests/www/job_seekers_views/test_list.py
- tests/www/search_views/tests.py
- tests/www/signup/test_siae.py
There should be one-- and preferably only one --obvious way to do it.
> Tech: nettoyage des factories des entreprises

- config/settings/base.py
- itou/approvals/notifications.py
- itou/job_applications/notifications.py
- itou/job_applications/utils.py
- itou/templates/apply/email/refuse_body_for_job_seeker.txt
- itou/templates/approvals/email/prolongation_request/denied/jobseeker_body.txt
- tests/approvals/__snapshots__/test_notifications.ambr
- tests/approvals/test_notifications.py
- tests/approvals/test_prolongation_requests.py
- tests/companies/factories.py
- tests/job_applications/tests.py
- tests/prescribers/factories.py
Pour le partenariat.
Le retour de #3944 de @francoisfreitag :)
> Notifications: ajout du partenariat avec l'Afpa [GEN-2712]

- tests/utils/tests.py
> Tech: Amélioration d'un test 

- itou/metabase/tables/users.py
- tests/metabase/management/__snapshots__/test_populate_metabase_emplois.ambr
- tests/metabase/management/test_populate_metabase_emplois.py
> Pilotage: Ajout du sub ProConnect à la table des utilisateurs

- itou/common_apps/address/departments.py
- itou/www/stats/views.py
- tests/www/stats/test_views.py
> Technique: Nettoyage des urls envoyées à matomo dans les pages de stats

- itou/siae_evaluations/migrations/0003_evaluatedsiae_final_state.py
Elle a migré les données de prod comme attendu mais bloque l'ajout de nouveaux champs sur le modèle.
> Tech: nettoyage d'une migration de donnée
