gip-inclusion/les-emplois

itou/www/stats/views.py
The underlying query for this sum was lacking a filter
to exclude some edge cases like
JobApplication: ef6bfa6e-20fe-4522-a79b-536865fd91ee
JobApplication: 188fce6b-ce42-4e12-a8ee-2ff617cd4c3c
which have
sender_prescriber_organization__is_authorized=True
but
job_seeker__eligibility_diagnoses__author_kind <> 'prescriber'
Apparently this kind of job_application does exist, which means
that the diagnose can be made by some non-prescriber entity
despite the fact that the application's sender is a prescriber.
=> Fix stats page (job_applications_having_authorized_prescriber query)

itou/templates/apply/includes/job_applications_filters.html, itou/templates/apply/list_for_job_seeker.html, itou/templates/apply/list_for_prescriber.html, itou/templates/apply/list_for_siae.html, itou/templates/layout/base.html, itou/www/apply/forms.py, itou/www/apply/tests/tests_list.py, itou/www/apply/views/list_views.py
Filtres ajoutés aux tableaux de bord Prescripteur et Candidat : 
- date de création
- statut
Cette PR supprime également le bloc `modal` du gabarit `base` : il n'était utilisé que pour les filtres mais cette solution n'était pas la plus optimale.
=> Un candidat ou un prescripteur peut filtrer ses candidatures.

itou/static/css/itou.css, itou/templates/home/home.html, itou/templates/layout/base.html
=> Mise à jour de la page d'accueil

itou/templates/admin/approvals/manually_add_approval.html, itou/templates/apply/email/accept_trigger_approval_body.txt, itou/templates/apply/process_details.html, itou/templates/dashboard/dashboard.html, itou/templates/layout/base.html, itou/templates/siaes/edit_siae.html, itou/templates/signup/signup_siae.html, itou/www/prescribers_views/forms.py, itou/www/siaes_views/forms.py, itou/www/signup/forms.py
Remplacement de "SIAE" par "Employeur solidaire" ou "votre structure" sur le site. 
Cependant, les termes utilisés dans l'admin restent les mêmes.
=> Modification d'affichage du terme "SIAE"

itou/templates/approvals/approval_as_pdf.html, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/views.py
Si un agrément a été délivré par Pôle Emploi et qu'il n'existe pas de diagnostic en lien dans la base de données, considère que ce dernier a été fait par Pôle Emploi et qu'il est valide.
Ce patch permet de télécharger une attestation d'agrément même si son diagnostic n'existe pas.
=> Patch - Agrément de Pôle Emploi sans diagnostic

Makefile
Le pre-commit hook génère un fichier qui contient des `\n` au lieu de sauts de lignes *(comportement par défaut de `echo`)*.﻿
=> Fix pre-commit-hook dans le Makefile du projet

config/settings/base.py, config/settings/test.py
CachedStaticFilesStorage is deprecated.
Refs :
- https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#cachedstaticfilesstorage
- https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage
=> Use ManifestStaticFilesStorage instead of CachedStaticFilesStorage

itou/static/css/itou.css
En cas de non-completion du champ de recherche, le bouton est `disabled` mais son apparence reste normale﻿
=> Opacité du bouton de recherche

.github/workflows/review-apps.yml
Une recette jetable devrait être créée uniquement quand le label "review-app" est présent dans la PR.
=> Correction dans le processus de recettes jetables

itou/www/stats/views.py
Initial bug report from Pierre : https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1585820853006600
403 CSRF errors happen randomly in production when
trying to load stats page for a specific department.
I could not reproduce in local nor in staging, but my guess
is that the department selector form CSRF token being
cached in the general stats page is the culprit.
This is an attempt to fix cache vs csrf as found here
https://docs.djangoproject.com/en/3.0/ref/csrf/#caching
I have good hope this fixes things in production, at least
it does not cause any issue in local dev.
Si ça ne suffit pas alors ce sera carrément un `@csrf_exempt` vu que cette form n'est pas sensible (read only - ne change pas de data en db)
=> Attempt to fix random 403 errors on stats page

itou/static/css/itou.css
Un seul changement cette semaine : la correction d'un bug qui rendait les liens non cliquables s'ils étaient sur la même ligne que le bouton "Je donne mon avis".
=> Boost design

config/settings/base.py
Normalement c'est un truc que je fais au niveau de Nginx :
```
if ($http_host != inclusion.beta.gouv.fr) {
return 444;
}
```
Mais là chez Clever je ne suis pas certain qu'on puisse le faire… Du coup je propose de mettre ces alertes sous silence au niveau de l'applicatif. Votre avis ?
=> Silence `Invalid HTTP_HOST header` errors

itou/static/js/city_autocomplete_field.js
When submitting organization search form, all inputs of the form in the results page are filled, except the name.
=> Fixed organization name disappearing in search form

itou/templates/apply/process_base.html
Bug : l'agrément s'affiche après la rétractation d'une candidature si le demandeur d'emploi a un agrément encore valide.
Proposition : ne pas l'afficher si l'employeur a annulé l'embauche.
Pour reproduire le bug, considérons qu'un DE a deux candidatures acceptées et un agrément. L'une des deux est annulée. L'agrément s'affiche encore, mais sans le numéro.
Or l'employeur s'attend à ce que l'agrément ait été supprimé après la rétractation. Il ne devrait donc plus voir la section "Agrément existant".
A débattre ensemble : affiche-t-on l'agrément si la candidature est dans un autre état que "cancelled" ou pas ?
=> Modification de l'affichage d'un agrément sur une candidature

itou/templates/apply/includes/list_card_body.html, itou/templates/apply/process_details.html, itou/templates/dashboard/dashboard.html, itou/templates/stats/stats.html
Le tableau de bord des prescripteurs montre désormais si l'organisation est habilitée ou pas.
=> Mise à jour du tableau de bord Prescripteur Habilités

itou/job_applications/models.py
Le bouton permettant de télécharger l'attestation d'un PASS IAE ne s'affiche plus si la candidature peut être annulée.
=> Bouton "Télécharger l'attestation"

itou/prescribers/models.py, itou/siaes/models.py
Actuellement nous mettons en majuscule la première lettre de **chaque** mot présent dans le nom d'une organisation. Or cela pose quelques soucis d'ordre marketing. Par exemple, on n'écrit pas "Pôle Emploi" mais "Pole emploi". 
Cette PR propose de ne mettre en majuscules que le premier mot.
Il faut également mettre à jour le nom des organisations Pôle emploi pour ajouter l'accent circonflexe actuellement manquant.
```
from itou.prescribers.models import PrescriberOrganization
orgs = PrescriberOrganization.objects.filter(name__icontains="POLE EMPLOI")
for org in orgs:
org.name = org.name.replace("POLE EMPLOI", "Pôle emploi")
org.save()
```
=> Modification de l'affichage du nom des organisations

itou/templates/apply/process_accept.html, itou/templates/apply/process_details.html, itou/users/factories.py, itou/www/apply/forms.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Si une structure est soumise aux règles de éligibilité, elle doit renseigner l'adresse du candidat lorsqu'elle accepte sa candidature.
Cette adresse s'affiche également sur la page récapitulative d'une candidature.
La page d'acceptation d'une candidature commençant à être assez longue, j'ai modifié quelques éléments pour la rendre plus lisible.
=> Adresse obligatoire lors de l'acceptation d'une candidature

itou/utils/tests.py, itou/utils/validators.py, itou/utils/widgets.py, itou/www/apply/forms.py, itou/www/dashboard/forms.py
La date de naissance doit être postérieure à 1900.
Ajout de bornes dans la sélection des années du _datepicker_.
=> Ajout d'un contrôle sur la date de naissance

itou/static/js/matomo.js, itou/templates/search/siaes_search_results.html
Testons si les utilisateurs aimeraient voir les résultats de recherche sur une carte !
Le bouton ne s'affiche que s'il y a des résultats.
:information_source: Cette PR est liée à une expérimentation. [Lire la documentation à ce sujet](https://app.gitbook.com/@itou/s/equipe-itou/analyses-dusage-sur-matomo/mesurer-lattractivite-dune-nouvelle-fonctionnalite) ou [consulter la liste des événements](https://app.gitbook.com/@itou/s/equipe-itou/developpeurs/matomo/evenements).
=> Ajout d'un bouton "Voir la carte"

itou/prescribers/models.py, itou/templates/dashboard/dashboard.html, itou/templates/prescribers/email/must_validate_prescriber_organization_email_body.txt, itou/templates/prescribers/email/must_validate_prescriber_organization_email_subject.txt, itou/www/autocomplete/views.py, itou/www/dashboard/views.py, itou/www/signup/forms.py, itou/www/signup/tests.py
- Added notification email to support when there is a new prescriber org auth validation to be done
- Do not display code except for orienter (simpler)
- Updated dashboard for PE prescriber: hide the secret code (useless with SAFIR)
- Better filter for prescriber org autocomplete
=> Feedback habilitations prescripteurs

itou/templates/search/siaes_search_results.html
Les scripts JS (block `script`) du template `base.html` ne sont pas importés:
* plus d'autocomplétion dans la page des résultats de recherche
=> FIX: import des fichiers JS dans les résultats de recherche

config/settings/base.py, exports/readme.md, itou/approvals/admin.py, itou/approvals/management/commands/export_approvals.py, itou/templates/admin/approvals/change_list.html, itou/utils/exports/export_approvals.py
Permet d'exporter les PASS IAE en cours de validité vers un fichier Excel (format xlsx).
Peut-etre utilisé via:
- une commande d'admin Django: `manage.py export_approvals`
- le site d'admin (bouton dans la partie `objecttools`)
=> Export des PASS IAE vers un fichier Excel

itou/www/signup/forms.py, itou/www/signup/tests.py
L'e-mail des prescripteurs (tous types) n'est pas correctement testé pour les doublons dans le formulaire d'inscription.
=> FIX - Problème d'email à l'inscription des prescripteurs

config/settings/base.py, itou/job_applications/models.py, itou/templates/apply/email/accept_body.txt, itou/templates/apply/email/accept_subject.txt, itou/templates/apply/email/approval_number_body.txt, itou/templates/apply/email/approval_number_subject.txt
Les liens vers les formulaires Typeform sont ajoutés aux emails de:
* délivrance d'un PASS IAE
* confirmation d'embauche pour un prescripteur
=> Ajout des formulaires d'opinion Typeform dans certains emails

itou/templates/home/home.html, itou/templates/signup/signup.html
Petit fix qui empêche d'avoir le focus deux fois sur le même élément quand on navigue au clavier entre les éléments d'une page.
=> Use <a> tags instead of <button> inside <a>

config/settings/base.py, config/settings/demo.py, config/settings/dev.py.template, config/settings/prod.py, config/settings/review_apps.py, config/settings/staging.py, itou/templates/layout/base.html
On force la langue en FR façon boucher charcutier car 3 personnes m'ont fait la remarque d'une popup en EN quand bien même leur navigateur était configuré en EN 🤣 
J'ai un doute sur le fait de passer `ITOU_ENVIRONMENT` en variable d'environnement plutôt que de le hardcoder en dur dans chaque setting comme `ITOU_FQDN`.
@ikarius il y a une raison pour l'avoir passé en variable d'environnement ?
=> Hotjar fine tuning

itou/prescribers/admin.py, itou/siaes/admin.py
Dans les interfaces `SiaeAdmin` et `PrescriberOrganizationAdmin`, si on modifie un objet et qu'on détecte un changement d'adresse, alors on recalcule les coordonnées géographiques.
=> Admin : nouveau calcul des coordonnées géographiques

itou/approvals/admin.py, itou/eligibility/admin.py, itou/job_applications/admin.py, itou/prescribers/admin.py, itou/siaes/admin.py, itou/users/admin.py
Ajout de la possibilité de rechercher par ID dans l'admin pour :
- `Approval`
- `PoleEmploiApproval`
- `PrescriberOrganization`
- `Siae`
- `User`
+ `pk` VS `id`
=> Ajout de la possibilité de rechercher par ID dans l'admin

itou/templates/home/home.html, itou/templates/layout/base.html, itou/templates/search/prescribers_search_home.html, itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_home.html, itou/templates/search/siaes_search_results.html, itou/www/search/urls.py, itou/www/search/views.py
La liste de résultats des employeurs solidaires n'est pas assez visible à cause du gros bandeau.
On implémente une séparation de la recherche (SIAE et prescripteurs) en deux parties avec :
- une home + bandeau
- les résultats sans bandeau
=> Rendre plus visible les résultats de recherche

itou/eligibility/admin.py, itou/eligibility/factories.py, itou/eligibility/models.py, itou/eligibility/tests.py, itou/job_applications/models.py, itou/job_applications/tests.py, itou/templates/apply/process_details.html, itou/users/models.py, itou/users/tests.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/process_views.py, itou/www/apply/views/submit_views.py
Un diagnostic est désormais valable six mois après sa création. Si un employeur veut embaucher une personne après l'expiration du diagnostic, il doit en réaliser un nouveau.
=> Un diagnostic a une durée de vie limitée

itou/job_applications/models.py, itou/templates/apply/process_details.html, itou/templates/eligibility/includes/new_diagnosis_button.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Actuellement, une embauche qui a été reportée (étiquette "Embauche pour plus tard") ne permet que l'acceptation ou le refus de la candidature.
Or, si le diagnostic qui a été réalisé n'est plus valide (il date de plus de six mois), l'employeur devrait être en mesure de réaliser un nouveau diagnostic avant l'embauche.
Cette PR permet également le refus d'une candidature qui est en cours de traitement (`STATE_PROCESSING`), avant la validation des critères d'éligibilité.
=> Une embauche reportée doit permettre un nouveau diagnostic

itou/templates/layout/base.html
=> Ajout de liens vers YouTube et LinkedIn dans le footer

itou/templates/layout/base.html
En passant le consentement en haut ça devient un bandeau plutôt qu'une modale :
=> Déplacement du consentement des cookies en haut sur l'écran et dans le DOM

itou/www/invitations_views/forms.py
Actuellement, lorsqu'un utilisateur envoie un formulaire d'invitation vide [ce dernier est considéré comme valide](https://stackoverflow.com/a/16878132/3086625). Cela génère des erreurs qui remontent souvent dans Sentry.
Cette PR supprime cette possibilité, rendant le formulaire invalide s'il est vide.
=> Résolution d'un bug relatif au système d'invitations

requirements/dev.txt
Heureusement, c'était fixé dans une nouvelle release de django-extensions :)
> https://github.com/django-extensions/django-extensions/commit/5836b3aed316b44803c220cda858f06d38ebece1
=> Fix pour "exceptions must derive from BaseException error"

itou/www/invitations_views/forms.py
La correction que j'ai apportée au système des invitations lundi a généré un autre bug assez improbable.
Le formulaire d'invitation permet la modification d'invitations et non plus simplement leur création ! Cette PR permet de revenir au fonctionnement initial dans lequel seul l'envoi d'invitations est possible.
=> Fix bug in invitations

README.md, itou/utils/tests.py
Dans le but de détecter si le problème signalé par Mailjet vient de notre code.
Petit fix du README au passage.
=> Utilisation de `itou@example.com` plutôt que `test@example.com`

itou/eligibility/data/administrative_criteria.json
Demandeur d'emploi de longue durée (inscrit à Pôle emploi)
(et pas **très** longue durée)
donnée modifiée sur la DB de prod
=> Petit mot en trop dans la description du DELD

itou/external_data/apis/pe_connect.py, itou/external_data/apps.py, itou/external_data/signals.py, itou/external_data/tests.py, itou/www/dashboard/views.py, requirements/dev.txt
La partie qui traite de manière asynchrone l'import de données crashe à chaque fin d'opération (générant une erreur Sentry).
NB:  Cette erreur n'est pas visible par l'utilisateur, et les données sont correctement stockées.
=> Fix bug async en fin d'import

itou/www/apply/views/submit_views.py
Une portion de code obsolète est en place coté éligibilité, créant des erreurs 
- la propriété `user.job_seeker_data` n'existe pas (c'est `user.jobseekerexternaldata`),
- ce code n'a vraiment rien à faire là (oubli lors de tests).
(voir https://sentry.data.gouv.fr/itou/itou-prod-5t/issues/1885721/)
=> Erreur Sentry eligibilité - retrait de code

itou/templates/siaes/email/new_signup_activation_email_to_official_contact_body.txt, itou/templates/signup/signup_select_siae.html, itou/www/signup/forms.py, itou/www/signup/tests.py, itou/www/signup/views.py
Pour tester : 
SIAE qui a des membres : 
- type : EI
- SIRET : 34445638900016
SIAE qui n'a pas de membre : 
- type : ACI 
- SIRET : 87985594800011
Le message d'erreur est probablement à retravailler.
Messages Eric
=> Interdire l'accès de nouveaux utilisateurs aux structures qui ont déjà des membres 

itou/www/prescribers_views/forms.py
Afin de nous éviter d'avoir à le chercher nous-mêmes pour près de 300 organisations.
Un e-mail va être shooté en parallèle.
=> Ajout de la possibilité de renseigner le SIRET des organisations de prescripteurs

itou/utils/apis/api_entreprise.py, itou/utils/tests.py, itou/www/signup/forms.py
Fix pour les prescripteurs qui peuvent s'inscrire avec une organisation fermée, ce qui génère des doublons d'organisations.
=> On ne tient plus compte des SIRET fermés

itou/templates/apply/process_accept.html
Lors de la confirmation d'une candidature (juste avant l'acceptation), certaines SIAEs pouvaient voir une popup permettant d'obtenir un PASS IAE ou non.
Inapproprié pour EA, EATT, GEIQ
Trello:
https://trello.com/c/ET5alkir/836-un-geiq-peut-demander-%C3%A0-obtenir-un-pass-iae
=> [BOOST] Retirer le choix d'obtention d'un PASS IAE pour les structures non-éligibles au diagnostic

itou/prescribers/admin.py
Empêche une erreur 500 dans l'admin des organisations de prescripteurs quand un objet n'existe pas.
À la place on affiche un message d'erreur :
> Organisation avec l’identifiant « 1867 » n’existe pas. Peut-être a-t-il été supprimé ?
=> Fix une erreur 500 dans l'admin quand un objet n'existe pas

config/settings/base.py, itou/templates/stats/stats.html, itou/utils/apis/metabase.py, itou/www/stats/views.py
Les titres étaient auparavant inclus dans l'iframe metabase. 
Ils sont maintenant dans la view/template Django
Les filtres dynamiques pour les régions / départements sont en place (affichage personalisé, via filtres metabase)
=> Titre des dashboard Metabase externalisés

itou/utils/emails.py, itou/utils/iterators.py, itou/utils/tests.py
Si les champs:
* TO
* CC
* BCC
d'un e-mail contiennent plus de 50 éléments, l'API Mailjet refuse de les envoyer.
Seul le champ "TO" est découpé pour l'instant (pas de cas d'overflow des CC et BCC)
Ce draft découpe les éléments destinataires en bloc de 50 éléments max. et les dispatche dans plusieurs e-mails.
=> [BUG] Limite de 50 destinataires pour l'API mailjet

itou/templates/account/password_reset_done.html, itou/www/signup/tests.py, itou/www/signup/views.py
Objectif : permettre aux gens de voir qu'ils ont peut-être une typo dans leur email
=> Affichage de l'email saisi lors de l'oubli d'un mot de passe

itou/siaes/management/commands/_import_siae/siae.py, itou/siaes/management/commands/import_siae.py
`row.name` in pandas surprisingly returns an unexpected integer
instead of the siae name.
We fix that by using `row["name"]` instead,
and use a one time fix for the 20 or so affected siaes.
=> Fix incorrect siae.name for newly created siaes

itou/invitations/models.py, itou/templates/layout/base.html, itou/utils/perms/context_processors.py, itou/utils/perms/middleware.py, itou/utils/tests.py, itou/www/dashboard/urls.py, itou/www/dashboard/views.py, itou/www/invitations_views/forms.py, itou/www/invitations_views/tests/tests_prescriber_organization.py
Sur le modèle de ce qui a été fait pour les SIAE, les prescripteurs peuvent maintenant être rattachés à plusieurs organisations.
La sélection de l'organisation s'effectue à partir du dashboard.
Le système d'invitation a été légèrement modifié pour permettre les invitations entre prescripteurs (ayant des membres enregistrés).
=> Multi-organisation pour les prescripteurs

itou/www/apply/forms.py, itou/www/dashboard/forms.py
Before this fix, the widget was limiting the birthdate
even more than necessary.
For example :
maximum age is 16 years
today is October 19 2020
max birthdate should be October 19 2004
but the datepicker widget would limit to max birthdate January 1st 2004
=> Fix issue about birthdate in forms

itou/www/signup/forms.py
Une erreur 500 se produit dans le parcours d'inscription des prescripteurs quand une adresse ne parvient pas à être géolocalisée.
Pour le SIRET `48790347800021`, l'API SIRENE trouve cette adresse :
> 14 RUE NEUVE
> BATIMENT "ESPACE CAMBRESIS"
> BP 70318
> 59400 CAMBRAI
Or l'API BAN ne parvient pas à trouver une latitude/longitude pour cette adresse => ça se matérialise par une erreur 500.
C'est la partie BATIMENT "ESPACE CAMBRESIS" qui pose problème.
Ce fix propose de ne pas inclure cette partie dans les appels à l'API BAN.
=> Fix pour une erreur de geocoding lors de l'inscription d'un prescripteur

.github/pull_request_template.md
Proposition d'une aide à la rédaction de pull request.
L'objectif est d'homogénéiser notre façon de faire pour éviter d'avoir tantôt une description ou un titre manquant, tantôt une capture d'écran en guise de descriptions des changements.
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
=> Ajout d'un template de pull request

.github/workflows/review-app-creation.yml, .github/workflows/review-app-removal.yml
Les recettes jetables sont cassées suite à un changement de nom des instances. Cette PR répare cela.
=> Réparation des recettes jetables 

itou/templates/siaes/deactivate_member.html
Modification du template de confirmation du retrait d'un collaborateur pour une SIAE
Le template comporte des informations invalides (url / action)
=> [FIX] Problème de template dans la gestion des collaborateurs de SIAE

itou/prescribers/admin.py, itou/siaes/admin.py
Utilisation de `readonly_fields` pour ne pas subir la lenteur engendrée par la sélection de toutes les instances liées pour l’affichage dans la liste déroulante de l'admin.
Fixe un problème de performance dans l'admin.
=> Utilisation de `readonly_fields` sur certaines FK dans l'admin

itou/prescribers/admin.py, itou/siaes/admin.py, itou/users/admin.py
Utilisation de readonly_fields pour ne pas subir la lenteur engendrée par la sélection de toutes les instances liées pour l’affichage dans la liste déroulante de l'admin.
Fixe un problème de performance dans l'admin.
=> Utilisation de readonly_fields sur tous les MembersInline

.github/workflows/review-app-creation.yml, .github/workflows/review-app-removal.yml
Les recettes jetables sont cassées ! :scream: Cela est dû à [une évolution récente des actions GitHub](echo "$REVIEW_APP_NAME.cleverapps.io") qui déprécie les commandes `set-env` et `add-path`.
Cette PR remplace ces commandes par celles conseillées par GitHub.
=> Remise à flot des recettes jetables

itou/prescribers/admin.py, itou/siaes/admin.py, itou/siaes/management/commands/_import_siae/siae.py, itou/templates/dashboard/dashboard.html, itou/templates/layout/base.html, itou/utils/address/models.py, itou/www/prescribers_views/forms.py, itou/www/siaes_views/forms.py
1 - Une indication sur le type de structure est présente sur le dashboard et la liste de selection multistructure
2 - le complément d'adresse n'est plus utilisé pour le geocoding
1 -Les SIAE ou organisations de prescripteurs peuvent être plusieurs à avoir un même SIRET et un même nom (mais des types différents). 
On donne une indication plus claire de la structure de travail actuelle dans le dashboard et dans la liste de sélection.
2- Inclure systématiquement le complément d'adresse peut influer grandement sur le score de géocoding (et affecter les résultats de recherche)
=> [C1] Boost 

itou/prescribers/admin.py, itou/siaes/admin.py
Remplacement du widget de cartographie dans l'admin.
La carte (géoloc) dans l'interface d'admin est floue et pas trés utile.
=> Suppression des cartes dans l'admin des SIAE et des orgas de prescripteurs

itou/templates/layout/base.html
À l'ouverture du lien "Besoin d'aide ?" qui pointe vers la FAQ, le focus est mis dans le champ de recherche.
Le champ de recherche est difficilement visible sur la FAQ et il est impossible d'en modifier la présentation : les gens ne le trouvent pas.
En modifiant le lien externe en ajoutant `?q=` dans la _querystring_.
=> À l'ouverture du lien "Besoin d'aide ?" le focus est mis dans le champ de recherche

.github/workflows/ci.yml
La CI est cassée car les paquets ne s'installent pas correctement : la source n'est pas trouvée.
Il faut lancer `apt-get update` avant l'installation afin de rafraîchir la source.
=> Réparation de la CI

itou/invitations/models.py, itou/job_applications/models.py
Des e-mails d'une structure sont envoyés à tort à des destinataires erronés.
Des utilisateurs anciens membres d'une structure continuent de recevoir certains e-mails destinés aux membres **actifs** de cette structure (lors d'invitations de nouveau membres par ex.).
Il est nécessaire de filtrer sur le champs `active_members` et non `members` pour obtenir la liste correcte des destinataires.
=> Les anciens membres d'une structure recoivent encore certaines notifications par e-mail

itou/templates/apply/includes/job_applications_filters.html, itou/templates/layout/base.html, itou/templates/siaes/edit_siae.html, itou/www/apply/forms.py, itou/www/apply/tests/tests_list.py
Ils peuvent désormais filtrer les candidatures envoyées par structures destinataires.
Les employeurs peuvent désormais voir le SIRET de leur structure sur la page qui leur permet de mettre à jour leurs informations.
=> Modifications diverses de l'interface

itou/templates/layout/base.html, itou/templates/layout/content.html, itou/templates/prescribers/card.html, itou/templates/search/prescribers_search_home.html, itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_home.html, itou/www/search/views.py
Le moteur de recherche des prescripteurs devient public.
Itou est seul à posséder cette cartographie des prescripteurs. On décide de le mettre à disposition de tout le monde.
=> Le moteur de recherche des prescripteurs devient public

clevercloud/python.json, itou/users/management/commands/sync_group_and_perms.py
Ajout d'une commande pour gérer les groupes et les permissions.
Actuellement le groupe `itou-admin` (auquel est rattaché tous les membres Itou) est créé à la main dans les différents environnements. C'est assez pénible à configurer à la main dans l'interface d'admin de Django (c.f. _screenshot_) et on manque d'une vision d'ensemble.
Une nouvelle commande permet de créer et de synchroniser les permissions du groupe à chaque déploiement et sur tous les environnements :
```python
django-admin sync_group_and_perms
```
Elle permet aussi d'avoir une vue d'ensemble sur toutes les permissions dont dispose le groupe.
Il faut penser à la mettre à jour quand on ajoute des nouveaux modèles.
=> Ajout d'une commande pour gérer les groupes et les permissions

itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/_import_siae/vue_af.py, itou/siaes/management/commands/_import_siae/vue_structure.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py
Améliorations mineures des scripts d'import de structures
1) Détection automatique des noms de fichiers.
2) Attente de 7 jours avant de supprimer des GEIQ/EA crées par le staff et non plus suppression immédiate.
1) Pour simplifier les imports. Plus besoin d'un commit à chaque fois! Je vais MAJ la doc du repo privée aussi.
2) Sans ce changement, si une GEIQ/EA a été créée juste avant l'import, elle sera supprimée si personne ne s'y est encore inscrit. Avec ce changement, on donne 7 jours à la personne pour s'inscrire avant de virer sa structure.
=> Améliorations mineures des scripts d'import de structures

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/_import_siae/utils.py
- Problème majeur: les données du 4 janvier 2021 ne contiennent aucune AF pour 2021. Bref en théorie on devrait désactiver et mettre en période de grâce la totalité de nos structures o_O. Du coup ajout d'un switch pour gérer cette situation exceptionnelle qui se reproduira chaque année.
- Par convénience, il n'est plus nécessaire de dézipper les CSV de l'ASP
A l'occasion des données ASP du 4 janvier 2021.
=> Améliorations mineures du script d'import des SIAE

.github/workflows/ci.yml
On fait d'abord jouer Black, isort et Flake8 avant les tests unitaires.
La CI termine en échec plus rapidement quand il y a un problème de syntaxe ou de style.
=> Résultat de Black, isort et Flake8 avant les tests

itou/approvals/models.py, itou/approvals/tests.py, itou/templates/approvals/includes/status.html, itou/templates/approvals/includes/suspension_reason_alert.html, itou/templates/approvals/suspend.html, itou/templates/approvals/suspension_update.html, itou/utils/templatetags/call_method.py, itou/utils/tests.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/urls.py, itou/www/approvals_views/views.py
Nouvelle interface permettant de modifier une suspension.
Les gens se trompent parfois de date de début et de date de fin ou bien une suspension peut être raccourcie ou prolongée.
---
=> Ajout de la possibilité de modifier une suspension

requirements/dev.txt
Rétablissement de `tblib`.
Sans `tblib`, les [tests lancés en parallèle échouent](https://code.djangoproject.com/ticket/25497#comment:6).
=> Rétablissement de tblib

itou/fixtures/django/04_test_users.json, itou/job_applications/models.py, itou/templates/apply/process_details.html, itou/templates/dashboard/edit_job_seeker_info.html, itou/users/models.py, itou/users/tests.py, itou/www/dashboard/forms.py, itou/www/dashboard/tests.py, itou/www/dashboard/urls.py, itou/www/dashboard/views.py
Au niveau du code : 
- Modification du formulaire d'édition des informations utilisateur
- Ajout d'un bouton sur la page de détail d'une candidature
- Ajout d'une vue pour gérer la modification des informations d'un candidat par l'employeur
- Modification d'une donnée du jeu de test
µAu niveau fonctionnel : 
- Un employeur ne peut pas modifier les informations d'un candidat s'il est considéré comme "autonome", c'est-à-dire s'il s'est connecté de lui-même avec son compte, même si ce dernier a été créé par un tiers. 
- Le bouton permettant la modification apparaît si la candidature est en attente ou acceptée.
Les employeurs aimeraient modifier certaines informations sur leurs candidats car elles sont parfois erronées ou obsolètes.
En parallèle, les candidats aimeraient modifier leur prénom …
=> Modification des informations d'un candidat 

config/settings/base.py, config/settings/demo.py, config/settings/prod.py, config/settings/review_apps.py, config/settings/staging.py, itou/templates/account/email/email_confirmation_message.txt, itou/templates/account/email/password_reset_key_message.txt, itou/templates/approvals/includes/suspension_reason_alert.html, itou/templates/dashboard/dashboard.html, itou/templates/home/home.html, itou/templates/layout/base.html, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt, itou/templates/signup/includes/submit_rgpd.html, itou/templates/signup/prescriber_choose_kind.html, itou/utils/emails.py, itou/utils/settings_context_processors.py, itou/utils/tests.py
Migration vers `emploi.inclusion.beta.gouv.fr` depuis `inclusion.beta.gouv.fr`.
Pour libérer le nom de domaine `inclusion.beta.gouv.fr` qui deviendra une _landing page_ dans le but de clarifier la galaxie Itou.
=> Migration vers emploi.inclusion.beta.gouv.fr

config/settings/base.py, itou/utils/new_dns/middleware.py, itou/utils/new_dns/tests.py
Ajout d'un middleware pour gérer les redirections vers les nouveaux domaines.
Dans le cadre du chantier de stratégie d'identité commune ("Identité de la plateforme"), on décide de clarifier la proposition de valeur des produits ITOU auprès des différentes cibles touchées.
Par conséquent, les noms de domaines suivants changent :
- `inclusion.beta.gouv.fr` => `emplois.inclusion.beta.gouv.fr`
- `staging.inclusion.beta.gouv.fr` => `staging.emplois.inclusion.beta.gouv.fr`
- `demo.inclusion.beta.gouv.fr` => `demo.emplois.inclusion.beta.gouv.fr`
Après avoir tenté pas mal de trucs dont…
- une redirection au niveau d'AlwaysData qui ne gère pas les redirections HTTPS
- une redirection via une balise `meta http-equiv="refresh"` et GitHub pages qui ne prenait pas en compte les liens profonds
…il nous …
=> Ajout d'un middleware pour gérer les redirections vers les nouveaux domaines

itou/templates/layout/base.html, itou/utils/new_dns/middleware.py, itou/utils/new_dns/tests.py
Correctif pour afficher un message informatif à propos des nouveaux domaines
L'utilisation du framework dans le _middleware_ était téméraire et ne pouvait pas fonctionner.
On affiche le message dans le template de base en se basant sur l'en-tête `HTTP Referer`.
=> Correctif pour afficher un message informatif à propos des nouveaux domaines

itou/templates/layout/base.html
Fix pour afficher le message de changement de domaine.
Les navigateurs ne font pas transiter l'en-tête HTTP referer dans les redirections.
On affiche un message temporairement prévenant les usagers d'un changement de domaine uniquement quand il n'y a pas de referer, donc à chaque accès direct.
=> Fix pour afficher le message de changement de domaine

config/settings/prod.py, itou/utils/new_dns/middleware.py, itou/utils/new_dns/tests.py
Redirection de `emploi.inclusion.beta.gouv.fr` vers `emplois.inclusion.beta.gouv.fr` (avec un `S` à emplois)
On suppose que des personnes vont taper `emploi` sans `s` et on ne veut pas les perdre.
=> Redirection de emploi vers emplois (avec un S)

itou/metabase/management/commands/_job_applications.py, itou/templates/apply/includes/list_card_body.html, itou/templates/apply/process_base.html, itou/templates/apply/process_details.html, itou/templates/approvals/includes/status.html
Suppression de la mention "Agrément expiré" lorsqu'une candidature est envoyée par un prescripteur habilité pour un candidat dont l'agrément est en période de carence.
Lorsqu'un candidat avec agrément expiré a été envoyé par un prescripteur habilité, l'employeur reçoit la candidature avec la mention "Agrément expiré".
Il décline alors la candidature car il pense que l'embauche est impossible.
Or il lui suffit de valider l'embauche pour générer un nouveau Pass IAE.
On masque la mention "Agrément expiré" pour ne pas semer le doute dans la tête de l'employeur.
=> Suppression de la mention "Agrément expiré"

itou/approvals/export.py, itou/approvals/management/commands/export_approvals.py, requirements/base.txt
Modification et optimisation de l'utilitaire d'export des PASS IAE au format Excel.
L'utilisation de cet utilitaire via l'admin Django fige la plateforme (temps de rendu trop long)
N'impacte pas la génération via Management Command.
- optimisation du changement de la taille des cellules
- changement de la requête SQL, pas flagrant en temps de traitement mais plus lisible
- utilisation de fichiers temporaires au lieu de la méthode `save_virtual_workbook` (deprecated)
- ajout de `lxml` pour le rendering XLS (plus rapide)
Les tests en mode `WRITE_ONLY` sont non-concluants:
- vraiment plus lents pour la génération (petit gain au streaming toutefois)
- nécessite une modification du code
- bousille le formatage des cellules
A tester en staging / recette avec données, d'ou la présence des …
=> BUG: l'export XLS des PASS IAE freeze la plateforme

itou/www/apply/views/list_views.py
Correction de la requête qui affiche la liste des candidatures des prescripteurs
Un prescripteur voit :
1. toutes les candidatures dont il est à l'origine
1. toutes les candidatures de l'organisation à laquelle il est connecté
Le point **1** date d'avant la possibilité de faire partie de plusieurs organisations et corrige un problème qui se présentait quand l'utilisateur était orienteur sans organisation.
Dans cette configuration, lorsqu'un orienteur rejoignait une organisation, il ne voyait plus ses anciennes candidatures.
Mais avec le multi-organisations pour les prescripteurs, il voit maintenant toutes les candidatures dont il est à l'origine peu importe l'organisation dans laquelle il se trouve.
On s'assure de récupérer uniquement les anciennes candidatures dont le prescripteur est à …
=> Correction de la requête qui affiche la liste des candidatures des prescripteurs

itou/metabase/management/commands/_database_psycopg2.py, itou/metabase/management/commands/_database_sqlalchemy.py, itou/metabase/management/commands/populate_metabase.py, itou/metabase/management/commands/populate_metabase_fluxiae.py
Refactoring pour que le cronjob metabase nocturne `populate_metabase.py` retombe en marche, tout en continuant à n'installer `sqlalchemy` que en local dev et pas en production.
Le cronjob metabase nocturne a cassé la nuit dernière :
https://sentry.data.gouv.fr/itou/itou-prod-5t/issues/1896613/?referrer=alert_email
Cette PR sépare mieux le code `psycopg2` vs `sqlalchemy` ce qui fait que `populate_metabase.py` n'importe plus `sqlalchemy` (dont il n'a pas besoin).
=> Hotfix du cronjob metabase nocturne

requirements/base.txt
Passage de Django en version 3.1.6
MAJ de sécurité mineure. 
Détails ici: https://www.djangoproject.com/weblog/2021/feb/01/security-releases/
MAJ du fichier de requirements `base.txt`
=> MAJ sécurité Django 3.1.6

itou/templates/dashboard/dashboard.html
Un problème a affecté la transmission entre Typeform et notre plateforme. Affichons un message informatif sur le tableau de bord des employeurs.
=> Ajout d'un message sur le tableau de bord des employeurs

requirements/base.txt
Mise à jour de Django vers [la version 3.1.7](https://www.djangoproject.com/weblog/2021/feb/19/security-releases/).
=> Mise à jour de sécu de Django

itou/approvals/models.py, itou/job_applications/models.py, itou/templates/apply/edit_contract_start_date.html, itou/templates/apply/process_details.html, itou/www/apply/forms.py, itou/www/apply/tests/test_edit.py, itou/www/apply/urls.py, itou/www/apply/views/edit_views.py, itou/www/apply/views/process_views.py
Ajout de la possibilité de modifier la date de départ d'un contrat pour les SIAE si cette date est dans le futur.
Demande de notre support.
Les décalages de début de contrat sont fréquents et pas nécessairement le résultat d'une mauvaise saisie (gestion administrative, demande de décalage par le DE).
- ajout d'un formulaire de modification des dates de début et  de fin du contrat
- vérification et éventuel décalage de la date de départ si émission d'un PASS IAE pour la candidature
Détails candidature:
Formulaire de modification:
=> Possibilité de repousser la date de départ du contrat, si elle est dans le futur

.gitignore
Utilisation d'un chemin absolu (root) et slash final pour indiquer répertoire uniquement.
=> Ajout de .vscode à .gitignore

.github/workflows/ci.yml, Makefile, pyproject.toml
Le formateur de code Black est utilisé avec un paramètre spécifique concernant la longueur des lignes (119 au lieu de 88 par défaut), ce paramètre est actuellement passé en ligne de commande ou bien doit être configuré dans l'éditeur car il n'est pas lu depuis un fichier de conf de la base de code.
Pour éviter de devoir configurer son éditeur et simplifier l'appel en CLI.
Seul le fichier `pyproject.toml` est lu par Black. Nouveau fichier :(
---
Liens intéressant :
- https://black.readthedocs.io/en/stable/pyproject_toml.html
=> Set line length of Black in config file

itou/eligibility/models.py, itou/eligibility/tests.py, itou/job_applications/models.py, itou/job_applications/tests.py, itou/www/approvals_views/views.py
Ajout de la possibilité de télécharger l'attestation du PASS IAE même lorsqu'il est expiré.
Un prescripteur, une DIRECCTE (contrôle a posteriori) peut lui demander l'attestation du PASS IAE.
Si le PASS a expiré, l'employeur ne peut plus le télécharger et ne peut pas fournir l'attestation demandée.
Il a fallu modifier modifier la logique de récupération d'un diagnostic au passage.
Si le PASS IAE a expiré, il faut pouvoir chercher le diagnostic qui a permis de l'établir car un diagnostic plus récent peut exister.
=> Pouvoir télécharger l'attestation du PASS IAE même lorsqu'il est expiré

itou/templates/siaes/configure_jobs.html
Inversion des colonnes "ROME" et "Publier la fiche de poste".
Les boutons d'action devraient être regroupés dans la même zone de la page.
=> Employeurs > Configurer les fiches de poste : modification de l'interface

itou/metabase/management/commands/_job_seekers.py, requirements/dev.txt
Extract à la demande d'Eric pour la DGEFP qui veut préparer son premier contrôle a posteriori.
- le script `dgefp_control.py` est dans le repo privé et fait l'objet d'une PR là-bas : https://github.com/betagouv/itou-private/pull/20 <= à reviewer aussi svp 🙏 
- ajout d'une dépendance `xlwt` uniquement en local dev bien pratique pour exporter une dataframe dans un fichier excel en une ligne `df.to_excel("exports/dgefp_control.xls", index=False)`
- petit refactoring de code pour être réutilisé par le script `dgefp_control.py` (DNRY)
La requête était bien trop complexe pour être faite en SQL, notamment pour les 15 colonnes, 1 par critère administratif. J'ai donc saisi l'occasion de faire un script python one-shot et de documenter un petit workflow simple (voir le docstring en tête du script). …
=> Extract pour contrôle DGEFP

requirements/base.txt
Mise à jour de pandas depuis la version v1.0 vers la v1.2
L'installation de pandas v1.0 échoue dans Archlinux à jour au 2 mars 2021.
L'installation déclenche la compilation du paquet numpy et échoue car le code utilise du code obsolète:
```
numpy/random/mtrand/mtrand.c:45406:25: attention: « _PyUnicode_get_wstr_length » est obsolète [-Wdeprecated-declarations]
45406 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
```
Via pip !
La dernière version ne semble pas comporter de changements majeurs qui nécessite une migration de notre code.
---
Liens intéressant :
- https://pandas.pydata.org/docs/whatsnew/v1.2.0.html
=> Mise à jour vers pandas v1.2

itou/asp/tests.py
Pour obtenir un résultat fiable, le patch défini explicitement l'adresse du `JobSeeker`.
Le test faisait aussi appel à l'API géo car celui ci n'était pas mocké certainement parce qu'il était prévu pour qu'il échoue avant l'appel de l'API, j'ai donc mocké tous les tests.
Pour éviter avoir un build stable et pouvoir le lancer hors ligne.
En appliquant le mock au niveau de la classe.
Remarque, je ne suis pas certain du but initial de ce test.
Les 2 premiers commits de cet PR doivent ignorés (en attente de merge).
=> Le test de format_address avec factory échoue parfois

itou/job_applications/models.py, itou/job_applications/tests.py, itou/www/apply/views/submit_views.py
Suppression du délai d'1h avant de pouvoir repositionner un candidat pour les SIAE.
Car il est impossible pour une SIAE de repositionner un candidat pour qui elle aurait décliné une candidature par erreur.
À l'origine on avait toujours un délai arbitraire de 24 heures avant de pouvoir repositionner un candidat.
Un contrôle côté serveur permettant d'empêcher la double soumission de formulaire était basé sur la même valeur.
On fait passer ce contrôle côté serveur à 10 secondes.
=> Suppression du délai d'1h avant de pouvoir repositionner un candidat en tant que SIAE

itou/cities/admin.py
Utilisation de `OSMWidget` à la place de `OpenLayersWidget` pour afficher une carte plus pratique dans l'admin des villes.
Pour pouvoir changer les coordonnées de Berre-l'Étang sans avoir à faire une requête SQL ou avoir à formater les données pour pouvoir peupler un `PointField`.
=> Utilisation d'une carte plus pratique dans l'admin des villes

itou/templates/apply/list_for_siae.html, itou/templates/apply/process_base.html, itou/templates/dashboard/dashboard.html, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/views.py
Réactivation de PDF Shift.
PDF Shift a terminé sa migration depuis OVH vers AWS.
On réactive comme avant, la gestion du timeout viendra dans les jours qui suivent.
=> Réactivation de PDF Shift 

itou/siaes/management/commands/_import_siae/financial_annex.py
Prise en compte d'un changement de date de fin d'annexe financière.
Lors de l'import des données ASP, la date de fin d'une annexe financière peut changer. Nous devons prendre en compte ce changement.
=> Prise en compte d'un changement de date de fin d'annexe financière

itou/job_applications/models.py, itou/job_applications/tests.py, itou/templates/apply/includes/list_card_header.html
Mise à jour de l'interface des prescripteurs et des employeurs et plus précisément de leur liste de candidatures.
Beaucoup de candidatures sont non traitées par les SIAE (pour plus de détails, voir la carte sur Trello). Nous voulons inciter les prescripteurs à relancer les employeurs quand les candidatures n'ont pas reçu de réponse depuis trop longtemps.
Une candidature est considérée comme trop vieille si elle n'a pas reçu de réponse depuis trois semaines. La "réponse" est le dernier log de transition.
Sur le tableau de bord Prescripteur et Employeur, ajout d'une phrase pour chaque candidature si les conditions suivantes sont remplies : 
- le dernier changement de statut a été effectué il y a plus de trois semaines
- elle est "en attente" : nouvelle, à l'étude ou pour plus tard.
=> Mise en avant des candidatures sans activité depuis plus de 3 semaines

itou/job_applications/factories.py, itou/job_applications/models.py, itou/job_applications/tests.py, itou/siaes/factories.py, itou/siaes/models.py, itou/siaes/tests.py, itou/templates/search/siaes_search_results.html
Affichage d'un message informatif dans la recherche employeurs si une fiche de poste a reçu plus de 20 candidatures. Cette limite étant une variable de la classe `SiaeJobDescription`, elle sera donc facilement modifiable.
Les candidats et prescripteurs envoient des candidatures sans savoir que l'employeur en a déjà reçu beaucoup trop.   
Nous ajoutons également un `Manager` au modèle `SiaeJobDescription` afin de pouvoir annoter des `querysets` de manière lisible.
Cette PR ne génère qu'une requête de plus : il y en avant 9 avant contre 10 maintenant.
=> Afficher un message si une fiche de poste a déjà reçu beaucoup de candidatures

itou/prescribers/admin.py, itou/prescribers/admin_forms.py, itou/siaes/admin.py, itou/siaes/admin_forms.py
Pouvoir supprimer le _geocoding_ dans l'admin des SIAE et des organisations de prescripteurs.
Le support se sert de cette fonctionnalité pour supprimer une organisation de la liste des résultats de recherche.
J'en profite au passage pour couvrir tous les cas d'usage possible dans l'admin :
- pouvoir explicitement demander un re-calcul du _geocoding_ (ou changer une adresse sans le modifier)
- pouvoir déplacer à la main la localisation pour du _fine tuning_ en affichant une carte
- pouvoir supprimer les coordonnées
_Bonus track_: le score du _geocoding_ passe en read-only
=> Pouvoir supprimer le geocoding dans l'admin

itou/templates/approvals/includes/status.html
Rendre visible les infos du PASS IAE lorsqu'il est expiré.
Dès que le PASS est expiré, l'employeur ne peut plus voir les dates et informations liées à ce PASS. 
Ce comportement date de la PR #530 dans laquelle on a décidé de faire disparaitre la mention "agrément expiré" si la candidature est envoyée par un prescripteur habilité pour ne pas semer le doute dans la tête de l'employeur.
Il manquait une condition : que la candidature soit toujours en attente de traitement.
Dans tous les autres cas, il faut afficher la mention "expiré" avec les dates de début et de fin du PASS IAE.
=> Rendre visible les infos du PASS IAE lorsqu'il est expiré

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests.py, itou/eligibility/models.py, itou/fixtures/django/12_pe_approvals.json, itou/templates/approvals/includes/status.html, itou/www/apply/tests/tests_submit.py
Lors de l'import des agréments en provenance de Pôle emploi, nous n'appliquons pas la prolongation COVID et celle-ci n'est pas intégrée aux données que nous recevons. Nous l'appliquons lors de la transformation d'un agrément en PASS IAE.
Mais une étape en amont fausse le processus : la récupération des agréments valides. En effet, un agrément expiré mais qui pourrait bénéficier de la prolongation COVID est considéré comme invalide car sa date de fin n'a pas encore été mise à jour. 
Le processus dans le code :
- Récupération du dernier agrément à prendre en compte : `Approval.get_or_create_from_valid(approvals_wrapper)`
- Dans `get_or_create_from_valid`, le système transforme un agrément existant s'il est considéré valide. Il n'est pas valide, car il est expiré.
- S'il n'était pas expiré, …
=> Des agréments Pôle emploi sont expirés alors qu'ils devraient bénéficier de la prolongation COVID

itou/utils/apis/metabase.py
Répare la page /stats
Suite à la mise à jour de PyJWT en version 2.0.1, les tokens retournés par `jwt.encode()` sont au format `string` VS `byte string`.
Suppression de `.decode("utf8")`.
=> Répare la page /stats

itou/metabase/management/commands/_database_sqlalchemy.py, itou/metabase/management/commands/populate_metabase_fluxiae.py
Amélioration de l'import fluxIAE dans metabase.
Nous avons identifié que 6 missions EHPAD présentes dans la vue fluxIAE étaient absentes de la db metabase.
Après investigation, il s'avère que ces 6 lignes ont été ignorées par `populate_metabase_fluxiae.py` car malformées e.g. ayant des `"` dans les champs.
=> Amélioration de l'import fluxIAE

itou/users/models.py, itou/users/tests.py, itou/www/signup/forms.py, itou/www/signup/tests.py
Remplacement de `allauth.utils.generate_unique_username()` par `uuid4()`.
Le champ [`User.username`](https://docs.djangoproject.com/fr/3.1/ref/contrib/auth/#django.contrib.auth.models.User.username) fait partie du modèle de base de `django.contrib.auth`. Il n'est pas utilisé dans Itou mais il reste nécessaire dans certaines méthodes comme [`create_user`](https://docs.djangoproject.com/fr/3.1/ref/contrib/auth/#django.contrib.auth.models.UserManager.create_user) utilisé [par ici](https://github.com/betagouv/itou/blob/2c1ff02aa379165de6e2b3cc47f602df0e9e0662/itou/users/models.py#L274)…
On utilise `allauth.utils.generate_unique_username()` pour générer une valeur _human-readable_.
Mais ça génère masse d'erreurs sur Sentry :
> https://sentry.io/organizations/itou/issues/2291675609/events/3cd606 …
=> Remplacement de `generate_unique_username`

Makefile, requirements/dev.txt
Nouvelle dépendance de dev sur `coverage` et nouvelles règles pour le Makefile.
J'ai aussi testé vite fait le plugin de coverage pour les templates Django mais le projet n'est pas très actif et je ne suis pas sûr de l'utilité donc je ne l'ai pas inclus.
Pour savoir ce que l'on ne teste pas.
L'outil fournit une jolie sortie HTML/JS pour consulter tout cela.
=> Ajoute un outil d'analyse de couverture de code par les tests

config/settings/base.py, itou/templates/approvals/approval_as_pdf.html, itou/templates/approvals/email/new_prolongation_for_prescriber_body.txt, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt, itou/templates/signup/siae_select.html, itou/utils/emails.py, itou/utils/settings_context_processors.py, itou/www/approvals_views/views.py, itou/www/siaes_views/forms.py, itou/www/siaes_views/tests.py
Replacement de l’email direct d’assistance par [le portail assistance](https://assistance.inclusion.beta.gouv.fr) dans toute l’application.
Pour favoriser l’utilisation du portail et ainsi simplifier la gestion des tickets support.
J’ai remplacé l’email direct d’assistance par [le portail assistance](https://assistance.inclusion.beta.gouv.fr) dans toute l’application :
- emails
- PDF du Pass
- formulaires siae (siret incorrect au signup et à la création)
Le signup, mais c’est pareil partout :
=> Replacement de l’email d’assistance par le portail assistance

itou/approvals/models.py
[Ce test](https://github.com/betagouv/itou/pull/612#issuecomment-810881174) échoue depuis ce matin alors qu'il fonctionnait hier. 
Prenons ces deux exemples : 
```python
from dateutil.relativedelta import relativedelta
date_one = datetime.date(2021, 4, 30)
date_two = datetime.date(2021, 5, 30)
date_one - date_two
relativedelta(date_one, date_two)
date_one = datetime.date(2021, 4, 30)
date_two = datetime.date(2021, 5, 31)
date_one - date_two
relativedelta(date_one, date_two)
```
`relativedelta` ne se trompe pas mais cela fausse notre calcul, car le PASS IAE est censé se terminer 2 ans - 1 jour après sa date de début. Si on modifie la date de fin en soustrayant un mois, il peut arriver (et c'est le cas dans ce test) qu'on rajoute un jour sans le vouloir.
Utilisons plutôt `datetime`.
=> Correction d'un bogue quand la date de début d'un PASS est recalculée

itou/allauth_adapters/peamu/adapter.py, itou/allauth_adapters/peamu/tests.py, itou/external_data/apis/pe_connect.py, itou/external_data/models.py, itou/external_data/signals.py, itou/external_data/tasks.py, itou/external_data/tests.py, itou/www/dashboard/views.py
Réduction du nombre de requêtes SQL à l'import PE.
Parce que moins de requêtes c'est mieux, pardi !
En passant l'instance de l'ORM en argument ou en utilisant la même query pour 2 tests, etc.
Au passage, quelques modifications concernant des remarques de pylint :
- les appels du logger doivent être lazy (pas de formatage des args sinon les loggers ne peuvent pas regrouper les messages)
- j'ai essayé de clarifier les noms de variables/fonctions, pas sûr d'y être vraiment parvenu, avec une table nommée ExternalDataImport, je ne suis pas aidé !
Seul le dernier commit de cette PR est intéressant (cette PR est dépendante d'une autre).
=> Réduction du nombre de requêtes SQL à l'import PE

Makefile, itou/prescribers/admin.py, itou/templates/admin/prescribers/change_form.html, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt
Dans l'interface d'administration, il est uniquement possible de modifier l'habilitation 
d'un organisation quand l'état est soit `pending` ou `refused` mais nous avons des
demandes du support (https://trello.com/c/vDyFd00M/1622-accorder-habilitation-%C3%A0-une-orga, https://trello.com/c/DR0IRF4Z/1621-retirer-habilitation-%C3%A0-une-orga) en dehors de ces cas.
Accès à ses actions dans tous les cas pour les super utilisateurs.
Pour éviter d'avoir à faire la manip depuis le shell Django de la prod.
En vérifiant le rôle de l'utilisateur dans le template de l'admin.
Au passage, **il était et il est** encore possible d'effectuer l'action sans être super utilisateur car il n'y a pas de check au niveau de `response_change` :
https://github.com/betagouv/itou/blob/master/itou/prescribers/admin.py#L …
=> Autoriser le super utilisateur à modifier l'état d'une habilitation

itou/fixtures/django/07_confirmed_emails.json
Mise à jour des données de test.
Certains comptes test sont inutilisables car leurs adresses électroniques n'ont pas été vérifiées.
=> Réparation des comptes tests

clevercloud/demo-after-success.sh, clevercloud/review-app-after-success.sh
Correction de la commande qui peuple la table Cities en recette jetable.
Nous avons mis à jour l'export SQL de la table Cities ainsi que la commande qui l'importe en DEV. Nous avons oublié de la reporter en recette jetable.
=> Correction des données de test en recette jetable

.coveragerc, Makefile
Exclus les migrations du coverage.
Car cela génère du bruit dans les rapports.
Ajout d'un fichier .coverage.rc et suppression du paramètre explicite dans le Makefile.
=> Ajustements des réglages pour coverage.py

itou/templates/apply/process_details.html
Les critères des candidatures envoyées par des **prescripteurs habilités** ne sont pas affichés de manière hiérarchisée afin de ne pas induire les employeurs en erreur au sujet des critères.
On ne touche pas à l'affichage des autres candidatures.        
Avec des critères hiérarchisés, ils ont tendance à penser que le candidat n'est pas éligible car pas suffisamment de critère de niveau 2 par exemple
Affichage spécifique dans ce cas précis.
J’ai hésité à extraire le code dans un include, car `itou/templates/apply/process_details.html` commence à devenir bien touffu. Je ne l’ai pas fait car j’ai l’impression que ce n’est ni réutilisable, ni trop la pratique dans l’équipe de découper les gros templates.
=> Affichage spécifique des critères d’éligibilité pour les candidatures envoyées par des prescripteurs habilités

itou/siaes/admin.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py
1. ajout de la colonne date de création qui permet au support de voir en clin d'oeil dans l'admin quelles et combien de structures ont été rajoutée dans les derniers imports
2. clarification du log de la suppression des EA/EATT/GEIQ
3. conversion des EA/EATT/GEIQ existantes quand elles sont trouvées dans l'export officiel postérieurement à leur création par le support et/ou l'employeur
A la demande de Sarah.
=> Améliorations mineures pour la gestion des EA/EATT/GEIQ par le support

itou/prescribers/models.py, itou/templates/common/emails/add_admin_email_body.txt, itou/templates/common/emails/add_admin_email_subject.txt, itou/templates/common/emails/member_deactivation_email_body.txt, itou/templates/common/emails/member_deactivation_email_subject.txt, itou/templates/common/emails/remove_admin_email_body.txt, itou/templates/common/emails/remove_admin_email_subject.txt, itou/www/prescribers_views/tests.py, itou/www/siaes_views/tests.py
Les sujets d’emails ne contiennent pas les noms des siae et prescripteurs.
Excellente question ! Je n’ai pas trouvé à 100%, mais:
- les tests automatisés ne testaient pas suffisament les chaines à vérifier, et donc il ne détectaient pas l’erreur
- pour une raison qui m’échappe, dans `translate` et `blocktranslate`, les `@property` sont mal remplacées (chaine vide, pas d’exception levée). L’objet est pourtant bien transmis, les attributs sont eux, bien affichés : on affiche correctement `siae.kind`, mais `siae.display_name` est une chaine vide.
- On peut tricher. Ainsi:
```jinja
{# chaine vide #}
{% blocktranslate %}
organization.display_name
{% endblocktranslate %}
```
mais 
```jinja
{# remplacement correct #}
{% blocktranslate with org_name=organization.display_name %}
org_name
{% …
```
=> Fix email content

config/settings/base.py, itou/allauth_adapters/peamu/urls.py, itou/api/apps.py, itou/approvals/apps.py, itou/asp/__init__.py, itou/cities/apps.py, itou/eligibility/apps.py, itou/external_data/tests.py, itou/invitations/apps.py, itou/job_applications/apps.py, itou/jobs/apps.py, itou/prescribers/apps.py, itou/siaes/apps.py, itou/users/apps.py, itou/www/apply/apps.py, itou/www/approvals_views/apps.py, itou/www/autocomplete/apps.py, itou/www/dashboard/apps.py, itou/www/eligibility_views/apps.py, itou/www/home/apps.py, itou/www/invitations_views/apps.py, itou/www/prescribers_views/apps.py, itou/www/search/apps.py, itou/www/siaes_views/apps.py, itou/www/signup/apps.py, itou/www/stats/apps.py, itou/www/welcoming_tour/apps.py, requirements/base.txt, requirements/dev.txt
Mise à jour vers [Django 3.2](https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys).
Et en même temps de la [Django Debug Toolbar](https://www.djangoproject.com/weblog/2021/apr/14/debug-toolbar-security-releases/).
- de nouvelles fonctionnalités et améliorations sont ajoutées
- des bogues sont corrigés
- les anciennes versions de Django finiront par ne plus recevoir de mises à jour de sécurité
- la mise à jour de chaque nouvelle version de Django rend les mises à jour futures moins pénibles
> https://docs.djangoproject.com/en/3.2/howto/upgrade-version/
Il reste un _warning_ un tout petit peu inquiétant :
```
/usr/local/lib/python3.9/site-packages/xworkflows/compat.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead …
```
=> Mise à jour vers Django 3.2

itou/www/invitations_views/forms.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/signup/tests.py
Bugfix : "Unable to find a unique username".
Toujours le même bug dans Allauth qui n'était pas adressé dans la partie "Invitations".
Au passage j'ajoute un commentaire que je trouve plus clair.
=> Bugfix : "Unable to find a unique username"

itou/templates/approvals/declare_prolongation.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/tests.py
Bugfix : un ACI ne peut pas utiliser le motif de prolongation "difficultés particulières".
La validation de Model (`Model.full_clean()`) est déclenchée à l’intérieur de l’étape de validation de formulaire, juste après l’appel à la méthode `clean()` du formulaire.
La majeure partie de la logique de validation des prolongations est implémentée et testée dans `Prolongation.clean()`.
Or il manquait une propriété dans le form `declared_by_siae` pour dérouler la validation proprement.
Cette erreur est couverte par un test.
=> Bugfix : un ACI ne peut pas utiliser le motif de prolongation "difficultés particulières"

itou/www/dashboard/forms.py, itou/www/dashboard/tests.py
Possibilité, pour les professionnels, d’éditer l’email d’un demandeur (tant que l’email n’est pas confirmé).
Les professionnels ne peuvent pas modifier l'adresse email du candidat
Ajout de l’email dans le formulaire d’édition d’un utilisateur, dans les cas concernés.
=> Possibilité d’éditer l’email d’un demandeur (tant que l’email n’est pas confirmé)

config/settings/base.py, itou/utils/nav_history.py, itou/www/apply/views/submit_views.py, itou/www/signup/views.py
Suppression de `SESSION_SAVE_EVERY_REQUEST`.
Le setting a été installé pendant la phase de réalisation du prototype pour gagner du temps.
Mais il force Django à enregistrer la session dans la base de données lors de chaque requête, même quand la session n'est pas manipulée.
Ça génère beaucoup d'écritures inutiles en base de données.
Avec `request.session.modified = True` quand c'est nécessaire pour gérer le dernier cas de la doc :
> https://docs.djangoproject.com/en/3.1/topics/http/sessions/#when-sessions-are-saved
```python
request.session['foo'] = 'bar'
del request.session['foo']
request.session['foo'] = {}
request.session['foo']['bar'] = 'baz'
```
=> Suppression de `SESSION_SAVE_EVERY_REQUEST`

itou/templates/dashboard/dashboard.html
Ouverture de l'interface "Mes AF" à tous les employeurs.
La première MEP ce lundi ne montrait cette interface qu'à la minorité de structures inactives, pour mitiger le risque d'une surcharge du support. Ce jeudi Sarah affirme qu'il n'y pas eu de surcharge, donc go on peut passer à cette seconde étape d'ouvrir à tous les employeurs.
=> Ouverture de l'interface "Mes AF" à tous les employeurs

itou/templates/dashboard/dashboard.html
Le titre et la description sont en français et au format texte.
Ajout d’un lien dans le dashboard des utilisateurs de type "employeur" vers une invitation à remplir un typeform dans lequel on demande à la structure d'indiquer les secteurs d'activité sur lesquelles elle intervient.
Pour connaître l'activité commerciale des employeurs pour le c4
Un encart dédié, cf capture d’écran.
=> Ajout d’un lien vers le Typeform "secteur d’activité employeurs"

.github/workflows/deploy.yaml
Mise en place d’un bouton pour déployer en production depuis Github.
Pour éviter de faire les choses:
- à la main depuis une console, ce qui peut être source d’erreur
- depuis son environnement local, qui peut être dans un état incohérent
Ajout d’une github action dédiée.
On peut déployer en production:
- en allant dans les [github actions du projet](https://github.com/betagouv/itou/actions).
- en choisissant "Deploy to production" -> "Run workflow" -> "Run"
La branche source n’a pas d’importance (pas trouvé comment le virer, pa).
Les utilisateurs de [Github CLI](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-using-github-cli) peuvent également déployer depuis un terminal via `gh workflow run deploy.yml`
Note:
dans mon test, j’ai …
=> Ajout d’un bouton de déploiment vers la production

itou/templates/apply/includes/info_csv.html
Changement de texte + redirection vers la doc
Le texte est à la fois pas assez détaillé pour des gens qui ne connaissent pas, et un peu long, il alourdit l’écran.
=> Modification de la notice pour ouvrir les exports CSV

itou/templates/dashboard/dashboard.html, itou/utils/apis/geocoding.py, itou/www/signup/forms.py
Correctif pour l'erreur `GEOSException` qui empêche des prescripteurs de pouvoir s'inscrire.
Dans le tunnel d'inscription des prescripteurs, on tente de récupérer automatiquement des informations de geocoding. Quand il n'y en a pas, PostGIS déclenche une erreur `GEOSException` car il manque les informations de latitude et de longitude.
On rend les informations de latitude et de longitude optionnelles et on affiche un message d'alerte sur le tableau de bord quand leur absence peut avoir des conséquences dans les résultats de recherche.
- ajout de doc
- changement de niveau du logging des erreurs de geocoding
=> Correctif pour l'erreur GEOSException

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/import_siae.py
- ajout d'erreurs fatales cassantes pour forcer supportix à resoudre manuellement certains edge cases
- résolution de edge cases variés rencontrés sur les dernières semaines
- ajout d'assertions variées pour détecter le plus en amont possible certains problèmes de données
Maintenant que c'est supportix qui fait tourner le script, il convient que certains warnings deviennent cassants pour une résolution manuelle par supportix.
=> Amélioration du script import_siae.py pour Supportix

itou/approvals/admin_forms.py, itou/approvals/tests.py
On laisse la possibilité de modifier un PASS IAE existant dans l'admin.
Pour pouvoir modifier ses dates, mais sans donner la possibilité de modifier le numéro déjà attribué.
Sans ça, le support ne peut plus faire de rétroactivité ou prendre en comptes les régulations demandées par les utilisateurs.
=> Possibilité de modifier un PASS IAE existant dans l'admin

itou/approvals/models.py, itou/approvals/tests.py
Ajout d'un contrôle de la date de début d'une prolongation dans l'admin.
Ce contrôle existe côté interface SIAE. Or il n'est pas présent dans l'admin.
Ajout du contrôle dans `Prolongation.clean()` de sorte qu'il soit toujours appelé en sortie d'un `ModelForm` (front ou admin).
=> Ajout d'un contrôle de la date de début d'une prolongation dans l'admin

itou/approvals/admin_forms.py, itou/templates/dashboard/dashboard.html, itou/templates/search/siaes_search_results.html, requirements/base.txt
Mise en avant du forum sur le tableau de bord.
Pour donner un coup de boost à l'acquisition du chantier de la communauté.
Ajout d'une mise en avant visuelle en haut du tableau de bord (ça fait un peu CDiscount mais c'est validé).
- la mise en avant du C4 passe en haut aussi
- homogénéisation du balisage HTML des mises en avant
- retrait de lien vers le sondage sur la page des résultats de recherche SIAE
- correctif d'une condition moisie de mon fait
- mise à jour de [sécurité de Django 3.2.1](https://www.djangoproject.com/weblog/2021/may/04/security-releases/)
=> Mise en avant du forum sur le tableau de bord

CHANGELOG.md, config/urls.py, itou/templates/layout/base.html, itou/templates/releases/list.html, itou/www/releases/tests.py, itou/www/releases/urls.py, itou/www/releases/views.py, requirements/base.txt
https://trello.com/c/7LF4V9oE/1581-c1-cr%C3%A9er-la-page-%C3%A9volutions-et-y-mettre-le-changelog-github
Nouvelle vue qui affiche le markdown de CHANGELOG.md en HTML.
Pour que le monde entier soit informé des changements effectués sur notre base de code dans un langage non technique.
En mettant un lien qui donne envie de cliquer dessus dans le pied de page.
Avec un petit cache pour tenir la charge sur hackernews.
=> Publication des notes de version

itou/approvals/admin_views.py, itou/external_data/apis/pe_connect.py, itou/job_applications/models.py, itou/users/models.py, itou/users/tests.py, itou/www/apply/views/process_views.py, itou/www/approvals_views/views.py, itou/www/dashboard/views.py, itou/www/invitations_views/views.py, itou/www/prescribers_views/views.py, itou/www/siaes_views/forms.py, itou/www/siaes_views/views.py, itou/www/signup/forms.py
Ouvre des contextes transactions dans les vues ou les *management commands* quand
plusieurs objets liés doivent être enregistrés de manière atomique.
Pour conserver la cohérence des données métiers si une erreur survient durant le traitement de la requête (vue).
En utilisant `with transaction.atomic()` avec une granularité fine mais toujours au niveau de la vue.
=> Ajout des transactions aux enregistrements interdépendants

itou/utils/perms/middleware.py
Changement de comportement du middleware.
Pour éviter une écriture transactionnelle à chaque requête HTTP.
En testant l'existence de la valeur en session.
Le commentaire initial du code ne faisait pas ce qu'il disait.
=> Défini seulement l'orga du prescripteur quand non définie

requirements/base.txt
Mise à jour vers Django 3.2.2
> https://www.djangoproject.com/weblog/2021/may/06/security-releases/
=> Mise à jour vers Django 3.2.2

itou/templates/apply/list_of_available_exports.html
Changement de l'affichage des noms de mois.
Clarté.
Je trouve bancale le formatage « M » pour les noms courts, je trouve que « N » est meilleur.
=> Affichage complet des mois

config/settings/base.py, itou/approvals/models.py, itou/utils/tests.py, itou/utils/urls.py, itou/www/apply/views/process_views.py, itou/www/siaes_views/forms.py
Ajout d'un  lien vers la documentation quand un candidat est en période de carence dans le message affiché aux orienteurs et aux employeurs.
Demande du métier pour être plus explicite.
Proposition de factorisation de la génération du HTML des liens utilisés dans le code Python pour viser l'homogénéité et l'accessibilité.
=> Ajout d'un lien vers la doc

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/models.py, itou/siaes/tests.py, itou/templates/search/siaes_search_results.html, itou/www/search/views.py
Hotfix des ACIPHC créees par le support.
Normalement le support devrait créer les ACIPHC from scratch, donc pas de convention et pas de problème.
Mais en pratique le support convertit parfois le type d'une antenne ACI existante en ACIPHC et du coup on a une incohérence de données pas critique pour la prod, mais problématique pour la cohérence des données.
L'incohérence est que la siae ACIPHC se retrouve attachée à une convention ACI. Ca ne devrait pas arriver car les ACIPHC sont supposées ne *pas* avoir de convention. Et de toute façon, une structure et sa convention devraient *toujours* avoir le même type.
En aval dans l'import SIAE, on corrige a posteriori les ACIPHC en question en détachant la convention ACI.
https://itou-inclusion.slack.com/archives/C01181Y04LT/p1620812621056500
=> Hotfix des ACIPHC créées par le support

itou/templates/siaes/configure_jobs.html, itou/www/siaes_views/forms.py, itou/www/siaes_views/tests.py, itou/www/siaes_views/views.py
Ajout d'une validation des données POST de la vue `configure_jobs`.
Sans cette validation, on peut passer à la requête un `custom_name` de taille supérieure à 255 caractères lever une erreur d'intégrité au niveau du champ de la base de données.
Avec un compromis appuyé par le fait que cette erreur n'est jamais remontée dans Sentry pour le moment.
La vue a été réalisée rapidement pendant la fabrication du prototype en se reposant sur JavaScript pour construire un formulaire dynamique. Du coup ça rend plus compliqué de valider les données et d'afficher les erreurs au bon endroit dans l'UI.
En attendant la refonte de cette UI (`ModelFormSet` ou validation JSON) on affiche les éventuelles erreurs en haut de la page.
=> Ajout d'une validation des données POST de la vue `configure_jobs`

itou/approvals/models.py, itou/approvals/tests.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/process_views.py, itou/www/apply/views/submit_views.py
Ignorer la période de carence pour les non SIAE.
Ce blocage n'a pas de sens pour les GEIQ/EA.
Cf https://trello.com/c/GeUSbdub/1679-un-orienteur-ne-peut-pas-candidater-en-ea-ou-geiq-si-son-candidat-a-un-parcours-iae-dans-le-d%C3%A9lai-de-carence
En étendant l'exception existante accordée aux prescripteurs habilités à toutes les structures non SIAE.
=> Ignorer la période de carence pour les non SIAE

itou/www/apply/views/process_views.py
Correctif pour un settings manquant
Fix de l'erreur Sentry :
> 'Settings' object has no attribute 'ITOU_DOC_PASS_VERIFICATION_URL'
=> Correctif pour un settings manquant

itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Nouveau test pour une branche de la vue `accept`.
Il manquait un test pour la branche concernant la délivrance manuelle de PASS IAE dans la vue `accept`.
Ce test vise à éviter de reproduire des erreurs comme celle d'hier :
> 'Settings' object has no attribute 'ITOU_DOC_PASS_VERIFICATION_URL'
=> Nouveau test pour une branche de la vue `accept`

itou/static/js/city_autocomplete_field.js, itou/templates/dashboard/edit_user_info.html, itou/utils/address/forms.py, itou/www/search/forms.py
Correctif pour l'erreur "Cette ville n'existe pas".
Pour soulager le support.
`AddressFormMixin` permet d'ajouter une adresse avec un mécanisme d'auto-complétion pour la ville.
Ce mécanisme est basé sur `js-city-autocomplete-input` qui travaille avec deux champs :
- `city` un champ masqué contenant un slug de la ville
- `city_name` le nom de la ville en toutes lettres
**Problème** : si une adresse existait déjà pour une instance de modèle, le champ caché `city` n'était pas pré-rempli.
Du coup au moment de la validation on tombait systématiquement sur l'erreur "Cette ville n'existe pas", quand bien même la ville était déjà renseignée en toutes lettres.
- déplacement de `AddressFormMixin.__init__()`
- affichage des erreurs une seule fois dans le template avec `alert_error_type="all"`
- …
=> Correctif pour l'erreur "Cette ville n'existe pas"

itou/templates/apply/submit_step_job_seeker_create.html, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/list.html, itou/utils/address/forms.py, itou/utils/address/tests.py, itou/utils/tests.py, itou/www/apply/forms.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/dashboard/forms.py, itou/www/signup/tests.py
Correctif pour `'CreateJobSeekerForm' has no field named 'addr1'`.
Je me suis trompé de nom de champ et `AddressFormMixin` n'était pas couvert par des tests.
Ajout de tests pour `AddressFormMixin`.
Déplacement des tests qui concernent `itou.utils.address` dans `itou.utils.address.tests` plutôt que de venir gonfler le fichier des tests à la racine du dossier `utils` : `itou.utils.tests`.
Ça sera probablement plus simple à revoir commit par commit.
=> Correctif pour 'CreateJobSeekerForm' has no field named 'addr1'

itou/approvals/models.py, itou/approvals/tests.py, itou/eligibility/models.py, itou/templates/approvals/includes/status.html, itou/www/apply/forms.py
Prise en compte de l'extension COVID dans les vérifications de date de fin d'embauche.
On a borné la date de fin d'embauche à la durée maximum d'un PASS IAE ou le temps restant d'un PASS IAE déjà existant dans la PR #666.
Or, si un agrément PE est éligible à l'extension COVID, la date de fin avec extension n'était pas prise en compte dans le contrôle.
Utilisation de `extended_end_at` à la place de `end_at`.
Au passage : factorisation du calcul de la durée de l'extension.
=> Prise en compte de l'extension COVID dans les vérifications de date de fin d'embauche

itou/users/models.py, itou/users/tests.py, itou/www/apply/tests/tests_process.py, itou/www/dashboard/forms.py, itou/www/dashboard/tests.py, itou/www/dashboard/views.py
On serre la vis ! Seule la personne ayant créé le compte candidat peut en modifier le courriel.
Actuellement, le courriel d'un candidat peut être modifié pendant le processus de candidature par l'employeur ou le prescripteur. Cela pose plusieurs soucis.
- Ajout de deux méthodes dans la classe `User` : `has_verified_email` et `can_edit_email`. 
- Modification du formulaire `EditUserInfoForm`.
- Ajout de quelques tests.
Je n'ai pas ajouté de test au niveau du modèle pour `has_verified_email` et `can_edit_email` car `coverage` m'indique que ces méthodes sont déjà testées. Je me dis que ça fera doublon. Qu'en pensez-vous ?
=> Seul le créateur d'un compte peut en modifier l'e-mail

itou/approvals/tests.py
Correctif pour `test_is_open_to_prolongation`.
Le test casse quand on est le dernier jour du mois. Exemple : 30 avril 2021.
Le test casse de temps en temps car on fait des calculs sur la base de 3 mois plus ou moins 1 jour pour s'assurer qu'on est dans la période ou en dehors.
Or 1 jour n'est pas suffisant pour éviter les périodes ambiguës. Quid des mois qui ont 28, 29, 30 ou 31 jours ?
Pour fixer le problème, on ajoute ou retranche une durée de 5 jours permettant d'éviter les cas ambigus.
> https://github.com/dateutil/dateutil/issues/1134
=> Correctif pour `test_is_open_to_prolongation`

itou/static/js/s3_upload.js
Modification du message d'erreur envoyé à Sentry et de celui affiché à l'utilisateur. 
Cela me permettra de vérifier l'hypothèse suivante : plusieurs utilisateurs envoient le CV plus d'une heure après l'affichage du formulaire. Cela génère une erreur 403 `Expired Policy`.
Sentry reçoit des erreurs lorsqu'un CV ne peut être ajouté à une candidature. Actuellement, elles manquent de détail et ne nous permettent pas de résoudre parfaitement les problèmes.
- Ajout d'informations dans le message envoyé à Sentry
- Modification du message d'erreur affiché à l'utilisateur si celle-ci vient d'une requête qui a échoué. 
Avant : 
Après :
=> Amélioration des erreurs S3 envoyées à Sentry

itou/utils/apis/api_entreprise.py
Des erreurs ne sont pas levées dans Sentry car elles sont [masquées par d'autres exceptions](https://sentry.io/organizations/itou/issues/2417913606/?environment=production&project=5671910&query=is%3Aunresolved).
L'exception `HTTPError` de HTTPx ne contient pas l'attribut `response`, or une ligne dans notre code le suppose. Pour avoir l'attribut `response`, il faut `HTTPStatusError`.
Remplacement de `HTTPError` par `HTTPStatusError`.
=> Résolution d'une erreur Sentry

itou/static/js/s3_upload.js
Une erreur Javascript empêche l'envoi d'erreur vers Sentry.
=> Correction d'une erreur Javascript dans le script d'envoi S3

requirements/base.txt
Mise à jour vers Django 3.2.4.
Mise à jour de sécurité.
> https://www.djangoproject.com/weblog/2021/jun/02/security-releases/
=> Mise à jour vers Django 3.2.4

itou/templates/layout/base.html
Masquage de l'icône Tarte au citron
L’icône apparaît au dessus de contenu et n'est pas demandé. 
Ajout des options disponibles dans la dernière version de Tarte au citron et modification de la valeur par défaut
(optionnel)
Avant :
Après :
=> Tarte au citron - Désactivation de l'icône présent en bas à droite

itou/utils/new_dns/middleware.py
Ajout de la redirection forum.inclusion.beta.gouv.fr -> communaute.inclusion.beta.gouv.fr
Cette redirection est actuellement gérée par une instance ruby/discourse [qui ne fait plus que cela](https://github.com/betagouv/itou-discourse/pull/77). Il continue d’y avoir un peu de traffic dessus, mais nous pouvons mutualiser les redirections permanentes sur ce projet et enlever une instance.
=> Ajout de la redirection forum.inclusion -> communaute.inclusion

itou/templates/apply/process_details_prescriber.html, itou/www/apply/tests/tests_process.py
Ajout des éléments suivants dans la page de suivi d'une candidature côté prescripteur : 
- raison du refus,
- message associé.
Avant, les utilisateurs avaient cette information dans la liste de leurs candidatures. Nous avons omis de la remettre dans la page de détails.
=> Les prescripteurs peuvent voir le message de refus des candidatures suivies

itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/_import_siae/vue_af.py, itou/siaes/management/commands/_import_siae/vue_structure.py, itou/siaes/management/commands/import_ea_eatt.py
- import SIAE : nouvelle donnée pourrie dans le dernier export faisant planter l'engine `python` de `pd.read_csv`. La solution est de passer à l'engine `c`, solution déjà implémentée pour l'import fluxIAE. Du coup cette PR fait un refactoring pour partager cette solution `get_fluxiae_df` entre tous les scripts.
- import EA : gros changement de données dans le dernier export, les colonnes ont changé de nom, nouvelle logique de déduplication et seulement 2% des EA ont un email (problème remonté à la DGEFP). Cette PR fait des correctifs préparatoires mais l'import est impossible tant que la DGEFP ne nous aura pas envoyé un nouveau fichier avec les emails.
Commit par commit sinon le diff est imbitable.
=> Correctifs pour les imports SAIE+EA du 6 juin 2021

itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/siaes/management/commands/_import_siae/utils.py
Ajout de 4 nouvelles tables fluxIAE dans metabase.
En deux parties :
- une PR publique https://github.com/betagouv/itou/pull/679 => ajout des 4 nouvelles vues en question
- une PR privée https://github.com/betagouv/itou-private/pull/37 => mise à jour de la documentation. Vu qu'on injecte un nombre toujours grandissant des 17 vues fluxIAE, autant simplifier et déplacer toutes les vues dans le bon dossier plutôt que s'embêter à choisir quelles vues déplacer
Pour que Soumia puisse faire encore plus de tableaux de bord intéressants dans metabase.
=> Ajout de 4 nouvelles tables fluxIAE dans metabase

clevercloud/cron.json, clevercloud/populate_metabase_itou.sh, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/metabase/management/commands/populate_metabase_itou.py
Renommage du script metabase "populate_metabase" en "populate_metabase_itou" pour éviter la confusion avec l'autre script "populate_metabase_fluxiae".
En deux parties :
- une PR publique https://github.com/betagouv/itou/pull/685
- une PR privée https://github.com/betagouv/itou-private/pull/39
Suite à discussion avec Stéphane.
=> Renommage du script metabase "populate_metabase" en "populate_metabase_itou" pour éviter la confusion avec l'autre script "populate_metabase_fluxiae"

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/_import_siae/financial_annex.py, itou/siaes/management/commands/import_siae.py
Abandon du dry run du script import_siae.
En deux parties :
- une PR publique https://github.com/betagouv/itou/pull/684 : suppression du dry run
- une PR privée https://github.com/betagouv/itou-private/pull/38 : mise à jour de la documentation
Maintenir ce dry run ajoutait trop de complexité pour pas assez de bénéfices.
Trop de complexité car dans de nombreux edge cases il fallait réagir différement selon dry ou wet run.
L'import SIAE étant constitué de plusieurs étapes successives dont chacune dépend des actions de la précédente, le dry run était de toute façon infaisable pour les dernières étapes.
Le dry run était au final partiel, donc donnait une fausse assurance que le wet run se déroulerait sans erreur. Si le dry run n'est pas capable d'assurer que le wet run se déroulera sans …
=> Simplification du script d'import des SIAE (abandon du "dry run")

itou/metabase/management/commands/_dataframes.py, itou/metabase/management/commands/_job_applications.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/metabase/management/commands/populate_metabase_itou.py
- Refactorings préparatifs, notamment déplacement de la méthode `store_df` dans une librairie commune aux deux scripts metabase (populate_metabase vs populate_metabase_fluxiae).
- Ajout d'une table de laison candidatures <-> fiches de poste dans metabase.
A la demande de Soumia.
Ne surtout pas regarder le diff global, illisible en raisons des refactorings préparatifs.
A la place, regarder commit par commit.
=> Ajout d'une table de laison candidatures <-> fiches de poste dans metabase

config/settings/base.py
Ajout du setting `SECURE_HSTS_SECONDS` pour ajouter un en-tête HTTP Strict Transport Security (HSTS).
Pour forcer les navigateurs à charger le site en HTTPS.
[Vu dans l'audit dashlord](https://dashlord.incubateur.net/#/url/https://emplois.inclusion.beta.gouv.fr).
=> Ajout du setting SECURE_HSTS_SECONDS

requirements/base.txt, requirements/dev.txt
La dépendance `sqlalchemy` doit être installée dans tous les environnements et non plus uniquement le dev local.
Jusqu'à vendredi dernier (10 juin 2021) `sqlalchemy` était uniquement utilisé par le script `populate_metabase_fluxiae` qui tourne seulement en local dev, une fois par semaine par supportix, donc jamais en prod.
Depuis vendredi dernier, suite à la MEP de https://github.com/betagouv/itou/pull/682, la nouvelle méthode `populate_selected_jobs` de `populate_metabase_itou` fait appel à `sqlalchemy` (via la méthode `store_df`). Hors `populate_metabase_itou` tourne non seulement en local dev mais aussi en prod chaque nuit via un cronjob, d'où la nécessité d'avoir `sqlalchemy` en production.
=> Réparation du cronjob metabase quotidien

itou/templates/apply/process_accept.html, itou/www/apply/forms.py
Suppression de la fenêtre surgissante
Parce que la fenêtre surgissante ne permet pas de voir quand il y a des erreurs sur un champs du formulaire.
Le contenu de la fenêtre surgissante est déplacé en lieu et place du bouton qui déclenchait son apparition. 
Avant :
Maintenant pour un employeur éligible IAE : 
Maintenant pour un employeur non éligible IAE :
=> Suppression de la fenêtre surgissante sur le formulaire d'embauche

itou/static/css/itou.css, itou/static/js/utils.js, itou/templates/apply/submit_step_application.html, itou/templates/layout/base.html, itou/templates/storage/s3_upload_form.html
Le formulaire permettant d'ajouter un CV à une candidature apparaît désormais uniquement si JavaScript est activé dans le navigateur.
Des utilisateurs ont écrit au support en se plaignant que le message de la candidature disparaissait après avoir essayé d'ajouter un CV en cliquant sur le lien "Choisissez un fichier". J'ai réussi à reproduire le problème en désactivant JavaScript. En effet, la classe `jsPreventDefault` n'a alors aucun effet et cliquer sur le lien a pour conséquence de rafraîchir la page.
Ajout d'une classe `jsDisplayIfJavascriptEnabled` qui affiche l'élément en JavaScript.
Evidemment, il s'agit d'une rustine. Activer ce formulaire aux utilisateurs qui n'ont pas JavaScript demande un peu plus de développement et nous en discuterons probablement lors de la prochaine journée …
=> Affichage du CV si JavaScript est activé dans le navigateur

itou/job_applications/models.py, itou/www/apply/tests/tests_process.py
Actuellement, des candidatures refusées ou obsolètes peuvent être acceptées sans diagnostic !
Les états dans `JobApplicationWorkflow.CAN_BE_ACCEPTED_STATES` n'ont pas été répercutés dans la méthode `JobApplication.eligibility_diagnosis_by_siae_required`.
Les tests ont été aveugles car nous l'avons été aussi ! En oubliant cette étape pourtant cruciale, les tests étaient toujours au vert.
- Modification de la méthode `JobApplication.eligibility_diagnosis_by_siae_required`
- Modification des tests
=> Affichage du bouton d'éligibilité pour les candidatures refusées et obsolètes

config/settings/base.py
Modification de la configuration de Huey.
Suite au problème survenu sur l'instance Redis le 12.06.2021 (OOM), il est nécessaire de modifier
la configuration de Huey dans Django.
Par défaut Huey stocke le résultat des tâches dans Redis en l'associant à un ID.
Dans le mesure où nos tâches actuelles ne renvoient rien ces résultats sont quasi-vides (contiennent peut être juste un code de retour) et prennent 40 octets avec le nom de la clef mais après l'envoi de 2,5 millions de mails nous atteignons les limites de mémoire de l'instance (100 Mo).
Ces résultats sont inutiles, il nous suffit de ne pas les stocker.
=> Désactivation du stockage des résultats de Huey dans Redis

config/settings/base.py, itou/utils/pdf.py
Investigation sur le nombre de PDF générés.
Difficile de trouver l'information exacte sur le site de PDFShift.
- Ajout d'un log sur les appels à l'API de génération de PDF pour compter les appels
- Ajout d'un _wrapper_ sur le endpoint `/credits/usage`
Il semble que : **A credit is counted per 5Mb chunks.**
Or les résultats me paraissent gros :
```shell
In [1]: from itou.utils.pdf import PDFShiftCreditsUsageAPI
In [2]: credits = PDFShiftCreditsUsageAPI()
In [3]: credits.used
Out[3]: 5876
In [4]: credits.number_of_approval_pdf_delivered
Out[4]: 195866
```
=> Investigation PDFShift

itou/utils/pdf.py
Utilisation de `logger.warn()` à la place de `logger.info()`.
On ne voit pas les logs `logger.info()`
> https://docs.sentry.io/platforms/python/usage/set-level/
=> Utilisation de `logger.warn()`

config/settings/base.py, itou/approvals/tests.py, itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/email/new_prolongation_for_prescriber_body.txt, itou/utils/emails.py, itou/utils/settings_context_processors.py
Faire confirmer une prolongation par le prescripteur.
Demande DGEFP.
Avec une version dégradée dans laquelle on demande au prescripteur de transférer un email à `prolongation@inclusion.beta.gouv.fr` afin de confirmer une prolongation. La demande est ensuite traitée en conciergerie par le support.
L'objectif est d'évaluer la quantité de confirmations à traiter avant d'investir plus de temps dans le code.
=> Faire confirmer une prolongation par le prescripteur

config/urls.py, itou/approvals/admin.py, itou/templates/admin/approvals/change_list.html
C'est dans le titre.
La management command `export_approvals`reste active bien sur.
L'export des PASS IAE déclenché via l'admin est fait via le worker principal sur Clever, et c'est un peu trop lourd pour lui:
```
2021-06-16T15:14:29+02:00 Wed Jun 16 13:11:07 2021 - *** HARAKIRI ON WORKER 2 (pid: 4628, try: 1) ***
2021-06-16T15:14:29+02:00 Exported 72262 approvals in 37.82 sec.
2021-06-16T15:14:29+02:00 Loading suspension data...
2021-06-16T15:17:10+02:00 Respawned uWSGI worker 2 (new pid: 4648)
2021-06-16T15:17:10+02:00 Wed Jun 16 13:11:21 2021 - HARAKIRI !!! end of worker 2 status !!!
2021-06-16T15:17:10+02:00 Wed Jun 16 13:11:15 2021 - HARAKIRI [core 0] 85.203.70.152 - GET /admin/approvals/approval/export_approvals since 1623849005
2021-06-16T15:17:10+02:00 DAMN ! worker 2 (pid: 4628) …
```
=> Retrait de l'export XLS des PASS IAE via l'admin

itou/approvals/notifications.py, itou/utils/notifications/base_class.py, itou/utils/notifications/tests.py
Supprimer la liste des destinataires par défaut
Pour que la liste des destinataires soit mieux maîtrisée par les utilisateurs de la classe BaseNotification (notamment pour bien cibler les utilisateurs actifs). 
Suppression de la valeur par défaut du paramètre type QuerySet + ajustement des tests unitaires
=> Modification de la classe de base des notifications 

itou/templates/signup/job_seeker_situation.html, itou/templates/signup/job_seeker_situation_not_eligible.html, itou/templates/signup/signup.html, itou/www/login/views.py, itou/www/signup/forms.py, itou/www/signup/tests.py, itou/www/signup/urls.py, itou/www/signup/views.py
Les SIAE reçoivent des candidatures autonomes de candidats non éligibles à l'IAE
On vise une meilleure qualification des candidatures pour :
- éviter la déception des candidats
- diminuer le traitement des candidatures par les SIAE
On ajoute une étape dans le workflow du parcours d'inscription candidat.
Le candidat doit déclarer sur l'honneur être dans l'une des situations administratives concernées pour pouvoir poursuivre son inscription
S'il n'est pas dans l'une des situations mentionnées, on l'invite à se rapprocher d'un prescripteur
L'URL d'inscription d'un candidat est modifiée pour afficher ce formulaire :
Si au moins un des critères d'éligibilité est coché, l'utilisateur est redirigé vers le formulaire d'inscription.
Si "Autre" est coché seul, la page spécifique suivante est …
=> Ajout du formulaire de situation avant l'inscription d'un demandeur d'emploi

itou/siaes/management/commands/_import_siae/siae.py, itou/siaes/management/commands/import_siae.py
- Traitement des structures créées par le support
- En passant, petit check des ACIPHC
Historiquement le support créé régulièrement des structures (source `STAFF_CREATED`) quand les données ASP sont en retard.
Normalement leur SIRET finit par apparaitre dans les données ASP, auquel cas elles sont converties et régularisées.
Mais dans le rare cas où leur SIRET n'apparait jamais dans les données ASP, elles restaient jusque là valides indéfiniment.
Cette PR met fin à cette immunité. Au bout de 90 jours après leur création (durée décidée par le support), ces structures sont soit supprimées (si sans membre ni candidature), soit une erreur fatale est émise pour forcer supportix à resoudre manuellement le problème.
=> Traitement des structures créées par le support

itou/templates/search/prescribers_search_results.html, itou/templates/search/siaes_search_results.html, itou/www/search/tests.py
Affichage des critères de recherche quels que soit les critères de ville et distance utilisés.
Si un utilisateur saisit une ville qui n'a pas de résultats (employeurs ou prescripteurs) dans la distance par défaut, il n'a pas la possibilité de modifier ses critères.
En ne conditionnant plus l'affichage des filtres selon le résultat du queryset et en fournissant un affichage adapté au queryset vide.
Je suis preneur d'une meilleure formulation « Aucun résultat avec les filtres actuels. » ou « Aucun résultat avec les critères sélectionnés. ».
=> Affichage permanent des filtres

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/models.py
Activation dans le script d'import des SIAE d'un contrôle que toutes les antennes ont dorénavant une convention sans exception.
Plus une petite simplification du code du modèle des structures qui fera plaisir à @kemar 
On trainait une dette technique d'antennes sans convention, remontant à l'époque où la création d'antenne se faisait sans garder un lien clair avec la structure mère.
J'ai résolu à la main la dizaine d'antennes qui restaient.
Cette situation ne devrait plus jamais se reproduire.
=> Les antennes ont dorénavant toutes une convention sans exception

config/settings/_sentry.py, itou/utils/pdf.py
Nouvelle configuration de Sentry.
Pour remonter les alertes de niveau `warning`.
> https://docs.sentry.io/platforms/python/guides/logging/
=> Configuration de Sentry pour remonter les warnings

itou/users/models.py, itou/users/tests.py, itou/www/dashboard/forms.py, itou/www/dashboard/tests.py
Empêcher la modification de l'adresse mail des demandeurs d'emploi dans leur profil
Pour éviter les incohérences et forcer les demandeurs d'emploi à utiliser la page dédiée à la modification de l'adresse Email
Suppression du champ "email" quand c'est le demandeur d'emploi qui est sur la modification de son profil. On laisse la possibilité à un prescripteur de modifier l'adresse mail si celle-ci n'a pas encore été vérifiée.
=> Les demandeurs d'emploi ne doivent pas pouvoir changer leur adresse mail dans la modification de leur profil

itou/approvals/models.py, itou/templates/approvals/includes/status.html, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/views.py
Les candidatures créées à partir d’un agrément Pole emploi n’ont pas de date de début (car cette information ne nous est pas fournie par PE). Il faut cependant quand même pouvoir les suspendre, et le code actuel utilise la date d’embauche comme date minimale de suspension.
PE ne fait plus les suspensions, nous devons proposer cette fonctionnalité.
Le formulaire de suspension `SuspensionForm` permet de sélectionner une date de début de suspension via, initialisée via
```python
min_start_at_str = Suspension.next_min_start_at(self.approval).strftime("%Y/%m/%d")
```
Cette ligne plante si `approval.user.last_accepted_job_application.hiring_start_at == None`.
Correction proposée: si pas de `hiring_start_at`, on renvoie la date du jour.
=> Rendre possible la suspension d'une candidature sans date de début

Makefile
Ajout d'une commande qui écrit le résultat d'une requête SQL dans un fichier CSV. Plus précisément, la commande prend en entrée un **fichier** SQL et génère en sortie un CSV dans le dossier `exports`.
Nous avons tous des manières différentes de générer les CSV : certains le font en Python, d'autres avec un `COPY` ou encore avec `psql --csv`. Je propose l'ajout de cette commande Make afin de faciliter la vie de Supportix et de passer moins de temps à la génération du CSV en tant que tel. 
Pour ceux qui utilisent Docker :
`make psql_to_csv FILEPATH=path/to/script.sql`
Pour les autres, je trouve que la commande d'origine est assez simple et ne mérite pas sa place dans le Makefile.
`psql --csv -f path/to/script.sql -o exports/export.csv`
=> Génération d'un CSV à partir d'un script SQL

Makefile, deploy_prod.sh, scripts/deploy_prod.sh
Ajout d’une commande `make deploy_prod`
Pour:
- faciliter le déploiement
- centraliser/documenter la manière de faire
- éviter que tout le monde réécrive ce script chez lui
- éviter les erreurs dues aux opérations manuelles
Ajout d’un script bash
=> Ajout d’une commande 'make deploy_prod'

itou/eligibility/models.py, itou/eligibility/tests.py, itou/job_applications/factories.py, itou/templates/approvals/approval_as_pdf.html, itou/www/apply/views/process_views.py, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/views.py
Simplification du code lié aux diagnostics.
La PR #750 permet de simplifier certain aspects du code.
Suppression de `EligibilityDiagnosisManager.test_last_before`.
=> Simplification du code lié aux diagnostics

itou/job_applications/models.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Simplification du code lié aux diagnostics (bis).
La PR #750 permet de simplifier certain aspects du code.
Unification de la méthode de récupération d'un diagnostic à partir d'une candidature quel que soit son état.
Permet d'économiser des requêtes SQL pour les candidatures qui ont déjà un diagnostic identifié.
=> Simplification du code lié aux diagnostics (bis)

requirements/base.txt
Mise à jour vers Django 3.2.5.
Mise à jour de sécurité.
> https://www.djangoproject.com/weblog/2021/jul/01/security-releases/
=> Mise à jour vers Django 3.2.5

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests.py
L'erreur **La date de début ne peut pas être différente de la date de fin du PASS IAE** se produit quand je tente de modifier une prolongation dans l'admin.
Une prolongation doit commencer exactement le même jour qu'un PASS IAE.
Quand on fait une prolongation, la date de fin du PASS IAE est modifiée aussi pour coller à la fin de la prolongation.
Au moment de modifier une prolongation dans l'admin, le contrôle de la date de début se base sur la date de fin du PASS IAE pour s'assurer qu'il s'agit du même jour.
Or celle-ci est désormais la même que la date de fin de la prolongation qu'on tente de modifier.
La modification de la prolongation devient impossible.
On limite le contrôle aux nouvelles prolongations.
=> Correctif pour pouvoir modifier une prolongation dans l'admin

itou/metabase/management/commands/_organizations.py, itou/metabase/management/commands/_siaes.py
Ajout de 2 nouveaux champs dans metabase
- structures.id_asp
- organisations.brsa
Pour débloquer Soumia.
Noter que le master doc est bien tenu à jour à chaque changement de colonnes : https://docs.google.com/spreadsheets/d/1H1YkxeremqE0niJIu66pghgL8wAHLuY0PUt7JGEFG3E/edit#gid=316863205
=> Ajout de 2 nouveaux champs dans metabase [sera MEP le 1er juillet]

Makefile, scripts/import-latest-db-backup.sh
Ajout d’un script d’import de dump de base
Cette tâche est documentée au format texte dans un dépot tiers, ce qui nécessite en l’état:
- de copier coller un script ailleurs
- que chacun réimplémente cette logique
Dans un souci de mutualisation et d’automatisation des tâches récurrentes, j’ai l’impression que cela a du sens d’avoir un tel script dans le projet.
Ajout d’un script dédié qui tire partie de nos outils.
=> Script de réimport de base de données

itou/www/approvals_views/views.py
Une erreur est levée lorsqu'un PASS délivré par nous n'est lié à aucun diagnostic. Or, parfois ce diagnostic existe mais n'est pas trouvé.
Le code utilise l'attribut `eligibility_diagnosis` qui récupère le diagnostic associé à une candidature via la clé (voir les PR #750 et #759 ). Mais cela ignore les règles métier qui permettent de retrouver un diagnostic (`JobApplication.get_eligibility_diagnosis`).
Rapide et efficace : remplacement de l'attribut par la méthode.
=> Correction d'un bug lors du téléchargement d'un PASS IAE

.env.template, Makefile, scripts/import-latest-db-backup.sh
Ajout d'une option pour télécharger la dernière sauvegarde de prod quand on lance la commande `make postgres_restore_latest_backup`.
Cela permet de tirer parti du [travail important réalisé par Clément](https://github.com/betagouv/itou-backups) mais qui a le désavantage de se trouver sur un tout autre projet.
Egalement, ajout d'un `.env.template`.
Cette commande doit être exécutée dans un autre répertoire et il est fastidieux d'y naviguer à chaque fois.
=> Téléchargement de la dernière sauvegarde

itou/approvals/models.py, itou/approvals/tests.py, itou/job_applications/tests.py, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/views.py
Filtrage des agréments pôle emploi qui démarrent dans le futur afin qu’ils n’apparaissent pas dans les résultats d’import.
https://trello.com/c/yvAp4kAe/1807-c1-plusieurs-agr%C3%A9ments-pe-commencent-dans-le-futur
Pour éliminer les erreurs de saisie dans les agréments ; avec un agrément dans le futur, on prend le risque d’une réutilisation
=> Éliminer des résultats les agréments Pôle emploi qui démarrent dans le futur

config/settings/_sentry.py
PR sans revue.
Oubli de ma part de remonter le niveau de log de Sentry après les tests sur l'extraction de log
=> Modification du niveau de log pour Sentry

itou/invitations/models.py, itou/invitations/tests.py, itou/www/invitations_views/forms.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_send.py
Suppression d'une condition dans le mécanisme d'invitation. Nous regardions si l'invitation était expirée. Si c'était le cas, nous prolongions l'invitation au lieu de la renvoyer.
Cela cause de nombreux soucis et ajoute de la complexité inutilement.
Imaginons un membre, Georges, qui a rejoint une organisation en cliquant sur un lien d'invitation.
L'administrateur de cette organisation décide de le désactiver. Georges n'est plus membre.
Mais voilà que l'administrateur l'engage de nouveau ! Il pense envoyer une nouvelle invitation mais, en réalité, notre algorithme prolonge la date de validité de la première invitation envoyée !
Georges clique sur le lien d'acceptation mais il voit le message d'erreur suivant : "Invitation déjà acceptée".
Envoi de l'invitation systématique.
=> Un membre retiré d'une structure peut être réinvité

itou/templates/invitations_views/includes/pending_invitations.html, itou/templates/invitations_views/new_user.html
Affichage du lien d'invitation directement dans la gestion des collaborteurs
Des utilisateurs disent ne pas recevoir le lien d'invitation. Le support doit alors le gérer manuellement, ce qui est chronophage.
Le lien d'invitation est affiché dans le tableau dans un champs texte en lecture seul pour faciliter sa copie.
Pour limiter les erreurs, le nom du collaborateur est ajouté sur la page cible du lien d'invitation.
Le tableau des collaborateurs : 
Page cible du lien d'invitation :
=> Affichage du lien d'invitation

itou/templates/approvals/pe_approval_search.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/tests.py, itou/www/approvals_views/views.py
Correctif pour une erreur 404.
Quand une SIAE souhaite récupérer un agrément PE pour le prolonger, on vérifie que ce dernier n'a pas déjà été utilisé pour émettre un PASS IAE.
Si c'est le cas, alors on récupère la dernière candidature associée au PASS IAE.
Or si la SIAE destinataire de la dernière candidature n'est pas la SIAE connectée, on tombe sur une 404.
Ajout d'une vérification pour s'assurer que la SIAE destinataire de la dernière candidature est bien la SIAE connectée.
=> Correctif pour une erreur 404 lors de la reprise d'un agrément PE

itou/templates/apply/submit_step_job_seeker_create.html
Suppression de la mention "avec un CV" pour plus de clarté.
=> Mise à jour du bouton "Continuer avec un CV"

itou/approvals/tests.py
Prise en compte du fuseau horaire dans les tests unitaires des agréments
Les tests unitaires ne passent pas entre minuit et 2h.
En utilisant le module `timezone` de `django.utils`.
=> Prise en compte du fuseau horaire dans les tests unitaires des agréments

itou/templates/500.html
Ajout d'un lien.
Le message initial laisse croire que le problème va être traité et nous ne sommes pas toujours suffisamment réactifs ou nous ne prenons pas bien la mesure du problème.
Avec ce lien, le but est d'avoir un contact avec l'utilisateur et d'obtenir plus d'infos.
=> Lien vers le support en cas d'erreur 500

itou/metabase/management/commands/_job_seekers.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/prescribers/factories.py, itou/users/models.py, itou/users/tests.py, itou/www/stats/views.py
- Ajout d'une colonne qui précise si le candidat est inscript à PE
- Filtrage des "fausses" candidatures liées à des agréments PE
- Les utilisateurs VIP (Soumia etc) peuvent maintenant avoir accès au TDB CD, le département sera toujours le 01.
=> Boost Metabase

itou/prescribers/models.py, itou/templates/signup/prescriber_choose_kind.html, itou/templates/signup/prescriber_choose_org.html, itou/templates/signup/prescriber_confirm_authorization.html, itou/templates/signup/prescriber_siren.html, itou/www/signup/forms.py, itou/www/signup/tests.py, itou/www/signup/urls.py, itou/www/signup/views.py
Ajout d'une étape de saisie du SIREN
Pour éviter les doublons d'organisations prescripteurs
En demandant le SIREN avant le type d'organisation, il est ainsi possible de voir si l'organisation existe déjà sur un département. Ainsi, il ne devrait plus y avoir plusieurs fois la même organisation avec des types différents.
Étape de saisie du SIREN
Quand des organisations existent avec le même SIREN sur le même département :
Si aucune organisation n'est trouvée, l'étape de choix du type est affichée (avec train d'étapes) :
Lorsque nous choisissons "Autre", l'étape d'après ne propose plus l'option "Seul (sans organisation)" et affiche le train d'étapes :
=>  Modification du tunnel d'inscription des prescripteurs

clevercloud/review-app-after-success.sh, config/settings/demo.py
Tout est dans le titre. :)
Les recettes jetables sont maintenant dans une organisation dédiée. Nous n'avons donc plus besoin d'une base de données personnalisée pour la démo.
J'ai migré les données de l'ancienne BDD vers la nouvelle, tout fonctionne.
=> Démo : utilisation de la base de données par défaut de l'extension Postgres Clever

.pylintrc, config/settings/test.py, itou/templates/signup/prescriber_signup.html, itou/templates/signup/prescriber_siren.html, itou/templates/signup/prescriber_siret.html, itou/users/factories.py, itou/utils/apis/api_entreprise.py, itou/utils/templatetags/format_filters.py, itou/utils/tests.py, itou/www/signup/forms.py, itou/www/signup/tests.py, itou/www/signup/views.py, requirements/base.txt, requirements/dev.txt
- nouveau formulaire de saisie du SIRET
- nouvelle interface pour l'API Entreprise
- contrôles supplémentaires des données
- amélioration des tests
- mise en forme SIRET/SIREN
- mock plus fin de l'API
Ces améliorations ont pour but de rendre l'interface plus agréable et le code plus robuste mais une refonte complète de l'UX est nécessaire (voir la carte associée).
La librairie respx permet de ne mocker que les appels HTTP ainsi il est possible de tester le code d'erreur et le traitement de la réponse.
Pour éviter que l'utilisateur saisisse un SIRET différent de celui utilisé pour la recherche d'établissement et pour éviter qu'il est l'impression de saisir une seconde fois la même information, la partie SIREN est positionné en lecture seule devant le champ
de saisie des 5 derniers chiffres …
=> Ajustements au tunnel d'inscription des prescripteurs

itou/templates/dashboard/dashboard.html
Test si un des liens sera affiché pour décider d'afficher l'icône.
L'icône seul ne sert à rien.
Utilisation d'un with au passage pour l'URL de la fiche.
https://trello.com/c/5Pj53pXK/1912-boost-licone-de-modification-des-infos-structure-est-visible-par-les-non-admin
=> Affiche l'icône si un lien est présent

itou/metabase/management/commands/_database_psycopg2.py
N'effectue pas de `commit` en cas d'erreur.
Pour éviter d'enregistrer une table partiellement valide (et inutile car non renommée).
Réserve `__exit__` à la gestion des ressources que la classe a créée.
=> Restreint le wrapper de DB aux ressources

.env.template, README.md
Complément d'information pour les virtualenv de dev.
Parce que Docker n'est pas nécessaire.
Le développement dans un virtualenv évite l'overhead inhérent à Docker. 
Accès direct à la DB et à ses logs, utilisation des sockets Unix possibles, etc.
Décrit l'astuce de chargement automatique des variables d'environnement dans le venv.
=> Notes pour les virtualenv

itou/siaes/management/commands/move_siae_data.py
Ajout d'une commande supportix pour déplacer les données d'une SIAE A vers une SIAE B.
C'est un besoin fréquent du support. Notamment quand un utilisateur a utilisé à tort la SIAE A au lieu d'utiliser la bonne SIAE B.
De façon similaire au script existant `merge_organizations.py`.
=> Ajout d'une commande supportix pour déplacer les données d'une SIAE A vers une SIAE B

docker/dev/django/Dockerfile
Changement du serveur pour la récupération de la clé GPG de Postgres
Le serveur de clés utilisé n'est plus disponible
Changement d'URL dans le Dockerfile
=> Remplacement du serveur de clés GPG

clevercloud/sync_employee_records.sh
Faire en sorte que le CRON de transfert des fiches salarié vers l'ASP ne fonctionne que sur les environnements sélectionnés
Pour éviter de pourrir les logs (et le sentry) des instances ne disposant pas de cette fonctionnalité
Conditionner le lancement du script à la présence sur l'instance de la variable d'environnement `EMPLOYEE_RECORD_CRON_ENABLED`
=> CRON des fiches salarié conditionnel

itou/approvals/models.py, itou/approvals/tests.py, itou/job_applications/csv_export.py, itou/job_applications/models.py, itou/job_applications/tests.py, itou/templates/approvals/includes/status.html, itou/templates/dashboard/dashboard.html, itou/users/models.py, itou/www/apply/views/submit_views.py
Donner la possibilité à un candidat de postuler s'il dispose d'un diagnostic valide, même s'il est en période de carence.
Actuellement, un candidat qui est en délai de carence ne peut pas postuler même si un prescripteur habilité a réalisé un diagnostic.
Le support a reçu plusieurs retours à ce sujet de la part de prescripteurs qui s'en étonnaient.
Nous adaptons donc le code au besoin métier.
Mise à jour d'une méthode qui contourne la période de carence dans certains cas.
Mise à jour de l'interface.
Une requête en plus pour un affichage conditionnel sur le tableau de bord candidat.
AVANT : 
MAINTENANT : 
AVANT : 
MAINTENANT : 
AVANT : 
MAINTENANT :
=> Un candidat peut postuler s'il a un diagnostic valide

itou/utils/pdf.py
Correction de la classe `PDFShiftUsage`.
Je pensais qu'un crédit était décompté par paquet de 5Mo.
Mais en fait, un crédit est compté par conversion, mais si on dépasse 5Mo par PDF, ce sera un crédit par paquet de 5Mo.
=> Correction de la classe PDFShiftUsage

.github/workflows/review-app-creation.yml, clevercloud/review-app-after-success.sh
Possibilité de redéployer une recette jetable sans avoir à la détruire. 
Chaque _push_ effectué sur une branche qui a l'étiquette "recette-jetable" déclenche un nouveau déploiement chez Clever. 
Il est très pénible de supprimer puis de créer une nouvelle recette jetable pour refléter un changement applicatif. C'est une perte de temps et d'énergie.
Ajout d'une étape conditionnelle dans le script de création des recettes jetables.
=> Déploiement d'une recette jetable en fonction de l'activité d'une branche

itou/templates/apply/submit_base.html
Affichage du nom de la personne dans le titre.
Harmonisation avec le parcours prescripteur.
Etape 1 : aucun changement
Etape 2 : aucun changement
Etape 3 : nom du candidat affiché
=> Mise à jour du titre affiché lorsqu'une SIAE réalise une auto-prescription

config/settings/base.py, itou/api/urls.py, requirements/base.txt
- Ajout de `drf-spectacular` et replacement du schéma OpenAPI par défaut par celui de drf-spectacular
- Ce changement corrige `https://emplois.inclusion.beta.gouv.fr/api/v1/redoc/` qui est cassé pour des raisons de droit d’accès au schéma OpenAPI.
Le schéma OpenApi par défaut de DRF est assez pénible à personnaliser, drf-spectacular permet facilement [d’annoter les vues](https://drf-spectacular.readthedocs.io/en/latest/readme.html#customization-by-using-extend-schema) avec les éléments que l’on souhaite: plus de codes de retour que ce qui est automatiquement deviné, personnalisation des payload d’erreur, spécitication des règles d’authentification… Avec l’arrivée de l’API PE, ça devient utile voire nécessaire pour ne pas trop s’embêter.
=> Ajout de drf-spectacular

config/settings/dev.py.template, itou/approvals/models.py, itou/templates/approvals/pe_approval_search.html, itou/templates/approvals/pe_approval_search_found.html, itou/templates/approvals/pe_approval_search_user.html, itou/templates/dashboard/dashboard.html, itou/www/apply/views/submit_views.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_pe_approval.py, itou/www/approvals_views/views.py
- Recherche dans les agréments PE à partir du numéro d'agrément sans le suffixe. Impossibilité de chercher avec le suffixe.
- Correction de l'erreur 403 qui était levée lorsque l'utilisateur arrivait au milieu du parcours de candidature.
- Harmonisation du parcours « Prolonger ou suspendre un agrément ».
- Des agréments Pôle emploi n'étaient pas trouvés.
- Erreur 403
- Simplification et factorisation du code
Exceptions : 
Le numéro entré ne fait pas 12 caractères.
L'agrément est utilisé par une autre structure.
L'agrément est expiré depuis moins de deux ans (en période de carence).
L'agrément est expiré depuis plus de deux ans ou n'a pas encore démarré (commence dans le futur).
L'agrément a été délivré par la plateforme (ce n'est donc pas un agrément).
=> Correctif concernant la récupération des agréments délivrés par Pôle emploi

itou/invitations/tests.py, itou/job_applications/factories.py, itou/www/apply/tests/test_edit.py, itou/www/apply/tests/tests_list.py, itou/www/apply/tests/tests_process.py, itou/www/approvals_views/tests/test_suspend.py
Certains tests unitaires ne passent pas entre minuit et 1h.
Certaines dates sont naïves et d'autres conscientes, ce qui créé des décalages de date entre 0h et 1h.
En passant par la méthode `localdate` de `timezone`
=> Correction de certains tests unitaires qui ne passent pas entre minuit et 1h

itou/metabase/management/commands/sql/003_fluxIAE_AnnexeFinanciere_v2.sql
- Extraire le numéro du département à partir du numéro de l'annexe financière
- Récupérer le type de structure de la colonne af.af_mesure_dispositif_code
- Retraiter les variables dates qui sont au format string dans la table fluxIAE_AnnexeFinanciere
Simplifier les requêtes Metabase
=> Retraitement de la donnée de la table fluxIAE_AnnexeFinanciere

itou/metabase/management/commands/sql/005_suivi_saisies_dans_asp.sql
Suivi des déclarations mensuelles faites par les structures dans l'extranet asp
Le besoin des DDETS est d'avoir un suivi en temps réel du retard que les structures prennent dans la saisie des données mensuelles dans l'extranet asp
=> Suivi des saisies des structures dans l'asp

.github/workflows/populate-metabase.yml
Tentative de correction de cette erreur lors de la github action `populate-metabase`:
```bash
Run $CLEVER_CLI deploy --branch $DEPLOY_BRANCH --force
Error:  Could not find master_clever.
Error: Process completed with exit code 1.
```
Le cron ne tourne pas à cause de ça
- Ajout du nom d’application
- Ajout de la possibilité de jouer le workflow à la main
=> Fix deploiement vers clever de la tâche populate-metabase

.github/workflows/imports-asp.yml, scripts/imports-asp.sh
Automatisation des imports de données de l’ASP
À la main, c’est long et source d’erreurs. Solliciter une machine de dev pour l’import metabase montre ses limites.
Sur le même modèle que https://github.com/betagouv/itou/pull/830:
- un workflow github s’occupe de créer la machine
- la tache à effectuer (`script/imports-asp.sh`) est stocké dans un hook clever
- on récupère les données, on exécute les 3 imports, on supprime les données en clair et la machine
=> Import des données ASP via une github action

itou/metabase/management/commands/sql/007_suivi_consommation_etp.sql
Construction d'un suivi  des structures qui sous-consomment ou sur-consomment les etp par rapport aux subventions
Les DDETS pourront redistribuer les aides aux postes en se basant sur la consommation réelle des structures
=> Suivi de la consommation des etp 

.github/workflows/review-app-creation.yml
Renommage de la branche principale de l'action Github pour l'édition des PR pour ajouter l'URL des recettes jetables.
La branche a été renommée de master à main > https://github.com/thollander/actions-comment-pull-request/issues/24
=> Renommage de la branche principale de l'action Github pour l'édition des PR

itou/utils/widgets.py, requirements/base.txt
Correctif pour les erreurs Sentry relatives au format de la date du datepicker.
J'en profite pour inclure [la mise à jour bugfix de Django 3.2.7](https://docs.djangoproject.com/en/3.2/releases/3.2.7/).
Pour fixer des erreurs rencontrées par les usagers.
En supprimant le `raise ValueError` du code du widget. La validation est faite par le `Field` sous jacent. Le widget ne s'occupe que de présentation.
=> Correctif pour les erreurs Sentry relatives au format de la date du datepicker

itou/users/models.py, itou/users/tests.py
- Mise à jour de l'accès des CD à leurs stats.
- Ajout de documentation dans la docstring de la méthode `user.can_view_stats_cd`.
Un CD == un conseil départemental.
- Pour débloquer Soumia dans son travail avec les CD.
- En évitant de montrer les stats CD à des organisations qui ne sont pas vraiment des CD.
- En montrant ces stats non seulement aux admins des CD mais aussi à tous les membres.
=> Mise à jour de l'accès des CD à leurs stats

itou/templates/layout/base.html
Ajoute une option d'opt-in / opt-out dans les paramètres personnalisés de tarteaucitron
Demande Thomas / DPO
- Ajout d'un "service" personnalisé Matomo dans tarteaucitron,
- modification du template `base.html`.
- lien vers la [carte Trello](https://trello.com/c/Wf5ciffG/1761-int%C3%A9grer-la-fonctionnalit%C3%A9-dopt-out-au-sein-de-notre-politique-de-confidentialit%C3%A9)
- [Thread de contexte](https://itou-inclusion.slack.com/archives/CQQBH3YFR/p1621935514002400) sur Slack
- Discussion récente [sur Slack](https://itou-inclusion.slack.com/archives/CQQBH3YFR/p1626935208004700)
=> Opt-in / opt-out Matomo dans tarteaucitron

itou/templates/apply/includes/job_seeker_info.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/dashboard/edit_job_seeker_info.html, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Ajout d'une étape de confirmation pour s'assurer que l'e-mail entré est bien le bon.
Des prescripteurs ou des employeurs utilisent une même adresse e-mail pour plusieurs candidats.
- Ajout d'une modale avec des informations sur le candidat trouvé en base
- Modifications diverses de l'interface
Si le prescripteur est orienteur :
Si l'utilisateur est employeur ou prescripteur habilité :
Aucun changement.
Changements par rapport aux maquettes :
- J'ai remplacé les guillemets ("") par les guillemets français («»).
- Message « Email existant » : « les informations personnelles du candidat pour **qui** vous allez postuler » par « les informations personnelles du candidat pour **lequel** vous allez postuler ».
- le message qui apparaît après avoir cliqué sur « Ce n'est pas mon candidat » est …
=> Ajout d'une étape au processus de candidature si le candidat existe déjà

config/settings/base.py, itou/api/siae_api/viewsets.py, itou/siaes/serializers.py, requirements/base.txt
Ajout de la possibilité d’ordonner les différents résultats de l’API `api/v1/siae`
Demande de Pole Emploi
- Introduction de `django_filter` pour ne pas écrire de code dédié (pas trouvé mieux, mais dès la doc de DRF [ils suggèrent cette option](https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter))
- Introduction d’une classe de mapping entre nom du paramètre de requête (en francais, comme en sortie de l’API) et les propriétés du modèle sur lequel faire le tri
- MAJ de la documentation d’API (les critères de tri ne sont pas inféré automatiquement) pour refléter cette possibilité
=> Filtre de tri pour l’API SIAE

itou/templates/apply/submit_step_application_sent.html, itou/templates/search/siaes_search_results.html, itou/templates/siaes/card.html, itou/templates/siaes/job_description_card.html, itou/utils/urls.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/urls.py, itou/www/apply/views/submit_views.py
Le prescripteur peut revenir à sa recherche après avoir postulé pour un candidat.
Les prescripteurs réalisent parfois plusieurs candidatures d'affilée. Revenir à la recherche leur fait donc gagner du temps.
Ajout d'une étape supplémentaire à la fin parcours de candidature avec deux boutons.
:warning: Cette étape apparaît uniquement aux prescripteurs. Les employeurs et les candidats autonomes ne sont pas concernés, ils continuent d'être redirigés vers la liste des candidatures.
=> Un prescripteur peut revenir à sa recherche après une candidature

.env.template, scripts/create-fast-machine.sh
Création d’une machine clever cloud depuis la machine locale pour lancer des commandes sur une machine qui ressemble à la prod, sans l’être, et sans solliciter la machine d’un dev, par exemple pour les imports.
Solution intermédiaire plutôt qu’utiliser les github actions.
Le faire depuis github montre des limitations:
- on perd les logs lorsque la machine est détruite
- en cas de crash on a du mal à lire les logs, les machines restent présentes car la destruction n’est pas réalisée
Nécessite l’installation de [`clever tools`](https://github.com/CleverCloud/clever-tools/) en local
Les commandes prévues dans `.github/workflows/imports-asp.yml` sont jouées dans un script dédié qui fait les appels
Ensuite il reste à:
- aller sur la machine (`clever ssh --alias nom_de_la_machine`)
- jouer un …
=> Ajout d’un script pour automatiser la création d’une machine pour les imports

config/settings/prod.py
Arrêt du suivi APM
Pour éliminer cette piste sur la page de téléchargement des PASS IAE.
Retrait de l'agent dans la config
=> Désactivation de l'agent APM

config/urls.py, itou/templates/api/index.html, itou/www/api/urls.py, itou/www/api/views.py
Ajout d’une landing page pour présenter l’API
- favoriser et faciliter son utilisation
- absence d’une telle page surprenante du point de vue des utilisateurs
- Ajout d’une page `/api`
- Code/style calqué sur la [page équivalente du marché](https://api.lemarche.inclusion.beta.gouv.fr/).
=> Landing page API

config/settings/prod.py, config/settings/review_apps.py, itou/www/approvals_views/views.py, requirements/base.txt, requirements/deploy.txt
L'appel pour la génération du pdf des PASS IAE ne fonctionne pas avec l'APM activé.
L'agent APM lève une erreur au moment de la capture de l'appel externe fait avec `httpx`.
Mise à jour de l'agent et de `httpx`
=> Résolution de l'erreur Elastic APM lors des appels httpx

config/settings/prod.py, config/settings/review_apps.py
Désactivation temporaire de l'APM.
Beaucoup d'erreurs Sentry :
- https://sentry.io/organizations/betagouv-f7/issues/2665037876/?project=5671910&query=is%3Aunresolved
- https://sentry.io/organizations/betagouv-f7/issues/2665039255/?project=5671910&query=is%3Aunresolved
Le serveur APM est down chez Clever Cloud. Ils sont au courant du problème.
Désactivation temporaire de l'APM en attendant résolution Clever.
=> Désactivation temporaire de l'APM

itou/fixtures/django/17_employee_records.json, itou/job_applications/models.py, itou/job_applications/tests.py, itou/templates/employee_record/create.html, itou/templates/employee_record/includes/list_item.html
Modification des fixtures des fiches salarié (ajout du SIRET)
Simplification de la requête de filtre des candidatures
- Pour permettre d'utiliser l'environnement de DEV par défaut avec les fiches salarié pré-enregistrées
- Simplifier le filtrage des embauches éligibles aux fiches salarié (conditions redondantes)
- en ajoutant un SIRET bidon aux exemples de fiches salarié
- faire confiance au processus d'annulation d'embauche: le PASS temporaire est détruit si l'embauche est annulée, donc l'éligibilité est automatiquement bloquée (pas de PASS IAE dispo)
=> Fixtures fiches salarié

itou/approvals/management/commands/import_pe_approvals.py
Correctifs pour `import_pe_approvals.py`.
Pour pouvoir importer le fichier fourni par PE.
- on force la valeur `ID_REGIONAL_BENE` au format chaîne de caractère
- on zappe les ID Pôle emploi qui ne sont pas au bon format pour ne pas faire échouer la commande
=> Correctifs pour `import_pe_approvals.py`

itou/employee_record/models.py
Le type de prescripteur (optionnel) transmis à l'ASP peut être mal formaté
Ce champ peut ne pas être existant en base (valeur vide)
Un peu plus défensif sur la valeur (test de `None`)
Pas de revue (fix PROD)
=> FIX: Type de prescripteur

itou/employee_record/admin.py, itou/employee_record/models.py, itou/employee_record/serializers.py, itou/users/admin.py
FIX 1: 
- type orienteur
- pas de dégradation de données, si pas au format on ne transmet pas le complément d'adresse
- amélioration de l'admin pour les contraintes de la prod (real life)
Traitement des retours d'intégration ASP / cas limites ou nouveau
Vite
- plusieurs PR du style à prévoir aujourd'hui
- - la plupart du temps sans revue (mais les tests sont toujours ok !)
=> FIX  - intégration fiches salarié 01

itou/common_apps/address/format.py, itou/employee_record/admin.py, itou/users/admin.py, itou/users/management/commands/sync_group_and_perms.py, itou/utils/mocks/address_format.py
Suite des fixes "à la volée" de l'intégration des fiches salarié. Moins critiques au fil du temps
Essentiellement amélioration du taux de transfert sans erreur et amélioration de l'admin
- amélioration de l'admin et de la recherche sur les fiches salarié
- ajout des droits pour les admin
- fix du formatage des voies et des extensions (bis. ter ...) suite a un breaking change de l'API geo
=> FIX intégration ASP 03

clevercloud/cron.json, itou/employee_record/serializers.py, itou/job_applications/models.py
- correction d’éléments d'adresse mal spécifiés
- modification des horaires de téléchargement des résultats ASP
Le CDC ASP est "victime" d'un copier / coller sauvage.
Certains descriptifs de validité sont copiés / collés et complètement faux pour certains champs (par exemple le libellé de la voie pour l'adresse du candidat).
Malheureusement, c'est déjà le 3eme cas ou les descriptifs du cahier des charges sont erronés.
Concernant le CRON, l'ASP ne respecte pas les horaires indiqués, donc jusqu`à normalisation, le téléchargement des fichiers aura lieu toutes les heures.
Ce pourrait être du "temporaire qui dure".
Modification "à la volée" dans le sérialiseur des éléments à transférer (pas de dégradation des données de la plateforme).
Pas de revue
=> Correctif intégration fiches salarié - 06

Makefile
- Fusion des commandes `style` et `quality` : si tout le monde est d'accord.
- Commande `test` : ajout d'une option pour passer en paramètre le nombre de tests à faire tourner en parallèle.
- Suppression de commandes obsolètes.
Parce que le ménage n'est pas réservé au printemps.
J'ai mis toute l'équipe en relecture car la fusion de `style` et `quality` peut venir perturber des habitudes individuelles.
=> Simplification du Makefile

itou/users/admin.py
Permettre la gestion des `memberships` (ajout/modification/suppression) depuis la page admin des utilisateurs.
Pour résoudre une inconsistence dans l'admin qui cause confusion et perte de temps.
Avant cette PR, les `memberships` était ajoutables/modifiables/supprimables uniquement depuis la page admin orga/siae/instituion, pas depuis la page utilisateur.
Cette inconsistence m'a fait personnellement perdre du temps, ainsi qu'à Zohra et à Sarah. Voir [ce thread](https://itou-inclusion.slack.com/archives/C01181Y04LT/p1634204040079600).
Avant :
Après :
=> Permettre la gestion des `memberships` depuis la page admin des utilisateurs

itou/static/js/commune_autocomplete_field.js, itou/www/autocomplete/views.py, itou/www/employee_record_views/forms.py, itou/www/employee_record_views/views.py
Modification de l'auto-complétion lors de la première étape de saisie des fiches salarié. 
Suite à une imprécision dans le cahier des charges, l'implémentation d'une vérification d'existence du code INSEE **à la date de naissance** du salarié n'a pas été effectuée.
Lors de l'auto-complétion de la commune sur le premier écran de saisie,
la date de naissance du salarié est transmise en paramètre à l'URL de complétion (query param `date`).
Si aucune date n'est trouvée dans le formulaire, le 01/01/1900 est pris pour borne basse de la période (minima dans les référentiels ASP).
Les résultats sont filtrés pour ne ressortir que les codes existant à la date de naissance du salarié.
=> Code de communes INSEE historisés

itou/users/admin_forms.py
Quand `approvals_wrapper` est vide, la création plante, ce qui bloque le support
En prenant plus de précautions avant d’accéder à `latest_approval`
=> Correction de la création de comptes demandeurs via l’admin

config/settings/prod.py, config/settings/review_apps.py, itou/www/approvals_views/views.py, requirements/deploy.txt
Mise à jour de l'agent Elastic APM
Pour corriger l'erreur levée avec `httpx`
En passant le paquet `elastic-apm` à la version 6.6.0
=> Mise à jour de l'agent Elastic APM

itou/eligibility/admin.py, itou/siaes/admin.py, itou/users/admin.py
Un batch d'améliorations mineures.
- Permettre la recherche par PK (demande de Sarah).
- Permettre la recherche par NIR (demande de Sarah).
- Bugfix sur le champ notifications au niveau des structures qui était éditable sans raison et prenait trop de place.
- Bugfix sur l'ajout de nouvelles memberships qui n'était pas possible (structures+organisations+institutions) car le champ PK n'était pas éditable.
- Bugfix sur le champ "modifié par" au niveau des institutions qui était éditable sans raison.
- Montrer l'ID ASP de structure ASP. Logique puisqu'on le montre déjà côté FS.
- Bugfix sur le champ notifications qui était éditable sans raison et prenait trop de place.
- Bugfix sur les fiches de poste : les champs "date de création" et "date de modification" ne sont plus éditables.
=> Petit boost admin

.github/workflows/imports-asp.yml, .github/workflows/populate-metabase.yml
Correction de la configuration des cronjobs.
Ils doivent utiliser `c1-fast-machine-config` et non `c1-prod-config`.
Sans quoi les cronjobs se mettent à envoyer des Fiches Salarié !
Voir [ce thread](https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1635849885014500).
=> Correction de la configuration des cronjobs

itou/approvals/models.py, itou/templates/approvals/declare_prolongation.html, itou/templates/approvals/includes/status.html, itou/utils/templatetags/js_filters.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_prolongation.py, itou/www/approvals_views/views.py
Une prolongation doit pouvoir être validée sans saisie de l'email d'un prescripteur habilité.
Le nouveau décret précise qu'une SIAE a la possibilité de prolonger un PASS IAE sans accord préalable d'un prescripteur habilité pour 2 motifs :
- CDI conclu avec une personne âgée de + de 57 ans
- Fin de formation
Retirer le champ "email d'un prescripteur habilité" si l'un des deux motifs ci-dessus a été sélectionné 
Champs "Email" masqué pour un des deux motifs :
Champs "Email" affiché pour les autres motifs :
=> Les employeurs peuvent prolonger un PASS IAE sans l'avis d'un prescripteur habilité pour deux motifs

itou/users/admin_forms.py
Suite à une modification du formulaire du User dans l'interface d'Admin, le mot de passe des utilisateurs n'était plus modifiable depuis cette interface.
Le formulaire User n'héritait pas de la class Django User de base/
=> Fix la fonctionnalité de modification du mot de passe depuis l'interface d'admin

scripts/imports-asp.sh
L'import des EA ne se fait plus me semble-t-il dans le script `import-asp.sh`
Le script d'import des EA a été commenté dans l'import ASP hebdomadaire depuis 2 mois.
- J'ai exécuté le script manuellement, et il ne semble pas planter, voir [ce thread slack 👀👀](https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1636104781076100)
- @Keirua t'as peut être d'autres infos que je n'ai pas vu ?
=> Le script d'import des EA est manquant dans l'import ASP hebdomadaire

itou/api/employee_record_api/tests.py, itou/employee_record/serializers.py
Les deux champs téléphone et e-mail ne sont plus envoyés à l'ASP mais doivent l'être à l'API destinée aux éditeurs de logiciels. 
Certains éditeurs se servent de l'adresse e-mail comme identifiant pour faire des recoupements.
Les champs n'étaient pas marqués comme optionnel et pour certains ils sont donc implicitement obligatoires.
Il faut donc assurer une compatibilité.
Laisser les champs vides pour l'export ASP (comportement actuel), mais les fournir dans l'API.
=> Les champs e-mail et téléphone sont disponible dans l'API FS

itou/job_applications/models.py, itou/www/apply/forms.py, itou/www/apply/tests/tests_process.py
Suppression des contrôles sur la date de fin d'embauche et la durée maximum d'un PASS IAE (ajoutés dans #666).
> Maintenant que le module de prolongation est opérationnel, il ne faut plus bloquer.
> Nous ne sommes pas garants des dates des contrats, donc c'est à l'employeur de s'assurer que la durée du contrat sera couverte.
=> Suppression des contrôles sur la date de fin d'embauche et la durée maximum d'un PASS IAE

config/settings/base.py, itou/templates/500.html, itou/templates/approvals/pe_approval_search_found.html
Le lien était cassé (affichage d'une page blanche). Il dirige désormais vers la page d'assistance du portail de la Communauté.
=> Mise à jour du lien vers le portail d'assistance

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/www/apply/forms.py
Affichage d'un message d'erreur au DE autonome en cas de doublon.
Un DE se connecte avec son compte qui n'a pas de NIR. Il ne sait pas qu'un autre compte existe avec son NIR. Quand il tente de candidater, il est bloqué. Actuellement, une erreur 500 apparaît. Ce n'est pas sympa.
Message d'erreur.
=> Affichage d'un message d'erreur en cas de doublon DE autonome

itou/common_apps/address/format.py, itou/employee_record/models.py
Corrections des erreurs restantes remontées sur Sentry, relatives au fiche salarié.
- nettoyage du Sentry
- correction d'un bug du au décallage possible de l'état de la convetion d'une SIAE entre deux imports ASP
- tests de la validité de la convention lors de la saisie -> notification à l'utilisateur
- rafraîchissement du SIRET et de l'ID ASP avant envoi de la fiche
- correction d'un bug mineur sur la géoloc
=> Correction d'erreurs Sentry relatives au fiches salarié

.github/workflows/imports-asp.yml, .github/workflows/populate-metabase.yml, itou/metabase/management/commands/_database_psycopg2.py, itou/metabase/management/commands/_job_descriptions.py, itou/metabase/management/commands/populate_metabase_itou.py
Améliorations diverses de la mise à jour quotidienne de Metabase avec les données C1.
Au menu :
Toutes nos github actions qui lancent une instance clever et un script dessus via un `CC_RUN_SUCCEEDED_HOOK` se heurtent à un timeout non documenté de 47 minutes. Même un `CC_RUN_SUCCEEDED_HOOK=sleep 3600` suffit à reproduire systématiquement le problème.
Clever reconnait que ce hook n'est pas fait pour des scripts longs. A la place, ils recommendent d'utiliser soit un worker, soit un cron, soit du ssh programmatique.
Le SSH programmatique est techniquement possible (e.g. `echo sleep 300 | $CLEVER_CLI ssh --alias $CRON_TASK_APP_NAME`) mais risque d'ajouter pas mal de complexité et de soucis de sécurité pour déployer une clé SSH dans la github action.  Cette clé SSH donnant accès SSH à toutes …
=> Améliorations diverses de la mise à jour quotidienne de Metabase avec les données C1

itou/users/management/commands/deduplicate_job_seekers.py, itou/users/tests.py
Prise en compte du NIR dans la déduplication.
Pour traiter les doublons en tenant compte du NIR.
Si un seul NIR existe pour un jeu de doublons, il est réaffecté au compte de destination de la fusion.
=> Prise en compte du NIR dans la déduplication

itou/users/management/commands/deduplicate_job_seekers.py, itou/users/tests.py
- Gestion plus propre des logs des doublons avec export en CSV
- Export des candidats en doublon avec plusieurs NIR pour la même personne
Pour faciliter la tache de Supportix qui, sinon, aurait eu à copier-coller l'output HTML dans la console.
=> Gestion plus propre des logs des doublons avec export en CSV

.github/workflows/imports-asp.yml, .github/workflows/populate-metabase-itou.yml, .github/workflows/populate-metabase.yml, config/settings/base.py, itou/metabase/management/commands/_database_tables.py, itou/metabase/management/commands/_dataframes.py, itou/metabase/management/commands/_utils.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/utils/slack.py
Evolutions de la mise à jour quotidienne de Metabase avec les données C1.
Sont listées ci-dessous les évolutions majeures uniquement. Les mineures sont visibles commit par commit.
Sans ces notifications, nous et la github action sommes incapables de dire si le script s'est bien terminé ou non.
Un flag permet d'afficher ou non toutes les étapes, sorte de log.
Les tables temporaires (new/old/dry) ont maintenant un préfixe `Z` qui les place en toute fin de liste. Pratique pour ne pas pertuber nos utilisateurs Metabase avancés.
De plus, les dry tables (celles issues d'un dry run) ne sont plus éternelles. Chaque wet run les supprime maintenant en passant. Moins de bruit.
Soumia commence à croiser des données C1 et des données FluxIAE. Du coup ses tables custom bénéficierons de tourner chaque …
=> Evolutions de la mise à jour quotidienne de Metabase avec les données C1

itou/employee_record/models.py, itou/templates/employee_record/includes/create_step_4.html, itou/templates/employee_record/includes/employee_record_summary.html, itou/www/employee_record_views/forms.py
Permettre de ne pas saisir l'annexe financière dans le parcours de création / modification de la fiche salarié.
Beaucoup de friction à cause de possible décalages de validité de l'annexe / convention (imports hebdomadaires).
Pour au final une info dont l'ASP ne fait rien.
Permettre de ne rien saisir à l'étape 4 du tunnel de création des fiches salarié.
=> Rendre l'annexe financière optionnelle pour les fiches salarié

itou/approvals/models.py, itou/approvals/tests.py, itou/www/apply/tests/tests_submit.py
https://trello.com/c/ARkraF5B/2371-c1-pouvoir-r%C3%A9cup%C3%A9rer-un-agr%C3%A9ment-expir%C3%A9-depuis-moins-de-3-mois
Je veux prolonger un agrément expiré, mais je ne peux pas le récupérer via le module "Prolonger/suspendre un agrément Pole Emploi"
Pour limiter la charge support, on a récemment donné la possibilité aux employeurs de prolonger un PASS IAE même s'il est expiré depuis 3 mois. 
Toutefois, ils n'ont pas la possibilité de récupérer un agrément Pole Emploi expiré, donc ils ne peuvent pas prolonger cet agrément
Donner la possibilité aux employeurs de récupérer un agrément expiré depuis moins de 3 mois dans le module "Prolonger/suspendre un agrément Pole Emploi"
- introduction d’une constante pour gérer ce délai demandé par le support
- modification de la logique d’extension de …
=> Les candidatures PE peuvent être importées 3 mois après leur expiration

docker-compose.yml
Augmentation de la mémoire disponible pour le conteneur PostgreSQL.
Je ne pouvais plus utiliser la base de prod localement car sa taille était trop importante.
Mise à jour de `docker-compose.yml`.
=> Augmentation de la mémoire disponible pour le conteneur PostgreSQL

itou/api/employee_record_api/serializers.py, itou/api/employee_record_api/viewsets.py, itou/approvals/admin.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/serializers.py, itou/employee_record/tests.py, itou/job_applications/models.py
Demandes d'évolutions et améliorations sur les fiches salarié.
- meilleure prise en charge par le support,
- éviter un  message d'information peu clair lors de la saisie des F.S.,
- évolutions de l'API demandées par les éditeurs de logiciel tiers,
- augmentation du nombre de fiches salarié à chaque envoi.
- blocage préventif de l'affichage et de la possibilité de créer 2 fiches salariés pour deux structures d'une même "entité" ASP (même SIRET mais types de SIAE différents)
- affichage de l'état de la fiche salarié correspondante dans la section "candidature" de l'admin du PASS IAE (si existante)
- ajout d'un champ pour le NIR dans l'API fiche salarié (si disponible)
=> Evolutions fiches salarié 

config/settings/base.py, itou/templates/layout/_footer.html, itou/templates/stats/stats.html, itou/templates/stats/stats_pilotage.html, itou/utils/apis/metabase.py, itou/utils/settings_context_processors.py, itou/www/stats/views.py
Ajout d'une url pour pouvoir visualiser des dashboards avec des ids particuliers.
Suite à la précédente [pr](https://github.com/betagouv/itou/pull/974) nous avons constaté un problème de scroll sur la page et que les titres de dashboards n'étaient plus affichés.
Ce fonctionnement est dû au fait que la bibliothèque iframeResizer a besoin d'être implémenté dans les deux sens (le parent et l'iframe) 👉👉 [voir la doc d'iframe-resizer](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.js#L4)
L'appel par défaut de l'url de metabase ajoute l'argument `#titled=false`
- [Pour aller plus loin dans la communication cross iframes](https://benohead.com/blog/2015/12/07/cross-document-communication-with-iframes/)
=> Ajout d'une page de stats à charger dans une iframe 2

itou/static/js/city_autocomplete_field.js, itou/static/js/commune_autocomplete_field.js
Augmentation du délai de l'autocomplétion
L'URL de destination est en top impact de L'APM (pas lente mais très sollicitée).
Augmentation du délai dans le javascript qui déclenche l'appel.
=> Augmentation du délai de l'autocomplétion

itou/job_applications/models.py
Disparition de l'affichage de certaines fiches valides
Dans le cas ou la création de la fiche salarié ne va pas jusqu'au bout (interruption par l'utilisateur),
un retour à la liste des fiches salarié à saisir n'affiche plus la fiche modifié.
=> Filtre mal foutu
Modification du filtre : ajout d'une condition (bloque l'affichage des fiches pour une SIAE différente de l'actuelle et pas simplement avec le même `asp_id`).
Pas de revue : HOTFIX
=> Fix filtre d'exclusion des SIAE de même ASP ID

itou/job_applications/models.py
Remise à zéro des champs concernant l'attribution du PASS IAE lors qu'une candidature est annulée.
Lorsqu'une embauche est de nouveau acceptée après une annulation, le Pass IAE ne peut pas être généré ([carte Trello](https://trello.com/c/ZQBiFsQV)).
Lors de l'annulation de l'embauche, les champs sont remis à 0.
=> Suppression des infos liées au PASS IAE sur les candidatures annulées

itou/approvals/models.py, itou/approvals/tests.py
Permettre aux utilisateurs "SIAE" + " Prescripteurs habilités" de déclarer une suspension jusqu'à 30 jours avant la date du jour dans deux cas précis : 
- Quand la date du début du PASS IAE est supérieur à 30 jours
- Quand la date du début d'embauche est supérieur à 30 jours
Quand l'une des deux conditions ne sont pas respectées, la suspension pourra être déclaré rétroactivement jusqu'à la date de début du PASS IAE.  
Changement de loi qui limite l'activation rétroactive d'une suspension après 30 jours. 
Ouvrir le droit à la rétroactivité à 30j (pour les PASS et les agréments PE importés)
SI le PASS a moins de 30 jours ce sera au plus tot la date de démarrage du PASS
[Carte trello](https://trello.com/c/VPDSCHDA/2359-r%C3%A9troactivit%C3%A9-de-la-suspension)
=> Limite de la rétroactivité des suspensions à 30 jours avant la date du jour

requirements/base.txt, requirements/deploy.txt
Mise à jour de Django, Elastic APM et Sentry
Une CVE a été publiée sur Django : 
https://www.djangoproject.com/weblog/2021/dec/07/security-releases/
Mise à jour des paquets Python.
=> Mise à jour de Django, Elastic APM et Sentry

itou/approvals/models.py, itou/approvals/tests.py, itou/job_applications/models.py, itou/users/models.py, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py, itou/www/apply/views/submit_views.py
Permettre la levée anticipée d'une suspension dès lors qu'un employeur valide une embauche
UNIQUEMENT POUR LES SUSPENSIONS POUR MOTIF "contrat de travail terminé ou contrat de travail rompu"
Date de fin de suspension = J-1
Actuellement seul l'auteur de la suspension peut la lever/modifier
C'est bloquant pour une nouvelle embauche
1. Se connecter comme `EI` sur la structure par défaut (`EI Garage Martinet Siège`)
2. Suspendre le PASS IAE de `**Jacques Henry**` pour un an avec l'un des deux motifs suivants : Contrat de travail rompu, Contrat de travail terminé
3. Soit :
1. Se connecter avec le compte candidat 
2. Se connecter avec le compte de prescripteur et postuler pour `test+de@inclusion.beta.gouv.fr`
4. Choisir une offre d'emploi, comme par exemple : …
=> Permettre de lever une suspension au moment de l'embauche [En attente de la PR #983]

itou/approvals/models.py, itou/approvals/tests.py, itou/www/apply/tests/tests_submit.py
Reverts betagouv/itou#977
Des agréments expirés sont récupérer hors du module de prolongation.
=> Revert "Les candidatures PE peuvent être importées 3 mois après leur expiration"

itou/metabase/management/commands/_approvals.py, itou/metabase/management/commands/_job_applications.py
Ajout de la colonne is_from_ai_stock (injection_ai) aux tables Candidatures et Agréments dans Metabase
L'import des AI a créé beaucoup de candidatures fantômes qui polluent les stats Metabase. Cette nouvelle colonne va permettre à Soumia de les filtrer.
=> Ajout de la colonne `is_from_ai_stock` (`injection_ai`) aux tables Candidatures et Agréments dans Metabase

config/settings/base.py, itou/approvals/models.py, itou/approvals/tests.py, itou/job_applications/models.py, itou/job_applications/tests.py, itou/www/approvals_views/tests/test_download.py
Les employés annulent des candidatures et donc les PASS qui ont été délivrés. Cela ne doit pas être possible automatiquement.
=> Les candidatures issues du script des salariés ASP ne peuvent pas être annulées

itou/metabase/management/commands/sql/009_recrutements.sql
Ajouter la colonne établissements publics de coopération intercommunale (EPCI) à la table 
Donner la possibilité aux DDETS, DREETS et CD la possibilité de filtrer les recrutements à l'échelle infra-départementale
=> Analyser les recrutements par EPCI

itou/metabase/management/commands/sql/006_heures_etp_salaries.sql
Quoi ?
Ajouter la colonne établissements publics de coopération intercommunale (EPCI) à la table
Pourquoi ?
Donner la possibilité aux DDETS, DREETS et CD la possibilité de filtrer les ETP à l'échelle infra-départementale
=> Analyse des heures travaillées par les salariés en IAE à l'échelle infra-départementale

config/settings/_sentry.py, itou/utils/tests.py, itou/utils/validators.py
Mise à jour des règles de validation du NIR
Désactivation de l'envoi de transactions à Sentry
Des NIR valide ne sont pas considéré comme tel.
Le quota Sentry est dépassé.
Ajustement de la regex
Modification de la conf pour Sentry
=> Boostdev S33

itou/approvals/models.py, itou/templates/apply/list_for_siae.html
Permettre la suspension d'un PASS IAE même si la candidature associée peut encore être annulée.
Suite aux dernières modifications notamment la suppression du délai des 96 heures, les candidatures peuvent être annulée à tout moment et par conséquent, la suspension n'est plus proposée.
En retirant la condition bloquante au niveau du modèle Approval.
=> Permettre la suspension d'un PASS IAE même si la candidature est annulable

itou/users/models.py, itou/users/tests.py, itou/utils/templatetags/format_filters.py, itou/utils/validators.py
Prise en compte de subtilités dans le formatage du NIR
Suite à une modification de la validation du NIR, des erreurs apparaissent ensuite lors de l'affichage de certains NIRs qui passent désormais la validation.
Ajustement de l'expression régulière au niveau du filtre de formatage du gabarit.
=> Erreur sur le formatage de certains NIR

itou/templates/static/accessibility.html
Mise à jour de la déclaration d'accessibilité.
La restitution de l'audit d'accessibilité a eu lieue en novembre 2021. Nous devons mettre en ligne le résultat de cet audit.
Ci-dessous un _screenshot_ du texte mis à jour.
=> Mise à jour de la déclaration d'accessibilité

itou/utils/apis/pole_emploi.py
Certains paramètres sont censés −d’après la documentation− être non obligatoires en cas de pass décliné. C’est le cas du type de SIAE et de son SIRET. Il sont en fait obligatoires.
J’ai évité de mettre des données non obligatoires pour éviter de faire du zèle inutile et surtout éviter des problèmes de données incompatibles mais visiblement c’est l’inverse qui s’est produit.
Ajout de données manquantes.
=> Ajout de paramètres non obligatoires dans les appels aux API pole emploi

config/settings/base.py, config/settings/prod.py, config/settings/test.py, itou/employee_record/management/commands/transfer_employee_records.py
Bloquer les interactions avec l'ASP pour les environnements autres que PROD.
Suite à diverses erreurs de manipulations et de configuration, des environnements autres que PROD ont pu transférer des lots de fiches salarié vers l'ASP sans le contexte nécessaire, créant des conflits et des retours d'erreurs (3436) chez les usagers.
En ne permettant l'utilisation de la `management command` permettant le transfert des fiches salarié : 
- que sur l'environnement de production (par défaut),
- que si l'environnement est **explicitement autorisé** à utiliser cette commande (par les `settings` Django pour un poste de dev ou via une variable d'environnement `EMPLOYEE_RECORD_TRANSFER_ENABLED` pour les instances cloud).
=> Blocage du transfert des fiches salarié sur un environnement autre que PROD

itou/eligibility/models.py, itou/eligibility/tests.py, itou/job_applications/tests.py
On considère une éligibilité valide si un PASS IAE valide existe sans diagnostic.
Afin de ne pas forcer les SIAE à repasser par la case "Valider les critères d'éligibilité" pour une nouvelle embauche d'un candidat qui dispose d'un PASS IAE hérité de l'import des AI.
=> On considère une éligibilité valide si un PASS IAE valide existe sans diagnostic

itou/job_applications/models.py, itou/job_applications/tests.py
- Les pass refusés ne sont pas transmis à PE
- Les PASS avec une date de début dans le futur ne sont pas transmis au moment de leur acceptation.
Ils seront transmis au moment de leur début effectif par un développment ultérieur
Actions décidées suite à la réunion avec PE du 16/12
Modification des règles métier en conséquence, ajout de tests.
=> Suppression de certains PASS du process de notification Pole Emploi

itou/templates/apply/includes/job_applications_filters.html
Ajout d'un bouton sur la page qui liste les candidatures pour les employeurs et les prescripteurs.
Le lien est déjà dans le tableau de bord mais n'est pas assez visible.
=> Ajout d'un bouton pour exporter les candidatures sur la page qui les liste

itou/france_connect/models.py, itou/france_connect/tests.py, itou/templates/layout/_nav_btn_items.html
- Masquage du bouton "Modifier mon mot de passe" quand on est connecté avec France Connect (mais pas pour les autres!)
- Correction: Si un utilisateur existe déjà avec l’email transmis par France Connect, on le prend (corrige [cette erreur](https://sentry.io/organizations/betagouv-f7/issues/2867133906/?project=5671910&query=is%3Aunresolved))
=> Amélioration de l’utilisation de France Connect

itou/utils/pdf.py, requirements/deploy.txt
Boostdev pour limiter les erreurs Sentry
Il y a des erreurs de type OSError et Timeout qui surviennent régulièrement.
Mise à jour du SDK Sentry
Augmentation du délai pour les requêtes vers l'API de génération de PDF
=> Boostdev pour limiter les erreurs Sentry

itou/users/management/commands/import_ai_employees.py, itou/users/tests/test_management_commands.py, itou/users/tests/test_models.py
Prise en compte des NIR invalides.
À la suite d'un bug dans le code, nous avons créé 842 candidatures pour le même candidat. Les AI ont donc vu sur leur tableau de bord des candidatures acceptées pour un candidat qui leur était inconnu. De nombreuses plaintes sont remontées au support.
D'où provenait ce bug ?
- [Ligne 121](https://github.com/betagouv/itou/blob/master/itou/users/management/commands/import_ai_employees.py#L421), les nir invalides sont remplacés par "". C'est implicite. :see_no_evil: 
-  [Ligne 277](https://github.com/betagouv/itou/blob/master/itou/users/management/commands/import_ai_employees.py#L277), le script effectue une boucle : il trouve un User en utilisant le NIR de la ligne (`User.objects.filter(nir=row[NIR_COL])`). Mais si le NIR est vide, il trouve le premier …
=> Correction du script qui importe les salariés des AI

itou/fixtures/django/04_test_users.json
Correction sur les `fixtures` suite à une modification du modèle `user` de la [PR 1031](https://github.com/betagouv/itou/pull/1031).
Une erreur empêche le chargement des données de démo. 
Modification d'un nom de champs dans la `fixture user`.
=> Correction sur les données initiales

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/dashboard/dashboard.html, itou/www/dashboard/tests.py
Ajout d'un message informatif à destination des AI pour les accompagner pendant la reprise de stock. Ce message a été validé par la DGEFP.
Suppression de messages obsolètes.
=> Ajout d'un message informatif sur le tableau de bord des AI

itou/templates/dashboard/dashboard.html
Restriction de l'affichage du message d'information.
Le message apparaît sur le tableau de bord des candidats alors qu'il ne devrait pas.
Ajout d'un test pour identifier si on est bien sur le tableau de bord d'une SIAE
=> Le message n'est pas destiné aux candidates

itou/approvals/models.py, itou/templates/apply/list_for_siae.html, itou/www/approvals_views/forms.py
L'administrateur ne doit pas être soumis à la règle de la rétroactivité à 30 jours.
Lors de la modification d'une suspension, le délai de rétroactivité doit être calculé par rapport à la première saisie.
Certains cas nécessitent la saisie de suspension au-delà des 30 jours de rétroactivité autorisée.
La modification d'une suspension 30 jours après sa création n'est pas possible en l'état.
La vérification est déplacée au niveau du formulaire utilisateur en se basant sur la date de création.
Un contrôle reste en place côté admin pour initialiser le formulaire, éviter le chevauchement et gérer le cas des agréments.
=> Pas de limitation à 30 jours sur les suspensions pour l'admin

itou/siaes/management/commands/_import_siae/vue_af.py
Résolution d'une erreur obscure `AttributeError: 'NoneType' object has no attribute 'total_seconds'` dans l'import SIAE depuis la MAJ django 4.
L'erreur se produit depuis la récente MAJ django 4 et dépendances. Elle se produit même avec pandas `1.3.5` (nous sommes actuellement sur la `1.3.4`).
Le bug semble connu côté pandas et non résolu : https://github.com/pandas-dev/pandas/issues/43516
Il semble se produire quand on itère sur les rows d'une df contenant des timezone aware datetimes.
La source de l'erreur fut difficile à trouver car l'erreur se produit au moment de l'itération sur la df et non au moment où les datetimes problématiques sont créées dans la df.
La solution est un pur contournement : on transforme les datetimes en "timezone aware" datetimes uniquement à la volée, sans …
=> Résolution d'une erreur obscure `AttributeError: 'NoneType' object has no attribute 'total_seconds'` dans l'import SIAE depuis la MAJ django 4.

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/_import_siae/financial_annex.py
Gestion automatique de la crise annuelle des AF manquantes côté ASP.
Chaque semaine l'ASP nous envoit ses données. Une SIAE est dite conventionnée si et seulement elle a au moins une AF valide à date. Or chaque début d'année, les AF de la nouvelle année sont très en retard. Le 1er janvier 2022 il n'y aura toujours aucune AF pour 2022, du coup en théorie toutes les SIAE sont déconventionnées.
Avant :
Un dev C1 devait manuellement mettre un flag pour stopper les déconventionnements, puis quelques mois plus tard retirer ce flag pour reprendre les déconventionnements.
Après :
Tout est automatisé. Le 1er janvier, quand 100% des SIAE devraient être déconventionnées, le script suspend automatiquement tout déconventionnement. Il attend que le nombre de SIAE à déconventionner retombe en dessous de …
=> Gestion automatique de la crise annuelle des AF manquantes côté ASP

itou/metabase/management/commands/sql/007_suivi_consommation_etp.sql
Modification du script qui permet de calculer la moyenne des ETP consommés depuis le début d'année
Pour gérer les cas suivants : 
- En Janvier de l'année en cours, moyenne_nb_etp_depuis_debut_annee = (consommé sur l'année n-1) / (le dernier mois travaillé sur l'année n-1)
- Afficher la bonne moyenne pour les structures qui sont en retard de saisie dans l'ASP
=> Modification de l'indicateur consommation des ETP

itou/templates/dashboard/dashboard.html
Suppression du message GTA du dashboard AI 🔪
Sur demande express de Eric.
Trivial donc pas de revue.
=> Suppression du message GTA du dashboard AI 🔪

itou/job_applications/models.py
Bugfix de la pagination des candidatures.
Avant ce bugfix, une même candidature pouvait remonter sur la page 1 et la page 2.
En utilisant un tri secondaire sur la clé primaire, qui permet de rendre la pagination déterministique. Avant cela, en raison des exports AI, de nombreuses candidatures avaient exactement la même date de création et la pagination n'était donc pas déterministique.
=> Bugfix de la pagination des candidatures

itou/templates/employee_record/list.html
Ajout d'un message d'erreur concernant les problèmes de tranfert vers l'ASP.
Depuis le 27 décembre à midi, suite à une modification technique des serveurs ASP, les connexions sont impossibles.
Dans l'attente d'un rétablissement de la connexion, un message informatif est affiché dans la rubrique fiche salarié.
=> Ajout d'un message d'information temporaire

itou/employee_record/management/commands/transfer_employee_records.py
Ajout d'options de connexion SSH / SFTP à `paramiko` / `pysftp`
L'ASP a procédé à une mise à jour de ses serveurs SFTP le 27.12.2021 vers midi.
Depuis aucun transfert de fiches salarié n'est possible.
Apparement les serveurs MAJ ne considèrent plus une connexion via certificat RSA comme valide par défaut.
Il est nécessaire d'ajouter une option de connexion SSH custom : `PubkeyAcceptedKeyTypes=+ssh-rsa` (via `pysftp` ou dans la config ssh).
Probablement du au fait que `openssh` considère désormais RSA-SHA1 comme `deprecated`
RSA sera à terme supprimé de `openssh`. 
Il est nécessaire de passer en ECDSA aussi vite que possible et l'ASP en a été notifié.
=> HOTFIX - Correction RSA pubkey suite à MAJ serveurs ASP

itou/employee_record/management/commands/transfer_employee_records.py, itou/templates/employee_record/list.html, requirements/base.txt
MAJ des serveurs ASP, part 2 : the Revenge of paramiko.
Le problème de transfert des fiches salarié est en fait double : 
- une MAJ des serveurs ASP le 27/12/2021 parasitant l'échange de clés RSA
- une MAJ d'une dépendance de `pysftp` (`paramiko`) le 23/12/2021 qui modifie la priorité de l'échange en RSA si d'autres options sont disponibles
Lors de la première MEP après le 23/12, l'installation de `pysftp` via `pip` a installé la version 2.9.2 de `paramiko` en dépendance (et mis le bazar).  
- Downgrade explicite dans les `requirements` de `paramiko` en version 2.8.1 (les versions >= 2.9.0 ont le "problème")
- retrait du message informatif à destination des utilisateurs
Voir le changelog de `paramiko`, à la section 2.9.0 :  
https://www.paramiko.org/changelog.html
=> HOTFIX - Retour des transferts de fiches salarié

itou/templates/dashboard/dashboard.html
Ajout d'informations pour les structures utilisant les fiches salarié.
Pour indiquer que la fin de validité des annexes financières pour l'année 2021 n'a pas d'incidence sur la saisie des fiches salarié.
=> Ajout d'un message d'information sur le dashboard - fiches salarié et annexes financières

requirements/base.txt
Passage à django 4.0.1, le composant clé du projet.
Mise à jour de sécurité [publiée aujourd’hui](https://www.djangoproject.com/weblog/2022/jan/04/security-releases/).
On utilise 2 des 3 éléments concernés, le problème est surtout le risque de DOS:
```bash
$ grep UserAttributeSimilarityValidator
config/settings/base.py
190:    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
```
Ceci dit l’injection dans `dictsort` ne semble pas possible car on hardcode la clé, mais même si c’était le cas le risque serait très localisé donc faible.
```bash
$ grep dictsort
itou/templates/apply/includes/eligibility_diagnosis.html
32:                    {% regroup administrative_criteria|dictsort:"level" by get_level_display as levels %}
80:                        {% …
```
=> Mise à jour de sécurité django 4.0 -> 4.0.1

itou/metabase/management/commands/sql/005_suivi_saisies_dans_asp.sql
Inclure les données de l'année n-1
Afficher la bonne date de dernière saisie dans l'asp (même sur l'année n-1) pour les structures qui sont en retard de saisie dans l'ASP
=> Suivi des saisies dans l'ASP

itou/templates/dashboard/dashboard.html, itou/users/models.py, itou/users/tests/test_models.py, itou/www/dashboard/views.py, itou/www/siaes_views/views.py
Permettre aux EA et GEIQ de créer à nouveau leurs antennes.
Suite à un [récent hotfix pas beau](https://github.com/betagouv/itou/commit/5c139c5151e36e34a6f6c356d7cfa17e8658d925) de période de fête, les EA/GEIQ ne pouvaient plus créer leurs antennes.
Refactorisation avec une méthode bien propre dans le modèle et des tests.
=> Permettre aux EA et GEIQ de créer à nouveau leurs antennes

itou/approvals/models.py
Correction d'une méthode qui faisait casser les tests uniquement pendant les années bissextiles.
Il est possible de décaler le début d'un PASS IAE s'il n'a pas encore commencé. Cela modifie la date de début et de fin. Or la manière dont nous calculions la nouvelle date de fin était inexacte.
Comme l'a bien expliqué @SebastienReuiller qui a trouvé l'origine du problème :
>  On vient récupérer un Pass IAE existant et on met à jour la date de début par rapport à la date de début du dernier contrat. Sauf que pour faire ça, quand on fait ça, on veut aussi décaler la date de fin en conséquence et pour ça on calcul l’intervalle de temps entre la nouvelle date de début et l'ancienne (qui est de 28 en ce moment dans le test qui foire car on revient un mois en arrière en chevauchant février !! ) et …
=> Correction du calcul de la fin des agréments reportés pendant les années bissextiles

itou/metabase/management/commands/sql/013_heures_etp_salaries_par_mois.sql
Suivre l'évolution mensuelle du nombre de salariés en insertion, des heures travaillées et du nombre d'ETP 
Un nouveau besoin a émergé suite au déploiement des tableaux de bord privés destinés au DDETS et DREETS : suivre de manière mensuelle la consommation des ETP
=> Suivi mensuel des heures travaillées par les salariés en insertion

itou/siaes/models.py
Amélioration de la documentation des champs SIRET.
Récemment @Keirua a travaillé sur un export qui incluait le SIRET à la signature, champ qui est présent dans le C1 mais obscur par manque de documentation.
=> Amélioration de la documentation des champs SIRET

itou/siaes/management/commands/move_siae_data.py
Modification du script permettant de déplacer les données d'une SIAE à une autre pour permettre de déplacer uniquement les candidatures.
Pour pouvoir juste basculer les candidatures dans le cas d'un changement de SIRET (déménagement).
En ajoutant une option pour ne déplacer que les candidatures. Les fiches de poste ne sont pas déplacer dans ce cas. Les candidatures déplacées apparaissent alors comme "Candidatures spontanées".
=> Transfert de candidatures d'une SIAE à une autre

itou/metabase/management/commands/_job_applications.py
Ajout de la colonne "ID organisation prescripteur" dans la table des candidatures Metabase.
Pour que Soumia puisse enfin croiser cette table avec la tables des organisations prescripteur.
=> Ajout d'une colonne dans Metabase

clevercloud/cron.json
Changement d'horaires dans le cron
Demande de l'ASP
MAJ du crontab pour effectuer l'upload toutes les 2 heures (au lieu de toutes les heures).
=> FIX: Maj des horaires du transfert des fiches salarié

config/settings/dev.py.template
Mise à jour des variables environnement de dev dans le fichier de config de template.
Afficher par défaut l'écran de sélection des comptes de test sur la home en localhost.
Ajout de la variable SHOW_TEST_ACCOUNTS_BANNER  à True.
=> Afficher par défaut la bannières des comptes de test en environnement de dev

itou/approvals/admin.py, itou/templates/account/login.html, itou/templates/siaes/includes/_list_siae_actives_jobs.html, itou/templates/siaes/job_description_card.html, itou/templates/signup/includes/france_connect_button.html, itou/users/admin.py, itou/www/siaes_views/tests.py
Les modifications boost demandées pour le sprint / release 34 :
- ajout de la date de naissance dans l'affichage en liste des PASS IAE et des utilisateurs.
- modification des marges pour les boutons de login.
- affichage des 5 derniers recrutements avec une option pour afficher les suivants (recherche de SIAE).
- corrections mineures (typos).
Session de boost classique
En retard
Recherche SIAE / recrutement :
=> BOOST : Sprint 34

config/settings/base.py
Modification de la date de mise en disponibilité de la fonctionnalité des fiches salarié (du 01.07.2021 au  01.09.2021 qui était la date originelle).
Cette date à déjà été modifiée par le passé pour pouvoir englober un "pool" plus important de candidatures à traiter.
Retour en arrière nécessaire, puisqu'on voit des fiches apparaître en doublon (c'était une demande DGEFP / ASP).
Pour info le mécanisme en question était destiné à une mise en production progressive de la fonctionnalité (l'ASP a coupé court et "the rest is history").
Dans les `settings` il y a une date `EMPLOYEE_RECORD_FEATURE_AVAILABILITY_DATE` qui est par la suite utilisée dans [un filtre d'affichage pour les fiches salarié](https://github.com/betagouv/itou/blob/b9c195df1691b9ca8d972f7e89455771de6e92ad/itou/job_applications/ …
=> Modification de la date de mise en production des fiches salarié

Makefile
- Ajout de documentation précisant les librairies nécessaires à l'utilisation de cette commande. Elles ne sont pas installées par défaut car cette commande, bien que très utile, est rarement utilisée.
- Mise à jour des modèles générés sur le graphique.
La commande `make graph_models_itou` permet de générer un graphique représentant le schéma de données.
=> Mise à jour de la documentation dans le Makefile

config/settings/_sentry.py
Ne pas remonter les informations du niveau `WARNING` en tant qu’événement Sentry.
Génère un volume trop élevé d'information qui explose le seuil du Sentry proposé par Beta. 
- retour à la valeur par défaut pour les événements Sentry  (`ERROR`).
- passage à une instance Sentry gérée par Itou.
=> Sentry : stop warnings

itou/utils/emails.py, requirements/deploy.txt
Modification du niveau de log de Huey.
Bonus : upgrade de sentry en v1.5.3
Pour éviter de polluer les logs avec tous les messages d'actions asynchrones.
Passage du niveau de logs de Huey de `INFO` à `WARNING`.
=> Niveau de log Huey

config/settings/base.py, itou/utils/settings_context_processors.py
Le bouton "Besoin d'aide" envoie maintenant vers une page d'aide C2 et non C1 si on est sur une page stats.
Lien C1 : https://communaute.inclusion.beta.gouv.fr/aide/emplois
Lien C2 : https://communaute.inclusion.beta.gouv.fr/aide/pilotage
La tête du bouton : 
Pas mal d'utilisateurs C2 viennent sur le C1 uniquement pour avoir accès aux TDB privés (DDETS, DREETS...). Du coup il est pertinent que le bouton "Besoin d'aide" renvoit vers la page d'aide C2 et non C1 si on consulte une page stats.
=> Le bouton "Besoin d'aide" envoie dorénavant vers une page d'aide C2 et non C1 si on est sur une page stats.

Makefile
La commande `make setup_git_pre_commit_hook` ne pointe vers aucune cible.
Vermeer / 29.01.2022 / canal slack #tech :  "Bien vu le setup_git_pre_commit_hook est un vestige, tu peux le virer du repo public stp."
Suppression de la commande dans la liste des cibles dans .PHONY
=> Suppression de la commande setup_git_pre_commit_hook dans Makeflie

itou/templates/apply/list_for_siae.html, itou/templates/apply/process_base.html, itou/templates/dashboard/dashboard.html
Suppression de deux boutons et ajout d'un message d'information sur le tableau de bord.
Nous ne pouvons plus générer de PDF car PDF Shift rencontre un problème technique.
=> Désactivation temporaire du téléchargement des PASS IAE

itou/templates/admin/base_site.html
Modification du contraste et / ou de la taille des `checkbox` (et éventuellement autres éléments comme les `radio`) sur le site d'administration.
Ces éléments manquent de contraste et / ou sont trop petits pour une utilisation par des personnes ayant des problèmes de vision.
Modification du template d'admin par défaut de Django via un ajout de CSS dans la balise `HEAD` de la page.
=> Modification des éléments à cocher dans le site d'admin

itou/templates/apply/list_for_siae.html, itou/templates/apply/process_base.html, itou/templates/dashboard/dashboard.html
Retour des boutons de téléchargement des PASS IAE et suppression du message d'information sur le tableau de bord.
PDF Shift, le service que nous utilisons pour générer les PDF, est de nouveau disponible.
=> Réactivation du téléchargement des PASS IAE

itou/job_applications/models.py, itou/users/tests/test_management_commands.py
Suppression du log d'erreur sur les diagnostics
Ajout d'un flag "CI" sur des tests de commandes.
Pour limiter les erreurs sur Sentry.
Pour que les tests soient plus rapides en local.
Suppression de l'envoi de l'erreur car c'est désormais possible d'accepter une embauche sans diagnostic ([PR](https://github.com/betagouv/itou/pull/1028))
Un décorateur sur les tests permets de ne jouer ceux-ci que si la variable d'environnement `CI` est définit à `True`.
=> Suppression du log d'erreur sur les diagnostics et ajout d'un flag "CI" sur les tests

itou/templates/apply/list_for_siae.html
Le lien retour depuis la carte candidature vers la liste des candidatures reçues, intègre les filtres de recherche utilisés
url de la carte candidature : /apply/_job_application_id_/siae/details
url de la liste des candidatures : /apply/siae/list
Lorsque l'utilisateur utilisait des filtres pour sa recherche de candidatures, ces filtres etaient perdus après la consulation d'une candidature: 
Scénario :
* J'applique un filtre sur les candidatures.
* Je consulte la candidature
* Je clique sur retour
* Le filtre s'est désactivé et j'ai de nouveau toutes les candidatures
Ajout du parametre `?back_url={{ request.get_full_path|urlencode }}` dans le template `apply/list_for_siae.html`
Ce parametre est interprété par `get_safe_url(request, "back_url", …
=> Filtre lien retour candidatures

itou/siaes/management/commands/move_siae_data.py
Le script move_data_siae option job_applications_only, transfère les candidatures d'une SIAE à une autre de même type.
- Les logs du traitement annoncent le nombre de candidatures transférées, mais rien sur le nombre de candidatures de la SIAE de destination, ni sur les décomptes post migration.
MOVE JOB APPLICATIONS OF siae.id=3852 - EI 34445638900019 - Job insertion 90
| Job applications sent: 0
| Job applications received: 6
INTO siae.id=3850 - EI 34445638900016 - EI Garage Martinet Siège
- le champ job_application.updated_at n'est pas mis à jour par le traitement de migration
-    ajout de compteurs AVANT/APRÈS la migration dans le logger
-    proposition d'evolution en mode dry-run
MOVE JOB APPLICATIONS OF siae.id=3852 - EI 34445638900019 - Job insertion 90
| Job applications sent: 0 …
=> enrichissement log de controle du script move_data_siae

CHANGELOG.md, itou/templates/dashboard/dashboard.html
Un message concernant les annexes financières apparaît en double sur le tableau de bord.
Parce que c'est moche.
Probablement, un mix entre différentes PR.
Il s'agit de ce message :
=> Modification du dashboard : retrait d'un message d'info en double

itou/metabase/management/commands/sql/007_suivi_consommation_etp.sql
Mise à jour du script qui alimente le suivi de la consommation des ETP
Afficher la consommation des ETP de l'année n-1 tant que les données de l'année n ne sont pas saisies dans l'ASP
=> Mise à jour du suivi de la consommation des etp

requirements/base.txt
Montée de version suite à une [mise à jour de sécurité](https://www.djangoproject.com/weblog/2022/feb/01/security-releases/). Les failles ne nous concernent probablement pas.
Cette montée de version corrige 2 problèmes concernant:
1) la **gestion de `debug` dans les template**. Nous ne somme sans doute pas concernés (`rg debug -t html` ne renvoie aucun résultat)
2) la **gestion des formulaires multipart**. [La faille](https://github.com/django/django/commit/f9c7d48fdd6f198a6494a9202f90242f176e4fc9) consiste à envoyer une requête malicieuse afin de déclencher une boucle infinie. Si je comprends bien nous ne sommes pas concernés, car:
- le composant impacté est utilisé dans les modèles
- notre seul upload public passe par S3 (via `boto3`, cf `utils/storage/s3.py` et a lieu dans …
=> Django passe de 4.0.1 à 4.0.2

itou/job_applications/admin.py, itou/job_applications/admin_forms.py
Empêcher notre support d'entrer dans l'admin certaines données incohérentes.
Récemment Zohra et Eric, chacun de leur côté, ont entré manuellement une candidature avec une SIAE émettrice manquante. Cela a provoqué des erreurs 500 dans le script Metabase quotidien, et aurait très bien pu causer des erreurs 500 ailleurs dans le code C1, puisqu'une candidature avec un `sender_kind` employeur est supposée toujours avoir une `sender_siae`.
En bétonnant l'admin.
=> Empêcher notre support d'entrer dans l'admin certaines données incohérentes.

config/settings/base.py, envs/dev.env.template
The default should be the production ones, in order to avoid having
debug values in production.
Since we don't want to set the loglevel to DEBUG for DRF, Django base
logs, etc in development, introduce a new specialized env var for the
application logs.
Faire en sorte que sans configuration spéciale, le niveau des logs applicatifs soit INFO.
On avait DEBUG par défaut ce qui est assez dangereux.
En ontroduisant une nouvelle variable d'env avec une valeur par défaut plus raisonnable.
=> config: Set ITOU app log level to INFO by default

config/settings/dev.py.template, itou/fixtures/django/10_eligibility_diagnoses.json, itou/www/approvals_views/tests/test_download.py, itou/www/approvals_views/views.py
Permettre le téléchargement des PASS IAE en dev/staging/demo.
Ce n'etait plus possible or c'est utile.
En ajoutant les fixtures de diagnostics d'ligibilité qui sont censés être requis.
=> Permettre le téléchargement des pass IAE en staging & démo

itou/approvals/models.py, itou/templates/approvals/suspend.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_suspend.py
Modification du formulaire de suspension des PASS IAE
Pour permettre à l'utilisateur de ne pas saisir de date de fin de suspension.
A l'aide d'une case à cocher dans le formulaire, permettant :
- de fixer la date de fin de suspension le plus loin possible (+12 mois actuellement),
- de masquer le champ de saisie de la date de fin si l'on choisi cette option.  
-
=> Ajout d'une date de suspension de PASS IAE par défaut

.github/workflows/ci.yml, docker/dev/postgres/Dockerfile
- Montée de version locale à postgres 14
- Infos de migration
On souhaite passer à la version 14
Les répertoires locaux sont incompatibles d’une version à une autre. Si on monte juste la version de postgres, on ne peut plus démarrer docker:
```
The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 14.1 (Debian 14.1-1.pgdg110+1).
```
Il faut donc bien supprimer les volumes, forcer le rebuild et refaire un import de base:
```
$ docker-compose down
$ docker rm -f $(docker ps -a -q)
$ docker volume rm $(docker volume ls -q)
$ docker-compose up --build --force-recreate
$ make postgres_restore_latest_backup
$ make run
$ make django_admin COMMAND=set_fake_passwords
$ make shell_on_postgres_container 
docker exec -ti itou_postgres /bin/bash …
```
=> Migration locale de docker vers PostgreSQL 14

itou/users/models.py, itou/users/tests/test_models.py
Changement des critères de sélection de la dernière embauche pour un candidat.
Dans certains cas (limites), la date de création de la candidature n'est pas discriminante pour savoir quelle SIAE a effectuée la dernière embauche pour un candidat donné.
On se base désormais sur 2 champs, la date de création de la candidature et la date d'embauche.
=> Modification du contrôle de la dernière embauche pour les suspensions

itou/users/models.py, itou/users/tests/test_models.py, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_suspend.py
`keyerror`dans Sentry, `clean`, pas assez testé
Fixer le fix : ajout d'un test
Défensif sur la lecture de `cleaned_data`
=> HOTFIX - date de suspension 

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests.py
Modifications mineures et tests ajoutés pour border les calculs de date minimum de départ des suspensions.
Les règles de calcul de la date de départ de la suspension ont été modifiées, mais non-testées.
Pour l'admin, il est parfois difficile de retrouver une suspension quand on part du numéro de PASS IAE.
- ajout de tests unitaires pour `Suspension.next_min_start_date`.
- ajout de champs de recherche dans l'admin des suspensions (ID, numéro de PASS IAE).
=> Modification de la cohérence de la date de départ des suspensions

docker/dev/django/Dockerfile
Mise à jour de la version du client PostgreSQL pour le container Django
Suite à la [montée de version de PostgreSQL](https://github.com/betagouv/itou/pull/1084), le container postgres est bien en v14, mais le client psql dans le container django n’a pas suivi la montée de version:
```bash
$ docker exec -ti itou_postgres /bin/bash
root@774124155de5:/# psql --version
psql (PostgreSQL) 14.1 (Debian 14.1-1.pgdg110+1)
$ make shell_on_django_container
docker exec -ti itou_django /bin/bash
app@43144ba6846c:~$ ./manage.py dbshell
psql (12.9 (Debian 12.9-1.pgdg100+1), server 14.1 (Debian 14.1-1.pgdg110+1))
WARNING: psql major version 12, server major version 14.
Some psql features might not work.
```
Cette PR corrige ce problème. Une fois le container recréé:
```bash
docker-compose down
docker rm …
```
=> Montée de version du client Postgres dans le container django

itou/approvals/models.py, itou/approvals/tests.py
Il est parfois impossible de créer une suspension pour les agrément PE qui ont été migrés en PASS IAE
Dans un cas précis, la date de départ de la suspension génère une `type error` à cause d'une date minimale non renseignée.
Ajout de code un peu plus défensif pour éviter l'erreur
**MAIS** :
- une passe métier doit être faite sur les règles d'établissement de la date minimale de suspension,
- une fois les règles à plat, il faudra border cette partie par des tests.
=> HOTFIX: modification de la date minimale de suspension pour les anciens agréments PE

itou/templates/apply/list_of_available_exports.html, itou/templates/includes/members.html, itou/templates/invitations_views/create.html, itou/templates/invitations_views/includes/pending_invitations.html, itou/templates/prescribers/list_accredited_organizations.html, itou/templates/siaes/includes/_configure_jobs_list.html, itou/templates/siaes/show_financial_annexes.html, itou/templates/signup/siae_select.html
Correction des erreurs a11y sur les tableaux
Pour mettre en conformité le site avec les règles d'accessibilité et respecter les recommandations de l'audit
En respectant les règles RGAA 5.1/5.2 et en ajoutant un titre aux `<table>` via la balise `<caption>`
https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-5-1
Remplacement des role aria info (qui n'existent pas) par des role status
=> Correction des erreurs a11y sur les tableaux

docker/dev/django/Dockerfile
Permettre de lancer l'application sous Docker avec postgres 14 sur un mac doté d'une puce M1.
libpq et psycopg ne sont pas encore fonctionnels dans leur version binaire pour les puces M1, en tout cas pas
dans la dernière version 14.
https://stackoverflow.com/questions/69573312/python-psycopg2-scram-authentication
We need to recompile psycopg2 to accomodate the M1 chips, since it's not
yet distributed properly in its binary version.
Same goes for libpq-dev which needs to be embedded in its arm64 form,
thus using rosetta to run the whole app.
- Forcer l'architecture cible de l'app docker en arm64 et s'appuyer sur Rosetta pour son execution.
- Compiler depuis les sources psycopg2 dans l'image Docker 
Validé fonctionnel par David.
=> [tech] Adapter le Dockerfile pour les Apple M1

itou/users/admin_forms.py, itou/users/tests/test_admin_forms.py
La mise à jour de l'adresse email d'un utilisateur lève une erreur 500 dans l'admin si l'adresse email est déjà utilisée.
La contrainte d'unicité est testée dans le formulaire `CreateJobSeekerForm` exposé dans le front itou, mais pas dans le formulaire d'admin `/admin/users/{id}/change`
Ajouter un test sur l'existance de l'email dans la méthode `Clean` de la Classe `UserAdminForm`
[nb: le même contrôle dans le `clean` de la Classe User fait planter les tests]
=> [Admin] mise à jour de l’email utilisateur

itou/job_applications/admin_forms.py, itou/job_applications/tests.py
reprise de la PR 1109
1. L'ajout de l’organisation du prescripteur est obligatoire dans l'admin, lors de l'enregistrement d'une candidature, même par si le prescripteur est sans orga.
1. La présence de l'émetteur n'est pas systématiquement vérifiée. Une candidature peut être enregistrée à tord sans émetteur.
1. Permettre l'enregistrement de candidatures par les prescripteurs sans organisation, y compris par le support.
1. Eviter que des candidatures de type `Prescripteur` et `Employeurs` soient enregistrées sans émetteur.
1. Modification du formulaire de l'admin Candidatures (job_applications) pour ne plus afficher le message bloquant  `Organisation du prescripteur émettrice manquante` si le prescripteur n’est pas lié à une orga.
1. Ajout des contrôles sur la présence de l'emetteur
=> [Admin] demander l'organisation prescriptrice seulement si le prescripteur est lié à une organisation

itou/approvals/admin.py, itou/approvals/tests.py, itou/job_applications/models.py, itou/job_applications/tests.py
reprise de la PR #1096 
Modifier le texte affiché dans le champ "Statut de la fiche salarié", de la page 'Modification des Pass IAE' de l'admin.
Dans l'admin 'Modification des Pass IAE', le champ "Statut de la fiche salarié" affiche "Pas de fiche salarié crée pour cette candidature" si la fiche est en attente de création OU si elle ne doit pas être créée.
Demande Métier : différencier les cas de fiches en attente de création et de fiches à ne pas créer car les conditions ne sont pas réunies
Ajout de la propriété `can_have_employee_record` dans le model JobApplication.
Cette propriété determine si la candidature est éligible à une fiche salariée
Utilisation de cette propriété dans `employee_record_status` de l'admin Approval
=> [Admin] gestion du status "fiche salarié en attente" dans la page "Pass IAE"

.pre-commit-config.yaml
Modification de la configuration de pre-commit.
Au lieu de casser la CI et de s'énerver, lançons djhtml en local à chaque commit grâce à `pre-commit`.
Pour refléter ces changements, lancez en local la commande suivante :
```
(venv) cms@cms $ git add .pre-commit-config.yaml 
```
=> Ajout de djhtml à la configuration de pre-commit

itou/job_applications/models.py, itou/job_applications/tests.py
Bug sur la gestion de la date de début `hiring_start_at` qui est optionnelle et peut être nulle.
https://sentry.io/organizations/itou/issues/3037587654/?project=6164438&query=is%3Aunresolved
Gestion du cas nul
=> hiring_start_at is optional so it can be none

itou/employee_record/management/commands/transfer_employee_records.py
Sentry se prends une marée de log d'erreurs en provenance des transferts de fiches salarié.
Si des fiches sont effacées manuellement avant un retour de l'ASP, le traitement du fichier retour renvoie des erreurs (sans crasher) et n'efface pas le fichier (ça boucle et à chaque passage : bingo).
- ce cas particulier n'est plus loggé comme une erreur mais comme un `warning`
- le fichier peut être effacé sans impact majeur
Pas de revue
=> HOTFIX : niveau de log de certaines erreurs lors du transfert de fiches salarié

itou/templates/siaes/card.html
When we get a VERY distorted SIAE (which should normally never happen)
at least display it somewhat correctly.
Corriger l'affochage de la nouvelle fiche structure dans certains cas extrêmes.
Quand un SIAE n'a aucune information définie, la fiche structure est moche.
En bougeant les `<hr>` de place et les rendant conditionnels.
Si l'adresse est vide, ne rien afficher.
Avant
Après
=> SIAE description: minor changes to the template design

itou/fixtures/django/04_test_users.json
Le mot de passe du prescripteur habilité ne permet pas/plus, depuis quelques jours de se connecter automatiquement.
J’ai copié le hash du password de l’utilisateur ETTI
=> Tentative de corriger le login auto du prescripteur habilité

itou/static/css/itou.css, itou/templates/siaes/includes/_configure_jobs_list.html
[Retours designs](https://www.notion.so/Indiquer-le-nombre-de-postes-ouverts-sur-chaque-fiche-de-poste-c9ee7545c5124782b16851be888026bb) liés au formulaire de fiches de postes:
- replacement du label par un aria-label
- Largeur + centrage de l’input qui colle à la maquette
L’implémentation initiale n’est pas fidèle au design
=> Corrections des nombres de postes pour coller au design

itou/job_applications/tests.py, itou/templates/apply/email/accept_for_proxy_body.txt, itou/templates/apply/includes/state_transition_siae.html, itou/templates/approvals/email/deliver_body.txt, itou/templates/approvals/email/manual_delivery_required_notification_body.txt, itou/templates/employee_record/summary.html, itou/www/apply/forms.py, itou/www/apply/tests/test_edit.py, itou/www/apply/tests/tests_process.py, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/tests/test_summary.py
Mise en place du CDI inclusion pour les SIAE au 01/01/22
Lorsqu'un employeur déclare une embauche pour un CDI inclusion il ne sait pas quelle date de fin renseigner car le système lui demande de renseigner une date de fin prévisionnelle.
- Ajouter un texte "ne pas compléter la date de fin dans le cadre d’un CDI Inclusion" dans les formulaires de saisie des dates de contrat, 
- Rendre le champ “date de fin” optionnel,
- Adapter les affichages de la date de fin du contrat dans le front office et dans les emails envoyés : date de fin de contrat ou "non renseigné".
Pas d'impact dans l'admin.
=> Rendre le champ 'date de fin de contrat' optionnel

itou/templates/home/home.html, itou/templates/layout/_header.html, itou/templates/layout/_nav_btn_items.html, itou/templates/layout/base.html, itou/templates/siaes/card.html
Correction de certaines erreurs a11y sur le contraste de couleurs, la présentation de l'information et la consultation. 
Pour mettre en conformité le site avec les règles d'accessibilité et respecter les recommandations de l'audit.
En modifiant le contraste et/ou la taille de certains éléments texte.
https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-3-1
https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-3-2
https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-10-4
En supprimant les attributs html de mise en forme 
https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-10-1
En ajoutant ou supprimant les attributs aria. …
=> Correction des erreurs a11y sur le contraste de couleurs, la présentation et consultation de l'information 

itou/templates/dashboard/dashboard.html, itou/www/dashboard/views.py
La référence pour les icônes est désormais [remixicon.com](http://remixicon.com/)
De nouveaux liens sont ajoutés dans le dashboard pour les DDETS et les SIAE pour le projet “Evaluation à postériori”.
Mettre à jour les icônes existants dans la page dashboard pour ne pas faire cohabiter 2 façons de gérer les icônes dans une même page, avant d’ajouter les nouveaux liens.
=> Remplacement des icones SVG du dashboard pour les icones remixicon

itou/job_applications/tasks.py
Log des tokens lors des appels à l’API PE
Pour identifier si nous avons bien un token différent ou identique lors des appels en mode test, afin de voir si l’erreur peut venir de chez nous ou non.
=> Log des tokens lors des appels à l’API PE

itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/tests/test_summary.py
Test des dates de fin de contrat optionnelles dans les pages `employee_record_views`
Le test qui vérifie la date de fin de contrat, quand elle est connue, recherchait "02" et non "2" pour les jours entre 1 et 9
Mise à jour du formatage
=> Correction des tests sur les dates de fin de contrats optionnelles

itou/job_applications/models.py, itou/job_applications/tasks.py, itou/utils/apis/pole_emploi.py
Amélioration des logs et correction du bug qui fait qu’on envoie des identifiants vides
Cela crée des erreurs
- Plus de logs. Les erreurs S100 sont les seules qui n’incluent pas le token/mode, pour une raison qui m’échappe
- Suppression du mode bac à sable de nos appels. Nous ne faisons pas d’appel en mode test de toute facons.
=> Correctif pour les appels à l’API pole emploi

itou/metabase/management/commands/_job_seekers.py, itou/metabase/management/commands/populate_metabase_itou.py
Evolutions Metabase, avec au menu :
- Note : les SIAE inactives n'étaient déjà pas envoyées avant cette PR.
- Les fiches de poste des SIAE inactives ne sont plus envoyées.
- Les candidatures avec une SIAE destinatrice inactive ne sont plus envoyées.
- Les liaisons fiche de poste / candidature portant sur une candidature avec une SIAE destinatrice inactive ne sont plus envoyées.
- Note : les candidatures créées lors de l'import d'un agrément Pole Emploi n'étaient déjà pas envoyées avant cette PR.
- Les liaisons fiche de poste / candidature portant sur une candidature créée lors de l'import d'un agrément Pole Emploi ne sont plus envoyées.
- Ajout du nouveau champ `candidats.injection_ai` qui était déjà présent dans les tables `candidatures` et `agréments`.
Pour faire avancer le C2, à la …
=> Evolutions Metabase

scripts/create-fast-machine.sh
Faire tourner `huey` sur les machines d’import est un problème, nous le désactivons.
=> Forcer CC_WORKER_COMMAND='' sur les machines d’imports

itou/job_applications/tasks.py
Plus de logs d’erreur et de vérifications concernant l’identifiant chiffré transmis à Pole Emploi.
Les correctifs déployés ces derniers jours (vérifier si le paramètre `encrypted_nir` est vide) n’aident pas à faire disparaitre définitivement le problème des erreurs E_ERR_EX042_PROBLEME_DECHIFFREMEMENT, alors que ça devrait être le cas.
Ces logs ont pourt but de permettre d’identifier si la cause est chez nous (mauvais traitement des cas d’erreur) ou bien si des identifiants chiffrés valides sont mal décodés en face.
=> Plus de logs et de vérifications concernant les erreurs de déchiffrement

itou/job_applications/models.py, itou/job_applications/tests.py
Page Admin des Pass IAE. Affichage de la mention "Statut de la fiche salarié"
Dans le cas où une fiche salarié existe déjà pour le même Pass IAE dans la même Siae, afficher "Pas de fiche salarié crée pour cette candidature"
1. Rechercher les fiches salariés existantes sur ce même critère, dans le modèle `Job_Application` avec la *nouvelle* propriété `candidate_has_employee_record`
2. Utiliser le résultat de cette recherche dans la propriété `is_waiting_for_employee_record_creation`
=> [ADMIN / Approval] Statut de la fiche salarié - cas d'une fiche existante pour un même Pass IAE dans la même Siae

itou/users/models.py, itou/www/approvals_views/tests/test_pe_approval.py
Correctif des `JobApplication.DoesNotExist sur /approvals/pe-approval/search`
https://sentry.io/organizations/itou/issues/3003707981/events/?project=6164438
Lors de la recherche d’un pass, 
```
job_application = approval.user.last_accepted_job_application
```
plante quand on a un Pass IAE mais pas de candidature acceptée.
TDD:
- à partir d’un cas trouvé dans les logs, j’ai pu reproduire localement, debugger et localiser le problème: `approval.user.job_applications.accepted() == JobApplicationQuerySet []`
- J’ai écris un test de caractérisation, 
- Fix du problème et évolution du test associé
=> Correction des erreurs occasionnelles sur la recherche d’agréments

.github/workflows/populate-metabase-itou.yml, itou/metabase/management/commands/populate_metabase_itou.py
- Envoi de l'ouput dans notre bucket. Kudos Vincent et Sébastien.
- Augmentation de la durée du script (3h => 7h => optimisations => 5h) constatée suite à https://github.com/betagouv/itou/pull/1154
- Meilleure gestion des timeouts mais le nouveau `timeout-minutes` reste encore à faire fonctionner.
=> Evolutions du cron quotidien Metabase

itou/approvals/models.py, itou/templates/apply/includes/info_csv.html, itou/templates/apply/process_eligibility.html, itou/templates/apply/submit_step_eligibility.html, itou/templates/dashboard/dashboard.html, itou/templates/home/home.html, itou/templates/layout/_footer.html, itou/templates/layout/_header.html, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt, itou/templates/signup/prescriber_choose_kind.html, itou/templates/stats/stats.html, itou/templates/storage/s3_upload_form.html, itou/utils/emails.py, itou/www/apply/views/process_views.py
Modifictations URL dans les templates, emails et views.
Les pages de documentation utilisateurs sont migrées de "https://doc.inclusion.beta.gouv.fr" vers "https://communaute.inclusion.beta.gouv.fr"
une par une :firecracker:
=> Mise à jour des liens vers communaute.inclusion.beta.gouv.fr

itou/static/css/itou.css, itou/templates/layout/_nav_btn_items.html, itou/utils/perms/context_processors.py, itou/utils/tests.py
Rendre les menus déroulants défilants quand ils contiennent trop d'éléments.
PLUS autres améliorations sur suggestion de @vperron voir screenshots plus bas.
Quand un utilisateur est attaché à de nombreuses structures, le menu "Changer de structure" est si long qu'il en devient ingérable, il est même parfois techniquement impossible d'atteindre les derniers éléments (cas vécu avec le compte institution de Soumia).
Au dela d'une certaine longueur, le menu devient automatiquement défilant.
On a que deux menus déroulants sur le C1 à ce jour :
Le menu "Mon espace" n'est pas affecté par ce fix :
Le menu "Changer de structure" avant ce fix (attention les yeux ça pique) :
Le menu "Changer de structure" après ce fix :
On montre toujours le kind en premier et on trie par (kind, display_name).
=> Rendre les menus déroulants défilants quand ils contiennent trop d'éléments

itou/approvals/management/commands/update_pe_approvals_from_asp_data.py
Importer les données ASP pour mettre à jour les nir/ntt_nia manquants
https://www.notion.so/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=f0cbc8ebc81240ed80295dc807feb7dc
Pour avoir une base plus propre
Cette _management command_ importe les données ASP et met à jour les champs `nir/ntt_nia` dans les `PoleEmploiApproval` à partir du numéro d’agrément PE présent dans le CSV.
=> Ajout de l’import des NIR/NTT/NIA à partir des données ASP

itou/approvals/management/commands/send_all_approvals_to_pe.py
Ajout de la commande `send_all_approvals_to_pe` afin d’envoyer à PoleEmploi tous les Pass (sauf ceux déjà envoyés et acceptés)
Demande de pole emploi
En sortant la liste des pass et en les envoyant, pardi !
A cause du rate limiting en face (un pass toutes les 2s), cette commande est très longue à faire tourner (de notre point de vue: compter plusieurs jours). La DSI concernée est au courant.
=> Ajout de la commande send_all_approvals_to_pe

itou/templates/layout/base.html, itou/www/stats/urls.py, itou/www/stats/views.py
Ajout d'une route temporaire pour tester les custom URLs Matomo.
Les custom URLs Matomo sont potentiellement une killer feature pour le C2.
Par exemple toutes les DDETS voient leurs stats sur la même URL `/stats/ddets/` mais dans Matomo on voudrait pouvoir grouper par région et/ou département. Du coup une custom URL `/stats/ddets/<REGION>/<DPT>/` serait parfaite pour cela, sans modifier quoi que ce soit à l'URL réelle.
Ici on ajoute une route dédiée à un tout premier test vu que malheureusement on ne sait pas trop tester Matomo depuis local dev. Si ça fonctionne, on 🔪  cette route bien sûr et on passera aux vraies routes.
=> Ajout d'une route temporaire pour tester les custom URLs Matomo

itou/approvals/models.py, itou/www/approvals_views/forms.py
Les suspensions sont modifiables retroactivement dans un certain délais.
- Allonger la durée de rétroactivité possible.
- Simplifier le message d'alerte à l'utilisateur dans le formulaire de saisie / mise à jour.
Mise à jour de la valeur de la constante MAX_RETROACTIVITY_DURATION_DAYS
Les tests existants couvrent déjà l'ensemble des cas métiers.
=> Mise à jour du délai de retroactivité des suspensions

config/settings/base.py, itou/templates/dashboard/dashboard.html, itou/www/stats/urls.py, itou/www/stats/views.py
Ajout d'un nouveau tableau de bord "Facilitation de l'embauche" pour les DDETS.
A la demande de Yannick pour le C2.
Très similairement aux autres TDB DDETS existants. A nouveau une DDETS ne voit que les données de son département.
=> Ajout d'un nouveau tableau de bord "Facilitation de l'embauche" pour les DDETS

itou/www/approvals_views/tests/test_pe_approval.py
Uniquement pour lancer la CI intégralement et pas en local.
=> Tests: corriger les erreurs ajoutées avec le message temporaire concernant Mailjet [a ne pas mettre au changelog]

.github/workflows/populate-metabase-itou.yml
Lancement du script Metabase quotidien plus tôt pour qu'il termine bien avant l'arrivée des premiers utilisateurs matinaux.
Avant ce changement, et après le récent décalage d'heure d'été, le script commencait à 4h du mat et se terminait jusqu'à 9h du mat.
En le lancant à 11h du soir plutôt que 4h du mat.
=> Lancement du script Metabase quotidien plus tôt pour qu'il termine bien avant l'arrivée des premiers utilisateurs matinaux

requirements/dev.txt
Upgrade de black.
Toute notre CI est down.
https://github.com/psf/black/issues/2976
MAJ.
=> Corriger la version de python-black

itou/metabase/management/commands/sql/009_recrutements.sql
Ajout des variables QPV, RQTH, tranche d'âge, ZRR dans le tableau de bord statistiques employeur
les SIAE souhaitent accéder aux indicateurs RQTH, ZRR et QPV pour leur pilotage interne et pour répondre aux sollicitations des institutions.
=> Mise à jour des recrutements

itou/approvals/management/commands/batch_notify_pe.py, itou/approvals/management/commands/import_pe_approvals.py, itou/asp/management/commands/gen_asp_ref_fixtures.py, itou/cities/management/commands/import_cities.py, itou/employee_record/management/commands/process_asp_report_file.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/jobs/management/commands/import_appellations_for_romes.py, itou/jobs/management/commands/import_romes.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py, itou/siaes/management/commands/import_siae.py, itou/users/management/commands/deduplicate_job_seekers.py, itou/users/management/commands/extract_c2_users.py, itou/users/management/commands/import_ai_employees.py, itou/users/management/commands/update_nir_from_pass.py, itou/utils/management_commands.py
Refactorisation/simplification du logger dans les commandes.
Sur suggestion de Vincent et de Victor dans cette autre PR : https://github.com/betagouv/itou/pull/1178
- Pour les quelques commandes que je maitrise, j'ai carrément viré la méthode `self.set_logger()` et à la place simplement utilisé les `self.stdout.write()` recommandés par Victor.
- Pour les nombreuses autres commandes que je ne maitrise pas bien et/ou qui utilisent vraiment plusieurs niveaux de logging et pas juste un seul, j'ai factorisé la méthode commune `self.set_logger()` dans un `ItouBaseCommand` partagé, c'est toujours ça de simplifié.
=> Refactorisation/simplification du logger dans les commandes.

itou/metabase/management/commands/sql/010_sorties.sql
Ajout des variables QPV, RQTH, tranche d'âge, ZRR dans le tableau de bord statistiques employeur
Les SIAE souhaitent accéder aux indicateurs RQTH, ZRR et QPV pour leur pilotage interne et pour répondre aux sollicitations des institutions.
=> Mise à jour de l'indicateur sorties

itou/templates/layout/base.html
Ajout d'un FQDN à la custom URL Matomo.
La custom URL Matomo existante échoue silencieusement (aucune trace côté Matomo). Un FQDN a de bonne chances de la faire tomber en marche.
Merci `location.origin`.
=> Ajout d'un FQDN à la custom URL Matomo

itou/www/apply/forms.py
Ajout d'un contrôle sur les départements des candidats pour générer la liste des cases à cocher.
Certains candidats ont un code postal commençant par deux zéros ce qui produit un département inconnu -> "00".
Avec une condition qui n'ajoute que les départements présents dans le dictionnaire `DEPARTMENTS`.
=> Ajout d'un contrôle sur la validité des départements de candidats

itou/metabase/management/commands/sql/008_saisies_mensuelles_iae.sql
Mise à jour du wording des filtres : QPV, RQTH, ZRR et tranches d'âge du salarié
Pour améliorer la lisibilité des filtres du tableau de bord statistiques Metabase
=> Maj de la table saisies mensuelles

clevercloud/cron.json
Une syntaxe alternative pour gérer les "range" dans le fichier CRON de clevercloud.
Les entrées contenant des expressions "range" (par ex. `1-5` pour les 5 premiers jours de la semaine) ne fonctionnent plus.
Remplacer les range par la série de valeurs correspondantes.
Dans le cas présent, `1-5` devient `1.2.3.4.5`
C'est une régression de la part de clevercloud. 
Il a été demandé de nous prévenir lors d'un retour à un fonctionnement normal.
=> Les entrées CRON de clevercloud sont pétées

config/settings/base.py, config/settings/test.py, envs/dev.env.template, itou/allauth_adapters/peamu/adapter.py, itou/allauth_adapters/peamu/tests.py, itou/external_data/apis/pe_connect.py, itou/external_data/tests.py, itou/job_applications/models.py, itou/job_applications/tasks.py, itou/job_applications/tests.py, itou/jobs/management/commands/generate_appellations_for_romes.py, itou/jobs/management/commands/generate_romes.py, itou/utils/apis/esd.py, itou/utils/apis/pole_emploi.py, itou/utils/tests.py
Refonte technique des paramètres `API_ESD_*` (lié aux appels aux APIs pole-emploi.io)  pour être plus robuste.
Pour mieux gérer les cas d’erreurs et planter au démarrage de l’appli en cas de problème. 
Contexte: les valeurs par défaut (sandbox) sont problèmatique dans l’environnement de production.
Quelle que soit la valeur par défaut, elle sera problématique:
- J’avais prévu le cas où une machine imprévue envoie des données chez PE, d’où le mode sandbox
- je n’avais PAS prévu qu’une machine ayant la possibilité d’envoyer les bonnes données à PE soit mal configurées… ce qui est arrivé
Refonte dans un style plus idiomatique django
=> Refonte des paramètre de l’API Pole Emploi

itou/www/siaes_views/tests/tests_job_description_views.py, itou/www/siaes_views/views.py
Il est possible dans certains (rares) cas d'avoir une erreur 500 lors de la visualisation du détails ou de l'aperçu d'une fiche de poste durant la modification.
Les données de session ne sont pas correctement initialisés si on sort du tunnel de création / modification sans avoir validé, et que l'on revient sur cette page via les options de navigations (précédent / suivant).
Si les données de session ne sont pas correctement initialisées sur les étapes de modification de la fiche de poste, on est automatiquement redirigé vers la première étape (et les données sont initialisées à ce moment là).
=> Modification d'une redirection dans les fiches de poste 

itou/www/apply/tests/tests_list.py
Correction du test du filtre par poste
Il échoue de façon aléatoire.
La fabrique de la SIAE créait des descriptions de postes inutilisées et lorsque le test en question créait des descriptions de poste sur le même poste, la contrainte d'unicité générait une erreur.
=> Correction du test du filtre par poste

config/settings/base.py, itou/templates/dashboard/dashboard.html, itou/utils/apis/metabase.py, itou/www/stats/urls.py, itou/www/stats/views.py
Ajout d'une seconde page stats pour les employeurs.
A la demande de Yannick, pour enrichir l'expérimentation C2 actuelle auprès d'une liste blanche d'employeurs.
=> Ajout d'une seconde page stats pour les employeurs

itou/api/employee_record_api/tests.py, itou/api/employee_record_api/viewsets.py
Modification du paramètre `status` de l'API pour permettre de passer plusieurs valeurs (tableau).
Suite à demande des utilisateurs.
Permettre de passer plusieurs valeurs en paramètre de requête. 
Par ex. `?status=NEW&status=READY` pour obtenir la liste agrégée des deux états.
=> Modification du paramètre `status` dans l'API fiche salarié. 

itou/metabase/management/commands/sql/008_saisies_mensuelles_iae.sql
Modification de l'intitulé de la tranche d'âge 'a- Moins de 25 ans' en 'a- Moins de 26 ans'
Demande lors du groupe de travail avec les SIAE pour être iso avec les tranches d'âge de la solution 'un jeune/une solution'
=> Modification des tranches d'âge des salariés en IAE

clevercloud/cron.json
Changement des ranhes sur le cron cleverclous (suite)
Voir : https://github.com/betagouv/itou/pull/1220
Modification des ranges sur les heures
=> Les entrées CRON de clevercloud sont toujours pétées

itou/approvals/management/commands/merge_pe_approvals.py, itou/approvals/models.py, itou/approvals/tests/tests.py, itou/eligibility/models.py, itou/templates/approvals/includes/status.html, itou/www/apply/tests/tests_submit.py
Retrait du code qui ajoute automatiquement 3 mois à la durée des PASS IAE délivrés pendant le confinement.
Nous ne sommes plus confinés et cela pose des problèmes de double extension.
En retirant tout le code associé.
=> PASS IAE : Supprimer le code lié au COVID et confinement

requirements/base.txt
Mise à jour de sécurité
Sécurité essentiellement, voir https://www.djangoproject.com/weblog/2022/apr/11/security-releases/
Passage en version 4.0.4
=> Mise à jour vers Django 4.0.4

itou/www/siae_evaluations_views/views.py
Corriger une typo dans le message de confirmation aux DDETS lors de la sélection du ratio.
Parce qu'on aime bien écrire en français ;)
Mise à jour du contenu du message dans `siae_evaluations_views/views.py`
=> Contrôle a posteriori : phase selection des Siaes - typo

itou/employee_record/serializers.py, itou/employee_record/tests/tests_serializers.py
Correction d'une erreur de sérialisation JSON sur l'adresse de l'employée. 
Il s'agit d'une régression introduite par la PR https://github.com/betagouv/itou/pull/1182
Utilisation du bon type de sérialiseur
Pas de revue (à passer rapidement)
=> Correction d'une erreur de sérialisation de l'adresse de l'employé

itou/fixtures/django/12_pe_approvals.json
Corriger la fixture PE approvals.
`number` fait 15 caractères or maintenant la limite est à 12.
En modifiant la fixture.
=> Corriger la fixture PE Approvals

itou/siaes/management/commands/import_siae.py, itou/siaes/tests/tests_import_siae_command.py
Correctif sur l'import SIAE.
Cette semaine Supportix (@ikarius) a remonté que l'import SIAE indique à tort qu'une grande quantité de structures sont "injoignables" par manque d'email d'authentification et/ou de membres pour inviter de nouveaux membres. Voir [ce thread](https://itou-inclusion.slack.com/archives/CQ6D0QPPZ/p1649746761291299) pour l'output.
Ce comportement incorrect a été introduit par la PR récente https://github.com/betagouv/itou/pull/1204 qui a introduit un code plus optimisé et plusieurs tests, malheurement ces tests ont un (gros) trou dans la raquette, un cas trivial très courant (que des membres actif et pas d'`auth_email`) qui devrait ne pas produire d'erreur, mais qui en produit.
- Refactorisation préparatoire et séparation des tests pour que les différents cas et …
=> Correctif sur l'import SIAE.

itou/www/login/forms.py, itou/www/login/tests.py
Refuser la connexion d’un utilisateur qui a utilisé France Connect ou PE Connect mais qui essaye de se connecter via le formulaire normal.
Actuellement, c'est possible (voir le ticket).
Je propose d’afficher le message d’erreur suivant :
> Votre compte est relié à {fournisseur d’identité}.
> Merci de vous connecter avec ce service.
=> Refuser la connexion Django pour les utilisateurs SSO

itou/common_apps/address/departments.py, itou/www/stats/urls.py, itou/www/stats/views.py
Ajout de custom URLs Matomo sur toutes les stats.
Quand Annie du C2 consulte les stats des stats (¬_¬) dans Matomo, par exemple pour les stats "DDETS IAE", elle voit un seul chiffre de visites pour l'URL `/stats/ddets/iae`. Avec les nouvelles custom URLs, l'URL virtuelle (vue uniquement par Matomo) sera du type `/stats/ddets/iae/<REGION>/<DEPARTEMENT>`. Du coup Annie pourra ventiler le chiffre de visites pas région et par département.
Les visites dans Matomo :
Après cette PR, on pourra déplier ce traffic directement à cet endroit, par région puis par département, et ce pour chaque type de stats.
=> Ajout de custom URLs Matomo sur toutes les stats.

itou/users/management/commands/sync_group_and_perms.py, itou/users/tests/test_management_commands.py
Ajouter le support externe au script de synchro des permissions.
On ne doit pas gérer cela manuellement dans l'admin, c'est dangereux et on perd notre maîtrise des droits des utilisateurs.
En utilisant une commande qui le sremet d'aplomb à chaque déploiement.
=> Synchronisation du groupe de permissions du support externe

.github/pull_request_template.md
Ajout de liens notion/slack dans le template de PR.
Pour encourager à penser à mettre le lien de la PR vers l'action notion.
Merci le template de PR.
```
- [action notion](FIXME-URL)
- [discussion slack](FIXME-URL)
```
=> Ajout de liens notion/slack dans le template de PR

itou/approvals/models.py, itou/users/models.py
Le bouton suspendre un PASS IAE est parfois inaccessible pour les SIAE.
Réparation d'une régression, voir carte:
https://www.notion.so/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=28a2b530834a415eb834c424c52a8025
Modification du tri par date (voir code).
=> Suspension: Fix last accepted job application date issue for user

config/settings/base.py, itou/templates/dashboard/dashboard.html, itou/www/stats/urls.py, itou/www/stats/views.py
Ajout d'une seconde vue stats "Facilitation de l'embauche" pour les DREETS.
A la demande de Yannick. Cette vue déjà consultable par les DDETS est très demandée par les DREETS.
Action notion : https://www.notion.so/TB160-L-ouvrir-aux-DREETS-98df54ab0ff84dd7a0a05838e0f1a4e9
=> Ajout d'une seconde vue stats "Facilitation de l'embauche" pour les DREETS

.github/workflows/build-metabase-final-tables.yml, itou/metabase/management/commands/_utils.py, itou/metabase/management/commands/build_metabase_final_tables.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/metabase/management/commands/populate_metabase_itou.py
Ajout d'une nouvelle github action Metabase pratique pour nos data analysts C2.
Après avoir fusionné leurs changements (PR sur les requêtes SQL de fin d'import Metabase), nos data analystes doivent actuellement :
- soit attendre le lendemain matin que le `populate_metabase_itou` de la nuit ait tourné
- soit lancer manuellement la github action `populate_metabase_itou` qui prend plusieurs heures (3-6h)
Ils voudraient un moyen de lancer uniquement les requêtes SQL de fin d'import (15-30min) pour voir plus vite leurs changements.
En ajoutant une nouvelle github action `build_metabase_final_tables` qui fait exactement cela.
Il n'est pas vraiment possible de tester la github action avant son arrivée dans `master`.  Il est du coup possible qu'une seconde PR de correctifs suive. ¯\_(ツ)_/¯ …
=> Ajout d'une nouvelle github action Metabase pratique pour nos data analysts C2

itou/approvals/tests/tests.py, itou/employee_record/tests/tests_notifications.py
Correction de plusieus test instables.
- problème aux alentours de minuit avec des `date` et `timezone`,
- ça bloque la C.I. la nuit.
Mettre des timezones à la place de dates n'est (vraiment) pas une bonne idée.
=> WIP fixes flaky test

itou/allauth_adapters/peamu/views.py, itou/external_data/apis/pe_connect.py, itou/templates/account/account_type_selection.html, itou/templates/dashboard/dashboard.html, itou/templates/siaes/edit_job_description.html, itou/www/login/views.py
- retrait des mentions à la DGEFP sur le dashboard
- retrait des imports de données `external-data` des remontée Sentry (avant un retrait définitif ?)
- ajout d'un comportement dynamique sur le champ "Autre type de contrat" dans le formulaire des fiches de poste
- si l'utilisateur n'est pas connecté pour postuler à une offre (après une recherche), ou autre accès non-identifié, un choix du type de connexion lui est proposé (SIAE, prescripteur, Inspecteur ou candidat)
Modifications "boost" pour la release 41
Avec patience et application.
=> Boost release 41 (voir détails PR pour changelog)

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests/tests.py, itou/job_applications/tests.py, itou/users/factories.py
Effectuer une recherche d'agrément par NIR avant de laisser la possibilité (comme aujourd'hui) de rechercher par ID PE.
Cela permettrait de réduire significativement la charge du support qui crée des PASS manuellement en faisant une recherche d'agrément à la main, quand elle pourrait souvent etre faite par NIR.
En l'ajoutant à la recherche actuelle par ID pole emploi.
J'ai créé  des membres dans la structure de type EI "Garage Martinet Siège" qui sont à valider.
Dans l'ancienne version, on n'a accès (dans "Gérer la candidature") que à une liste manuelle de critères.
Ici, comme on trouve un Agrément PE contenant le NIR de chacun de ces 5 candidats, on a la possibilité de créer le PASS IAE automatiquement.
https://c1-review-vperron-look-for-nir.cleverapps.io/apply/siae/list?states=new&states …
=> Agréments : recherche par NIR en plus du pole_emploi_id

itou/templates/siaes/edit_job_description.html
Le champ concernant la description du contexte de marché pour les OPCS est absent du formulaire (régression).
Lors de l'ajout de la modification du type de contrat, la structure du gabarit à changé, et le champ est passé à la trappe.
Simple ajout du champ dans le gabarit dans le cas d'un OPCS.
=> HOTFIX : ajout d'un champ manquant dans les fiches de postes pour les OPCS

config/settings/base.py, itou/templates/dashboard/dashboard.html, itou/users/models.py, itou/www/dashboard/views.py, itou/www/stats/urls.py, itou/www/stats/views.py
Ajout de stats PE qui permettent à tout membre d'agence PE de consulter les stats de son département.
La fonctionnalité est cachée mais accessible par l'URL secrète `stats/pe`.
Le commit pour publier la fonctionnalité est préparé (et reverté) dans cette PR même.
Pour offrir leurs toutes premières stats Metabase aux agences PE pardi !
En s'inspirant fortement de l'existant et similaire tableau de bord des CD.
https://www.notion.so/Publier-le-TB-tensions-de-recrutement-pour-les-agences-PE-en-standby-116a07968e654e84be8528b6481f4315
=> Ajout de stats PE qui permettent à tout membre d'agence PE de consulter les stats de son département

itou/eligibility/migrations/0009_rename_refugee_administrative_criteria.py
Changement du nom et du texte des justificatifs sur le critère administratif réfugié.
Suite à l’Arrêté du 12 avril 2022 modifiant l'arrêté du 1er septembre 2021 fixant la liste des critères d'éligibilité des personnes à un parcours d'insertion par l'activité économique
Création d'une migration pour la mise à jour du critère concerné.
Formulaire d'éligibilité :
=> Modification du critère d’éligibilité réfugié

itou/users/management/commands/extract_c2_users.py
Ajout d'une colonne "DateRattachement" dans l'extract des utilisateurs C2.
Pour aider Annie à identifier les nouveaux utilisateurs qui arrivent dans cet extract semaine après semaine.
Pas de revue nécessaire... pas besoin.
=> Ajout d'une colonne "DateRattachement" dans l'extract des utilisateurs C2

docker/dev/django/Dockerfile, itou/users/factories.py
Débloquer les CI en évitant les erreurs d'unicité sur les tests.
Des erreurs d'unicité apparaissent inopinément sur les tests.
En remettant les séquences sur le `username` et l'email sur la factory user.
J'en profite pour aligner la version de l'image Docker de dév avec la version Python de la CI.
=> Éviter les erreurs d'unicité aléatoires sur les tests

itou/siaes/management/commands/_import_siae/utils.py
Ajout du référentiel "RefTypeAide" dans le fluxIAE.
Une vérification sur le nombre de fichiers bloque l'exécution.
En passant le nombre de fichiers attendus à 29.
=> Nouveau référentiel dans le FluxIAE

itou/siae_evaluations/enums.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/email/eligible_siaes_body.txt, itou/templates/siae_evaluations/email/eligible_siaes_subject.txt, itou/templates/siae_evaluations/includes/list_item.html, itou/templates/siae_evaluations/siae_job_applications_list.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/siae_evaluations_views/tests.py, itou/www/siae_evaluations_views/urls.py, itou/www/siae_evaluations_views/views.py
Informer les user admin des SIAEs du contrôle et leur donner accès à la liste des embauches soumises au contrôle.
1. En tant que SIAE soumise au contrôle je veux être alertée par mail du lancement de la procédure.
2. En tant que SIAE je veux un accès à l’espace dédié au contrôle.
3. En tant que SIAE je veux visualiser la liste de mes embauches soumises au contrôle
* notification email des membres admin de la SIAE lors du peuplement de la campagne
* ajout d'un lien dans le dashboard de la SIAE à tous les membres de la SIAE, pour accéder à la liste des autoprescriptions contrôlées
* ajout d'une page de liste paginée des autoprescriptions contrôlées
- Cette PR s'arrête à cette liste, elle n'inclue pas les liens vers les pages de détails des autoprescriptions, ni de choix des critères …
=> Contrôle a posteriori, Pack SIAE : notification et liste des justificatifs demandés (cartes 1 à 3)

itou/approvals/management/commands/send_all_approvals_to_pe.py, itou/utils/apis/pole_emploi.py
Arreter de crasher sans raison pour des erreurs coté PE et aller le plus loin possible.
Actuellement pour des erreurs bêtes, le script cesse totalement meme en plein nuit.
Or nous avons 100000 PASS à envoyer, il serait urbain que le script continue le plus possible.
On repassera sur les derniers cas dans une seconde et troisième passe; pas de "retry" pour l'instant.
En gérant les cas d'erreur.
Le code de l'API est un peu spécial: pas robuste, plein de doublons pas totalement équivalents, pas vraiment testé.
Il est prévu que je fasse une passe derrière (juste après en réalité) pour adapter, tester, factoriser ce code et le rendre plus robuste, eventuellement avec des `retry`.  Car nous allons devoir envoyer aussi tous les agréments PE et ça va piquer.
En attendant j'ai besoin que ce code …
=> Rendre plus robuste le code de l'API Pole Emploi le temps de l'envoi des PASS IAE

itou/approvals/admin.py, itou/approvals/models.py, itou/approvals/tests/tests.py, itou/job_applications/tests.py, itou/users/factories.py
Réintroduire la recherche par NIR, exemptée du bug que l'on a constaté en production.
Elle avait été retirée jeudi dernier suite à des soucis en production.
Il fallait absolument corriger le bug introduit, qui faisait remonter le plus ancien agrément PE comportant un NIR vide quel que soti le demandeur d'emploi à NIR vide.
Ceci est désormais testé.
**A LIRE COMMIT PAR COMMIT**
- le commit initial, réintroduit
- son fix
=> Recherche d'agréments PE par NIR : version corrigée

clevercloud/review-app-after-success.sh
Cf le titre.
C'est cassé depuis [cette PR](https://github.com/betagouv/itou/pull/1221).
En portant la modification aussi dans ce script.
J'en profite pour clarifier et mettre des options longues.
=> Technique: corriger le chargement des villes dans les fusions de code

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/layout/base_email_text_body.txt, itou/templates/siae_evaluations/email/eligible_siaes_body.txt, itou/templates/siae_evaluations/email/email_institution_notification_body.txt, itou/templates/siae_evaluations/email/email_institution_opening_siae_body.txt, itou/templates/siae_evaluations/email/email_institution_opening_siae_subject.txt
Envoi d'un email aux DDETS lorsque les SIAE peuvent téléverser leurs justiicatifs. C'est-à-dire au moment où les campagnes sont populated.
- En tant que DDETS  je veux être alertée par mail du lancement de la procédure de transmission des justificatifs
- Ajout d'un template de mail
- Envoi de l'email aux DDETS lors de l'appel à la méthode `populate` de `EvaluationCampaign`
- mise à jour du contenu de l'email de notification aux Siaes (PR initiale 1223)
=> Contrôle a posteriori, Pack DDETS : notification ouverture de la phase de transmission des justificatifs (carte 1/5)

itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/includes/siae_infos.html, itou/templates/siae_evaluations/institution_evaluated_siae_list.html, itou/templates/siae_evaluations/samples_selection.html, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/siae_evaluations_views/tests.py, itou/www/siae_evaluations_views/urls.py, itou/www/siae_evaluations_views/views.py
Accéder à la liste des Siae sélectionnées dans un contrôle a posteriori
- En tant que DDETS  je veux visualiser et suivre la liste des SIAE à contrôler
- refactoring : suppression des méthodes `has_active_campaign` pour preparer la simplification du code à venir (accès aux campagnes par pk)
- ajout vue de liste des `EvaluatedSiae` d'une `EvaluationCampaign`
- ajout d'un lien dans le dashboard des DDETS pour accéder à cette vue
=> Contrôle a posteriori, Pack DDETS : liste des siae contrôlées (carte 2/5)

itou/job_applications/factories.py, itou/templates/search/includes/prescribers_search_filters.html, itou/templates/search/includes/prescribers_search_form.html, itou/templates/search/includes/siaes_search_filters.html, itou/templates/search/includes/siaes_search_form.html, itou/templates/search/siaes_search_results.html, itou/templates/siaes/card.html, itou/templates/siaes/includes/_card_siae.html, itou/templates/siaes/includes/_list_siae_actives_jobs.html, itou/templates/siaes/includes/_list_siae_actives_jobs_row.html, itou/templates/siaes/includes/_list_siae_jobs.html, itou/templates/siaes/job_description_card.html, itou/www/search/tests.py
Améliorer l'UX et UI des résultats de recherche d'employeurs.
- Manque de visibilité des postes ouverts au recrutement, en particulier lorsqu'ils sont nombreux
- Redondance dans l'affichage des postes en recrutement et de l'ensemble des postes de la structure.
- Nécessité d'afficher la localisation du poste
Modifier les cards de résultats pour :
- afficher les 5 premiers postes sous forme de liste plus étroite.
- Afficher la commune à droite du nom du poste
- Distinguer davantage les infos générales de la structure des recrutements en cours
- Retirer la possibilité d'expand "Voir les métiers exercés au sein de la structure" à l'échelle de la carte et rapporter tous les métiers sur la page de la fiche structure.
Résultats page 1
Résultats page 2
Effet de bord dans la page de la structure, …
=> Nouvelle interface pour les résultats de recherche employeurs

itou/common_apps/notifications/tests.py, itou/job_applications/tests.py, itou/siaes/factories.py, itou/templates/apply/email/new_for_siae_body.txt, itou/templates/approvals/email/deliver_body.txt, itou/templates/approvals/email/deliver_subject.txt
Lorsque les EA/EATT/geiq/OPCS reçoivent une candidature et valident une embauche, les mails qu’elles reçoivent sont très orientés IAE. 
Les emails pour lesquels il faut retirer les mentions sur le pass IAE sont les suivants :
- nouvelle candidature
- candidature acceptée
Ne pas envoyer le mail avec le détail du Pass lors de la confirmation d’embauche.
Cette règle est valable aussi pour les GEIQ.
Lors de la réception d’une nouvelle candidature, les EA/GEIQ/OPCS reçoivent un e-mail qui parle de l’éligibilité IAE et parfois du PASS IAE or, ils ne sont pas concernés par l’éligibilité IAE, ni par le PASS IAE
=> Les emails reçus par les employeurs non soumis aux règles d’éligibilité IAE ne sont pas tous adaptés à leur profil

.gitignore, pytest.ini, requirements/dev.txt
Ajout d'un fichier de configuration Pytest pour nos amis VScodiens.
Modification du .gitignore pour ne pas versionner le .envrc.
Suite à l'excellent atelier de Victor.
=> Configuration Pytest et non versionnement de .envrc

itou/www/siae_evaluations_views/tests/tests_siaes_views.py
Le `itou.www.siae_evaluations_views.tests.SiaeUploadDocsViewTest.test_access` fait planter aléatoirement la CI
```
AssertionError: {'url[166 chars]142245Z', 'policy': 'eyJleHBpcmF0aW9uIjogIjIwM[404 chars]34'}} != {'url[166 chars]142246Z', 'policy': 'eyJleHBpcmF0aW9uIjogIjIwM[404 chars]1e'}}
Diff is 2026 characters long. Set self.maxDiff to None to see it.
```
Vraisemblablement un problème lors de la comparaison des dictionnaires en entier.
- remplacer le test du dictionnaire par un test clé par clé
=> Contrôle a posteriori - Correction du test SiaeUploadDocsViewTest.test_access

itou/job_applications/tasks.py, itou/job_applications/tests.py
Donner plus de détails dans un log.
Pour l'instant il n'est pas très utile sinon.
Dans le titre.
Attention les tests ne vont pas passer car actuellement les logs sont désactivés en mode test.
=> notify_pole_emploi: Rendre un journal plus verbeux

config/urls.py, itou/job_applications/tasks.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Durant le parcours de création d'un demandeur d'emploi il arrive (rarement) que des erreurs 500 soient remontées pour cause de préexistence d'un autre utilisateur portant le même NIR.
Il faudrait idéalement:
- ne pas planter, mais le signaler à l'utilisateur;
- alternativement empecher via le parcours que ce probleme se présente. 
Ca empeche certains demandeurs d'emploi de se créer un compte.
Je ne suis pas certain de ma solution à ce [pronblème remonté via Sentry](https://sentry.io/organizations/itou/issues/2959654373/events/bd4d6f5b9d9c4085be6a1a33e599492a/?project=6164438&query=is%3Aunresolved&sort=freq&statsPeriod=14d).
En effet le souci arrive dans la vue `apply:step_job_seeker` qui vient IMMEDIATEMENT après la vue `apply:step_job_seeker_nir` qui vérifie déjà que l'on ne connaît pas …
=> Inscription de demandeur d'emploi: ne pas crasher en cas de préexistence d'un NIR (et petits patchs)

Makefile
So that you can also reset the test database easily.
Pour resetter la database, ou lancer des tests en ligne de commande si vous n'avez pas deja un script :)
Plus facile.
Avec une commande.
=> Makefile: Ajout de la commande test_venv

clevercloud/cron.json
Désactivation des scripts de transfert des fiches salarié sur la période du 30-31.05.2022.
A ces dates une reprise des données de l'ASP sera en cours (pour procéder à la mise en place des notifications de changement sur les PASS IAE).
Une autre PR est à suivre pour la réactivation des scripts CRON.
Suppression du lancement des scripts concernés dans le fichier CRON de clevercloud.
=> Désactivation des scripts CRON concernant les fiches salarié

itou/templates/dashboard/dashboard.html
Ajout d'un message d'information pour les structures utilisant les fiches salariés.
Coupure du transfert des fiches salarié les 30 et 31 mai 2022 : pour installation du service de MAJ des dates de PASS IAE et le temps d'une reprise de données par l'ASP.
Petit message informatif sur le tableau de bord.
=> Message d'information fiches salarié

itou/approvals/management/commands/export_asp_approval_data.py
Ajout d'une management command permettant d'ajouter / actualiser les dates de fin des PASS IAE dans un fichier de données fourni par l'ASP.
Dans le cadre d'une procédure de reprise de données programmée par l'ASP pour la mise en production des notifications de changement sur les PASS IAE liés à une fiche salarié.
- parcours le fichier d'entrée en vérifiant que le PASS existe et que le demandeur d'emploi est le bon (hash id),
- affiche les erreurs
- crée un nouveau fichier augmenté des dates de fin actualisé pour les lignes valides du fichier d'entrée
=> Management command pour l'export des PASS IAE pour la reprise ASP

itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/models.py
Modification de l'import des notifications.
Apparemment, une méthode du queryset à du sauter lors d'un rebase entre les tests ASP et la MEP
Remettre en place la méthode de queryset `find_by_batch` pour les notifications.
=> HOTFIX : Management command transfert du fichier de feedback pour les notifications ASP

clevercloud/download_employee_records.sh, clevercloud/upload_employee_records.sh, itou/employee_record/management/commands/transfer_employee_records_updates.py
Ajout des notifications de changement des PASS IAE dans les scripts automatiques de transfert vers l'ASP.
Fin des vérifications manuelles des transferts de notifications, le processus peut devenir automatique.
Ajout des lancements de la management command spécifique aux notifications aux scripts automatisés déjà existant.
Les notifications de changement de PASS IAE étaient la dernière partie du cahier des charges "Interopérabilité" de l'ASP.
C'est la fin des travaux d'échanges d'informations avec l'ASP :)
Ne s'en suivront que des modifications coté plateforme pour améliorer l'expérience utilisateur.
=> Mise à jour des scripts automatiques de transfert des fiches salariés 

itou/templates/siae_evaluations/institution_evaluated_job_application.html, itou/www/siae_evaluations_views/forms.py
Retirer la bascule du champ du formulaire en readonly après la revue par les DDETS.
Des pièces ont été refusées avant la mise en production du formulaire. Des DDETS voudraient en profiter pour ajouter un commentaire a posteriori. Le passage en readonly crée un effet de bord génant pour le rattrapage.
À repenser pour les prochaines campagnes.
- suppression de la méthode `init` de `LaborExplanationForm` (non testée :| )
- retrait de la décoration du template pour modifier le bouton
=> Contrôle a posteriori : laisser le formulaire de saisie du commentaire modifiable après la revue par les DDETS

itou/templates/dashboard/dashboard.html
Retirer le message sur le tableau de bord indiquant que le transfert de fiches salarié est interrompu.
L'intervention est terminée.
Enlever le message
=> Retrait d'un message d'information obsolète

itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html
Tout est dans le titre.
La DDETS doit vérifier un justificatif au regard de la date de délivrance du Pass IAE. Par exemple, le justificatif date de moins de 3 moins avant la date de délivrance
Ajout de la date dans l'include `job_seeker_infos_for_institution`
=> Controle a posteriori : afficher la date du Pass IAE (patch)

itou/job_applications/models.py
cf titre
Le filtre par statut 'Nouvelle' excluait uniquement les fiches à l'état DISABLED. Les fiches à l'état NEW n'était pas prises en compte. Impossible de les compléter par les SIAE
Mise à jour de la selection dans la méthode `eligible_as_employee_record`
=> Gérer mes fiches salariés : rendre visible les fiches à l'état 'nouvelle'

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Correctif rapide en attendant de pouvoir ajouter un test.
Les prescripteurs qui n'ont pas le droit de mettre à jour le NIR des candidats sont bloqués dans une boucle infinie. Ils cliquent sur « continuer » et la page se recharge. C'est normal car la logique a changé dans la PR #1283 avec cet effet de bord indésirable.
Correction de la logique.
=> Correctif pour débloquer les prescripteurs n'ayant pas la possibilité de mettre à jour le NIR

.github/workflows/ci.yml
Tentative d'accélération de la CI, pas vraiment fulgurante car on passe de 13 minutes à 12, mais au moins les migrations échouent avant les tests.
- La CI est trop lente.
- C'est trop frustrant que la CI casse à cause d'une migration manquante après avoir attendu 10 minutes que les tests passent.
=> Accélération de la CI

.github/workflows/ci.yml, requirements/deploy.txt, requirements/dev.txt
Mise à jour des Github Actions `setup` / `checkout` et des paquets Python de dev (essentiellement pour la qualité du code)
Pour profiter des évolutions et éviter les erreurs liées à obsolescence des dépendances.
Passage des Github actions en v3.
Passage des paquets Python à la dernière version à date.
=> Mise à jour des Github Actions et des paquets Python de dev

docker/dev/django/entrypoint.sh
Le serveur `werkzeug` s'arrête en développement (env Docker) depuis la dernière mise à jour du paquet.
https://github.com/django-extensions/django-extensions/issues/1715
Soit il fallait downgrader le paquet `Werkzeug`.
Soit il fallait ajouter un argument à la commande `runserver_plus`.
Pour aller de l'avant, j'ai opté pour la deuxième option.
=> Éviter l'arrêt du serveur en environnement de développement Docker

itou/metabase/management/commands/sql/022_delai_recrutement.sql
Suivre le délai de recrutement des candidats en IAE
Maintenir un délai de recrutement inférieur à 30 jours
=> Délai de recrutement en IAE

itou/metabase/management/commands/sql/023_candidats_sans_solution.sql
Suivi du nombre de candidats sans solution à 30 jours
Statistiques d'impact des emplois de l'inclusion
=> Candidats sans solution à 30 jours

.github/workflows/populate-metabase-itou.yml, itou/metabase/management/commands/_approvals.py, itou/metabase/management/commands/_job_applications.py, itou/metabase/management/commands/_job_seekers.py, itou/metabase/management/commands/_utils.py, itou/metabase/management/commands/populate_metabase_itou.py
Amélioration de la performance du cron Metabase quotidien :
- refactoring significatif autour de `is_from_ai_stock`.
- `populate_job_seekers` tombe de 120 minutes à 30 minutes (!) en local dev.
- `populate_job_applications` passe de 50 minutes à 40 minutes en local dev.
- `populate_approvals` passe de 35 minutes à 15 minutes en local dev.
- le cron dans son ensemble tombe de 6h+ à seulement 2h20 en condition réelle (fast-machine).
- amélioration de la documentation autour du timeout infranchissable de 6 heures des github actions.
- depuis 2-3 semaines ce cron échoue chaque nuit car dépasse le timeout github action de 6 heures. En dépannant je le lancais chaque samedi depuis mon local dev (qui, ironiquement, ne prend que 4 heures, comme quoi le réseau n'est pas à blamer), puisque le local …
=> Amélioration de la performance du cron Metabase quotidien.

itou/users/admin.py
Affichage de l'identifiant obfusqué dans l'édition d'un utilisateur.
Pour pouvoir mener des analyses sur des exports où l'identifiant a été obfusqué.
Affichage dans l'administration
=> Affichage de l'identifiant obfusqué dans l'administration

clevercloud/cron.json, clevercloud/status-probes.sh, config/settings/base.py, config/urls.py, itou/status/apps.py, itou/status/factories.py, itou/status/management/commands/run_status_probes.py, itou/status/migrations/0001_initial.py, itou/status/models.py, itou/status/probes.py, itou/status/tests.py, itou/status/urls.py, itou/status/views.py, itou/templates/status/index.html
Création d'une application Django `status` qui permet de surveiller les API externes que nous utilisons. 
Notre système est de plus en plus interfacé avec des services externes qui sont parfois indisponibles. Aujourd’hui, nous n’avons pas de moyen rapide de savoir si elles sont joignables ou non.
Tâche cron:
- Lance une _management command_.
- Exécutée toute les 5 minutes, ça devrait être suffisant pour notre besoin.
- Le drapeau `STATUS_PROBES_CRON_ENABLED` permet de la désactivée, par exemple sur les _reviews app_ :).
Application `status`:
- Pas d'historique, seul le dernier _success_ et _failure_ sont disponible.
- Les probes actuelles font une requête HTTP `HEAD` sur l'URL de base (en se basant sur les `settings`), elles tombent en échec si il y a une erreur réseau ou une erreur HTTP …
=> Page de statut pour API externes

.github/workflows/ci.yml, Makefile, README.md, config/settings/dev.py.template
- Correction du template pour `settings/dev.py` afin de ne plus logguer les requêtes SQL en double.
- Suppression des recettes du Makefile avec un suffixe `_venv` pour un flag.
L'idée est que tout le monde utilise la même interface (_ie._ nom des recettes) et qu'on s'adapte ensuite dans le Makefile, ça permet notamment d'éviter la duplication des commandes qui n'avais parfois pas tout à fait les mêmes options sans trop de raison.
=> Commandes `_venv` du Makefile et logs SQL en double

itou/users/models.py, itou/users/tests/test_models.py, itou/www/dashboard/tests.py
Dans le tableau de bord employeur EA+GEIQ+ EATT :  Supprimer  le lien “créer/rejoindre une nouvelle structure”
En plus des OPCS et des ACIPH
La fonctionnalité “antennes” pour les SIAE du C1 n'est pas pertinente pour les EA, car les “antennes” potentielles d’EA dans le fichier EA existent déjà dans le fichier EA et donc existent en tant que structures mères sur le C1. La METH est très vigilante a ce qu’aucune EA ne puisse se créer un établissement sans SIRET.
- Modification de la méthode `can_create_siae_antenna`, exclusion des types d'entreprises non gérées par l'ASP, même si une convention existe.
=> Bloquer la création d’antennes pour les EA / EATT / GEIQ

itou/api/employee_record_api/tests/tests_throttling.py, itou/api/siae_api/tests.py, itou/approvals/factories.py, itou/approvals/tests/tests.py, itou/common_apps/notifications/tests.py, itou/eligibility/factories.py, itou/eligibility/tests.py, itou/invitations/factories.py, itou/job_applications/factories.py, itou/job_applications/tests/tests_transfer.py, itou/siae_evaluations/tests/tests_models.py, itou/siaes/factories.py, itou/siaes/tests/tests_models.py, itou/users/factories.py, itou/users/tests/test_management_commands.py, itou/users/tests/test_models.py, itou/utils/tests.py, itou/www/apply/tests/tests_list.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/approvals_views/tests/test_pe_approval.py, itou/www/dashboard/tests.py, itou/www/eligibility_views/tests.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/invitations_views/tests/tests_siae_send.py, itou/www/search/tests.py, itou/www/siaes_views/tests/tests_job_description_views.py, itou/www/siaes_views/tests/tests_views.py, itou/www/welcoming_tour/tests.py
Utilisation de [Traits](https://factoryboy.readthedocs.io/en/stable/reference.html#factory.Trait) en lieu et place de classe enfants.
Principalement pour ne pas devoir créer une classe (`Siae`, `SiaeWithMembership`, `SiaeWithJobsFactory`, `SiaeWithMembershipAndJobsFactory`, etc) pour chaque combinaison qui nous intéresse.
Répandre cette possibilité et avoir l'avis collégial [1] sur cette manière de faire !
[1] Alors, oui, j'ai déjà fait les commits pour supprimer certaines _factories_ mais on est pas obligé de les fusionner ;).
=> Utilisation de `factory.Trait` pour `SiaeFactory()`

config/settings/base.py, itou/allauth_adapters/peamu/tasks.py, itou/allauth_adapters/peamu/tests.py, itou/allauth_adapters/peamu/urls.py, itou/allauth_adapters/peamu/views.py, itou/templates/account/login_job_seeker.html, itou/templates/signup/job_seeker_signup.html, itou/www/dashboard/views.py, itou/www/login/views.py, itou/www/signup/views.py
- Corrections de bugs relatifs à PE Connect.
- Ajout d'un interrupteur dans les settings pour désactiver PE Connect rapidement.
- Ajout d'un message dans l'interface (inscription et connexion) si PE Connect ou FranceConnect sont désactivés.
Quand un utilisateur venait de se créer un compte avec PE Connect, il était redirigé vers Itou mais voyait une 404.
Cela vient du fait que Allauth ne prend pas en compte l'adaptateur que nous utilisons à la place de `settings.LOGIN_REDIRECT_URL`. Il continuait de rediriger l'utilisateur vers la valeur par défaut, `/accounts/profile`.
Je propose une redirection de cette URL vers le tableau de bord. Ce n'est pas terrible, j'en conviens, mais c'est rapide et efficace.
À sa déconnexion, l'utilisateur était redirigé vers le site de Pôle emploi et y restait …
=> Boost PEConnect

itou/www/dashboard/views.py
[Dans une PR précédente](https://github.com/betagouv/itou/pull/1364), je proposais de faire un appel HTTP à l'URL de déconnexion de Pôle emploi au lieu de la redirection. Pourquoi ? Car le paramètre `redirect_uri` n'étant plus reconnu par leur SI, l'utilisateur finit son parcours sur le site de PE au lieu d'être redirigé vers le nôtre.
Malheureusement, la technique proposée ne fonctionne pas. Je suppose que le _endpoint_ nettoie des données de session stockées dans le navigateur et qu'il faut, par conséquent, bel et bien que le navigateur charge la page. Ce n'est qu'une supposition.
En attendant, revenons à ce qui fonctionne : la redirection !
=> Déconnexion de PE Connect via une redirection et non via le serveur

itou/metabase/management/commands/sql/021_tx_candidats_acceptes_par_prescripteurs.sql
Suivre le taux d'acceptation des candidats orientés par les prescripteurs
Statistiques d'impact des emplois de l'inclusion
=> Taux acceptation par prescripteur

itou/static/css/itou.css, itou/templates/account/login_generic.html, itou/templates/account/login_job_seeker.html, itou/templates/apply/submit_base_two_columns.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/templates/signup/job_seeker_signup.html, itou/templates/signup/job_seeker_situation.html, itou/www/apply/forms.py, itou/www/apply/views/submit_views.py
Améliorer l'UX de l'étape de renseignement du NIR du candidat dans le parcours de prescription.
Pour assurer la continuité dans le parcours d'inscription et éviter les confusions sur le NIR à renseigner.
• En étant plus guidant dans les étapes
• Laisser le NIR visible à l'écran à l'étape de création du compte candidat
• Rappeler la structure sur laquelle il postule
Déclaration d'une embauche
Un candidat postule
Erreur dans la saisie du NIR
Étape de création du compte candidat
=> Améliorer l'UX de l'étape de renseignement du NIR du candidat dans le parcours de prescription

itou/templates/layout/_footer.html
Mise à jour du lien du footer "Questions à la communauté"
Le lien redirige vers une page 404 (du C3)
Mise à jour de l'url dans le template
=> Lien vers "questions à la communauté" dans le footer

itou/siaes/management/commands/import_siae.py, itou/siaes/models.py, itou/siaes/tests/tests_import_siae_command.py, itou/siaes/tests/tests_models.py, itou/templates/siaes/email/activate_your_account_body.txt, itou/templates/siaes/email/activate_your_account_subject.txt
En tant que SIAE récemment intégrée dans la base de donnée, on m’informe que je peux désormais créer mon compte sur les emplois de l’inclusion.
A ce jour, un grand nombre de SIAE n’ont encore jamais activé leur compte sur les emplois de l’inclusion. Cela les empêche d’embaucher, obtenir des PASS IAE et envoyer leurs fiches a l’ASP. Souvent, ce sont des SIAE qui ont plusieurs structures, donc elles vont créer une antenne, au lieu de rejoindre la bonne structure mère. Ensuite, au moment de l’envoi des fiches salarié, elles envoient sur la mauvaise annexe fi, et contactent le support. Beaucoup de temps en régularisation
Envoyer un email automatique lorsqu’une une nouvelle structure est détectée après l’import de nouvelle SIAE. 
Management Command `import_siae`
Traiter les EA, les EATT et les …
=> Envoyer un email automatique lorsqu’une une nouvelle structure est détectée après l’import de nouvelle SIAE

itou/templates/layout/content.html, itou/templates/stats/stats.html
Mise a jour de la zone de contenu d'aide sur les pages "Stats".
Voir la carte notion pour plus d'infos https://www.notion.so/Modifier-page-des-tableaux-de-bord-529fc3f33cbe42958a3cc88705fee2ee
Pour fournir une aide à la prise en main des Tableaux de bord
En remplacant le bloc de texte “Aide à la lecture et à l'utilisation de ces indicateurs/graphiques” par des `.cards` avec redirection vers la documentation
Ces textes sont présent sur toutes les pages du C1 avec des tableaux de bord
Elles sont toutes derrière l’URL https://c1-review-deloo-update-stats-help-content.cleverapps.io/stats et ayant pour construction [https://c1-review-deloo-update-stats-help-content.cleverapps.io/stats/[rôle]/[nom_du_tebleau_de_bord]](https://c1-review-deloo-update-stats-help-content.cleverapps.io/stats/%5Br%C3% …
=> Mise a jour de la zone de contenu d'aide sur les pages "Stats" 

itou/siaes/management/commands/_import_siae/vue_af.py
- Ignorer les types exotiques comme ACIPA pendant l'import SIAE.
- Petite opti pour éviter l'utilisation de `df.iterrows()` connu pour être mauvais en performance sur suggestion de @vincentporte .
L'import SIAE plante ce jour suite à la toute première apparition du type exotique ACIPA dans la Vue AF.
Testé en local dev avec le dernier dataset de prod et le dernier dataset FluxIAE. L'import SIAE finit dans le vert, ça fait plaisir.
=> Ignorer les types exotiques comme ACIPA pendant l'import SIAE

itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/templates/apply/submit_step_job_seeker.html, itou/www/apply/views/submit_views.py
Des employeurs et des prescripteurs ne peuvent pas passer l’étape de saisie du mail du candidat.
Le bouton suivant ne semble pas fonctionner sur certains navigateurs.
Correction sur le balise `button` en ajoutant l'attribut `value`.
J'en profite pour remettre les messages d'erreur comme avant sur l'étape de saisie de NIR car il y a eu des remontées d'utilisateurs bloqués à cette étape. J'émets l'hypothèse qu'ils avaient une erreur non affichée.
=> Déblocage des employeurs et des prescripteurs à l’étape de saisie du mail du candidat

itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/management/commands/import_geiq.py
1. Ignorer les EA/EATT ayant une convention qui a expirée.
2. Meilleure gestion des emails manquants.
3. Affichage de quelques informations à propos des lignes contenues dans le fichier.
1. Ne pas se préoccuper d'informations désormais inutiles.
2. Que le script fasse ce qu'il doit faire même si ils nous manquent des informations.
3. Avoir une meilleure idée de semaine en semaine de l'évolution du contenu du fichier.
=> Import EA/EATT

itou/siae_evaluations/admin.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/includes/criterion_infos.html
Pendant la phase contradictoire, les `review_state` peuvent être mis à jour par la SIAE et par la DDETS en même temps. Ce qui crée des incohérences de données dans le calcul de l'état de `EvaluatedSiae`
1. Test dans la méthode `state` de `EvaluatedSiae` insuffisant
2. plus un ajout de champ de l'admin et d'un label dans le front pour mieux suivre les états.
mise du calcul de la méthode `state` dans le modèle `EvaluatedSiae`
- Rechercher les cas de `EvaluatedAdministrativeCriteria` avec un `review_state` à `REFUSED_2` mais dont la date `submitted_at` est inférieure à la date `reviewed_at`de la `EvaluatedSiae` mère 
- Mettre à jour ces cas à `REFUSED`
=> Controle a posteriori : patch urgent en phase contradictoire pour prevenir des incoherences de données

itou/approvals/models.py, itou/approvals/tests/tests.py
cf titre
Cas nominal : Le Pass d’un candidat est suspendu. Le candidat est embauché plus tard. La date de fin de suspension du Pass est mise à jour à la veille de la date de début du nouveau contrat.
Règles métier :
- pas d'embauche dans le passé (la date de début de contrat est au minimum aujourd’hui)
- pas de suspension dans le futur (la date de début de suspension est au maximum aujourd’hui)
Cas en erreur :  Le Pass d’un candidat est suspendu au jour J. Le candidat est embauché *le même jour J*. La plateforme tente de mettre à jour la date de fin de suspension à J-1.
⇒ date de fin de suspension (J-1) est inférieur la date de début de suspension (J) … KO
Mise à jour de la méthode `unsuspend` de la class `Approval`. Test de l'équivalence entre la date de début de suspension et la date …
=> Supprimer la suspension si la date de début de contrat est égale à la date de début de suspension du pass

itou/api/data_inclusion_api/tests.py, itou/api/data_inclusion_api/views.py
Active l'authentification par token pour le endpoint data.inclusion
Accès programmatique
=> Active l'authentification par token pour le endpoint data.inclusion

config/settings/base.py, itou/metabase/management/commands/_siaes.py, itou/metabase/management/commands/populate_metabase_fluxiae.py, itou/metabase/management/commands/populate_metabase_itou.py, itou/templates/dashboard/dashboard.html, itou/users/models.py, itou/utils/perms/context_processors.py, itou/www/stats/views.py
- Evolution des stats employeur : "Ensemblier" des structures. Pour la première fois on montre les stats aggrégées de toutes les structures C1 dont l'employeur est membre, pas seulement la structure C1 actuellement sélectionnée.
- Refactorisation de code commun pour récupérer la liste des structures C1 de l'employeur.
- Ajout d'une colonne `structures.nom_complet` (e.g. `ACI - ID 1058 - Emmaüs Alternatives`) dans Metabase qui sera utilisée dans le TDB employeur pour identifier clairement les différentes structures C1 de l'employeur.
- Améliorations mineures des scripts Metabase en passant.
En webinaire employeur en parlant de ce TDB employeur on a eu de nombreux retours comme quoi les employeurs souhaitaient voir les données de toutes leurs structures C1 simultanément.
=> Evolution des stats employeur : "Ensemblier" des structures

itou/www/search/tests.py
job_app_score is None if there are no job descriptions, so the two
following factories have the same score, and their order in the
query_set is not always the same:
- No job description and a job application
- No job description, no job application.
- etc.
=> Fix flaky test

itou/siae_evaluations/models.py, itou/templates/siae_evaluations/includes/criterion_infos.html, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/templates/siae_evaluations/includes/siae_infos.html
Rendre plus explicite les labels pour les DDETS pendant la phase contradictoire.
+ suppression du label "en attente" générateur d'ambiguité pour la SIAE.
Certains labels : 
* laissaient penser que le passage en phase contradictoire avait été annulé pour la SIAE et que par conséquent, tout le travail déjà réalisé par la DDETS était à refaire,
* ne permettaient pas aux DDETS de retrouver rapidement les dernières pièces à valider
* mise à jour des templates
* inversion des contrôles dans la méthode `state` de `EvaluatedJobApplication`
=> Contrôle a posteriori : desambiguation des labels pour les DDETS pendant la phase contradictoire

itou/metabase/management/commands/_job_applications.py
Ajout d'une colonne candidatures.nom_complet_structure dans Metabase.
Pour éviter à Yannick quelques jointures.
Pas de revue car trivial. Testé en dry run, ok.
=> Ajout d'une colonne candidatures.nom_complet_structure dans Metabase

config/settings/base.py, config/settings/demo.py, config/settings/dev.py.template, config/settings/review_apps.py, config/settings/staging.py
Correction de la connexion avec France Connect 
La connexion n'est plus possible (Page blanche Error).
En supprimant le `/` de fin en trop.
=> Correction de la connexion avec France Connect 

itou/allauth_adapters/peamu/adapter.py, itou/allauth_adapters/peamu/tests.py, itou/openid_connect/france_connect/tests.py, itou/openid_connect/france_connect/views.py, itou/www/signup/tests/test_job_seeker.py
Conserver le NIR lors de l'inscription avec France Connect
On ne conserve le NIR que lorsqu'on s'inscrit via le formulaire django.
Il faut aussi le conserver en passant par la mire de connexion France Connect.
NB: Je constate qu'on ne le conserve pas non plus en passant par PE Connect, @celine-m-s on est d'accord que je ne cherche pas à corriger ça ?
=> Conserver le NIR lors de l'inscription avec France Connect

itou/users/adapter.py
Un [AnonymousUser](https://docs.djangoproject.com/en/4.0/ref/contrib/auth/) (utilisateur non authentifié) n'a pas accès aux attributs de notre class User, ce qui fait que si on arrive dans la fonction de logout sur un tel utilisateur, le code va planter.
Sans la valeur par défaut dans getattr, ça ne fonctionnera pas mieux qu'avant.
=> Correction de la déconnextion des utilisateurs anonymes n°2

itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py
Ne plus attendre une 302 de la part de l'url de logout d'Inclusion Connect.
On ne donne pas le paramètre de redirection à Keycloak (`redirect_uri` avec la version 16.1, ou `post_logout_redirect_uri` pour la versions 18.0.2 qui implémente correctement OpenID Connect).
On ne peut donc jamais avoir une 302.
=> Correction du logout pour Inclusion Connect

itou/templates/dashboard/dashboard.html
Le système des fiches salariés est indisponible. Prévenons les utilisateurs que nous sommes au courant.
Problème de transmission avec l'ASP.
Ajout d'un message conditionnel sur le tableau de bord.
=> Affichage d'un message informatif concernant l'indisponibilité des fiches salariés

itou/employee_record/exceptions.py, itou/employee_record/management/commands/_common.py, itou/employee_record/management/commands/transfer_employee_records.py, itou/employee_record/management/commands/transfer_employee_records_updates.py, itou/employee_record/models.py, itou/employee_record/tests/tests_update_management_command.py
- Ajout d'une option `--preflight` pour les management commands des fiches salarié (fiches et notifications de modification).
- Renforcement de la robustesse générale des commandes en cas de problèmes de sérialisation JSON.
Certaines fiches ou notifications peuvent contenir des erreurs de structure menant a des blocages de transferts de données vers l'ASP (dans certains cas aux limites). 
Ajout d'une fonctionnalité / option sur les management commands impactées permettant de : 
- vérifier la sérialisation de l'ensemble des objets à envoyer à l'ASP
- pointer précisément quelle est la première occurrence en erreur (type d'objet, PK, et détails de l'erreur de sérialisation) par le jet d'une exception détaillé (custom).
L'utilisation de cette option de commande n'est pas actuellement …
=> Ajout d'une option de "preflight" pour les management commands des fiches salarié

itou/templates/apply/process_base.html, itou/www/apply/views/process_views.py
Ajout d'une icône à droite du lien pour suspendre quand l'employeur n'a plus la main.
Pour éviter de l'incompréhension liée à la disparition du bouton pour suspendre.
Ajout d'une icône et d'une infos bulle à son survol.
=> Ajout d'une icône à droite du lien pour suspendre quand l'employeur n'a plus la main.

itou/templates/dashboard/dashboard.html
Ajout du lien vers le formulaire de suspension pour les prescripteurs habilités.
Le décret du 30/08/21 précise qu'un  prescripteur habilité peut suspendre un PASS IAE.
Lien sur le tableau de bord.
=> Ajout du lien vers le formulaire de suspension pour les prescripteurs habilités

itou/api/data_inclusion_api/enums.py, itou/api/data_inclusion_api/serializers.py, itou/api/data_inclusion_api/tests.py, itou/api/data_inclusion_api/views.py
Ajout des données organisations (`PrescriberOrganization`) au endpoint représentant les données au format data.inclusion.
dans la continuité des travaux entamés avec #1314
* Un seul endpoint pour les données provenant des 2 tables `Siae` et `PrescriberOrganization`.
* Récupération de l'une ou de l'utre table via le query param `?type=siae` ou `?type=orga`
=> feat(api): ajout des données organisations à la vue d'api data.inclusion

itou/templates/dashboard/dashboard.html
Retrait du message d'information concernant l'incident de juillet 2022 et l'arrêt de la transmission des fiches salarié.
Problème résolu par l'ASP.
Modification du template du dashboard.
=> Retrait du message d'information concernant le dysfonctionnement des fiches salarié

itou/siaes/management/commands/_import_siae/convention.py
Résolution d'un nouveau cas tordu de l'import SIAE.
Parce qu'il s'est produit ce début de semaine.
D'habitude, quand une SIAE est déconventionnée, toutes ses AF dans les données ASP sont marquées invalides, sa convention C1 est alors désactivée, et ce n'est que bien plus tard (voire jamais) que toute trace de cette structure disparait des données ASP.
Cette fois une SIAE, active jusque là, a subitement disparu des données ASP. Du coup on s'est trouvé dans le cas `convention.is_active and siae.siret not in SIRET_TO_ASP_ID` qui n'était pas traité avant cette PR, et le sera dorénavant.
En traitant non seulement l'ancien cas `not convention.is_active and siae.siret not in SIRET_TO_ASP_ID` mais aussi le nouveau `convention.is_active and siae.siret not in SIRET_TO_ASP_ID`.
=> Résolution d'un nouveau cas tordu de l'import SIAE

itou/approvals/factories.py, itou/approvals/tests/tests.py, itou/eligibility/factories.py, itou/eligibility/tests.py, itou/job_applications/factories.py, itou/prescribers/factories.py, itou/prescribers/tests.py, itou/templates/apply/submit_step_pending_authorization.html, itou/users/tests/test_models.py, itou/www/apply/tests/tests_list.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/urls.py, itou/www/apply/views/submit_views.py, itou/www/approvals_views/tests/test_prolongation.py, itou/www/prescribers_views/tests/test_edit.py, itou/www/search/tests.py
Ajout d'un message d'avertissement lors du dépôt de candidature pour les prescripteurs en cours d'habilitation.
Pour éviter la confusion lorsque les employeurs doivent valider les critères d'éligibilité IAE pour une candidature provenant d'un prescripteur habilité entre temps.
Ajout d'une étape en tout début de parcours de dépôt de candidature.
=> Ajout d'un message d'avertissement pour les prescripteurs en cours d'habilitation

scripts/create-fast-machine.sh
Montée de CC_PYTHON_VERSION à 3.10 pour fast-machine.
La version avait été montée partout dans la base de code sauf cet endroit, petit oubli.
Pas de revue, trivial.
=> Montée de CC_PYTHON_VERSION à 3.10 pour fast-machine

itou/templates/dashboard/dashboard.html, itou/www/dashboard/tests.py
Le lien vers le formulaire de suspension pour les prescripteurs habilités est uniquement pour Pôle emploi
Le lien ne doit pas être visible par les autres prescripteur, non concerné.
Une petit `if` dans le template !
=> Le lien vers le formulaire de suspension pour les prescripteurs habilités est uniquement pour Pôle emploi

itou/openid_connect/france_connect/tests.py, itou/openid_connect/france_connect/views.py, itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/openid_connect/models.py, itou/users/models.py, itou/users/tests/test_models.py
Vérifier que les personnes qui se connecte avec FranceConnect/InclusionConnect ne sont pas d'un autre type que celui prévu.
Si son compte est d’un autre type, il doit être redirigé vers la page de connexion.
Un employeur c'est retrouvé à la fois candidat et employeur car il s’est connecté avec FranceConnect.
Le système ne vérifie pas le type d’utilisateur.
1. Le model n'autorise plus d'avoir plusieurs types, il faudrait que ce soit une contrainte mais il faut nettoyer de la donnée avant. Et idéalement il ne faudrait avoir que un seul champs et pas 4 comme actuellement.
2. On affiche un message (avant que le model nous envois bouler) si jamais quelqu'un passe par FC ou IC et que le compte existant n'est pas du bon type.
=> Empêcher qu'un utilisateur cumule les types (candidat, prescripteur, etc)

requirements/base.txt, requirements/deploy.txt
Modifier certaines dépendances.
PE Connect semble cassé depuis une dizaine de jours.
Il demande en outre de valider une nouvelle étape, non nécessaire auparavant.
Enfin, il vient de sortir une mise à jour de sécurité de Django.
En faisant des mises à jour d'urgence pour corriger le problème, mais des investigations plus poussées seront intéressantes et instructives.
=> Correction de dépendances

itou/approvals/models.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/templates/approvals/pe_approval_search_found.html, itou/www/approvals_views/forms.py, itou/www/approvals_views/tests/test_pe_approval.py, itou/www/approvals_views/views.py
Retirer une partie de l'utilisation de l'Approval Wrapper.
Ce code est ancien, complexe et probablement source de confusion dès que nous cherchons à intervenir sur les PASS et agréments.
Il crée du couplage fort entre plusieurs applications du système d'information et est en grande partie obsolète aujourd'hui.
Il est bon de le retirer en vérifiant au passage que certains bugs ne peuvent pas être corrigés par la même occasion.
Quatre étapes (vues commit par commit)
- Nettoyage de certaines incohérences (attente sur le numéro de pass/agrément qui aujourd'hui est toujours unique et à 12 chiffres car consolidé, templates imprécises ou variables non nécessaires, étapes superflues...)
- Nettoyage de l'utilisation du ApprovalsWrapper en mode "recherche d'agrément pour sa transformation manuelle" …
=> Nettoyage du code ApprovalsWrapper (phase 1)

itou/metabase/management/commands/_job_applications.py, itou/metabase/tests/test_job_applications.py
Réparer la colonne Metabase `candidatures.motif_de_refus` qui est devenue 100% vide.
Elle est devenue vide suite à la MEP de cette PR ([lien](https://github.com/betagouv/itou/pull/1427)) et en particulier de ce changement ([lien](https://github.com/betagouv/itou/pull/1427#discussion_r938002402)) :
En raison d'une coicidence malheureuse de deux boulettes.
1) L'oubli de `*.value` sur le enum dans les tests, réparé par la présente PR.
2) Le changement de dernière minute de`None if o.refusal_reason == "" else o.refusal_reason.label` (qui aurait cassé bruyamment au prochain run, même si pas dans les tests) en `getattr(o.refusal_reason, "label", None)` qui renvoit `None` 100% du temps car `o.refusal_reason` est un `str` et donc n'a jamais de champ `label`.
1) Utilisation correcte du `*.value` …
=> Réparer la colonne Metabase `candidatures.motif_de_refus` qui est devenue 100% vide

itou/users/management/commands/extract_c2_users.py
Ne pas spammer les structures inactives.
L'extract C2 contenait les membres de SIAE inactives.
En excluant les membres de SIAE inactives de cet extract destiné à du mailing.
Non, trivial.
=> Ne pas spammer les structures inactives

itou/www/apply/tests/tests_submit.py, itou/www/apply/views/submit_views.py
Ne plus générer une erreur 500 lambda mais, soit une erreur ciblé, soit une redirection vers la page de départ.
Le parcours de dépôt de candidature s'appuis fortement sur les sessions, pour éviter des problèmes nous supprimons ces sessions dès que nous le pouvons mais les utilisateurs utilisent régulièrement le retour navigateur ce qui finis en général par une erreur 500 (car `KeyError`).
Les protections étaient déjà là, mais pas forcément fonctionnelles (:confounded:) ou activées.
Je suis rester superficiel dans les corrections car ces parties vont être supprimées/modifiées avec la dernière étape de la refonte du dépôt de candidature, qui d'ailleurs corrige déjà en partie ces problèmes ;).
=> Meilleure gestion des erreurs de session pour les pages du dépôt de candidature

itou/employee_record/models.py, itou/job_applications/models.py, itou/utils/perms/employee_record.py, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/views.py
La liste des fiches salarié en état `NEW` est incorrecte et affiche des candidatures ayant déjà une fiche salarié associée.
Certaines candidatures ayant déjà une fiche associée sont re-proposées à la complétion / soumission.
Une protection ultérieure empêche l'utilisateur d'aller plus loin, mais l'affichage est définitivement faux.
Un petit oubli sur le commit https://github.com/betagouv/itou/commit/ecc543a0d70fc716086bbb6f884f5cfe94d649f9
La méthode `is_eligible_for_employee_record` devient trop permissive (L231).
Il est nécessaire de filtrer sur les candidatures n'ayant pas encore de fiches salarié associée.
Voir code: exclusion des `job_application` ayant une fiche salarié associée.
Cette PR est un "quick fix" pour améliorer l'expérience utilisateur rapidement. 
Mais elle est aussi un …
=> Erreur d'affichage dans la liste des nouvelles fiches salarié

itou/openid_connect/inclusion_connect/enums.py, itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/templates/invitations_views/includes/invitation_errors.html, itou/templates/invitations_views/invitation_errors.html, itou/templates/invitations_views/new_prescriber.html, itou/templates/invitations_views/new_user.html, itou/users/adapter.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/views.py, itou/www/login/views.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/views.py
En tant que prescripteur invité à rejoindre une organisation , je peux m’inscrire /me connecter via Inclusion Connect
On ne veut plus créer de nouveaux prescripteurs avec un compte Django.
A faire :
=> Invitations de prescripteurs avec Inclusion Connect

itou/institutions/enums.py, itou/institutions/factories.py, itou/institutions/models.py, itou/metabase/management/commands/_organizations.py, itou/prescribers/admin.py, itou/prescribers/enums.py, itou/prescribers/factories.py, itou/prescribers/management/commands/import_pole_emploi_agencies.py, itou/prescribers/management/commands/update_refused_prescriber_organizations_kind.py, itou/prescribers/migrations/0017_update_authorization_status.py, itou/prescribers/models.py, itou/prescribers/tests.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/dashboard/dashboard.html, itou/users/management/commands/extract_c2_users.py, itou/users/models.py, itou/users/tests/test_models.py, itou/www/dashboard/tests.py, itou/www/dashboard/views.py, itou/www/invitations_views/forms.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/prescribers_views/forms.py, itou/www/prescribers_views/tests/test_edit.py, itou/www/prescribers_views/views.py, itou/www/signup/forms.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/views.py
Déplacement des types de prescripteurs et des institutions dans des fichiers dédiées.
Pour améliorer la lecture du code des modèles et des `enums`.
En créant des fichiers `enums.py`.
=> Déplacement des types de prescripteurs et des institutions dans des fichiers dédiées pour en améliorer la lecture

itou/job_applications/enums.py
cf le titre
bug graphique
masquer les choix du `form.refusal_reason` si pas de label texte
=> Un bouton radio sans texte dans les motifs de refus

config/settings/base.py, itou/job_applications/management/commands/display_missing_eligibility_diagnoses.py, itou/job_applications/tests/tests.py, itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/move_siae_data.py, itou/siaes/tests/test_management_commands.py, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/users/management/commands/deduplicate_job_seekers.py, itou/users/management/commands/extract_c2_users.py, itou/users/tests/test_management_commands.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/views.py
La semaine dernière (3J) a été dédiée à la correction des boost sur le controle a posteriori.
Cette "semaine" (1.5J) corrige un certain nombre de boost dev qui trainaient depuis longtemps.
A noter que le ticket concernant l'[erreur de sécurité sur l'envoi de mails](https://www.notion.so/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=a21b982d589f4743bdc9e34ee0e2dbb0&pm=s) n'a pas de correction.
Les premiers commits sont  de la mise au propre pour servir des commits suivants,
et quelques erreurs ou choses dommages corrigées en chemin.
Les derniers commits concernent des tickets Notion.
Cf Notion pour les derniers commits.
- [Justificatif téléversé](https://www.notion.so/de268046f9a044b2a7c80cdbf98ad8b7?v=d0715164c06741279f40cea896652fe1&p=b86625e9f9d441c181e05e27ca47ef …
=> BOOST Sprint 47 ("week" 2)

itou/metabase/management/commands/sql/017_fiches_deposte_en_tension_recrutement.sql
Remplacement du motif de refus "pas de poste ouvert en ce moment" par "pas de recrutement en cours" suite à MEP C1
=> Correction nouveaux motif de refus

itou/siaes/management/commands/move_siae_data.py, itou/siaes/tests/test_management_commands.py
Déplacement des données de contrôle a posteriori pendant un move_siae_data.
Sans cela, ces données restaient sur l'ancienne SIAE, et cette dernière étant souvent supprimée au final, les données en question disparaissaient mystérieusement.  Un garde fou a été placé mais le cas se reproduit donc pas le choix, il faut implémenter le transfert de ces données.
Comme pour toutes les autres données déplacées par move_siae_data.
=> Déplacement des données de contrôle a posteriori pendant un move_siae_data

itou/templates/apply/process_cancel.html, itou/www/apply/tests/tests_process.py, itou/www/apply/views/process_views.py
Rendre plus explicite l'annulation d'un Pass
Certains employeurs annulent les PASS : 1-par erreur, 2-à la place d’une suspension, 3-pensant bien faire pour ainsi repartir “au propre” sur le parcours du salarié embauché
- modification du message d'alerte
- affichage du lien `suspendre` lorsque c'est possible
=> En tant que SIAE je veux m'assurer que l'annulation du PASS est justifiée dans mon cas

itou/prescribers/models.py, itou/users/models.py, itou/www/stats/views.py
Les DR PE (Direction Régionale Pôle emploi) peuvent maintenant voir les stats de toute leur région et non de seulement leur département.
Dans la db C1 les DR PE sont actuellement des agences PE comme les autres, du coup, comme les agences PE classiques, elles n'avaient accès qu'aux stats de leur département.
Une DR PE a bien sûr vocation à consulter les stats de sa région entière et pas juste son département.
Vu le nombre très réduit (18) de DRPE et leur stabilité dans le temps, on évite de rajouter un champ ou un type d'organisation prescripteur, et on hardcode leur liste. Cela me parait le plus simple mais c'est ouvert à débat.
- (Non bloquant) Décider comme faire évoluer le tracking Matomo correspondant pour distinguer proprement DRPE du reste.
- (Non bloquant) Rajouter un filtre …
=> Les DR PE peuvent maintenant voir les stats de toute leur région

itou/fixtures/django/12_pe_approvals.json
Le pass IAE des fixtures expirait en février 2022 ce qui empêchait de candidater.
=> Mise à jour des dates du passe IAE des fixtures

itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/siaes/models.py, itou/www/apply/views/submit_views.py
Je vois qu'on a deux manières de récupérer l'url complète du site :
- une fonction get_absolute_url qui se base sur des settings
- request.build_absolute_uri quand un a un object request valide.
C'est utile pour mettre des liens dans les emails ou pour générer des urls de retour quand on redirige l'utilisateur vers un site partenaire (par exemple les SSO : France Connect, Inclusion Connect ou PE Connect)
Je propose de ne garder que la 1ère qui a l'avantage de fonctionner aussi dans les management commands (où aucun objet request n'est disponible)
- etc.
=> Homogénéiser la construction de l'url du site

itou/siaes/management/commands/_import_siae/convention.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/management/commands/import_ea_eatt.py, itou/siaes/tests/tests_import_siae_command.py
- Fix TDD d'une typo dans le code de l'import SIAE.
- Fix import EA : on ignore le nouveau type exotique EAMP.
- Evolution de la règle qui autorise les imports SIAE/EA/GEIQ à supprimer automatiquement des structures
- Règle plus sûre (ne jamais jamais supprimer une structure sous contrôle)
- Règle plus aggressive (supprimer dorénavant les structures n'ayant que des candidatures à l'état nouveau, et peu importe s'il elles ont des membres)
- Voir ci-dessous le avant/après : changement pas énorme mais tout de même
```
227 siaes past their grace period cannot be deleted
97 EA_EATT cannot be deleted as they have data.
199 siaes past their grace period cannot be deleted
72 EA_EATT cannot be deleted as they have data
```
L'import ASP casse cette semaine sur les 2 premiers soucis.
=> Evolutions mineures des imports SIAE et EA

itou/employee_record/tests/tests_notifications.py
Correction d’un test au résultat incertain
Le test a échoué dans https://github.com/betagouv/itou/pull/1498, alors
que la PR ne change rien en rapport avec ce test.
=> Correction d’un test au résultat incertain

itou/eligibility/admin.py, itou/eligibility/factories.py, itou/eligibility/migrations/0010_eligibilitydiagnosis_expires_at.py, itou/eligibility/models.py, itou/fixtures/django/10_eligibility_diagnoses.json
Création d'un champs persisté en DB pour `EligibilityDiagnosis.expires_at`.
Dans le nouveau parcours du dépôt de candidature nous donnons la possibilité aux prescripteurs habilités de mettre un jour le diagnostique d’éligibilité, ce changement introduis deux cas : 
1. Lorsqu'un PH met à jour le diagnostique alors on crée un nouvel objet et l'on fait terminer l'actuel en modifiant `expires_at`.
2. Si les critères et la personnes réalisant le diagnostique sont les mêmes alors on modifie `expires_at` pour que l'objet reste valable encore 6 mois.
=> Remplacement de la propriété `EligibilityDiagnosis.expires_at` par un champs

envs/dev.env.template
Mise à jour du envs/dev.env.template.
Inclusion Connect peut désormais tourner en local mais il faut indiquer les bonnes variables d'environnement.
=> Ajout de variables d'environnement en dev pour Inclusion Connect

itou/templates/account/login_generic.html, itou/templates/inclusion_connect/includes/description.html, itou/users/admin.py, itou/www/invitations_views/views.py, itou/www/login/views.py, itou/www/signup/views.py
- désactiver les mires lorsque l'url n'est pas définie dans les settings
- afficher l'identity provider dans l'admin du modèle User (au lieu de juste s'il utilise PE Connect)
=> Améliorations diverses pour inclusion connect

config/settings/base.py, itou/users/models.py, itou/users/tests/test_models.py
Ouverture nationale des stats PE+Employeur.
Le grand jour du C2 est arrivé !
- Fix d'un flaky test `test_can_view_stats_cd` qui se déclenchait 4% du temps (4 départements sur 100).
~Virer `STATS_SIAE_USER_PK_WHITELIST` des instances clever de conf.~ Eh non, on l'utilise encore pour le TDB expérimental des ETP.
=> Ouverture nationale des stats PE+Employeur (MEP le 7 septembre)

itou/utils/apis/geocoding.py
Gérer les retours de l'appel à l'API de Géocoding
En cas d'anomalie lors du géocoding d'une adresse, le plantage de l'API fait planter nos processus métier au lieu de rendre la main à l'utilisateur pour lui permettre de corriger l'adresse.
Dans le cas de l'anomalie sentry traitée, le plantage empêche la création de la fiche salariée.
Ajout de la gestion les codes 5xx dans la méthode `call_ban_geocoding_api`
ref https://www.python-httpx.org/exceptions/
remarque : partie de code mockée mais jamais testée ;)
=> Permettre la correction de l'adresse du candidat lors de la création de la fiche salariée

Makefile
Corrige la version Python du Makefile
La version de prod est 3.10.
=> Corrige la version Python du Makefile

Makefile
Marque les règles Make qui ne crée pas de fichiers .PHONY
Indique à `make` de ne pas chercher de fichier correspondant à la règle.
=> Marque les règles Make qui ne crée pas de fichiers .PHONY

README.md
Groupe les notes d’installation Docker et venv
Regroupe les notes spécifiques à l’environnement virtuel pour clarifier quelle note correspond à quel environnement. De même avec Docker.
=> Groupe les notes d’installation Docker et venv

config/settings/base.py, config/settings/prod.py, itou/templates/stats/stats.html, itou/utils/apis/metabase.py, itou/www/stats/views.py
Intégration de formulaires Tally (successeur de Typeform) sur les vues stats.
Annie souhaite mesurer la satisfaction utilisateur sur chaque vue stat et a préparé un formulaire spécifique pour chaque vue.
=> Intégration de formulaires Tally (successeur de Typeform) sur les vues stats

itou/employee_record/management/commands/sanitize_employee_records.py, itou/employee_record/models.py, itou/employee_record/tests/tests_management_commands.py
Modification de la management command `sanitize_employee_records` avec l'ajout de la vérification des fiches salarié sans PASS IAE associé.
Au fil du temps, certaines candidatures voient le PASS IAE qui leur est associé être supprimé (pour différentes raisons).
Il n'y a pas de contrainte ou liaison en DB directe entre une fiche salarié et son PASS IAE (ça passe par la candidature).
Si aucun PASS IAE n'est présent, l'API ne peut pas afficher les fiches en question (source d'erreur Sentry).
**SUPPRESSION** des fiches salarié sans PASS IAE associé.
Il n'y a aucun intérêt à garder des fiches dont le PASS IAE n'existe plus (incohérent).
=> Nettoyage des fiches salarié sans PASS IAE

itou/common_apps/resume/forms.py, itou/eligibility/models.py, itou/eligibility/tests.py, itou/static/css/itou.css, itou/static/js/utils.js, itou/templates/apply/email/new_for_job_seeker_body.txt, itou/templates/apply/submit/application/base.html, itou/templates/apply/submit/application/eligibility.html, itou/templates/apply/submit/application/end.html, itou/templates/apply/submit/application/jobs.html, itou/templates/apply/submit/application/resume.html, itou/templates/apply/submit_base.html, itou/templates/apply/submit_step_application_sent.html, itou/templates/apply/submit_step_check_job_seeker_nir.html, itou/users/models.py, itou/users/tests/test_models.py, itou/utils/python.py, itou/utils/session.py, itou/utils/templatetags/str_filters.py, itou/utils/tests.py, itou/www/apply/forms.py, itou/www/apply/tests/tests_submit.py, itou/www/apply/urls.py, itou/www/apply/views/submit_views.py, itou/www/eligibility_views/forms.py, itou/www/eligibility_views/tests.py
:warning: Il ne faut relire qu'à partir des `js.utils: Add ...` (5ffcc350). Les commits précédents sont ceux des PR #1472 et #1473. :warning:
Améliorer le parcours prescripteur de dépôt de candidature.
- Les prescriptions ne sont pas assez détaillées et donc pas assez qualitatives pour les recruteurs.
- Manque d'accompagnement dans la complétion de la candidature
Comme à l’accoutumé les premiers commits sont préparatoire :
1. Ajout de nouvelles fonctionnalités JS
a. `swap-elements`
Utiliser dans la dernière page du parcours pour passer de l'affichage texte au formulaire lorsqu'on clique sur le bouton "modifier".
b.`shroud`
Utiliser sur la page des critères d'éligibilités pour "désactiver" le formulaire.
2. Transformation des 2 FBV `step_check_job_seeker_info()` et …
=> [Refonte Dépôt de candidature 3/3] Améliorer le parcours de prescription

itou/www/siae_evaluations_views/tests/tests_siaes_views.py, requirements/dev.txt
Correction du résultat incertain de SiaeUploadDocsViewTest.test_access
Le test échouait de manière aléatoire, sur des changements qui ne modifiait pas le comportement correspondant.
Exemple d’erreur :
```
FAIL: test_access (itou.www.siae_evaluations_views.tests.tests_siaes_views.SiaeUploadDocsViewTest) [s3_form_values] (k='fields')
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/freitafr/dev/itou/itou/www/siae_evaluations_views/tests/tests_siaes_views.py", line 483, in test_access
self.assertEqual(v, response.context["s3_form_values"][k])
AssertionError: {'x-a[131 chars]070214Z', 'policy': 'eyJleHBpcmF0aW9uIjogIjIwM[419 chars]54e'} != {'x-a[131 chars]070215Z', 'policy': 'eyJleHBpcmF0aW9uIjogIjIwM[419 chars]326'}
- …
```
=> Correction du résultat incertain de SiaeUploadDocsViewTest.test_access

.github/workflows/ci.yml
- Simplification de la configuration
- Ajout d’un cache pour les dépendances
Une seule version de Python est utilisée, il est inutile de configurer une matrice de versions.
Les dépendances sont systématiquement téléchargées depuis PyPI, ce qui augmente la pression sur PyPI et ralentit les builds.
=> Petites améliorations de l’outil d’intégration continue

config/settings/base.py, itou/siaes/enums.py, itou/siaes/tests/tests_models.py, itou/www/siaes_views/forms.py
Depuis 2 ans une expérimentation permet de faire un parcours préalablement à l’entrée dans un ACI. Il s’agit des dispositif Convergence et Premières Heures en Chantier. Il faut limiter la sélection de ce type de contrat uniquement à une liste d’ACI.
Ajout d'une variable d'environnement pour définir la whitelist dans le code.
=> Limiter l'accès aux contract PHC à une liste définie d'ACIs

itou/templates/dashboard/dashboard.html, itou/www/dashboard/tests.py
Restaure l'affichage du PASS IAE pour les candidats sur leur tableau de bord.
Cela avait disparu suite à cette (un peu trop grosse) [PR](https://github.com/betagouv/itou/pull/1450).
En rétablissant le bon paramètre pour le gabarit, et en testant la sortie attendue.
=> dashboard: Restore displaying the PASS IAE for job seekers

itou/approvals/management/commands/export_pe_api_rejections.py, itou/approvals/tests/test_management_commands.py
Ajout d'une commande à lancer régulièrement pour informer PE.
PE nous demande à présent de leur communiquer chaque début de mois la liste des erreurs que leur API nous a envoyées afin qu'ils puissent investiguer. Cette commande en sera le moyen.
En proposant une liste CSV des rejets de l'API.
=> approvals: Ajout d'une commande pour gérer les rejets d'API PE

.github/workflows/review-app-creation.yml
Deploiement recette: limite le nom de l’app à 63 caractères
Enlever le warning sur le nom des branches de la documentation.
La taille maximal d’un `label` dans un nom de domaine est 63 caractères
(partie du domaine entre les points).
https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.4
=> Deploiement recette: limite le nom de l’app à 63 caractères

itou/templates/signup/prescriber_check_already_exists.html, itou/utils/apis/api_entreprise.py, itou/utils/tests.py, itou/www/signup/forms.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/urls.py, itou/www/signup/views.py
L’API entreprise est parfois injoignable pendant plusieurs heures pour des raisons de maintenance. Par exemple, du 31 janvier au 3 février ou le 21 septembre prochain.
Le prescripteur qui souhaite se créer un compte avec une organisation voit alors l’erreur suivante : 
> Problème de connexion à la base Sirene. Essayez ultérieurement.
L'erreur lié à l'API empêche un prescripteur de s'inscrire et/ou de rejoindre une structure déjà existante alors que l'API ne nous sert pas dans ce cas précis.
Déplacement des appels API dans le formulaire utilisé lorsqu'on veux créer une nouvelle organisation plutôt que lorsqu'on recherche si elle existe.
=> Amélioration de la résilience du parcours d'inscription prescripteur face aux API indisponibles

config/settings/prod.py
Dans le titre.
Pour suivre les recommandations de Django et de l'audit de sécurité.
Mettant la valeur du setting à 1 an.
=> settings: Augmenter le timeout HSTS

itou/www/siae_evaluations_views/tests/tests_siaes_views.py
Une des fixtures a une apostrophe dans son nom, caractère qui est transformé en `&#x27;` dans la réponse HTML.
- etc.
=> Correction d'un test

itou/metabase/management/commands/sql/019_candidatures_echelle_locale.sql
A la demande de PE, du nom du conseiller pe ayant effectué la prescription
=> Candidatures : ajout nom conseiller pe

requirements/base.in, requirements/base.txt, requirements/demo.txt, requirements/dev.txt, requirements/prod.txt, requirements/staging.txt
It is required by boto3 and will be automatically updated on its own every time we bump the dependencies by runnning compile-deps.
With this change, we get rid of this happening randomly which can be annoying.
[non je ne traduis pas tout ça, ça n'a pas a entrer dans le changelog, etc]
=> [TECH] Bump botocore

itou/templates/layout/_header.html
The button appears as “{% include 'layout/_nav_btn_items.html' with
button_size='btn-sm' %}” in the template.
Correction d’une typo sur le bouton “S’inscrire | Se connecter”.
Un extrait de code incompréhensible apparait actuellement pour les utilisateurs.
=> Fix typo in “S’inscrire” nav option

itou/templates/approvals/includes/status.html, itou/templates/approvals/printable_approval.html, itou/templates/employee_record/create.html, itou/templates/employee_record/disable.html, itou/templates/employee_record/includes/list_item.html, itou/templates/employee_record/reactivate.html, itou/templates/employee_record/summary.html, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html, itou/utils/templatetags/format_filters.py, itou/utils/tests.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
Enlève les espaces lors de la présentation d’identifiants
Le support reçoit régulièrement les numéros copiés/collés, qui contiennent les espaces. La saisie d’un numéro avec les espaces dans un champ de recherche affecte la pertinence des résultats. Le support “nettoie” les données manuellement en enlevant les espaces avant d’effectuer une action.
Avec un peu de markup et de CSS :
`<span>GROUPE1</span><span class="ml-1">GROUPE2</span>`
=> Enlève les espaces lors de la présentation d’identifiants

itou/templates/apply/submit/application/resume.html, itou/www/apply/tests/tests_submit.py
Ajout des fiches de poste sélectionnées dans le formulaire en tant que champs cachés.
Depuis la MEP de #1485 toutes les candidatures sont enregistrées sans les fiches de postes sélectionnées en étape 1.
=> Correction : Les candidatures ne sont plus toutes enregistrées comme "spontanée"

itou/approvals/models.py, itou/approvals/tests/tests.py, itou/www/approvals_views/forms.py
Le motif de suspension d'un pass IAE "contrat de travail suspendu depuis plus de 15 jours" est un motif de suspension comme les autres et permet à un candidat de postuler à d'autres offres.
Actuellement le motif “contrat de travail suspendu depuis plus de 15 jours” implique qu’il n’est pas possible de travailler dans une  autre SIAE par conséquent l’orientation est bloquée.
Cependant les candidatures créées avant la suspension peuvent encore être validées mais la suspension du PASS n’est pas levée. On constate également que ce motif est mal utilisé par les employeurs . Ces 2 problématiques génèrent des tickets au support
Plutôt que de réaliser 2 développements pour résoudre ces 2 problèmes, nous proposons d’aller vers + de simplification en assumant le fait que certains employeurs …
=> Le motif de suspension “contrat de travail suspendu depuis plus de 15 jours” d'un pass IAE n’empêche plus de postuler à d'autres offres

Makefile, README.md
Instead of requiring everybody to type the path to their venv, just make
an alias.
=> Add a venv alias to build the virtualenv

config/settings/base.py, itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/job_applications/tests/tests_transfer.py, itou/prescribers/models.py, itou/prescribers/tests.py, itou/siaes/management/commands/_import_siae/utils.py, itou/siaes/models.py, itou/siaes/tests/tests_models.py, itou/templates/approvals/includes/status.html, itou/templates/dashboard/dashboard.html, itou/templates/includes/test_accounts.html, itou/templates/prescribers/email/refused_prescriber_organization_email_body.txt, itou/templates/signup/siae_select.html, itou/utils/settings_context_processors.py, itou/utils/templatetags/tally.py, itou/utils/tests.py, itou/utils/urls.py, itou/www/approvals_views/tests/test_suspend.py, itou/www/dashboard/forms.py, itou/www/dashboard/tests.py, itou/www/employee_record_views/forms.py, itou/www/signup/tests/test_siae.py
Les modifications suivantes effectuées pour les différentes cartes Notion de boost dev : 
- les réponses données aux candidatures sont supprimées lors d'un transfert entre SIAE
- notification des données factices sur l'environnement de démo
- correction d'un avertissement concernant le format de date lors de l'import des SIAE
- vérification de la suppression de l'e-mail de notification d'une nouvelle embauche pour les SIAE
- suppression de l'affichage de la raison d'une suspension
- lors de la saisie des informations d'un utilisateur, le téléphone devient optionnel et les informations de l'adresse obligatoires
- modification de l'e-mail envoyé aux prescripteurs lors d'un refus d'habilitation
- suppression de Typeform et remplacement par Tally
Dans le cadre de la session Supportix.
Avec …
=> Boost Dev - Sprint 50 - Semaine 37

itou/job_applications/models.py, itou/job_applications/tests/tests.py, itou/users/models.py, itou/users/tests/test_models.py
Calcul de la date d'acceptation d'une candidature :
- Pour une candidature classique : on se réfère au log des transitions
- Pour une candidature créée lors d’un import d’agrément : on se réfère à la date de création de la candidature.
Permettre au dernier employeur qui a embauché un candidat d’avoir la main pour prolonger ou suspendre
En ne se basant plus sur la date de contrat mais sur la date d’acceptation de la candidature.
=> Permettre au dernier employeur qui a embauché un candidat d’avoir la main pour prolonger ou suspendre

itou/invitations/models.py, itou/openid_connect/inclusion_connect/models.py, itou/openid_connect/inclusion_connect/tests.py, itou/openid_connect/inclusion_connect/views.py, itou/siaes/models.py, itou/templates/account/login_generic.html, itou/templates/invitations_views/new_ic_user.html, itou/templates/signup/siae_user.html, itou/users/enums.py, itou/users/models.py, itou/users/tests/test_models.py, itou/utils/perms/middleware.py, itou/www/invitations_views/forms.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/invitations_views/urls.py, itou/www/invitations_views/views.py, itou/www/login/forms.py, itou/www/login/tests.py, itou/www/login/views.py, itou/www/signup/forms.py, itou/www/signup/tests/test_prescriber.py, itou/www/signup/tests/test_siae.py, itou/www/signup/urls.py, itou/www/signup/views.py, itou/www/welcoming_tour/tests.py
Le lien d'invitation envoie sur la page suivante :
- etc.
=> Utiliser Inclusion Connect en tant qu'employeur

itou/siae_evaluations/models.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py
Débute la phase contradictoire avec EvaluatedSiae.reviewed_at
La revue des justificatifs d’auto-prescription des SIAE par les DDETS s’effectue en deux phases. Premièrement, une phase amiable durant laquelle les SIAE peuvent envoyer les justificatifs, pour qu’ils soient traitées par la DDETS. Une fois la phase amiable terminée, les SIAE dont les justificatifs ont été refusées entrent dans une phase contradictoire, d’une durée de 6 semaines, leur offrant la possibilité de se conformer aux remarques de la DDETS. La DDETS va alors à nouveau traiter les documents, et cette fois un refus est définitif.
La date d’intérêt est la première revue, qui a démarré la phase contradictoire. La seconde revue est définitive, sa date importe peu et n’est pas enregistrée pour le moment.
=> Débute la phase contradictoire avec EvaluatedSiae.reviewed_at

config/settings/base.py, config/urls.py, itou/utils/perms/tests.py, itou/utils/perms/user.py, requirements/base.in, requirements/base.txt, requirements/demo.txt, requirements/dev.txt, requirements/prod.txt, requirements/staging.txt
Permettre à un groupe d'administrateurs d'aller plus vite sur leurs investigations en permettant de "voir" le site comme un autre utilisateur.
En particulier le support mais aussi les développeurs peuvent passer du temps à demander à un utilisateur des détails, captures d'écran, URLs, etc qui peuvent prendre du temps, etre imprécises, etc.
Avec cette fonctionnalité les administrateurs seront en mesure de valider eux-memes un problème et avoir tous les indices directement.
En utilisant django-hijack.
Cf la review app:
=> support: Ajouter une fonctionnalité pour prendre temporairement l'identité d'un utilisateur

itou/allauth_adapters/peamu/tests.py, itou/api/employee_record_api/tests/tests.py, itou/approvals/tests/tests.py, itou/openid_connect/inclusion_connect/tests.py, itou/prescribers/tests.py, itou/utils/tests.py, itou/www/apply/tests/test_edit.py, itou/www/apply/tests/tests_list.py, itou/www/apply/tests/tests_process.py, itou/www/apply/tests/tests_submit.py, itou/www/approvals_views/tests/test_display.py, itou/www/approvals_views/tests/test_pe_approval.py, itou/www/approvals_views/tests/test_prolongation.py, itou/www/approvals_views/tests/test_suspend.py, itou/www/dashboard/tests.py, itou/www/employee_record_views/tests/test_create.py, itou/www/employee_record_views/tests/test_disable.py, itou/www/employee_record_views/tests/test_list.py, itou/www/employee_record_views/tests/test_reactivate.py, itou/www/employee_record_views/tests/test_summary.py, itou/www/invitations_views/tests/tests_prescriber_organization.py, itou/www/invitations_views/tests/tests_siae_accept.py, itou/www/invitations_views/tests/tests_siae_send.py, itou/www/prescribers_views/tests/test_admins.py, itou/www/prescribers_views/tests/test_edit.py, itou/www/prescribers_views/tests/test_members.py, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siaes_views/tests/tests_job_description_views.py, itou/www/siaes_views/tests/tests_views.py
Utilisation de la méthode `force_login()` du client de test au lieu de `login()`.
`login()` vérifie sérieusement les identifiants de l’utilisateur, ce qui est coûteux en terme de calcul. `force_login()` “hack” le système pour que l’utilisateur soit directement connecté.
Même si certains tests vérifient le comportement du *backend d’authentification*, la plupart des tests veulent simplement simuler un utilisateur identifié sur le site. Les quelques tests pour qui le comportement du backend d’authentification est important ont été préservés, les autres utilisent maintenant `force_login()`.
Un petit point d’attention : `force_login()` ne vérifie pas que `User.active is True`. Les tests modifiés ne vérifient pas l’accès avec un utilisateur inactif.
=> Accélération des tests

.github/workflows/ci.yml, Makefile, itou/siaes/tests/tests_import_siae_command.py, pytest.ini, requirements/dev.in, requirements/dev.txt
Utilisation de pytest pour lancer les tests
- L’utilisation du runner Django est assez verbeuse (pas mal de configuration). Voir https://itou-inclusion.slack.com/archives/C0412CTV63D/p1663851337162789
- L’interface du runner Django est bien moins aboutie, notamment à cause de l’affichage des messages (`print()`) qui empêche de suivre la progression des tests, et les rapports d’échecs et d’erreurs pytest sont beaucoup plus précis, facilitant le diagnostic.
- En attendant un débat avec l’équipe, je propose de garder la compatibilité avec unittest. Pour cette raison, la CI continue de tourner avec le test runner django (basé sur unittest). Le runner pytest est simplement plus mis en avant afin d’améliorer la qualité de vie des devs.
- Cheatsheet :
- `make test` : `pytest`
- `make …
=> Utilisation de pytest pour lancer les tests

itou/asp/factories.py, itou/common_apps/address/format.py, itou/employee_record/admin.py, itou/users/tests/test_models.py, itou/utils/mocks/address_format.py
- réparation d'un problème de formatage d'adresse dans le parcours des fiches salarié
- au passage ajout de l'information de forçage de l'intégration d'une fiche salarié dans l'admin
Affichage bloquant d'une erreur à la première étape de la saisie des fiches salarié lorsque l'adresse du salarié comporte un type de voie "exotique" (en Basque ou Breizh) non-référencé par l'ASP ou pas de type de voie du tout.
Si le type de voie n'arrive pas a être correctement déterminé, on se replie sur "Lieu-Dit" (LD).
De toute façon, ces informations ne sont pas impactantes pour l'ASP (et peuvent si besoin être modifié sur l'extranet).
Il faudra effectuer une refonte de `format_address` et le border correctement de tests. 
Et refondre aussi l'utilisation des mocks de géoloc (tout pourris, mais j'assume).
=> Blocage du parcours des fiches salarié en cas d'absence de type de voie dans l'adresse du salarié

config/settings/base.py, itou/metabase/management/commands/_job_seekers.py, itou/templates/dashboard/dashboard.html, itou/templates/stats/stats.html
Boost stats avec au menu :
- Ajout de colonnes utiles extraites du NIR (sexe, année et mois de naissance) dans la table `candidats` sur Metabase.
- Ajout de deux blocs informatifs en bas des pages stats exactement comme c'est déjà fait sur le site https://pilotage.inclusion.beta.gouv.fr/
- Désactivation temporaire de certains formulaires Tally à la demande d'Annie. Commentés dans le code donc facilement réactivables. Attention @vperron tu as auras un petit merge conflict sur le setting `METABASE_DASHBOARDS`.
- Débranchage du TDB AF DGEFP qu'on rebranchera début 2023 (donc on le garde prête à rebrancher).
- Retrait plusieurs badges "Nouveaux".
J'aurai bien aimé écrire des tests pour `_job_seekers` mais malheureusement pas possible tant que je n'ai pas d'abord résolu un bug cryptique de …
=> Boost stats

.github/workflows/ci.yml
Les changements concernant la façon d'installer les dépendances font que `make test` lance désormais une installation de dépendances en sous-main dans un dossier `.venv` bien particulier.
Or, le build CI actuel réalisait déjà une installation de dépendances juste avant, mais sans le faire dans ce dossier `.venv`. On avait donc deux installations de dépendances, une "globale" puis une locale (qui fail, car le CPUCOUNT n'est plus mis en place).
Par ailleurs, si l'on passe à une installation de dépendances via la Makefile (`make venv`), les commandes qui ne passent pas par ce dernier vont échouer car elles vont chercher à résoudre les binaires dans l'environnement global elles aussi; il faut leur donner le chemin vers le `.venv` pour assurer le fonctionnement.
=> ci: Correction du build

itou/employee_record/tests/tests_models.py, itou/prescribers/tests.py, itou/www/eligibility_views/tests.py
assertEquals is deprecated.
https://docs.python.org/3/library/unittest.html#deprecated-aliases
=> Replace deprecated assertEquals → assertEqual

scripts/create-fast-machine.sh
We never run `django-admin run_huey` on the fast machines.
They're not supposed to access the redis then.
Stop any confusion !
=> fast-machine: Retirer les accès Redis.

itou/siae_evaluations/models.py, itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/siae_job_applications_list.html, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/urls.py, itou/www/siae_evaluations_views/views.py
Ajout de l’ID des SIAE évaluées aux URLs du contrôle a posteriori
La même SIAE peut être évaluée sur plusieurs campagnes. Au lieu de déduire l’évaluation à partir du statut de la campagne, le système utilise maintenant l’ID passé en paramètre.
Pour être sélectionnée dans une campagne de contrôle a posteriori, une SIAE doit avoir réalisé des auto-prescriptions et donc avoir au moins une candidature. Le cas d’une SIAE contrôlée sans candidatures ne devrait pas arriver en pratique. Maintenant, le système indique l’erreur avec un code de statut 404 (not found) au lieu d’afficher une page presque vide indiquant qu’aucun contrôle n’est en cours.
SiaeJobApplicationListViewTest.test_access compte les requêtes SQL, mais ce nombre dépend des requêtes HTTP précédentes, qui initialisaient des caches. …
=> Ajout de l’ID des SIAE évaluées aux URLs du contrôle a posteriori

itou/siae_evaluations/admin.py, itou/www/siae_evaluations_views/forms.py
That’s the default Python inheritance style, is easier to follow and
friendlier to renaming.
https://rhettinger.wordpress.com/2011/05/26/super-considered-super/
=> Use Python 3 super()

itou/templates/siae_evaluations/includes/criterion_validation.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/templates/siae_evaluations/siae_job_applications_list.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/tests/tests_siaes_views.py, itou/www/siae_evaluations_views/views.py
Contrôle a posteriori: Utiliser POST pour modifier les données
Meilleure accessibilité pour les utilisateurs, indique que cliquer sur le bouton soumet un formulaire et modifie des ressources sur le serveur, au lieu d’indiquer une simple navigation.
Facilite l’observation côté serveur des requêtes qui changent les données ou pas.
=> Contrôle a posteriori: Utiliser POST pour modifier les données

itou/siae_evaluations/admin.py, itou/siae_evaluations/enums.py, itou/siae_evaluations/migrations/0009_evaluatedsiae_sanctioned_at.py, itou/siae_evaluations/models.py, itou/siae_evaluations/tests/tests_models.py, itou/templates/siae_evaluations/includes/job_seeker_infos_for_institution.html, itou/templates/siae_evaluations/includes/siae_infos.html, itou/templates/siae_evaluations/institution_evaluated_siae_detail.html, itou/templates/siae_evaluations/institution_evaluated_siae_list.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py
Évaluation SIAE: Implémentation de la phase contradictoire
Précédemment, une SIAE entrée en phase contradictoire y restait définitivement. Lorsqu’une décision est prise, la DDETS devrait voir le résultat de cette décision.
Un nouveau champ est ajouté au modèle EvaluatedSiae: `final_reviewed_at`. Il permet de distinguer la phase amiable de la phase contradictoire.
Le statut `REVIEWED` est supprimé. Il indiquait auparavant un état transitoire entre la revue d’une SIAE par une DDETS et la prise d’une décision. Une décision positive donne immédiatement lieu à un résultat positif, sans passer par cet état. L’effet d’une décision négative varie :
- dans la phase amiable, il débute la phase contradictoire, offrant …
=> Évaluation SIAE: Implémentation de la phase contradictoire

.dockerignore, .env.template, Makefile, config/settings/dev.py, docker-compose.yml, docker/dev/django/Dockerfile, docker/dev/django/entrypoint.sh, docker/dev/postgres/Dockerfile, docker/dev/postgres/maintenance/backup, docker/dev/postgres/maintenance/restore, docker/dev/postgres/psql_init.sh
- Réduction de nombre de variables d’environnement pour n'utiliser que celle comprises par `libpq`.
- Remplacement du fichier `envs/dev.env` au profit de variables _inline_.
- :warning: Suppression du fichier `envs/secrets.env` au profit de `.env` (chargé automatiquement par les settings).
- Suppression de l'utilisateur `itou` pour n'utiliser que `postgres` pour la BDD.
- Amélioration de la vitesse de création des images docker.
- On ne promeut plus l'utilisation des variables `*_PORT_ON_DOCKER_HOST` mais elles restent documentées.
- :exclamation: Utilisation de `runserver` plutôt que `runserver_plus` car [les templates ne sont plus rechargé automatiquement](https://github.com/django-extensions/django-extensions/issues/1766).
Problème initial : L'env docker `django` ne fonctionnais plus …
=> [Tech] docker : Quelques simplifications suite à la nouvelle gestion des settings

itou/approvals/tests/tests.py, itou/www/apply/tests/tests_process.py, itou/www/signup/tests/test_job_seeker.py
Example warning:
```
RemovedInDjango50Warning: Passing response to assertFormError() is
deprecated. Use the form object directly:
assertFormError(response.context['form'], 'situation', ...)
```
=> Handle assertFormError signature warnings

itou/templates/dashboard/dashboard.html, itou/templates/siae_evaluations/samples_selection.html, itou/templates/stats/stats.html, itou/www/siae_evaluations_views/tests/tests_institutions_views.py, itou/www/siae_evaluations_views/views.py, itou/www/stats/views.py
Retrait des dates de la campagne de contrôle a posteriori 2021
La campagne 2022 commence le 10 octobre. Évitons la confusion.
L’accès à la page de sélection du échantillon de contrôle requiert maintenant une campagne de contrôle en cours. Cette page n’est accessible que depuis le tableau de bord, et seulement lorsque l’échantillon n’a pas été selectionné. Une fois l’échantillon sélectionné, la page n’est plus accessible que :
1. pour l’utilisateur qui vient de définir l’échantillon (redirection après la soumission du formulaire)
2. directement via l’URL
L’accès à la page sans campagne de contrôle a posteriori n’a pas besoin d’être géré.
Les titres de la page de sélection de l’échantillon ont été mis à jour pour utiliser des /headings/ (`h1`, `h2`, …) au lieu de paragraphes dont le style …
=> Retrait des dates de la campagne de contrôle a posteriori 2021

.github/workflows/build-metabase-final-tables.yml, .github/workflows/imports-asp.yml, .github/workflows/populate-metabase-itou.yml, .github/workflows/review-app-removal.yml
Most of them aren't actually secrets.
Since the secrets in GH are not readable, it's better to have them explicited here.
After this we're going to be able to remove every secret except CLEVER_SECRET & CLEVER_TOKEN.
=> Technique : retirer les utilisations de la plupart des secrets Github.

itou/api/data_inclusion_api/serializers.py, itou/api/data_inclusion_api/tests.py
Exposition via l'api data.inclusion d'un lien vers la page de la structure sur les emplois
```json
{
"id": "44b32551-8c00-4b1a-a833-641a98f3bb4d",
"typologie": "ACI",
"nom": "ACI Librairie Mille Feuilles",
"siret": "21780621500547",
"rna": "",
"presentation_resume": "Chantier …",
"presentation_detail": "Chantier d'insertion professionnelle…",
"site_web": "",
"telephone": "0130561812",
"courriel": "librairie.mille-feuilles@mairie-trappes.fr",
"code_postal": "78190",
"code_insee": "",
"commune": "Trappes",
"adresse": "23 rue Pierre Sémard",
"complement_adresse": "",
"longitude": 2.005141,
"latitude": 48.775355,
"source": "ASP",
"date_maj": "2022-09-20T14:56:50.728907+02:00",
"structure_parente": null,
"lien_source": "https://emplois.inclusion.beta.gouv.fr/siae/3918/card" <---
}
```
Pour …
=> feat(api): add link to structure page
