- itou/templates/dashboard/api_token.html
- itou/templates/dashboard/edit_user_info.html
- itou/templates/dashboard/edit_user_notifications.html
- itou/www/dashboard/views.py
> UX/UI: Ajout d'un bouton de retour à la page d'accès aux APIs [GEN-1964]

- itou/templates/layout/_header_user_dropdown_menu.html
- tests/www/__snapshots__/test_layout.ambr
En doublon  car on peut y accéder via le menu prinicpal (accueil)
> UX/UI: Retirer l’item “tableau de bord” du menu “mon espace”

- itou/utils/templatetags/nav.py
Éviter une redirection, on sait que l’utilisateur est authentifié.
Merci à Xavier pour cette bonne idée : https://github.com/gip-inclusion/les-emplois/pull/4667#issuecomment-2331719591
> UX/UI : Amélioration des performances d’accès au tableau de bord depuis le menu

- itou/www/job_seekers_views/forms.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
Car dans cette page, ce sont des candidats.
> Candidat: correction du paramètre fictif pour le filtre du nom de candidat dans la vue liste

- itou/templates/utils/templatetags/nav_anonymous.html
Sinon, on a du `<a class="is-active"href="/search/employers">Rechercher un emploi inclusif</a>` dans https://emplois.inclusion.beta.gouv.fr/search/employers
> Tech: correction de l'HTML généré dans la barre de navigation en anonyme

- itou/www/companies_views/forms.py
- tests/www/companies_views/test_create_company_views.py
> Employeur: : Modification du message d'erreur sur le SIRET lors de la création d'antenne

- tests/communications/test_models.py
Cf https://github.com/gip-inclusion/les-emplois/actions/runs/10787394093/job/29916000581
```
except e._NO_TRACEBACK as ex:
>           raise ex.with_traceback(None)
E           django.db.utils.IntegrityError: duplicate key value violates unique constraint "communications_announcementcampaign_start_date_key"
E           DETAIL:  Key (start_date)=(2024-02-01) already exists.
```
> tests: correction d'un test instable

- itou/templates/companies/members.html
- itou/templates/companies/show_financial_annexes.html
La section titre `s-title-02` ne doit pas contenir trop de texte pour limiter sa hauteur. Elle sera bientôt "siticky", donc toujours présente à l'écran. il faut donc limiter sa hauteur / son contenu
> UX/UI: Déplacer le texte d'intro dans les 3 onglets “organisation”

- runtime.txt
Trop de patchs, on oublie de mettre à jour.
Avec un peu de chance, on greppera `3.11` au moment de la migration vers Python `3.12`.
> dependabot: Utiliser les versions mineures de Python au lieu des patchs

- itou/templates/dashboard/dashboard.html
- itou/templates/dashboard/includes/employer_job_applications_card.html
- tests/www/dashboard/test_dashboard.py
Ajouter le bouton “Déclarer une embauche” en haut à droite (comme pour les SIAE) et le retirer de la rubrique candidature
> Tableau de bord : déplacer "déclarer une embauche" pour les GEIQ

- itou/templates/companies/job_description_list.html
- itou/templates/companies/members.html
- itou/templates/companies/show_financial_annexes.html
- itou/templates/dashboard/includes/employer_company_card.html
- itou/utils/templatetags/nav.py
Actuellement ça s’appelle “organisation” mais les employeurs n’utilisent pas ce terme
> UX/UI: renommer “organisation” en “structure” pour les employeurs

- itou/openid_connect/inclusion_connect/enums.py
- itou/www/signup/views.py
- tests/www/signup/test_prescriber.py
Cette valeur d'enum n'est pas utile car il n'y a pas de parcours particulier à faire (contrairement à l'activation, l'invitation et map).
On traite un channel "POLE_EMPLOI" comme les autres prescripteurs.
C'est un reliquat des commits suivant
mise en place dans c11e0ec96e1eec5fda69e18dc8b49e5c626caa7b
plus utile depuis d347c391538951e7afd10a3191424d570ced7348
> Connexion: Suppression d'un paramètre inutilisé 

- clevercloud/cron.json
- requirements/dev.txt
- requirements/test.in
- requirements/test.txt
- tests/test_consistency.py
> Vérifier que le fichier `cron.json` est correctement trié

- tests/communications/test_models.py
The first existing_campaign is unused in the test and looks like an oversight.
> Simplifier Announcement test_start_date_conflict_constraint

- itou/employee_record/management/commands/employee_record.py
Codifier et versionner certaines actions non disponible ailleurs que depuis _www_ et qui peuvent nous être utile dans le cadre du support.
Le problème général est : SIAE à besoin de transférer un PASS pour un SIRET différent de l'actuel
On a actuellement 2 cas différents :
1. Une SIAE a changée de SIRET en cours d'année, et a besoin de transférer sur son ancien SIRET pour la période avant son changement, la FS actuelle est utilisée pour le nouveau SIRET donc on ne veux pas y toucher
2. Une SIAE se retrouve découpée en plusieurs structures, et a besoin de transférer sur le nouveau et/ou pour plusieurs SIRET mais une seul candidature existe et elle est sur l'ancien SIRET
L'idée est donc de créer une FS via la commande et de mettre le SIRET désiré afin de la transmettre comme d'habitude. …
> Fiches salarié : Création d'une commande d'utilitaires

- itou/utils/templatetags/nav.py
Ce template tag n’est inclus qu’en mode connecté.
> Simplifier le template tag nav en mode connecté

- itou/static/css/itou.css
- itou/templates/apply/includes/transfer_job_application.html
- itou/templates/apply/process_details_company.html
- itou/templates/layout/base.html
- itou/utils/staticfiles.py
Lorsque je transfère une candidature, la modale de confirmation est grisée et non cliquable, je dois faire un retour navigateur pour avoir de nouveau accès au site.
Déplacer la génération du HTML des modales plus haut dans le DOM, et donc plus haut dans l'arborescence des templates.
@hellodeloo m'a pointé vers le projet `le-marché` où un `{% block modals %}` [existe](https://github.com/gip-inclusion/le-marche/blob/master/lemarche/templates/pages/home.html#L325), tout comme nous avons un `{% block scripts %}`.
Si je ne me trompe pas :
1. on ne peut pas utiliser de `{% block * %}` dans les fichiers …
> UX/UI: dégriser la modale de transfert de candidature

- tests/job_applications/factories.py
- tests/job_applications/test_admin.py
The enum comes from the enums module, not models.
> Corriger l’import de JobApplicationState dans des tests

- itou/employee_record/admin.py
- tests/employee_record/test_admin.py
Quand on est sur l’admin de la fiche salarié, le n° du PASS est affiché mais n’est pas cliquable. 
Si on souhaite de nouveau avoir le visu sur le PASS, on doit faire un retour en arrière.
Or si le n° de PASS sur la FS devient cliquable, cela nous simplifiera la vie.
> Admin: PASS IAE cliquable dans la fiche salarié

- config/settings/base.py
- itou/templates/dashboard/includes/stats.html
- itou/www/dashboard/views.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_utils.py
- tests/www/stats/test_views.py
https://www.notion.so/gip-inclusion/Supprimer-liste-blanche-sur-TB-346-et-330-7f0e8f96415140c1b4fdd5215f8be596
@dejafait Avec le webinaire mardi prochain, plus c'est fusionné tôt mieux c'est, donc si c'est toi qui la tamponne demain (vendredi) tu pourras la mettre en prod dans la foulée :pray: .
> Pilotage : Ouverture des TB 346 et 330 à tout les conseils départementaux

- itou/templates/apply/includes/list_job_applications.html
- itou/templates/apply/list_prescriptions.html
- itou/templates/dashboard/includes/employer_prescription_card.html
- itou/templates/dashboard/includes/prescriber_job_applications_card.html
Demande : 
> Postuler pour un candidat : on arrive sur la homepage intégrée dans le layout connecté.
> Est-ce qu’il y a moyen de mettre direct sur la page de résultat de recherche d’emploi mais sans avoir rentré de ville ? 
Dans la demande, on n'a pas précisé quels boutons changer. Il y en a plusieurs : sur le tableau de bord des employeurs, dans les pages qui listent les candidats et candidatures. 
Par souci d'homogénéité, j'ai tout modifié.
> Tableau de bord : le bouton Postuler pour un candidat envoie directement dans la page des résultats de recherche

- itou/templates/approvals/list.html
- itou/templates/companies/job_description_list.html
- itou/templates/companies/members.html
- itou/templates/companies/show_financial_annexes.html
- itou/templates/dashboard/includes/employer_employees_card.html
- itou/templates/employee_record/list.html
- itou/www/approvals_views/views.py
- itou/www/companies_views/views.py
- itou/www/employee_record_views/views.py
- tests/www/approvals_views/__snapshots__/test_list.ambr
- tests/www/approvals_views/test_list.py
- tests/www/companies_views/__snapshots__/test_job_description_views.ambr
- tests/www/companies_views/test_job_description_views.py
- tests/www/dashboard/test_dashboard.py
- tests/www/employee_record_views/__snapshots__/test_list.ambr
- tests/www/employee_record_views/test_list.py
Tout comme la catégorie structure avec 3 sous sections, on considère maintenant que “Salariés et PASS IAE” et “Fiches salariés ASP” sont des sous sections de “Salariés”, ils doivent donc avoir des onglets
**Avant**
**Apres**
> UX/UI: Passer “Salariés et PASS IAE” et “Fiches salariés ASP” en onglets

- itou/templates/employees/detail.html
- itou/www/employees_views/views.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/employees_views/test_detail.py
https://itou.sentry.io/issues/5837228505/
Dans les faits: l'utilisateur va sur la page de son salarié, annule sa candidature acceptée (et donc son PASS).
Il rafraîchit la page et :boom: .
> Profil salarié: gérer l'absence de PASS IAE

- itou/companies/migrations/0009_remove_company_rdv_insertion_id.py
- itou/companies/migrations/0010_remove_company_rdv_insertion_id_for_real.py
Remplacement de la colonne `rdv_insertion_id` en `rdv_solidarités_id`
PR 3/3 (zero-downtime)
- PR 1/3 : Ajout de la nouvelle colonne, migrations
- PR 2/3 : Suppression de l'ancienne colonne
- **PR 3/3 : Cleanup**
> Simplification des migrations companies relatives au renommage de rdv_insertion_id

- itou/www/apply/views/process_views.py
Actuellement erreur 422 car la catégorie n'est pas spécifiée et que certaines structures participant à l'expérimentation ont plusieurs catégories de motif actives.
Nous ne devions pas rencontrer de structure avec plusieurs catégories à ce stade car actuellement impossible de soumettre la catégorie de manière "stable" (ID, slug).
En attendant le support d'un slug côté API RDV-I, on peut sélectionner la catégorie en la soumettant par son label.
> Permettre à RDV-I d'envoyer une invitation pour les structures ayant plusieurs catégories de motif

- tests/www/apply/test_submit.py
The identifier for a job is the job_description object, not appellations.
> Correction du test test_apply_as_job_seeker_from_job_description

- itou/templates/apply/submit/application/resume.html
- itou/www/apply/forms.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Les données sont déjà validées à l’étape `ApplicationJobsView`, puis stockée en session. Au lieu de jouer au ping-pong avec le client et de re-valider les métiers choisis à l’étape d’envoi du CV, autant lire directement depuis la session.
Comme il y avait deux moyens de choisir les métiers, les tests utilisaient les deux, souvent en contradiction.
Pour éviter une requête inutile qui allait chercher les métiers, les tests se concentrant sur la validité du CV utilisent maintenant une candidature spontanée.
> Retirer le champ SubmitJobApplicationForm.selected_jobs

- itou/static/css/itou.css
Une fois qu'un widget select2 est téléchargé (`.select2-container--bootstrap-5`) la largeur est fixée selon la taille de l'écran :
```html
<span dir="ltr" data-select2-id="3" style="width: 694.667px;" class="select2 select2-container select2-container--bootstrap-5">
```
Le problème arrive quand on change la taille de l'écran, ces composants sont pas réponsive :
Dans ce PR je propose une fixe simple où on ajoute une classe qui enforce le composant ne peut pas manger plus de la page que son parent
> UX/UI : largeur réponsive pour les composants `.select2`

- itou/siae_evaluations/admin.py
- tests/siae_evaluations/test_admin.py
Affichait `State: -`.
L’attribut `state` n’existe pas sur les instances.
Django masque ces erreurs pour afficher un `-`:
https://github.com/django/django/blob/8e68f938f376cf2ca22a7e8ff0bcbe1b7a5832d1/django/contrib/admin/helpers.py#L269-L272
> Admin : Correction de l’affichage de l’état des candidatures contrôlée a posteriori

- itou/templates/dashboard/dashboard.html
- itou/templates/dashboard/dashboard_stats.html
- itou/templates/dashboard/includes/dashboard_title_content.html
- itou/utils/templatetags/nav.py
- itou/www/dashboard/urls.py
- itou/www/dashboard/views.py
- tests/www/dashboard/test_dashboard.py
Besoin initial : [Modifier l’action retour sur les emplois pour revenir à l’onglet stats au lieu de l’onglet vue d’ensemble](https://www.notion.so/gip-inclusion/UX-Modifier-l-action-retour-sur-les-emplois-pour-revenir-l-onglet-stats-au-lieu-de-l-onglet-vue-d-5e7c1d3ba36b4eba992121d135729426?pvs=4)
Cela aurais pu être gérer d'une autre manière (i.e. full frontend) mais j'ai préféré saisir l'occasion au vol pour diverses raisons.
_tl;dr_: La page étant la première sur laquelle les gens arrivent, l'onglet "Statistiques" étant moins vue et utile que l'onglet principal, et avec les divers ajouts anticipés autant découper quand c'est facile.
- Ça complexifiais et rendais la vue plus verbeuse que nécessaire
- C'est pas très lourd mais on commence à ajouter des choses autres que des liens dans …
> Tableau de bord : Déplacer le contenu de l'onglet "Statistique" dans sa propre vue

- itou/www/stats/views.py
Voir [LES-EMPLOIS-PROD-1Z9](https://itou.sentry.io/issues/5842565606/).
> Statistiques : Correction de la page `/stats` pour les prescripteurs sans organisation

- itou/templates/approvals/includes/list_card.html
- itou/www/employees_views/views.py
- tests/www/approvals_views/test_list.py
- tests/www/employees_views/test_detail.py
Suite à #4713 l'accès au Profile salarié se fait via l'identifiant public du compte candidat.
Or certains candidats ont plusieurs PASS et apparaissent plusieurs fois dans la liste mais avec toujours le même lien menant au profil salarié affichant le dernier PASS (depuis #4731) et avec impossibilité de revoir les infos des anciens PASS.
Cette PR corrige ce soucis.
> Profil salarié: redonner l'accès aux anciens PASS IAE

- itou/prescribers/admin.py
- tests/prescribers/tests.py
Je me suis rendu compte que les tests étaient bizarres car les subTests ne font rien de différent (les arguments ne sont pas utilisés par le formulaire).
Je ne suis pas certain de ce qu'on veut faire à la place (vu qu je ne suis pas certain de ce que les SubTests voulaient tester) 
> Admin: Remplacer l’erreur 500 en cas de refus d'habilitation par un message plus explicite

- itou/openid_connect/models.py
- itou/openid_connect/pe_connect/views.py
- itou/templates/django_bootstrap5/messages.html
- itou/templates/layout/base.html
- itou/templates/utils/modal_includes/france_travail_registration_failure.html
- itou/templates/utils/modals.html
- itou/users/models.py
- itou/utils/templatetags/str_filters.py
- tests/openid_connect/pe_connect/tests.py
- tests/users/test_models.py
- tests/www/invitations_views/test_company_accept.py
- tests/www/invitations_views/test_prescriber_organization.py
- tests/www/signup/test_prescriber.py
- tests/www/signup/test_siae.py
Le SSO permet l’existence de plusieurs comptes avec le même email, ce qui fait qu’à chaque connexion depuis un compte ou un autre attaché au même email, on va écraser les données.
> [GEN-1937] Connexion: Empêcher l'écrasement des comptes France Travail (courriels dupliqués)

- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Avant ce commit, on pouvait mettre de mauvaises données dans la session. Ce n’était pas grave, mais pas terrible non plus.
> Valider le métier sélectionné dans apply:start

- tests/companies/test_admin.py
- tests/conftest.py
- tests/job_applications/test_transfer.py
- tests/users/test_admin_views.py
- tests/www/dashboard/test_edit_user_notifications.py
Plus de stabilité, moins de requêtes, moins de surprises.
> tests: Préchauffer le cache de ContentType de manière globale

- .github/workflows/review-app-creation.yml
- scripts/clever-deploy
- scripts/create-fast-machine.sh
La création de recettes jetables est très lente.
> Recettes jetables: utilisation de git

- .editorconfig
- .github/workflows/notify-slack.yml
[[Notifs sur slack] - Mettre en place les notifs de mep C2 pour qu’elles aient la même tête que dans mep c1](https://www.notion.so/gip-inclusion/Notifs-sur-slack-Mettre-en-place-les-notifs-de-mep-C2-pour-qu-elles-aient-la-m-me-t-te-que-dans-m-9b52111e165548929273f848efb3ec3f?pvs=4)
RàF :
> github : Notifier automatiquement le pilotage quand une PR est fusionnée

- itou/eligibility/models/geiq.py
Ne pas réimplémenter ces conditions, avoir une source de vérité.
> Réutiliser GEIQEligibilityDiagnosis.valid_diagnosis_for()

- Makefile
- README.md
Recharger une base de données vide plus rapidement.
Mettre en cache un dump d’une base de données complète créée à partir des fixtures.
Grâce aux dépendances du `Makefile`, la base cachée sera reconstruite si le schéma de base de données ou les fixtures changent.
Performances sur ma machine:
- création de la base, migration et chargement des données: 50s
- `pg_restore` de la base cachée : 15s
```
make resetdb
```
À voir si ça vous intéresse. Les avantages principaux :
- éviter de taper plusieurs commandes pour créer une base de données avec les données fictives
- gagner un peu de temps
Après, le mécanisme est un peu complexe et pas parfait (ex.: oubli de dépendance, ou `mtime` qui change alors que le contenu du fichier de dépendance n’a pas changé de manière significative).
Dans les idées …
> Ajouter une règle resetdb au Makefile

- itou/www/stats/views.py
Sinon l'utilisateur ne peux pas choisir une autre de ses structures directement depuis le filtre Metabase.
Se base sur #4775.
> Statistiques : Correction du filtre des structures pour le TB 440

- itou/templates/layout/_header_user_dropdown_menu.html
- tests/www/__snapshots__/test_layout.ambr
> UX/UI : Étendre la zone cliquable du bouton déconnexion

- itou/asp/admin.py
Avant qu'il y ait un drame car quelqu'un aura édité l'objet.
Comme indiqué dans le commit, `PkSupportRemarkInline` n'est plus utile car la MAJ du référentiel a supprimée les communes créés manuellement et vu que tout est _RO_ bah ça ne va plus trop servir :).
> Admin : Lecture seule pour le référentiel ASP des pays

- itou/templates/layout/_header_user_dropdown_menu.html
- tests/www/__snapshots__/test_layout.ambr
Éviter les maxclicks.
**Pour infos:**
Le `.stretched-link` ajoute un pseudo element ::after à l'élément HTML afin d'agrandir la zone de click/survol. Ce ::after a pour propriété d'être positionné en absolu et de prendre toute la largeur et la hauteur disponible. Pour limiter la zone de click, il faut bloqué la dimension prise par le ::after en donnant une limite  via la propriété de `position:relative` donner a un élément parent. Sinon la dimension de ::after ne s'arrêtera qu'au premier parent possédant un position:relative 
**Avant**
**Apres**
> UX/UI : Fix la zone cliquable du bouton déconnexion

- itou/templates/apply/includes/buttons/accept.html
- itou/templates/apply/process_details_company.html
- tests/www/apply/test_geiq.py
En tant que GEIQ, la modale de confirmation d'embauche d'un candidat sans aide est cachée derrière le backdrop.
On réutilise le block `{% block modals %}` dans `process_details_company.html`
STR :
1. Se connecter en tant que GEIQ
2. Créer une candidature pour le GEIQ
3. Étudier la candidature
4. Cliquer sur Accepter
> UX/UI : réparer la modale de confirmation d'embauche GEIQ sans aide

- itou/templates/layout/base.html
Le script ne fonctionnait que sur la homepage (pb avec `document.body.clientWidth`) et gérait une hauteur pour le mobile inutile
> Corriger la hauteur minimale de l'iframe livestorm

- scripts/clever-deploy
- scripts/create-fast-machine.sh
Éviter les refs ambigües.
```
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:
- Looking for a ref that matches 'master' on the remote side.
- Checking if the <src> being pushed ('refs/remotes/origin/master')
is a ref in "refs/{heads,tags}/". If so we add a corresponding
refs/{heads,tags}/ prefix on the remote side.
Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'refs/remotes/origin/master:refs/heads/master'?
error: failed to push some refs to 'https://push-n3-par-clevercloud-customers.services.clever-cloud.com/app_3b692b2d-6045-4713-a18b-2708cdee4e88.git'
Traceback (most recent …
```
> Réparation du script `create-fast-machine.sh` suite au passage à `clever-deploy`

- itou/templates/stats/stats.html
- itou/www/stats/views.py
https://www.notion.so/gip-inclusion/enqu-te-utilisateur-Ajouter-un-encart-sur-les-TDB-afin-d-annoncer-l-enqu-te-utilisateurs-6d9f60a98d7840ce9cc3d52ee1119cbd?pvs=4
> Pilotage : Ajouter un encart sur les TDB afin d’annoncer l’enquête utilisateurs

- itou/openid_connect/france_connect/views.py
- itou/openid_connect/inclusion_connect/views.py
- itou/openid_connect/models.py
- itou/openid_connect/pe_connect/views.py
- itou/templates/utils/modal_includes/sso_email_conflict_registration_failure.html
- itou/templates/utils/modals.html
- tests/openid_connect/france_connect/tests.py
- tests/openid_connect/inclusion_connect/tests.py
Sur OIDConnect, les nom d’utilisateurs (sub) sont uniques, mais non les e-mails. Les SSOs permettent donc la réutilisation des emails entre comptes, qui est invalide sur notre service. Désormais on a permis la modification de nom d'utilisateur quand il arrive du même SSO avec un autre `sub`. Cela cause des problèmes intransients pour nos utilisateurs, et ce PR remplace ce comportement avec les erreurs explicite sur le login. C'est une étape intermediare, où après on va enforcer qu'un email peut utiliser seulement un SSO.
FranceConnect
InclusionConnect
> Connexion : Empêcher les utilisateurs de se connecter à un autre compte du SSO partageant un courriel existant

- itou/asp/forms.py
- itou/asp/models.py
- itou/templates/apply/includes/profile_infos.html
- itou/templates/apply/submit/create_or_update_job_seeker/step_1.html
- itou/users/forms.py
- itou/users/models.py
- itou/utils/validators.py
- itou/www/apply/forms.py
- itou/www/apply/views/submit_views.py
- itou/www/employee_record_views/forms.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_submit.py
Les prescripteurs et les employeurs peuvent créer les demandeurs d'emploi et leurs candidatures sur les parcours de `apply/.../sender/...` et `apply/.../hire/...`. Deux champs importants sur leur fichier sont la commune et la pays de naissance qui sont avec ce PR inclusent lors de ces parcours.
Ce besoin a impliqué la logique un peu particulière du gestion de `birth_place` et `birth_country`, partagée maintenant entre trois formulaires (`NewEmployeeRecordStep1Form`, `CertifiedCriteriaInfoRequiredForm` et `CreateJobSeekerWithBirthFieldsStep1Form`).
Cette logique gère la création et la modification des profils du candidat sur les formulaires qui peuvent cible le `JobSeekerProfile` en directe ou par le clé sur `User`. J'ai pu encacher cette complexité en `BirthPlaceAndCountryMixin`, afin de …
> Demandeur d’emploi : Ajout lieu de naissance dans le formulaire de création par un tiers [GEN-1944]

- itou/companies/admin.py
Éviter des erreurs humaines et les grains de sable dans la machinerie.
`siret` : Utiliser par l'import IAE comme valeur identifiant
`convention` : Je ne vois pas de raison pour laisser modifier la convention par autre chose que l'import IAE vu que c'est la source de donnée
`auth_email` : Moins critique mais vu que c'est l'email utilisé pour la première inscription c'est pas plus mal de ne pas autoriser sa modification pour rester aligné avec les données du flux
> Admin : Lecture seule pour les champs `siret`, `convention` et `auth_email` quand l'entreprise vient du flux IAE

- tests/utils/test.py
Parfois, le noeud n'a pas d'attribut `origin` et :boom: .
> assertSnapshotQueries: gestion d'une origine manquante

- itou/openid_connect/france_connect/models.py
- itou/openid_connect/inclusion_connect/models.py
- itou/openid_connect/inclusion_connect/views.py
- itou/openid_connect/models.py
- itou/openid_connect/pe_connect/models.py
L'idée est de sortir une partie de la PR ProConnect pour permettre à Calum de l'utliser dans une autre PR où l'on va empêcher FranceConnect et PEConnect de convertir des comptes Django, et de se connecter depuis un compte de l'autre SSO  
> Connexion: Amélioration technique autour de la mise à jour de SSO

- itou/templates/approvals/suspension_update.html
- tests/www/approvals_views/test_suspend.py
Sinon, par défaut le bouton d'annulation renvoie vers le tableau de bord.
> PASS IAE: retour sur la page d'origine lors de l'annulation d'une modification de suspension

- itou/templates/search/includes/prescribers_search_form.html
- itou/templates/search/includes/siaes_search_form.html
- tests/www/dashboard/__snapshots__/test_dashboard.ambr
Pacque des classes responsives n'étaient plus utilisées que sur la home
> UX/UI: l'input de recherche dépasse du viewport en mobile

- itou/users/models.py
- itou/www/apply/forms.py
- itou/www/dashboard/forms.py
- tests/users/factories.py
- tests/www/apply/test_submit.py
- tests/www/dashboard/test_edit_job_seeker_info.py
- tests/www/dashboard/test_edit_user_info.py
Une nouvelle vérification pour être sûr que les données entrées soient cohérentes.
> Candidature : vérifier la cohérence du NIR avec la date de naissance et la civilité

- itou/www/companies_views/forms.py
- tests/www/companies_views/test_edit_company_views.py
Le champ `email` était obligatoire dans le formulaire **d'édition** d'une SIAE, mais pas dans le formulaire **de création**.
On veut harmoniser, et il semble préférable d'avoir un **champ facultatif** : une structure peut ne pas vouloir recevoir d'emails.
Dans pas mal de jobboards, l'entreprise a le choix de ne pas exposer ce champ au public.
> Employeur : le champ `email` est facultatif dans les formulaires d'édition et de création de SIAE

- itou/templates/approvals/suspend.html
- itou/templates/employee_record/add.html
- itou/templates/utils/templatetags/buttons_form.html
- itou/utils/templatetags/buttons_form.py
- tests/utils/__snapshots__/test_templatetags.ambr
- tests/utils/test_templatetags.py
- tests/www/approvals_views/__snapshots__/test_suspend.ambr
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_create.ambr
- tests/www/prescribers_views/__snapshots__/test_edit.ambr
- tests/www/signup/__snapshots__/test_job_seeker.ambr
Pour que le tag fasse ce qu'on pense qu'il fait.
Dans le formulaire de création de suspension, cela permet de conserver ce que l'on avait saisi dans la première étape lorsqu'on clique sur `Retour`.
Dans le formulaire de création de fiche salarié, cela ne semble pas avoir d'impact.
> Tech: correction des formulaires de création de suspension & fiche salarié

- itou/templates/approvals/suspension_delete.html
- itou/templates/approvals/suspension_update_enddate.html
- itou/www/approvals_views/views.py
- tests/www/approvals_views/__snapshots__/test_suspend.ambr
- tests/www/approvals_views/test_suspend.py
Il y avait un mélange des `back_url`/`reset_url`/`secondary_url` qui empêchait l'utilisateur de revenir de là où il venait.
Le mieux est encore de comparer la différence de comportement entre cette recette jetable et la démo.
> PASS IAE: correction des boutons d'annulation/retour dans le processus de suppression d'une suspension

- itou/openid_connect/france_connect/views.py
- itou/openid_connect/inclusion_connect/views.py
- tests/openid_connect/inclusion_connect/tests.py
Extrait de #4080
Voir https://github.com/gip-inclusion/les-emplois/pull/4080#discussion_r1752096446 et https://github.com/gip-inclusion/les-emplois/pull/4080#discussion_r1752128117
> Connexion: Ajout d'un vérification du paramètre `next_url` lors d'une connexion via un SSO

- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Auparavant, les prescripteurs voyaient les diagnostics d’éligibilité établis par les employeurs lors du processus de prescription.
- Si le prescripteur ne mettait pas à jour le diagnostic, le candidat n’obtenait pas de diagnostic d’un prescripteur habilité qui permet aux GEIQ d’obtenir l’aide au poste maximal. C’était néfaste pour le candidat.
- Si le prescripteur mettait à jour le diagnostic, le système effectuait par erreur une mise à jour du diagnostic employeur, au lieu d’établir un diagnostic d’un prescripteur habilité.
1. Se connecter en tant que GEIQ
2. Enregistrer une candidature pour un nouveau candidat
3. Dans le process, établir un diagnostic d’éligibilité
4. Se connecter en tant que prescripteur
5. Effectuer un prescription pour le candidat de l’étape 2.
6. Durant le process, …
> GEIQ : Masquer les diagnostics d’éligibilité employeurs aux prescripteurs [GEN-1975]

- itou/eligibility/models/geiq.py
> Expliquer le tri des GEIQEligibilityDiagnosis avec un commentaire

- itou/templates/apply/includes/accept_section.html
- itou/templates/apply/includes/job_application_accept_form.html
- itou/templates/apply/submit/hire_confirmation.html
- itou/www/apply/views/common.py
La vue est appelée pour les SIAE et les GEIQ. La condition `siae.kind == CompanyKind.GEIQ` est perturbante.
> Renommer la variable siae de la vue _accept en company

- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- tests/www/apply/test_geiq.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/apply/test_submit.py
Clarifier le cycle de vie de `apply_session`.
Correction d’une perte de données dans un cas rarissime (voir message de commit).
> Vérifier l’existence d’une `apply_session` après ApplicationJobsView

- itou/templates/layout/_header.html
- itou/templates/layout/_header_authenticated.html
- itou/utils/staticfiles.py
- tests/www/__snapshots__/test_layout.ambr
Afin que ces deux menus s'ouvrent toujours par le haut
> UX/UI: forcer la position .dropdown-menu sur les menu "mon espace" et "besoin d'aide"

- itou/openid_connect/france_connect/models.py
- itou/openid_connect/inclusion_connect/models.py
- itou/openid_connect/models.py
- itou/openid_connect/pe_connect/models.py
- tests/openid_connect/france_connect/tests.py
- tests/openid_connect/pe_connect/tests.py
Désormais quand l'utilisateur se connecte aux emplois avec un SSO (InclusionConnect, PEConnect, FranceConnect) et le compte n'existe pas mais le courriel est utilisé par un autre SSO, on va montrer en erreur. Précédemment on a laissé l'utilisateur à écraser son compte, et ça a causé des problèmes pour les utilisateurs qui partagent une adresse e-mail.
On permet toujours les utilisateurs à remplacer leur compte Django avec un compte SSO.
Sur un prochain ticket on va remplacer les alertes / modales affichées avec des alertes qui rédirigent vers le connexion. Je les ai laissé dans l'état actuel pour l'instant pour simiplifier cette étape ci.
Extension de https://github.com/gip-inclusion/les-emplois/pull/4810
> Connexion : Empêcher les utilisateurs de remplacer leur SSO une fois ils sont inscrit [GEN-2115]

- config/settings/base.py
- itou/static/js/easymde_config.js
- itou/templates/companies/card.html
- itou/templates/companies/create_siae.html
- itou/templates/companies/edit_job_description_details.html
- itou/templates/companies/edit_siae_description.html
- itou/templates/companies/edit_siae_preview.html
- itou/templates/companies/includes/_job_description_details.html
- itou/templates/prescribers/card.html
- itou/templates/prescribers/edit_organization.html
- itou/utils/urls.py
- itou/utils/widgets.py
- itou/www/companies_views/forms.py
- itou/www/prescribers_views/forms.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- tests/www/companies_views/test_card_views.py
- tests/www/companies_views/test_edit_company_views.py
- tests/www/companies_views/test_job_description_views.py
- tests/www/prescribers_views/test_edit.py
:warning:  Nouvelle PR suite au retour métier (j'avais fusionné trop vite 😵‍💫). Les ajouts/modifications de code, par rapport à la PR initiale relue, sont indiqués ci-après.
PR initiale : https://github.com/gip-inclusion/les-emplois/pull/4816
PR de revert : https://github.com/gip-inclusion/les-emplois/pull/4833
Inciter les utilisateurs à renseigner plus d’infos dans leurs descriptions de fiche structure et fiche de poste.
On a observé de très bons résultats sur le marché depuis qu’ils l’ont fait.
- utiliser `django-easymde`, qui importe `EasyMDE` (js et css) dans les formulaires, via `{{ form.media }}`.
Malheureusement la version actuelle du `django-easymde` ne permet pas de configuration "dynamique" (mentionner une fonction JS, comme `toggleBold` par exemple), donc on doit configurer …
> Employeur : ajouter un éditeur de texte markdown sur les grands champs de saisie

- itou/templates/approvals/declare_prolongation.html
- itou/templates/approvals/suspend.html
- itou/templates/approvals/suspension_action_choice.html
- itou/templates/approvals/suspension_delete.html
- itou/templates/approvals/suspension_update.html
- itou/templates/approvals/suspension_update_enddate.html
- itou/www/approvals_views/views.py
- tests/www/approvals_views/__snapshots__/test_suspend.ambr
> PASS IAE: utilisation du nouvel encart de PASS dans les formulaires de suspension & prolongation [GEN-2121]

- itou/users/models.py
On a a priori envie que les anciennes valeurs soient mises à jour quand on sauve le modèle.
Typiquement quand on créer le job seeker profile, on fait un create en premier, puis on remplie les valeurs de la même instance. donc on ne détecte pas qu'elles changent.
C'est nécessaire pour que le test `test_apply_as_prescriber_with_pending_authorization` fonctionne dans #4869.
La question que je me pose est si on copie tout `self.__dict__` on si on regarde juste les 2 champs qui nous intéressent en vérifiant juste qu'ils sont présents pour éviter des requêtes supplémentaires en cas de champs "deferred": 
```
def set_old_values(self):
watched_fields = ["nir", "birthdate"] 
self._old_values = {
field: value 
for field, value in self.__dict__
if field in watched_fields
}
```
> _Décrivez en …
> Amélioration des méthodes `has_data_changed()`

- clevercloud/crons/populate_metabase_emplois.sh
- itou/metabase/db.py
- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/metabase/tables/utils.py
Car un code postal n'est pas unique et peux donc être assigné à plusieurs ville, on se retrouve donc avec des noms de ville fausses dans les tableaux de bord.
PR associée : https://github.com/gip-inclusion/pilotage-airflow/pull/356
> Pilotage : Utilisation du code INSEE enregistré plutôt que de l'inférer depuis le code postal

- itou/job_applications/models.py
- itou/templates/apply/includes/list_card_body_company.html
- itou/www/apply/views/list_views.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Pour économiser notre base de données.
> Performance: utilisation d'une annotation pour éviter des requêtes en boucle

- itou/approvals/models.py
- tests/approvals/tests.py
> PASS IAE: suppression lors de l'annulation de la dernière candidature acceptée [GEN-2032]

- itou/users/models.py
- tests/www/dashboard/test_edit_user_info.py
Quand le mois 'est pas une valeur entre 1 et 12, on ne peut pas comparer avec le mois de naissance renseigné.
> Candidature: Amélioration de la validation du NIR

- itou/www/apply/forms.py
- tests/www/apply/test_forms.py
Suite à une remontée utilisateur : https://plateforme-inclusion.zendesk.com/agent/tickets/20239
> Candidature: Correction de la sélection de commune quand le code insee a changé depuis la naissance du candidat

- itou/approvals/admin.py
- itou/employee_record/admin.py
- itou/users/admin.py
Pour éviter un `SELECT COUNT()` pas forcément utile.
> Admin: suppression du total de tous les objets sur la page de liste de certains objets

- itou/templates/apply/includes/appointments.html
- itou/templates/apply/includes/invitation_requests.html
- itou/templates/apply/list_of_available_exports.html
- itou/templates/approvals/prolongation_requests/list.html
- itou/templates/companies/job_description_list.html
- itou/templates/companies/show_financial_annexes.html
- itou/templates/dashboard/api_token.html
- itou/templates/geiq/employee_contract_list.html
- itou/templates/geiq/employee_exit_list.html
- itou/templates/geiq/employee_job_application_list.html
- itou/templates/geiq/employee_personal_information_list.html
- itou/templates/geiq/employee_support_list.html
- itou/templates/geiq/geiq_list.html
- itou/templates/includes/members.html
- itou/templates/invitations_views/includes/pending_invitations.html
- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/prescribers/list_accredited_organizations.html
- itou/templates/siae_evaluations/default_calendar_html.html
- itou/templates/siae_evaluations/sanctions_helper.html
- itou/templates/static/legal/privacy.html
- itou/templates/status/index.html
- tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/approvals_views/test_prolongation_requests.py
- tests/www/geiq_views/__snapshots__/tests.ambr
Évolutions de l'ui et harmonisation
> UX/UI: Uniformisation des tableaux

- itou/employee_record/admin.py
- tests/employee_record/test_admin.py
e8914fbf28a608f14ad09cffd4b239f911cdda06 et parce que Django fait son boulot correctement :).
Mais le support à parfois besoin de supprimer une FS pour débloquer une situation donc on l'autorise explicitement.
Normalement les tests sont suffisants
> Admin - Fiches salarié : Corriger la supression

- config/urls.py
- itou/communications/__init__.py
- itou/templates/account/email/email_jobseeker_created_by_third_party_body.txt
- itou/templates/account/email/email_jobseeker_created_by_third_party_subject.txt
- itou/templates/account/password_reset_from_key.html
- itou/users/models.py
- itou/users/notifications.py
- itou/www/apply/views/submit_views.py
- itou/www/signup/views.py
- tests/users/__snapshots__/test_models.ambr
- tests/users/test_models.py
- tests/www/signup/__snapshots__/test_password.ambr
- tests/www/signup/test_password.py
Quand un candidat est créé par un tier, on devrait lui notifier avec un lien qui lui permet définir son mot de passe
> Inscription : Parcours initialisation de mot de passe pour les candidats créés par un tiers [GEN-235]

- itou/siae_evaluations/admin.py
- tests/siae_evaluations/test_admin.py
Pour accéder plus facilement aux informations.
> Contrôle a posteriori: amélioration de l'admin pour afficher l'état d'une auto-prescription au sein d'une entreprise contrôlée

- itou/approvals/admin.py
- tests/approvals/test_admin.py
Localement, la recherche d'un PASS par numéro passe de 5 secondes à 30 ms.
> admin: amélioration de la recherche de PASS IAE

- itou/approvals/admin.py
Si le terme de recherche est un nombre de 12 chiffres ou moins, la recherche ne se fera plus que sur le numéro du PASS et non plus sur le NIR du candidat pour un gain de performance substantiel: 45 ms vs 450 ms en local.
> Admin: amélioration de la recherche des PASS IAE par numéro

- itou/utils/staticfiles.py
Après rechargement des résultats par activation des filtres/statuts htmx, le js des boutons "copy to clipboard" ne fonctionnait plus.
Maj du thème avec prise en compte de l'event [htmx:load](https://github.com/gip-inclusion/itou-theme/blob/main/src/javascripts/app.js#L41-L45)
> Stabilité:  Correction du fonctionnement des "copy to clipboard" apres htmx:load

- itou/www/apply/forms.py
- tests/www/apply/test_list_prescriptions.py
L'affichage utilisé partout est `Prénom NOM`.
> Candidature: uniformisation de l'affichage des noms de candidat et d'utilisateur dans les filtres de recherche

- itou/eligibility/migrations/0001_initial.py
- itou/eligibility/models/common.py
- itou/eligibility/models/geiq.py
- itou/eligibility/models/iae.py
- itou/templates/apply/includes/certification_info_box.html
- itou/templates/apply/includes/eligibility_diagnosis.html
- itou/templates/apply/includes/geiq/geiq_diagnosis_details.html
- itou/templates/apply/includes/selected_administrative_criteria_display.html
- itou/templates/apply/process_details.html
- itou/templates/apply/process_details_company.html
- itou/templates/apply/submit/hire_confirmation.html
- itou/templates/employees/detail.html
- itou/templates/job_seekers_views/details.html
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/employees_views/views.py
- itou/www/job_seekers_views/views.py
- tests/eligibility/factories.py
- tests/eligibility/test_iae.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/__snapshots__/test_templates.ambr
- tests/www/apply/test_templates.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/siae_evaluations_views/test_siaes_views.py
:warning:  Je recommande une relecture commit par commit.
En tant qu'employeur (SIAE ou GEIQ) ayant embauché un candidat pour lequel j'ai réalisé moi-même le diagnostic d’éligibilité, je souhaite voir les critères qui ont été certifiés par l'API Particulier dans la page du diagnostic.
- Réorganisation du gabarit qui affiche les critères.
- Calcul de la validité de la certification dans une Queryset pour qu'il soit réutilisable ailleurs (dans le contrôle a posteriori par exemple).
En tant qu'employeur (SIAE ou GEIQ), réaliser une auto-prescription pour un candidat connu de l'API Particulier avec le critère BRSA.
Dans la page de candidature, un macaron « …
> Candidature : API Particulier -> interface

- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Les prescripteurs voient les diagnostics d’éligibilité établis par les SIAE pour leurs auto-prescriptions. Ceci conduit les prescripteurs à considérer que le candidat bénéficie déjà d’un diagnostic d’éligibilité et à ne pas le refaire. Au final, les candidats sont mis en difficulté, car un diagnostic établi par un prescripteur habilité est valide pour toutes les SIAE, alors que celui établi par une SIAE n’est valide que pour cet employeur.
1. Se connecter en tant que SIAE (EI)
2. Déclarer une candidature
3. Créer un compte candidat (e.g. NIR 111111111111120)
4. Étudier la candidature
5. Accepter la candidature
6. Établir un diagnostic d’éligibilité
7. Arrêter le parcours à l’étape de détail du contrat
8. Se connecter en tant que prescripteur habilité
9. Faire une candidature pour le …
> Prescripteur : Ignorer les diagnostics d’éligibilité des auto-prescriptions [GEN-1657]

- itou/job_applications/models.py
- itou/templates/dashboard/includes/job_seeker_approval_card.html
- itou/users/models.py
- tests/users/test_models.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
Sinon, même avec un PASS IAE valide, un candidat voyait le message ["Un prescripteur habilité a réalisé un diagnostic d'éligibilité. **Vous pouvez commencer un nouveau parcours.**"](https://github.com/gip-inclusion/les-emplois/blob/61131e5e907aab7632effc294ff2e89fcf85a139/itou/templates/dashboard/includes/job_seeker_approval_card.html#L21) s'il avait un précédent agrément PE dans le délai de carence.
> Tableau de bord: correction du message lié au délai de carence pour l'encart PASS IAE du candidat

- itou/templates/apply/submit/application/resume.html
- itou/templates/apply/submit_step_check_job_seeker_nir.html
- itou/templates/apply/submit_step_job_seeker.html
- itou/templates/apply/submit_step_job_seeker_check_info.html
- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Quand on rentre dans le parcours “postuler” et qu’on fait annuler, on revient sur l’accueil, on s’attend à revenir sur la fiche de poste sur laquelle on était (à priori ce fonctionnement s’applique partout → lorsqu’on annule on revient à la racine du parcours.
> Candidature : le bouton Annuler renvoie vers la fiche de poste ou l'entreprise

- .github/workflows/notify-slack.yml
La question c'était posée lors la PR initiale (https://github.com/gip-inclusion/les-emplois/pull/4776), à l'usage cela semble une bonne idée afin de limiter le bruit coté C1.
cc @calummackervoy
> github: Possiblité de notifier seulement le pilotage

- CHANGELOG.md
- itou/approvals/admin.py
- itou/templates/approvals/list.html
- itou/templates/dashboard/includes/employer_employees_card.html
- itou/templates/employee_record/list.html
- itou/utils/templatetags/nav.py
- tests/www/__snapshots__/test_layout.ambr
- tests/www/dashboard/test_dashboard.py
Dans "fiches salarié", "salarié" ne s'accorde pas au pluriel.
Souci remonté par Sandrine en direct.
Je n'ai volontairement pas touché aux occurrences dans le changelog.
> Mise à jour du wording "Fiches salarié"

- .github/workflows/notify-slack.yml
Erreur passée inaperçue : https://github.com/gip-inclusion/les-emplois/actions/runs/11435968045/workflow
> github: Possiblité de notifier seulement le pilotage (pour de vrai cette fois)

- tests/eligibility/test_iae.py
Seuls les diags employeurs peuvent être certifiés, voir `AbstractEligibilityDiagnosisModel.criteria_can_be_certified`.
> Corriger les diags des tests/eligibility/test_iae

- itou/templates/includes/gip_address.html
- itou/templates/static/accessibility.html
- itou/templates/static/legal/notice.html
- itou/templates/static/legal/privacy.html
L'ancienne adresse est affichée sur le site sur quelques pages, et il y a besoin de la mettre à jour
> UX/UI: Fix outdated date for the GIP

- itou/employee_record/serializers.py
- tests/employee_record/test_serializers.py
L'ASP n'accepte que 30 caractères au maximum.
Cf. https://itou-inclusion.slack.com/archives/C01181Y04LT/p1729762979362779
- Pas touché au sérialiseur de l'API, uniquement celui destiné au fichier déposé en sftp
> Limitation du prénom à 30 caractères dans le sérialiseur à destination de l'ASP

- itou/eligibility/models/common.py
- tests/eligibility/test_iae.py
- tests/www/apply/test_templates.py
Utilisé uniquement dans les tests, pas par du code de production. L’alternative est très simple.
> Retirer l’argument save de SelectedAdministrativeCriteria.certify

- itou/templates/apply/includes/appointments.html
- tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
Depuis #4861 le contenu de la modale est aligné à droite :
Ajout d'un `text-start` sur la modale spécifiquement.
@hellodeloo je te laisserai voir si tu souhaites reprendre davantage la structure (RDVI est configuré et utilisable en démo, tu peux me contacter pour setup en dev ou en recette jetable)
> RDVI: Réalignement du contenu de la modale à gauche

- scripts/clever-deploy
`/bin/env` n'est pas présent de partout, `/usr/bin/env` est plus courant
> Mise à jour de clever-deploy

- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/dashboard/views.py
- itou/www/stats/urls.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_views.py
https://www.notion.so/gip-inclusion/TB-440-TB-ETP-SIAE-Publier-le-TB-en-Occitanie-et-en-Bretagne-pour-les-SIAE-les-DDETS-les-DREETS-58c28a4ede4645c9ab52970cbf5b52e3
RàF :
> Pilotage : Publier le TB 440/485 en Occitanie et en Bretagne pour les SIAE, les DDETS, les DREETS, les CD, et la DGEFP

- README.md
- config/settings/dev.py
Si un développeur fait tourner son local dev sur une machine A (ex : un laptop) et veut y accéder depuis une machine B (ex : une tablette), il ne peut jusqu'ici pas le faire proprement (nécessité de modifier `dev.py` qui est versionné) et il manque la documentation de comment y parvenir.
> Technique : Simplification de l'accès au serveur de développement local depuis d'autres appareils

- itou/eligibility/enums.py
- itou/eligibility/models/common.py
- tests/eligibility/test_iae.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
Faciliter la gestion des dépendances circulaires.
> Déplacer CAN_BE_CERTIFIED_KINDS vers AdministrativeCriteriaKind

- itou/users/admin.py
- tests/users/test_admin_views.py
Découvert grâce au mood support
> Admin: Permettre de libérer des comptes ProConnect pour bascule Employer <-> Prescripteur

- itou/templates/companies/job_description_card.html
- tests/www/companies_views/test_job_description_views.py
Bouton redondant avec le bouton "< Retour à la liste" présent dans le .prevstep
> UX/UI: Retirer le bouton “Retour vers la liste des postes”

- itou/openid_connect/inclusion_connect/views.py
- tests/openid_connect/inclusion_connect/tests.py
Même si les liens ne sont pas accessible, il ne faut pas qu'un marque page enregistré par un utilisateur fonctionne
-> https://itou.sentry.io/issues/5647707850/?project=6164438&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=8
Il y a encore des utilisateurs qui finissent dessus
> Connexion: Bloquer l'accès à la connexion Inclusion Connect quand ProConnect est activé

- itou/static/css/itou.css
Depuis l'harmonisation UI des tableaux avec alignement à droite de la cellule contenant les boutons d'action. Les modales contenues dans ces cellules héritent des styles de la cellule et d'un parent plus ou moins direct.
Définition des règles css pour réinitialiser les alignements et taille de polices
**Bonus:** Suppression de classes inutiles ou plus utilisées
> UX/UI: Corriger l'alignement du texte dans les modales imbriquées

- itou/templates/apply/submit_step_check_job_seeker_nir.html
- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
Corriger un problème empêchant la soumission du NIR et requérant une nouvelle soumission de l’information.
Voir le message de commit pour les détails.
1. Commencer un parcours de candidature
2. Saisir un NIR invalide
3. Saisir un NIR valide et appuyer sur <kbd>Entrée</kbd> lorsque le champ NIR est focus pour soumettre le formulaire.
Avant : Le NIR n’était pas enregistré
Après : Le NIR est enregistré
> Candidature : Remplacer le bouton pour passer la recherche de NIR par un <a>

- itou/openid_connect/models.py
- tests/openid_connect/pro_connect/tests.py
J'ai l'impression qu'un utilisateur n'arrive pas à se connecter alors que son email est déjà lié à un compte ProConnect.
Je voudrais donc pouvoir vérifier si on ne tombe pas dans ce cas de figure là.
> Connexion: AJout de remontée d'erreur en cas de problème de connexion avec ProConnect

- itou/siae_evaluations/migrations/0003_delete_2021_test_campaigns.py
Ces campagnes étaient un test, nous ne souhaitons pas qu’elles soient présentes dans l’historique.
> Retirer les campagnes de contrôle a posteriori de 2021 [GEN-2210]

- itou/templates/signup/job_seeker_nir.html
- itou/www/signup/views.py
- tests/www/signup/test_job_seeker.py
Corriger un problème empêchant la soumission du NIR et requérant une nouvelle soumission de l’information.
Voir le message de commit pour les détails.
1. Commencer un parcours d’inscription candidat
2. Choisir un critère
2. Saisir un NIR invalide
3. Saisir un NIR valide et appuyer sur <kbd>Entrée</kbd> lorsque le champ NIR est focus pour soumettre le formulaire.
Avant : Le NIR n’était pas enregistré
Après : Le NIR est enregistré
> Inscription : Remplacer le bouton pour passer la recherche de NIR par un <a>

- itou/templates/apply/submit_base_two_columns.html
- tests/gps/test_create_beneficiary.py
Éviter d’induire les utilisateurs en erreur.
Empiler des hacks 🙈. Cacher l’entreprise destinataire quand `is_gps`, en attendant d’avoir un module de création de compte candidat par un tiers.
> GPS : Cacher les informations de l’entreprise fictive France Travail lors de la création d’un bénéficiaire [GEN-1925]

- itou/eligibility/models/common.py
- itou/eligibility/tasks.py
- itou/utils/apis/api_particulier.py
- itou/utils/mocks/api_particulier.py
- tests/eligibility/test_iae.py
- tests/eligibility/test_tasks.py
- tests/utils/apis/test_api_particulier.py
- tests/www/apply/test_templates.py
Être un bon citoyen, éviter de tabasser l’API des copains.
Éviter de faire attendre des workers web, car on peut vite saturer notre bande passante (DoS). Par exemple, si l’API se met à répondre avec des 500, chaque worker qui essaye de certifier un critère sera bloqué pour 3 * 2 = 6s, à attendre et réessayer. En augmentant le nombre de critères certifiés, on peut assez vite faire tomber le service, où tous les workers sont en train de `time.sleep(2)` (les fainéants !).
Suivre les [indications de l’API quant à la fréquence des appels](https://particulier.api.gouv.fr/developpeurs/#respecter-la-volum%C3%A9trie).
Ne faire que le premier essai de certification en synchrone. En cas d’échec, démarrer une tâche asynchrone qui effectuera la vérification.
> API particulier : Respecter la fréquence d’appels et les workers web

- itou/templates/apply/submit_step_pending_authorization.html
- itou/templates/dashboard/includes/dashboard_title_content.html
- itou/templates/job_seekers_views/step_check_job_seeker_nir.html
- itou/www/apply/forms.py
- itou/www/apply/urls.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/forms.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_forms.py
- tests/www/apply/test_submit.py
- tests/www/dashboard/test_dashboard.py
- tests/www/job_seekers_views/test_forms.py
Dans cette PR, on déplace les vues, formulaires et URLs relatives à la vérification du NIR :
- vues, formulaires : déplacés
- URLs : copiés, pour ne pas casser les parcours en cours en production. Les anciennes seront supprimées dans un second temps.
Les autres étapes : https://www.notion.so/plateforme-inclusion/Extraire-le-parcours-de-cr-ation-de-compte …
> Déplacer les vues, formulaires et URLs de vérification du NIR à `job_seekers_views`

- itou/www/apply/forms.py
- itou/www/apply/urls.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/forms.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
Dans cette PR, on déplace les vues, formulaires et URLs relatives à la recherche de candidat par adresse email :
- formulaires et vues : déplacés
- URLs : copiés, pour ne pas casser les parcours en cours en production. Les anciennes seront supprimées dans un second temps.
Les autres étapes : https://www.notion.so/plateforme-inclusion/Extraire-le-parcours …
> Déplacer les vues, formulaires et URLs de recherche par email à `job_seekers_views`

- tests/utils/test.py
Cela aurait attrapé: https://github.com/gip-inclusion/les-emplois/pull/4953/files et ça ne coûte pas bien cher.
> tests: détection d'erreur de rendu dans les templates Django

- itou/templates/apply/includes/job_application_answers.html
- itou/templates/apply/list_of_available_exports.html
- itou/templates/approvals/includes/job_description_list.html
- itou/templates/approvals/suspend.html
- itou/templates/companies/includes/_company_info.html
- itou/templates/dashboard/edit_user_notifications.html
- itou/templates/employee_record/includes/create_step_3.html
- itou/templates/includes/demo_accounts.html
- itou/templates/prescribers/list_accredited_organizations.html
- itou/templates/siae_evaluations/evaluated_job_application.html
- itou/templates/siae_evaluations/includes/list_item.html
- itou/templates/users/details.html
- itou/templates/welcoming_tour/employer.html
- itou/templates/welcoming_tour/job_seeker.html
- itou/templates/welcoming_tour/prescriber.html
- itou/utils/templatetags/theme_inclusion.py
- tests/gps/__snapshots__/test_views.ambr
- tests/utils/__snapshots__/test_templatetags.ambr
- tests/utils/test_templatetags.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_templates.py
- tests/www/geiq_views/__snapshots__/tests.ambr
Amélioration niveau accessibilité et vérification du markup
> UX/UI: Remplacer role=button par des <button>

- itou/templates/announcements/news.html
- itou/www/announcements/views.py
- tests/www/announcements/__snapshots__/test_views.ambr
- tests/www/announcements/test_views.py
Maintenant que sur production il y a des nouveautés pour tout type d'utilisateur, on va supprimer la page ancienne des nouveautés du site.
Supprimer toute campagne en local par le site admin ou avec le shell :
```
python manage.py shell_plus
>>> AnnouncementCampaign.objects.all().delete()
```
Visitez la page nouveautés (http://localhost:8000/announcements/news/)
Pour tester la pagination, on peut créer des campagnes d'annonce rapidement avec:
```python
AnnouncementCampaignFactory.create_batch(26, with_items_for_every_user_kind=True)
```
> UX/UI: Suppression de la redirection de repli sur page nouveautés

- itou/www/apply/forms.py
- itou/www/apply/urls.py
- itou/www/apply/views/common.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/forms.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/welcoming_tour/tests.py
Dans cette PR, on déplace les vues, formulaires et URLs relatives à la vérification des informations (en fin de formulaire) :
- vues, formulaires : déplacés
- URLs : copiés, pour ne pas casser les parcours en cours en production. Les anciennes seront supprimées dans un second temps.
Les autres étapes : …
> Déplacer les vues, formulaires et URLs de vérification des infos à `job_seekers_views`

- itou/templates/companies/job_description_card.html
- tests/www/companies_views/__snapshots__/test_card_views.ambr
Parcqu'il était tout seul dans une barre d'action prévue pour plusieurs boutons et que nous avons une mise en page prévue pour un seul bouton d'action
**Avant**
**Apres**
> UX/UI: Passer le bouton “Modifier” de la fiche de poste à droite

- CHANGELOG_breaking_changes.md
Communiquer les changements aux collègues.
> Ajouter Python 3.12 au CHANGELOG_breaking_changes.md

- tests/www/companies_views/test_card_views.py
The first is set to 42. If the database sequence was at 41, the factory
will use the next available PK (42), which causes:
```
E           django.db.utils.IntegrityError: duplicate key value violates unique constraint "siaes_siaejobdescription_pkey"
E           DETAIL:  Key (id)=(42) already exists.
```
> Robustesse de TestJobDescriptionCardView::test_card_tally_url_with_user

- itou/templates/dashboard/dashboard.html
- itou/templates/dashboard/includes/staff_stats_card.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_utils.py
- tests/www/stats/test_views.py
Ce fonctionnalité permet les membres de l'équipe des emplois d'accéder aux stats indicateurs clés de la service
> Statistiques: Indicateurs à suivre accessible aux membres de l'équipe des emplois [GEN-2190]

- itou/static/js/sliding_tabs.js
- itou/templates/approvals/list.html
- itou/templates/companies/job_description_list.html
- itou/templates/companies/members.html
- itou/templates/companies/show_financial_annexes.html
- itou/templates/employee_record/list.html
Les onglets `data-it-sliding-tabs="true"` n’est pas réinterprété en "sliding-tabs" après un rechargement partiel htmxx
> UX/UI: Problème de rechargement des sliding-tabs apres reload htmx

- itou/www/apply/urls.py
Dans des PRs précédentes on avait **copié** des URLs de `apply` à `job_seekers_views`, pour ne pas casser les candidatures en cours en production.
On peut à présent supprimer ces URLs.
Les autres étapes : https://www.notion.so/plateforme-inclusion/Extraire-le-parcours-de-cr-ation-de-compte-candidat-130e8fa5c35b80b9947cea2573cf90e7?pvs=4#130e8fa5c35b800b9 …
> Supprimer les URLs de `apply` qui ont été déplacées à `job_seekers_views`

- itou/openid_connect/inclusion_connect/views.py
- itou/openid_connect/pro_connect/views.py
- itou/www/invitations_views/helpers.py
- itou/www/invitations_views/views.py
- tests/invitations/factories.py
- tests/invitations/tests.py
- tests/www/invitations_views/test_company_accept.py
- tests/www/invitations_views/test_helpers.py
- tests/www/invitations_views/test_prescriber_organization.py
Cela permet d'être sur que les prescripteurs et employeurs utilisant ProConnect et Inclusion Connect soient correctement associés à leur structures.
> Invitations: utiliser automatiquement toutes les invitations valides disponibles à la connexion [GEN-2221]

- itou/companies/admin.py
- itou/companies/admin_forms.py
- itou/companies/management/commands/move_company_data.py
- itou/companies/transfer.py
- itou/templates/admin/companies/change_company_form.html
- itou/templates/admin/companies/transfer_company.html
- itou/users/admin.py
- itou/users/admin_forms.py
- itou/utils/admin.py
- tests/companies/test_admin.py
- tests/companies/test_management_commands.py
Éviter de passer par supportix et avoir plus de logs concernant les transferts.
> Admin: ajout d'un bouton pour transférer des données entre entreprises [GEN-1527]

- tests/test_consistency.py
Sinon, le test plante sous macOS, cf https://itou-inclusion.slack.com/archives/C0412CTV63D/p1731663000643109
> tests: ignorer les fichier `.DS_Store` dans le test `test_unused_templates`

- itou/templates/gps/includes/memberships_results.html
- itou/templates/gps/my_groups.html
- itou/templates/users/details.html
- tests/gps/__snapshots__/test_views.ambr
La proximité du bouton "Ajouter un bénéficiaire" avec le filtre de la liste créait de la confusion pour les utilisateurs (cf. [retours au support](https://plateforme-inclusion.zendesk.com/agent/tickets/21700)).
Passer les principaux boutons d'action dans le header (sur le modèle, par exemple, de [la liste des candidatures reçues](https://github.com/gip-inclusion/les-emplois/blob/18a7a0f9e600fa1c8b2bb7656b4b030ce7bf1e2f/itou/templates/apply/list_for_siae.html#L4)).
On en profite pour résoudre des bugs visuels sur les petites tailles d'écran.
> GPS: Mise en page de la liste des bénéficiaires

- itou/metabase/management/commands/populate_metabase_fluxiae.py
https://www.notion.so/gip-inclusion/Cr-ation-pour-les-emploi-Rajouter-l-export-de-la-table-march-financier-dans-le-code-populate_flux_-13d5f321b604807caa2ad07bbcabb800?pvs=4
> Pilotage : Rajouter l'export de la table marché financier du flux IAE

- itou/templates/dashboard/includes/gps_card.html
- itou/templates/gps/my_groups.html
- itou/www/autocomplete/views.py
- itou/www/dashboard/views.py
- itou/www/gps/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
- tests/www/dashboard/__snapshots__/test_dashboard.ambr
- tests/www/dashboard/test_dashboard.py
> GPS: Permettre aux orienteurs d’accéder à GPS sur leur dashboard [GEN-2226]

- itou/companies/management/commands/import_ea_eatt.py
L'import _hebdomadaire_ est le seul moyen pour les EA/EATT d'être créées, on veux donc être prévenu si jamais il venais à ne pas être correctement exécuté, afin d'éviter de possible tickets au support ou des demandes SupportiX.
> EA/EATT : Ajout d'un moniteur sentry pour l'import

- itou/www/approvals_views/views.py
- tests/www/approvals_views/test_detail.py
Sinon, ça :boom: avec `'>' not supported between instances of 'datetime.date' and 'NoneType'`
Cf https://itou.sentry.io/issues/6011765619/?project=6164438 & https://itou-inclusion.slack.com/archives/C01181Y04LT/p1731954611260899 & 
> PASS IAE: correction de la vue de détail pour d'anciens PASS liés à des candidatures acceptées sans date de début d'embauche

- itou/files/management/commands/configure_bucket.py
- tests/conftest.py
- tests/files/tests.py
Éviter une suppression accidentelle d’un fichier sur le stockage.
Les fichiers supprimés par l’application sont inaccessibles, puis réellement supprimés après 90 jours.
En utilisant les _delete markers_ de S3.
> Versionner les fichiers du stockage S3

- itou/templates/apply/includes/job_application_sender_info.html
En passant l'historique de la candidature en onglet, les utilisateurs n'ont plus rapidement l'info de la date d'émission de la candidature sur l'onglet d'infos générales
> UX/UI: Ajouter la date d'émission de la candidature dans l'onglet d'infos générales

- itou/approvals/models.py
- tests/approvals/tests.py
- tests/www/approvals_views/__snapshots__/test_approval_box.ambr
- tests/www/approvals_views/__snapshots__/test_detail.ambr
Nouvelle remontée en mood support ([voir ici pour une précédente](https://itou-inclusion.slack.com/archives/C0412CTV63D/p1729695821094099)).
Le cas d'école est l'affichage de "Date de fin prévisionnelle" (`approvals/includes/box.html`) pour une première embauche dans le futur, on se retrouve à afficher une date de fin prévisionnelle inférieure à la date de fin enregistrée et qui ne colle donc pas avec la date de début. Cette date de fin prévisionnelle se retrouve à évoluer chaque jour entre maintenant et la date de début, donc quand le support traite le ticket il y a souvent plus rien à voir ou faire.
De mémoire ceci avait été fait historiquement pour afficher à l'utilisateur la date de fin prévisionnelle si il embauchait maintenant, sauf que depuis ce template est utilisé partout et la …
> PASS IAE : Limiter la date de fin prévisionnelle aux dates enregistrées

- itou/templates/apply/process_details_company.html
`upcoming_appointments` ne semble jamais défini sur une candidature et la règle d'affichage de l'onglet:
```
{% if job_application.upcoming_participations_count or request.current_organization.rdv_solidarites_id %}
<div class="tab-pane fade" id="appointments" role="tabpanel" aria-labelledby="appointments-tab">
<div class="s-section__row  row">
<div class="col-12 col-lg-8 order-2 order-lg-1">
{# Appointments ------------------------------------------------- #}
{% include "apply/includes/appointments.html" with job_application=job_application %}
</div>
</div>
</div>
{% endif %}
```
ayant un `aria-labelledby` pointant vers ce lien se base sur `job_application.upcoming_participations_count` donc j'imagine que c'est ce qu'on souhaite.
Trouvé via #5055
> _Décrivez en quelques mots la solution …
> Candidature: correction des règles d'affichage de l'onglet pour voir les rendez-vous d'une candidature

- .github/workflows/notify-slack.yml
Car c'est cassé depuis #5104.
Erreur : https://github.com/gip-inclusion/les-emplois/actions/runs/11916918556/job/33213313523
> github : Correction des notifications de mise en prod

- itou/templates/apply/includes/job_application_info.html
- tests/www/apply/test_process.py
> Candidature: ajout d'un lien vers la fiche structure pour les utilisateurs n'appartenant pas à la structure [GEN-2234]

- itou/templates/apply/includes/list_card_body_company.html
- itou/templates/apply/includes/list_card_body_jobseeker.html
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/test_list_prescriptions.py
Car les utilisateurs cliquant sur la carte candidature se retrouvaient par erreur sur la vue Candidat ou la vue Entreprise.
> Candidature: suppression de liens vers la fiche candidat ou entreprise dans la vue liste des candidatures [GEN-2257]

- itou/approvals/models.py
Résoudre un problème de test vers minuit, comme j’ai fait l’investigation pour avoir un exemple à expliquer.
> Corriger la date logguée par notify_pole_emploi autour de minuit

- itou/templates/apply/includes/list_card_body_jobseeker.html
- tests/www/apply/__snapshots__/test_list.ambr
Les critères administratifs ne sont jamais calculés dans cette vue et ne peuvent donc pas être affichés.
Comme on ne souhaite pas les afficher au candidat car cela serait très redondant, autant ne pas avoir ce code dans le template.
> Candidature: suppression de code inutile

- itou/templates/itou_staff_views/merge_users.html
- itou/templates/itou_staff_views/merge_users_confirm.html
- itou/www/itou_staff_views/forms.py
- itou/www/itou_staff_views/merge_utils.py
- itou/www/itou_staff_views/urls.py
- itou/www/itou_staff_views/views.py
- tests/www/itou_staff_views/__snapshots__/tests.ambr
- tests/www/itou_staff_views/tests.py
Pour éviter des erreurs de la personne qui fait la fusion :
- on met automatiquement le compte le plus ancien à gauche (celui qui va recevoir les relations)
- -on ne met plus de choix par défaut pour la selection des informations personnelles. 
> Amélioration de l'interface de fusion de comptes

- itou/templates/apply/submit_step_pending_authorization.html
- itou/templates/dashboard/includes/dashboard_title_content.html
- itou/templates/job_seekers_views/step_check_job_seeker_nir.html
- itou/www/apply/urls.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/utils/test.py
- tests/www/apply/test_submit.py
- tests/www/dashboard/test_dashboard.py
- tests/www/job_seekers_views/test_create.py
Dans cette PR, on déconnecte l'étape de vérification du NIR du parcours de candidature. En effet, les vues `CheckNirForJobSeekerView` et `CheckNirForSenderView` héritaient de classes dans `apply`.
**À noter :** 
Pour ne pas casser les parcours de candidature en cours en production, nous devons temporairement avoir 2 jeux d'URLs fonctionnels :
- avec une …
> Création de compte candidat : déconnecter la vérification du NIR du parcours `apply`

- itou/www/apply/views/list_views.py
- itou/www/approvals_views/views.py
- itou/www/companies_views/views.py
- itou/www/geiq_views/views.py
https://www.notion.so/plateforme-inclusion/Passer-20-r-sultats-en-vue-carte-et-en-vue-tableau-137e8fa5c35b80e7ab9efe482c6fd036
Je cite :
```
On est passés par erreur à 50 résultats en vue carte.
Après discussion on passe tous les résultats à 20 (en vue carte ET en vue tableau)
```
> Pagination : Passer de 50 à 20 résultats par page sur 6 listes dont les listes de candidatures

- itou/www/stats/views.py
L'actuelle n'est plus d’actualité, et utilisation d'un format générique.
https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-sur-la-page-des-TB-priv-s-et-publics-1455f321b60480a5a091f8d0abea988f?pvs=4
> Statistiques : Mise à jour de la bannière utilisée par défaut

- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create.py
Dans cette PR, on déconnecte l'étape de recherche de candidat par email pour que la vue `SearchByEmailForSenderView` ne dépende plus de classes dans `apply`.
**À noter :** 
Pour ne pas casser les parcours de candidature en cours en production, nous devons temporairement avoir 2 jeux d'URLs fonctionnels, avec et sans le paramètre `company_pk`. Cette …
> Création de compte candidat : déconnecter la recherche par email du parcours `apply` 

- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create.py
Dans cette PR, on déconnecte les étapes de création/modification de candidat, pour que ces vues ne dépendent plus de classes dans `apply`.
La suite, c'est les vues `Update*` !
**À noter :** 
Pour ne pas casser les parcours de candidature en cours en production, nous devons temporairement avoir 2 jeux d'URLs fonctionnels, avec et sans le paramètre …
> Création de compte candidat : déconnecter la création du parcours `apply` 

- itou/rdv_insertion/admin.py
- itou/rdv_insertion/apps.py
Permettre de visualiser rapidement les invitations envoyées, rendez-vous pris (et leur nombre) ainsi que de suivre les webhooks traités et voir leur payload facilement (JSON formaté).
- À venir
> Ajout de RDV-Insertion à l'admin Django [GEN-2178]

- itou/templates/apply/includes/appointments.html
- tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
Tracker l'ensemble des événements prévus :
- Clic bouton proposer un rdv (commun listing/detail de candidature) (déjà en place)
- Clic onglet RDV (déjà en place)
- **Clic sur la modale détails (nouvellement ajouté)**
> Mesurer l’usage de la fonctionnalité RDV-Insertion (Matomo) [GEN-2177]

- tests/utils/test.py
- tests/utils/tests.py
- tests/www/apply/test_process.py
- tests/www/dashboard/test_dashboard.py
Cette forme encourage le développeur à utiliser un entier (la PK d’un objet) comme cible à remplacer. Les premiers entiers sont souvent présents ailleurs dans la page (compte de résultat,, URL encoded `%3D`, etc), ce qui amène à des remplacements surprenants et des tests instables. Dernier exemple en date : #5119
Encourageons les développeurs à mettre du contexte, pour éviter les remplacements instables.
> parse_response_to_soup: Retirer la forme courte de replace_in_attr

- tests/utils/test.py
- tests/utils/tests.py
Éviter des erreurs de remplacement.
Structure de données plus adaptée.
> parse_response_to_soup: Amélioration de replace_in_attr

- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/job_seekers_views/list.html
- itou/templates/layout/base.html
- itou/utils/staticfiles.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Mettre en avant la nouvelle fonctionnalité pour "Postuler pour un candidat"
> UX/UI: Mise en avant du bouton "Postuler pour ce candidat"

- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create.py
Enlever le problème pour l’ajout de future tests, éviter des variables inconnues dans les templates.
> Toujours définir update_job_seeker dans les templates job_seekers_views

- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
- tests/www/dashboard/test_dashboard.py
- tests/www/dashboard/test_dashboard_stats.py
Globalement plus simple à maintenir, plus complet également, et ça permet aussi de voir une partie des changements apportés dans #4589.
Pour les `parametrize` j'ai _normalement_ repris toutes les conditions possibles dans les fonctions `can_view_*` afin de tester le plus de cas particuliers sans exploser le nombre de tests générés.
> Tableau de bord : Utilisation de _snapshots_ pour tester le contenu de l'onglet "Statistiques"

- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create.py
Nous sommes lundi. Dans la nuit, un cron a lancé une commande pour nettoyer les sessions, on peut donc être sûr que les nouvelles sessions ne contiennent plus les URLs dépréciées. Dans cette PR, on supprime le code de :
- CheckNir
- SearchByEmail
- CreateJobSeeker
--- 
Les autres étapes : https://www.notion.so/plateforme-inclusion/Extraire-le-parcours-de …
> Création de compte candidat : nettoyage des URLs et vues dépréciées

- config/settings/base.py
- config/settings/test.py
- itou/analytics/management/commands/collect_analytics_data.py
- itou/analytics/migrations/0001_initial.py
- itou/analytics/models.py
- itou/analytics/tech.py
- itou/utils/apis/sentry.py
- tests/analytics/test_collect_analytics_data_management_command.py
- tests/analytics/test_tech_metrics.py
- tests/conftest.py
- tests/utils/apis/test_sentry_api.py
Afin de suivre l'impact technique de nos actions, nous récoltons l'apdex et le taux de requêtes en échec de Sentry et les conservons dans l'app Analytics.
cf https://github.com/gip-inclusion/les-emplois/pull/5162
> [Analytics] Suivi de l'Apdex et des requêtes non abouties (Sentry)

- itou/www/job_seekers_views/views.py
Dans notre grand nettoyage (#5180) on a oublié d'enlever `SessionNamespaceRequiredMixin` inutile dans `SearchByEmailForSenderView`.
La classe `JobSeekerForSenderBaseView` s'assure déjà qu'on a bien une session.
> Suppression d'une mixin inutilisée 

- itou/www/itou_staff_views/merge_utils.py
- itou/www/itou_staff_views/views.py
- tests/www/itou_staff_views/tests.py
On ne peut pas avoir 2 tokens pour un même utilisateur
> Correction de la gestion des tokens lors de la fusion d'utilisateurs

- itou/www/job_seekers_views/views.py
Les sessions contenant une `birthdate` dans la partie `user` (vs `profile`) ont disparu depuis un moment.
> Tech: nettoyage de code de rétrocompatibilité sur le parcours de création/mise à jour de candidat

- itou/static/js/utils.js
La dernière utilisation de `js-prevent-default` a été supprimée dans f0fdd152cf7448965ee81ddb393b24080babb4dc
> Tech: nettoyage de code inutile

- itou/static/js/utils.js
Lorsque l'élément _swappé_ est l'élément qui doit être trouvé, `target.querySelectorAll` ne le trouvera pas ce qui peut être piégeux.
> Tech: amélioration du code JS pour les swaps htmx

- config/settings/base.py
- itou/openid_connect/pro_connect/middleware.py
- tests/openid_connect/pro_connect/test_middleware.py
Permettre aux utilisateurs ayant une session proconnect active, d'être connectés automatiquement  en provenant des autres sites de la plateforme de l'inclusion
Issue [Commu #846](https://github.com/gip-inclusion/itou-communaute-django/issues/846)
Connexion
* ajout d'un `middleware` activé en présence du paramètre `proconnect_login`
* exploitation du paramètre `username` pour verifier l'existence de l'utilisateur dans les emplois
> disposer d'une instance Pro Connect accessible
> Ajout d'un middleware pour connecter automatiquement les utilisateurs pro_connect

- itou/templates/companies/overview.html
- itou/www/companies_views/views.py
Bouton "retour" plus utile sur les pages de premier niveau
> https://www.notion.so/plateforme-inclusion/Pr-sentation-de-ma-structure-Supprimer-bouton-retour-151e8fa5c35b80d6b772fdd0d8985737?pvs=4
> UX/UI: Suppression du bouton retour sur la page présentation des structures

- itou/approvals/admin.py
- itou/users/admin.py
- itou/utils/admin.py
https://itou-inclusion.slack.com/archives/C02J7LWNT6Z/p1733493909992649
> admin: Utiliser le SIRET et le nom de l’entreprise pour identifier l’appartenance d’un employeur

- itou/templates/companies/job_description_list.html
- tests/www/companies_views/test_job_description_views.py
Le bouton permettant de bloquer ou de débloquer la réception de nouvelles candidatures ne s'affichait que si la structure avait renseigné des fiches de poste. 
Se connecter en tant qu'employeur, aller dans l'onglet Fiches de poste et activer ou bloquer la réception de nouvelles candidatures.
> [Employeur] Affichage du bouton de blocage des candidature pour les structures sans fiches de poste

- itou/templates/companies/job_description_list.html
Seules les balises `<label>`  & `<output>` sont censées avoir un attribut `for`.
> Tech: nettoyage HTML

- config/settings/base.py
- itou/static/js/easymde_config.js
- itou/templates/companies/create_siae.html
- itou/templates/companies/edit_job_description_details.html
- itou/templates/companies/edit_siae_description.html
- itou/templates/layout/base.html
- itou/templates/prescribers/edit_organization.html
- itou/utils/staticfiles.py
- itou/utils/widgets.py
- itou/www/companies_views/forms.py
- itou/www/prescribers_views/forms.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- tests/utils/test_widgets.py
Éviter le problème de dependabot avec setuptools (exemples: #5181-#5195).
Parce que la lib d’intégration a pas mal de défaut et semble non maintenue.
Pour mieux indiquer nos dépendances JS (plutôt que de passer une lib qui vendor pour nous).
Plutôt que de passer par un form Media qui est peu clair, j’ai ajouté la dépendance directement dans `base.html`. Tout le monde devra le charger une fois, puis on n’en parlera plus.
Valider les éditeurs de texte riche sur les pages de :
- description fiche de poste employeur
- description entreprise et accompagnement employeur
- description orga prescripteur
> Vendor la dépendance easyMDE

- config/urls.py
- tests/www/test_anymail.py
Pour limiter le nombre d'URLs exposés au minimum.
Ajouts de tests basiques pour vérifier le fonctionnement, notamment en vu du passage à `LoginRequiredMiddleware`.
> Tech: restriction des URLs exposés par anymail

- itou/static/js/utils.js
Le formulaire de mise à jour de candidat est désactivé si le candidat a pris contrôle de son compte.
Si `birth_place` n'est pas rempli, alors le JS réactive le champ `birth_country`, qui devient alors le seul champ modifiable.
Cette PR propose une correction.
1. En tant que prescripteur habilité, postuler pour Jacques Henry (test+de@inclusion.beta.gouv.fr)
2. À la page de sélection de poste, cliquer sur *Vérifier le profil* (en haut)
3. Tous les champs devraient être grisés
> Correction du JS pour désactiver un champ

- itou/utils/staticfiles.py
Mise à jour du thème pour passage de Gulp a Vitejs.
Vitejs compile et minifie les fichiers différemment donc beaucoup de changement dans les fichiers statiques lié au  changement de l'[outil de build](https://github.com/gip-inclusion/itou-theme/commit/3c0de7cbc30e17075b2d905ef587a8779a40f939).
> UX/UI: Mise a jour du theme en version 2.5.0

- itou/eligibility/models/common.py
Le champ `expires_at` n’est pas nullable, cet attribut aura toujours une valeur
> Simplifier AbstractEligibilityDiagnosisModel.is_valid

- itou/templates/dashboard/includes/edit_job_seeker_info_form.html
- itou/www/dashboard/forms.py
- tests/conftest.py
- tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
- tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
- tests/www/dashboard/test_edit_job_seeker_info.py
- tests/www/dashboard/test_edit_user_info.py
Collecter ces informations pour certifier la situation administrative des candidats (Bénéficiaire RSA, …).
1. Se connecter en tant que candidat
2. Aller dans « Mon profil » en utilisant le menu déroulant
3. Constater la présence des champs
4. Vérifier la logique de validation
1. Se connecter
2. Dans une candidature ou l’interface mes candidats, cliquer sur « modifier » dans l’encart des informations personnelles d’un candidat
3. Constater la présence des champs
4. Vérifier la logique de validation
> Candidats: Ajout des champs commune et pays de naissance dans « Mon profil »

- itou/templates/layout/base.html
- itou/utils/staticfiles.py
La mise à jour du thème en v2.5.3 inclus :
- la montée de version de Bootstrap [5.3.2 > 5.3.3](https://github.com/gip-inclusion/itou-theme/commit/2490c151162b4030c93a3bc2e8f1adc18af85287) 
- la montée de version de Tarte au citron [1.14.0 > 1.19.0](https://github.com/gip-inclusion/itou-theme/commit/35e567b77ae3b43decee4c4107351bc42288729e)   
- un fix de z-index pour [tooltip x offcanvas](https://github.com/gip-inclusion/itou-theme/commit/c7dcf8e0ddd730a0453a01f8fb5f8cfb93083fa1)
Changement de côté de l'icône Tarte au citron, car elle chevauchait le footer du menu connecté
> UX/UI: Mise a jour du theme en version 2.5.3

- itou/asp/models.py
- tests/asp/test_communes.py
- tests/users/factories.py
- tests/www/apply/test_forms.py
- tests/www/apply/test_process.py
Test bagottant : https://github.com/gip-inclusion/les-emplois/actions/runs/12235030153/attempts/1
Reproductible avec `pytest --randomly-seed=3864335593 -vv tests/www/employee_record_views/test_create.py::TestCreateEmployeeRecordStep2::test_access_granted`
Les valeurs choisies était "1999-12-31" pour la date de naissance alors que la ville était :
```
id   | start_date |  end_date  | code  |     name     |          created_at           | city_id 
-------+------------+------------+-------+--------------+-------------------------------+---------
57089 | 1900-01-01 | 1999-12-31 | 67152 | GEISPOLSHEIM | 2023-10-02 08:19:11.118299+00 |  [NULL]
```
> Demandeur d’emploi : Correction de la sélection de la commune de naissance pour les personnes nées le dernier jour de validité de la commune

- itou/common_apps/address/models.py
- itou/users/admin_forms.py
On ne fait rien de ces erreurs donc autant les mettre en `info`.
Et plutôt que de logger les adresses postales, on se contente de logger l'objet à l'origine de l'erreur (la plupart du temps).
> Tech: réduction du niveau de log des erreurs `GeocodingDataError`

- itou/analytics/admin.py
- itou/analytics/management/commands/collect_analytics_data.py
- itou/analytics/models.py
- itou/analytics/tech.py
- tests/analytics/test_collect_analytics_data_management_command.py
- tests/analytics/test_models.py
- tests/analytics/test_tech_metrics.py
Le modèle Datum conserve la valeur en tant qu'entier, or l'apdex et le taux de requête en erreur sont des pourcentages. Ils ont donc une valeur de 0 aujourd'hui. cf #5162 
Les autres mesures étant des valeurs absolues, il me semble inutile de changer le type du champ.
Je ferai une reprise de stock.
```
import datetime
import logging
from dateutil.relativedelta import relativedelta
from itou.utils.apis.sentry import SentryApiClient
from itou.analytics.models import Datum, DatumCode
data = Datum.objects.filter(code__in=[DatumCode.TECH_SENTRY_APDEX, DatumCode.TECH_SENTRY_FAILURE_RATE])
logger = logging.getLogger("itou.analytics")
for datum in data:
if datum.value > 0:
continue
date = datetime.datetime.fromisoformat(datum.bucket)
start = (date - relativedelta(days=1)).replace(hour=0, …
```
> [Stats] Convertion des décimaux en entiers pour ne pas enregistrer des zéros

- tests/users/factories.py
- tests/www/employee_record_views/test_create.py
Reproductible avec `pytest tests/www/employee_record_views/test_create.py::TestUpdateRejectedEmployeeRecord::test_submit_after_rejection --randomly-seed=105817706`
> Tech : Correction d'un test bagottant

- itou/common_apps/organizations/models.py
- tests/companies/test_models.py
- tests/institutions/tests.py
- tests/prescribers/tests.py
- tests/www/apply/__snapshots__/test_submit.ambr
Les _Memberships_ inactives ne devraient pas être prises en compte.
:warning: Mais je me demande si on ne devrait pas tout simplement se baser sur `request.organizations`, ce qui éviterait des requêtes inutiles et centraliserait la règle métier.
> Tech: correction du comportement de `member_required`

- itou/common_apps/organizations/models.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/dashboard/views.py
- tests/companies/test_models.py
- tests/institutions/tests.py
- tests/prescribers/tests.py
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/dashboard/test_switch_organization.py
On a déjà l'info via le middleware donc par nécessaire de la re-récupérer une nouvelle fois d'une autre façon.
> Tech: suppression de la méthode `member_required`

- itou/approvals/admin.py
- itou/users/admin.py
- itou/utils/admin.py
- tests/users/test_admin.py
Suite de cf47b6641c5b6c3da10cab47ebb7cefcb360bc86.
> admin: Clarifier les structures dont sont membres les utilisateurs

- config/settings/base.py
- config/settings/test.py
- itou/analytics/migrations/0001_initial.py
- itou/analytics/models.py
- itou/analytics/tech.py
- itou/utils/apis/updown.py
- tests/analytics/test_collect_analytics_data_management_command.py
- tests/analytics/test_tech_metrics.py
- tests/conftest.py
- tests/utils/apis/test_updown.py
Suivre l'évolution de notre taux de disponibilité au fil du temps.
cf https://github.com/gip-inclusion/itou-secrets/pull/115
```python
import datetime
import logging
from dateutil.relativedelta import relativedelta
from dateutil.rrule import rrule, DAILY
from django import db
from django.db import transaction
from django.forms import models
from django.utils import timezone
from itou.analytics.models import Datum, DatumCode
from itou.utils.apis.updown import UpdownApiClient
logger = logging.getLogger("itou.analytics")
end = timezone.now()
start = datetime.datetime(2024,10,1, tzinfo=datetime.UTC)
days = (end-start).days
dates = list(rrule(freq=DAILY, dtstart=start, count=days))
def call_and_store(date):
start = (date - relativedelta(days=1)).replace(hour=0, minute=0, second=0, …
```
> [Analytics] Récupération du taux de disponibilité de notre applicatif et de l'apdex (Updown)

- tests/job_applications/factories.py
- tests/www/apply/test_list_prescriptions.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_details.py
- tests/www/job_seekers_views/test_list.py
Car l'utilisation directe du trait `with_mocked_address` du `JobSeekerFactory` est plus simple/clair (et évite de faire croire que `JobApplicationFactory(job_seeker=job_seeker, job_seeker_with_address=True)` va fournir un candidat avec adresse :see_no_evil: )
> Tests: suppression du trait `job_seeker_with_address`

- config/settings/base.py
- itou/templates/signup/job_seeker_signup_credentials.html
- itou/utils/password_validation.py
- itou/www/signup/forms.py
- tests/users/factories.py
- tests/users/test_models.py
- tests/www/signup/__snapshots__/test_job_seeker.ambr
- tests/www/signup/__snapshots__/test_password.ambr
- tests/www/signup/test_job_seeker.py
- tests/www/signup/test_password.py
Histoire que les candidat arrivent à comprendre pourquoi leur mot de passe est refusé.
Et pour améliorer la sécurité en conformité avec les règles de la CNIL
> Connexion: Donner plus d'informations sur le choix du mot de passe pour un nouveau candidat 

- itou/openid_connect/utils.py
- itou/utils/constants.py
- itou/www/signup/urls.py
- itou/www/signup/views.py
- tests/www/signup/test_job_seeker.py
Ce code a été mis en place pour faciliter la transition pour les utilisateurs en cours d'enregistrement au moment du déploiement, et devait être supprimé peu de temps après.
> Inscription: Supprimer code temporaire pour le deploiement de la refonte du parcours d'inscription

- itou/www/job_seekers_views/views.py
Voir message de commit.
TL;DR il restait des miettes après un coup de balais.
> Nettoyage des valeurs initiales dans `CreateOrUpdateJobSeekerStep3Form` 

- itou/communications/cache.py
- itou/utils/cache.py
- tests/communications/test_cache.py
- tests/conftest.py
- tests/utils/test_cache.py
La campagne active est mise en cache pour être utilisée dans une modale qui s'affiche sur le site. Si la connexion au cache est interrompue, une erreur 500 sera générée.
> Page d’accueil: Éviter le plantage en cas de rupture de la connexion au cache

- itou/metabase/tables/job_seekers.py
- tests/metabase/management/test_populate_metabase_emplois.py
Actuellement nous calculons la validité des diag à la main, suite à plusieurs changements métier ce n’est plus vraiment la bonne façon de procéder. 
Cette info est présente sur les emplois donc nous allons la récupérer directement 🙂
> Pilotage : Récupérer la validité des diagnostic directement dans les emplois

- itou/approvals/admin.py
- itou/companies/admin.py
- itou/prescribers/admin.py
- itou/users/admin.py
- itou/utils/admin.py
Car ce n'était pas le cas jusqu'à présent, que [ça été demandé](https://github.com/gip-inclusion/les-emplois/pull/5309/files#r1899721912), que ça semble une bonne chose, et que ça évite de devoir aller trifouiller dans les `admin.LogEntry`.
La seule interaction à laquelle j'ai pensée est la logique de _proxy_ mais ça ne devrais pas poser problème dans le futur, on pourrais même dire qu'un utilisateur créé depuis l'admin est bien géré par un proxy :).
Créer un utilisateur depuis l'admin
> Admin : Renseigner le champ `User.created_by` lors de la création

- itou/cities/management/commands/sync_cities.py
- itou/emails/admin.py
- itou/metabase/db.py
- itou/metabase/management/commands/populate_metabase_matomo.py
- itou/rdv_insertion/api.py
- itou/utils/apis/api_entreprise.py
- itou/utils/apis/api_particulier.py
- itou/utils/apis/data_inclusion.py
- itou/utils/apis/datadog.py
- itou/utils/apis/esd.py
- itou/utils/apis/geiq_label.py
- itou/utils/apis/geocoding.py
- itou/utils/apis/pole_emploi.py
- itou/utils/apis/sentry.py
- itou/utils/apis/updown.py
- itou/www/apply/views/process_views.py
Il s'avère que `.raise_for_status()` retourne la réponse ! Donc pas besoin de saucissonner les appels.
Documentation associée : https://www.python-httpx.org/quickstart/#response-status-codes
Dépend si vous faite confiance ou pas à notre suite de test :shrug: :see_no_evil: :innocent:
> Tech : Chainer les appels pour `.raise_for_status()` d'HTTPX

- itou/employee_record/admin.py
- itou/employee_record/migrations/0002_fix_archived_json_as_string.py
Car pendant un certain temps c'était la sérialisation JSON de la sérialisation JSON de l'archive qui était stockée : `"{\"numLigne\":124,\"typeMouvement\":\"C\",...}"`
Alors que l'on veux juste la sérialisation JSON : `{"numLigne":124,"typeMouvement":"C",...}`
Commits associés :
- https://github.com/gip-inclusion/les-emplois/pull/1659/commits/37c890ffd42c98dad5ffbfb25f1e810cb25d6e4a
- https://github.com/gip-inclusion/les-emplois/pull/3761/commits/adccc5ff1ce313cff28dbae80d85c4fa24ec7644#r1522958833
> Fiches salarié : Corriger définitivement la sérialisation des vieilles archives JSON

- itou/eligibility/models/common.py
- itou/eligibility/models/geiq.py
- itou/eligibility/models/iae.py
- itou/www/apply/views/submit_views.py
- tests/eligibility/factories.py
- tests/eligibility/test_iae.py
- tests/www/apply/test_submit.py
Aligner la durée de validité des diagnostics employeur avec la durée de validité des justificatifs (3 mois).
1. Se connecter en tant qu’employeur
2. Créer une candidature pour un nouveau candidat
3. Dans le parcours d’acceptation de candidature, effectuer un diagnostic d’éligibilité
4. Vérifier dans l’admin que le diagnostic d’éligibilité expire dans 92j.
Vérifier que les diagnostics IAE PH et GEIQ continuent de durer 6 mois.
> Employeur: Réduction de la durée de validité du diagnostic d’éligibilité à 92 jours [GEN-2276]

- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
Demande de LJT :
> Je veux bien que tu nous rajoutes de quoi voir (lecture seule) les prescriptions et candidatures, c’est pratique comme contexte avant de contacter quelqu’un.
> Admin : Donner accès aux candidatures en lecture seule à GPS

- itou/companies/management/commands/import_geiq.py
- itou/utils/faker_providers.py
- tests/companies/test_management_command_import_geiq.py
Parfois les SIRET sont des float dans le tableur importé. Une fois casté en chaîne de caractères, le SIRET devient 'XXXXXXXXXXXXXX.0'.
cf https://inclusion.sentry.io/issues/15011873/
C'est la solution la plus courte que j'ai trouvée, mais je suis preneur d'amélioration le cas échéant !
---
Label `bug` ou pas ? :thinking:
> GEIQ : meilleure gestion du type de la colonne SIRET du xls importé

- itou/companies/management/commands/update_companies_job_app_score.py
- tests/companies/test_management_commands.py
En manipulant le script en local pour creuser l'évolution en cours de la recherche employeur, j'ai réalisé qu'on avait un gros souci avec l'algorithme actuel. Des entreprises non pertinentes (grand nombre de candidatures) se retrouvent en toute première page en prod et accumulent des candidatures. Probablement car quand leur nouveau score devient None (si elle n'ont plus aucune fiche de poste après en avoir eu) ce None n'est jamais propagé en db et l'ancien score reste ad vitam eternam.
Voir les exemples d'entreprises non pertinentes dans https://www.notion.so/plateforme-inclusion/Tri-des-employeurs-fiches-de-postes-137e8fa5c35b804b95c7f05f68f69b81
J'ai commencé par rajouter du test cassant (TDD). Ca repasse au vert quand j'enlève toute la clause `exclude`. Je propose ici une solution …
> Correctif de la mise à jour des scores de la recherche employeur

- itou/utils/staticfiles.py
Pour harmoniser les styles des [textarea EasyMDE](https://www.notion.so/plateforme-inclusion/UI-Adapter-le-textarea-de-EasyMDE-au-th-me-161e8fa5c35b80dc8f6cd3c771cdf49a?pvs=4) avec les textarea du thème et ajouter une aide visuelle au focus
**Avant**
**Apres**
> UX/UI: mise a jour du theme vers v2.5.6

- itou/communications/dispatch/base.py
- itou/communications/dispatch/email.py
- itou/templates/apply/includes/job_application_sender_info.html
- itou/templates/layout/base_email_text_body.txt
- itou/users/notifications.py
- itou/www/apply/views/process_views.py
- tests/communications/test_dispatch.py
- tests/job_applications/__snapshots__/test_transfer.ambr
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_process.py
Simplifier la prise de contact avec le référent.
Il faut mettre en place l'envoi des réponses aux administrateurs avant ce ticket en revanche
> Candidature: Prévenir dans la candidature que la personne a quitté l’organisation

- scripts/mkchangelog
Pour le corriger :)
Avec cette PR la prochaine entrée du changelog sera 
```
Rien à signaler cette semaine
...
```
> Correctif du script de génération du journal des changements.

- itou/templates/layout/base.html
Pour que les surcharges fonctionnent comme prévu. Tri du plus général au plus spécifique: upstream < app.css (thème) < itou.css (spécifique aux emplois).
> Ordonner les feuilles de style dans base.html

- itou/utils/templatetags/badges.py
- tests/utils/__snapshots__/tests.ambr
- tests/www/approvals_views/test_list.py
https://www.notion.so/plateforme-inclusion/Harmoniser-la-couleur-des-badges-PASS-IAE-160e8fa5c35b80599b66d1abfa97d2b5?pvs=4
Acté avec Antoine. Finalement, les couleurs de badges de statues de "Pass IAE" resteront les mêmes dans les cartes de résultats et donc plus clair que ceux dans la box de Pass IAE. Juste une petite correction sur le badge "Agrément expiré"
> UX/UI: modification de la couleur du badge "Agrément expiré"

- itou/communications/dispatch/email.py
- tests/communications/test_dispatch.py
> Notifications: Continuer à envoyer les notifications aux anciens collaborateurs

- itou/eligibility/models/iae.py
- itou/siae_evaluations/fixtures.py
- tests/www/apply/test_submit.py
Réparer `make resetdb`.
```
python manage.py shell -c 'from itou.siae_evaluations import fixtures;fixtures.load_data()'
Traceback (most recent call last):
File "/home/freitafr/dev/itou3/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
return self.cursor.execute(sql, params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/freitafr/dev/itou3/.venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
raise ex.with_traceback(None)
psycopg.errors.NotNullViolation: null value in column "expires_at" of relation "eligibility_eligibilitydiagnosis" violates not-null constraint
DETAIL:  Failing row contains (6, employer, 2653, 2024-11-23 15:59:33.079627+00, 2025-01-07 15:59:33.570748+00, 28, null, 48, null).
```
> Définir EligibilityDiagnosis.expires_at pour le CaP

- itou/templates/apply/submit/application/base.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create_or_update.py
Dans cette PR, on déconnecte les étapes de modification de candidat, pour que ces vues ne dépendent plus de classes dans `apply`.
Il y a un peu plus de changements que dans les vues précédentes, puisque les vues de `Update*` utilisaient une session un peu différente. Les URLs utilisaient le `job_seeker.public_id`. 
On introduit ici le concept de vue …
> Création de compte candidat : déconnecter la modification de compte du parcours `apply` 

- itou/templates/search/includes/siaes_search_top.html
- itou/www/search/views.py
- tests/www/search/__snapshots__/tests.ambr
Ces résultats sont jusqu'ici triés par catégorie puis par date de modification puis par date de création.
Or la date de modification `updated_at` étant un `datetime`, il n'arrive jamais en pratique que deux valeurs soient identiques.
On peut s'en convaincre avec un simple `select count(*), count(DISTINCT(created_at)), count(DISTINCT(updated_at)) from companies_jobdescription;` sur le jeu de données de prod.
Conclusion : le troisième tri (date de création) n'est jamais utilisé en pratique. C'est un écran de fumée qui induit en erreur le developpeur sur la nature du tri.
Noter que pour un object créé puis jamais modifié, son `updated_at` est égal à sa date de création.
En virant le tri superflu, et en mettant à jour la description du tri sur le frontend.
C'est pour Xavier.
Léo mon binôme …
> Simplification du tri des résultats de la recherche de fiches de poste

- itou/eligibility/tasks.py
- itou/utils/apis/api_particulier.py
- itou/utils/mocks/api_particulier.py
- tests/eligibility/test_iae.py
- tests/eligibility/test_tasks.py
- tests/www/apply/test_process.py
Dans un email du 15 novembre à 14:23, une régression cassant la compatibilité a été annoncée:
> Vous utilisez l'API Revenu de solidarité active du bouquet API Particulier
> et avez prévu d'utiliser les API Allocation de soutien familial et
> Allocation adulte handicapé.
>
> Dans le Swagger et la documentation affichés actuellement sur API
> Particulier, nous indiquons que nous diffusons la date de fermeture du
> droit. Toutefois, cette date n'est pas toujours correcte. En effet, elle
> était calculée par notre API en se basant sur la date de début du droit.
> Cette date de début du droit correspond à la date de première attribution.
> Lorsque le droit est renouvelé, la date de début n'est pas modifiée. Cela
> peut donc renvoyer à une date de fin antérieure à la date à laquelle
> l'appel …
> Éligibilité : Prise en compte du forçage de `dateFin` à null par l’API Particulier

- migrations.md
Les rendre visibles aux développeurs et leur donner envie de les compléter.
> Documenter les migrations techniques en cours

- itou/templates/apply/email/cancel_body.txt
- itou/templates/apply/email/new_for_employer_body.txt
- itou/templates/apply/email/new_for_job_seeker_body.txt
- itou/templates/apply/email/new_for_prescriber_body.txt
- itou/templates/apply/includes/job_application_info.html
- itou/templates/apply/includes/list_reset_filters.html
- itou/templates/apply/includes/selected_jobs_list.html
- itou/templates/approvals/includes/list_reset_filters.html
- itou/templates/companies/card.html
- itou/templates/companies/job_description_card.html
- itou/templates/companies/job_description_list.html
- itou/templates/gps/includes/memberships_results.html
- itou/templates/gps/my_groups.html
- itou/templates/search/includes/siaes_search_subtitle.html
- itou/templates/signup/company_select.html
- itou/utils/templatetags/str_filters.py
- tests/gps/__snapshots__/test_views.ambr
- tests/utils/tests.py
Suite à une discussion avec @rsebille.
Pour éviter les `pluralizefr` / `{% if ... ` en cascade.
Cela nécessitera un test pour vérifier que toutes les entrées du dictionnaire.
Premier commit, utilisation d'un tag `{% plural ...`:
`{% plural "{} bénéficiaire suivi" memberships_page.paginator.count %}`
Version actuelle, utilisation d'un filtre:
`{{ memberships_page.paginator.count|plural:"{} bénéficiaire suivi" }}`
Autre possibilité:
`{{ "{} bénéficiaire suivi"|plural:memberships_page.paginator.count }}`
Cela serait effectivement en alternative/concurrence au natif `{% blocktranslate ... %} ... {% plural %} {% endblocktranslate %}` de Django qui est assez verbeux.
> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés. Attirez l'attention …
> Amélioration de `pluralizefr` pour correspondre au `pluralize` de Django

- itou/asp/forms.py
- itou/templates/signup/job_seeker_signup.html
- itou/templates/signup/job_seeker_signup_credentials.html
- itou/www/signup/forms.py
- tests/openid_connect/pe_connect/tests.py
- tests/www/signup/__snapshots__/test_job_seeker.ambr
- tests/www/signup/test_job_seeker.py
- tests/www/welcoming_tour/tests.py
Afin de certifier l’éligibilité d’un candidat à certains critères administratifs et lui octroyer automatiquement les droits à un parcours IAE, l’API particulier requiert la commune et le pays de naissance. Ces informations sont maintenant requises pour l’inscription sur les Emplois de l’inclusion.
La classe de base `BirthPlaceAndCountryMixin` hérite désormais de `Form`, non plus de `ModelForm`. Ceci permet au formulaire d’inscription (qui n’est pas un `ModelForm`) de réutiliser le _mixin_. Le point d’extension `_post_clean()` n’est pas disponible sur les `Form`, sa logique a été intégrée dans la méthode `clean()`.
1. S’inscrire en tant que candidat
> Inscription : Ajouter les champs lieu et pays de naissance pour les candidats [GEN-1946]

- itou/users/models.py
- itou/www/autocomplete/views.py
- tests/gps/test_views.py
On n'a pas très envie d'avoir du code utilisant les modèles de GPS dans users/models.py
> Déplacement de code GPS

- itou/eligibility/migrations/0009_fix_selectedadministrativecriteria_certification_period.py
L’API particulier calculait le champ `dateFin` avec la formule : `dateDebut + 3 mois`. Cette information est très déroutante, car une personne bénéficiaire depuis 2009-06-01 aurait comme réponse:
```json
{
"statut": "beneficiaire",
"dateDebut": "2009-06-01",
"dateFin": "2009-09-01",
}
```
Cependant, le `statut` indique que cette personne est bénéficiaire **aujourd’hui**, malgré la `dateFin` (qui est erronée).
L’API vient d’évoluer pour toujours définir `dateFin=null` afin de limiter les mauvaises interprétations. https://github.com/gip-inclusion/les-emplois/pull/5337
Correction d’environ 11 000 diagnostics, en utilisant la date d’appel à l’API pour le calcul de la date de fin de certification.
L’exemple ci-dessus provient de données actuellement en production.
:warning: **Ne relire que le …
> Éligibilité : Rattrapage de dates de fin incorrectes de l’API Particulier

- itou/templates/employee_record/includes/create_step_1.html
- itou/templates/employee_record/includes/create_step_2.html
- tests/www/employee_record_views/__snapshots__/test_create.ambr
Dans le formulaire pour "Compléter une fiche salarié" : 
- passer le 'bon à savoir' en composant info
- mettre les label+input l’un en dessous des autres
-> https://www.notion.so/plateforme-inclusion/Compl-ter-une-fiche-salari-Passer-le-bon-savoir-en-composant-info-174e8fa5c35b80f5a483c2f4a9e5f638?pvs=4
**Avant**
**Apres**
> UX/UI: Passer le "bon à savoir" en composant info

- .github/workflows/ci.yml
Notre configuration sur le dépôt fait que Github bloque le lancement des workflows pour les nouveaux contributeurs, dans le bloc de fusion [1] il y a alors un bouton _"Approve and run"_ qui permet de lancer le workflow si on fait confiance aux modifications apportées par la PR, mais notre action de CI n'est pas relancée lorsqu'on clique sur ce bouton, ce qui bloque la fusion de la PR.
Je me souviens de discussion à ce propos mais pas retrouver de _commit_ donc j'imagine qu'on repart pour un tour :sweat_smile:.
Inconvénient : Ouvrir la PR relance le workflow en entier, même si pas de changement depuis.
Inconvénient : Oblige d'ouvrir une PR (au moins en _draft_) pour avoir la CI de lancée.
https://github.com/gip-inclusion/les-emplois/pull/5323
[1]
> github: Pouvoir lancer `ci.yml` sur les PR ouvertes depuis un fork publique

- itou/metabase/db.py
- itou/metabase/utils.py
- tests/eligibility/factories.py
Problème d’interprétation de date (naïve), révélé par `pytest --randomly-seed=3296184821 tests/metabase/management/test_populate_metabase_emplois.py::test_populate_job_seekers -vv`.
> Pilotage: Utiliser une date qui prend en compte la timezone pour EligibilityDiagnosis.created_at

- itou/www/apply/views/process_views.py
- tests/www/apply/test_geiq.py
Je ne savais pas que c'était possible ça :/
mais c'est plus d'un quart des candidature geiq acceptées, donc mieux vaut le corriger
https://inclusion.sentry.io/issues/15627811/?project=4508410589020240&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=16
> candidature: correction de l'affichage d'une candidature geiq acceptée sans diagnostic

- itou/www/stats/views.py
Il n'y a plus des webinaires prévues (https://www.notion.so/gip-inclusion/Supprimer-l-encart-webinaires-q-r-1775f321b60480bb906afda8030656ce).
Pour l'instant j'ai choisis la solution rapide. À la suite je vais ouvrir un PR qui propose une patterne où on utilise un modèle pour paramétrer l'activation d'encart webinaire.
Visiter un TdB en local (par example celui pour les administrateurs). Ils sont trouvables par le dashboard.
> Pilotage: Supprimer l’encart webinaires

- itou/templates/gps/includes/memberships_results.html
- itou/templates/gps/my_groups.html
- itou/www/gps/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
https://www.notion.so/gip-inclusion/Transformer-la-liste-des-b-n-ficiaires-en-tableau-14d5f321b604807db116cdd0197dc5ec?pvs=4
> GPS: Transformer la liste des bénéficiaires en tableau

- itou/www/apply/views/process_views.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/companies_views/test_job_description_views.py
Demande métier.
https://www.notion.so/plateforme-inclusion/Lorsque-je-transf-re-une-candidature-et-que-je-me-rends-sur-une-fiche-de-poste-mise-par-ma-structur-32bdf1d08cc244f8b9ddedb7aa0acdd9?d=126e8fa5c35b8040a94e001c93e9f791
> Candidatures : Masquer le bouton « Modifier » des fiches de poste lors du transfert vers un métier de sa structure [GEN-2005]

- config/settings/base.py
Migration en @inclusion.gouv.fr.
> Changer l’adresse de contact pour l’API des emplois

- itou/www/employee_record_views/forms.py
- itou/www/job_seekers_views/forms.py
Ratée dans c92937218b13e00946a1dc54fd8ee7f63dc2010d
> Retirer la classe non utilisée js-period-date-input

- itou/gps/admin.py
- itou/users/admin.py
- tests/gps/test_admin.py
- tests/users/__snapshots__/test_admin_views.ambr
https://www.notion.so/gip-inclusion/Faire-figurer-les-groupes-de-suivi-sur-les-pages-utilisateurs-de-l-admin-1735f321b6048037828cdf72eb037f24?pvs=4
> GPS: Ajout de liens dans l'admin

- itou/communications/dispatch/base.py
- itou/job_applications/models.py
- itou/job_applications/notifications.py
- itou/www/apply/views/submit_views.py
- tests/communications/test_dispatch.py
- tests/job_applications/tests.py
- tests/www/dashboard/__snapshots__/test_edit_user_notifications.ambr
Certaines notifications ne prennent pas en compte la configuration par l'utilisateur, ou alors peuvent être envoyée à un utilisateur désactivé
> Notifications: Correction de l'envoi de certaines notifications

- itou/templates/apply/submit/application/base.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/views.py
- migrations.md
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create_or_update.py
Dans cette PR , on apporte quelques corrections, voir les commits et leur message.
---
**Ancienne description** (car cette PR était plus complexe, le reste sera fait dans une nouvelle PR)
Dans l'optique de [Créer un compte candidat depuis l'espace Mes candidats](https://www.notion.so/plateforme-inclusion/5-5-En-tant-qu-utilisateur-je-peux-cr-er-un-compte …
> Création de compte candidat : remise à plat des query params pour les vues Update

- itou/templates/prescribers/card.html
Pour harmoniser avec les fiches employeurs
https://www.notion.so/plateforme-inclusion/Revoir-UI-des-fiches-de-d-tail-d-un-prescripteur-12ee8fa5c35b806db21bf851cb83123c?pvs=4
**Avant**
**Apres**
> UX/UI: Correction des fiches de détail d’un prescripteur

- itou/templates/stats/stats.html
- itou/utils/apis/metabase.py
- itou/www/stats/views.py
- tests/www/stats/test_views.py
Nous souhaitons ajouter un bandeau pour informer nos utilisateurs qu'un tableau de bord est en sursis avec un lien tally pour leur demander leur avis.
https://www.notion.so/gip-inclusion/Ajouter-un-bandeau-sur-les-TB-en-sursis-1765f321b60480919dbece1c355ebf34
> Pilotage: Ajouter un bandeau sur les tableaux de bord en sursis

- itou/templates/includes/deactivate_member.html
- itou/templates/includes/update_admin.html
Je n'ai pas ajouté de test sur le wording pour le moment, je ne sais pas si c'est très utile, à part pour s'assurer que le bon message s'affiche pour les prescripteurs.
Un avis ?
> UX/UI: Amélioration du message affiché avant de retirer un collaborateur [GEN-1823]

- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/enums.py
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create_or_update.py
Précédemment, dans la série, nous avons introduit une vue `start` pour les vues `Update*` (#5177), qui permet d'initialiser la session du bloc et de renvoyer à la vue désirée.
Cette PR est dédiée à la réalisation du même travail poru les vues relatives à la recherche et la création de compte candidat. On utilise une nouvelle vue `Start` pour initialiser …
> Création de compte candidat : une vue `Start` pour la recherche et la création de compte

- itou/templates/account/login_existing_user.html
- tests/www/login/__snapshots__/tests.ambr
InclusionConnect a été remplacé par ProConnect dans `login_generic.html`, mais `ExistingUserLogin` présente nos utilisateurs avec la mode de connexion active sur leur compte.
ExistingUserLogin est utilisé quand il y a un conflit des e-mails pendant une connexion avec un SSO, et dans le parcours de connexion candidat.
* Se connecter avec un candidat où `identity_provider == "IC"`
> Connexion: Rediriger les utilisateurs d'InclusionConnect vers ProConnect

- config/settings/base.py
- itou/templates/apply/includes/eligibility_section.html
- itou/templates/apply/submit/application/eligibility.html
- itou/templates/apply/submit/application/resume.html
- itou/templates/dashboard/includes/prescriber_organisation_card.html
- itou/templates/search/siaes_search_home.html
- itou/utils/templatetags/url_add_query.py
- tests/utils/tests.py
> Le site des emplois redirige vers le Diagnostique Parcours IAE de la communaute. Ce diagnostique necessite l'authentification de l'utilisateur. Nous pensons que les utilisateurs `pro_connect` lors du changement de site, pourraient ne pas être motivés à se reconnecter. Nous testons la mise en place de l'autoconnection sur ce lien des emplois vers la commu.
lien avec [l'issue communaute #846](https://github.com/gip-inclusion/itou-communaute-django/issues/846)
changelog : connexion
> ajout d'un tag `autologin_proconnect`
>  se connecter avec un utilisateur `ProConnect`
> Permettre l'autoconnection à proconnect sur les liens vers la communauté (DSP) [GEN-2389]

- itou/www/gps/forms.py
- tests/gps/test_create_beneficiary.py
Un hack avait été utilisé pour permettre la création de bénéficiaire dans GPS : passer par `apply` (c'est-à-dire commencer un processus de candidature) avec une entreprise spéciale (PoleEmploi).
Grâce au travail sur `job_seekers_views` et l'extraction du parcours de création de compte du parcours de candidature, on peut éviter de passer par `apply` pour créer un bénéficiaire dans GPS.
Pour éviter les erreurs lors de la mise en production¹, la logique touchant à GPS dans `apply.views.submit_views` est nettoyée dans une PR (#5408) qui sera fusionnée ultérieurement.
¹ : ce qui peut se produire : 
1. un utilisateur affiche la page "Ajouter un bénéficiaire", avec l'URL `apply/start?gps=true`
2. le déploiement se fait
3. l'utilisateur clique sur le lien
4. 💥
---
Au passage, le bug suivant est …
> GPS : la création de bénéficiaire ne passe plus par les vues `apply` 

- itou/utils/apis/pole_emploi.py
Ces 2 scopes font que toutes les demandes de token échouent avec comme erreur `invalid_scope`.
Cela empêche toutes les utilisations des APIs FranceTravail.
Cette PR débloque la situation mais idéalement je pense qu'il faudrait que chaque commande ne demande que les scopes dont elle a besoin.
Je n'ai pas commenté la commande `sync_romes_and_appellations`: son échec dans Sentry nous rappellera peut-être d'aller dé-commenter ces scopes si on ne l'a pas encore fait.
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une …
> API: commentaire temporaire des scopes de l'API Rome en maintenance

- itou/www/job_seekers_views/views.py
- tests/gps/test_create_beneficiary.py
Depuis le travail effectué sur `job_seekers_views`, que GPS utilise pour créer un nouveau bénéficiaire, on remplit une session avec l'information `tunnel="gps"`. 
On n'a donc plus besoin de passer cette information dans l'URL.
---
Déploiement : on attend lundi pour que les sessions possèdent bien toutes un `tunnel`.
- se rendre dans GPS (dashboard > Visualiser les bénéficiaires > Ajouter un bénéficiaire)
- taper n'importe quoi dans la barre de recherche de bénéficiaires, pour faire apparaître le lien "Enregistrer un nouveau bénéficiaire"
- cliquer sur ce lien
- vérifier que `?gps=true` n'apparaît dans aucune page tout au long de la création du bénéficiaire
> GPS: utiliser le `tunnel` de la session et non un paramètre dans l'URL

- itou/templates/companies/includes/_card_siae.html
- tests/www/search/tests.py
Lorsque l'employeur bloque l'envoi de candidatures, les boutons "Postuler" ne sont pas affichés.
Tous, sauf dans un cas : dans la recherche employeur, si au moins une offre d'emploi n'est pas individuellement désactivée.
Ça mène à des incompréhensions : https://gip-inclusion.slack.com/archives/C0412CTV63D/p1737120766865729
- en tant qu'administrateur d'une entreprise, bloquer l'envoi de canditatues (à la page /company/job_description_list)
- en tant qu'un autre utilisateur
- chercher l'entreprise dans la recherche et cliquer sur Postuler
- ou saisir directement l'adresse `/apply/<pk de l'entreprise>/start`
Avant : 
Après :
> Recherche employeur : ne jamais afficher de bouton Postuler quand l'employeur a bloqué l'envoi de candidatures

- itou/templates/job_seekers_views/details.html
- itou/templates/job_seekers_views/includes/nav_tabs.html
- itou/templates/job_seekers_views/job_applications.html
- itou/www/job_seekers_views/urls.py
- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/test_details.py
https://www.notion.so/plateforme-inclusion/Lorsque-je-consulte-une-candidature-depuis-l-onglet-candidat-d-une-fiche-candidat-je-devrais-reve-126e8fa5c35b80dd87bbdf105a7856cb
Les deux onglets de la page Candidat (voir screenshots ci-dessous) n'ayant pas d'URL propre, si on clique sur un lien puis qu'on revient en arrière, on revient systématiquement sur l'onglet par défaut (informations générales) et pas sur l'onglet secondaire (Candidatures) même si on était dessus avant de cliquer sur le lien.
On donne à chaque onglet son URL propre en séparant l'unique route actuelle en deux routes. Notez qu'on conserve une unique vue mais qu'on sépare son gabarit en deux.
Chaque route pointe vers son gabarit directement dans le `urls.py`. Pour cela j'ai d'abord tenté un …
> UX/UI : Lorsque je consulte une candidature depuis l’onglet “candidat” d’une fiche candidat, je devrais revenir sur ce même onglet

- itou/static/js/gps.js
- itou/www/autocomplete/views.py
- tests/gps/test_views.py
> GPS: Amélioration de l'affichage des résultat de l'ajout de bénéficiaires

- itou/www/itou_staff_views/urls.py
- itou/www/itou_staff_views/views.py
- tests/www/itou_staff_views/tests.py
> la fusion de membres est actionnable à partir des `id` incrémental des `users`
Admin
> remplacer les `id` par les `public_id`
-  Mettre à jour le CHANGELOG_breaking_changes.md ? > Non
[ref notion](https://www.notion.so/plateforme-inclusion/IDOR-securiser-l-url-de-fusion-des-membres-181e8fa5c35b80cdbc09f93f152c6b87?pvs=4)
> [IDOR] sécurisation des urls de fusion de membres [GEN-2400]

- itou/templates/admin/job_applications/jobapplication_change_form.html
- itou/templates/apply/includes/buttons/new_diagnosis.html
- itou/templates/apply/includes/job_seeker_info.html
- itou/templates/apply/includes/transfer_job_application.html
- itou/templates/apply/process_refuse.html
- itou/templates/approvals/details.html
- itou/templates/approvals/includes/box.html
- itou/templates/approvals/includes/list_card.html
- itou/templates/approvals/prolongation_requests/list.html
- itou/templates/approvals/prolongation_requests/show.html
- itou/templates/dashboard/includes/dashboard_title_content.html
- itou/templates/dashboard/includes/employer_job_applications_card.html
- itou/templates/geiq/assessment_info_for_employer.html
- itou/templates/includes/members.html
- itou/templates/job_seekers_views/includes/list_results.html
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/approvals_views/__snapshots__/test_approval_box.ambr
- tests/www/approvals_views/__snapshots__/test_detail.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/geiq_views/__snapshots__/tests.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Les attributs de data-bs-tooltip étaient souvent pas complets
En remplacant les `title="blabla..."` par des `data-bs-title="blabla..."` afin que le js de BS puisse correctement associer (avec un `aria-labelledby=""`) les `data-bs-toggle="tooltip"` avec l'élément contenant le texte du `data-bs-title` lors de l'activation du tooltip
> UX/UI: Correction des attributs sur les tooltips

- .github/pull_request_template.md
Pour mieux mesurer le nombre de PR résolvant un bogue.
> Gabarit des PR : ajout d'une mention pour vérifier si l'étiquette Bug est nécessaire

- itou/templates/apply/includes/geiq/legislative_text_link.html
- itou/templates/apply/submit/application/eligibility.html
- itou/templates/apply/submit/application/geiq_eligibility.html
- itou/templates/approvals/prolongation_requests/deny.html
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
Certains templates d'étapes de formulaire ne respectaient pas la "charte" du thème.
-> https://gip-inclusion.slack.com/archives/C02GBUVFUBY/p1737467095703439
- En corrigeant les incohérences de largeur de colonnes
- En supprimant les sous colonnes inutiles
- En remplaçant le `.c-form-conseil` par un `.c-info`
- En nettoyant le DOM
**Avant**
**Apres**
> UX/UI: corrections UI des templates "eligibility"

- itou/www/employee_record_views/urls.py
> cf titre
Mettre à jour le CHANGELOG_breaking_changes.md > NON
[notion](https://www.notion.so/plateforme-inclusion/tech-typage-manquants-dans-des-url-de-employee_record_views-183e8fa5c35b80a39475ea8b59564422?pvs=4)
> tech: typage manquants d'arguments des urls de `employee_record_views` [GEN-2416]

- itou/api/README-FS-SSII.md
- itou/fixtures/django/05_test_users.json
- itou/fixtures/django/06_confirmed_emails.json
- itou/siae_evaluations/fixtures.py
- itou/utils/mocks/rdv_insertion.py
- itou/utils/templatetags/demo_accounts.py
- scripts/mkchangelog
- tests/rdv_insertion/tests.py
- tests/www/apply/test_detail_rdv_insertion.py
- tests/www/apply/test_list_rdv_insertion.py
Les emails en @inclusion.beta.gouv.fr disparaitront bientôt.
> Préférer des emails en @inclusion.gouv.fr

- itou/www/job_seekers_views/views.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create_or_update.py
En voulant nettoyer/migrer les tests de création de compte candidat depuis `apply` vers `job_seekers_views`, je me suis rendu compte qu'il manquait une vérification de permission/userkind : les inspecteurs du travail et le staff Itou ne devraient pas être capables de créer de compte candidat (commit n°2).
J'ai également un peu simplifié ce qu'il se passe quand un utilisateur d'un certain type arrive sur le tunnel d'un autre type (par exemple, un `job_seeker` sur `CheckNIRForSender` ou un employeur sur `CheckNIRForJobSeeker`).
En pratique, ceci ne devrait jamais arriver, pour deux raisons :
- j'avais mis un `logger.info` qui relève quand une redirection se produit (https://github.com/gip-inclusion/les-emplois/blob/master/itou/www/job_seekers_views/views.py#L305, …
> Création de compte candidat : gestion des permissions

- itou/companies/models.py
- itou/templates/apply/submit/application/jobs.html
- itou/templates/companies/includes/_card_jobdescription.html
- itou/templates/companies/includes/_list_siae_actives_jobs_row.html
- itou/templates/companies/includes/_siae_jobdescription.html
- itou/www/apply/forms.py
- itou/www/search/views.py
- tests/companies/test_models.py
- tests/www/search/__snapshots__/tests.ambr
- tests/www/search/tests.py
https://www.notion.so/plateforme-inclusion/Le-badge-20-candidature-sur-les-r-sultats-de-recherche-ne-doit-pas-inclure-de-candidatures-archiv-e-177e8fa5c35b80e49344f093e58cf484
Les candidatures archivées (trop anciennes) ne doivent pas être comptées pour l’affichage du badge 20+ candidatures car : 
- il risque de ne jamais disparaître car ces veille candidatures ne seront jamais traitées
- il ne reflète pas l’état actuel du recrutement
- trop nombreux donc perd son impact
- Je renomme `popular` en `overwhelmed` qui est plus pertinent car l'état en question est en fait indésirable.
> Le badge 20+ candidatures sur les résultats de recherche ne doit pas inclure de candidatures archivées

- itou/templates/common/emails/member_deactivation_email_body.txt
- tests/www/companies_views/__snapshots__/test_members_views.ambr
- tests/www/companies_views/test_members_views.py
- tests/www/institutions_views/__snapshots__/test_views.ambr
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/__snapshots__/test_members.ambr
- tests/www/prescribers_views/test_members.py
Les institutions n’ont pas d’email.
> Notifications: Masquer le champ email de la structure dans l’email de désactivation de compte inspecteur du travail

- itou/gps/models.py
- itou/users/admin.py
cf https://www.notion.so/gip-inclusion/Donner-acc-s-advisor_information-sur-l-admin-1815f321b60480308e41e8155e79c4ee?pvs=4
J'ajoute un élément à la page d'admin, mais j'aurais tendance à mettre le label modifié parce que je modifie une page existante, vous êtes d'accord avec la logique ? 
J'en ai profité pour changer le `__str__` du modèle  `FranceTravailContact` car l'affichage du `JobSeekerProfile` ne me semblait pas utile vu qu'on le récupère normalement depuis cet objet. 
> Admin: Ajout du référent FT sur la page de profil de demandeur d'emploi

- itou/templates/apply/includes/list_reset_filters.html
- tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_list_for_job_seeker.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_prescriptions.py
Actuellement, quand on se met en mode tableau et qu'on ajoute des filtres (ou dans l'autre sens), si on enlève ensuite les filtres avec le bouton "Effacer tout", on est rebasculé en mode liste.
Pas trop d'idée de test par contre...
> Candidature: conserver le mode d'affichage (Tableau/Liste) quand on efface tous les filtres

- itou/common_apps/nir/forms.py
- itou/www/apply/forms.py
- itou/www/apply/views/common.py
Consolider l’implémentation de la modification du profil utilisateur.
> Utiliser JobSeekerProfileFieldMixin pour JobSeekerPersonalDataForm

- itou/asp/forms.py
- itou/templates/apply/includes/job_application_accept_form.html
- itou/users/forms.py
- itou/www/apply/forms.py
- itou/www/apply/views/common.py
- itou/www/dashboard/forms.py
- itou/www/employee_record_views/forms.py
- itou/www/employee_record_views/views.py
- itou/www/job_seekers_views/forms.py
- itou/www/signup/forms.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_forms.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
- tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
- tests/www/job_seekers_views/test_forms.py
Préambule à [empêcher la modification des informations d’un candidat qui a au moins un critère administratif certifié](https://www.notion.so/plateforme-inclusion/Emp-cher-la-modification-des-informations-d-un-candidat-qui-a-au-moins-un-crit-re-administratif-cert-47724fdc4b0a48e9ace2c305376bd21f). Centraliser la gestion de ces champs permettra de centraliser la logique de désactivation.
Les informations candidats demandées pour une embauche GEIQ diffèrent de l’IAE, pour des raisons historiques. Ces informations seront harmonisées bientôt.
https://www.notion.so/plateforme-inclusion/Pr-requis-Certification-Refonte-du-parcours-d-acceptation-de-candidature-158e8fa5c35b80959d71c3642d33512e
Vérifier la modification des données demandeur d’emploi dans les parcours …
> Demandeur d’emploi: Unifier les formulaires de gestion de données personnelles

- itou/www/apply/views/common.py
https://inclusion.sentry.io/issues/23729495/?alert_rule_id=106033&alert_type=issue&notification_uuid=65c1809b-0bc0-42b6-b93f-d765d6428375&project=4508410589020240&referrer=slack
> S’assurer que le candidat a un diagnostic valide avant d’essayer de certifier les critères d’éligibilité

- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/approvals_views/views.py
- tests/www/apply/__snapshots__/test_submit.ambr
Pour éviter qu'un utilisateur malin n'en profite.
> Vérification du type d'utilisateur pouvant accéder aux vues

- itou/templates/dashboard/dashboard.html
Pour questionner les prescripteurs et employeurs s’ils souhaitent qu’on leur propose d’autres solutions que les offres existantes.
Ajour d'un questionnaire Tally en popup
- ~**J'ai utilisé le `public_id` pour ne pas exposer la PK, qu'en pensez-vous ?**~ Finalement j'expose la PK (utilisée dans les traitements en interne) et j'affiche bien le titre
> Ajout d'une popup Tally sur la dashboard prescripteurs habilités et employeurs [GEN-2351]

- itou/www/job_seekers_views/views.py
Le bloc de recherche/création de compte candidat peut être utilisé dans plusieurs contextes (*tunnels*) différents :
- candidature
- embauche
- GPS
- et bientôt depuis l'espace Mes Candidats
Une fois qu'un compte est trouvé ou créé, l'utilisateur est redirigé vers une nouvelle page, en fonction du *tunnel*.
Cette PR est une proposition de refactorisation, pour clarifier la sortie du bloc.
Une nouvelle méthode, `get_exit_url()`, similaire à `get_next_url()` mais pour avoir l'URL de l'étape *après* le bloc. 
Elle permet d'identifier les URLs de sortie de bloc.
> Création de compte candidat: refactoriser la sortie du bloc

- itou/templates/dashboard/dashboard.html
Pour inviter les candidats sans diagnostic d’éligibilité valide et sans candidature acceptée à participer à une session d'information.
- WIP en attendant le lien
> Ajout d'un bandeau d'info pour inviter les candidats autonomes à un webinaire d'information [GEN-2409]

- itou/eligibility/admin.py
- itou/eligibility/admin_form.py
- itou/eligibility/migrations/0005_alter_administrativecriteria_created_by_and_more.py
- itou/eligibility/models/geiq.py
- itou/eligibility/models/iae.py
- tests/eligibility/admin_utils.py
- tests/eligibility/test_admin.py
L'idée est de permettre la régularisation par le support sans avoir à détourner les comptes, et en pouvant mettre un commentaire sur le diag créé.
Ça a l'inconvénient de dupliquer un peu la vérification des informations, mais je ne suis pas sur qu'envoyer sur les méthodes `create_eligibility_diagnosis` ou `create_diagnosis` soit mieux.
> Administration: correction des formulaire d'ajout et de modification de diagnostic via l'admin

- itou/www/job_seekers_views/forms.py
- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
On cache le nom des candidats qu'un prescripteur non habilité (= orienteur) n'a pas créé… sauf ici.
Avant :
Après :
> Prescripteur : masquer le nom des candidats dans le filtre de la liste des candidats

- itou/templates/gps/includes/group_members.html
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
Cela ne nous intéresse pas trop de savoir si un utilisateur affiche ses propres informations de contact 
> GPS: Ne pas masquer les informations de contact de l'utilisateur

- itou/static/css/itou.css
- itou/templates/apply/includes/accept_section.html
- itou/templates/apply/includes/buttons/rdv_insertion_invite.html
- itou/utils/staticfiles.py
- tests/www/apply/__snapshots__/test_detail_rdv_insertion.ambr
- tests/www/apply/__snapshots__/test_list_rdv_insertion.ambr
Mise a jour du thème pour :
- corriger un problème z-index des `.tooltip` dans les `.dropdown`
- modifier le fonctionnement de la classe utilitaire `.has-spinner-loading` afin qu'elle se comporte différemment selon qu'elle est appliquée sur un `<div>` ou sur un `.btn`. (Sur une idée de @leo-naeka ) [Plus de précisions dans le ZeroHeight](https://zeroheight.com/85c89893b/p/02df01-spinner)
- suppression des règles et de la classe `.has-btn-with-spinner-loading-text`, maintenant inutile car gérée dans le thème
> UX/UI: Mise a jour du thème vers la v2.6.1

- itou/eligibility/admin_form.py
- tests/eligibility/test_admin.py
Une organisation prescriptrice peut ne plus être habilitée au moment ou l'on modifie le diagnostic pour régulation.
> Admin: Correction du formulaire des diagnostics d'éligibilité.

- itou/eligibility/admin.py
- itou/eligibility/admin_form.py
- tests/eligibility/test_admin.py
Histoire d'éviter des erreurs involontaires
> Admin: Ajout d'un message warning lors de la selection d'une organisation non habilité pour un diagnostic d'éligibilité.

- itou/analytics/management/commands/collect_analytics_data.py
- itou/approvals/management/commands/prolongation_requests_chores.py
- itou/companies/management/commands/sync_pec_offers.py
- itou/employee_record/management/commands/sanitize_employee_records.py
- itou/siae_evaluations/management/commands/evaluation_campaign_notify.py
- itou/users/management/commands/pe_certify_users.py
- tests/analytics/test_collect_analytics_data_management_command.py
- tests/approvals/__snapshots__/test_prolongation_requests.ambr
- tests/approvals/test_prolongation_requests.py
- tests/companies/test_sync_pec_offers.py
- tests/employee_record/__snapshots__/test_sanitize_employee_records.ambr
- tests/employee_record/test_sanitize_employee_records.py
- tests/siae_evaluations/test_management_commands.py
- tests/users/__snapshots__/test_management_commands.ambr
- tests/users/test_management_commands.py
Toutes ces commandes sont principalement lancées par cron.
@rsebille J'ai un peu modifié les messages de `sanitize_employee_records`, dis moi si ça te semble moins clair (voir même faux :sweat_smile: ).
> Tech: migrations d'autres commandes aux logs

- itou/templates/dashboard/dashboard.html
Pour inviter les utilisateurs du Gard à découvrir GPS.
> Tableau de bord: Ajout d'un bandeau promotionnel de GPS pour le Gard [GEN-2435]

- itou/templates/apply/process_base.html
- itou/templates/apply/submit/application/base.html
- itou/templates/approvals/declare_prolongation.html
- itou/templates/approvals/prolongation_requests/show.html
- itou/templates/approvals/suspend.html
- itou/templates/approvals/suspension_action_choice.html
- itou/templates/approvals/suspension_delete.html
- itou/templates/approvals/suspension_update.html
- itou/templates/approvals/suspension_update_enddate.html
- itou/templates/companies/job_description_card.html
- itou/templates/dashboard/edit_job_seeker_info.html
- itou/templates/employee_record/summary.html
- itou/templates/geiq/assessment_info_for_employer.html
- itou/templates/geiq/assessment_info_for_labor_inspector.html
- itou/templates/geiq/assessment_review.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/templates/siae_evaluations/institution_evaluated_siae_notify_step1.html
- itou/templates/siae_evaluations/institution_evaluated_siae_notify_step2.html
- itou/templates/siae_evaluations/institution_evaluated_siae_notify_step3.html
- tests/www/apply/test_submit.py
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/geiq_views/__snapshots__/tests.ambr
- tests/www/login/__snapshots__/tests.ambr
- tests/www/siae_evaluations_views/test_institutions_views.py
Les badges sont maintenant à la droite des titres
Nous n'utilisons plus le `.text-muted` pour mettre en avant les noms des candidats/structures/etc dans les titres de pages 
https://www.notion.so/plateforme-inclusion/Passer-le-badge-de-la-section-titre-droite-dans-les-fiches-de-poste-et-les-fiches-salari-es-ASP-188e8fa5c35b80c6a676d4cf1da0a145?pvs=4
**Avant**
**Apres**
> UX/UI: Modifier l'alignement des badges et supprimer les .text-muted dans la section titre

- itou/www/approvals_views/urls.py
- itou/www/approvals_views/views.py
- tests/www/approvals_views/test_detail.py
> La redirection en objet n'est plus utile, il n'est donc pas nécessaire de la modifier dans la #5431 
> suppression
NON : Mettre à jour le CHANGELOG_breaking_changes.md ?
NON : Ajouter l'étiquette « Bug » ?
PASS IAE
> suppression de la redirection temporaire approvals:redirect_to_employee vers employees:detail

- itou/employee_record/admin.py
- itou/employee_record/exceptions.py
- itou/employee_record/management/commands/archive_employee_records.py
- itou/employee_record/management/commands/sanitize_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- itou/employee_record/migrations/0003_alter_employeerecord_status_and_more.py
- itou/employee_record/models.py
- itou/templates/employee_record/includes/list_item.html
- itou/www/employee_record_views/views.py
- tests/api/employee_record_api/tests.py
- tests/employee_record/__snapshots__/test_archive_employee_records.ambr
- tests/employee_record/__snapshots__/test_sanitize_employee_records.ambr
- tests/employee_record/factories.py
- tests/employee_record/test_admin.py
- tests/employee_record/test_archive_employee_records.py
- tests/employee_record/test_models.py
- tests/employee_record/test_sanitize_employee_records.py
- tests/employee_record/test_transfer_employee_records.py
- tests/employee_record/test_transfer_employee_records_updates.py
- tests/www/employee_record_views/test_disable.py
- tests/www/employee_record_views/test_list.py
- tests/www/employee_record_views/test_reactivate.py
- tests/www/employee_record_views/test_summary.py
Étape 1 de [Historique d’une fiche salarié](https://www.notion.so/plateforme-inclusion/Historique-d-une-fiche-salari-FS-99398b749d304d62925241f8a32259ff?pvs=4)
Je ne me suis pas trop attardé sur l'histoire des `Status` _vs._ `NotificationStatus` vu qu'à la fin il n'en restera plus qu'un, mais c'est le passage à XWorkflows qui a fait apparaître le problème dans un des tests :see_no_evil:.
La suite de tests est normalement suffisante :crossed_fingers:.
> Fiches salarié : Utilisation de XWorkflows pour gérer les états et leurs transitions

- .github/workflows/ci.yml
- .gitignore
- docker-compose.yml
- docs/environment.md
TCP has a measurable overhead for each DB query compared to the unix
socket.
https://momjian.us/main/blogs/pgblog/2012.html#June_6_2012
> Utiliser une socket UNIX pour se connecter à la base de données en dev

- itou/static/css/itou.css
- itou/static/js/utils.js
- itou/templates/apply/includes/job_applications_filters/top_filters.html
- itou/templates/apply/includes/list_job_applications.html
- itou/templates/apply/includes/list_table.html
- itou/templates/apply/includes/list_tr.html
- itou/templates/apply/includes/selected_job_applications.html
- itou/templates/apply/includes/siae_actions.html
- itou/templates/apply/includes/siae_actions_modals.html
- itou/templates/apply/list_for_siae.html
- itou/templates/apply/process_refuse.html
- itou/templates/includes/pagination.html
- itou/www/apply/forms.py
- itou/www/apply/urls.py
- itou/www/apply/views/batch_views.py
- itou/www/apply/views/list_views.py
- itou/www/apply/views/process_views.py
- tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_forms.py
- tests/www/apply/test_list_for_siae.py
> Candidature: traitement par lot [GEN-1949]

- tests/www/apply/test_submit.py
Non régression.
Le scénario a causé des 500 dans le parcours d’embauche : https://inclusion.sentry.io/issues/23729495/
Le problème a été résolu au plus vite avec a0444406ea4f8cac16f89696aa554f11b45836c7. Maintenant que la situation est stable, assurons nous de couvrir ce cas par un test.
> Tester l’embauche d’une auto-prescription d’une autre entreprise

- itou/templates/apply/email/refuse_body_for_proxy.txt
- tests/job_applications/__snapshots__/tests.ambr
- tests/job_applications/tests.py
Car c'était une pâle copie de celui envoyé au candidat : si l'on ne partageait pas le motif avec le candidat (choix par défaut), le prescripteur ne l'avait jamais dans le mail.
- Le prescripteur a toujours le motif indiqué dans son mail à présent
- On indique en plus si c'est partagé ou non avec le candidat (comme les autres items du mail)
- En reprenant les tests et couvrant mieux ce cas d'usage
> Notifications : correction du contenu de l'email envoyé aux prescripteurs lors du refus d'une candidature

- itou/static/js/duet_date_picker_widget.js
L’implémentation précédente était basée sur `UIEvent.which`, qui est dépréciée : https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which
Corriger un bug qui m’énerve depuis 2 ans, taper `01/` écrit `01//` dans le champ.
> UX/UI: Amélioration des champs de saisie de dates

- itou/templates/apply/includes/list_tr.html
- itou/templates/apply/includes/list_view_switcher.html
- itou/templates/apply/includes/siae_actions.html
- itou/templates/apply/list_for_siae.html
- itou/utils/staticfiles.py
- itou/www/apply/views/list_views.py
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_list.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_rdv_insertion.py
https://www.notion.so/gip-inclusion/Par-d-faut-afficher-la-liste-des-candidatures-en-vue-tableau-18a5f321b60481ecae82ff24b2958297?pvs=4
> Candidature: mettre la vue tableau par défaut pour les employeurs

- itou/openid_connect/pro_connect/views.py
- itou/users/adapter.py
- itou/www/apply/views/process_views.py
- itou/www/employee_record_views/views.py
- itou/www/login/views.py
Pour que nos utilisateurs ne se fassent pas piéger.
> Tech: correction des vulnérabilités de redirection ouverte

- itou/templates/apply/email/refuse_body_for_job_seeker.txt
- itou/templates/apply/email/refuse_body_for_proxy.txt
- itou/templates/apply/includes/job_application_answers.html
- itou/www/apply/forms.py
- itou/www/apply/views/batch_views.py
- itou/www/apply/views/process_views.py
Les employeurs ne sont pas toujours à l’aise avec le fait de renseigner un motif de refus, ce qui explique des candidatures non traitées. C’est plus simple de ne rien faire. 
Si on leur permet de refuser un candidat en indiquant qu’ils ne souhaitent pas renseigner de motif, traiteront-ils plus de candidatures ?
En rendant optionnel le motif de refus si l'entreprise se situe dans le Rhône, que ce soit dans le parcours unitaire ou traitement par lot.
> Candidature: Simplification du parcours de refus (expérimentation dans le Rhône) [GEN-1611]

- itou/cities/management/commands/sync_cities.py
- itou/jobs/management/commands/sync_romes_and_appellations.py
- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/metabase/management/commands/upload_data_to_pilotage.py
- itou/users/management/commands/sync_group_and_perms.py
- itou/utils/python.py
- tests/cities/tests.py
- tests/jobs/management/test_sync_romes_and_appellations.py
- tests/metabase/management/__snapshots__/test_upload_data_to_pilotage.ambr
- tests/metabase/management/test_populate_metabase_emplois.py
- tests/metabase/management/test_upload_data_to_pilotage.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
- tests/users/test_sync_group_and_perms.py
Car ces commandes sont lancées par des crons et notre logging permet de facilement regrouper les logs d'une même commande.
> Tech: migration de commandes vers l'utilisation de logging

- config/sentry.py
Car il envoie toutes les requêtes se terminant en 500 à Sentry:
https://github.com/namespace-ee/django-datadog-logger/blob/v0.7.3/django_datadog_logger/middleware/request_log.py#L41-L44
ce qui cause des rapports en double vu que Sentry aura déjà envoyé le soucis ayant causé la 500.
Cf:
https://inclusion.sentry.io/issues/14187836/
&
https://inclusion.sentry.io/issues/14187834/
> Sentry: ignorer le logger `django_datadog_logger.middleware.request_log`

- itou/common_apps/organizations/views.py
Retirer des vérifications en doublon, et commencer la vue par les contrôles d’accès.
> Simplifier update_admin_role

- itou/common_apps/organizations/models.py
- itou/common_apps/organizations/views.py
Faciliter les mises à jour futures.
> Réusinage de l’activation/désactivation du statut administrateur d’un membre d’une organisation

- itou/common_apps/organizations/views.py
- itou/www/companies_views/views.py
- itou/www/institutions_views/views.py
- itou/www/prescribers_views/views.py
- tests/www/companies_views/test_members_views.py
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/test_members.py
Afin d’éviter des cas limite, l’application indique maintenant 404 si le membership de l’utilisateur à désactiver n’est pas actif.
Petit réusinage nécessaire pour partager le code entre les différentes vues, indiquer le résultat d’une opération par un booléen a ses limites.
> Correction des vues deactivate_member

- itou/www/apply/views/batch_views.py
- tests/www/apply/test_batch_views.py
Pour les champs optionnels, valider le formulaire n'est pas suffisant.
On vérifie donc d'abord l'existence des infos de l'étape.
Cela corrige un test flaky qui échouait quand le département du Rhone était tiré au sort.
> Tech: amélioration de la détection des étapes précédentes manquantes

- itou/users/management/commands/extract_c2_users.py
Carte Notion : https://www.notion.so/gip-inclusion/Script-Extraites-Utilisateurs-1895f321b60480eb8d5accbfb4d28e1f
La modification d'un script pour faciliter les devs à exporter des CSVs des données utilisateurs pour le métier.
J'ai modifié la commande d'export existant pour ajouter des nouveaux données. J'ai inclus deux paramètres optionnels parce que les données démandé par le métier peuvent varier.
C'était discuté, mais je n'ai pas ciblé la possibilité des filtres sur les données (par example par département ou par date) pour minimiser les changements de ce PR dans la contexte qu'ils font pas partie des besoins du moment, et c'est possible que ça ne va pas arriver pendant les prochains 6 mois.
* Ajouter aux données standards deux organisations prescripteurs (un ODT et un DEPT)
* Lancer …
> Pilotage: Étendre commande extract_c2_users avec plus des données

- itou/gps/admin.py
- tests/gps/test_admin.py
Pour permettre de donner une date logique de début de suivi aux groupes créés manuellement.
Vu la faible sensibilité de cette date, je l'ai rendue accessible tout le temps pour simplifier la fonctionnalité (pas besoin de ne le faire que pour la création et la modification de membership créées manuellement)
> Admin: Permettre de modifier la date de début de suivi d'un membre de groupe GPS

- tests/invitations/factories.py
- tests/invitations/tests.py
- tests/www/invitations_views/test_helpers.py
- tests/www/invitations_views/test_prescriber_organization.py
Suivre la convention établie pour les entreprises et institutions.
> Renommer PrescriberWithOrg{Sent,}InvitationFactory

- itou/templates/dashboard/dashboard.html
Retrait du bandeau le 4 février 14h
Refs #5464
> Tableau de bord: Retrait du bandeau pour inviter les candidats autonomes à un webinaire d'information

- itou/templates/dashboard/dashboard.html
Retrait du bandeau le 4 février 14h
Refs #5495
> Tableau de bord: Retrait du bandeau promotionnel de GPS pour le Gard

- itou/templates/job_seekers_views/step_search_job_seeker_by_email.html
- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
Une modale s'affiche lorsqu'on trouve un compte candidat à partir de son NIR ou de son adresse email.
Cette modale s'affiche dans différents contextes (candidature, GPS, …) et devient assez complexe.
Testons son contenu.
> Tests : vérifier le contenu de la modale confirmant un candidat trouvé par son NIR ou son email

- tests/gps/test_create_beneficiary.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
`assertContains` teste également le `status_code`, pas besoin de rappeler `assert response.status_code == 200`.
De même, `assertRedirects` vérifie que `status_code == 302`, et il est inutile de rappeler `assert response.url == next_url`.
Nettoyage effectué dans `apply`,  `job_seekers_views` et `gps`.
> Tests : retrait des assertions dupliquées assertContains et assertRedirects

- itou/templates/apply/includes/buttons/refuse.html
- itou/templates/apply/process_refuse.html
- itou/www/apply/urls.py
- itou/www/apply/views/batch_views.py
- itou/www/apply/views/process_views.py
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_process.py
Les deux parcours sont censés suivre la même logique.
> Candidature: réutilisation du traitement par lot pour le refus d'une seule candidature

- itou/utils/staticfiles.py
La classe utilitaire appliquée pendant les requêtes htmx (.has-spinner-loading) sur un `.form-swith` (ou sur un parent contenant un ` .form-swith`) méritait une amélioration visuelle
Ajout de règles css spécifiques à ce cas
ici -> https://c1-review-deloo-fix-has-spinner-on-switch.cleverapps.io/company/job_description_list
**Avant**
**Apres**
> UX/UI: Correction UI du spinner sur les switch

- itou/files/management/commands/sync_s3_files.py
- tests/files/tests.py
Pour être alerté que l'on fournit des liens vers des objets n'existant pas.
> Tech: ajout d'une option pour alerter sur des fichiers ayant disparu de notre bucket

- itou/www/employee_record_views/views.py
- tests/www/employee_record_views/test_add.py
Correction de #5541 (https://inclusion.sentry.io/issues/28983753/?project=4508410589020240)
> Technique: Correction d'une regression apportée par #5541

- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
La page `job-seekers/list` est très lente.
Le planificateur de postgresql a du mal à comprendre ce qu'il se passe : https://gip-inclusion.slack.com/archives/C0412CTV63D/p1738926763619239?thread_ts=1738837725.145859&cid=C0412CTV63D
En découpant un peu les requêtes, ça devrait mieux passer.
> Performances : amélioration des requêtes pour la liste des candidats

- itou/utils/apis/pole_emploi.py
- tests/jobs/management/test_sync_romes_and_appellations.py
- tests/utils/apis/test_pole_emploi_api.py
L'ancien scope `api_romev1` ne semble plus valide (cf https://francetravail.io/produits-partages/catalogue/rome-4-0-metiers/documentation#/api-reference/)
Et l'endpoint est maintenant sur un autre chemin: https://francetravail.io/produits-partages/catalogue/rome-4-0-metiers/documentation#/api-reference/operations/listerAppellations
> Tech: mise à jour de notre code pour rester compatible avec l'API ROME de FranceTravail

- .github/workflows/ci.yml
- .github/workflows/mkchangelog.yml
- .github/workflows/review-app-creation.yml
- .github/workflows/review-app-removal.yml
- CHANGELOG_breaking_changes.md
- Makefile
- docker-compose.yml
- itou/openid_connect/models.py
- itou/users/enums.py
- itou/www/login/views.py
- pyproject.toml
- runtime.txt
- tests/users/test_enums.py
- tests/www/login/tests.py
Rester à jour, aller plus vite, un meilleur debug et plein de trucs chouette !
> MàJ vers Python 3.13

- tests/utils/test_templatetags.py
tester ave `reverse()` ne permet pas de mettre des vus qui prennent des paramètres dans l'url.
> Tests: Améliorer les tests du menu de navigation

- itou/users/management/commands/extract_c2_users.py
Suite à https://github.com/gip-inclusion/les-emplois/pull/5498, on veut ajouter le nom de l'organisation à l'extrait
`python manage.py extract_c2_users --include-institutions --include-prescribers --include-siae`
> Pilotage: Ajout du nom au extrait utilisateurs

- itou/www/apply/views/process_views.py
- tests/www/apply/test_process.py
il n'est alors plus possible de rediriger vers l'espace candidat quand c'est de là que l'utilisateur est arrivé?
> Stabilité: Correction d'une redirection cassée après avoir annulé une embauche [GEN-2188]

- itou/companies/management/commands/update_companies_coords.py
- itou/users/management/commands/update_job_seeker_coords.py
- tests/companies/test_management_commands.py
- tests/users/test_management_commands.py
Suite à cette remontée: https://github.com/gip-inclusion/les-emplois/security/code-scanning/129
Seules ces 2 commandes utilise ce code, et effectivement c'est mieux que ça ne finisse pas en print dans les données collectées par clever.
Je le rend facultatif pour permettre d'afficher les données en local lors de tests manuels (qui on a priori permis à victor de faire ces stats à l'époque).
Je me demande si on ne peut pas désormais supprimer update_companies_coords maintenant que c'est fait automatiquement à chaque modification dans l'admin :thinking: 
> _Les instructions pour reproduire le problème, …
> RGPD: Ne pas mettre les adresses géolocalisées par les management commands dans la sortie standard

- config/settings/base.py
- itou/api/errors.py
- tests/api/test_error.py
Quand notre API plante, rien ne sert de renvoyer une page HTML. D'autant plus quand elle plante: https://inclusion.sentry.io/issues/29358189/
> API: amélioration de notre réponse d'erreur

- itou/common_apps/organizations/admin.py
- itou/common_apps/organizations/models.py
- itou/invitations/migrations/0001_initial.py
- itou/invitations/models.py
- itou/www/institutions_views/views.py
- tests/companies/test_admin.py
- tests/companies/test_models.py
- tests/institutions/tests.py
- tests/prescribers/tests.py
- tests/www/companies_views/test_members_views.py
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/test_members.py
- tests/www/signup/test_prescriber.py
Sécurité.
https://yeswehack.com/vulnerability-center/reports/310822
> Empêcher les membres d’une structure de s’y maintenir via des invitations

- itou/www/stats/views.py
Deux vues qui tentent de transmettre toutes les entreprises d'un utilisateur au TB peuvent essayer d'inclure des entreprises non SIAE, ce qui entraîne une `AttributeError` sur`company.convention` pour les utilisateurs affiliés à des non-SIAEs.
J'ai testé à la main avec le processus suivant :
* Ajouter un utilisateur employeur de SIAE à une enterprise adaptée, en tant que administrateur.
* Se connecter à ce compte
* Visiter http://localhost:8000/stats/siae/orga_etp, avant et après l'application du fix
* Visiter http://localhost:8000/stats/siae/etp où le bug est également possible
> Pilotage: Correction de crash sur les TdBs ETP quand un utilisateur est aussi membre des non-SIAEs

- itou/approvals/admin.py
- itou/employee_record/management/commands/employee_records_status.py
- itou/job_applications/models.py
- itou/templates/employee_record/add.html
- itou/templates/employee_record/list.html
- itou/www/employee_record_views/forms.py
- itou/www/employee_record_views/views.py
- tests/approvals/tests.py
- tests/job_applications/tests.py
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_list.ambr
- tests/www/employee_record_views/test_add.py
- tests/www/employee_record_views/test_list.py
> Fiches salarié: Faciliter la saisie des nouvelles fiches salariés [GEN-749]

- docs/environment.md
Inutilisées depuis 22dfb9f11516bc5159771b2e2b8578958b5e0474.
> docs: Retirer des références aux variables Mailjet pour le compte principal

- itou/employee_record/admin.py
- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- itou/employee_record/migrations/0004_employeerecordtransitionlog.py
- itou/employee_record/models.py
- itou/templates/admin/employee_records/employeerecord_change_form.html
- itou/www/employee_record_views/views.py
- tests/api/employee_record_api/tests.py
- tests/employee_record/__snapshots__/test_admin.ambr
- tests/employee_record/test_admin.py
- tests/employee_record/test_models.py
- tests/www/employee_record_views/test_create.py
- tests/www/employee_record_views/test_disable.py
- tests/www/employee_record_views/test_list.py
- tests/www/employee_record_views/test_reactivate.py
- tests/www/employee_record_views/test_summary.py
Comprendre ce qui a été fait et par qui pour en déduire ce qui fonctionné ou non pour la résolution de la problématique.
Log des transitions XWorflows
Avec la suite de test.
> Fiches salarié : Historique des transitions [GEN-384]

- itou/templates/gps/my_groups.html
- itou/templates/utils/templatetags/nav.html
- itou/utils/templatetags/nav.py
- itou/www/dashboard/views.py
- itou/www/gps/views.py
- tests/gps/__snapshots__/test_views.ambr
- tests/gps/test_views.py
- tests/www/__snapshots__/test_layout.ambr
- tests/www/dashboard/__snapshots__/test_dashboard.ambr
- tests/www/dashboard/test_dashboard.py
https://www.notion.so/gip-inclusion/Parcours-d-acc-s-GPS-dans-le-Gard-menu-lat-ral-dashboard-bandeau-info-sur-la-liste-1915f321b60480d88b65d90d3d3ff6f9?pvs=4
> GPS: Ajouter une section au menu de gauche pour les pros du Gard

- itou/prescribers/admin.py
- itou/users/admin.py
- tests/prescribers/tests.py
- tests/users/__snapshots__/test_admin_views.ambr
This way, we only allow it on the organization page.
We now need to handle the following issue : for organization with more than 250 members, we have more than DATA_UPLOAD_MAX_NUMBER_FIELDS limit of 1000.
We could make all the inlined memberships readonly ig there are too many and allow to change them from the user detail page ?
Or handle the memberships from a dedicated page that we filter from the url (?user=X or ?company=Y)
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. Si vous disposez d'une recette jetable, mettre l'URL pour tester …
> Admin: Amélioration de la gestion des appartenances aux organisations

- itou/eligibility/tasks.py
- itou/utils/apis/api_particulier.py
- tests/eligibility/factories.py
- tests/eligibility/test_geiq.py
- tests/eligibility/test_iae.py
- tests/eligibility/test_tasks.py
- tests/job_applications/tests.py
- tests/utils/apis/test_api_particulier.py
- tests/www/apply/test_process.py
- tests/www/apply/test_templates.py
A l’instar du critère BRSA on veut interroger l’API Particuliers pour certifier le critère AAH.
AAH est un critère pour lequel on demande un justificatif de < de 3 mois.
Règles identiques au critère RSA.
En tant que SIAE, réaliser une auto-prescription avec un critère AAH.
> [GEN-557] Candidature : préparation à la certification AAH

- config/settings/base.py
Sinon, `huey` rajoute un `StreamHandler` sur son logger, cf:
- https://github.com/coleifer/huey/blob/2.5.2/huey/contrib/djhuey/management/commands/run_huey.py#L87-L88
- https://github.com/coleifer/huey/blob/2.5.2/huey/consumer_options.py#L147-L170
alors même que les logs sont propagés au logger racine et ses handlers.
On se retrouve alors avec des logs en double dont l'un n'est pas du JSON [polluant fortement nos logs](https://app.datadoghq.eu/logs?query=service%3Aitou-prod&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1739304820000&to_ts=1739304840000&live=false) lorsqu'il y a des tracebacks.
> _Décrivez en quelques mots la solution …
> Tech: correction de configuration des logs `huey`

- docs/javascript.md
- itou/static/js/utils.js
- itou/templates/apply/includes/list_view_switcher.html
- itou/templates/apply/includes/selected_job_applications.html
- migrations.md
- tests/www/apply/test_list_for_siae.py
Pour plus facilement identifier qui fournit le mécanisme utilisé.
> JS: migration à data-emplois- pour notre "setter"

- config/settings/base.py
Un warning indique une migration à venir.
Doc correspondante :
https://docs.allauth.org/en/latest/release-notes/recent.html#:~:text=The%20setting%20ACCOUNT_AUTHENTICATION_METHOD:%20str,This%20change%20is%20performed%20in%20a%20backwards%20compatible%20manner.
> MàJ d’un setting pour django-allauth 65.4.0

- itou/www/dashboard/forms.py
- tests/www/dashboard/__snapshots__/test_edit_job_seeker_info.ambr
- tests/www/dashboard/__snapshots__/test_edit_user_info.ambr
Mutualiser les comportements et simplifier.
> Réutiliser JobSeekerProfileForm dans EditJobSeekerInfoForm [GEN-1380]

- itou/templates/job_seekers_views/step_check_job_seeker_nir.html
- itou/templates/job_seekers_views/step_search_job_seeker_by_email.html
- itou/users/models.py
- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_create_or_update.ambr
- tests/www/job_seekers_views/test_create_or_update.py
Lorsqu'on insère un NIR ou une adresse mail au début du parcours de création de compte candidat, une modale apparaît lorsqu'un candidat correspond à ce NIR ou cette adresse email.
Dans le cas d'une création de compte candidat sans candidature, il a plusieurs sous-cas :
- le candidat existe déjà et est présent dans la liste "Mes candidats"
- le candidat existe déjà et n'est pas présent dans la liste
La présente PR ajoute ces deux cas à cette modale.
- en tant que prescripteur (habilité ou non), créer un compte candidat depuis la liste de "Mes candidats" grâce au bouton dédié
- insérer le NIR d'un compte existant
- soit absent de la liste Mes candidats
- soit présent dans la liste parce que créé par l'utilisateur en cours
- soit présent dans la liste parce que créé par un membre de …
> Prescripteur : amélioration de la modale confirmant qu'un candidat existe déjà avec ce NIR ou cet email [GEN-2198]

- itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
Suite à des retours utilisateurs, nous voulons changer le wording du filtre
login employeur > candidatures > tous les filtres
Avant, en démo :
Après, en local :
> [GEN-2208] Changement d’intitulé pour le filtre des candidatures archivées

- itou/templates/common/tables/th_with_sort.html
- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/job_seekers_views/list.html
- itou/utils/staticfiles.py
- itou/www/job_seekers_views/enums.py
- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_enums.py
- tests/www/job_seekers_views/test_list.py
> Prescripteur: ajout de tri dans la liste des candidats [GEN-1844]

- itou/approvals/models.py
`now` est en UTC donc `now.date()` & `localdate(now)` ne renvoie pas la même chose aux alentours de minuit.
Donc entre minuit & 1h (et bientôt entre minuit & 2h), le temps qu'UTC rattrape CEST, on sélectionne des PASS démarrant aujourd'hui et qui se font tout de suite retoquer avant d'être réessayé 5 minutes plus tard.
> PASS IAE: correction du code empêchant l'envoi d'un PASS avant sa date de début

- itou/approvals/models.py
- tests/approvals/tests.py
Actuellement, on ne met à jour que les attributs ayant une valeur (`{key: value for key, value in update_dict.items() if value}`).
Ce qui signifie que:
- `pe_save_success` n'efface pas les champs `pe_notification_endpoint` ou `pe_notification_exit_code`
- `pe_save_pending`  met à jour `pe_notification_exit_code` sans mettre à jour `pe_notification_endpoint`
- etc
avec des incohérences à la clef.
> Tech: simplification du code de mise à jour de l'état de synchronisation d'un PASS IAE vers France Travail

- itou/www/job_seekers_views/enums.py
- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Si 2 candidats ont les mêmes noms & prénoms, ou plus simplement, le même nombre de candidature le tri:
- doit être stable dans le temps
- doit bien s'inverser si l'ordre sélectionné est inversé
> Candidat: stabilisation du tri en cas d'égalité

- itou/templates/employee_record/includes/create_step_4.html
- itou/www/employee_record_views/forms.py
- tests/www/employee_record_views/test_create.py
Nous n’avons toujours pas reçu les AF de 2025 pour toutes les SIAE (prévu pour Avril), chaque année on les reçoit avec beaucoup de retard.
Cela est gênant pour les SIAE qui utilisent un logiciel de gestion car à l’étape 4 du parcours des fiches salarié la sélection d’une AF est un prérequis à la transmission de la donnée Fiche salarié vers le logiciel de gestion RH, par conséquent cela génère une double saisie pour nos utilisateurs.
> Fiches salarié : Autoriser les employeur à séléctionner une annexe financière non valide [GEN-2245]

- itou/templates/dashboard/includes/stats.html
- itou/utils/apis/metabase.py
- itou/www/stats/urls.py
- itou/www/stats/views.py
- tests/www/dashboard/__snapshots__/test_dashboard_stats.ambr
La DGEFP ne peut pas accéder à ses TBs privés car on touche la limite pour la longueur d'une URL à cause des filtres géographiques, les nouveaux TB ont été dupliqué afin de supprimer ces filtres.
https://www.notion.so/gip-inclusion/Corriger-le-bug-associ-aux-TBs-DGEFP-1985f321b6048049b235df2cfaec9533
> Pilotage : Corriger le bug associé aux TBs DGEFP

- config/settings/base.py
- itou/templates/apply/includes/buttons/rdv_insertion_promote.html
- itou/templates/apply/includes/siae_hiring_actions.html
- itou/www/apply/views/process_views.py
Car on n'a pas eu de soumission aux Tally depuis hier !
On étend à d'autres départements (tout Auvergne Rhône-Alpes) et à la page de détail des candidatures.
> Candidature: extension de l'affichage du bouton de promotion [GEN-2235]

- .github/workflows/review-app-creation.yml
- .github/workflows/review-app-removal.yml
Car le nom de ma branche pour #5687 est trop longue :
```
❯ echo -n "c1-review-rsebille-er-creation-without-completion-for-future-hiring" | wc -c
67
❯ echo -n "c1-review-rsebille-er-creation-without-completion-for-future-hi" | wc -c
63
```
J'ai corriger la variable dans clever et le déploiement est passé.
> Recettes jetable : Limiter le nom à 63 caractères

- itou/templates/employee_record/includes/create_step_4.html
La mention est affichée alors qu'il n'y a pas de champs obligatoire à cette étape.
Avant :
Après :
> Fiches salarié : retirer la mention champs obligatoire de l’étape de sélection des Annexes financières  dans le parcours des fiches salarié [GEN-2213]

- itou/templates/dashboard/includes/staff_export_card.html
Problème : le titre comité technique d’animation n’est pas explicite
en le remplaçant par “ Export des prescripteurs et employeurs”
Avant :
Après :
> Tableau de bord (équipe support uniquement) : modifier le nom “comité technique d’animation” par “export des prescripteurs et employeurs” [GEN-2209]

- clevercloud/cron.json
- itou/users/management/commands/new_users_to_brevo.py
- itou/users/management/commands/send_users_to_brevo.py
- tests/users/test_management_commands.py
Mieux accompagner les candidats :
- à leur inscription
- autonomes bloqués
> Alimenter les listes de contacts Brevo avec certains profils candidats [GEN-1400]

- .gitignore
Postgis ne distribue qu'une image `amd64` de postgres sur DockerHub. Il y a 2-3 semaines j'ai build une image `aarch64` et l'utilise depuis pour éviter d'émuler l'archi x86 en local.
Grâce à ce fichier, je ne surcharge que l'image du service postgres.
Le gain en perfs est négligeable lorsqu'on lance un test spécifique, mais lorsqu'il s'agit de toute la batterie de tests, ça représente bien 15-20% de gain avec 14 workers.
> Performances: Ajout de docker-compose.override.yml au .gitignore

- scripts/delete-bucket
Depuis l'activation du versionning des objets S3, les buckets ne sont plus supprimés correctement sur les review apps si des fichiers avaient été chargés.
En utilisant `list_object_versions` au lieu de `list_objects_v2`
> Stabilité: Correction du script de suppression des buckets

- itou/approvals/migrations/0011_allow_more_status_for_employee_record_notifications.py
- itou/approvals/models.py
- itou/employee_record/admin.py
- itou/employee_record/management/commands/sanitize_employee_records.py
- itou/employee_record/models.py
- tests/employee_record/__snapshots__/test_admin.ambr
- tests/employee_record/__snapshots__/test_sanitize_employee_records.ambr
- tests/employee_record/test_admin.py
- tests/employee_record/test_models.py
- tests/employee_record/test_notifications.py
Commits :
1. Plus simple pour les échanges et la compréhension général
2. On se retrouvais à avoir 2 boutons, autant blinder la chose et faire comme le système aurais fait
3. Évite une manipulation en plus quand on désarchive depuis l'admin
4. On est jamais à l’abri d'une surprise, donc autant qu'un changement sur les statuts soit visible là où ils sont utilisés
5. `SENT` car on peux tomber dans le cas où la FS est en cours d'envoi et que le PASS est modifié. `DISABLED` on suppose qu'elle a été intégrée, au pire on aura une erreur, mais l'idée est que c'est plus embêtant d'en rater une que d'en faire une de trop.
6. Car... Comment dire... J'ai été clenché, OK ! :angel: 
La suite de test couvre les cas normalements
> Fiches salarié : Améliorations pour le désarchivage et la création automatique des notifications

- itou/static/js/utils.js
- itou/templates/apply/includes/job_applications_filters/offcanvas.html
- itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
- itou/templates/apply/includes/list_reset_filters.html
- itou/templates/apply/includes/list_table.html
- itou/templates/apply/list_for_job_seeker.html
- itou/templates/apply/list_for_siae.html
- itou/templates/apply/list_prescriptions.html
- itou/templates/common/tables/th_with_sort.html
- itou/utils/ordering.py
- itou/www/apply/views/list_views.py
- itou/www/job_seekers_views/enums.py
- tests/www/apply/__snapshots__/test_list_for_job_seeker.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_list.py
- tests/www/apply/test_list_for_job_seeker.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_prescriptions.py
> Candidature: ajout du tri sur les listes de candidatures [GEN-2248]

- itou/job_applications/enums.py
- itou/job_applications/migrations/0001_initial.py
[notion](https://www.notion.so/gip-inclusion/Refus-automatique-2-3-Ajout-d-un-nouveau-motif-de-refus-Refus-automatique-1ab5f321b60480068bf8debadffc12cf)
🍰 ajout d'un motif de refus pour les candidatures, non accessible dans le formulaire de refus des employeurs. 
🍦 Ajout dans l'enum `RefusalReason` et dans la liste des raisons de la classe `hidden`
🍦 pas de blocage dans l'admin
☑️   Mettre à jour le CHANGELOG_breaking_changes.md ?
☑️   Ajouter l'étiquette « Bug » ?
> Candidature: Ajout d’un nouveau motif de refus “Refus automatique” [GEN-2298]

- itou/templates/includes/deactivate_member.html
- itou/templates/includes/members.html
- itou/templates/includes/update_admin.html
- itou/www/companies_views/urls.py
- itou/www/companies_views/views.py
- itou/www/institutions_views/urls.py
- itou/www/institutions_views/views.py
- itou/www/prescribers_views/urls.py
- itou/www/prescribers_views/views.py
- tests/www/companies_views/test_members_views.py
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/test_admins.py
- tests/www/prescribers_views/test_members.py
> les urls des `companies_views`, `prescribers_views` et `institutions_views` permettent l'accès à la gestion des membres (ajout, mise à jour, suppression) à partir de l'`id` incrémental du `user`
Employeur, Prescripteur, Institutions
🦺  remplacer les `id` par les `public_id`
🦺 ajout de 3 routes temporaires pour le deploiement `zero downtime`
🦺 simplification de routes utilisant `re_path`, pour supprimer les `regex` sur les `uuid`
-  Mettre à jour le CHANGELOG_breaking_changes.md ? > Non
[ref notion](https://www.notion.so/plateforme-inclusion/IDOR-securiser-les-urls-de-gestion-des-membres-des-compagnies-prescripteurs-et-institutions-181e8fa5c35b809e856ff155eb792a75?pvs=4)
> Admin: sécurisation des urls de gestion des membres [GEN-2399]

- config/settings/test.py
Cela permet aux tests de passer même quand on a `FORCE_PROCONNECT_LOGIN=False` dans notre environnement de dev.
> Modifier la valeur de FORCE_PROCONNECT_LOGIN en tests

- .github/workflows/require-labels.yml
Le correctif de https://github.com/mheap/github-action-required-labels/issues/66 est dispo depuis la 5.5.0, et ça tombe bien c'est la version qu'on utilise ;).
> github : Lancer `require-labels` quand une PR est mis dans la merge queue

- itou/templates/employees/detail.html
- itou/www/employees_views/views.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/employees_views/test_detail.py
La mise en place de l’encart IF sur la page salarié ne semble pas avoir d’impact sur les sorties positives. Nombre de visites très faible. 243 depuis début octobre. Taux de conversion à 0,6% sur 2024. ( 1 demande d’immersion au total sur 2024)
On l’affiche sur toutes les pages salarié et pas seulement celles dont les PASS arrivent à expiration dans moins de 90 jours.
Techniquement on passe de 2 à 3 cas, voir plus bas.
>  Profil salarié : afficher l’encart Immersion Facilitée de la page de tous les salariés [GEN-355]

- clevercloud/cron.json
- itou/job_applications/enums.py
- itou/job_applications/management/commands/reject_job_applications_after_delay.py
- itou/job_applications/models.py
- itou/job_applications/notifications.py
- itou/templates/apply/refusal_messages/auto.txt
- tests/job_applications/__snapshots__/test_reject_job_applications_after_delay.ambr
- tests/job_applications/test_reject_job_applications_after_delay.py
- tests/job_applications/tests.py
suite #5726 
réduire le taux de candidature sans réponse.
🍣  Refuser automatiquement avec un message adapaté, les candidatures non mises à jour depuis plus de 2 mois, à l'état 'nouvelle' ou 'à l'étude'
🥑  Seuls les demandeurs d'emploi sont notifiés, les prescripteurs ne le sont pas dans un premier temps pour éviter de spammer leur boite mail.
🌪️ Dans la mesure du possible, toutes les candidatures éligibles d'un même candidat sont traitées dans le même batch, même si des candidatures plus anciennes restent en attente.
Lancer la management command `reject_job_applications_after_delay`
liste des candidatures
detail candidature
historique de la candidature
> Candidatures: Décliner toutes les candidatures sans réponse (nouvelle + à l’étude) depuis plus de 2 mois [GEN-2294]

- itou/approvals/admin.py
- tests/approvals/tests.py
Il faut passer par le lien `Délivrer un PASS IAE dans l'admin` de la page d'une candidature.
Personne n'a utilisé ce lien depuis plus de 6 mois, donc ça ne bloquera personne.
Ce changement accompagne #5757 et fait suite à [cette discussion](https://gip-inclusion.slack.com/archives/C0412CTV63D/p1726462099832469) de septembre 2024 :see_no_evil: 
> admin: Forcer la création manuelle de PASS IAE via la procédure prévue

- itou/templates/apply/includes/eligibility_badge.html
- itou/templates/apply/submit/application/base.html
- itou/templates/apply/submit/hire_confirmation.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/templates/job_seekers_views/includes/list_results.html
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
L'option `force_valid=True` des badges d'éligibilité permet de masquer une partie de l'information pour simplifier la vue aux employeurs.
Cependant, les badges sont également utilisés pour les prescripteurs, et on voudrait leur afficher plus de détails (`force_valid=False`).
> Gabarits : passer systématiquement `force_valid` aux badges d'éligibilité

- itou/approvals/admin.py
- itou/approvals/admin_forms.py
- tests/approvals/tests.py
Pour retirer des champs a priori pas utiles, et pouvant causer des incohérences.
en attente d'une réponse à https://gip-inclusion.slack.com/archives/C02J7LWNT6Z/p1741846061560809
> Admin: Limiter les modifications de PASS IAE

- itou/www/approvals_views/urls.py
- itou/www/approvals_views/views.py
- itou/www/companies_views/urls.py
- itou/www/companies_views/views.py
- itou/www/institutions_views/urls.py
- itou/www/institutions_views/views.py
- itou/www/prescribers_views/urls.py
- itou/www/prescribers_views/views.py
- tests/www/approvals_views/test_detail.py
- tests/www/approvals_views/test_display.py
- tests/www/companies_views/test_members_views.py
- tests/www/institutions_views/test_views.py
- tests/www/prescribers_views/test_members.py
Des urls de redirection sur le `pk` de l'instance ont été déployées pour assurer un déploiement sans interruption des `urls` du scope des IDOR. Ces redirections ne sont plus utiles. 
suppression des routes, des vues et des tests associées
[notion](https://www.notion.so/gip-inclusion/V-rifier-les-IDOR-et-contr-les-d-acc-s-18a5f321b604810cbd53ef9f584801c3)
> IDOR: suppression des redirections temporaires

- itou/job_applications/models.py
- itou/templates/apply/includes/job_applications_filters/eligibility.html
- itou/templates/apply/includes/job_applications_filters/offcanvas_body.html
- itou/templates/apply/includes/job_applications_filters/pass.html
- itou/www/apply/forms.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_prescriptions.py
Aujourd’hui, on a ça, il manque la case “Eligibilité à valider” et le statut du PASS IAE “expiré” :
**Dans Eligibilité IAE :**
On ajoute une case “A valider”
On renomme “Eligibilité validée” en “Valide”
**Dans statut du PASS IAE :**
On ajoute une case “Expiré”
Résultat : 
Je ne suis historiquement ni familier ni à l'aise avec la logique assez complexe des PASS et diagnostics. Du coup cette PR est un bon exercice pour moi, mais attention des choses restent floues pour moi, je m'explique ci-dessous.
Je recommande de lire chacun des deux commits séparement. Ce ticket regroupe deux nouveaux filtres qui sont techniquement complètement indépendants.
Je me base sur un `filters.append(Q(approval__end_at__lt=timezone.localdate()))`.
En pratique cela montre bien les candidatures des candidats qui …
> Candidature : Modification des filtres Eligibilité IAE et PASS IAE dans la liste de candidatures [GEN-1182]

- itou/job_applications/models.py
- itou/users/models.py
- itou/www/apply/forms.py
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_list_for_siae.py
Le filtre `eligibility_validated` n'était utilisé que pour filtrer les *candidatures*.
On en a à présent besoin pour les *candidats* également, et cela a plus de sens de positionner cette méthode du côté des candidats.
On définit donc `UserQueryset`.
> Querysets : refonte du filtre `eligibility_validated`

- itou/utils/hijack/views.py
- tests/utils/perms/tests.py
- tests/utils/test_hijack.py
Pour éviter de devoir saisir le code OTP après chaque hijack
> Admin: améliorer la prise en charge du 2fA lors du détournemet d'identité

- itou/static/js/htmx_dropdown_filter.js
- itou/templates/includes/btn_dropdown_filter/checkboxes.html
- itou/templates/job_seekers_views/includes/job_seekers_filters/single_checkbox.html
- tests/www/apply/test_list_for_job_seeker.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_prescriptions.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Une contribution au grand renommage/préfixage de notre JS : https://github.com/gip-inclusion/les-emplois/commit/fbe4e43828a82380f41fb4175691fb70806a428e
> JS : utiliser le préfixe data-emplois- pour la synchronisation des checkboxes

- itou/metabase/tables/approvals.py
- itou/metabase/tables/companies.py
- itou/metabase/tables/criteria.py
- itou/metabase/tables/evaluated_criteria.py
- itou/metabase/tables/evaluated_job_applications.py
- itou/metabase/tables/evaluated_siaes.py
- itou/metabase/tables/evaluation_campaigns.py
- itou/metabase/tables/gps.py
- itou/metabase/tables/institutions.py
- itou/metabase/tables/job_descriptions.py
- itou/metabase/tables/memberships.py
- itou/metabase/tables/prolongation_requests.py
- itou/metabase/tables/prolongations.py
- itou/metabase/tables/users.py
- itou/metabase/tables/utils.py
Avec ce changement on peut supprimer la patterne d'implementer un `get_field` clone pour chaque table de l'import Metabase.
> Pilotage: Ajout d'un fonction utilitaire pour l'accès au champ d'un modèle donnée

- itou/templates/employee_record/add.html
- itou/templates/employee_record/includes/list_header.html
- itou/templates/employee_record/includes/list_results.html
- itou/templates/employee_record/list.html
- itou/www/employee_record_views/views.py
- tests/www/employee_record_views/__snapshots__/test_add.ambr
- tests/www/employee_record_views/__snapshots__/test_list.ambr
- tests/www/employee_record_views/test_add.py
Actuellement l'URL n'a pas de `reset_url` et se termine donc pas une 404.
Ajouter dans 54451cdf7 suite à #5736.
> Fiches salarié : Correction de l'URL du bouton "Créer une fiche salarié"

- itou/templates/apply/includes/eligibility_badge.html
- itou/templates/job_seekers_views/includes/list_results.html
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
Les badges dans les tableaux devraient avoir la taille XS.
https://github.com/gip-inclusion/les-emplois/pull/5790#discussion_r2000457981
> UX/UI : Réduire la taille des badges dans le tableau des demandeurs d’emplois des prescripteurs

- itou/users/models.py
- itou/www/job_seekers_views/views.py
- tests/users/test_models.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/job_seekers_views/test_list.py
Faisant suite à la discussion du début de semaine sur la liste de candidats dans les 2 onglets.
Je propose de modifier les candidats affichés dans l'onglet `Tous les candidats de ma structure` pour n'avoir que ceux effectivement concernés pas des actions réalisés dans cette structure.
Actuellement :
- Dans l'onglet "Mes candidats" on a:
- les candidats que j'ai créé (quelque soit l'orga sélectionnée)
- les candidats pour lesquels j'ai postulé (quelque soit l'orga sélectionnée)
- Dans l'onglet "tous les candidats de la structure" on a :
- les candidats que j'ai créé (quelque soit l'orga sélectionnée)
- les candidats créés par un membre de mon orga (aka en ayant sélectionné cette orga)
- les candidats avec une candidature envoyée par mon organisation
- les candidats avec une candidature …
> Prescripteur: Améliorer la liste des candidats affichés dans l'onglet  "Tous les candidats de ma structure"

- itou/templates/companies/card.html
- itou/templates/companies/includes/_card_siae.html
- itou/templates/companies/job_description_card.html
- itou/templates/dashboard/includes/dashboard_title_content.html
- itou/www/apply/views/submit_views.py
- tests/www/apply/test_submit.py
- tests/www/companies_views/__snapshots__/test_card_views.ambr
- tests/www/job_seekers_views/test_create_or_update.py
Je vois deux petits problèmes au fonctionnement actuel :
1. quand on clique sur un bouton **Postuler** directement dans les résultats de la recherche, puis qu'on annule le parcours, on revient à une fiche de poste ou une fiche d'entreprise. On s'attendrait davantage à revenir aux résultats de recherche.
2. lors du parcours "Postuler pour ce candidat", lorsqu'on annule, on retourne également à la fiche de poste ou d'entreprise, **sans le bandeau "Vous postulez actuellement pour…"**.
Une solution est d'ajouter le traditionnel (mais controversé ?) `?back_url=` aux boutons Postuler.
La vue `StartView` insère dans `apply_session` cette info dans `reset_url`. …
> Candidature : ajouter `back_url` sur les boutons Postuler

- .github/workflows/ci.yml
- config/settings/base.py
- config/settings/test.py
- itou/utils/storage/s3.py
- requirements/base.txt
- requirements/dev.txt
- requirements/test.txt
- tests/files/tests.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/apply/test_submit.py
La nouvelle version de Boto3 dans sa configuration par défaut ne peut plus recevoir ou envoyer d’objets vers Cellar. Elle nécessite une adaptation.
1. Utiliser Cellar dans la CI au lieu de MinIO, pour révéler le problème avec la mise à jour. Autrement, on découvre le problème en production, [comme la commu’](https://github.com/gip-inclusion/itou-communaute-django/issues/897).
2. Mettre à jour avec le contournement documenté par Amazon.
> Mise à jour de Boto3

- config/settings/dev.py
Eviter le copier-coller de snippets dans `shell_plus`
Ajout des libs dans la variable d'environnement `SHELL_PLUS_IMPORTS` dans `settings.dev `
> Tech: importer les librairies frequemment utilisées dans shell_plus

- itou/templates/dashboard/dashboard.html
Les sondages ne sont plus actifs.
* Se connecter avec un employeur ou prescripteur
* Visiter la page d'acceuil
> Tableau de bord: Supprimer les sondages présentés aux employeurs et aux prescripteurs [GEN-2336]

- itou/gps/management/commands/sync_follow_up_groups_and_members.py
- itou/gps/models.py
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/views.py
- tests/gps/test_management_commands.py
- tests/gps/test_models.py
- tests/www/apply/test_submit.py
- tests/www/job_seekers_views/test_create_or_update.py
Voir https://www.notion.so/gip-inclusion/Flux-d-ajout-la-cr-ation-d-un-compte-candidat-1ae5f321b604802d947dc5a98ab181d9?pvs=4
Maintenant qu'on utilise `can_view_personal_information` pour paramétrer l'affichage des informations personnelles
- les prescripteurs non habilités peuvent également suivre les candidats lorsqu'ils postulent pour eux
- les prescripteurs / employeurs peuvent suivre les candidats lorsqu'ils créent un compte même sans postuler ensuite (vu que c'est encore plus facile avec l'espace candidat)
Je lancerai la commande `sync_follow_up_groups_and_members` une fois la PR mergée pour rattraper les groupes manquants 
> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés. Attirez l'attention sur les décisions d'architecture …
> GPS: Mise à jour des règles de suivi automatique

- itou/utils/apis/geiq_label.py
- tests/utils/apis/test_geiq_label.py
On va en avoir besoin pour le nouveau bilan d'exécution.
> GEIQ: ajout de la méthode `get_compte_pdf` utilisant le nouvel endpoint `/rest/DownloadCompte`

- .vscode/launch.json
permettre le debuggage des commandes de gestion dans `vscode`
> Outillage: ajout debugger pour les management command dans vscode

- itou/templates/stats/stats.html
- itou/utils/apis/metabase.py
- itou/utils/settings_context_processors.py
- itou/www/stats/views.py
- tests/www/stats/test_views.py
Carte Notion: https://www.notion.so/gip-inclusion/TB-488-Formulaire-Tally-par-type-de-prescripteur-1bb5f321b60480149bf4f04f0582eff1
Dans [un nouveau formulaire Tally](https://tally.so/forms/3XQ5D4/submissions), on paramètre le type de prescripteur dans un [champ encaché](https://tally.so/help/hidden-fields).
* Créer un utilisateur test depuis le shell :
```python
from tests.prescribers.factories import PrescriberOrganizationWithMembershipFactory
from itou.prescribers.enums import PrescriberOrganizationKind
PrescriberOrganizationWithMembershipFactory(kind=PrescriberOrganizationKind.CHRS, department="75", authorized=True)
```
* Détourner l'utilisateur membre de l'organisation.
* Visiter http://localhost:8000/stats/ph/state/main
* Attendre l'apparation du formulaire, ou lancer du JS depuis …
> Pilotage: Suivre le type de prescripteur dans les réponses au formulaire NPS TB 488

- itou/templates/apply/list_for_siae.html
Pour que Justine ait des rendez-vous avec des employeurs
> Candidature: ajout d'une bannière pour inviter les employeurs à un entretien [GEN-2341]

- itou/utils/apis/data_inclusion.py
- tests/utils/apis/test_data_inclusion_api.py
Soliguide est rentré dans une phase d'expérimentation qui nous permet d'afficher leurs données hors DORA. Nous modifions les thématiques de recherche pour  que ces offres de service soient affichées.
En modifiant les thématiques de recherche. Malin.
Le test était déjà là.
> apis: Change data⋅inclusion themes

- itou/templates/dashboard/includes/prescriber_job_seekers_card.html
- itou/templates/job_seekers_views/includes/job_seekers_filters/top_filters.html
- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/job_seekers_views/list.html
- itou/users/models.py
- itou/www/dashboard/views.py
- itou/www/job_seekers_views/forms.py
- itou/www/job_seekers_views/views.py
- tests/www/dashboard/test_dashboard.py
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_list.py
Mieux accompagner ces candidats.
L’info candidat bloqué devrait bientôt remonter de pilotage. Je n’ai donc pas trop mis l’accent sur les tests du filtre, sachant qu’il est déjà pas mal validé par `send_users_to_brevo`.
En termes de perfs, en utilisant des gros émetteurs de candidatures avec la requête suivante, je passe de 100 à 150 ms en locale. Pas de quoi fouetter des chats.
```sql
SELECT sender_id, COUNT(*)
FROM job_applications_jobapplication
WHERE sender_kind='prescriber'
GROUP BY sender_id
ORDER BY 2 DESC;
```
Romain a maintenant un double intérêt à nous remonter l’info candidat sans solution depuis le pilotage, pour éviter qu’on ne fouette des chats.
Se connecter en tant que prescripteur habilité, un membre de la liste des candidats est dans ce cas.
> Identifier les candidats dans la file active depuis plus de 30j [GEN-556]

- itou/employee_record/models.py
- itou/job_applications/models.py
- tests/employee_record/factories.py
- tests/job_applications/tests.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/test_process.py
Car maintenant nous avons les logs de transitions donc on sais si une FS a déjà été transmise ou pas, cela permettra au support (mais aussi aux employeurs !) de ne pas être bloqué dans les cas où l'employeur n'a fait que créer la FS sans l'envoyer, par exemple quand une embauche est annulée.
> Candidature : Autoriser l'annulation quand la fiche salarié n'a pas été transmise

- itou/templates/dashboard/includes/prescriber_job_seekers_card.html
Afin de suivre l'utilisation de celui-ci.
@vincentporte @francoisfreitag Je n'ai plus les règles qui avait été données pour le nommage et pas trouvé de logique claire dans les existants donc n'hésitez pas à corriger si ce que j'ai fait n'est pas bon :).
> Tableau de bord : Ajout d'un évènement matomo pour le lien des candidats sans solution

- itou/templates/account/account_inactive.html
- itou/templates/account/email_confirm.html
- tests/test_consistency.py
- Le cas où le tag `{% extends %}` n'était pas la première ligne n'était pas géré.
- Ajout de la détection de load en double
> test: amélioration de la vérification des templates

- itou/templates/layout/base.html
- itou/utils/staticfiles.py
Parcque faire apparaitre le menu à la tabulation semble une meilleure pratique A11Y (et iso DSFR).
Du coup, quelques petites adaptations  UI
> A11Y: Mise à jour de la mise en forme et du comportement des liens d'évitements

- itou/templates/apply/submit/application/jobs.html
- itou/www/apply/forms.py
- itou/www/apply/views/constants.py
- itou/www/apply/views/submit_views.py
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_submit.py
Suite au https://github.com/gip-inclusion/les-emplois/pull/5698, [on a décidé de mettre ce changement dans un seconde PR](https://github.com/gip-inclusion/les-emplois/pull/5698#issuecomment-2711138958)
> Employeur : empêcher l'envoi de candidatures en cours dès que l'employeur ferme les offres

- tests/www/companies_views/test_job_description_views.py
L’auxiliaire est surprenant, et je n’aime pas ce genre de surprise. Que retourne `self._login` ? La réponse à l’URL de la classe testée…
> Retrait d’un auxiliaire de test de test_job_description_views.py

- itou/templates/employees/detail.html
- itou/www/employees_views/views.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/employees_views/test_detail.py
Un PASS IAE peut être valide mais ne pas avoir démarré.
On corrige pour que l'encart Immersion Facilitée ne dise pas l'inverse du contenu de la page.
(voir captures)
Avant :
Après :
> Profil salarié : correction de la mention du PASS si celui-ci n'a pas démarré dans l'encart Immersion Facilitée

- itou/templates/account/account_inactive.html
- itou/templates/account/account_type_selection.html
- itou/templates/account/email_confirm.html
- itou/templates/account/login_existing_user.html
- itou/templates/account/login_generic.html
- itou/templates/account/login_job_seeker.html
- itou/templates/account/logout.html
- itou/templates/account/password_change.html
- itou/templates/account/password_reset.html
- itou/templates/account/password_reset_done.html
- itou/templates/account/password_reset_from_key.html
- itou/templates/account/password_reset_from_key_done.html
- itou/templates/account/peamu_no_email.html
- itou/templates/account/verification_sent.html
- itou/templates/account/verify_otp.html
- itou/templates/announcements/news.html
- tests/www/signup/__snapshots__/test_password.ambr
Après redécoupage de la [fat PR slippers c-title](https://github.com/gip-inclusion/les-emplois/pull/5806/commits) composant.
Voici la part02
> Ajout du composant c-title aux templates account et announcements

- itou/templates/geiq/assessment_info_for_employer.html
- itou/templates/geiq/assessment_info_for_labor_inspector.html
- itou/templates/geiq/assessment_review.html
- itou/templates/geiq/employee_details.html
- itou/templates/geiq/geiq_list.html
- itou/templates/geiq/list_base.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_base.html
- itou/templates/job_seekers_views/create_or_update_job_seeker/step_end.html
- itou/templates/job_seekers_views/details.html
- itou/templates/job_seekers_views/job_applications.html
- itou/templates/job_seekers_views/list.html
- itou/templates/job_seekers_views/step_check_job_seeker_nir.html
- itou/templates/job_seekers_views/submit_base_two_columns.html
- tests/www/apply/test_submit.py
- tests/www/geiq_views/__snapshots__/tests.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
Après redécoupage de la [fat PR slippers c-title](https://github.com/gip-inclusion/les-emplois/pull/5806/commits) composant. Voici la "petite" **part05**
Refactorisation de la zone de titre des templates geiq et job_seekers afin d'utiliser le composant c-title.
Quelques corrections UI sur certains éléments de cette même zone.
> Ajout du composant c-title aux templates geiq et job_seekers

- itou/templates/gps/group_details_base.html
- itou/templates/gps/group_edition.html
- itou/templates/gps/group_list.html
- itou/templates/gps/join_group.html
- itou/templates/gps/join_group_from_coworker.html
- itou/templates/gps/join_group_from_name_and_email.html
- itou/templates/gps/join_group_from_nir.html
- itou/templates/institutions/members.html
- itou/templates/logout/warning.html
- itou/templates/search/prescribers_search_results.html
- itou/templates/search/siaes_search_results.html
- itou/templates/signup/choose_user_kind.html
- itou/templates/signup/company_select.html
- itou/templates/signup/employer.html
- itou/templates/signup/facilitator_search.html
- itou/templates/signup/job_seeker_signup_base.html
- itou/templates/signup/prescriber_check_already_exists.html
- itou/templates/signup/prescriber_check_pe_email.html
- itou/templates/signup/prescriber_choose_kind.html
- itou/templates/signup/prescriber_choose_org.html
- itou/templates/signup/prescriber_confirm_authorization.html
- itou/templates/signup/prescriber_pole_emploi_safir_code.html
- itou/templates/signup/prescriber_pole_emploi_user.html
- itou/templates/signup/prescriber_request_invitation.html
- itou/templates/signup/prescriber_user.html
- itou/templates/stats/stats.html
- tests/gps/__snapshots__/test_views.ambr
Après redécoupage de la [fat PR slippers c-title](https://github.com/gip-inclusion/les-emplois/pull/5806/commits) composant. Voici la "petite" **part06**
Refactorisation de la zone de titre des templates gps, search et signup afin d'utiliser le composant c-title.
Quelques corrections UI sur certains éléments de cette même zone.
> Ajout du composant c-title aux templates gps, search et signup

- itou/www/stats/views.py
Car le titre dans les vues et le texte dans les liens ne sont pas synchronisé et que j'ai oublié de le faire dans https://github.com/gip-inclusion/les-emplois/pull/5807
> Pilotage : Correction du titre des pages des TB refondus

- itou/approvals/models.py
- tests/approvals/tests.py
Le code actuel se tromps d'un jour quand il n'est pas minuit pile (c'est à dire tout le temps)
Avant:
Après:
> PASS IAE: Correction de l'affichage de la durée destante du PASS

- itou/templates/dashboard/api_token.html
- itou/templates/dashboard/edit_job_seeker_info.html
- itou/templates/dashboard/edit_user_email.html
- itou/templates/dashboard/edit_user_info.html
- itou/templates/dashboard/edit_user_notifications.html
- itou/templates/dashboard/includes/dashboard_title_content.html
- itou/templates/eligibility/update.html
- itou/templates/employee_record/add.html
- itou/templates/employee_record/create.html
- itou/templates/employee_record/disable.html
- itou/templates/employee_record/includes/_status.html
- itou/templates/employee_record/includes/list_item.html
- itou/templates/employee_record/list.html
- itou/templates/employee_record/missing_employee.html
- itou/templates/employee_record/reactivate.html
- itou/templates/employee_record/summary.html
- itou/templates/employees/detail.html
- tests/www/eligibility_views/__snapshots__/test_views.ambr
Après redécoupage de la [fat PR slippers c-title](https://github.com/gip-inclusion/les-emplois/pull/5806/commits) composant. Voici la "petite" **part04**
Refactorisation de la zone de titre des templates dashboard, employee_record et employees afin d'utiliser le composant c-title.
Quelques corrections UI sur certains éléments de cette même zone.
> Ajout du composant c-title aux templates dashboard et employees

- itou/approvals/models.py
- itou/eligibility/tasks.py
- itou/users/enums.py
- itou/users/management/commands/pe_certify_users.py
- itou/users/migrations/0026_identitycertification.py
- itou/users/models.py
- tests/approvals/test_notify_pole_emploi.py
- tests/eligibility/test_iae.py
- tests/eligibility/test_tasks.py
- tests/users/__snapshots__/test_management_commands.ambr
- tests/users/test_management_commands.py
- tests/users/test_models.py
Enregistrer facilement la certification de l’identité d’un individu.
Plusieurs objectifs :
1. Centraliser les informations de certification afin d’afficher les champs correspondants en lecture seule, en expliquant pourquoi aux utilisateurs. #5749 
2. Empêcher les utilisateurs de changer d’identité une fois que le système les a retrouvé dans un référentiel d’identité et a confirmé certains critères d’éligibilité (ex. BRSA sur l’API Particulier)
3. Horodater les mises à jour de l’identité, pour pouvoir rafraîchir les informations
4. Lorsque la CNAV fournira l’identité, les champs certifiés dépendront de chaque utilisateur. L’utilisation d’un modèle intermédiaire permettra d’indiquer quels champs ont été certifiés.
> Ajout d’un champ JobSeekerProfile.identity_certifications [GEN-1380]

- itou/approvals/management/commands/prolongation_requests_chores.py
- itou/common_apps/organizations/models.py
- itou/companies/transfer.py
- itou/eligibility/models/iae.py
- itou/job_applications/models.py
- itou/users/management/commands/send_check_authorized_members_email.py
- itou/www/apply/views/common.py
- itou/www/apply/views/process_views.py
- itou/www/companies_views/views.py
- tests/approvals/factories.py
- tests/approvals/tests.py
- tests/companies/test_models.py
- tests/conftest.py
- tests/job_applications/__snapshots__/test_transfer.ambr
- tests/job_applications/test_transfer.py
- tests/job_applications/tests.py
- tests/metabase/management/test_populate_metabase_emplois.py
- tests/siae_evaluations/test_models.py
- tests/users/test_management_commands.py
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/approvals_views/test_detail.py
- tests/www/dashboard/test_dashboard.py
- tests/www/employee_record_views/test_create.py
- tests/www/search/tests.py
- tests/www/siae_evaluations_views/test_institutions_views.py
Car c'est assez facile de les oublier.
J'ai rajouté la possibilité d'esquiver la vérif via un commentaire si on veut vraiment éviter de mettre à jour le champs `auto_now` mais je ne suis pas trop convaincu: on a toujours la possibilité de faire un `Model.objects.update` pour cela si on le souhaite...
> tests: détection de champs `auto_now=True` absent de l'argument  `update_fields`

- itou/employee_record/common_management.py
- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/models.py
- itou/job_applications/models.py
- tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
- tests/employee_record/test_transfer_employee_records.py
- tests/job_applications/tests.py
[Erreur sentry 1](https://inclusion.sentry.io/issues/35896481/?notification_uuid=ae6927d3-dfaa-4acc-8a1a-f14c01d9dfa3&project=4508410589020240)
- La candidature est acceptée
- La fiche salarié est complétée par l'employeur (statut `READY`)
- L'employeur annule la candidature
=> Le PASS IAE est supprimé, ce qui casse l'envoi de la FS en attente. (Cas résolu par la version actuelle de la PR)
[Erreur sentry 2](https://inclusion.sentry.io/issues/37050035/?alert_rule_id=106033&alert_type=issue&notification_uuid=369b9dc5-e2d5-4d41-acf8-9feadbea7477)
- La candidature est acceptée
- La fiche est pré-remplis (statut `NEW`)
- La candidature est annulée
=> La fiche salarié reste et ne peux pas être finalisée. (Cas résolu par la version actuelle de la PR)
Idéalement il faudrait gérer ce genre de cas …
> Candidatures : Supprimer les fiches salariés non transmises lors de l'annulation

- itou/users/admin.py
- itou/users/migrations/0026_identitycertification.py
- itou/users/models.py
- tests/users/test_admin.py
Suivre les certifications dans l’admin.
> admin: Ajouter les certificateur d’identité au profil demandeur d’emploi

- itou/templates/employee_record/add.html
- itou/www/apply/views/batch_views.py
- itou/www/employee_record_views/views.py
- itou/www/utils/wizard.py
- tests/www/employee_record_views/__snapshots__/test_add.ambr
Vu ce matin en atelier métier.
Le `secondary_name="wizard_goto_step" secondary_value=wizard_steps.prev` faisait qu'au clic on validais le formulaire et on étais donc envoyé vers le tunnel de création de la FS.
Le `reset_url` est obligatoire dans notre `WizardView` donc autant garder les filtres sélectionnés par l'utilisateur.
J'en profite pour corriger des typo qui traînent :).
> Fiches salarié : Correction des actions "Annuler" et "Retour" pour le tunnel "Créer une fiche salarié"

- itou/templates/apply/submit/application/base.html
- itou/templates/companies/card.html
- itou/templates/companies/includes/_card_jobdescription.html
- itou/templates/companies/includes/_card_siae.html
- itou/templates/companies/includes/_company_info.html
- itou/templates/companies/includes/_list_siae_actives_jobs_row.html
- itou/templates/companies/includes/_siae_jobdescription.html
- itou/templates/companies/job_description_card.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/templates/job_seekers_views/details.html
- itou/templates/job_seekers_views/includes/list_results.html
- itou/templates/job_seekers_views/job_applications.html
- itou/templates/search/includes/siaes_search_content.html
- itou/www/apply/views/submit_views.py
- itou/www/job_seekers_views/views.py
- itou/www/search/views.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/apply/test_submit_from_job_seekers_list.py
- tests/www/companies_views/test_card_views.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/__snapshots__/test_list.ambr
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/job_seekers_views/test_details.py
- tests/www/job_seekers_views/test_list.py
- tests/www/search/tests.py
Ce changement va permettre d'utiliser le même nom de paramètre dans les différentes vues utilisées dans le parcours de candidature, et donc de simplifier la récupération de l'information.
Comme il n'y a pas de changement des schémas d'url mais juste d'un nom de paramètre GET, les `or ...` suffisent à garantir la rétrocompatibilité le temps que tout le monde soit déconnecté
> Candidature: Uniformisation du nom d'un paramètre GET

- itou/users/admin.py
Centraliser la définition des champs en lecture seule, faciliter l’extension.
> Mini modifs sur ItouUserAdmin.get_readonly_fields 

- itou/static/js/nps_popup.js
- itou/templates/apply/list_for_siae.html
- itou/templates/apply/list_prescriptions.html
- itou/templates/apply/submit/application/end.html
On est en train de quitter Hotjar. 🔪
J'ai ajouté un script `nps_popup.js` statique qui prend quelques paramètres.
Je ne suis pas très à l'aise en js donc ne pas hésiter à me dire si j'aurai du faire autrement.
> Statistiques : Migrer le NPS de Hotjar vers Tally [GEN-2357]

- itou/templates/apply/includes/eligibility_badge.html
- itou/templates/apply/includes/list_card_body.html
- itou/templates/apply/includes/list_tr.html
- itou/templates/apply/submit/application/base.html
- itou/templates/apply/submit/hire_confirmation.html
- itou/templates/job_seekers_views/check_job_seeker_info_for_hire.html
- itou/templates/job_seekers_views/includes/list_results.html
- tests/job_applications/tests.py
- tests/www/apply/__snapshots__/test_list.ambr
- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/__snapshots__/test_list_prescriptions.ambr
On ne veut plus marquer PASS expiré sur le badge, et laisser l'employeur avoir l'alerte qui lui dit de passer par un prescripteur habilité dans le parcours d'embauche.
J'ai donc revu ma copie
~Si on a un diagnostic (de prescripteur?) valide, alors on est éligible, même si on a un PASS expiré dans le délais de carence.~
~Le template `eligibility_badge.html` est sacrément plus compliqué, et il manque un joli test pour tester toutes les combinaisons... j'attends un retour sur la carte notion~
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc. …
> Candidature: Correction du badge d'éligibilité quand le PASS IAE est expiré [GEN-1462]

- itou/templates/companies/job_description_card.html
- itou/templates/companies/job_description_list.html
- itou/utils/templatetags/datetime_filters.py
- tests/utils/tests.py
🛑 Ne relire que les deux derniers commits !
Prérequis nécessaire au projet dépublication des fiches de poste.
On souhaite afficher la date de dernière mise à jour des fiches de poste aux employeurs.
En affichant la date de dernière mise à jour dans une colonne (listing tableau, date relative) et dans le haut de la page (détails de la fiche de poste, date exacte).
PR suivante.
> Fiche de poste: Affichage de la date de dernière mise à jour [GEN-2088]

- itou/archive/management/commands/notify_archive_jobseekers.py
- tests/archive/tests_management_command.py
> Vie privée : Allonger la durée d'inactivité à 24 mois avant la notification des comptes candidats sans candidature inactifs

- itou/templates/admin/companies/change_company_form.html
- tests/companies/test_admin.py
L'utilisation de la fonctionnalité est déjà conditionnée à la permission.
> Admin: utilisation de la permission `change_company` pour l'affichage du bouton de transfert d'entreprise

- itou/static/js/nps_popup.js
- itou/templates/apply/list_for_siae.html
- itou/templates/apply/list_prescriptions.html
- itou/templates/apply/submit/application/end.html
Le popup tally du NPS récemment mis en prod (https://github.com/gip-inclusion/les-emplois/pull/5959) s'affiche aussi en démo et ses résultats potentiels se mélangent à ceux de la prod tout en en étant indistinguables.
En remplacant le domaine en dur https://tally.so par son alter ego dynamique `{{ TALLY_URL }}` qui est défini en prod et pas en démo. Comme ça le popup NPS est cassé à la racine et n'apparait plus du tout en démo.
Pour mémoire le domaine https://tally.so est aussi en dur historiquement à plein d'autres endroits du code, notamment pour des questionnaires tally qui ont exactement le même problème (fonctionner en démo et polluer la prod). 
Mais j'hésite à tous les casser en démo avec la même solution car j'imagine que c'est assez pratique pour nous de vérifier jusqu'au bout …
> Statistiques : Désactivation du NPS en démo

- itou/geiq/models.py
- itou/siae_evaluations/models.py
- itou/utils/models.py
Pour facilement indiquer l'ordonnancement de deux champs dates.
Comme je compte en [rajouter 6 sur le bilan d'exécution GEIQ](https://github.com/gip-inclusion/les-emplois/blob/xfernandez/geiq_assessments/itou/geiq_assessments/models.py#L148-L197), autant éviter un peu les redites :grimacing: 
> Tech: ajout d'un petit helper `check_date_order_constraint`

- itou/www/approvals_views/forms.py
- tests/www/approvals_views/__snapshots__/test_prolongation.ambr
Affichage du _spinner_ sur la totalité du formulaire et non seulement sur le champ qui a déclenché l'événement.
Avant
Après
> [Prolongations] Affichage du _spinner_ sur la totalité du formulaire

- itou/templates/apply/list_for_siae.html
Parcque le chef demande
https://www.notion.so/gip-inclusion/Remonter-le-bandeau-Votre-avis-nous-int-resse-au-dessus-du-bandeau-action-de-la-liste-de-candidatu-1df5f321b604804c9854dbe66033f5a2
En déplacant l'alerte dans le mauvais `{% block %}` 🙈 (mais c'est une alerte temporaire, c'est presque pardonnable)
> Interface: Remonter le bandeau “Votre avis nous intéresse” au dessus du bandeau action de la liste de candidatures

- itou/companies/transfer.py
- tests/companies/test_admin.py
Le bouton de transfert d'une entreprise est souvent utilisé pour transférer les données vers une entreprise **qui a déjà des membres**.
Actuellement, si un membre existe dans les 2 entreprises, quels que soient les attributs du *membership* (`is_admin` ou `is_active`), on ne fait rien.
On voudrait dans un premier temps que si le statut `is_admin` diffère, celui-ci soit transféré également.
> Admin : conserver le statut d'administrateur lors du transfert d'une SIAE à une autre, et supprimer les membres lors de la désactivation [GEN-2374] 

- itou/job_applications/models.py
Utiliser le setting django `settings.AUTH_USER_MODEL` à la place de la définition statique `"users.User"` pour le champ `archived_by` dans le modèle `JobApplication`
> Performances: JobApplication: correction de la FK vers User pour le champ archived_by

- itou/templates/apply/includes/certification_info_box.html
Une icône seule n’est pas liée au lien, et ne sera pas mise à jour avec le thème.
> Éligibilité : Mieux indiquer le lien externe dans le bloc d’information sur la certification des critères

- .github/workflows/mkchangelog.yml
Les actions GitHub ont déjà un token défini pour leur exécution. L’utiliser évite la gestion d’un token séparé.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
> Changelog : Utiliser le token GitHub des actions

- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
> [Admin] Permettre aux admins itou d'ajouter un calendrier

- itou/templates/dashboard/dashboard.html
- itou/templates/dashboard/includes/employer_prescription_card.html
Pour prérarer la migration de tous les éléments de navigation de l’accueil vers le menu de gauche qui est en cours pour pouvoir faire de la place pour mettre en oeuvre ce projet du semestre : [https://www.notion.so/gip-inclusion/Faire-de-l-accueil-un-tableau-de-bord-](https://www.notion.so/gip-inclusion/Faire-de-l-accueil-un-tableau-de-bord-1d55f321b604802a8513d6e9f6039869?pvs=4)
Echange sur le besoin [ici
](https://gip-inclusion.slack.com/archives/CQ6C3LSAH/p1745932108990039)
> Interface: Inversion des blocs structure et orientation sur le dashboard 

- itou/templates/static/legal/terms.html
- itou/www/companies_views/forms.py
- itou/www/signup/forms.py
- tests/www/companies_views/test_create_company_views.py
La plupart du temps sur le site on trouve la formulation "numéro SIRET", mais à quelques endroit subsistent des "numéro **de** SIRET".
On harmonise.
> Interface : harmonisation de la formulation en "numéro SIRET"

- itou/templates/companies/hx_dora_services.html
- itou/www/companies_views/views.py
- tests/www/companies_views/__snapshots__/test_dora_views.ambr
- tests/www/companies_views/test_dora_views.py
random.shuffle() was returning services that were way too similar to each other.
- add a special case where we WANT a soliguide service to be selected on a few given departments; in any other case, just pick one.
- make sure that the other selected services's themes are as far as possible from the others.
- make sure it can't crash.
- don't do anything too complicated with for instance a distance function, a bitmap  or something. We want an will always only want 3 items.
[On est partis sur ça](https://www.notion.so/gip-inclusion/Int-gration-Les-Emplois-correction-de-bug-modif-source-1d55f321b604801ea801c6c8c63ad5ee?pvs=4) pour garder une implémentation la plus simple possible, meme si ça fait un peu brouillon.
- KO Mettre à jour le CHANGELOG_breaking_changes.md ?
- KO Ajouter l'étiquette …
> get_di_services : Amélioration de la sélection des services + mention de la source

- itou/templates/apply/includes/certification_info_box.html
- itou/templates/apply/includes/selected_administrative_criteria_display.html
- tests/www/apply/test_templates.py
Attirer l’attention des employeurs sur le fait qu’ils doivent conserver les justificatifs en cas de contrôle.
1. Déclarer une embauche pour un nouveau candidat dans une SIAE
2. À l’étape de validation de l’éligibilité, choisir des critères certifiables (AAH, Parent isolé, et/ou RSA)
3. Valider l’éligibilité
4. Terminer la candidature
5. Aller voir la page de la candidature
Il devrait y avoir:
- des badges Non certifiés à côté des critères certifiables.
- une explication sur les critères certifiés et non certifiés.
> Eligibilité : Ajouter un badge pour indiquer les critères non certifiés [GEN-2008]

- itou/templates/companies/edit_job_description_details.html
- itou/templates/companies/edit_job_description_preview.html
- itou/templates/companies/job_description_card.html
- itou/www/companies_views/urls.py
- itou/www/companies_views/views.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/companies_views/test_job_description_views.py
Protéger le parcours des problèmes d’une session modifiée dans des onglets multiples.
En écrivant l’ID de la session dans l’URL.
J’en ai profité pour ajouter `job_description_id` dans les URLs, afin de mieux indiquer si le parcours est une création de fiche de poste ou une mise à jour.
`test_empty_session_during_edit` a été supprimé, puisque la `SessionNamespace` requiert dorénavant une `edit_session_id`.
Créer une fiche de poste.
Mettre à jour une fiche de poste.
> Utiliser le SessionNamespace pour sécuriser l’édition des fiches de poste [GEN-2311]

- itou/approvals/models.py
> Admin: Amélioration d'une description de champ [GEN-2325]

- itou/www/signup/views.py
- tests/www/signup/test_siae.py
Difficile à tester en local vu qu'on bloque ProConnect.
Je peux néanmoins configurer une recette jetable sur la démo de ProConnect pour tester le fonctionnement, mais je pense que le changement est suffisamment petit pour qu'on s'en passe.
> Inscription: Sécuriser l’inscription des OPCS pour éviter les offres frauduleuses [GEN-2373]

- config/settings/base.py
- itou/companies/management/commands/import_ea_eatt.py
- tests/companies/__snapshots__/test_import_ea_eatt.ambr
- tests/companies/test_import_ea_eatt.py
- tests/utils/test_logger.py
capturer les logs de la `command` dans le logger, en passant les données variables en `kwargs`
Non Mettre à jour le CHANGELOG_breaking_changes.md ?
Non Ajouter l'étiquette « Bug » ?
> [GEN-2321] Stabilité: traitement des logs de Import EA EATT

- itou/templates/companies/includes/_card_jobdescription.html
Car on ne comprenait pas bien que l'item de job était cliquable
Au passage, remplacement de la classe `.has-external-link` par une icône, car les deux classes (.has-external-link et .stretched-link) agissaient sur le même pseudo-élément `::after`
> Interface: ajout de la classe .stretched-link manquante sur les cartes de job_description

- itou/templates/prescribers/list_accredited_organizations.html
Pour qu'ils puissent demander le retrait d'une organisation plus facilement.
Se connecter avec les codes suivants :
- email : cd@test.com
- mot de passe : `LesNocesDeFigaro98_`
Puis dans le tableau de bord, cliquer sur Liste des organisations conventionnées.
> [Prescripteur] Ajout d'un message pour les admins des CD

- itou/siae_evaluations/models.py
- itou/siae_evaluations/templatetags/siae_evaluations_siae_tags.py
- itou/templates/siae_evaluations/includes/job_seeker_infos_for_siae.html
Faciliter l’ajout d’un état différent lorsqu’une candidature est automatiquement acceptée grâce à un critère certifié.
Voir le message de commit pour le détail.
1. Se connecter en tant qu’ETTI
2. Aller sur le contrôle en cours
3. Suivre le parcours pour vérifier les différents badges
> Contrôle a posteriori : Réusinage du badge d’état des candidatures pour les SIAE [GEN-2345]

- itou/users/management/commands/sync_group_and_perms.py
- tests/users/__snapshots__/test_sync_group_and_perms.ambr
Les membres de l’équipe RDV Insertion mettent en correspondance les entreprises des Emplois avec les entreprises de RDV-I. Comme nous n’avons pas d’identifiant en commun, les correspondances se basent sur les noms et les membres.
Une fois une entreprises identifiées, les autres entreprises d’un groupe sont repérées à l’aide des membres.
1. Lancer la commande `sync_group_and_perms`
1. Se connecter à l’admin
2. Créer un nouvel utilisateur
3. Ajouter l’utilisateur au groupe rdvi
4. Se connecter sur le compte du nouvel utilisateur (ou le détourner)
5. Accéder à l’admin et vérifier que l’utilisateur n’a accès qu’en lecture, aux entreprises et aux utilisateurs (ainsi que l’encart membre des entreprises).
> RDV Insertion : Création d’un groupe pour un accès restreint à l’interface administateur

- itou/utils/apis/metabase.py
- itou/www/stats/views.py
C'est cassé, le filtre géographique pour la France entière est trop long.
> Pilotage : Réparer le TB "Suivi des prescriptions des AHI" pour la DIHAL

- itou/companies/models.py
- itou/www/companies_views/views.py
- tests/www/companies_views/__snapshots__/test_job_description_views.ambr
- tests/www/companies_views/test_job_description_views.py
L'ordre est à présent basé sur :
1. Statut actif (FDP actives en premier)
2. Date de mise à jour (si définie, la dernière mise à jour employeur prend le dessus sur `updated_at`)
3. Date de création
Pour avoir un fonctionnement plus cohérent dans le listing des FDP et présenter les actives en priorité aux employeurs.
Cf. https://gip-inclusion.slack.com/archives/CU8ATF54L/p1745850440314969?thread_ts=1741943558.714919&cid=CU8ATF54L
> Fiche de poste: Mise à jour de l'ordonnancement des fiches

- itou/companies/enums.py
- itou/companies/models.py
- itou/employee_record/models.py
- itou/metabase/tables/companies.py
Le dispositif Convergence ACI s'applique actuellement aux entreprises dont le SIRET fait partie d'une liste blanche.
Le SIRET de leurs antennes ne fait a priori pas partie de cette liste blanche du coup elles ne sont pas considérées comme PHC CVG, ce qui cause une frustration légitime.
- Un refacto DRY de la logique antenne/parent, qui retouche à du code de Pilotage en passant.
- Un refacto DRY de la logique PHC CVG qui touche aussi à Pilotage.
- Le correctif lui-même.
- Tonial qui était au tout début la discussion.
- Rsebille pour le refacto côté Pilotage.
> Employeur : Correctif de la logique Convergence ACI (PHC CVG) pour les antennes [GEN-2411]

- itou/users/admin.py
- tests/users/test_admin.py
Several users contacted us to modify job seekers' information
that should be valid, because these job seekers were certified by the
API Particulier, but are not.
Until we find out how job seekers could certified with what
could be wrong information, let's unblock customer support.
> Admin : Rendre les champs utilisateurs éditables même lorsque son identité est certifiée

- itou/geiq/sync.py
- itou/siae_evaluations/models.py
- itou/users/admin.py
- itou/www/apply/views/batch_views.py
- scripts/clever-deploy
- tests/api/employee_record_api/test_serializers.py
- tests/approvals/test_prolongation_requests.py
- tests/employee_record/test_serializers.py
- tests/external_data/tests.py
- tests/job_applications/test_transfer.py
- tests/job_applications/tests.py
- tests/metabase/management/test_populate_metabase_emplois.py
- tests/users/test_admin.py
- tests/users/test_management_commands.py
- tests/www/apply/test_batch_views.py
- tests/www/apply/test_list_for_siae.py
- tests/www/apply/test_list_rdv_insertion.py
- tests/www/apply/test_process.py
- tests/www/approvals_views/test_prolongation.py
- tests/www/dashboard/test_dashboard.py
- tests/www/dashboard/test_edit_user_info.py
- tests/www/employee_record_views/test_list.py
- tests/www/employees_views/test_detail.py
- tests/www/geiq_eligibility_views/test_forms.py
- tests/www/itou_staff_views/tests.py
- tests/www/signup/test_job_seeker.py
Pour mettre ça derrière moi avant de partir en congé.
Seconde passe après https://github.com/gip-inclusion/les-emplois/pull/6030
- `personal` avec un N 
- `aggregation` avec deux G
- `transferred` avec deux R
- `criteria` ne prend pas de S car est déjà le pluriel de `criterion`
- `preferred` avec deux R
- `overridden` avec deux D
- et d'autres
Je me suis pas mal aidé de https://github.com/codespell-project/codespell
- champ `agregation_kind` 💩
> Typos : Correctif de typos variées dans le code et les commentaires du code

- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/metabase/tables/job_applications.py
- tests/metabase/management/test_populate_metabase_emplois.py
Pour permettre à Pilotage de sortir des stats sur ce champ utile, par exemple "dans quelle mesure la présence d'un CV impacte les chances de réussite d'une candidature ?"
- @tonial car potentiel conflit avec https://github.com/gip-inclusion/les-emplois/pull/6102
- @YannickPassa pour le joke (il y a un easter egg pour toi dans cette PR)
- @rsebille pour avoir un dev Pilotage
> Pilotage : Ajouter l’absence/présence de CV dans la table candidatures de Metabase [GEN-2272]

- itou/gps/admin.py
- tests/gps/test_admin.py
Pour contrôler, mesurer et comprendre les usages de la fonction "Motif d'accompagnement".
Dans l'admin, via `/admin/gps/followupgroupmembership/?has_reason=yes`.
> GPS: Ajout d'un filtre dans l'admin

- tests/siae_evaluations/test_models.py
Un test plus rapide, grâce à moins de requêtes.
> Simplifier TestEvaluationCampaignManager.test_populate

- Makefile
Cette recette ne fait pas aussi bien que `git clean`, et propose moins d’options.
> Retirer la recette `make clean`

- tests/www/apply/test_process.py
- tests/www/apply/test_templates.py
- tests/www/eligibility_views/utils.py
La durée de validité d’une certification était calculée de manière incorrecte, un critère restait certifié plus longtemps qu’attendu (184 jours au lieu de 92 jours attendus). Les employeurs n’ont pas rencontré ce bug, parce que le diagnostic d’élígibilité expire au bout des 92 jours comme prévu, masquant le fait que le calcul de l’éligibilité était incorrect.
Voir https://github.com/gip-inclusion/les-emplois/pull/6126
Ce test permet de vérifier que le critère certifié n’apparaîssait pas grâce a l’expiration du diagnostic. Je ne pense pas l’intégrer, mais il permet de jouer avec le système et de bien comprendre son comportement.
> Éligibilité : Vérifier que le badge certifié n’était pas affiché aux employeurs après l’expiration du diag

- itou/templates/companies/includes/buttons/job_description_refresh.html
- itou/templates/companies/includes/buttons/spontaneous_applications_refresh.html
- itou/templates/companies/includes/buttons/spontaneous_applications_toggle.html
- itou/templates/companies/job_description_card.html
- itou/templates/companies/job_description_list.html
- itou/www/companies_views/urls.py
- itou/www/companies_views/views.py
- tests/www/companies_views/__snapshots__/test_job_description_views.ambr
- tests/www/companies_views/test_job_description_views.py
Actuellement la mise à jour d’une fiche de poste nécessite de passer par le formulaire d’édition et faire 5 clics pour la mettre à jour.
Avoir un moyen de mettre à jour rapidement (càd avoir le même résultat que si on avait cliqué sur “enregistrer” à la fin du parcours d’édition de fiche de poste sans avoir besoin de l’ouvrir).
En ajoutant dans le tableau de listing des fiches de poste et sur leur page de détail un bouton permettant d'actualiser leur date de mise à jour.
- S'identifier avec l'EI
- Consulter [https://c1-review-leo-add-job-description-updated-date-update-action.cleverapps.io/company/job_description_list](https://c1-review-leo-add-job-description-updated-date-update-action.cleverapps.io/company/job_description_list)
> Fiche de poste: Ajout d'une action permettant d'actualiser la date de mise à jour en un clic [GEN-526]

- itou/templates/siae_evaluations/includes/criterion_infos.html
- tests/www/siae_evaluations_views/test_siaes_views.py
Mieux structure l’information, faciliter l’ajout du badge certifié pour https://www.figma.com/design/D03fLXh9KzMgCiKbrGEnQg/%F0%9F%94%B5-Contr%C3%B4le-a-posteriori?node-id=4878-3837&p=f.
> Interface : Petite amélioration de l’encart justificatif du contrôle a posteriori

- itou/templates/prescribers/edit_organization.html
- tests/www/prescribers_views/test_edit.py
La bannière dit que les informations entrées sont visibles par tous les utilisateurs connectés, ce qui n'est vrai que pour les prescripteurs habilités.
> Prescripteur : dans la page d'édition de l'organisation, n'afficher l'alerte sur la visibilité des informations qu'aux prescripteurs habilités

- itou/templates/static/accessibility.html
- tests/www/test_static_views.py
Pour actualiser certaines infos
Suppression de la partie “Contenus non accessibles” car elle détaillait des points défaillants qui ne le sont plus ou qui ne sont plus les mêmes. De plus, cette partie n'est pas présente dans le "modèle" beta.gouv que nous utilisons sur le pilotage, la commu et le site de la pdi
Mise à jour de la section contact par remplacement du lien de contact par un lien vers le formulaire de contact de l'aide
> Accessibilité: Mise a jour du contenu de la page Accessibilité

- itou/eligibility/migrations/0001_initial.py
- itou/eligibility/models/common.py
- itou/eligibility/models/geiq.py
- itou/eligibility/models/iae.py
- itou/www/eligibility_views/forms.py
- itou/www/siae_evaluations_views/forms.py
- itou/www/siae_evaluations_views/views.py
- tests/eligibility/test_iae.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/eligibility_views/test_forms.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/siae_evaluations_views/test_forms.py
Découpage pour mieux gérer la sélection de critères en présence de critères certifiés (qui seront cochés et `disabled` par défaut).
Déplacer la logique de récupération des critères dans la vue.
> Réusinage de siae_select_criteria pour les critères certifiés

- itou/users/models.py
Faciliter la lecture des règles associées à la création d’antennes.
> Clarifier User.can_create_siae_antenna

- tests/www/siae_evaluations_views/test_institutions_views.py
- tests/www/siae_evaluations_views/test_siaes_views.py
Ils ne sont plus utiles, et nous voulons être alertés de références à des variables inconnues, même nommées `reviewed_at`.
> Retirer les ignore_unknown_variable_template_error des tests siae_evaluations

- tests/www/prescribers_views/test_edit.py
Erreurs intermittentes des tests:
```
=================================== FAILURES ===================================
_______________________ TestCardView.test_card_subtitle ________________________
[gw3] linux -- Python 3.13.3 /home/runner/work/les-emplois/les-emplois/.venv/bin/python3
self = <django.db.backends.utils.CursorWrapper object at 0x7f7dc09d0410>
sql = 'INSERT INTO "prescribers_prescriberorganization" ("address_line_1", "address_line_2", "post_code", "city", "departmen...s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "prescribers_prescriberorganization"."id"'
params = ('', '', '75167', '', '75', None, ...)
ignored_wrapper_args = (False, {'connection': <DatabaseWrapper vendor='postgresql' alias='default'>, 'cursor': …
```
> Fin du bagotage pour prescribers_views.test_edit

- tests/www/siae_evaluations_views/test_institutions_views.py
- tests/www/siae_evaluations_views/test_siaes_views.py
Éviter de gaspiller du temps de test, clarifier. Voir le message de commit pour les détails.
> Retrait d’un test en double dans tests/www/siae_evaluations_views/test_institutions_views.py

- itou/eligibility/migrations/0013_remove_administrative_criteria_created_by_database_operation.py
prequis #6133 
Le champ `created_by` n'est pas utilisé dans les modèles `AdministrativeCriteria` et `GEIQAdministrativeCriteria`.
Il crée une ambiguïté vis-à-vis des traitements d'archivage. 
Suppression du champ pour SQL (partie 2)
> Vie privée : suppression du champ created_by dans les modèles AdministrativeCriteria [GEN-2453] (partie 2/2)

- itou/templates/approvals/prolongation_requests/show.html
- itou/www/approvals_views/views.py
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/approvals_views/test_prolongation_requests.py
Voir sentry : https://inclusion.sentry.io/issues/15013580/events/latest/?referrer=latest-event
Soit lié à un double click (j'ai ajouté la class js pour l'éviter)
Soit parce que la demande a été validée depuis un autre onget (ou par un collègue en parallèle)
> PASS IAE: Correction d'un bug lors de l'acceptation d'un demande de prolongation [GEN-2204]

- itou/eligibility/models/common.py
- itou/eligibility/models/geiq.py
- itou/eligibility/utils.py
- itou/www/apply/views/process_views.py
- itou/www/apply/views/submit_views.py
- itou/www/employees_views/views.py
- itou/www/job_seekers_views/views.py
- tests/eligibility/test_iae.py
- tests/eligibility/test_utils.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/test_process.py
- tests/www/apply/test_templates.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
Au départ, l’API particulier donnait une période d’éligibilité pour la certification des critères. Il s’est avéré que la réponse de l’API correspond à la question « est-ce que cette personne est bénéficiaire aujourd’hui ? », et que la date de début correspond à l’ouverture des droits actuels. La date de fin s’est révélée fausse et a été changée pour ne jamais être spécifiée par l’API (voir 9d44cd13f602550e2aae38afc6a3487897abc704).
Nous avons décidé de fixer la date de fin à 92 jours, qui correspond à la fin d’acceptabilité d’un justificatif daté (justificatif de moins de trois mois). La période de certification inclut donc maintenant le délai de trois mois (`is_considered_valid`), mais nous ne sommes pas revenus sur `with_is_considered_valid`, qui octroie également ce délai. Ainsi, le …
> Éligibilité : Correction de la durée de validité de la certification des critères

- itou/eligibility/migrations/0014_selectedadministrativecriteria_empty_certification_period.py
Il y a des données invalides dans la base de données.
```sql
SELECT certified_at
FROM eligibility_selectedadministrativecriteria
WHERE certified AND certification_period IS NULL
ORDER BY 1 DESC;
```
donne 1048 resultats, le plus récent date du 9 janvier 2025.
https://inclusion.sentry.io/issues/42627599/?project=4508410589020240&referrer=github-pr-bot
> Éligibilité : Correction de durées de certification de critères administratifs incorrects

- clevercloud/cron.json
- itou/archive/management/commands/notify_archive_jobseekers.py
- itou/archive/management/commands/notify_archive_users.py
- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/templates/account/email/email_inactive_user_body.txt
- itou/users/enums.py
- itou/users/notifications.py
- itou/utils/constants.py
- tests/archive/__snapshots__/tests_management_command.ambr
- tests/archive/tests_management_command.py
- tests/openid_connect/france_connect/tests.py
- tests/openid_connect/pe_connect/tests.py
- tests/users/factories.py
prequis de #6074 
adapter le code existant, spécialisé sur les profils de candidats, compatibles avec les profils d'employeurs, d'inspecteurs du travail et de prescripteurs
> Vie privée : refactor en préparation de la notification et de l'archivage des professionnels

- itou/fixtures/django/.gitattributes
C'est assez laborieux de travailler avec des fichiers binaires, et ça ne servait, a priori, qu'à nettoyer la sortie de `git grep`.
Les utilisateurs de `git grep` seront heureux de savoir qu'un comportement similaire peut être retrouvé avec `git grep "Jacques" -- ':(exclude)*.json'`.
> Considérer les fixtures `.json` comme du texte et non comme des fichiers binaires

- itou/eligibility/migrations/0012_remove_administrativecriteria_created_by_state_operation.py
- itou/eligibility/migrations/0013_remove_administrative_criteria_created_by_database_operation.py
conserver un historique de migrations simples
remplacement du couple de migrations pour un `zero_downtime` par une migration simple.
> Vie privée : suppression du champ created_by dans les modèles AdministrativeCriteria [GEN-2453] (partie 3/2)

- itou/companies/models.py
- itou/employee_record/management/commands/resend_employee_records.py
- itou/employee_record/models.py
- itou/templates/employee_record/includes/list_header.html
- itou/templates/employee_record/includes/list_item.html
- itou/templates/employee_record/includes/list_results.html
- itou/templates/employee_record/includes/send_back_dropdown.html
- itou/templates/employee_record/summary.html
- itou/utils/perms/employee_record.py
- itou/www/employee_record_views/views.py
- tests/companies/test_models.py
- tests/employee_record/__snapshots__/test_admin.ambr
- tests/employee_record/test_models.py
- tests/utils/perms/tests.py
- tests/www/employee_record_views/__snapshots__/test_create.ambr
- tests/www/employee_record_views/__snapshots__/test_list.ambr
- tests/www/employee_record_views/__snapshots__/test_summary.ambr
- tests/www/employee_record_views/test_create.py
- tests/www/employee_record_views/test_list.py
- tests/www/employee_record_views/test_summary.py
On veut faciliter le renvoi de la fiche salarié lorsque si l'entreprise a un nouveau SIRET.
En fait, on généralise un petit peu, puisque renvoyer des FS peut être utile dans d'autres cas (fiche supprimée côté ASP par exemple).
On affiche donc un bouton "Renvoyer la fiche salarié" sur toutes les FS *Intégrées*.
**Points de vigilance :**
- le siret est celui de l'entreprise mère (`employee_record.siret_from_asp_source`)
En pratique, le bouton `Renvoyer > Avec modification` est un lien vers `employee_record_views:create` (qui gère également la modification).
Le bouton `Renvoyer > Sans modification` est directement un POST vers la dernière étape du même processus. J'ai trouvé que c'était le plus simple, mais c'est questionnable sans souci.
> _Les instructions pour reproduire le problème, les …
> Fiche salarié : faciliter le nouvel envoi de la fiche si le SIRET de l'entreprise a changé

- tests/www/employee_record_views/test_list.py
Un test bagottant dû à la sélection aléatoire du statut de fiche salarié.
Les fiches archivées ne sont pas affichables.
> Fiches salarié : correction d'un test bagottant

- Makefile
- README.md
Il arrive de travailler hors ligne, et dès qu'il y a un changement dans `requirements/dev.txt`, `uv` se lance pour mettre à jour les dépendances et plante s'il n'y a pas de réseau.
On peut utiliser l'option `-o requirements/dev.txt` pour ignorer les changements, mais il y a des appels récursifs à `make`.
Je propose donc d'ajouter cette option aux appels récursifs (qui ne concernent que des cibles de réinitialisation/dump de la base de données).
J'ai aussi remarqué qu'il y a une variable `VIRTUALENV`, probablement une coquille, cela devrait être `VIRTUAL_ENV` ?
> Makefile : ignorer les changements dans `requirements/dev.txt` dans les appels récursifs à  `make`

- itou/www/siae_evaluations_views/forms.py
- itou/www/siae_evaluations_views/views.py
- tests/www/eligibility_views/test_forms.py
- tests/www/siae_evaluations_views/test_forms.py
- tests/www/siae_evaluations_views/test_siaes_views.py
Le formulaire autorisait la saisie d’un seul critère de niveau 2 pour justifier une auto-prescription, alors que deux ou trois critères sont requis (selon le type de SIAE).
Bisecté à 9acbe5f32d0bf4d808a5798f6a86746a8fa7fd5e.
Voir le message de commit pour l’explication et pourquoi le code s’exécutait sans erreur.
1. `make resetdb`
1. Se connecter en tant que l’ETTI
2. Depuis le tableau de bord, naviguer vers la campagne de contrôle contrôle a posteriori en cours
3. Sélectionner les critères pour une auto-prescription (uniquement un critère de niveau 2)
5. Soumettre le formulaire
Attendu : une erreur, il faut trois critères de niveau 2 pour une ETTI.
Constaté : le formulaire est accepté, l’employeur peut justifier uniquement un critère
> Contrôle a posteriori : Correction d’une régression dans la validation du formulaire de sélection des critères administratifs [GEN-2457]

- itou/asp/migrations/0007_ignore_historic_mayotte_communes.py
Si on se retrouve à sélectionner une commune historique (commençant par 985) alors l'Extranet nous envois bouler : _Le champ Commune de Naissance doit être en cohérence avec le champ Département de Naissance_.
Les communes actuelles n'ont pas ce problème.
On va donc ignorer les communes historiques et fin de l'histoire.
> Fiches Salarié : Ignorer les communes historiques de Mayotte

- itou/templates/geiq_assessments_views/assessment_contracts_details.html
- itou/templates/geiq_assessments_views/assessment_details_for_institution.html
- tests/www/geiq_assessments_views/__snapshots__/test_views_for_institution.ambr
Evolution de la mise en forme des [.list-data](https://zeroheight.com/85c89893b/p/468448-list-data)
Mise a jour du thème, des templates et corrections de quelques points UI
@xavfernandez La nouvelle mise en forme pousse a mettre les éléments en ligne (libelle : valeur) et donc plus trop la largeur pour 2 colonnes (bien que ce soit encore possible avec le `.list-data-group`). Bref, j'ai passé les `.list-data` en une seule colonne comme sur les maquettes.
> Interface: Mise à jour des .list-data sur les pages GEIQ

- itou/archive/management/commands/notify_archive_users.py
- itou/archive/tasks.py
- itou/utils/brevo.py
- tests/archive/__snapshots__/tests_tasks.ambr
- tests/archive/tests_tasks.py
- tests/utils/__snapshots__/test_brevo.ambr
- tests/utils/test_brevo.py
Les méthodes décorées par `@task` doivent être déclarées dans un fichier nommé `tasks.py` pour être visible de `Huey`
déplacer de `async_delete_contact` dans un fichier `tasks.py` dans l'app `Archive`
> Vie privée : rendre la tâche de suppression des emails visible de Huey

- itou/static/js/demo_accounts.js
- itou/templates/layout/_news_modal.html
La fonction `supports_local_storage` n'était dispo que sur la démo & les recettes jetables, pour l'affichage de la modale de connexion des comptes de démo.
La modale de nouveautés n'a donc jamais fonctionné en production :see_no_evil: :smiling_face_with_tear: .
En définissant la fonction uniquement là où elle est utilisée.
Mais je me demande si on ne pourrait pas complètement la supprimer au vu de la compatibilité des navigateurs:
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage#browser_compatibility
> Nouveautés: correction de l'affichage de la modale

- config/settings/base.py
- itou/templates/static/maintenance.html
- itou/www/middleware.py
- tests/www/__snapshots__/test_maintenance.ambr
- tests/www/test_maintenance.py
Pour permettre de facilement faire des petites coupures de service pour certains déploiements
> Tech: Ajout d'un mode de maintenance

- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- itou/employee_record/models.py
- tests/api/employee_record_api/__snapshots__/tests.ambr
- tests/employee_record/__snapshots__/test_transfer_employee_records.ambr
- tests/employee_record/__snapshots__/test_transfer_employee_records_updates.ambr
- tests/employee_record/test_transfer_employee_records.py
- tests/employee_record/test_transfer_employee_records_updates.py
- tests/www/employee_record_views/__snapshots__/test_list.ambr
Pour éviter une cascade de requête SQL au moment de la sérialisation de l'objet.
> Fiches Salarié : Réduction du nombre de requête SQL lors de l'envoi

- itou/emails/tasks.py
- tests/emails/test_tasks.py
Simplifier un peu le code, s’assurer que la tâche s’exécute toujours `on_commit`.
> emails : Décorer _async_send_message avec on_commit_task

- itou/approvals/models.py
- itou/eligibility/tasks.py
- itou/emails/tasks.py
- itou/geiq/sync.py
- itou/gps/management/commands/import_advisor_information.py
- itou/gps/management/commands/sync_follow_up_groups_and_members.py
- itou/job_applications/management/commands/reject_job_applications_after_delay.py
- itou/www/apply/views/batch_views.py
- itou/www/apply/views/process_views.py
- itou/www/geiq_assessments_views/views.py
- tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
Incident en production aujourd’hui, tout le site était très lent.
https://docs.djangoproject.com/en/5.2/ref/models/querysets/
> By default, select_for_update() locks all rows that are selected by the query. For example, rows of related objects specified in select_related() are locked in addition to rows of the queryset’s model. If this isn’t desired, specify the related objects you want to lock in select_for_update(of=(...)) using the same fields syntax as select_related(). Use the value 'self' to refer to the queryset’s model.
```sql
SELECT * FROM pg_stat_activity;
```
a révélé plus de 70 requêtes en attente pour des SelectedAdministrativeCriteria. D’après la description ci-dessus, le critère administratif correspondant était aussi verrouillé, ce qui limitait beaucoup la concurrence et …
> Resserrer les select_for_update() pour mieux gérer la concurrence

- itou/templates/announcements/news.html
- itou/templates/employee_record/add.html
- itou/templates/siae_evaluations/siae_select_criteria.html
- itou/templates/siae_evaluations/siae_upload_doc.html
- tests/www/announcements/__snapshots__/test_views.ambr
- tests/www/employee_record_views/__snapshots__/test_add.ambr
Certaines colonnes ont encore un breakpoint MD et parfois même en col-md-9 🙀 (alors que c'est 8/12 et 4/12, pas 9/12 ou 3/12)
LG-8 pour toutes les colonnes principales (de `<section>` directement  sous le `<main>`)
> Interface: Harmoniser les breakpoints des colonnes principales

- itou/archive/management/commands/anonymize_users.py
ajuster le monitor `sentry` à la planification de `anonymize_users`
> Vie privée: correction de la surveillance d'une tâche planifiée

- config/settings/base.py
- itou/utils/constants.py
- itou/utils/immersion_facile.py
- tests/utils/test_immersion_facile.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
Dans nos environnements de recette, on ne veut pas par accident faire une action sur la prod d'Immersion Facile (par exemple #6334).
On définit cette constante par une variable d'environnement.
Si celle-ci n'est pas définie, on pointe par défaut vers le staging de IF.
> Settings : définir `IMMERSION_FACILE_SITE_URL` par une variable d'environnement

- tests/siae_evaluations/__snapshots__/test_models.ambr
- tests/utils/test.py
- tests/www/itou_staff_views/__snapshots__/tests.ambr
- tests/www/siae_evaluations_views/__snapshots__/test_institutions_views.ambr
- tests/www/siae_evaluations_views/__snapshots__/test_siaes_views.ambr
Rollback de #6297 
cpython 3.13.5 a rollback le commit problématique. 
On verra ce qui se passera en 3.14 :shrug:
>  Tests: Remettre <genexpr> des origins dans les snapshots de requêtes

- itou/templates/apply/includes/pmsmp_box.html
- itou/templates/apply/process_base.html
- itou/utils/immersion_facile.py
- itou/www/apply/views/process_views.py
- tests/utils/test_immersion_facile.py
- tests/www/apply/test_process.py
Intégrer un encart pour informer l’employeur qu’il peut proposer une PMSMP au candidat.
Dans la page de détail d’une candidature ; ne concerne que les candidatures adressées par un prescripteur habilité
> Employeur : prescrire une PMSMP depuis les Emplois [GEN-2269]

- itou/templates/apply/includes/certification_info_box.html
- itou/templates/apply/includes/job_application_diagoriente_invite.html
- itou/utils/staticfiles.py
Le contenu des "nouvelles" `.list-data` n'étaient pas correctement affichées à l'impression des fiches candidature
Ne pas appliquer les `container-type` si `@media print` car mal supportés
En passant quelques ajustements html et css (masquage de certains éléments à l'impression)
> Interface: Correction de bugs à l'impression des fiches candidatures

- itou/archive/management/commands/anonymize_users.py
* rendre prévisible l'ordre d'anonymisation des candidats notifiés 
* ajout d'un tri sur la date de notification
> Vie privée : ajout d'un tri sur la date de notification des candidats à anonymiser

- itou/www/stats/views.py
Ajouter un encart pour les professionnels rattachés à un PLIE qui viennent d’avoir accès au TB 488. 2 webinaires ont été organisés en avril/mai pour les 275 PLIE. Seulement 28% d’acquisition. Pour capitaliser sur les webinaires ⇒ diffuser le replay sous forme d’encart dans le TB
https://www.notion.so/gip-inclusion/Encart-Ajouter-un-encart-sur-le-TB-488-pour-les-PLIE-uniquement-1f95f321b604800c8f10f74eb499699f?pvs=4
> Pilotage : Ajouter un encart sur le TB 488 pour les PLIE

- itou/eligibility/models/iae.py
- tests/eligibility/test_iae.py
- tests/www/apply/__snapshots__/test_process.ambr
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/employees_views/__snapshots__/test_detail.ambr
Avant, à partir du moment où un candidat a un PASS en cours de validité, tous ses diagnostics étaient considérés valides.
Ça paraît plus logique de restreindre `is_considered_valid` et `considered_to_expire_at` au PASS associé au diagnostic.
cf https://github.com/gip-inclusion/les-emplois/pull/6084#discussion_r2152116765
> Éligibilité : utiliser le PASS IAE associé au diagnostic pour en calculer la validité

- itou/templates/layout/_structure_switcher_nav.html
- itou/templates/layout/_structure_switcher_offcanvas.html
On change de structure, et non d’utilisateur.
> Renommer `switch{User,Structure}Dropdown`

- config/settings/base.py
Pour éviter que des locks en cascade ne bloquent toute la production.
> Tech: ajoute la possibilité de configurer un `statement_timeout`

- itou/www/employee_record_views/forms.py
- tests/www/employee_record_views/test_create.py
Un employeur est bloqué par cette vérification pour remplir l’adresse de son salarié dans sa fiche salarié. Le salarié habite à Bastia, dont le code postal est 20600, et le code INSEE 2B033.
https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement
Remplacé par une vérification que le code postal correspond à une ville.
> Fiches salarié : Retrait d’une vérification de cohérence de l’adresse

- itou/geiq_assessments/models.py
- itou/templates/geiq_assessments_views/assessment_contracts_details.html
- itou/templates/geiq_assessments_views/assessment_contracts_list.html
- itou/www/geiq_assessments_views/export.py
- itou/www/geiq_assessments_views/urls.py
- itou/www/geiq_assessments_views/views.py
- tests/www/geiq_assessments_views/__snapshots__/test_views_for_both.ambr
- tests/www/geiq_assessments_views/test_views_for_both.py
Pour faciliter les vérifications cotés GEIQ & DDETS/DREETS.
> GEIQ: ajout de l'export des données de contrats en Excel

- itou/approvals/admin.py
- itou/users/admin.py
- itou/users/utils.py
- tests/approvals/test_admin.py
Le NIR n’est pas uniquement décimal. Cette erreur a amené à une réponse erronée du support, qui ne trouvait pas la personne par son NIR.
> admin : Permettre les recherches de NIR contenant un A ou un B

- tests/www/apply/__snapshots__/test_list_for_siae.ambr
- tests/www/apply/test_list_for_siae.py
Parce que ce test problématique a causé bien de la confusion dans https://github.com/gip-inclusion/les-emplois/pull/6376
Le test construit une job_app et fait une recherche en laissant penser au lecteur que le résultat est cette unique job_app. En fait le résultat n'était pas testé et était vide, ce qui faisait que certaines requêtes SQL habituellement effectuées n'avaient pas lieu.
En corrigeant le test pour que la recherche retourne bien un résultat non vide. Du coup les requêtes SQL manquantes font surface.
> Stabilité : correctif d'un test incomplet

- itou/employee_record/serializers.py
- tests/employee_record/__snapshots__/test_serializers.ambr
- tests/employee_record/test_serializers.py
L'équipe RIAE met en prod une nouvelle version ce matin afin d'accepter les 11 caractères du nouveau format.
> Fiches Salarié : Ne plus tronquer l'identifiant France Travail lors de l'envoi à l'Extranet IAE

- config/settings/base.py
- itou/templates/429.html
- itou/utils/throttling.py
- itou/www/middleware.py
- tests/www/test_throttling.py
Sécurité : mieux identifier et bloquer les énumérations.
Afin de pouvoir effectuer un rendu complet de la page de 429, il faut que le middleware soit placé après `ItouCurrentOrganizationMiddleware`.
- Se connecter
- Beaucoup appuyer sur la touche <kbd><F5></kbd>
Le testeur malin changera la limite à une requête par minute.
> Limiter le nombre d’actions par minute pour les utilisateurs authentifiés

- itou/www/job_seekers_views/views.py
- tests/www/job_seekers_views/__snapshots__/test_details.ambr
- tests/www/job_seekers_views/test_details.py
On ne vérifie pas le type d'utilisateur dont on affiche les infos.
En pratique, ce n'est pas trop grave car on utilise un UUID. Mais quand même.
> Vie privée : empêcher `job_seekers_views:details` d'afficher les informations des utilisateurs qui ne sont pas des candidats

- tests/conftest.py
- tests/www/employee_record_views/__snapshots__/test_template.ambr
- tests/www/employee_record_views/test_template.py
Comme on utilise de plus en plus de `{% include ... with ... only %}` il est assez facile d'oublier le `csrf_token`.
> Tests: détection des oublis de `csrf_token`

- itou/archive/admin.py
Certains champs de `AnonymizedProfessional` sont manquant dans l'admin
> Vie privée : ajout de champs dans l'admin

- itou/companies/models.py
- itou/templates/apply/submit/application/jobs.html
- itou/templates/companies/includes/_card_jobdescription.html
- itou/templates/companies/includes/_list_siae_actives_jobs_row.html
- itou/templates/companies/includes/_siae_jobdescription.html
- itou/www/apply/forms.py
- itou/www/search/views.py
- tests/companies/test_models.py
- tests/www/search/__snapshots__/tests.ambr
- tests/www/search/tests.py
Au lieu d’indiquer `20+ candidatures`, afficher le badge `Soyez parmi les premiers à postuler` sur les postes qui ont reçu N ou moins candidatures récentes.  
N=0 pour commencer. Finalement N=1 et ce sera facile à ajuster (cf troisième commit).
On change la logique du badge existant : au lieu de le montrer si 20 ou plus candidatures, on le montre si N ou moins candidatures. 
Dans le futur on pourra facilement ajuster le seuil N.
> Fiche de poste : Le badge 20+ candidatures sur les résultats de recherche n’est pas compris et induit en erreur [GEN-2036]

- itou/templates/apply/submit/hire_confirmation.html
Éviter d’inclure deux foix les éléments du parent (qui par chance, sont vides pour le moment).
> Retirer un {{ block.super }} doublon dans la confirmation d’embauche

- itou/scripts/management/commands/clean_old_applied_migrations.py
- tests/scripts/test_clean_old_applied_migrations.py
```
❯ ./manage.py showmigrations | wc -l
296
❯ psql -d itou_prod -c 'select count(*) from django_migrations'
count 
-------
754
(1 row)
```
> Tech: Nettoyage des vielles migrations squashée 

- itou/archive/management/commands/anonymize_jobseekers.py
- itou/archive/management/commands/anonymize_professionals.py
- itou/archive/utils.py
- tests/archive/__snapshots__/tests_management_command.ambr
- tests/archive/__snapshots__/tests_utils.ambr
- tests/archive/tests_management_command.py
- tests/archive/tests_utils.py
reprise de #6074 suite au split de la management commande dans #6332 
prerequis #6370 (ajout & modification des modèles) et #6371 (déclaration de la management command)
Anonymiser les comptes de prescripteurs, d'employeurs et d'inspecteurs du travail, inactifs depuis 24 mois
Si le compte n'est lié à aucun objet protégé ou restreint, l'utilisater est supprimé, un `AnonymizedProfessionnal` est enregistré à la place.
Si le compte est lié à des objets protégés ou restreints, l'utilisateur est conservé, les données personnelles sont effacées sauf le nom et le prénom. L'utilisateur et ses `memberships `sont passés à l'état `is_active=False`. Son password est rendu inutilisable
> _Décrivez en quelques mots la solution retenue et mise en oeuvre, les difficultés ou problèmes rencontrés. Attirez …
> Vie privée : anonymiser les professionnels non actifs depuis plus de deux ans

- itou/companies/management/commands/_import_siae/convention.py
- itou/companies/management/commands/_import_siae/financial_annex.py
- itou/companies/management/commands/_import_siae/siae.py
- tests/companies/test_import_siae_command.py
- tests/companies/test_models.py
- tests/users/test_models.py
- tests/utils/test.py
Car c'est mieux :), et je vais avoir besoin du test pour https://github.com/gip-inclusion/les-emplois/pull/6368
> Tech : Ajout des `updated_at` manquant lors des `.save(update_fields=...)` pour l'import des SIAE

- itou/archive/management/commands/anonymize_professionals.py
- itou/archive/management/commands/notify_inactive_professionals.py
- tests/archive/__snapshots__/tests_management_command.ambr
- tests/archive/tests_management_command.py
Informer les utilisateurs professionnels qui ne se sont pas connectés depuis 700 jours (365j * 2 - 30j) de l'anonymisation de leurs données sans connection de leur part sous 30 jours.
Les utilisateurs professionnels sont du type  : `labor_inspector`, `prescriber` et `employer`
🟢 suite de #6366 
🔴 déployer à partir du 15 juillet
réutilisation dans une commande de gestion spécifique aux profesionnels, des principes utilisés pour la notification des candidats.
> Vie privée : notifier les professionnels sans activité récente

- itou/www/search/views.py
Revert partiel de 0100b5b
On pourrait probablement adapter `form_valid()` pour gérer l'absence de donnée, mais c'est plus simple comme ça (et contrairement aux filtres de candidature, on n'aura pas le problème de classe `is-valid` avec des appels htmx)
> Candidature: Correction du formulaire de recherche de poste [GEN-2588]

- itou/utils/throttling.py
- itou/www/middleware.py
- tests/www/test_throttling.py
Depuis ce matin, nous recevons environ 80K requêtes par heure, au lieu des 5K habituelles en heures de pointe.
Le traffic additionnel semble provenir de robots qui parcourent le site sans ménagement.
Modifier l’intergiciel de régulation du trafic qui existait pour les utilisateurs connectés afin qu’il limite également le trafic pour les requêtes anonymes.
> Limiter l’accès au site à 30 requêtes par minute

- itou/templates/apply/includes/job_seeker_info.html
- tests/www/apply/test_details.py
On a un beau "Non renseigné" pour ça.
Cela impactait le détail de candidature, le détail des fiches salarié, le détail des candidats.
J'ai rajouté un fichier de test `tests/www/apply/test_details.py` pour ne pas alourdir davantage les fichiers de tests de `apply` existants.
Avant :
Après :
> Candidature : ne pas afficher `None` si des informations concernant le candidat sont manquantes

- itou/approvals/models.py
- itou/www/approvals_views/forms.py
- tests/approvals/test_admin.py
- tests/approvals/tests.py
Le support est bloqué car des utilisateurs demandent à changer la date de début des suspensions. Actuellement, la limite est fixée à la date de création de la suspension pour le support seulement. Les utilisateurs finaux peuvent faire commencer la suspension jusqu'à 365 jours avant sa date de création (`Suspension.MAX_RETROACTIVITY_DURATION_DAYS`). 
Ce comportement a été introduit [dans cette PR](https://github.com/gip-inclusion/les-emplois/pull/1038).
Aujourd'hui, le support a oublié que c'était une demande métier et se retrouve simplement coincé. Il crée des tickets Supportix. Sandrine et Zohra pensent que le plus simple et que tout le monde suive la même règle.  
Cette PR est liée à la PR #6243 . Le support a mis à jour manuellement la date de fin des PASS IAE mais ne peut pas …
> Admin : permettre la modification de la date de début des suspensions si la nouvelle date est avant la date de création

- tests/communications/test_campaigns.py
Les candidats ne voient pas tous les éléments des annonces. Si `random_user_kind_factory` renvoie `JobSeekerFactory` et que les `AnnouncementItemFactory` ont du `user_kind_tags` sans `UserKind.JOB_SEEKER`, alors le test casse.
https://github.com/gip-inclusion/les-emplois/actions/runs/16073642999/job/45363693853
Solution retenue : aligner le `user_kind_tags` sur le type d'utilisateur pour être sûr que celui-ci soit concerné par l'annonce.
> Tests : correction d'un test bagottant sur la modale de nouveauté

- config/settings/test.py
- tests/communications/test_admin.py
- tests/conftest.py
- tests/files/tests.py
- tests/www/announcements/test_views.py
- tests/www/apply/test_process_external_transfer.py
- tests/www/apply/test_submit.py
- tests/www/approvals_views/test_prolongation.py
- tests/www/approvals_views/test_prolongation_requests.py
- tests/www/geiq_assessments_views/test_views_for_geiq.py
- tests/www/siae_evaluations_views/test_siaes_views.py
- tests/www/siae_evaluations_views/test_views.py
Sinon on continue d'utiliser un bucket fourre-tout, en dev et sur la CI :
Supprimer le bucket `c1-tests` de votre minio local et lancer les tests
> Tech : Rendre l'usage de `temporary_bucket` obligatoire

- config/settings/base.py
- itou/templates/account/email/email_confirmation_subject.txt
- itou/templates/account/email/password_reset_key_subject.txt
- itou/templates/layout/base_email_signature.txt
- itou/utils/emails.py
- itou/utils/enums.py
- scripts/create-fast-machine.sh
c1-worker est maintenant utilisé pour la plupart des commandes. L’environnement `FAST-MACHINE` étant moins utilisé, il sera moins bien maintenu. Autant tout basculer sur PROD et éviter la gestion d’un autre environnement.
> Retirer l’environnement FAST-MACHINE

- itou/files/management/commands/find_orphan_files.py
Éviter de maintenir la liste des fichiers dans l’app, et surtout d’oublier de le faire.
> find_orphan_files : Découvrir les relations à `File`

- itou/utils/db.py
- itou/utils/management/commands/migrate.py
Lorsque plusieurs instances de l’application servent le trafic web, CleverCloud construit une nouvelle instance pour chaque instance au déploiement. Ainsi, la commande `django-admin migrate` est appelée plusieurs fois au cours d’un seul déploiement, sans gestion de la concurrence.
Les opérations DDL étant transactionnels sur PostgreSQL, il n’y aura pas de conflits dans la plupart des cas. En revanche, les migrations de données ont souvent `atomic=False` pour éviter les longues transactions, et pourraient être exécutées en parallèle, ce qui risquerait de dupliquer le travail pour la base de données, voire de corrompre les données.
Utilisation des _advisory locks_ de PostgreSQL pour empêcher l’exécution concurrente des migrations sur la base de données.
Voir le message de commit pour plus …
> Empêcher les migrations de base de données en parallèle

- tests/www/approvals_views/test_prolongation_requests.py
3 tests dans `test_prolongation_requests.py` écrasais directement `default_storage.location`, cet écrasement était maqué par l'ancienne fixture `storage_prefix_per_test` qui n'existe plus depuis https://github.com/gip-inclusion/les-emplois/pull/6464.
A voir si on garde le commit pour 1 bucket par session ou pas.
En local avec le minio, trois possibilités :
- `pytest -p no:randomly -v tests/www/approvals_views/test_prolongation_requests.py::test_show_view tests/communications/test_admin.py`
- `pytest -p no:randomly -v tests/www/approvals_views/test_prolongation_requests.py::test_show_view_no_siae tests/communications/test_admin.py`
- `pytest -p no:randomly -v tests/www/approvals_views/test_prolongation_requests.py::test_snapshot_by_status tests/communications/test_admin.py`
> Tech : Correction pour les tests utilisant `temporary_bucket` échouant "aléatoirement" sur la CI

- itou/companies/management/commands/deactivate_old_job_descriptions.py
- tests/companies/test_management_commands.py
Après avoir désactivé les fiches de poste vieilles de 2 ans, on continue avec celles vieilles de 1 an (13% des fiches actives restantes)
> Employeur: Désactivation des fiches de poste non mises à jour depuis plus de 1 ans [GEN-2585] 

- tests/conftest.py
Aurait attrapé https://github.com/gip-inclusion/les-emplois/pull/6517.
Patchy, en attendant de corriger upstream.
> Vérifier la génération des fichiers Excel de manière plus stricte

- itou/templates/apply/includes/siae_batch_actions.html
- itou/templates/apply/list_for_siae.html
Annoncer le changement de fonctionnement de la barre d’actions pour les nouvelles candidatures
Ajouter un IntroJS sur la `list_for_siae`, lancé au `htmx:load`. 
Si le bouton "Accepter" est présent dans la barre d'action (donc si les employers `can_accept`), on lance le IntroJS qui ne s'affichera qu'une fois.
Pour tester plusieurs fois, il faut supprimer le cookie `introjsBatchActionsDontShowAgain`
> Interface: Annoncer le fonctionnement de la barre d’actions avec les "nouvelles" candidatures

- itou/www/geiq_assessments_views/views.py
Afin de préparer l'arrivée d'une fonction `save_file` qui enregistera le fichier dans le S3 et créera le File associé en base de données, il est nécessaire de modifier cette petite portion de code. Lié à la PR #6037 en cours de découpage.
> [Fichiers] Utiliser un wrapper dans geiq-assessments

- itou/www/geiq_assessments_views/views.py
- tests/www/geiq_assessments_views/test_views_for_geiq.py
Ils n'étaient pas dans un dossier alors que tous les autres fichiers de nos applications le sont.
Ajout du préfixe "geiq-assessment" à la clé.
> [Fichiers] Ranger les fichiers GEIQ dans un « dossier » S3

- itou/approvals/models.py
- itou/companies/management/commands/sync_pec_offers.py
- itou/jobs/management/commands/sync_romes_and_appellations.py
- itou/prescribers/management/commands/sync_ft_organizations.py
- itou/users/management/commands/pe_certify_users.py
- itou/utils/apis/__init__.py
- itou/utils/apis/pole_emploi.py
- tests/users/test_management_commands.py
- tests/utils/apis/test_pole_emploi_api.py
Pour préparer l'arrivée de la certification RQTH, il faut intégrer les nouveaux périmètres qui sont sous le royaume `Agent`. L'authentification est identique au royaume `Partenaire`, seuls les périmètres diffèrent.
Deux classes enfant qui héritent d'une même classe Parent permet de distinguer les deux périmètres et les deux royaumes tout en partageant les méthodes communes.
Cette PR modifie le fonctionnement actuel. Une autre PR viendra pour intégrer le nouveau royaume Agent.
Création d'une classe parent et utilisation dans la classe actuelle. Changement du nom actuel.
Tout est couvert par les tests automatisés.
> [API] FranceTravail.io : création d'une classe parent

- itou/approvals/admin.py
- itou/files/admin.py
- itou/files/models.py
- itou/job_applications/models.py
- itou/siae_evaluations/admin.py
- itou/www/approvals_views/views.py
- itou/www/geiq_assessments_views/views.py
- itou/www/siae_evaluations_views/views.py
- tests/files/tests.py
- tests/www/approvals_views/test_prolongation_requests.py
- tests/www/siae_evaluations_views/test_views.py
Pour éviter d'importer default_storage partout.
Il reste la question du téléchargement des fichiers geiq où l'on passe un paramètre supplémentaire pour définir le nom du fichier. On pourrait mettre une fonction `get_url()` à la place pour permettre de passer des kwargs additionnels
> Tech: Ajout de propriétés sur les `File` pour construire les urls

- itou/job_applications/admin.py
Éviter des mauvaises manips dans l’admin. Améliorer l’affichage en enlevant des textarea.
> Admin : Passer les champs texte des candidatures en lecture seule

- clevercloud/cron.json
Démarrer l'archivage des professionnels sans notification récente
Planification de la tâche dans la `crontab`
> Vie privée : activer la notification des professionnels sans activité récente

- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/metabase/tables/job_applications.py
- tests/metabase/management/test_populate_metabase_emplois.py
Pour prendre en compte ces candidatures dans les tableaux de bord.
https://www.notion.so/gip-inclusion/Remplacer-intitul-auto-dans-les-motifs-de-refus-2015f321b60480278f71cb43d191b96f?source=copy_link
> Add auto refused applications to metabase table

- itou/companies/perms.py
- itou/templates/dashboard/includes/employer_company_card.html
- itou/users/models.py
- itou/www/companies_views/views.py
- itou/www/dashboard/views.py
- tests/users/test_models.py
- tests/users/test_perms.py
- tests/www/dashboard/__snapshots__/test_dashboard.ambr
- tests/www/dashboard/test_dashboard.py
Cette méthode sera bientôt appelée à chaque requête, car l’option pour créer une antenne se déplace du tableau de bord vers le menu, qui est présent sur toutes les pages.
> Économiser une requête sur can_create_siae_antenna

- clevercloud/cron.json
- itou/companies/management/commands/import_ea_eatt.py
- itou/employee_record/management/commands/transfer_employee_records.py
- itou/employee_record/management/commands/transfer_employee_records_updates.py
- itou/metabase/management/commands/populate_metabase_matomo.py
- tests/companies/__snapshots__/test_import_ea_eatt.ambr
- tests/companies/test_import_ea_eatt.py
Les moulinettes de l'équipe EA2 de l'ASP ne tournent semble t-il pas les jours fériés, mais rattrape tout de même le lendemain... Donc pour tout les lundi fériés le fichier est accessible à partir du mardi.
Voir le commit.
J'étais parti pour utiliser [holidays](https://pypi.org/project/holidays/) afin d'expliciter cette logique mais vu que le code le gère déjà sans je me dit qu'on peux s'épargner une dépendance à usage unique.
> Import EA/EATT : Gérer le cas des lundi fériés

- itou/approvals/management/commands/prolongation_requests_chores.py
- itou/archive/management/commands/notify_inactive_jobseekers.py
- itou/archive/management/commands/notify_inactive_professionals.py
- itou/asp/management/commands/sync_communes.py
- itou/companies/management/commands/import_ea_eatt.py
- itou/companies/management/commands/import_geiq.py
- itou/companies/management/commands/import_siae.py
- itou/emails/management/commands/delete_old_emails.py
- itou/employee_record/management/commands/archive_employee_records.py
- itou/employee_record/management/commands/employee_record.py
- itou/employee_record/management/commands/resend_employee_records.py
- itou/employee_record/management/commands/unarchive_employee_records.py
- itou/metabase/management/commands/metabase_data.py
- itou/prescribers/management/commands/sync_ft_organizations.py
- itou/scripts/management/commands/add_admin_for_company_group.py
- itou/scripts/management/commands/create_asp_employee_records.py
- itou/siae_evaluations/management/commands/evaluation_campaign_notify.py
- itou/users/management/commands/sync_group_and_perms.py
- itou/utils/command.py
Erreur en prod :
[LES-EMPLOIS-PROD-E5](https://inclusion.sentry.io/issues/51937791/)
[LES-EMPLOIS-PROD-E6](https://inclusion.sentry.io/issues/51978404/)
Le `set_config()` est local donc si il est appelé en dehors d'un bloc transactionnel la valeur est "perdue".
Ce n'est pas visible dans les tests car une transaction est ouverte par défaut, donc à défaut je lève une exception dans `triggers.context()` si on n'est pas dans un bloc _atomic_ afin d'orienter plus facilement sur le problème :).
Lancer l'import SIAE ou `metabase_data stalled-job-seekers --wet-run`
> Tech : Correction du contexte manquant pour les management commands

- itou/users/models.py
- tests/users/test_models.py
Cet identifiant permet à FT de faciliter le calcul du référent (c'est a priori une PK de leur datalake).
Si une partie des informations de l'utilisateur change, il faut que FT vérifie et nous renvoie l'identifiant pour qu'on soit sur de récupérer le bon référent.
> GPS: Nettoyage automatique de l'ID unique utilisé lors des échanges avec FT si les informations du compte candidat changent

- clevercloud/cron.json
- itou/archive/management/commands/notify_inactive_professionals.py
Le stock de professionnels notifiables est trop important par rapport nombre de professionnels effectivement notifiés par jour
Passer de 1 à 3 execution de la management command par jour
> Vie privée : ajuster le nombre de professionnels notifiés par jour

- itou/utils/admin.py
La clé primaire est souvent requise pour les `raw_id_fields`, par exemple pour les demandes de prolongation. L’afficher fréquemment évite des actions supplémentaires pour trouver la clé primaire d’une organisation.
> admin : Afficher la PK de la structure

- itou/www/apply/views/edit_views.py
- tests/www/apply/test_edit.py
Suivre plus facilement les modifications des dates des contrats (`hiring_start_at` et `hiring_end_at`).
> Candidature : Ajout de logs sur la modification des dates du contrat

- itou/www/stats/utils.py
- itou/www/stats/views.py
- tests/www/stats/test_utils.py
- Limiter les erreurs :
[LES-EMPLOIS-PROD-9W](https://inclusion.sentry.io/issues/45759330/)
[LES-EMPLOIS-PROD-AN](https://inclusion.sentry.io/issues/46708856/)
[LES-EMPLOIS-PROD-C2](https://inclusion.sentry.io/issues/49901552/)
[LES-EMPLOIS-PROD-96](https://inclusion.sentry.io/issues/44630899/)
- Plus explicite sur l'attendu d'avoir la gestion d'accès à l'entrée de la vue que 2 ou 3 appels de fonction plus tard
> Pilotage - Tableau de bord : Vérification des droits en amont plutôt qu'en aval

- itou/templates/apply/list_prescriptions.html
Il y a eu suffisamment de prises de rendez-vous.
https://gip-inclusion.slack.com/archives/CU8ATF54L/p1753428999514309?thread_ts=1753340123.606429&cid=CU8ATF54L
> Prescripteur : Supprimer le bandeau de prise de rendez-vous d'entretiens utilisateur

- tests/archive/__snapshots__/tests_management_command.ambr
- tests/archive/tests_management_command.py
cf titre
retourner des listes au lieu de `queryset` pour l'évaluation des snapshots
> Vie privée : rendre les snapshots plus lisibles dans les tests

- itou/static/css/itou.css
- itou/templates/includes/btn_dropdown_filter/checkboxes.html
- itou/templates/includes/btn_dropdown_filter/radio.html
- itou/templates/search/includes/siaes_search_content.html
- itou/templates/search/includes/siaes_search_filters_departments.html
- itou/templates/search/prescribers_search_results.html
Sur petits écrans les menus déroulants de la recherche (Distance, Types de structure…) sont orientés vers le haut.
Ils rentrent en conflit avec la section titre `s-title-02` qui est sticky, et qui a un `z-index` supérieur.
Certaines valeurs sont donc inaccessibles.
Ce problème arrive plus fréquemment depuis 5739c32bc4cb081e8bcde8f6a9d529fa58654dee, avec le changement de breakpoints.
En attendant que @hellodeloo  puisse réorganiser le `z-index` des différents éléments dans le thème (ou toute autre solution qu'il trouvera pertinente), voilà un correctif temporaire.
cf https://gip-inclusion.slack.com/archives/C01181Y04LT/p1753692325909599
Avant : 
Après :
> Recherche employeur : Correctif temporaire permettant d'afficher le menus déroulants (distance, type de structure…) au-dessus du titre et des onglets

- itou/www/login/forms.py
Le login en tant que superutilisateur nécessite la saisie d'un code OTP dans une page de formulaire dédié. Ce champ unique n'est pas `autofocus` et necessite une action supplémentaire avant de saisir le code (tab ou clic souris)
Ajouter l'attribut `autofocus` au champ `opt_token`
> Admin : autofocus sur le champ de saisie du code OTP

- itou/companies/management/commands/import_geiq.py
- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/utils/python.py
- tests/metabase/management/test_populate_metabase_emplois.py
Doublon avec le comportement dans notre classe de base et très peu utile dans les 2 derniers endroits l'utilisant.
> Tech : Suppression de `@timeit`

- itou/www/invitations_views/views.py
- tests/www/invitations_views/test_generic.py
Une erreur est remontée : https://inclusion.sentry.io/issues/53631664
> Invitations : vérifier que request.current_organization n'est pas None avant de l'utiliser

- itou/www/companies_views/views.py
- tests/www/companies_views/__snapshots__/test_card_views.ambr
- tests/www/companies_views/__snapshots__/test_job_description_views.ambr
- tests/www/companies_views/test_card_views.py
Les fiches de poste et fiches des entreprises désactivées (`company.is_searchable=False`) ne sont pas accessibles via la recherche, mais peuvent rester indexées dans d'autres moteurs de recherche.
Servir une 404.
> Fiche entreprise, fiche de poste : Arrêter de servir les fiches des entreprises désactivées [GEN-2627]

- config/settings/base.py
- itou/eligibility/models/common.py
- tests/eligibility/test_iae.py
Avec l'arrivée de la certification RQTH, 3 nouvelles requêtes seront exécutées dans la méthode `certify_criteria` si le critère TH est sélectionné. Ces appels risquent d'allonger la durée de la requête pour l'utilisateur final qui devra simplement attendre que toutes les API aient rendu leur verdict.
Il y a néanmoins un désavantage : si le critère est en cours de certification, le badge affichera « Critère non certifié » car c'est le fonctionnement actuel. Une PR suivra pour proposer d'autres intitulés.
Rendre l'appel asynchrone par défaut et mettre en place un _feature flag_ pour revenir rapidement en arrière si les utilisateurs sont perdus.
> [Certification] Certifier de manière asynchrone via un feature flag

- itou/approvals/management/commands/send_approvals_to_pe.py
- itou/approvals/models.py
- itou/jobs/management/commands/sync_romes_and_appellations.py
- itou/users/management/commands/pe_certify_users.py
- itou/utils/apis/pole_emploi.py
- tests/jobs/management/test_sync_romes_and_appellations.py
- tests/utils/apis/test_pole_emploi_api.py
Réutiliser le client HTTPX permet de réutiliser la connexion TCP (au lieu d'en recréer une pour chaque requête) entre plusieurs requêtes consécutives.
[Lire la documentation pour en savoir plus](https://www.python-httpx.org/advanced/clients/#why-use-a-client)
Voir aussi  https://github.com/gip-inclusion/les-emplois/pull/4971/commits/487faee04ceffd2c8178e53bca9381739cd07e24
Ajout d'un client HTTP privé à la classe pour créer un client réutilisable entre chaque requête lorsque `pole_emploi_agent_pole_emploi_partenaire_api_client` est utilisé en gestionnaire de contexte.
> [API] Pole emploi : utilisation d'un client en gestionnaire de contexte

- itou/templates/gps/group_memberships.html
- tests/gps/__snapshots__/test_views.ambr
Les `button` étant dans un `<form>`, ils étaient de type `submit` ce qui ne plait plus à htmx
> GPS: Correction de l'affichage des informations personnelles des intervenants

- clevercloud/cron.json
- config/settings/dev.py
- itou/metabase/management/commands/upload_data_to_pilotage.py
- tests/metabase/management/__snapshots__/test_upload_data_to_pilotage.ambr
- tests/metabase/management/test_upload_data_to_pilotage.py
Il arrive régulièrement que le fichier téléversé soit incomplet, même sans mise en prod, mais cela n'arrive jamais quand on relance la commande manuellement...
Dans la version actuelle de la commande, il faut aller supprimer le fichier dans la console scaleway et ensuite relancer la commande, ce qui n'est pas très pratique :).
@leo-naeka Je te met en relecteur vu que tu es le prochain SupportiX, donc si tu veux t'éviter du boulot dans les prochaines semaines c'est le bon moment :grin:.
> Pilotage : Rendre le téléversement du flux IAE plus robuste

- itou/templates/companies/card.html
- itou/templates/companies/includes/_card_siae.html
- itou/templates/companies/job_description_card.html
- tests/www/apply/test_process_external_transfer.py
- tests/www/companies_views/__snapshots__/test_card_views.ambr
- tests/www/companies_views/test_card_views.py
Les boutons “Postuler” et "Transférer la candidature" sont en doublons, car déjà présent dans la barre d'action
- Mise a jour du graissage (font-weight) des icones `ri-draft-line`
- Remplacement de l'icone `ri-draft-line` de "Transférer la candidature" par `ri-arrow-left-right-line`
> Interface: Supprimer les boutons “postuler/transferer” en doublon dans les fiches structures

- clevercloud/cron.json
FT subit toujours des erreurs 500 en été.
Complément de #5945
Clever étant en UTC, élargissement de l'intervalle à `[22:00 ; 0:00[ ` pour couvrir l'indisponibilité de l'API FT en écriture tant en CET qu'en CEST.
> PASS IAE: Ne plus envoyer les PASS à FT entre minuit et 1h CET/CEST [GEN-2651]

- itou/static/css/itou.css
- itou/templates/includes/btn_dropdown_filter/checkboxes.html
- itou/templates/includes/btn_dropdown_filter/radio.html
- itou/templates/search/includes/siaes_search_content.html
- itou/templates/search/includes/siaes_search_filters_departments.html
- itou/templates/search/prescribers_search_results.html
- tests/www/apply/test_list_for_siae.py
Cf https://github.com/gip-inclusion/les-emplois/pull/6615
Via l'utilsation du `data-bs-display="static"`
> Recherche employeur: Forcer l'ouverture des menus déroulants (distance, type de structure…) par le dessous

- itou/templates/dashboard/includes/dashboard_title_content.html
- tests/www/dashboard/__snapshots__/test_dashboard.ambr
- tests/www/dashboard/test_dashboard.py
Pour faciliter les échanges avec le support ? (la carte notion n'explique pas pourquoi on a besoin que ce soit plus simple pour le candidat de retrouver son ID)
La maquette présente aussi un bouton dans le menu de gauche, mais ce n'est pas indiqué dans la carte notion :shrug: 
On verra en recette
> Candidat: Permettre de copier son ID candidat depuis le tableau de bord [GEN-2567]

- itou/templates/employees/detail.html
- itou/utils/immersion_facile.py
- itou/www/employees_views/views.py
- tests/www/employees_views/__snapshots__/test_detail.ambr
- tests/www/employees_views/test_detail.py
Vu avec Eric et Nathalie (IF), comme on a retiré l’autre encart à la demande de la DGEFP, on peut se permettre d’ajouter un lien pour initier une convention ça reste dans le cadre autorisé par la DGEFP.
Sur les pages de profil salariés, on va ajouter un nouveau lien "Initier une convention" dans l’encart IF  : https://immersion-facile.beta.gouv.fr/initier-convention?mtm_campaign=les-emplois-recherche-immersion&mtm_kwd=les-emplois-recherche-immersion 
en dessous du lien existant "Rechercher une immersion".
> Profil salarié : Ajout d’un lien supplémentaire dans l’encart IF [GEN-2648]

- itou/utils/templatetags/badges.py
Pour garder les badges de statut alignées en debut de colonne
https://www.notion.so/gip-inclusion/18a5f321b604815dae97d270c3aaec68?v=18a5f321b604811bad80000cf7934cee&p=2535f321b6048044abaffae497be80ce&pm=c
> Interface: Placer le badge d'archivage après le badge du statut de candidature

- config/settings/base.py
- itou/metabase/management/commands/populate_metabase_emplois.py
- itou/metabase/management/commands/populate_metabase_matomo.py
Pour clarifier que ces messages sont destinés à #pilotage-tech-notifications.
C'est rétro-compatible vu qu'on fallback sur le settings existant (`SLACK_CRON_WEBHOOK_URL`):
https://github.com/gip-inclusion/les-emplois/blob/2475bd9a107ef690536a7753be2d55fd01c4c523/itou/utils/slack.py#L17
> Tech: ajout du setting `PILOTAGE_SLACK_WEBHOOK_URL`

- itou/openid_connect/france_connect/apps.py
- itou/openid_connect/france_connect/views.py
- itou/status/probes.py
- itou/templates/static/legal/terms.html
- itou/users/adapter.py
- itou/www/dashboard/forms.py
- tests/openid_connect/france_connect/tests.py
Pour être prêt pour la version 2 de FranceConnect:
https://docs.partenaires.franceconnect.gouv.fr/fs/migration/fs-migration-diff-v1-v2/#accordion-blMhW51TdMHL0TuUewk4E-8
En restant compatible avec la version 1 qui ne founit pas ces codes d'erreur.
> FranceConnect: gestion des cas d'erreur pour le passage à la version 2

- itou/templates/account/email/email_jobseeker_created_by_third_party_body.txt
- itou/templates/account/email/email_jobseeker_created_by_third_party_for_gps_body.txt
- tests/users/__snapshots__/test_models.ambr
Phrase qui n’est pas bien comprise par nos utilisateurs, de nombreuses demandes arrivent.
Plus de 80% des demandes n’aboutissent pas à une suppression car l’utilisateur n’avait pas compris l’impact de sa demande.
> Vie privée : retrait d'une mention RGPD incomprise causant beaucoup de demande au support [GEN-2678]

- itou/employee_record/admin.py
- tests/employee_record/test_admin.py
Lorsque c’est possible, ajouter le nom, le type et la PK de l’entreprise. Dans le cas où l’annexe financière n’est pas disponible (supprimée), continuer d’afficher simplement le SIRET.
> Admin : Enrichir les fiches salarié avec les détails de l’entreprise

- itou/templates/companies/job_description_list.html
- tests/www/companies_views/test_job_description_views.py
La ligne est en haut du tableau, elle est assez visible, on n'a pas besoin de la voir à chaque page.
Prérequis : #6652
> Fiche de poste : N'afficher l'entrée dédiée aux candidatures spontanées que sur la première page de la liste

- tests/metabase/conftest.py
- tests/metabase/management/__snapshots__/test_populate_metabase_emplois.ambr
- tests/metabase/management/test_populate_metabase_emplois.py
- tests/utils/testing.py
Dans les tests de `populate_metabase_emplois` et `metabase_fixture` on récupère un curseur depuis la connexion Django, on a donc l'instrumentation des requêtes, raison de pourquoi `assertNumQueries()` fonctionne, mais pas toutes les métadonnées habituelles.
Le cas d'utilisation est assez limité mais le changement étant simple et que ça simplifie pas mal la vie d'avoir les requêtes SQL plutôt que juste des `+= 1` je propose le changement, surtout que ça m'a permis de trouver une amélioration (-50%, -30s) pour le script donc ça peux être utile sur le long terme.
> Tech : `assertSnapshotQueries()` pour les curseurs DBAPI d'une connexion Django

- itou/openid_connect/france_connect/models.py
- tests/openid_connect/france_connect/tests.py
- tests/www/signup/test_job_seeker.py
FranceConnect nous le fournit déjà en v1 et continuera de le fournir en V2: autant l'utiliser.
> FranceConnect: récupération du genre de l'utilisateur

- config/settings/base.py
- itou/eligibility/models/common.py
- tests/eligibility/test_iae.py
- tests/utils/apis/test_api_particulier.py
La méthode qui certifie les critères peut déjà émettre 3 requêtes HTTP vers l’API Particulier. Si cette API est lente, tout le site peut tomber.
L’ajout de la certification de la RQTH ajoutera 2 ou 3 requêtes supplémentaires, vers l’API de France Travail. Si cette API est lente, tout le site peut tomber.
Grâce à l’ajout de badges pour la certification (https://github.com/gip-inclusion/les-emplois/pull/6755), les utilisateurs sont maintenant informés que la certification est en cours. Ils pourront ainsi patienter si le résultat de la certification n’arrive pas immédiatement.
> Éligibilité : Ne pas certifier les critères au sein de la requête web

- itou/www/signup/views.py
- tests/www/signup/__snapshots__/test_siae.ambr
- tests/www/signup/test_siae.py
L’admin ne pourra inviter personne dans la structure.
> Employeur : Ne pas recommander de contacter un admin inactif à l’inscription

- itou/archive/management/commands/anonymize_jobseekers.py
- tests/archive/tests_management_command.py
Une candidature n'est pas supprimable lorsqu'elle est liée à une fiche salariée.
1.correction de données incohérentes sur le PASS 79234, en prérequis de cette PR
2.ajout de la suppression de `EmployeeRecord` dans la commande `anonymize_jobseekers`
3.ajout d'un commentaire prevenant d'une issue similaire avec les `EvaluatedJobApplication`
#6775 et #6785 doivent être toutes les deux fusionnées avant de relancer le traitement d'anonymisation des candidats
> Vie privée : suppression de la fiche salariée lors de l'archivage du candidat

- itou/templates/companies/deactivate_member.html
- itou/templates/companies/update_admins.html
- itou/templates/includes/deactivate_member.html
- itou/templates/includes/update_admin.html
- itou/templates/institutions/deactivate_member.html
- itou/templates/institutions/update_admins.html
- itou/templates/prescribers/deactivate_member.html
- itou/templates/prescribers/update_admins.html
Ecrans qui datent un peu
**Avant**
**Apres**
---
**Avant**
**Apres**
> Interface: Amélioration des templates de retrait des collaborateurs de structure

- itou/templates/dashboard/dashboard.html
https://www.notion.so/gip-inclusion/Supprimer-bandeau-d-alerte-pour-une-enqu-te-Maze-2535f321b60480a0bf9ad676395ae4d8?d=6765f321b604826dab6f8329344dbef6
Dans la zone d'alerte
> Prescripteur: Suppression d'un bandeau d’alerte pour une enquête Maze

- itou/archive/management/commands/anonymize_professionals.py
- itou/archive/migrations/0014_delete_emailadress_of_anonymized_professionals.py
- tests/archive/tests_management_command.py
Les professionnels à anonymiser, liés à des objets dans la base de données, ne peuvent pas être supprimés. Ils sont simplement anonymisés, càd notamment que la valeur de leur email est mis à `None`.
Les professionnels à anonymiser, non liés à des objets dans la base de données, sont effacés. Le modèle `EmailAddress` est `on_delete=Cascade`. Ces cas ne sont pas concernés.
1. Compléter l'anonymisation est supprimant l'objet `EmailAddress`
2. Reprise du stock
> Vie privée : supprimer EmailAddress (allauth) des professionnels anonymisés mais non effacés

- itou/asp/forms.py
- itou/asp/models.py
- itou/employee_record/serializers.py
- itou/users/migrations/0039_jobseekerprofile_jobseekerprofile_birth_country_and_place.py
- itou/users/models.py
- itou/utils/validators.py
- tests/asp/test_countries.py
- tests/asp/test_sync_communes.py
- tests/companies/factories.py
- tests/conftest.py
- tests/employee_record/__snapshots__/test_serializers.ambr
- tests/employee_record/test_serializers.py
- tests/gps/test_views.py
- tests/invitations/factories.py
- tests/users/factories.py
- tests/users/test_models.py
- tests/www/apply/test_process.py
- tests/www/apply/test_submit.py
- tests/www/companies_views/test_job_description_views.py
- tests/www/dashboard/test_edit_user_info.py
- tests/www/employee_record_views/__snapshots__/test_template.ambr
- tests/www/employee_record_views/test_create.py
- tests/www/employee_record_views/test_template.py
- tests/www/job_seekers_views/test_create_or_update.py
- tests/www/job_seekers_views/test_list.py
- tests/www/signup/test_job_seeker.py
Cette règle métier est vérifiée dans les formulaires mais pas dans l'admin, et donc parfois on se tombe sur un os suite à une modification manuelle, ce qui bloque ensuite la transmission des FS,
A noter qu'actuellement nous n'avons aucun cas en erreur ;).
Une contrainte `CHECK` n'a accès qu'au du tuple inséré donc je fige la PK de `birth_country` dans la contrainte et ajoute des tests afin de détecter un changement de clé primaire.
J'aime pas spécialement mais vu que c'est un référentiel et que ça vient d'une fixture ça me semble tout de même acceptable si ça nous évite des incohérences de données (que j'aime encore moins :grin:).
> Candidat : Ajout d'une contrainte pour la cohérence entre le pays et la ville de naissance

- config/settings/base.py
- itou/utils/apis/esd.py
- itou/utils/apis/pole_emploi.py
- tests/approvals/test_notify_pole_emploi.py
- tests/companies/test_sync_ft_offers.py
- tests/external_data/tests.py
- tests/job_applications/tests.py
- tests/jobs/management/test_sync_romes_and_appellations.py
- tests/openid_connect/pe_connect/tests.py
- tests/users/test_management_commands.py
Préparer à l’arrivée de `AUTH_BASE_URL_AGENT` pour la RQTH.
> Renommer API_ESD["AUTH_BASE_URL{,_PARTENAIRE}"]

- itou/approvals/admin.py
- tests/approvals/test_admin.py
Les suspensions et prolongations ont normalement lieu pendant la durée de vie du PASS.
~550 suspensions et ~26 prolongations n'ont apparemment pas reçu l'information :see_no_evil: 
> Tech: ajout de nouveau test de cohérence pour les dates de prolongation

- .github/workflows/review-app-creation.yml
La création des review apps plantaient lamentablement.
En cause : `clever-tools` v4.1.0 qui plante à présent si on essaie de lier une app déjà liée.
https://github.com/CleverCloud/clever-tools/blob/master/CHANGELOG.md#410-2025-09-17 ([commit](https://github.com/CleverCloud/clever-tools/commit/157f5285711f591768377b7c7116c534adfd9c80)).
> Tech : Réparer la création des applications de recette

- itou/utils/apis/metabase.py
Suite à la mise en place d'une v2 pour deux TBs ETP, changement du bon id_dashboard pour le TB SIAE et ajout des TBs DREETS et DDETS oubliés lors de la PR https://github.com/gip-inclusion/les-emplois/pull/6889
> [Metabase]  Changement de l'id des TBs metabase etp (SIAE & DREETS/DDETS)

- itou/utils/templatetags/nav.py
- tests/approvals/tests.py
- tests/www/__snapshots__/test_layout.ambr
https://www.notion.so/gip-inclusion/ETQ-prescripteur-habilit-j-ai-acc-s-la-prolongation-des-PASS-IAE-menu-de-gauche-1a55f321b60480af9a6dc3a09493fd89?v=18a5f321b604811bad80000cf7934cee&source=copy_link
> Prescripteur: Ajout d'un accès aux demandes de prolongation dans le menu de gauche pour les prescripteurs habilités

- itou/utils/apis/metabase.py
Changement de l'id_dashboard suite à la mise en place d'une nouvelle version pour le TDB "facilitation à l'embauche".
> change id to get new facilitation embauche dashboard

- itou/employee_record/management/commands/employee_record.py
- itou/employee_record/models.py
- tests/employee_record/test_employee_record_command.py
Pour pouvoir renvoyer une fiche salarié existante sur un ancien SIRET.
> Fiche salarié: correction de l'utilitaire `employee_record`

- docker-compose.yml
Suite à l'acquisition de Bitnami par Broadcom, les images gratuites de la communauté ne sont plus disponibles et Bitnami ne propose plus que des images "secure" dans leur plan payant.
Cf. https://github.com/bitnami/containers/issues/83267
Utilisation de l'image officielle
Ça concerne l'environnement local.
J'ai testé l'accès à des blob uploadés avec l'ancienne l'image, l'upload de nouveaux et la création du bucket via `make buckets`. RAS.
> MinIO : utilisation de l'image officielle

- tests/job_applications/tests.py
Les noms aléatoires des candidats peuvent être suffisamment courts pour être similaires à des mots dans la candidatures.
eg:
```
pytest tests/job_applications/tests.py::TestJobApplicationNotifications::test_cancel_sent_by_prescriber --randomly-seed=152003495
pytest tests/job_applications/tests.py::TestJobApplicationNotifications::test_new_for_prescriber --randomly-seed=3464864558
```
> Candidatures : débagottage de tests

- itou/templates/includes/structures/_structure_info.html
- tests/www/apply/__snapshots__/test_submit.ambr
- tests/www/apply/__snapshots__/test_submit_from_job_seekers_list.ambr
- tests/www/approvals_views/__snapshots__/test_prolongation_requests.ambr
- tests/www/prescribers_views/test_overview.py
Le dropdown de la box `.c-box--structure` retournait l'erreur suivante
> Because The element button must not appear as a descendant of an element with the attribute role=button dans `class="c-box--structure__summary"`
De plus le dropdown ne s'actionnait pas au clavier (ouverture/fermeture avec entrée) et le titre de niveau `<h3>` cassait l'ordre descendant des titres.
Bref, un coup de propre
> Accessibilité: Correction du dropdown .c-box--structure

- itou/utils/apis/metabase.py
- itou/www/stats/views.py
Pour modifier l'ancien tableau de bord par sa nouvelle version.
> Pilotage : Mise à jour du TB auto-prescription pour les DDETS/DREETS/SIAE
